### ISSUE TITLE
Sort app services by running

### ISSUE THREAD

**Issue by Pahomk** [MuntashirAkon/AppManager#1000]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Add sorting for app services by running, as was done in the similar app "MyAndroidTools".

### Describe the solution you'd like

When I open app settings and go to tab with a list of its services, I want to sort them by running.

### Describe alternatives you've considered

Sort app services by running  in "MyAndroidTools"

**Comment by MuntashirAkon** [comment]
App Manager, at present, does not have any feature where all the running services are listed. Not sure what you mean.

**Comment by Pahomk** [comment]
> App Manager, at present, does not have any feature where all the running services are listed. Not sure what you mean.

I wanted to suggest adding this feature.

**Comment by MuntashirAkon** [comment]
> I wanted to suggest adding this feature.

In that case, create a new feature request or edit this feature request to include it along with what you want, possibly, using screenshots.

**Comment by MuntashirAkon** [comment]
#1004
