### ISSUE TITLE
Uninstalled apps won't uninstall completely

### ISSUE THREAD

**Issue by HarriBuh** [MuntashirAkon/AppManager#1003]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Whenever I am uninstalling an Android system app, a shallow, 0 Byte "zombie" of the former app will always remain on my system.
It is still selectable via App Manager and I cannot delete the remains, instead there is a pop-up asking me to either reinstall or cancel the operation - I'm wondering why.

### To Reproduce

Open up App Manager
Click on  a specific app
Click "uninstall"
Refresh
Click on the just uninstalled app
Get the pop-up
Wonder

### Expected behavior

Uninstalled apps should be completely removed from the system, including any remains.

### Device info

- Device: Google Pixel 7
- OS Version: Android 13
- App Manager Version: 3.0.4
- Mode: Root

**Comment by MuntashirAkon** [comment]
Uninstall != delete. App Manager does not modify system partition, thus, does not actually delete the APK itself. It only uninstalls the app.
