### ISSUE TITLE
[Feature Request] Startup Manager

### ISSUE THREAD

**Issue by dhammel** [MuntashirAkon/AppManager#1006]
Hello,

there is one feature that I would like to see and it could replace another app I use which is to disable startup events of apps like permission RECEIVE_BOOT_COMPLETED to prevent apps from starting up with device. I know that some apps (very few in my case) end up re-enabling it somehow anyway, but it works great for most apps.

Would you consider this?

Thank you

**Comment by Pahomk** [comment]
I support this idea

**Comment by MuntashirAkon** [comment]
Duplicate of #309
