### ISSUE TITLE
Adb Shell 

### ISSUE THREAD

**Issue by nguiN2** [MuntashirAkon/AppManager#1013]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

it would be even better to implement something like adb shell inside the app manager (wireless debugging), I'm removing bloatware and some of the system apps I don't use using pm uninstall --user 0 <com.> with a pc with my phone connected

**Comment by MuntashirAkon** [comment]
You can already do the same in App Manager using batch operations and profile.

1. Create a new profile in the profiles page, add the apps you need to remove and save it
2. In the main page, filter by the profile you've just created (along with the flag _installed_)
3. Long click any item to select it
4. In the selection box at the bottom, tap on _select all_ button
5. Hit the _uninstall_ button to uninstall them all.

This is an extremely useful method in case you want to check which apps you've uninstalled in the future.
