### ISSUE TITLE
Can I add my own tracker list?

### ISSUE THREAD

**Issue by lshilshi** [MuntashirAkon/AppManager#1014]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Can I add my own tracker list?
This will block trackers with one click.
Current lists can't afford to keep up with advertisers' changes.

Block and unblock can be multi-selected？
Rather slowly when there are many candidates.

**Comment by MuntashirAkon** [comment]
> Can I add my own tracker list?
> This will block trackers with one click.
> Current lists can't afford to keep up with advertisers' changes.

If you find that some trackers are missing, you can add them via Exodus: https://etip.exodus-privacy.eu.org/. We are gradually replacing trackers with a different concept as we have found the concept of “tracker” misleading. If you're threat model is different which includes components that we do not consider as trackers, I suggest using the **block components...** feature in the 1-click ops page. See also #664.

> Block and unblock can be multi-selected？
> Rather slowly when there are many candidates.

Yes, there's an option to block trackers via the batch ops in the Main page.
