### ISSUE TITLE
Adding an application to the startup

### ISSUE THREAD

**Issue by Protey** [MuntashirAkon/AppManager#1016]
### Describe the existing feature/documentation

Hello, tell me how to add applications to startup via AppManager?

**Comment by MuntashirAkon** [comment]
> Hello, tell me how to add applications to startup via AppManager?

You can't run apps on startup via App Manager.

**Comment by Protey** [comment]
> You can't run apps on startup via App Manager.

Are you planning to add such a feature to App Manager?

**Comment by MuntashirAkon** [comment]
> Are you planning to add such a feature to App Manager?
> I think such a function is very necessary in applications such as App Manager!

Well, launching an app at startup is something automation apps such as Tasker or Automation should do. App Manager is not meant to manage automations.
