### ISSUE TITLE
SSAID_Bug

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#1025]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When Editing the SSAID of an App we aren't presented with an apply toggle,however we are presented with it if we use the random SSAID generator

### To Reproduce

1. Open Appinfo of any which uses SSAID
2. Try editing its SSAID

### Expected behavior

We should be presented with an Apply toggle just like when we use the random SSAID generator

### Screenshots

https://user-images.githubusercontent.com/72438196/224247553-c4b5e842-a073-4bff-b291-02d986e7ceeb.mp4

### Device info

- Device:RMX2061
- OS Version:A11
- App Manager Version:3.1.0-beta2-DEBUG
- Mode: Root

**Comment by kryptobolt200528** [comment]
Also encountered this:

https://user-images.githubusercontent.com/72438196/224288229-e9b0d60c-56b2-4953-979b-f7a38ff426d5.mp4

**Comment by MuntashirAkon** [comment]
Fixed in 4860b4792485e65bf54b8006564771301145ce76

**Comment by kryptobolt200528** [comment]
That was quick honestly.👍
