### ISSUE TITLE
Search in AppOps and uses permission 

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#1026]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

There is no option to search in AppOps and "uses permission" screens.

### Describe the solution you'd like

It would be great to have search in both of them as sometimes it gets a little annoying while searching for a specific permission(even though it doesn't take that much time).

**Comment by MuntashirAkon** [comment]
This feature was mistakenly removed. Re-added in e4f8c2a2632394533cae55ba360306aaf9072cb7

**Comment by kryptobolt200528** [comment]
> This feature was mistakenly removed. Re-added in [e4f8c2a](https://github.com/MuntashirAkon/AppManager/commit/e4f8c2a2632394533cae55ba360306aaf9072cb7)

Yeah i kinda had memories of it existing but thought that i had false memories 😅.
