### ISSUE TITLE
Convert to system app (replace / integrate update)

### ISSUE THREAD

**Issue by 44nony** [MuntashirAkon/AppManager#1028]
There is an option an old manager like Link2SD has: Convert an user app to system app (and also a system app to user).

Why?. You can manually download and install a system component update (like webview apk). But the new version will be shown as a user app that can be deleted. And the original app will be kept as a system app.

By converting the update to system app, you replace the old app with the update. The new version is now the original that can't be deleted with a stock app manager. And you save storage space too.

By doing the opposite (system to user) you can delete and manage the system app with the stock app manager.

Thank you.

**Comment by MuntashirAkon** [comment]
System app utilities via Magisk are currently a work in progress (see #150). But App Manager does not and will never modify the system partition. So, you won't gain anything out of this.
