### ISSUE TITLE
Describe process to share backup to other phone

### ISSUE THREAD

**Issue by R-omk** [MuntashirAkon/AppManager#1030]
### Describe your problem(s)

I want to move some apps from my old phone to a new one, both are rooted and have the latest version of the app available. I did not find a simple "Share" button for a backup and I see that the backup consists of more than one file on the disk.

Perhaps it need to open a new feature request for sharing backups.

### Additional context

[v3.0.4]

**Comment by MuntashirAkon** [comment]
You can copy the backup folder to the other phone. Then, grant storage permission/select storage in App Manager, and wait for App Manager to gather all the backups you've copied. After that, you can restore the backups.
