### ISSUE TITLE
Activities Shortcut open issue reference #1001

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#1034]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When i create App activity shortcut of user app its working but with system apps its not working.

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by kryptobolt200528** [comment]
Is the mode of operation root or adb ??

**Comment by MuntashirAkon** [comment]
I don't understand. Is this related to #1001 or the same issue?

**Comment by ParryShah** [comment]
> Is the mode of operation root or adb ??

Root mode

**Comment by ParryShah** [comment]
> I don't understand. Is this related to #1001 or the same issue?

Same issue..
I am using activity launcher from play store if dev can check that app it could be help..
That app is working with activity shortcut

**Comment by MuntashirAkon** [comment]
Duplicate of #1001
