### ISSUE TITLE
 Ability to install all self signed apps 

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#1036]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Some self signed apps cannot be installed using App manager however when installing thorough the inbuilt installer we get a play security warning and can proceed to install it.

![Screenshot_2023-03-27-22-48-30-88_7036e97d057c640af5e19886b605c25a](https://user-images.githubusercontent.com/72438196/228023198-4c3b4bda-8c00-4da9-98af-4065d16e4f59.jpg)

![Screenshot_2023-03-27-22-48-47-91_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/72438196/228023263-f6b558e7-5f3d-4ed0-bdfd-0bbe62407f79.jpg)

### Describe the solution you'd like

App manager should too provide a way to install such apps.

**Comment by MuntashirAkon** [comment]
> Some self signed apps cannot be installed using App manager however when installing thorough the inbuilt installer we get a play security warning and can proceed to install it.

This is Google installer. Not built-in AOSP installer.

**Comment by kryptobolt200528** [comment]
> > Some self signed apps cannot be installed using App manager however when installing thorough the inbuilt installer we get a play security warning and can proceed to install it.
> 
> This is Google installer. Not built-in AOSP installer.

yeah it is,my bad.Is it not possible to implement this feature?

**Comment by MuntashirAkon** [comment]
> Is it not possible to implement this feature?

Google, of course, would've never wanted any other installer to install apps in first place. The reason they allow third-party apps to install APK files is because of anti-trust issues. So, no. They don't provide any API to bypass this.
