### ISSUE TITLE
Feature to delete app remnants in case of improper uninstallation 

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#1037]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

As mentioned in a "discussion" post, somehow an app wasn't completely uninstalled,installing an updated version would fail(due to siganture issues with previous version),inbuilt app manager and play store wouldn't display app,App manager would display app and clicking on it would return "App not installed toast",long pressing it would return options ,all of them not toggeable.
![Screenshot_2023-03-26-15-53-37-84_7036e97d057c640af5e19886b605c25a](https://user-images.githubusercontent.com/72438196/228026305-d49ef42f-24b1-4c78-aec0-e52fb5965702.jpg)

However pm uninstall com.reddit.frontpage cleared all remnants

### Describe the solution you'd like

During such installtions add an option like "Clear remnants/Uninstall completely and retry".

### Additional context

Additional context:
discussion #1035

**Comment by MuntashirAkon** [comment]
As stated in 8062e58696bf0fbf8193bec2a27754960e444c05, this is a very sticky situation and needs to be handled quite carefully. This could be handled in two places:

1. Display an uninstall prompt in the Main page for user apps that were uninstalled without clearing data and signatures (for system apps, we display an option to reinstall the app). It should clearly specify that the app was uninstalled without clearing data and signatures.
2. In the installer, display an option to uninstall the previous app and install the app again like what we do when App Manager detects a typical mismatched signature.

**Comment by MuntashirAkon** [comment]
> I would like to ask,where does android exactly store the data(eg in my case the signature) of apps with the DELETE_KEEP_DATA flag?

`/data/system/packages.xml`

**Comment by kryptobolt200528** [comment]
> > I would like to ask,where does android exactly store the data(eg in my case the signature) of apps with the DELETE_KEEP_DATA flag?
> 
> `/data/system/packages.xml`

Thanks alot

**Comment by MuntashirAkon** [comment]
Implemented via 4c30b30410d3107c44523ca07dad5f951f38a5b6, 09dc2d907a71c0b1926608518e84c0bdee1a1e23 and 1fd000b9e6ec0c151578174363992faf67f03aa7
