### ISSUE TITLE
Cannot update AppManager to 3.1.0

### ISSUE THREAD

**Issue by MR-Diamond** [MuntashirAkon/AppManager#1038]
I am unable to update AppManager from 3.0.4 to 3.1.0; since on f-droid is still on 3.0.4 (why has not been updated on f-droid?) I downloaded the apk from here - github -.
As I attempt to install it I just got:

![AppManager](https://user-images.githubusercontent.com/32249442/228837243-3b85d0de-6715-4fe8-a793-ca4a3b39b660.png)

**Comment by MuntashirAkon** [comment]
You have to ask on F-Droid forum/issue tracker for help related to F-Droid. We have no control over the build cycle of F-Droid. However, nowadays F-Droid build cycle is very very slow. So, it should take about three weeks to appear there.
