### ISSUE TITLE
App freeze lag , crasher  cant touch anithink 

### ISSUE THREAD

**Issue by QPLAYid** [MuntashirAkon/AppManager#1039]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App open work but cant touch anithink is laggy , 
I run in android 13 rom miui 14

But android 12 miui 13 is normally 

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by MuntashirAkon** [comment]
You haven't specified all the required fields.
