### ISSUE TITLE
Exclude blocking trackers of am app in one click ops

### ISSUE THREAD

**Issue by chiranz135** [MuntashirAkon/AppManager#1041]
### Describe the existing feature/documentation

I wanted to exclude an apps trackers being blocked while running 1 click ops.
Can I do that?
How do I do it?

**Comment by MuntashirAkon** [comment]
After you click on the option and choose to scan system apps (or not), a dialog appears listing all the apps whose trackers would be blocked. You can search and exclude any app you like.

**Comment by chiranz135** [comment]
I was looking for a solution where I wouldn't have to deselect it everytime I do it
Something like a permanent whitelist.
Is there anything like that.

**Comment by MuntashirAkon** [comment]
> I was looking for a solution where I wouldn't have to deselect it everytime I do it Something like a permanent whitelist. Is there anything like that.

Not yet. See #664

**Comment by chiranz135** [comment]
Thank you.
