### ISSUE TITLE
Integration with Shizuku

### ISSUE THREAD

**Issue by zoroya1** [MuntashirAkon/AppManager#1042]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Currently users can use wireless debugging in App manager, but it is more of miss thing than hit.

### Describe the solution you'd like

If possible, shizuku support will elevate usability of app to great extent

### Describe alternatives you've considered

I'vr considered using Inure app manager, but it is not as user friendly as app manager, it is a bit overkill for managing apps.

**Comment by MuntashirAkon** [comment]
This feature has been asked many times in the past, in #987, #983 #55, and more. Visit one of them to understand why this isn't possible for me.
