### ISSUE TITLE
Play services app not showing up in the app list

### ISSUE THREAD

**Issue by Manupriyan** [MuntashirAkon/AppManager#1043]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I'm on A13 superior os. Everytime I disable dangerous app permissions via appops otherwise it's nearly impossible to disable permissions. So the problem is when I try to find play services. It's not showing up. All other apps are listed except this one. 
![Screenshot_20230404-171721](https://user-images.githubusercontent.com/82517944/229782949-eccbb83f-7d38-4be5-a7a5-e732666aaf1d.png)

### Logs

No crashes

### Device info

- Device: Miatoll
- OS Version: 13
- App Manager Version: 3.0.4
- Mode: Root

**Comment by kryptobolt200528** [comment]
does it normally show up in the inbuilt app manager?

**Comment by Manupriyan** [comment]
Yes it shows up in the settings  any fix?

**Comment by MuntashirAkon** [comment]
This might be related to #140 or other similar issues. Can you share some logs? It would help me confirm it.

**Comment by Manupriyan** [comment]
Sure, here it is.

**Comment by MuntashirAkon** [comment]
> Sure, here it is.

I don't see any attachments.

**Comment by Manupriyan** [comment]
I find that it depends on certain roms. Now I'm using Crdroid and I haven't seen any bugs i mentioned above. So I'm closing the issue.
