### ISSUE TITLE
AppInfoActivity/AppDetailsActivity intent filter matching issue on Android 13

### ISSUE THREAD

**Issue by cliuff** [MuntashirAkon/AppManager#1044]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

For apps targeting Android 13, e.g. AppManager 3.1.0, intents launching from outside of the app must [exactly match the intent filter](https://developer.android.com/about/versions/13/behavior-changes-all#intents) declared in `AndroidManifest`. Rules are documented in [filter rules](https://developer.android.com/reference/android/content/IntentFilter#filter-rules).

From the `AndroidManifest` source code, `AppInfoActivity` has 3 intent filters declared, all of which expect a `data`/`uri` field. Thus making an intent launch by only passing `EXTRA_PACKAGE_NAME` from a third-party app fail the intent filter rules.

Please add a new `<intent-filter>` node with all `<data>` nodes removed.

### Device info

- Device: Pixel 4
- OS Version: Android 13
- App Manager Version: 3.1.0
- Mode: Root

**Comment by MuntashirAkon** [comment]
> From the `AndroidManifest` source code, `AppInfoActivity` has 3 intent filters declared, all of which expect a `data`/`uri` field. Thus making an intent launch by only passing `EXTRA_PACKAGE_NAME` from a third-party app fail the intent filter rules.

This is an internal API, not meant to be used outside App Manager. Because like all internal APIs, they are subjected to change. If you have specific use-case for an API like this, consider requesting it via #546.
