### ISSUE TITLE
Bug : App not getting reinstall 

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#1046]
### Describe the existing feature/documentation

While reinstalling app from uninstalled list its shows "App not installed"

How to solve this??
![Screenshot_2023-04-19-15-49-21-94_7036e97d057c640af5e19886b605c25a](https://user-images.githubusercontent.com/42093168/233045737-a388049c-3ee9-44aa-98bd-e8cebb0d7802.jpg)

### Describe your problem(s)

Can't reinstall app

**Comment by MuntashirAkon** [comment]
Fixed via 4c30b30410d3107c44523ca07dad5f951f38a5b6
