### ISSUE TITLE
Complete removal of system apps

### ISSUE THREAD

**Issue by funnysith** [MuntashirAkon/AppManager#1050]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Now the app can only uninstall for one user, apk after uninstallation still remains in system. This is necessary feature for rooted devices.

**Comment by MuntashirAkon** [comment]
App Manager does not modify system partitions in any ways, and will never do so in the future. For systemless removal, see #150. If you're worried about space, install a custom ROM. SafetyNet will be broken on both cases anyway.
