### ISSUE TITLE
AppManager cannot be included in backup

### ISSUE THREAD

**Issue by A-7666** [MuntashirAkon/AppManager#1052]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

There is a bug that doesn't allow backup.

After I run Seedvault, I can see AppManager present in the "programs that do not allow backup" list.

This is very unfortunate. Could you fix this?

### To Reproduce

- Run backup in Seedvault.
- See the program present in the "programs that do not allow backup" list.

### Expected behavior

AppManager to not be present in the "programs that do not allow backup" list in Seedvault.

### Device info

- Device: <any>
- OS Version: <any AOSP>
- App Manager Version: 3.1.0(423)
- Mode: NonRoot

**Comment by MuntashirAkon** [comment]
The only thing that might be backed up in App Manager is the KeyStore that it uses internally. While we already provided an option to back up the KeyStore inside App Manager, we can also also allow Android backups. But some tests are required to find out whether the restore will actually work.

**Comment by MuntashirAkon** [comment]
Added via 1dddf8719f48a075ff8a03cfe64825378ac746fe. Not tested yet.

**Comment by MuntashirAkon** [comment]
Tested both v4.0.0-alpha01 and latest debug build. Both working with SeedVault in Lineage OS 18.1 (Android 11). Make sure you're using the correct version.

**Comment by MuntashirAkon** [comment]
This is currently an experimental feature which is only available for the testers (as you can see the milestone is set to v4.0.0-alpha01 and not v3.1.x). You need to wait for the next major release to enjoy the feature.
