### ISSUE TITLE
List Android's shared libraries

### ISSUE THREAD

**Issue by resiehnnes** [MuntashirAkon/AppManager#1053]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Periodically I am getting new version of android's System WebView in Aurora Store, but if I want the update to succeed I have to update (install a new one as it turns out) the android's Trichrome Library first, matching the same version as new System WebView. The problem is that every time I install a new Trichrome Library the old ones are staying in the system and only way to remove them is connecting my phone to PC with a cable and  run in terminal `adb shell pm uninstall com.google.android.trichromelibrary*_version_code` through ADB protocol.

There is an app you most likely know called SD Maid, which lets me to see all shared libraries which are present in my system, but it does not let me remove it because, I guess, I don't have root privilege.

So my question is, is it possible to implement feature that SD Maid has to be able to list android's shared libraries in app list + let us remove them (in my case 'com.google.android.trichromelibrary' libraries which clutters the system)

Screenshot with SD Maid showing shared libraries in App Control list:

![e9db9830-44a0-4096-960e-ad6c67865c3f](https://user-images.githubusercontent.com/52158526/235153341-2f7c2631-5f82-4d35-be66-6bec1f035c73.jpg)

**Comment by MuntashirAkon** [comment]
Added in 288e77d4e0fcab7c12401a8f022c54aa846206ed

**Comment by resiehnnes** [comment]
@MuntashirAkon Great, thanks a lot!
