### ISSUE TITLE
Logviewer

### ISSUE THREAD

**Issue by RaWolFoX** [MuntashirAkon/AppManager#1061]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Logviewer not pausing. Play/pause button do nothing. If i press pause button it changes to play button without pausing log. And if if press play button after this, button not changing back to pause. Buttons do nothing.

### To Reproduce

-1 goto logviewer
-2 press play/pause button

### Expected behavior

Log viewer should pause when pressed pause button and resume when play button press.

### Device info

- Device: OPPO A9 2020
- OS Version: Android 11 (coloros)
- App Manager Version: 3.1.0 (423)
- Mode: Both ADB and NonRoot

**Comment by MuntashirAkon** [comment]
This does not seem to be reproducible on my side.
