### ISSUE TITLE
Preventing an app from restarting after killing it

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#1067]
### Describe the existing feature/documentation

For this example, I will use the app com.duckduckgo.mobile.android. It keeps restarting, with the log showing entries such as this:

```
[05-16 15:19:40.123 474:474 I/ActivityManager]
Start proc 1819:com.duckduckgo.mobile.android/u0a146 for service com.duckduckgo.mobile.android/androidx.work.impl.background.systemjob.SystemJobService
```

In AppManager, I have disabled System Job Service (in the Services tab) - the exact one mentioned whenever the app restarts (androidx.work.impl.background.systemjob.SystemJobService)

Two questions:

1. Why doesn't disabling this service prevent the app from restarting?

2. Would you recommend any other methods to prevent apps from constantly restarting?

**Comment by 2011** [comment]
> I don't see any reason for anybody stopping an app from running in the background.

Thank you for your reply.

My biggest problem comes from the fact that so many of these apps want to run in the background, which eventually consumes all of the memory on my device. Then when I want to start a different app, it takes an inordinate amount of time to start up, and (a good percentage of the time) the memory manager will kill something like the VPN (which I don't ever want killed) instead of background applications.

I don't consider this much of a security threat (maybe a bigger privacy threat), but above all else, I hate that apps running in the background simply slow down my devices. I would prefer that when I exit an app that it stops and releases all of the memory immediately

**Comment by MuntashirAkon** [comment]
Memory management has always been problematic in Android. Vendors have made it even worse by customising it to _supposedly_ improve memory usage. If you're running an Android < 7.0, you're basically out of luck because Android does not provide any options to control per-app background operation. However, you could still limit background apps by going to Settings > Developer options > Background process limit.
