### ISSUE TITLE
Unable to install an unsigned apk

### ISSUE THREAD

**Issue by hyplant** [MuntashirAkon/AppManager#1068]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Unable to install an unsigned apk,
although installing unsigned apk has been enabled through software like com.coderstory.toolkit
The window that parses unsigned apks always flashes by and does not enter the installation process at all.
无法安装未签名的apk，
即使已经通过像com.coderstory.toolkit这样的软件被启用安装未签名的apk
解析未签名apk的窗口总是一闪而过，根本不会进入安装流程。

### To Reproduce

在文件管理器中尝试打开一个未签名的apk

### Expected behavior

install succeeded

### Device info

- Device:samsung n9760
- OS Version:12.0
- App Manager Version:3.2.0-alpha01-DEBUG (433)
- Mode: Root

**Comment by MuntashirAkon** [comment]
I'm not sure I got this correctly. Isn't the purpose of CorePatch is to disable signature verification? When you use an unsigned APK, it's not signed at all. What you can do is enable APK signing in App Manager.

**Comment by hyplant** [comment]
也许核心破解(com.coderstory.toolkit)主要不是为了安装未签名的应用，但它有个功能可以禁用系统对签名的检验，至少可以让系统自带的安装器安装未签名的应用。

**Comment by hyplant** [comment]
The corePatch (com.coderstory.toolkit) may not be primarily intended to install unsigned apks, but it have a feature that disables system verification of signatures, which allows the system installer(com.android.packageinstaller) to install unsigned apks.

**Comment by MuntashirAkon** [comment]
Fixed via e9fc8d7931af950de75e11be622f62238b59da48
