### ISSUE TITLE
No APK file generated 

### ISSUE THREAD

**Issue by Primokorn** [MuntashirAkon/AppManager#1070]
### Describe the existing feature/documentation

Hello
I tried to extract the APK file of an app thanks to the Backup APK file option from the app info page.
here is what I get...
Could you please help? Thank you.

![Screenshot_2023-05-19-12-55-55-76_07f20907771ad09ffa2dcbecf65bb740](https://github.com/MuntashirAkon/AppManager/assets/5938828/9bab890e-2e63-4f0b-8376-33b210fe2ea6)

### Describe your problem(s)

No APK generated

**Comment by MuntashirAkon** [comment]
`source.tar.gz.0` contains the APK files. **Backup APK** option is meant to be used by App Manager backup/restore feature. It's not a standalone feature. If you need to save the APK files, use **Save APK** option available within in batch operations.
