### ISSUE TITLE
Filter apps by "Stopped" status

### ISSUE THREAD

**Issue by sconim** [MuntashirAkon/AppManager#1072]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

The app doesn't currently offer a way to filter apps by the "Stopped" status. This is typically indicated by a turquoise colored bar in the app list and it's not the same status as "Disabled" or "Frozen".

### Describe the solution you'd like

Add a "stopped" filter to the list of existing filters. 

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by jstetten** [comment]
Specifically, force-stopped apps, would be the most useful, for me at least.

Thinking about it further...the most useful option of all would be to filter, or at least sort, by apps that've restarted themselves *after* being force-closed. Perhaps it would be easier to add a filter/sort of apps with running services instead, which would also be helpful and would save at least my most frequent reason for opening developer options.

**Comment by sconim** [comment]
> Specifically, force-stopped apps would be the most useful, for me at least.
> 
> Thinking about it further...the most useful option of all would be to filter, or at least sort, by apps that've restarted themselves _after_ being force-closed. Perhaps it would be easier to add a filter/sort of apps with running services instead, which would also be helpful and would save at least my most frequent reason for opening developer options.

"Stopped" is the name used by the app but, yes, "Forced-stopped" is exactly what I meant. Ditto on filtering/sorting apps that restarted after being forced-stopped. 
![Uploading Screenshot_20230526_213421_App Manager.jpg…]()

**Comment by MuntashirAkon** [comment]
> Thinking about it further...the most useful option of all would be to filter, or at least sort, by apps that've restarted themselves _after_ being force-closed.

The Linux equivalent for `kill` is `force-stop` in Android VM. There's no point in logging the starting of such apps.

> Perhaps it would be easier to add a filter/sort of apps with running services instead, which would also be helpful and would save at least my most frequent reason for opening developer options.

There's already such option present in privileged mode.

**Comment by MuntashirAkon** [comment]
Note that the Main page always presents a cached version of the apps to improve speed (otherwise, it would take a lot of time to display the list). This also means that these temporary status would not be much reliable.

**Comment by MuntashirAkon** [comment]
Added in 5fa9fb08c7bfa5281a8c229b86b9d885005a3d7a
