### ISSUE TITLE
Refresh not working on latest debug builds

### ISSUE THREAD

**Issue by Rokcy98** [MuntashirAkon/AppManager#1074]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I can't refresh the applist with latest debug builds 2355 and 2356, with 2354 and previous versions everything works.
I've tried resetting the app too

### Device info

- Device:
- OS Version: A13
- App Manager Version:
- Mode: Root

**Comment by HashLiver** [comment]
same problem in 3.1.1

**Comment by MuntashirAkon** [comment]
You need to share some logs taken during the refreshing process. Chances are that an unknown issue is preventing the application information loader from retrieving app list.

**Comment by MuntashirAkon** [comment]
Closed due to a lack of response. Feel free to open it again if you're still facing the issue.
