### ISSUE TITLE
edit the path in file explorer

### ISSUE THREAD

**Issue by hyplant** [MuntashirAkon/AppManager#1076]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

The file path in file explorer is editable.
You can open any path in it.

**Comment by MuntashirAkon** [comment]
Implemented in 61cb37b70483b298272c15f822ae708a35b6a3d2
