### ISSUE TITLE
Block trackers

### ISSUE THREAD

**Issue by Sergei-Alekseev** [MuntashirAkon/AppManager#1077]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Device is Sony Xperia Z3 Compact, Android 6.0.1, off. firmware, SuperSU.
Latest stable AppManager.
Can't block trackers at all. 
"Rules not applied" message if trying to block individual tracker or pressing "Apply rules" in menu.

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by sco-gar** [comment]
+1 on Surface Duo 2/Android 12. Worked initially, now only errors, rules are not applied.

**Comment by MuntashirAkon** [comment]
You need to find a way to reproduce the issue.

**Comment by MuntashirAkon** [comment]
This issue is now tracked via #1071
