### ISSUE TITLE
App deleted long ago still show up

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#1082]
### Describe your problem(s)

I (vaguely) remember the mess with the trichromelibrary a couple of years ago (not any of the details, though), and AppManager still shows remnants of that debacle.

On one device (an Android 10 phone), AppManager (3.1.0) displays (in the list of apps):
com.google.android.trichromelibrary_438910534
com.google.android.trichromelibrary_443006634
com.google.android.trichromelibrary_443008234
com.google.android.trichromelibrary_443009134

All four of these have red bars on the left, and selecting any of them will (of course) display an "App not installed" message. Does some way exist to remove these entries from the list of apps?

**Comment by MuntashirAkon** [comment]
Not sure if this related to #1054. The handling of static libraries was quite complicated and I've forgot most of the details. Can you try the latest debug and report? It's always possible that the remnants still remained (or that App Manager was only dreaming).

**Comment by 2011** [comment]
Installed AppManager_v3.2.0-alpha01-DEBUG#2378.  The four trichromelibrary entries still show up in the app list.

**Comment by MuntashirAkon** [comment]
Run `pm uninstall com.google.android.trichromelibrary_443009134` in privileged mode, and see if this package is still there (you may have to wait for some time to update the cached apps in App Manager).

**Comment by 2011** [comment]
```
/ # pm uninstall com.google.android.trichromelibrary_443009134
Success
/ # pm uninstall com.google.android.trichromelibrary_443008234
Success
/ # pm uninstall com.google.android.trichromelibrary_443006634
Success
/ # pm uninstall com.google.android.trichromelibrary_438910534
Success
```

:)

Seems like something didn't get updated correctly at some point in the past. AppManager no longer shows any trichromelibrary entries in the app list. Thank you so much.

**Comment by MuntashirAkon** [comment]
There's something definitely wrong with those packages. App Manager should've offered you to uninstall those packages instead of displaying “App not installed.”
