### ISSUE TITLE
Improve runtime optimization

### ISSUE THREAD

**Issue by Rokcy98** [MuntashirAkon/AppManager#1083]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

It would be nice if you added the runtime optimization option to the multi-selection panel. At the moment, you can either optimize one app at a time, or you can optimize every app through "one-click operations": it would be nice to have the ability to choose only the app you want to optimize

### Describe the solution you'd like

Select some apps --> optimize runtime in the bottom panel

**Comment by MuntashirAkon** [comment]
Implemented in c7c24eb4fa60c0a985f7168eea0cfa79b4fe53bf
