### ISSUE TITLE
Can't press Agree to start the app

### ISSUE THREAD

**Issue by Stemp123** [MuntashirAkon/AppManager#1084]
### Describe the existing feature/documentation

The background flashes and nothing happens when i press "Agree". What's up with that? 

I can't use APK editor X pro either, just crashes when i choose full edit. Maybe it's something with my phone.

### Additional context

Nothing Phone - Android 13

**Comment by MuntashirAkon** [comment]
You said it might be an issue with your phone but didn't include any spec.

**Comment by FriesI23** [comment]
I stuck at this dialog either
![Screenshot_2023-06-09-09-53-05-504_io.github.muntashirakon.AppManager.jpg](https://github.com/MuntashirAkon/AppManager/assets/20661034/37171754-176b-43c6-a3d3-3ec666fc961e)

my device is xiaomi 13 with miui14.0.24 (android 13), no root on my device

**Comment by bukiru** [comment]
hi, I have this bug also. I've tried different versions, from 3.1.0-beta01 to latest beta v4.0.0-alpha01. and only 3.1.0-beta01 works correctly. every update freezes. the newly version I install - the large time for lags it takes. on v.4 also I have android permissions controller crash..
my phone is Poco X3 Pro, RisingOS, rooted, A13

**Comment by MuntashirAkon** [comment]
Please, install a debug version and send some logs.
