### ISSUE TITLE
Backup cache option does not save

### ISSUE THREAD

**Issue by HanabishiRecca** [MuntashirAkon/AppManager#1086]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

"Settings > Backup/Restore > Backup Options > Cache" option does not save its state and resets on app exit.

### To Reproduce

1. Go to "Settings > Backup/Restore > Backup Options".
2. Disable "Cache" option.
3. Click "Save".
4. Relauch the app, the option will appear enabled again.

### Expected behavior

The option state should be saved.

### Device info

Reproducible on 3.1.0 and 3.1.1.

**Comment by MuntashirAkon** [comment]
Fixed in 31e96ffc8f1c97c4bfc75b5e0b05c6af55019f77
