### ISSUE TITLE
Doesn't show any running apps

### ISSUE THREAD

**Issue by HuyMaster** [MuntashirAkon/AppManager#1093]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

In the running apps page, it only shows the memory, not the running application

### To Reproduce

- 1.  Click on '3 dots' on the top right
- 2. Select the 'running apps' item

*Note: I don't know if it's only my device that has the bug or other devices have it too*

### Screenshots

![Screenshot_2023-06-12-12-06-40-675_io github muntashirakon AppManager](https://github.com/MuntashirAkon/AppManager/assets/80255843/01aeead4-4180-4db7-b1b0-ec709b614fa9)

### Device info

- Device: Mi 11 Lite(coubert)
- OS Version: MiUI 14 global [T]
- App Manager Version: 3.1.1(424)
- Mode: Root

**Comment by MuntashirAkon** [comment]
You need to share some logs from the debug version.

**Comment by MuntashirAkon** [comment]
Closed due to a lack of response. Feel free to open it again if you're still facing the issue.

**Comment by HuyMaster** [comment]
I switched to EvolutionX and the function worked fine
