### ISSUE TITLE
reversing "prevent background operation"

### ISSUE THREAD

**Issue by Mobasheera** [MuntashirAkon/AppManager#1098]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Is there a way to reversing "prevent background operation" to let an app run in the backgroud. I by mistake clicked on prevent background operation and now I am not able to find a way to undo it. Please help. Thankyou.

**Comment by MuntashirAkon** [comment]
The answer was already there. You just didn't pay enough attention. This is what comes up when you click on that option:

<img src=https://github.com/MuntashirAkon/AppManager/assets/8176128/d79adbc7-c941-4be1-b620-c55cbd7b2a78 width=400 />

**Comment by Mobasheera** [comment]
Yes I do agree with what you said, there's an additional dialog box for safety and confirmation. But my question is, is there a way to reverse this change? by reinstalling the app or running an adb command from a computer....or any other method? Thank you.

**Comment by MuntashirAkon** [comment]
Go to the App Ops tab for the relevant apps in the App Details page and set those values to either **allow** or **default**.

**Comment by Mobasheera** [comment]
reverting these two toggle switches will revert the change right?
![image](https://github.com/MuntashirAkon/AppManager/assets/83943245/fa4ee4e9-cb6b-47a6-8984-11fccd5f92ed)

**Comment by MuntashirAkon** [comment]
Correct.

**Comment by Mobasheera** [comment]
Thank you so much!:)
