### ISSUE TITLE
Crashes when selecting App Usage in menu

### ISSUE THREAD

**Issue by DrizztFR** [MuntashirAkon/AppManager#11]
Hello,

When clicking on the three dots menu on the top right and selecting "App Usage", Appmanager immediately closes. It happens with or without the permission needed.

Here is a log I found just before force-crash :

06-10 00:25:00.924 I/am_crash(1345): [15612,0,io.github.muntashirakon.AppManager,815283780,java.lang.NoSuchMethodError,No virtual method unsafeCheckOpNoThrow(Ljava/lang/String;ILjava/lang/String;)I in class Landroid/app/AppOpsManager; or its super classes (declaration of 'android.app.AppOpsManager' appears in /system/framework/framework.jar),AppUsageActivity.java,184]

I'm on LineageOS without GApps, using fresh installed fdroid version. 

Thank you for your work, it's cool to have everything in one place with a cool design!

**Comment by MuntashirAkon** [comment]
Until I release the new update, you can use this: [AppManager_v2.4.4 (100).apk.zip](https://github.com/MuntashirAkon/AppManager/files/4755451/AppManager_v2.4.4.100.apk.zip)
