### ISSUE TITLE
Light theme when activity opened from external link

### ISSUE THREAD

**Issue by opusforlife2** [MuntashirAkon/AppManager#110]
**Describe the bug**
App Manager provides options like App Info and Manifest Viewer for apk files. Opening them doesn't follow the dark theme set in app settings, but shows light theme instead.

**To Reproduce**

1. Go to any folder containing an apk.
2. Open it in Manifest Viewer or App Info.
3. They open in light theme instead of dark.

**Expected behavior**
Dark theme even when opening activities from external links.

**Device info**
 - App Manager Version: v2.5.13

**Comment by MuntashirAkon** [comment]
Fixed in v2.5.14.
