### ISSUE TITLE
Problem? 

### ISSUE THREAD

**Issue by Gabriellokoh** [MuntashirAkon/AppManager#1101]
### Describe the existing feature/documentation

I'm on Android 13 (miui 14) in the notifications says it's stopped, but in the app always gives this error shown in the image below someone can help me? Need to enable USB debugging? Install via USB or not? 

### Describe your problem(s)

Not connecting 
![Screenshot_2023-06-16-19-44-48-871_io github muntashirakon AppManager](https://github.com/MuntashirAkon/AppManager/assets/108633186/612f97c3-fc41-487b-812c-e8d577c2cb7d)
![Screenshot_2023-06-16-19-45-14-858_com android settings-edit](https://github.com/MuntashirAkon/AppManager/assets/108633186/d2101829-fa9b-44b7-9b99-f5aa4b1b5fb5)

**Comment by MuntashirAkon** [comment]
For starters, have you read the docs linked in the message? You need to enable additional settings in **Developer options**.

**Comment by Gabriellokoh** [comment]
Is it logical that I did that, didn't see what I said? It's all activated!

Em dom., 18 de jun. de 2023 11:10, Muntashir Al-Islam <
***@***.***> escreveu:

**Comment by Gabriellokoh** [comment]
> 

Regarding "documentation" I click on the word marked blue only nothing happens. It doesn't work for me.

**Comment by MuntashirAkon** [comment]
Here's the link given there: https://muntashirakon.github.io/AppManager/#subsec:enable-usb-debugging

**Comment by MuntashirAkon** [comment]
Fixed clicking not working via fa6d6de6bd6e04faf1037148c3d94f6464aabc0f
