### ISSUE TITLE
1 click ops block trackers never starts

### ISSUE THREAD

**Issue by famewolf** [MuntashirAkon/AppManager#1102]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Did a fresh CLEAN install of crdroid on the oneplus 7 pro from xda-developer.com.  Installed app manager from f-droid.  Ran it and selected 1 click ops..tried both with enabling system apps and without...block all trackers...job showed it was starting but didn't appear in the pull down panel like normally and never got a completion response.  I ran matlog and saved the zip.

[logs-2023-06-17-02-59-31.zip](https://github.com/MuntashirAkon/AppManager/files/11778173/logs-2023-06-17-02-59-31.zip)

### Device info

- Device: Oneplus 7 Pro
- OS Version: crdroid/android 13
- App Manager Version: f-droid
- Mode: Root/Magisk 26.1

**Comment by MuntashirAkon** [comment]
The logs aren't from App Manager. You need to take logs from App Manager from the moment you visited 1-click ops page.

**Comment by BigKananga** [comment]
I had the same problem on my Samsung GT-N5110 on unofficial LineageOS 16 (Android 9) and Magisk 24.1 with versions 3.1.1 and 3.1.2. The current alpha is working fine.

**Comment by MuntashirAkon** [comment]
Closed due to a lack of response. Feel free to open it again if you're still facing the issue.
