### ISSUE TITLE
Installer package name spoofing won't work on Android 13

### ISSUE THREAD

**Issue by yephny** [MuntashirAkon/AppManager#1116]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

An app that I'd like to use employs a check (whether it was installed by com.android.vending) that causes the app to crash if it was installed by any other installer. To get it to work, I installed Fake Store and set it accordingly in the App Manager Installer settings to spoof com.android.vending. After I installed the app, "Installer app" changed when I checked it from App Manager but the app kept crashing and it said the actual installer package name was null in the crash log.

### To Reproduce

1. Find an app that checks the integrity and security of your device through installer package name.
2. Enable Installer in App Manager and change the installer package name to com.android.vending. You can install Fake Store also.
3. Install the app through App Manager.
4. Launch the app to see if the trick has worked.

### Expected behavior

Installed app is tricked into taking the spoofed installer package name as the actual installer.

### Logs

`
Installed from an unsecure source. Expected installer package names: [com.android.vending]. Actual installer package name: null
`

### Device info

- OS Version: Android 13, LineageOS
- App Manager Version: 3.1.1
- Mode: Root

**Comment by MuntashirAkon** [comment]
Nothing regarding installer package has been changed since Android 11. I think this is something to do with this particular package checking for originating or initiating package instead of installer package. Since Android does not provide a way to set those values, nothing could be done on that regard other than intercepting it with zygisk/Xposed/Frida which is beyond this project.

Also, this is not a _trick_ as you have implied. This feature is provided by Android framework itself.

**Comment by yephny** [comment]
@MuntashirAkon Thank you for your answer. I see that it's beyond this project as you said but I still haven't been able to find a solution to this. Would you mind elaborating what you meant by intercepting it with Zygisk? I have Magisk, so that could work, it's just that I didn't quite get what you meant. For reference, I have already everything about this app enabled in DenyList.
