### ISSUE TITLE
VirusTotal not working

### ISSUE THREAD

**Issue by AndiDink00x** [MuntashirAkon/AppManager#1117]
### Describe your problem(s)

VirusTotal does not work on my app. I tried both stable and debug apps, check multiple times the api key and still after i scan an app no display of VirusTotal
https://imgur.com/a/avWvLQq

### Additional context

AppManager latest debug build
LOS19.1- Android 12.1
Poco X3 Pro

**Comment by MuntashirAkon** [comment]
Make sure you've enabled Internet in Settings > Appearances > Enable/disable features.
