### ISSUE TITLE
Xposed Apps

### ISSUE THREAD

**Issue by sleeping3119** [MuntashirAkon/AppManager#1120]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

I believe it would be beneficial to have a filter and label for Xposed module apps in the app manager. Currently, if Lsposed is not installed, I have no way to filter Xposed apps unless I install Lsposed detectors. Would it be possible to consider implementing this feature?

### Describe alternatives you've considered

if you don't find it necessary than please tell me the way that how can i differentiate between xposed modules and other apps in terminal with su

**Comment by MuntashirAkon** [comment]
There's already all the framework present in App Manager, and a tag will be present in the app info tab very soon. But adding it to the main page will take some time.

> if you don't find it necessary than please tell me the way that how can i differentiate between xposed modules and other apps in terminal with su

Apps can do this by reading a metadata namely `xposedmodule` from the AndroidManifest of an app which can be possible with tools like `aapt`.
