### ISSUE TITLE
Page going one step back on toggling pure black mode

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#1122]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Just read the title. And attaching a video.

https://github.com/MuntashirAkon/AppManager/assets/83750299/f6d3467e-56a0-4bdb-8627-096525e0b5fd

### Device info

- Device: 12345
- OS Version: 13
- App Manager Version: AM Debug v3.2.0-alpha01 Run#2506
- Mode: Root

**Comment by MuntashirAkon** [comment]
When you change the theme configuration, the activity is automatically restarted to reflect the changes which is causing the issue. I'll see what I can do.

**Comment by MuntashirAkon** [comment]
Fixed via 14d1784193624a89eabf4bb97fd9f44757440dd9
