### ISSUE TITLE
Crashing when "go to.." is just a string without slash 

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#1123]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Just watch the video, and attaching a crash log.

https://github.com/MuntashirAkon/AppManager/assets/83750299/07b85ac6-f9cd-413b-ae1f-2b28e64886ec

Here is crash - https://pastebin.com/23w2Xt9w

### Device info

- Device: Check logs
- OS Version: check logs
- App Manager Version: latest debug
- Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed via 5134461cdfe088f5b51977a38275d9a1ff0b2a26 and 955c228cd4c579ab3100164a402b9dd1027aee5c
