### ISSUE TITLE
Use setPackageSource() API

### ISSUE THREAD

**Issue by ghost** [MuntashirAkon/AppManager#1126]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Google in Android 13 has made API(s) like Accessibility service(s) unavailable to apps not installed via a Session-based package installer, unless the User enables 'restricted settings' for an app in App Info Page settings.

App Manager currently does not use the setPackageSource() API to tell the system that an APK is user-acquired, which could be dangerous because an App installed via App Manager could trick users into enabling Accessibility service for it.

### Describe the solution you'd like

App Manager should use Android’s new setPackageSource() API to tell the system that the app came from a user-acquired APK via the parameters PACKAGE_SOURCE_LOCAL_FILE or PACKAGE_SOURCE_DOWNLOADED_FILE. This can be used by apps implementing the session-based package installation API to trigger the same behavior when sideloading arbitrary APK files.

**Comment by MuntashirAkon** [comment]
Several app stores support installing apps through App Manager. So, your suggestions cannot be implemented on their own.

**Comment by MuntashirAkon** [comment]
> App Manager currently does not use the setPackageSource() API to tell the system that an APK is user-acquired, which could be dangerous because an App installed via App Manager could trick users into enabling Accessibility service for it.

Is there any resources to back this claim. I've looked into the AOSP source code and found no evidence of any reliance on this information to do _anything_. It appears to be only used for documenting purposes for now.

**Comment by notahomosapien** [comment]
> Several app stores support installing apps through App Manager.

I don't know much about this, but If this is the case, Can't those app stores tell App Manager to pass PACKAGE_SOURCE_STORE parameter to PackageInstaller?

**Comment by MuntashirAkon** [comment]
Implemented via 5d39b8ac36add24d44d8b89ceaf4b72b7e6cb89d

**Comment by MuntashirAkon** [comment]
Implemented via 5d39b8ac36add24d44d8b89ceaf4b72b7e6cb89d
