### ISSUE TITLE
change the notification alert type

### ISSUE THREAD

**Issue by mexon86** [MuntashirAkon/AppManager#1128]
### Describe your problem(s)

idk how this app work and what it can do but can i change the notification alert style of the system ui , i just want get minimize notification for dnd mode but it is blocked in phone settings it cant be changeable so is this app can change it

**Comment by MuntashirAkon** [comment]
> idk how this app work and what it can do but can i change the notification alert style of the system ui

It can't.

> i just want get minimize notification for dnd mode but it is blocked in phone settings it cant be changeable so is this app can change it

If you can find the name of the setting, I think you can do it using [SetEdit](https://github.com/MuntashirAkon/SetEdit).
