### ISSUE TITLE
Remove notification permission removed fron app install dialog

### ISSUE THREAD

**Issue by ZenerDeveloper** [MuntashirAkon/AppManager#1132]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Currently when an app targeting a version before api 33 android 13 is installed, android automatically adds the post_notification permission. All this works fine but when app manager tries to update it, it will always show -android.permission.POST_NOTIFICATION on the installer (see below).

### Describe the solution you'd like

It would be nice if the installer checked
1) are you running android 13+
2) is the app targeting <api 33
And don't show the permission being removed since it will just be re added by the system when the app updates and it causes a little bit of confusion.
If the app targets api 33+ and it doesn't have the permission then show it being removed since the system won't add it on those versions.

### Additional context

![Screenshot_20230722_210001_App Manager](https://github.com/MuntashirAkon/AppManager/assets/80724816/2adb7213-0410-4783-a108-78e53c0e0f32)

**Comment by MuntashirAkon** [comment]
Thanks for reporting. I'm still on A11 which is why I missed this particular issue.

**Comment by MuntashirAkon** [comment]
App Manager currently retrieves permission info from the system. If the system adds the permission, App Manager will report it. It's not possible to fix this in the current system since there's no way to know if the app has declared it in its own manifest. When App Manager will have its own package parser, these issues will be fixed automatically.

**Comment by MuntashirAkon** [comment]
It turns out it was actually an AOSP issue which they have since fixed.
