### ISSUE TITLE
All "Running Apps" not shown

### ISSUE THREAD

**Issue by Nzzyme** [MuntashirAkon/AppManager#1133]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

On the "Running Apps" page, all apps that are running in the background are not listed. 

### To Reproduce

1. Open AM
2. From Menu, go to 'Running Apps' page.
3. I only see three entries related to App Manager itself.

It should have shown all the other apps that are currently running in the background. I know for sure there are others which I have locked in the memory in order to prevent Android from killing them.

### Expected behavior

The "Running Apps" page should display ALL the apps that are currently running in the background. Further views/filters can be added to only show the list of running Activities, Services, Receivers, Providers, etc...

### Device info

- Device: Poco M5
- OS Version: MIUI 13.0.12 (Android 12)
- App Manager Version: v4.0.0-alpha01
- Mode: NonRoot

### Additional context

On the main homepage of AM, I checked by selecting the filter as "Running apps" and the "Sort" option as "App label" but still it just shows me AM in the filtered results.

**Comment by MuntashirAkon** [comment]
App Manager does not have enough permission to fetch and list other applications.

> On the main homepage of AM, I checked by selecting the filter as "Running apps" and the "Sort" option as "App label" but still it just shows me AM in the filtered results.

You could grant App Manager `android.permission.DUMP` permission via ADB which will list running applications in the main page.

**Comment by Nzzyme** [comment]
> App Manager does not have enough permission to fetch and list other applications.
> 
> > On the main homepage of AM, I checked by selecting the filter as "Running apps" and the "Sort" option as "App label" but still it just shows me AM in the filtered results.
> 
> You could grant App Manager `android.permission.DUMP` permission via ADB which will list running applications in the main page.

Well, maybe I could but that seems to be more of an additional workaround step. I just Googled and found [this](https://stackoverflow.com/questions/3304685/how-to-get-the-list-of-running-applications)

Are you not able to include such a functionality?
