### ISSUE TITLE
Crashes when tapping on any app 

### ISSUE THREAD

**Issue by wilberfan** [MuntashirAkon/AppManager#1135]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App opens to main screen.  Tapping on any app displays the app info screen for a second or so before crashing.  "App Manager has just crashed.  Tap to submit crash report." message is displayed. 

### To Reproduce

-1. Open App Manager
-2. Click on any app

### Expected behavior

App info screen stays open, allowing options to be selected, etc. 

### Logs

[crash.report.txt](https://github.com/MuntashirAkon/AppManager/files/12196333/crash.report.txt)
[file_1765734019018160798.zip](https://github.com/MuntashirAkon/AppManager/files/12196353/file_1765734019018160798.zip)

### Device info

- Device:  Pixel 7 Pro
- OS Version: Android 14 beta 4 
- App Manager Version: 3.1.1
- Mode: Root

### Additional context

Began after upgrading to Android 14 beta 4.

**Comment by MuntashirAkon** [comment]
Stable version does not yet support Android 14. You need to use the latest prerelease.

**Comment by wilberfan** [comment]
I should have thought to try that.  Thanks so much.  The pre-release is installed and seems to be working fine.
