### ISSUE TITLE
Uninstall apps and keep data

### ISSUE THREAD

**Issue by muhammadbahaa2001** [MuntashirAkon/AppManager#1140]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Uninstall apps and keeping it's data is a feature introdced in Android 10 and it doesn't support all apps only some apps, and it's up to the developer to decide if app supports this, but it works on all Android versions and any app using ADB caommands.

### Describe the solution you'd like

Option to keep data when uninstall an app.

### Describe alternatives you've considered

If this is impossible, so it should work at least in Terminal in App Manager.

**Comment by MuntashirAkon** [comment]
The feature is already present in App Manager from the beginning. When you click uninstall in App Info tab, depending on permissions you've granted, App Manager will display an option to keep data and signatures before uninstalling the app.
