### ISSUE TITLE
Old tablet, root asked but not used

### ISSUE THREAD

**Issue by Werve** [MuntashirAkon/AppManager#1142]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

This older SM-P905 tablet has Android 5 Stock and supports up to Magisk 20.2 (boot partition size too small). 
When starting the App Manager, it asks for root permissions and I confirm with Magisk but the app still uses the no root mode, both by setting the automatic mode and by forcing the root one. 
Attached are the logs. 
Is it not compatible with Magisk 20.2?

### To Reproduce

1 Open App Manager 
2 Allow root privileges (Magisk 20.2 , Magisk Manager 8.0.7 )
3 App Manager use the no root mode

### Expected behavior

App Manager use the root mode

### Logs

deleted

### Device info

- Device: Samsung Galaxy Note Pro SM P905
- OS Version: Android 5.0.2 Stock
- App Manager Version: 3.1.1 (424) latest fdroid Release version
- Mode: Root

**Comment by MuntashirAkon** [comment]
These logs were taken _after_ App Manager was started. You need to take logs before App Manager was started. Logs should also be systemwide so that I can read the <abbr title="Interprocess communication">IPC</abbr> logs to see what's preventing it from creating a remote service.

App Manager also does not care about which `su` you're using, it will work as long as it is rooted properly (ie. full root, not partial root).

**Comment by Werve** [comment]
Ok, I should have got all the logs now. 
Rooting was done the usual way, by flashing magisk 20.2 zip from twrp.
[am_log_file_230808.zip](https://github.com/MuntashirAkon/AppManager/files/12289375/am_log_file_230808.zip)

**Comment by MuntashirAkon** [comment]
You need to take logs using a debug version of App Manager (i.e. AM Debug) to discover the exact point where it failed.

**Comment by Werve** [comment]
Ok, sorry if i'm not very good at collecting logs. 
I used AppManager_v4.0.0-alpha01-DEBUG#2527 found on telegram because on github it's expired.
[logs-2023-08-17-13-48-26.zip](https://github.com/MuntashirAkon/AppManager/files/12369264/logs-2023-08-17-13-48-26.zip)

**Comment by MuntashirAkon** [comment]
> Ok, sorry if i'm not very good at collecting logs.

No, you did good. Earlier it just missed the debug logs because the release was not a debug one.

```

08-17 13:46:43.126 D/Runner  (26650): RootShell
08-17 13:46:43.126 D/RunnerUtils(26650): PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
08-17 13:46:43.146 D/RunnerUtils(26650): SU(file=/sbin/su, exists=true, executable=true)
08-17 13:46:43.146 E/ModeOfOps(26650): null
08-17 13:46:43.146 E/ModeOfOps(26650): java.lang.Exception: Root is unavailable.
08-17 13:46:43.146 E/ModeOfOps(26650): 	at io.github.muntashirakon.AppManager.settings.Ops.init(Ops.java:237)
08-17 13:46:43.146 E/ModeOfOps(26650): 	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel.lambda$setModeOfOps$0$io-github-muntashirakon-AppManager-settings-SecurityAndOpsViewModel(SecurityAndOpsViewModel.java:75)
08-17 13:46:43.146 E/ModeOfOps(26650): 	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel$$ExternalSyntheticLambda3.run(D8$$SyntheticClass)
08-17 13:46:43.146 E/ModeOfOps(26650): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
08-17 13:46:43.146 E/ModeOfOps(26650): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-17 13:46:43.146 E/ModeOfOps(26650): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-17 13:46:43.146 E/ModeOfOps(26650): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-17 13:46:43.146 E/ModeOfOps(26650): 	at java.lang.Thread.run(Thread.java:818)
```

This is probably happening due to:

```
08-17 13:46:43.036 D/LIBSU   (26650): 
08-17 13:46:43.036 D/LIBSU   (26650): java.io.IOException: Shell check timeout
08-17 13:46:43.036 D/LIBSU   (26650): 	at com.topjohnwu.superuser.internal.ShellImpl.<init>(ShellImpl.java:116)
08-17 13:46:43.036 D/LIBSU   (26650): 	at com.topjohnwu.superuser.internal.BuilderImpl.build(BuilderImpl.java:148)
08-17 13:46:43.036 D/LIBSU   (26650): 	at com.topjohnwu.superuser.internal.BuilderImpl.build(BuilderImpl.java:136)
08-17 13:46:43.036 D/LIBSU   (26650): 	at com.topjohnwu.superuser.internal.BuilderImpl.build(BuilderImpl.java:112)
08-17 13:46:43.036 D/LIBSU   (26650): 	at com.topjohnwu.superuser.internal.BuilderImpl.build(BuilderImpl.java:34)
08-17 13:46:43.036 D/LIBSU   (26650): 	at io.github.muntashirakon.AppManager.runner.NormalShell.<init>(NormalShell.java:23)
08-17 13:46:43.036 D/LIBSU   (26650): 	at io.github.muntashirakon.AppManager.runner.Runner.getRootInstance(Runner.java:95)
08-17 13:46:43.036 D/LIBSU   (26650): 	at io.github.muntashirakon.AppManager.runner.RunnerUtils.isAppGrantedRoot(RunnerUtils.java:105)
08-17 13:46:43.036 D/LIBSU   (26650): 	at io.github.muntashirakon.AppManager.runner.RunnerUtils.isRootGiven(RunnerUtils.java:91)
08-17 13:46:43.036 D/LIBSU   (26650): 	at io.github.muntashirakon.AppManager.settings.Ops.hasRoot(Ops.java:271)
08-17 13:46:43.036 D/LIBSU   (26650): 	at io.github.muntashirakon.AppManager.settings.Ops.init(Ops.java:236)
08-17 13:46:43.036 D/LIBSU   (26650): 	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel.lambda$setModeOfOps$0$io-github-muntashirakon-AppManager-settings-SecurityAndOpsViewModel(SecurityAndOpsViewModel.java:75)
08-17 13:46:43.036 D/LIBSU   (26650): 	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel$$ExternalSyntheticLambda3.run(D8$$SyntheticClass)
08-17 13:46:43.036 D/LIBSU   (26650): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
08-17 13:46:43.036 D/LIBSU   (26650): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-17 13:46:43.036 D/LIBSU   (26650): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-17 13:46:43.036 D/LIBSU   (26650): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-17 13:46:43.036 D/LIBSU   (26650): 	at java.lang.Thread.run(Thread.java:818)
08-17 13:46:43.036 D/LIBSU   (26650): Caused by: java.util.concurrent.TimeoutException
08-17 13:46:43.036 D/LIBSU   (26650): 	at java.util.concurrent.FutureTask.get(FutureTask.java:176)
08-17 13:46:43.036 D/LIBSU   (26650): 	at com.topjohnwu.superuser.internal.ShellImpl.<init>(ShellImpl.java:107)
08-17 13:46:43.036 D/LIBSU   (26650): 	... 17 more
08-17 13:46:43.036 D/BUILDER (26650): exec sh
```

This usually means that App Manager is unable to create a shell environment in your device. I have no idea why.

**Comment by Werve** [comment]
If I remember correctly, among the apps I had tried on this device only App Manager showed difficulty with root permissions.
Mixplorer, Matlog (which I initially used to capture the log), Titanium Backup, and others I do not recall had errors.

If more information or tests are needed to help find the cause I can try to send them.
Perhaps checking to see if a shell environment like Termux is working might help? (I don't remember on this device)

**Comment by MuntashirAkon** [comment]
> If I remember correctly, among the apps I had tried on this device only App Manager showed difficulty with root permissions.
> Mixplorer, Matlog (which I initially used to capture the log), Titanium Backup, and others I do not recall had errors.

App Manager uses [libsu](https://github.com/topjohnwu/libsu) library to execute shell commands from where the errors seem to be emitted.

**Comment by Werve** [comment]
I quick tested all the App Manager release apk on Github. Means I tried opening an app info, manifest, show app shared prefs, and open the Running Apps page.
2.0 to 2.5.4  - Somewhat it works, but error at some manifest app
2.5.4 to 2.5.11 - Unstable/unusable even with Root off option
2.5.12 to 2.5.13 - _opening an app info, manifest, show app shared prefs:_ OK , Running Apps page show blank.
2.5.17 to 2.5.20 - even Running Apps page works!
2.6.0 to 2.6.5.1 - _opening an app info, manifest, show app shared prefs:_ OK , Running Apps page show blank (again).
3.0.0 to 4.0.0 alpha latest - Even with root option it switch to no-root mode.

**Comment by MuntashirAkon** [comment]
Thanks for testing all those versions. As I said, this is clearly something to do with the libsu library. I'll try to implement that part without using libsu to see what happens.

**Comment by BigKananga** [comment]
I had the same problem on my Samsung GT-N5110 on unofficial LineageOS 16 (Android 9) and Magisk 24.1 with versions 3.1.1 and 3.1.2. The current alpha is working fine.

**Comment by MuntashirAkon** [comment]
@Werve: Can you test with latest alpha (v4.0.0-alpha02)? I don't remember altering anything, but there's no harm in trying.

**Comment by Werve** [comment]
Tried the current v4.0.0-alpha02 but it has the same behavior, problem not fixed.
I taked the log, just in case they could be useful.
[logs-2023-09-22-20-18-47.zip](https://github.com/MuntashirAkon/AppManager/files/12703597/logs-2023-09-22-20-18-47.zip)

**Comment by wuniversales** [comment]
This same error is in my tablet with android 5.1.1
In my case I have "Supersu" installed.

**Comment by MuntashirAkon** [comment]
> Tried the current v4.0.0-alpha02 but it has the same behavior, problem not fixed.
> I saved the log, just in case they could be useful.
> [logs-2023-09-22-20-18-47.zip](https://github.com/MuntashirAkon/AppManager/files/12703597/logs-2023-09-22-20-18-47.zip)

Logs must be taken from the debug version of App Manager like I said earlier in order to figure out the issue.

**Comment by MuntashirAkon** [comment]
Closed due to a lack of response. Feel free to open it again if you're still facing the issue.

**Comment by MuntashirAkon** [comment]
BTW, the issue may have been fixed in the latest debug. Please check.
