### ISSUE TITLE
Crashing on Android 13 while getting Superuser Privilege 

### ISSUE THREAD

**Issue by Kero309x** [MuntashirAkon/AppManager#1145]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The app crashes while getting Superuser Privilege, if didn't get it works fine.

### Screenshots

![Screenshot_20230811-075502_App_Manager](https://github.com/MuntashirAkon/AppManager/assets/55901942/11609b7f-9ef3-4143-bfa6-c9289aa058ac)
![Screenshot_20230811-080013_DerpLauncher](https://github.com/MuntashirAkon/AppManager/assets/55901942/9e6d5bc9-7c99-49f3-81e6-3fbf8a74e5b7)

### Logs

You can find logs here: https://bin.kv2.dev/~64d5bc85e599576ea02d986c

### Device info

- Device: Redmi Note 9 Pro
- OS Version: 13
- App Manager Version: 3.1.1 Stable 
- Mode: Root

**Comment by Kero309x** [comment]
Sorry, I forget how to solve this issues but know I got that the recovery encryption type is different so app manager cannot get storage access due to encryption.

**Comment by MuntashirAkon** [comment]
Thanks for the info.
