### ISSUE TITLE
loop when opening a file

### ISSUE THREAD

**Issue by arguits** [MuntashirAkon/AppManager#1146]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

happens only when you open any files in the root, example: /0/Android/data/com.app/document.txt
usually doesn't open, stays in an infinite loop carrying

### Screenshots

![Screenshot_20230811_164335_App Manager](https://github.com/MuntashirAkon/AppManager/assets/139021990/e01078e3-3de6-4f65-9022-609b34733616)

### Device info

- Device: Samsung A03
- OS Version: Android 13
- App Manager Version: 4.0.0alpha1
- Mode: ADB

**Comment by MuntashirAkon** [comment]
Issue is fixed by 619e9901e9fea12ef917a33e7dc9e77ffba4f05c which gave rise to another related issue #1177.
