### ISSUE TITLE
Allow sorting and/or filtering by "Installer App"

### ISSUE THREAD

**Issue by surlyhacker** [MuntashirAkon/AppManager#1149]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

I would like the ability to sort and/or filter the app list by "Installer App", which is the app that installed the app in question.
In other words, I want to be able to sort so that all apps installed from the Play Store are together in the list and then all apps installed from Chrome listed next, etc

And for me, this sorting would be pretty useless without feature #1148 also being implemented

and/or...

And for filtering, I want to filter the list at list at least in these ways:
1. Only apps installed from the Play Store
2. Only apps NOT installed from the Play Store

**Comment by MuntashirAkon** [comment]
Just to note here: Since Android 11, there are 3 installer apps assigned to each app:
1. The installing app as set by the install initiator
2. The install initiator app (e.g. the actual app that installed the app)
3. The originating app (e.g. the app from where the APK files came)
