### ISSUE TITLE
New mode of operation: System (UID 100) is not available in v4.0.0-alpha01

### ISSUE THREAD

**Issue by Falcosoft** [MuntashirAkon/AppManager#1152]
### Describe the existing feature/documentation

Changlelog/documentation mentions that a new mode of operation namely System (UID 100) is available.

### Describe your problem(s)

The v4.0.0-alpha01 changlelog/documentation mentions that a new mode of operation namely System (UID 100) is available.
I have SMT Shell installed and it is working perfectly on Samsung A52s(Android 12) yet I do not see the new operation mode in  Settings -> Mode of operation in this new alpha version.
I could not find a description about what I should do to make this new mode of operation appear.
Thanks in advance.   

### Additional context

Ps:
I have downgraded the Samsung TTS component manually so I do not have Shizuku installed. Maybe that is the problem?

**Comment by MuntashirAkon** [comment]
SMT Shell has nothing to do with App Manager nor this mode of operation. You can subscribe to #922 to read how that functionality might be added in the future.

**Comment by Falcosoft** [comment]
OK, thanks for this information. But my question (if in somewhat rephrased form) still holds:
The v4.0.0-alpha01 changlelog/documentation mentions that a new mode of operation namely System (UID 100) is available.
I could not find a description about what I should do to make this new mode of operation appear.
Thanks in advance again.

**Comment by MuntashirAkon** [comment]
> The v4.0.0-alpha01 changlelog/documentation mentions that a new mode of operation namely System (UID 100) is available.
> I could not find a description about what I should do to make this new mode of operation appear.

Not all modes of operation has a public-facing UI. It's determined by the environment App Manager is currently working.
