### ISSUE TITLE
Notification for background install is delayed and sometimes doesn't appear 

### ISSUE THREAD

**Issue by warmoans** [MuntashirAkon/AppManager#1153]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When you use background install whether or not it is automatic the notification for the active installing part doesn't always appears. I have taken a screen record and uploaded here https://mega.nz/file/gWoUAKzK#9rVRmEu2oRzMXp-jmS0TNU3z45TrsuBJ2nDbj0FzUU4

### To Reproduce

Install an APK/apkm and click background install or have them on automatically and see that a notification doesn't always show up for the active install process. Usually just that the install finished. 

### Expected behavior

A notification to appear immediately after the install starts and says installing with a loading bar (it can just be cosmetic and just always animated) since not even the play store shows install percentage.

### Device info

- Device: Pixel 7 Pro 
- OS Version: 13 (August 2023)
- App Manager Version: 4.0.0-alpha01
- Mode: Root

**Comment by MuntashirAkon** [comment]
May be fixed by 12c288a000dc800557821ea96827d1e413d88328

**Comment by warmoans** [comment]
> May be fixed by [12c288a](https://github.com/MuntashirAkon/AppManager/commit/12c288a000dc800557821ea96827d1e413d88328)

I still only get install completed notifications on the debug build with that commit.

**Comment by MuntashirAkon** [comment]
Well, it's quite difficult to fix issues that aren't producible. Notifications in App Manager are perfectly working on other pixel phones running A13 and, even, A14. Not sure what went wrong with yours.

**Comment by warmoans** [comment]
> Well, it's quite difficult to fix issues that aren't producible. Notifications in App Manager are perfectly working on other pixel phones running A13 and, even, A14. Not sure what went wrong with yours.

Would a logcat help?
[logcat--2023-09-08--23-07.log](https://github.com/MuntashirAkon/AppManager/files/12564475/logcat--2023-09-08--23-07.log)
This is taken right after reinstalling an app and only getting the completed notification. Sorry I didn't get before.

**Comment by warmoans** [comment]
Granting usage access seems to help. I'm getting notifications for 100% install completion for a couple seconds before getting the install complete notification.

**Comment by MuntashirAkon** [comment]
> Granting usage access seems to help.

How has usage access got to do anything with notification triggered by foreground services? The entire thing seems puzzling to me.
