### ISSUE TITLE
Install a apk as frozen

### ISSUE THREAD

**Issue by yilksd** [MuntashirAkon/AppManager#1154]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Is there any method to install a apk as  frozen , from the beginning? I mean, never been running. I want to use App Manager to restrict ( disable some components, etc)  it before running the app. I know stopped apps (including apps that never been manually started after installed) cannot receive system broadcast beacause the system adds [FLAG_EXCLUDE_STOPPED_PACKAGES](https://developer.android.com/reference/android/content/Intent#FLAG_EXCLUDE_STOPPED_PACKAGES) to all broadcast intents, but some powerful apps just run before I touch their icon.

### Describe the solution you'd like

When installing a app using App Manager , there is a option like " install as frozen".

**Comment by MuntashirAkon** [comment]
An app can't open itself if it's installed for the first time. But if you're updating it, it can run itself by listening to certain broadcast receivers.

**Comment by yilksd** [comment]
> An app can't open itself if it's installed for the first time. 

An app can't open itself if it's installed for the first time because it cannot receive **system** broadcast, but some powerful apps just runs. Maybe by using other apps which are already installed and have been running  to send custom broadcast to wake this app up?

> But if you're updating it, it can run itself by listening to certain broadcast receivers.

I didn't update it.

**Comment by Incog5** [comment]
DeepL will  adds itself to a  menu when tap and holding text in chrome and other apps, when it is installed, before first run. 
Is there an exception for this or did the app run on install?

https://play.google.com/store/apps/details?id=com.deepl.mobiletranslator 

![Screenshot_20230831_133053_Chrome~2](https://github.com/MuntashirAkon/AppManager/assets/14378320/839c8e2c-99e4-4802-8be7-3d0c273114ee)

**Comment by MuntashirAkon** [comment]
These options are based on the intent filters in the AndroidManifest.xml inside the APK file. It's nothing to do with running or not running an app. But if you click on it, it will launch the app.

**Comment by Incog5** [comment]
Understood. Thanks.

**Comment by MuntashirAkon** [comment]
It's not actually that difficult to implement such an option in our existing model. But I think I need to think it through:

An app can run right after installing it if it's being updated (with the exception of system apps which can run in first install). But I don't think it's necessary to freeze the app to prevent the app from running automatically (freezing has consequences over temporary data such as launcher/dynamic shortcuts). We can prevent this by stopping the app before installing it (if the option is enabled). This way it can't receive broadcast actions such as `ACTION_MY_PACKAGE_REPLACED` and stay stopped.

**Comment by yilksd** [comment]
> An app can run right after installing it if it's being updated (with the exception of system apps which can run in first install).

I didn't update it.

Maybe you could check this: https://www.javacodegeeks.com/2012/05/android-broadcast-receiver-change-in.html
An app can send custom broadcast with  FLAG_INCLUDE_STOPPED_PACKAGES to wake up stopped apps.

**Comment by MuntashirAkon** [comment]
> Maybe you could check this: https://www.javacodegeeks.com/2012/05/android-broadcast-receiver-change-in.html
> An app can send custom broadcast with FLAG_INCLUDE_STOPPED_PACKAGES to wake up stopped apps.

This is actually the default behaviour. Installer specifically avoid waking up stopped packages by setting `FLAG_EXCLUDE_STOPPED_PACKAGES`. If it's happening to you, some other system app is triggering it, not the installer.

**Comment by MuntashirAkon** [comment]
My verdict: Such feature isn't required due to the reason [stated above](https://github.com/MuntashirAkon/AppManager/issues/1154#issuecomment-1752007281).
