### ISSUE TITLE
interceptor is not opened from Xiaomi camera app

### ISSUE THREAD

**Issue by cewbdex** [MuntashirAkon/AppManager#1155]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Interceptor does not open when I select it after tapping last shot in Xiaomi camera app, the same behavior is observed with all of other apps available to open with, only Termux opens and does kinda something:
![Screenshot_2023-08-25-08-27-47-735_com termux](https://github.com/MuntashirAkon/AppManager/assets/9021297/27e33db9-3ef4-4d55-bd96-04467a3e93ce)

### To Reproduce

- 1. Use ADB to disable system Xiaomi app for gallery (com.miui.gallery).
- 2. Open camera app, take a picture.
- 3. Click on the icon to open last shot picture, select Interceptor to open with.
- 4. Nothing opens

### Expected behavior

Interceptor opens and tells me information I need.

### Device info

- Device: Xiaomi Mi 10 5G
- OS Version: Android 13, MIUI 14.0.2.0 EU
- App Manager Version:
- Mode: NonRoot

**Comment by MuntashirAkon** [comment]
Likely due to some A13 issue. Can you provide a link to the apk (e.g. APKMirror) or upload it?

**Comment by cewbdex** [comment]
I tried to get the apk: https://1drv.ms/u/s!AprI9YdiQxJ2lbU_Ht3F9bLFFA6U9w?e=hPclgP
If you want also the gallery, I will upload it too.

**Comment by MuntashirAkon** [comment]
> If you want also the gallery, I will upload it too.

Sorry, I meant the gallery app.

**Comment by cewbdex** [comment]
https://1drv.ms/u/s!AprI9YdiQxJ2lbVAk4vncKnEtcsYwg?e=zCFlIi
Here

**Comment by MuntashirAkon** [comment]
May be fixed by 2e84e0407ef2dcf39814c61cc343690d13a82048. Not tested.

**Comment by cewbdex** [comment]
Thank you, could you upload a build of this for me, so I could test it?

**Comment by MuntashirAkon** [comment]
You can find it in the GitHub Actions page. Example: https://github.com/MuntashirAkon/AppManager/actions/runs/6048954517

**Comment by cewbdex** [comment]
Thank you! It works now and shows something.

![Screenshot_2023-09-02-10-35-30-673_io github muntashirakon AppManager debug](https://github.com/MuntashirAkon/AppManager/assets/9021297/8d67c008-c9ca-4db0-93d3-91039cd2d493)
