### ISSUE TITLE
Manually unblock app activity

### ISSUE THREAD

**Issue by mid-kid** [MuntashirAkon/AppManager#1156]
### Describe your problem(s)

I've accidentally disabled App Manager's main activity (io.github.muntashirakon.AppManager/.main.MainActivity), and even when I uninstall and reinstall the app, I cannot figure out a way to re-enable it. How does AppManager achieve this, and can I manually re-enable it?

**Comment by MuntashirAkon** [comment]
If you're using the default/IFW blocking method, head over to `/data/system/ifw` and delete `io.github.muntashirakon.AppManager.xml`, or if you have a terminal installed, you can do this via `su`.

```sh
su -c rm /data/system/ifw/io.github.muntashirakon.AppManager.xml
```

After that, App Manager should reappear in your app drawer. I think I should add an option to protect the components of App Manager.

**Comment by mid-kid** [comment]
Thanks a lot!
