### ISSUE TITLE
Can not open Google Play Services info

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#1164]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Since the ARSClib  update a few days ago, AM is not able to open Google Play Services from the list. It says " couldn't fetch the package info ". 

Logs - https://pastebin.com/raw/WWy44aSv

### To Reproduce

Just open the app
Tap on Google Play Services in app list 

### Expected behavior

It should open.

### Device info

- Device: Android 
- OS Version: 13
- App Manager Version: latest debug
- Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed via dbe0e168498d0869c9687a2915925ed4eb772fac
