### ISSUE TITLE
The category selection list in the Interceptor is missing fullnames

### ISSUE THREAD

**Issue by soulpursuit** [MuntashirAkon/AppManager#1168]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Because the name of the intention is too long, the display is incomplete.

### Screenshots

![Screenshot_2023-09-06-12-03-44-861_io github muntashirakon AppManager debug](https://github.com/MuntashirAkon/AppManager/assets/48674277/0103a2ce-5a86-4d63-a86d-ee5f7b6fc391)

### Device info

- Device:Xiaomi 10 Pro
- OS Version:miui 14 A13
- App Manager Version:4.0.0-alpha01-DEBUG 434
- Mode: Root

**Comment by MuntashirAkon** [comment]
This is a bit difficult to handle. But I think the last part is more important than the first part. So, we can only choose to show the last part instead.

**Comment by soulpursuit** [comment]
Can you use the method of scrolling left and right?

**Comment by MuntashirAkon** [comment]
Fixed via 9468e004b67a4fa72b6a199aa869c508a4e138dd
