### ISSUE TITLE
Add scroll button for "User manual"

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1170]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Currently we've only a _viewbar_ for the "User manual" (UM) which lets you know where the current screen is in relation to the maximum height.
Adding a scroll button would allow users to jump screen quickly.

Use case: I've used UM so many times that now I know the ≈positions of them. Scroll button would allow me to jump to preferred position easily. This is the fastest way than _search keyword_ _, click from contents_ if you're already familiar with the UM.

**Comment by MuntashirAkon** [comment]
Added in 7cbf838fd21a2ab794ab80d4058835945d72b795
