### ISSUE TITLE
Cannot interact with AppManager without notification perm

### ISSUE THREAD

**Issue by AeliusSaionji** [MuntashirAkon/AppManager#1173]
This is a strange one.
AppManager will not respond to any touch input at all unless notification permissions are granted.
On first run, I did not approve the request for notifications, and the next popup (accept/exit) could not be dismissed. Further, the screen was flickering. I went and granted notification permissions, accepted the dialog, then turned them back off. No longer flickering, but the app does not react to touch input.

Android 13

**Comment by MuntashirAkon** [comment]
I implemented it somewhat blindly as I did not have access to any A13 device. But notifications are very much part and parcel of App Manager. So, it naturally will refuse to work without granting the notification permission.

**Comment by MuntashirAkon** [comment]
Fixed in 93ce56cc89f9fc4fd109098370b933ff1f1bb430

**Comment by MuntashirAkon** [comment]
While the notification permission is now optional, you may still face the other issues as described in #1388.
