### ISSUE TITLE
sh: <stdin> adb: command not accessible or not found 

### ISSUE THREAD

**Issue by guiilerm1** [MuntashirAkon/AppManager#1181]
### Describe the existing feature/documentation

reinstalling uninstalled system apps 

### Describe your problem(s)

I accidentally uninstalled an app from the system so I tried to reinstall it with the command: adb shell cmd package install-existing com.sec.android.app.soundalive
but a not accessible error appears or not found. Is the command correct or should I use a different command to reinstall?
![Screenshot_20230915_224611_App Manager](https://github.com/MuntashirAkon/AppManager/assets/142160595/b71b22cf-0974-402b-b505-9143e63d1be2)

**Comment by MuntashirAkon** [comment]
The command is correct, but you're using it wrong. `adb shell` creates a shell when you use it from a non-ADB terminal. App Manager's already using ADB, so you just have to run this command:

```sh
cmd package install-existing com.sec.android.app.soundalive
```
