### ISSUE TITLE
buildDocs error

### ISSUE THREAD

**Issue by zhangchunsheng** [MuntashirAkon/AppManager#1185]
### Describe the existing feature/documentation

Build file 'AppManager/docs/build.gradle' line: 25

Execution failed for task ':docs:buildDocs'.
> Process 'command 'AppManager/scripts/make_docs.sh'' finished with non-zero exit value 1

### Describe your problem(s)

Build file 'AppManager/docs/build.gradle' line: 25

Execution failed for task ':docs:buildDocs'.
> Process 'command 'AppManager/scripts/make_docs.sh'' finished with non-zero exit value 1

**Comment by MuntashirAkon** [comment]
Run the script manually from root (eg. AppManager folder) to see the actual error:

```sh
bash scripts/make_docs.sh
```

**Comment by ducle6487** [comment]
I've got same problem, how to fix that?

**Comment by MuntashirAkon** [comment]
> I've got same problem, how to fix that?

I've asked a question in my last comment. If you can answer that, then a solution may be found. Otherwise there's nothing I can do. Alternatively, you can check how GitHub builds it in the `.github/workflows` directory. Note that, the app cannot be built from the Windows operating system.
