### ISSUE TITLE
Weird looking "options menu"

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1187]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

![gif-18-09-23](https://github.com/MuntashirAkon/AppManager/assets/48226312/4c6aae5f-3ad1-40db-9327-db40874c8212)

It appears if you open "App info > Options menu" 1st time only.

### Device info

- Device: moto g71 5G
- OS Version: 12
- App Manager Version: 4.0.0-alpha02
- Mode: No Root

**Comment by MuntashirAkon** [comment]
Can you still reproduce it? I don't seem to.

**Comment by shuvashish76** [comment]
> It appears if you open "App info > Options menu" 1st time only.

Not anymore.
I noticed it 3-4 days back (I think before beta01 debug builds) not sure what triggered it. I'll reopen if I successfully reproduce it or notice in future. Thanks.

**Comment by shuvashish76** [comment]
Still I haven't noticed in debug builds, please remove it from v4.0.0-beta02 milestone.

**Comment by MuntashirAkon** [comment]
Removed as requested.
