### ISSUE TITLE
Typo in context menu

### ISSUE THREAD

**Issue by HarriBuh** [MuntashirAkon/AppManager#1191]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Self explanatory.
The correct German word would be "Auswählen", not "Asuwählen".

### To Reproduce

1. Open app
2. Open "Log Betrachter" (could be "log viewer" in English?)
3. Long press on an entry > pop-up menu opens
4. Recognize typo

### Screenshots

![markup_1000005985](https://github.com/MuntashirAkon/AppManager/assets/123186113/d800a508-e37e-4399-a395-58d75a9e7837)

### Device info

- Device: Google Pixel 7
- OS Version: 13
- App Manager Version: 3.1.2
- Mode: Root w/ Magisk 26.3

**Comment by shuvashish76** [comment]
Language : English
Minor typo from AM docs [6.1.4](https://muntashirakon.github.io/AppManager/en/#toc:elliptic-curve-crypography-ecc) Elliptic Curve ~Crypography~ (ECC) Cryptography

**Comment by MuntashirAkon** [comment]
> The correct German word would be "Auswählen", not "Asuwählen".

Fixed in c9d1070c709f300440f13fe4ee0f162ce2883735
