### ISSUE TITLE
Can't Uninstall app manager 3.1.2

### ISSUE THREAD

**Issue by privacyonly** [MuntashirAkon/AppManager#1193]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Can't uninstall app manager 3.1.2

### To Reproduce

1. install the latest version of app manager 3.1.2
2. try Uninstalling
3. package installer keeps stopping

### Expected behavior

Uninstall successfully

### Device info

- Device: Samsung S21 Ultra SM-G998B
- OS Version: Android 13 OneUI 5.1 Play August 2023 Patch Sept 2023
- App Manager Version: 3.1.2
- Mode: ADB

**Comment by MuntashirAkon** [comment]
You need to provide us the exact crash report to understand what happened. If you don't know how to take one, you can use the Log Viewer in Android with only `crash` buffer enabled, or any other third-party crash detector such as **Scoop**.

**Comment by MuntashirAkon** [comment]
You need to provide us the exact crash report to understand what happened. If you don't know how to take one, you can use the Log Viewer in Android with only `crash` buffer enabled, or any other third-party crash detector such as **Scoop**.

**Comment by privacyonly** [comment]
Unknown restriction queried by uid 1000 (com.samsung.android.hdmapp et al): io.github.muntashirakon.AppManager

after disabling that

Unknown restriction queried by uid 1000 (com.samsung.sec.android.teegris.tui_service et al): io.github.muntashirakon.AppManager

**Comment by user0-tb** [comment]
I think it's the `android:hasFragileUserDat="true"` attribute in Android Manifest.xml. Would you try my snapshot build [here](https://github.com/user0-tb/AppManager/suites/17403226149/artifacts/994615073)

**Comment by mutchiko** [comment]
Hi im able to recreate the issue, the only thing is, i tried making a log using scooper but i was traumatised by the amount of issues i get from DiagMonAgent, anybody can help me make a proper log?

**Comment by MuntashirAkon** [comment]
> Hi im able to recreate the issue, the only thing is, i tried making a log using scooper but i was traumatised by the amount of issues i get from DiagMonAgent, anybody can help me make a proper log?

You can try LogFox instead. Basically, I need the following files:

1. Full system logs taken using `logcat` command or **LogFox** app (if you fear it contains something private, consider sending me an email)
2. **framework.jar** and **services.jar** located at `/system/framework` (accessible without root or ADB)
3. **Package Installer** APK file.

**Comment by MuntashirAkon** [comment]
I have been helped by a Telegram user regarding this issue. I cannot disclose the reason for now. But the issue was due to a simple logical error in a system application.

**Comment by mutchiko** [comment]
Glad to hear that, i already followed the steps and reproduced the issue, if you want to take a look at the logs, i can send them on telegram.

**Comment by MuntashirAkon** [comment]
> Glad to hear that, i already followed the steps and reproduced the issue, if you want to take a look at the logs, i can send them on telegram.

OK, in case the other user was facing a different issue.

**Comment by mutchiko** [comment]
Yeah I think I figured it out, it happenes when you use the app in adb mode, then restart the phone (which will revoke the access to adb) and then if you try to uninstall any app installed from app managaer, the error will occur

**Comment by MuntashirAkon** [comment]
Those who are facing the issue, can you confirm the following:
1. (Optional) App Manager having the usage stats permission
2. Package Installer app having the usage stats permission.

**Comment by chr56** [comment]
This maybe a known bug on _(only)_ **Android 10** with external **physical SD card**.
See https://gist.github.com/agnostic-apollo/58def38fdb1c90563454974108ae52df.

**Comment by MuntashirAkon** [comment]
> This maybe a known bug on _(only)_ **Android 10** with external **physical SD card**. See https://gist.github.com/agnostic-apollo/58def38fdb1c90563454974108ae52df.

Possible solutions have already been covered here: https://github.com/amcommunity/TipsAndTricks/issues/7

**Comment by MuntashirAkon** [comment]
Closed due to a lack of response from the OP. Feel free to open it again if you're still facing the issue. However, I am still against removing `android:hasFragileUserData` from App Manager's manifest.
