### ISSUE TITLE
Profiles not working for alpha release

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1194]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Profiles not working in v4.0.0-alpha02 on creating/importing profile > apply.
But working as expected in v3.1.2, also works if you update to alpha from stable release.

### To Reproduce

1. Fresh install v4.0.0-alpha02 (important)
2. Create a profile > Save
3. Apply
4. Check profile Log viewer > no logs shown
5. Not applied (as I checked the app was not freezed)

Same result if you import profiles > apply

### Logs

[20-09_06-55-21.txt](https://github.com/MuntashirAkon/AppManager/files/12667769/20-09_06-55-21.txt)

Indeed no such "profile_test.log" file in `/storage/emulated/0/Android/data/io.github.muntashirakon.AppManager/cache` directory. (exist for v3.1.2)

### Device info

- Device: moto g71 5G
- OS Version: 12
- App Manager Version: 4.0.0-alpha02
- Mode: Root

### Additional context

The .json file exist in `/data/user/0/io.github.muntashirakon.AppManager/files/profiles` for v4.0.0-alpha02.

**Comment by MuntashirAkon** [comment]
Fixed in 3d5ba2e94d3e72d3fab42765d4015a99efbb1e6d
