### ISSUE TITLE
Redesign "Save partial logs"

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1195]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

![Screenshot_20230920-153501](https://github.com/MuntashirAkon/AppManager/assets/48226312/cd7ae3c9-dbec-4469-8091-3c2ff39f4c0c)
[matlog](https://github.com/pluscubed/matlog) has this feature.

As I understand we've removed that feature as we support batch operation. But the issue is we don't support selecting consecutive logs at once. So you've to click on each of the line to select them.

Suggestion:
1. Single click to expand/collapse log text
2. Selection mode - Long click to select a log + show the bottom batch ops sheet
 i) single click to select _for others_
 ii) long click to select in between items
(In short the operation should work just like AM home page.)

But the issue is currently we've "search by/copy to clipboard/select" context menu when we long click.
 - Search by (Tag & PID) - Move that to _Advanced_ Search section. But somehow we still need this feature on log viewer screen. [Maybe show both "batch ops-bottom sheet" with "search by-context menu" at the same time when enter (2) but close the context menu if you enter (2i) & (2ii) or scroll up/down]
 - Copy to clipbaord - Move that to bottom sheet which would allow users to use with batch ops (notice that currently we support copying only one log text)
 - ~Select~ - Not relevant anymore

**Comment by MuntashirAkon** [comment]
I think this approach would look better:

1. Normal mode
   1. Click: expand/collapse text
   2. Long click: Open context menu (including the option to select an item, this isn't awkward as I've seen it in other popular apps)
3. Selection mode
   1. Click: Select clicked item
   2. Long click: Select items between last item to the clicked item if possible. Otherwise, only click the item. (There's no need to have a context menu in the selection mode)

In addition, the will be a copy option in the batch selection menu.

**Comment by shuvashish76** [comment]
> this isn't awkward as I've seen it in other popular apps

I don't like it but like or not your approach probably best in this case 👍🏿
With this design we've space for adding "filter" (similar to [LogFox](https://github.com/F0x1d/LogFox)) directly from the context menu (i.e. auto fill PID/tag/package name etc..). Just an idea, needs a separate issue for other feature discussions.

**Comment by MuntashirAkon** [comment]
> With this design we've space for adding "filter" (similar to [LogFox](https://github.com/F0x1d/LogFox)) directly from the context menu (i.e. auto fill PID/tag/package name etc..). Just an idea, needs a separate issue for other feature discussions.

Log Viewer needs a revamp in terms of how logs are generated or created as well as the UI (it looks a bit different from the rest of the app). You can share your ideas in #755. I didn't like the design of LogFox's filter options you shared earlier. But I need to try the app to see this myself.

**Comment by MuntashirAkon** [comment]
Implemented via 6a148858283a40b8ba9c62fccaba2852ad35b14e and 87c8dd17f3a028f086cd816e2c2d2d8b783be705
