### ISSUE TITLE
trichrome librarie

### ISSUE THREAD

**Issue by researchscum** [MuntashirAkon/AppManager#1198]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

show installed trichrome library like sd maid

### Describe the solution you'd like

show installed trichrome library like sd maid

### Describe alternatives you've considered

show installed trichrome library like sd maid se/2

### Additional context

i'm not trying to spam or anything. it just for the question asked that is all i can think to answer it.
in sd maid it show every trichrome library installed no root or adb needed. when google play delete it, it also gone in sd maid.
and in the current am_debug_4.0.0-alpha02-debug#2588
**trichrome library can't show 117 in the home screen only in app info.**
i do a factory reset and install trichrome version 117 than the main app for it which is chrome 117 but when i open am debug with mode ADB it show chrome 117 but trichrome still the pre installed one version 114 there is no screenshoot for 114.

pocof3
miui14 android 13
mode ADB
app version am_debug_4.0.0-alpha02-debug#2588

<details>
  <summary>screenshot</summary>

![1695347131533](https://github.com/MuntashirAkon/AppManager/assets/97543175/fcfe93e8-bb9a-4542-8ee6-770766d8c003)
![1695347131531](https://github.com/MuntashirAkon/AppManager/assets/97543175/76e7887e-ab3a-4924-80fa-2e07cbc6d2b9)
![Screenshot_2023-09-22-08-45-52-438_io github muntashirakon AppManager debug-edit](https://github.com/MuntashirAkon/AppManager/assets/97543175/463811b4-f277-4114-86d2-a5a7f12b68d3)
![Screenshot_2023-09-22-08-46-19-374_io github muntashirakon AppManager debug](https://github.com/MuntashirAkon/AppManager/assets/97543175/cd056a38-3aab-4c8c-a0fc-f9d5dff678c7)

</details>

**Comment by MuntashirAkon** [comment]
Click on the **static shared library** tag to view and manage the other variants. Shared libraries come with a single package name, but some apps display different package names with version code appended at the end probably because they do not understand how static shared libraries work in Android and use the package name reported by the system instead of the actual package name.
