### ISSUE TITLE
[Feature] Freeze user and system apps

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#12]
(Dependent on #2)

Yet another feature that could be considered useful would be the ability to freeze (disable) user and system apps from the app's interface.

Rationale: not all system apps can be frozen (disabled) from the Android app info and no user apps can.

**Comment by MuntashirAkon** [comment]
Do you have any example FOSS app? It would be easier to implement this way.

**Comment by Atrate** [comment]
> Do you have any example FOSS app?
No, I don't think so

**Comment by MuntashirAkon** [comment]
Fixed via b58ed49
