### ISSUE TITLE
Wrong message shown when importing empty blocking rules

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1200]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

1. Settings > Rules > Import/export blocking rules
2. Import from Watt/Blocker
3. It opens up your _documentsui_ system app > click back/pick nothing
4. It says "Imported"

No such message if you pick "import rules from App Manager".
Same issue if you pick "import existing rules", but IG this is expected.

### Device info

- App Manager Version: 3.1.2
- Mode: Root

### Additional context

Similar issue for apps > add to profile > pick no profile, again expected.

**Comment by MuntashirAkon** [comment]
Fixed in a984d0c746170fb303aa5c3486bd2f899be28c85
