### ISSUE TITLE
Components' blocking status

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1201]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Suppose you blocked many components of an app using different blocking methods. Now it's impossible to recognize which blocking methods you used for those components.

AM should show their status so that the user can recognize them visually.
Here is my proposal
1. Either - Always show their blocking status just below the component switch.
2. Or - Only show their status if it's different than your default blocking status. (No status means > it's your default one)

![component_blocking_status](https://github.com/MuntashirAkon/AppManager/assets/48226312/efabd9f2-f88b-4928-971d-08d8c9a4d85a)

**Comment by MuntashirAkon** [comment]
Implemented in d65eeeafcc4392e86654ea8467640d813a5d1ec0

**Comment by shuvashish76** [comment]
> Blocking method is displayed in short form under the toggle button.

For "Services" the status is under the app icon.

**Comment by shuvashish76** [comment]
For any component
1. When the status is `IFW+Dis` > long click & choose _only_ `IFW` = it doesn't work i.e. the status remains `IFW+Dis`
2. When the status is _only_ `Dis` > long click & choose _only_ `IFW` = the status changes to `IFW+Dis` instead

Bug or expected behaviour?

**Comment by MuntashirAkon** [comment]
> For "Services" the status is under the app icon.

6aef6890dcbbf9a76b79ea8285e0f5b5215897fb



> For any component
> 
> 1. When the status is `IFW+Dis` > long click & choose _only_ `IFW` = it doesn't work i.e. the status remains `IFW+Dis`
> 2. When the status is _only_ `Dis` > long click & choose _only_ `IFW` = the status changes to `IFW+Dis` instead
> 
> Bug or expected behaviour?

be2b2c94405866cce65d9b0795cdb7a6e8fd4ec6

**Comment by shuvashish76** [comment]
> [be2b2c9](https://github.com/MuntashirAkon/AppManager/commit/be2b2c94405866cce65d9b0795cdb7a6e8fd4ec6)

Nothing changed as per my testing.
AM Debug v4.0.0-beta01 Run#2744

**Comment by MuntashirAkon** [comment]
> > [be2b2c9](https://github.com/MuntashirAkon/AppManager/commit/be2b2c94405866cce65d9b0795cdb7a6e8fd4ec6)
> 
> Nothing changed as per my testing. AM Debug v4.0.0-beta01 Run#2744

Logs?

**Comment by shuvashish76** [comment]
https://github.com/user-attachments/assets/1cc1687a-ab3c-4d2d-afcd-3d971e0c59c3

Full logs: 
[15_07-10-01-25_961.log](https://github.com/user-attachments/files/16230198/15_07-10-01-25_961.log)
