### ISSUE TITLE
Some unknown net policies

### ISSUE THREAD

**Issue by HemanthJabalpuri** [MuntashirAkon/AppManager#1209]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

> Policies unknown to App Manager will have a Unknown prefix along with the policy constant name and number in the hexadecimal format. Unknown policies should be reported to App Manager for inclusion.

Docs states to report unknown policies

### To Reproduce

Go to net policy from any app info

### Expected behavior

All policies should be known in future

### Screenshots

![Screenshot_20231002-114141](https://github.com/MuntashirAkon/AppManager/assets/39197123/57e8a076-de9f-4fc0-b6b8-a77e3c7764f5)

### Device info

- Device: Moto G52 running Stock ROM
- OS Version: 12
- App Manager Version: 3.1.2
- Mode: Root (Magisk)

**Comment by MuntashirAkon** [comment]
Could you send me **framework.jar** from `/system/framework`?

**Comment by MuntashirAkon** [comment]
Can you share a screenshot from “Mobile data & Wi-Fi” page?

1. Go to “App Info” page of any app (in Android settings, not in App Manager)
2. Then navigate to the “Mobile data & Wi-Fi” page
3. Take an screenshot and upload it here.

**Comment by MuntashirAkon** [comment]
Added via 1198b51e28a6822f3481c85124df6638cda946bf
