### ISSUE TITLE
Add support for backing up various stats of an app

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#121]
Some useful stats to consider backing up;
1. Magisk hide state
2. Accessibility stat
3. Battery Usage>
    Background Restriction
    Battery Optimization
4. Notification Access

Done;
1. Permissions (Contacts, location, phone, storage, etc)
2. Usage Access

**Comment by Cyberavater** [comment]
Currently, I see the permission stat is already considered n added so I'ven't added it to the list.

**Comment by MuntashirAkon** [comment]
These require some major study as I don't know where they're saved or how they can be restored.

**Comment by MuntashirAkon** [comment]
@Cyberavater what do you mean by **usage access**? Is it the usage access permission? If so, #102 already covers it.

**Comment by Cyberavater** [comment]
> @Cyberavater what do you mean by **usage access**? Is it the usage access permission? If so, #102 already covers it.

Yes, Usage access permission. OP updated.

**Comment by Cyberavater** [comment]
For Magisk hide state, it's possible to read them via terminal and also enable and disable them there.

**Comment by MuntashirAkon** [comment]
> For Magisk hide state, it's possible to read them via terminal and also enable and disable them there, Afaik.

Yeah, using `magiskhide` terminal command.

> And if you have any specific questions, I'll try finding the answer.

I actually need help regarding the other three features (2-4):

2-3: I'm not sure if they're really store in the secure table.
4: What do you mean by notification access? Do you mean the apps that request `android.permission.BIND_NOTIFICATION_LISTENER_SERVICE` or just notification settings? Notification settings are not saved to secure table either, it seems.

There are other settings that worth consideration: (all of them are located at the secure table)
5. `always_on_vpn_app`: Package name of the always on VPN
6. `always_on_vpn_lockdown` (0/1)
7. `assistant`
8. `autofill_service`: service name
9. `backup_transport`
10. `default_input_method`
11. `enabled_input_methods`
12. `enabled_notification_assistant`
13. `enabled_notification_listeners`: `android.permission.BIND_NOTIFICATION_LISTENER_SERVICE`
14. `enabled_notification_policy_access_packages`
15. `input_method_subtype_history`
16. `location_providers_allowed` (plus `location_changer` and `location_mode`)
17. `media_button_receiver`
18. `screensaver_components`
19. `screensaver_default_component`
20. `selected_spell_checker`
21. `touch_exploration_granted_accessibility_service` (with `touch_exploration_enabled`)
22. `voice_interaction_service`
23. `voice_recognition_service`

These are just consideration. It doesn't mean that all of them will be supported.

**Comment by MuntashirAkon** [comment]
24. App installer
25. Battery optimisation
    - **Backup:** `dumpsys deviceidle whitelist` (output format: mode,package,uid)
    - **Restore:** `dumpsys deviceidle whitelist +package.name`
26. SSAID: `/data/system/users/0/settings_ssaid.xml` (unlike others, `ssaid` namespace isn't available via `cmd settings` command but it does have a provider)
27. Net policy (background restrictions):
    - **Backup:** `cmd netpolicy list restrict-background-whitelist|blacklist` (check for uid)
    - **Restore:** `cmd netpolicy add|remove restrict-background-whitelist|blacklist UID`
28. Notification policy (highly unlikely): `/data/system/notification_policy.xml`

**Comment by MuntashirAkon** [comment]
I've decided to add support for 1, 13, 24, 25, 27 for now.

**Comment by MuntashirAkon** [comment]
Fixed via e555b552, c7c1b2c1.

**Comment by MuntashirAkon** [comment]
It looks like restoring SSAID is essential for some apps (otherwise may cause random crash).

**Comment by MuntashirAkon** [comment]
Implemented in 405cdf00.
