### ISSUE TITLE
Activity disabling like blocker in App Manager.

### ISSUE THREAD

**Issue by rickdtc** [MuntashirAkon/AppManager#1216]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

It would be great if this feature is added for adb mode it would be a great alternative to [blocker](https://github.com/lihenggui/blocker) which uses shizuku api.

**Comment by MuntashirAkon** [comment]
We have no intention to automatically modify an APK file to inject “test-only” flag if this is what you mean. Other than that Blocker offers no extra features. For Shizuku, we've got a community post for it: https://github.com/amcommunity/TipsAndTricks/issues/14
