### ISSUE TITLE
apps are not showing up

### ISSUE THREAD

**Issue by ZakitheBig** [MuntashirAkon/AppManager#1225]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Well I use the app manager in root mode I managed to use it for some time But after uninstalling some user applications and restarting my device it no longer shows me the applications :(

### Device info

- Device: Motorola Edge 
- OS Version: 11
- App Manager Version: 4.0.0 alpha-2
- Mode: Root

**Comment by WhiteNightN0** [comment]
I encountered the same problem on 3.1.4. It still exists after upgrading version 3.1.5.Later, I tried to cache the data clearly, including uninstalling and reinstalling, but I couldn't realize the APP list. (in root mode))

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
