### ISSUE TITLE
meaning of warnings on signature page?

### ISSUE THREAD

**Issue by thx101** [MuntashirAkon/AppManager#1227]
### Describe your problem(s)

I couldn't find anything in the docs about this, but an app I had open in app info showed over 100 warnings. I didn't see any way to display what they were or more info.

**Comment by MuntashirAkon** [comment]
> I couldn't find anything in the docs about this, but an app I had open in app info showed over 100 warnings. I didn't see any way to display what they were or more info.

App Info tab does not display any warning. Did you mean the _Signatures_ tab? If so, the warnings aren't relevant which is why they are noted but not displayed.
