### ISSUE TITLE
App crashed 

### ISSUE THREAD

**Issue by t00bie77** [MuntashirAkon/AppManager#1230]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App manager crashes when launching after gave root priviledge to it. 

### Screenshots

![Screenshot_20231019_212932_One UI Home](https://github.com/MuntashirAkon/AppManager/assets/122029834/a02d365f-d693-4996-a59d-c1da1c4dba04)
![Screenshot_20231019_212859_Files by Google](https://github.com/MuntashirAkon/AppManager/assets/122029834/30fde834-fa9f-4dc6-bd54-9362c25bdf32)

### Logs

[crash.log](https://github.com/MuntashirAkon/AppManager/files/13050292/crash.log)

### Device info

- Device: sm-s911b/ds
- OS Version: a13 latest
- App Manager Version: latest stable or alpha
- Mode: Root/ADB/NonRoot root
[device.txt](https://github.com/MuntashirAkon/AppManager/files/13050299/device.txt)

**Comment by MuntashirAkon** [comment]
Duplicate of #948

**Comment by MuntashirAkon** [comment]
Please read/subscribe to #948 to get further updates on the issue.
