### ISSUE TITLE
Customize Exported App List

### ISSUE THREAD

**Issue by pudah** [MuntashirAkon/AppManager#1233]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

The XML resulting from the **Export App List** feature contains a lot of very useful info. But sometimes I don't want everything. For example, I sometimes only need Label and Package Name, or Package Name and Installer Package, or any other combination. Right now I do some cumbersome post processing on the resulting XML file. It would be very useful if the user could select which fields are desired in the XML.

### Describe the solution you'd like

I am wondering if some sort of template system might be created. 

Possibly an option in Settings where the user can create named templates wherein the fields to include in the report can be specified.

Then when the user selects the option to produce the report from the apps list and is presented with the current XML or Markdown format options, a secondary list of the named templates would be presented if the user selects XML.

If not a template system per se, then perhaps at the time the user selects XML from the format list, a menu could then be presented that would allow the user to select which fields to include. It could either default to all fields and the user would deselect the ones he doesn't want, or no fields and the user would pick the ones he wants. Perhaps the last selected fields could be retained between uses.

### Describe alternatives you've considered

If it is not feasible to disrupt the current XML report format, would it be possible to have an option to create some other type of output file like csv or json, still giving the user the option to specify which fields are included.

**Comment by MuntashirAkon** [comment]
> If it is not feasible to disrupt the current XML report format, would it be possible to have an option to create some other type of output file like csv or json, still giving the user the option to specify which fields are included.

The purpose of the export feature (with XML in particular) is to allow a user to import the list as well (#122, #464). So, I need to think this through.

**Comment by MuntashirAkon** [comment]
I've decided to add support for straightforward formats, such as CSV and JSON without support for any customisation. You can customise the file later using another editing software such as spreadsheet editor.

**Comment by pudah** [comment]
Thanks very much.

**Comment by MuntashirAkon** [comment]
Implemented in 941d4bac058afeeedc4ba5f18805178175bd1117
