### ISSUE TITLE
App Manager stuck at initialize 

### ISSUE THREAD

**Issue by Yoongdeer** [MuntashirAkon/AppManager#1234]
### Describe the existing feature/documentation

Installed then given su right it just hangs at initializing

### Describe your problem(s)

Installed then given su right it just hangs at initializing

**Comment by Yoongdeer** [comment]
https://imgbox.com/Vchl2KGS

**Comment by H3XDaemon** [comment]
In case you're using latest Magisk Alpha. #1231

**Comment by Yoongdeer** [comment]
> In case you're using latest Magisk Alpha. #1231

Yes i just commented there hopefully there's a fix else i try magisk delta , thx

**Comment by MuntashirAkon** [comment]
Ah, 1234, interesting issue number albeit a duplicate one

**Comment by MuntashirAkon** [comment]
Duplicate of #1231
