### ISSUE TITLE
Exodus Report

### ISSUE THREAD

**Issue by spookymyo** [MuntashirAkon/AppManager#1236]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Not sure if this is really a bug or not, but this seemed like the best place to post.
In the screenshots on the XDA page it shows an Exodus report tab, which is awesome. But when I installed the latest version (3.1.3), I can't find the Exodus report anywhere. Has this been removed?

### Device info

- Device: Pixel 6 Pro
- OS Version: 14
- App Manager Version: 3.1.3
- Mode: Root, Magisk

**Comment by spookymyo** [comment]
Found documentation that shows Exodus was replaced with Scanner. Which isn't as helpful BTW.

**Comment by MuntashirAkon** [comment]
> In the screenshots on the XDA page it shows an Exodus report tab, which is awesome. But when I installed the latest version (3.1.3), I can't find the Exodus report anywhere. Has this been removed?

There were never any Exodus report tab in App Manager. It was always the static scanner and is still there in the same way as before except a few UI changes.
