### ISSUE TITLE
When adb doesnt work

### ISSUE THREAD

**Issue by aleks01100001** [MuntashirAkon/AppManager#1238]
### Describe the existing feature/documentation

Hey guys, I just wanted to ask a question:

When using the app manager with ADB and removing some permissions, such as fine_location, what happens if we cannot open the app after some time? Because the ADB TCP/IP number has changed, or does something else happen that we cannot open the app? Do the removed permissions activate again, or do they stay removed?

### Additional context

I'm sorry if it's hard to read. I tried to describe it as best as I could.

**Comment by MuntashirAkon** [comment]
> Do the removed permissions activate again, or do they stay removed?

They stay removed.
