### ISSUE TITLE
installing apps with different signatures

### ISSUE THREAD

**Issue by cimon-bkr** [MuntashirAkon/AppManager#1239]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

devices with root such as miui use modded apps with different signatures after disabling signature vérification.
 but app manager doesn't allow installing apps with different signatures 

### Describe the solution you'd like

add an install anyway button on apps with different signatures

**Comment by MuntashirAkon** [comment]
WDYM? App Manager already has the feature.

**Comment by MuntashirAkon** [comment]
Ah, this is specific to the system apps, I think.

**Comment by cimon-bkr** [comment]
Yes it only allows user apps no system apps

**Comment by MuntashirAkon** [comment]
Fixed in bd4babf8f82ad8079a1a87c5099d27d9ec00d4f8
