### ISSUE TITLE
Upgrade (& unify) filter options to allow NOT conditions

### ISSUE THREAD

**Issue by tew42** [MuntashirAkon/AppManager#1242]
**Please check before submitting an issue**
- [x]  I am using the latest version of App Manager
- [x]  I have searched the issues and haven't found anything relevant
- [x]  I have read the docs

**Describe a description of the new feature**
We can already search for Installed/Uninstalled apps, User/System apps, With/Without Backup.

But other filters are positive-only (Frozen, Running, Activities, Rules, Splits, SAF, SSAID, ...), i.e., it's very difficult to find apps that DON'T meet those criteria. For my own purposes, NOT frozen would be the most relevant, but I'm sure the others also have use cases.

In my mind, the ideal solution would be to unify the filter buttons so for ANY filter characteristic we can mark "YES", "NO", and "unfiltered"

**Comment by tew42** [comment]
never mind, just called something different

**Comment by Mikanodav15** [comment]
> **Please check before submitting an issue**
> - [x]  I am using the latest version of App Manager
> - [x]  I have searched the issues and haven't found anything relevant
> - [x]  I have read the docs
> 
> **Describe a description of the new feature**
> We can already search for Installed/Uninstalled apps, User/System apps, With/Without Backup.
> 
> But other filters are positive-only (Frozen, Running, Activities, Rules, Splits, SAF, SSAID, ...), i.e., it's very difficult to find apps that DON'T meet those criteria. For my own purposes, NOT frozen would be the most relevant, but I'm sure the others also have use cases.
> 
> In my mind, the ideal solution would be to unify the filter buttons so for ANY filter characteristic we can mark "YES", "NO", and "unfiltered"

**Comment by MuntashirAkon** [comment]
Advanced filtering will be implemented once I am finished with #321.

**Comment by MuntashirAkon** [comment]
Superseded by #1488
