### ISSUE TITLE
System fixed permissions

### ISSUE THREAD

**Issue by AlexeyIgnashin** [MuntashirAkon/AppManager#1248]
### Describe your problem(s)

Hello,

I have a question about so called "system fixed" permissions. 

Is there any way to revoke these permissions? Not neccessarily with App Manager, but also by any other means, including Magisk modules. I have searched a lot but there is very little information about them on the Internet.

These are regular permissions except that they are granted to system apps by default and, most importantly, cannot be revoked using any means, including App Manager or ADB.

Most notable examples are `ACCESS_FINE_LOCATION `(and other location-related permissions) and `ACTIVITY_RECOGNITION `granted to Google Play services and grayed-out in the settings.

Any attempt to revoke them with App Manager results in the "could not revoke permission" message and when you attempt to do it with ADB you get this:

```
timelm:/ $ pm revoke com.google.android.gms android.permission.ACCESS_FINE_LOCATION

Exception occurred while executing 'revoke':
java.lang.SecurityException: Non-System UID cannot revoke system fixed permission android.permission.ACCESS_FINE_LOCATION for package com.google.android.gms
        at com.android.server.pm.permission.PermissionManagerService.revokeRuntimePermissionInternal(PermissionManagerService.java:1708)
        at com.android.server.pm.permission.PermissionManagerService.revokeRuntimePermission(PermissionManagerService.java:1615)
        at android.permission.PermissionManager.revokeRuntimePermission(PermissionManager.java:417)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2395)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:262)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25888)
        at android.os.Binder.shellCommand(Binder.java:950)
        at android.os.Binder.onTransact(Binder.java:834)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4980)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8960)
        at com.android.server.pm.PackageManagerServiceEx.onTransact(PackageManagerServiceEx.java:66)
        at android.os.Binder.execTransactInternal(Binder.java:1184)
        at android.os.Binder.execTransact(Binder.java:1143)
```

I have also noticed that Google Play services has the ability to grant itself system fixed permissions when it wants. 

My Google Play instance did not have any location permissions by default (because I opted out of any Google location improvement after factory reset), but it granted them to itself immediately after I reenabled the `GoogleLocationManagerService` service in App Manager by half-rebooting (for the lack of a better term, it was just like a regular reboot but way faster) the device.

This is not right. This behavior is very invasive and unchecked. There has to be a way to do something about it.

**Comment by MuntashirAkon** [comment]
These permissions are whitelisted for these applications by the vendor. Therefore, nothing could be done without root.

**Comment by AlexeyIgnashin** [comment]
I should have mentioned this, but I was talking specifically about what can be done on rooted devices. How can these permissions be revoked? App Manager with root access just shows the "could not revoke permission" message.

**Comment by MuntashirAkon** [comment]
After you discover the correct file(s), you can remove the permission from there and replace it directly or systemless-ly. I suggest you ask this question to MicroG or related forums since they are familiar with how permission whitelisting works with Gapps.

**Comment by AlexeyIgnashin** [comment]
Thanks. I had already tried to modify one of these files systemless-ly before I created this issue, but the permission was still there. Perhaps it was the wrong file - there are so many of them.

It would be nice to have a feature for this in App Manager - showing in "System Config" exactly what file is responsible for each app's system-fixed permissions. Please consider adding it in future releases.

**Comment by AlexeyIgnashin** [comment]
Actually, I think we might be talking about different kinds of permissions here, I have just remembered what I found out while investigating this. 

The permissions listed in `etc/permissions`-like directories are special permissions that can only be granted to privileged system apps. But system-fixed permissions are different from them. System-fixed permissions are just regular permissions that are granted by the system and can't be revoked by any means known to me. 

Please see the attached screenshot showing the contents of the file presumably responsible for the privileged permissions granted, for example, to Google Play Store.

App Manager's System Config is shown on the left and on the right is App Manager showing all the permissions granted to this app.

The read/write external storage permissions are system-fixed and can't be revoked, but they are not listed in the privileged permissions file - the file's contents matches what App Manager shows on the left (I have shown some matches with arrows). App Manager also does not tag the external storage permissions as privileged (unliked the arrowed ones) and yet they can't be revoked.
![image](https://github.com/MuntashirAkon/AppManager/assets/5496980/f36cc945-449e-4f53-a866-4fd184b9bd5d)

**Comment by drogga** [comment]
_While I was researching on how to grant/allow notifications listener access when you can't from the UI (in WSA, not the latest), like in/under "special app access" > "notification access" and manually adding it to the item containing them in the config. db. table (not exactly what's being discussed here, but I decided to share some background on what lead me here),_ I was surprised to find out how little (and basically nothing) can actually be done to/with the permissions with root, even with other similar apps that can supposedly manage permissions and I tried everything I could find, but unfortunately it looks like the really important ones and those that actually/really matter are too special and nothing can be done with them without much tinkering with the system, like modifying stuff, which is super dangerous, even for the experienced, so I concluded that my options it to modify the Manifest when possible/suitable and sadly I had to drop that idea here.

**Comment by drogga** [comment]
_While I was researching on how to grant/allow notifications listener access when you can't from the UI (in WSA, not the latest), like in/under "special app access" > "notification access" and manually adding it (an app I was testing) to the item containing them in the config. db. secure table, which is "enabled_notification_listeners" (not exactly what's being discussed here, but I decided to share some background on what led me here),_ I was surprised to also find out how little (and basically nothing) can actually be done to/with the permissions with root, even with other similar apps that can supposedly manage permissions and I tried everything I could find, but unfortunately it looks like the really important ones and those that actually/really matter are too special and nothing can be done with them without much tinkering with the system, like modifying stuff, which is super dangerous, even for the experienced, so I concluded that my option is to modify the Manifest when possible/suitable and sadly I had to drop that idea here.

**Comment by AlexeyIgnashin** [comment]
@drogga there is this app called "Permission Manager X" that claims it can revoke system-fixed permissions: 

https://mirfatif.github.io/PermissionManagerX/help/en/#faq40

I have tried it once and it did not work, probably because it requires a paid version for this. 

It is not explained **how** exactly it does it, but I reckon the answer may be in the adb log I attached to my original message: `Non-System UID cannot revoke system fixed permission`

So, you need a system UID to revoke it. Or better yet, prevent them from being granted in the first place by removing them from some file where they are listed.

> it looks like the really important ones and those that actually/really matter are too special

It is really important for Google Play services to have access to ACTIVITY_RECOGNITION then? No, I am not buying that. Pretty sure it will work just fine without it.

**Comment by MuntashirAkon** [comment]
> The read/write external storage permissions are system-fixed and can't be revoked, but they are not listed in the privileged permissions file - the file's contents matches what App Manager shows on the left (I have shown some matches with arrows). App Manager also does not tag the external storage permissions as privileged (unliked the arrowed ones) and yet they can't be revoked.

This particular section lists the whitelisted system permissions (hence, `privapp`), not permission flags. Permission flags can be set via `exception` tags which aren't listed in system config right now. (This is why I said file(s)). However, you can check if a permission is SYSTEM_FIXED by long-clicking on the permission.

**Comment by MuntashirAkon** [comment]
> It is not explained **how** exactly it does it, but I reckon the answer may be in the adb log I attached to my original message: `Non-System UID cannot revoke system fixed permission`

Yes, you can revoke it as follows:

```
su -c 1000 pm revoke <package> <perm>
```

This isn't integrated into AM yet, because it may have other unknown consequences. Permissions, unfortunately, largely remained unexplored, because this is something one man cannot do, especially, someone with only four years of experience in working with the Android system. Many people have tried to make sense of permissions before, but it's quite difficult to determine what works and what doesn't, not to mention heavy modifications by the vendors.

**Comment by drogga** [comment]
@AlexeyIgnashin PMX is junk, they just want your money.
That much I will comment, because it appears that even tho it's on topic and not off-topic one, my comment was marked as duplicate, I just don't see or know on what, which tells me that the Owner/Maintainer don't want or like people to engage here at all and discuss things very much related to not only the app, but also to the issue ticket topic which is Closed btw, so it's not that my comment harms or anything, but OK if that's how it's going to be, then not only I will stop engaging in reporting problems or give any feedback, but I will also stop helping, like how I just did in his SetEdit repo. Bye from me.
_Muntashir, if you don't like this comment, then I will just delete it - no problem, just say so or react on it with thumbs-down emoji._

**Comment by MuntashirAkon** [comment]
> @AlexeyIgnashin PMX is junk, they just want your money. That much I will comment, because it appears that even tho it's on topic and not off-topic one, my comment was marked as duplicate, I just don't see or know on what, which tells me that the Owner/Maintainer don't want or like people to engage here at all and discuss things very much related to not only the app, but also to the issue ticket topic which is Closed btw, so it's not that my comment harms or anything, but OK if that's how it's going to be, then not only I will stop engaging in reporting problems or give any feedback, but I will also stop helping, like how I just did in his SetEdit repo. Bye from me. _Muntashir, if you don't like this comment, then I will just delete it - no problem, just say so or react on it with thumbs-down emoji._

You posted the same comment two times, that's why, and now you deleted one and claiming otherwise. I generally do not take anything personally unlike you.

![Screenshot 2023-12-19 at 21 27 16](https://github.com/MuntashirAkon/AppManager/assets/8176128/79c92f96-3d82-45d3-bef3-546d9e825003)

**Comment by drogga** [comment]
I'm really sorry for this, but by the time I posted that one, the first one with many edits was already deleted.

**Comment by MuntashirAkon** [comment]
> I'm really sorry for this, but by the time I posted that one, the first one with many edits was already deleted by me.
> I would like to personally apologize you, sorry again.

Reinstated. When I marked it as duplicate, the previous comment was still there.

> If you don't mind me asking - from where / what is this screenshot taken ?

Thunderbird.

Regarding your other accusation: My projects are very much personal, for my own use (except Metro for some complicated reasons). I explicitly made them public for the benefit of others. This is why I do not use any organisation handle unlike many others who develop/maintain a wide range of apps. So, I have specific plans and I know the directions of my projects better than anybody else. This is why anything people suggest are only suggestions and nothing else. My projects are fully reproducible, copylefted, and available on F-Droid. I also try my best to write as much documentation I can. Hence, anybody can take over if they do not agree with me. But I believe that most returning users are happy with the direction App Manager is going (may not true for other projects because I do not actively maintain them), and there's already exists no exact alternative for the app. I'm not boasting anything here (unlike some people might think), what I'm stating are the facts. The primary reason for developing App Manager was the vacancy that I felt. Many people like you have helped me with ideas, encouragement and funding which are equally important for sustaining a large-scale project like this, and I believe every user to be an owner of the app and contributor to the project. However, the project did prove to be beneficial to me in some respect, but, I believe that the amount of effort I've put into this project makes me worthy of it.

**Comment by drogga** [comment]
I saw > Thank you (for the ThunderBird too). I guarantee you 100% for sure that I did like ~10 edits, refreshed (Bromite on Android) the page, copied it, deleted it, refreshed again to make sure it's not there, because GH will also automatically mark it as duplicate - it wasn't here, so I posted the previously copied text and didn't edited it after.

> OK if that's how it's going to be, then not only I will stop engaging in reporting problems or give any feedback, but I will also stop helping, like how I just did in his SetEdit repo. Bye from me.

^This was me overreacting... (I think your response was based mainly on that part), pls. accept my apologies.
I don't think there's need to dig any farther with this, so if you accept my apologies, let's just drop this ?, we can continue the permissions discussion tho if there's need, but I intend to test this `su -c 1000 pm revoke <package> <perm>` on x86 and see what it can revoke and what not, please consider adding it to A.M. as very experimental and dangerous.
Thank You in advance ;)

**Comment by AlexeyIgnashin** [comment]
> but I intend to test this su -c 1000 pm revoke <package> <perm> on x86 and see what it can revoke and what not

Please report your results here. I will test it as well when I have time.

**Comment by AlexeyIgnashin** [comment]
@MuntashirAkon by the way I followed your instructions yesterday, used a long-click on the ACCESS_FINE_LOCATION permission granted to Google Play services and got a very odd result. To my surprise the dialog window said it was actually USER_FIXED but ADB (see the log in my original message) claims it is SYSTEM_FIXED.

![image](https://github.com/MuntashirAkon/AppManager/assets/5496980/ffe9acf2-1c3e-4e39-9142-99dde7a38624)

**Comment by AlexeyIgnashin** [comment]
```
timelm:/ $ su -c 1000 pm revoke com.google.android.gms android.permission.ACTIVITY_RECOGNITION
/system/bin/sh: 1000: inaccessible or not found
127|timelm:/ $ exit
```

Getting this when I try to run the revoke command in Termux and adb both.

**Comment by MuntashirAkon** [comment]
> ```
> timelm:/ $ su -c 1000 pm revoke com.google.android.gms android.permission.ACTIVITY_RECOGNITION
> /system/bin/sh: 1000: inaccessible or not found
> 127|timelm:/ $ exit
> ```
> 
> Getting this when I try to run the revoke command in Termux and adb both.

My mistake. The correct command is the following:

```sh
su - 1000 -c pm revoke com.google.android.gms android.permission.ACTIVITY_RECOGNITION
```

This basically means running as `1000` UID which is the system UID.

**Comment by AlexeyIgnashin** [comment]
Thank you, I has worked with adb, the permission is gone now and remains revoked after a reboot. Interestingly thought, it cannot be granted back by any means.

When you run `su - 1000 -c pm grant com.google.android.gms android.permission.ACTIVITY_RECOGNITION` it is not shown as enabled by Android - just the same grayed out radio buttons as before, but this time it is disabled. If you try to reenable it with App Manager, the slider moves to the right, but the permission is still not granted and the slider goes back to the left if you reopen the permissions tab.

Not that I am going to miss it, but how can you grant a system-fixed permission again?

> This isn't integrated into AM yet, because it may have other unknown consequences.

Please consider adding this feature to App Manager with some kind of warning. Or, at the very least, consider adding information about system-fixed permissions and how to deal with them to the documentation because there is very little information about them on the internet.

**Comment by MuntashirAkon** [comment]
> Not that I am going to miss it, but how can you grant a system-fixed permission again?

No idea.

**Comment by AlexeyIgnashin** [comment]
@MuntashirAkon Something very odd is going on with privileged permissions. I have been trying to figure out how to revoke them permanently without success.

I decided to try to revoke `android.permission.PACKAGE_USAGE_STATS` from Google Play Store (com.android.vending)

First, I located the file that whitelisted these privileged permissions on my device, commented this permission out and created a Magisk module to replace the file systemless-ly as you suggested earlier:

> After you discover the correct file(s), you can remove the permission from there and replace it directly or systemless-ly. I suggest you ask this question to MicroG or related forums since they are familiar with how permission whitelisting works with Gapps.

I verified that this is the right file by double-checking it in App Manager as you also suggested:

> You can also find this whitelist in App Manager > System Config > privapp-permissions

The permission is indeed not shown in `privapp-permissions` for this package when it is commented out in the whitelist file.

Commenting the permission out was not enough to revoke it, so I tried to revoke `android.permission.PACKAGE_USAGE_STATS` in App Manager on the "Uses permissions" tab since there is a slider for this one. The permission was revoked successfully as shown by App Manager. I also double-checked that it had been revoked by running `dumpsys package com.android.vending | grep PACKAGE_USAGE_STATS`

The problem is that the permission is back after I reboot the device every time I do that. I have also tried to run the `pm revoke` command in Termux. The behavior is exactly the same as with App Manager.

Do you have any idea why the permission is granted like that?
