### ISSUE TITLE
Allow user to select whether to restore app on work or personal profile

### ISSUE THREAD

**Issue by tadekdudek** [MuntashirAkon/AppManager#1249]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

When restoring a backup, it always restores it on both personal and work profile. It should allow user to choose where the backup should be restored.

### Describe the solution you'd like

There should be a dialog when clicking the restore button where to restore backup like that shown when clicking on app installed on both profiles.

**Comment by shuvashish76** [comment]
I've mentioned my suggestions in #1220

**Comment by MuntashirAkon** [comment]
Duplicate of #1220
