### ISSUE TITLE
App info loading very slow sometimes

### ISSUE THREAD

**Issue by fusionneur** [MuntashirAkon/AppManager#125]
**Describe the bug**
App loading is very slow sometimes (a couple of minutes), but in the end loads. After it self unbugs, clicking other apps open fast

**To Reproduce**
Steps to reproduce the behaviour:
Click on a random app
App details loading very slow

**Expected behavior**
App loading should be fast as usual

**Screenshots**

**Crash logs**

**Device info**
 - Device: [e.g. One Plus 7T Pro]
 - OS Version: [e.g. Android 10]
 - App Manager Version: [e.g. v2.5.16 pre 364]
 - Mode: root

**Additional context**

**Comment by MuntashirAkon** [comment]
This probably depends on device, memory, processor and reading speed (of internal storage). On my device, I've tried as many as thirty apps, they all opened without any lag.

**Comment by fusionneur** [comment]
OP 7T PRO is super fast so it is unrelated to hardware spec in my case. I am not very sure how to reproduce as it happens randomly, but I will try to find a way

**Comment by MuntashirAkon** [comment]
Could you please confirm it on v2.5.17?

**Comment by fusionneur** [comment]
Seems to be fixed. Will let you know if i experience it again. Thank you!

**Comment by MuntashirAkon** [comment]
@fusionneur this problem is caused by AM local server. If the server is not running, it starts the server and _then_ loads the app details page. This is not limited to this page though. It can happen in the main page, running apps page and app ops tab. Once the server is started (or if the server isn't busy due to some error), everything will work as expected.

**Comment by fusionneur** [comment]
it happened again today.. very slow loading, but this time eventually crashed. i sent you an email with the crash

**Comment by MuntashirAkon** [comment]
> it happened again today.. very slow loading, but this time eventually crashed. i sent you an email with the crash

That's a different error. See #135.
