### ISSUE TITLE
failed to connect ADB (wireless debug bridge)

### ISSUE THREAD

**Issue by guiilerm1** [MuntashirAkon/AppManager#1253]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

the appmanager cannot boot via ADB, I provide the pairing code and port and the appmanager connects but does not start, it seems to be in a loop state.

### Device info

- Device: Poco X5 Pro
- OS Version: MIUI 14.0.7
- App Manager Version: 4.0.0 alpha02
- Mode: ADB

**Comment by guiilerm1** [comment]
I managed to 'resolve' had to connect some things related to USB.

**Comment by MuntashirAkon** [comment]
Well, it's Xiaomi. So, it's basically [Murphy's Law](https://en.wikipedia.org/wiki/Murphy's_law).
