### ISSUE TITLE
Couldn't import signing key, error "Could not read the Keystore" displayed as toast message.

### ISSUE THREAD

**Issue by jasonkhoo87** [MuntashirAkon/AppManager#1254]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Error "Could not read the Keystore" displayed as toast message when you try to import the JKS Keystore file from signing key.

### To Reproduce

1. Go to "Settings"
2. Go to "APK Signing"
3. Go to "Signing key"
4. Select "Import"
5. Default option is "JKS"
6. Enter password and select KeyStore file (.jks) using Android standard file manager.
7. Click on "OK"
8. Error "Could not read the Keystore" displayed as toast message.

### Expected behavior

Should be able to import the Keystore file without error.

### Screenshots

![Screenshot_2023-12-19-19-17-04-45](https://github.com/MuntashirAkon/AppManager/assets/2129787/897a94bd-7d39-4280-a6ed-ea3b7673c738)

### Logs

[file_836762889984002327.zip](https://github.com/MuntashirAkon/AppManager/files/13714988/file_836762889984002327.zip)

### Device info

- Device: Oppo A31
- OS Version: Android 9
- App Manager Version: 4.0.0-alpha02 (435)
- Mode: NonRoot

**Comment by MuntashirAkon** [comment]
It reports the following:

```
12-19 19:21:49.414 E/KeyPairImporterDialogFragment(27842): java.io.IOException: Invalid keystore format
12-19 19:21:49.414 E/KeyPairImporterDialogFragment(27842): 	at android.sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:604)
12-19 19:21:49.414 E/KeyPairImporterDialogFragment(27842): 	at android.sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:54)
12-19 19:21:49.414 E/KeyPairImporterDialogFragment(27842): 	at java.security.KeyStore.load(KeyStore.java:1484)
12-19 19:21:49.414 E/KeyPairImporterDialogFragment(27842): 	at io.github.muntashirakon.AppManager.crypto.ks.KeyStoreUtils.listAliases(KeyStoreUtils.java:112)
12-19 19:21:49.414 E/KeyPairImporterDialogFragment(27842): 	at io.github.muntashirakon.AppManager.settings.crypto.KeyPairImporterDialogFragment.lambda$onCreateDialog$11$io-github-muntashirakon-AppManager-settings-crypto-KeyPairImporterDialogFragment(KeyPairImporterDialogFragment.java:154)
12-19 19:21:49.414 E/KeyPairImporterDialogFragment(27842): 	at io.github.muntashirakon.AppManager.settings.crypto.KeyPairImporterDialogFragment$$ExternalSyntheticLambda12.run(Unknown Source:6)
12-19 19:21:49.414 E/KeyPairImporterDialogFragment(27842): 	at java.lang.Thread.run(Thread.java:764)
```

Was it a valid JKS file?

**Comment by jasonkhoo87** [comment]
Hi, 

Yes, it is a valid generated JKS file, I am using apksigner to generate it. 

Just to update after few days searching method to convert JKS key, I found this software "https://keystore-explorer.org/" for PC, then using same JKS keystore to export to PKCS#12 format.

By using the same import method, just different in selecting P12 for the key type. App Manager able to import it without problem.

My problem is solved now since I was able to import the key to App Manager. Should this be close?

**Comment by MuntashirAkon** [comment]
> Yes, it is a valid generated JKS file, I am using apksigner to generate it.

Can you generate a dummy JKS file and share it here with the passwords, etc.? I wonder why the app is not recognising it.

**Comment by jasonkhoo87** [comment]
![Screenshot_2023-12-31-17-15-46-83](https://github.com/MuntashirAkon/AppManager/assets/2129787/98e09a73-53f7-4cee-8970-3ca54b5941c7)
[https://file.io/kxtxdj3MsXA0](url)

I generated dummy JKS with alias "test" and password "12345678".
I shared the screenshot info of the generated key s well.

**Comment by drogga** [comment]
Your link actually leads to: `https://github.com/MuntashirAkon/AppManager/issues/url`, you can edit to fix it {I will delete this comment after you do ;)}

**Comment by MuntashirAkon** [comment]
Thanks. As you can see in the image, it's a PKCS12 keystore, not a Java KeyStore (JKS). Hence, you should have selected `PKCS #12 KeyStore (P12)` instead.
