### ISSUE TITLE
stuck on initializing at first run

### ISSUE THREAD

**Issue by AeliusSaionji** [MuntashirAkon/AppManager#1260]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Upon installing 3.1.4 fresh, App Manager will show the secret key, then "initializing".

It only advances when I toggle USB debugging.

### Device info

- Device: Xperia 1 V
- OS Version: 14
- App Manager Version: 3.1.4
- Mode: ADB

### Additional context

I am running `adb tcpip 5555` from within termux. Perhaps that is unexpected?

**Comment by YGOmod** [comment]
@AeliusSaionji I had same problem for weeks, I'm running adb as well, I was always reinstalling app but at the end I came up with simple solution.. you need to enable all permissions app is asking.. I had notifications disabled and after enabling it, it works perfectly 🤣🤣 give it a try, maybe it will solve your problem too 😀👍🏻

**Comment by MuntashirAkon** [comment]
> @AeliusSaionji I had same problem for weeks, I'm running adb as well, I was always reinstalling app but at the end I came up with simple solution.. you need to enable all permissions app is asking.. I had notifications disabled and after enabling it, it works perfectly 🤣🤣 give it a try, maybe it will solve your problem too 😀👍🏻

Should be fixed by 93ce56cc89f9fc4fd109098370b933ff1f1bb430
