### ISSUE TITLE
Move user application to the system and backwards

### ISSUE THREAD

**Issue by wuniversales** [MuntashirAkon/AppManager#1267]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

I find it strange that having so many options, you can't move the user application to the system, and the other way around, move from the system to the user application.
Is it pending to add the function?
Thanks, best regards

**Comment by MuntashirAkon** [comment]
**App Manager never modifies the system partition.** However, something similar can be done systemless-ly in the future via Magisk (#150). Since you're using SuperSu, you won't get such features. Consider using another app if you need this feature.
