### ISSUE TITLE
App Usage stopped working on e/OS 1.18-s (android 12), Samsung Galaxy S10+ SM-G975F/DS

### ISSUE THREAD

**Issue by WizardNumberNext** [MuntashirAkon/AppManager#1270]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I am running e/OS from 1.16-s on Samsung Galaxy S10+ SM-G975F/DS. I update pretty soon after update becomes available. I have USB debugging, rooted debugging, wireless debugging and ADB over TCPIP on. App manager is paired with wireless debugging. It used to read App Usage. App manager works over wireless debugging, ADB over TCPIP and root (phone is not rooted, but rooted debugging gives some extra freedom).
I have tried to disable and reenable Usage permissions, but this haven't solve it. I have cleared cache, nothing. Cleared cache and data, nothing. Reinstalled App manager, nothing. There is only reboot left, whi h dream due to GPS week roll over bug, which hits me every reboot now. 

I have rebooted. No change.

It may or may have something to do with me changing date 2038-11-21 to workaround GPS week roolover.

I have tried to plug phone to USB, no change. I even toggled USB debugging with and without rooted debugging (all combinations). All changes with verification for USB debugging from computer.

How can I help to resolve issue. I am definitely not only one, who got such issue.

### Device info

- Device: Samsung Galaxy S10+ SM-G975F/DS
- OS Version: e/OS 1.18-r
- App Manager Version: 3.1.4
- Mode: root, ADB, wireless debugging

**Comment by MuntashirAkon** [comment]
Try disabling and enabling usage permission from Android settings. Usage permission is composed of a permission and an app op which often cause issues. Otherwise, install a debug version from GitHub actions and take some logs when you open the app usage page.

**Comment by WizardNumberNext** [comment]
The problem disappeared after upgrade to 1.19.1-s. I shall monitor it. I did reboot. I did try with permissions, but that didn't help.

**Comment by MuntashirAkon** [comment]
In that case, it's likely a regression error on the OS' side. I'm closing the issue. Feel free to open it again in case it pops up in the future.
