### ISSUE TITLE
Tracker in Amazon Music cannot be disabled

### ISSUE THREAD

**Issue by jw243** [MuntashirAkon/AppManager#128]
When scanned with exodus, 6 trackers are found:

![Screenshot_20201011-203502_App_Manager](https://user-images.githubusercontent.com/13139555/95687310-07c94c00-0c03-11eb-9c8c-876782c5b762.png)

In the app info page, however, app manager does not report any trackers:

![Screenshot_20201011-203431_App_Manager](https://user-images.githubusercontent.com/13139555/95687324-29c2ce80-0c03-11eb-82fd-6bc2cf2fa877.png)

I suppose, this also means that the trackers won't be disabled upon clicking **block trackers**.

**Device info**
 - Device: Galaxy Tab S2 8.0
 - OS Version: LineageOS 16.0 MicroG version
 - App Manager Version: v2.5.13
 - Mode: root

Any idea why this happens?

**Comment by MuntashirAkon** [comment]
Trackers ≠ tracking components.

You can only block tracking components, not tracker classes. Tracker classes can only be removed by modifying the apk file itself. Also, the exodus scanner (like the original exodus scanner) does a static scanning of the apk file, which means it doesn't guarantee that all the libraries are actually used by the app.
