### ISSUE TITLE
Difference between Tracker & Logger

### ISSUE THREAD

**Issue by Rexadev** [MuntashirAkon/AppManager#1281]
### Describe the existing feature/documentation

 Does AppManager also like warden blocks both Trackers and Loggers or only tracker ?
https://gitlab.com/AuroraOSS/AppWarden

![image](https://github.com/MuntashirAkon/AppManager/assets/62152714/b586d36a-21a8-4273-a5cc-199f0ceaaf13)

**Comment by MuntashirAkon** [comment]
Loggers have no significance on their own unless the logs are sent automatically to a server over the Internet, in which case it's considered a tracker. Besides, most apps have their own custom way to store logs (including App Manager) which are virtually undetectable without a thorough analysis of the APK which is beyond the purpose of the app. Hence, in App Manager, we only consider trackers, though some loggers may appear as utilities in the Libraries section in the Scanner page.
