### ISSUE TITLE
Set permission for all apps with certain permissions.

### ISSUE THREAD

**Issue by Rexadev** [MuntashirAkon/AppManager#1282]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

https://github.com/MrBIMC/RunInBackgroundPermissionSetter

**Comment by MuntashirAkon** [comment]
You need to be more specific about your feature request. I do not usually have the time to investigate another app understand the feature.

If you mean `RUN_IN_BACKGROUND` (63) app op, you can already filter the corresponding apps in the 1-Click Ops page. If you need to block it from specific apps, you can either use Batch Ops or create a new profile with the said applications and app ops field set to `RUN_IN_BACKGROUND RUN_ANY_IN_BACKGROUND` or `63 70`.

**Comment by Rexadev** [comment]
Add option to set a permission for all apps for example see all apps that use RUN_IN_BACKGROUND RUN_ANY_IN_BACKGROUND and use a toggle to turn it off or on.
@MuntashirAkon

**Comment by MuntashirAkon** [comment]
> Add option to set a permission for all apps for example see all apps that use RUN_IN_BACKGROUND RUN_ANY_IN_BACKGROUND and use a toggle to turn it off or on.

That's more or less what **1-Click Ops** > **Set mode for app ops...** does. I don't see the need for any specific option for this other than #321.

**Comment by Rexadev** [comment]
> That's more or less what **1-Click Ops** > **Set mode for app ops...** does. 

That applies to all apps ?

> I don't see the need for any specific option for this other than #321.

Finder seems great to set  "a permission for all apps for example see all apps that use RUN_IN_BACKGROUND RUN_ANY_IN_BACKGROUND and use a toggle to turn it off or on."

**Comment by MuntashirAkon** [comment]
> That applies to all apps ?

No. There's a selection dialog that allows you to choose the apps. It lists only the apps that does not have the given **mode** to make the list a bit short.

**Comment by Rexadev** [comment]
@MuntashirAkon Where to find list of AppOps numbers ?

**Comment by Rexadev** [comment]
1.  Where to find list of AppOps numbers ?
2. IT would be nice if there is a drop down with appOps list.
3. It shows error "could not parse some numbers" for `70` `63 70` `RUN_IN_BACKGROUND`

@MuntashirAkon

**Comment by MuntashirAkon** [comment]
> 1. Where to find list of AppOps numbers ?

You can find many app op constants in the App Details page > App Ops tab of an app. You can find a list in the **Set custom app op** in the three-dots menu in the same tab.

> 2\. IT would be nice if there is a drop down with appOps list.

This isn't possible right now because the field is not interactive. You can create a feature request if you want.

> 3\. It shows error "could not parse some numbers" for `70` `63 70` `RUN_IN_BACKGROUND`

The issue was fixed in a later release.
