### ISSUE TITLE
Enable/disable features should probably be in another Settings section

### ISSUE THREAD

**Issue by Porkepix** [MuntashirAkon/AppManager#1290]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Currently if one wants to enable or disable a feature in the application, this is located into `Settings > Appearance > Enable/disable features`. As it was mentioned in another issue, I wanted to disable a feature and was unable to find where to do this, looking many times in the places that seemed to fit the most. To me, appearance was so obviously not the place it would be that I didn't checked there, and only ended up seeing  out of sheer luck the word feature in the description text.

I do think this deserves its own Settings section, or to be in a place a little bit more obvious like Advanced.

PS: For the context, as I think I get the idea why it ended up there as I guess some features if enabled have to be present or not in the application's menu and therefore end up hidden and modify menu's "appearance". But I was looking to disable interceptors… which have no menu entry, so even that small explanation doesn't fit here.

### Expected behavior

Find this feature in a more obvious place.

### Device info

App Manager 1.3.4.

**Comment by Mitezuss** [comment]
And can be disabled by default?

**Comment by MuntashirAkon** [comment]
You're right. It was put there because it involves the appearances of App Manager itself, not just UI/UX. It was found to be the best place then because the advanced settings were not available at the time.

**Comment by MuntashirAkon** [comment]
From v4.0.0-beta01, some of the features can also be enabled/disabled in other part of settings. So, I guess this issue can now be closed.
