### ISSUE TITLE
same question i have

### ISSUE THREAD

**Issue by htndbr** [MuntashirAkon/AppManager#1291]
### Describe the existing feature/documentation

1-Click Ops > Perform runtime optimization

dex2oat compiler filter > everything-profile
no 1st box
yes 2nd box
no 3rd box
yes 4th box

Click Run

after some mintutes i got Done notfication.

### Describe your problem(s)

if i want back to default what i need to do?

- only possible by pressing the "Reset to Default" in "Perform runtime optimization"?
- will clearing Dalvik/Cache in twrp reset it?

### Additional context

thanks for an amzing app

**Comment by MuntashirAkon** [comment]
Clearing Dalvik cache will trigger a rebuild using the default optimisation options. So, I guess both options will work as expected if they follow the AOSP. But a vendor may choose to do things differently.
