### ISSUE TITLE
Unblock components

### ISSUE THREAD

**Issue by GirishKumarSharma** [MuntashirAkon/AppManager#1295]
### Describe the existing feature/documentation

I accidentally block all components of all apps (1 click ops) and now other than system apps; no user apps including this App Manager is also not working even after adb install io.github.muntashirakon.AppManager_v427.apk.

How do I resolve the issue?

**Comment by MuntashirAkon** [comment]
You can follow this tutorial: https://github.com/amcommunity/TipsAndTricks/issues/10

**Comment by GirishKumarSharma** [comment]
Is there any possibility to unblock all the components of all user apps in one go as it seems me tough for me because to access the file in root partition my file explorer com.mixplorer_v23041810.apk is also not working.

**Comment by MuntashirAkon** [comment]
> Is there any possibility to unblock all the components of all user apps in one go as it seems me tough for me because to access the file in root partition my file explorer com.mixplorer_v23041810.apk is also not working.

First unblock all components of App Manager, and then reset all rules from the settings.

**Comment by MuntashirAkon** [comment]
I hope your problem was solved. Closing the issue. Feel free to ask more questions if you didn't solve it.
