### ISSUE TITLE
AppManager ADB over TCP not working on new Fire TV 4K Max

### ISSUE THREAD

**Issue by Werve** [MuntashirAkon/AppManager#1296]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I tried AppManager v3.1.4 Stable with Fire TV 4K Max 2 Gen (Android 11) but both auto mode and ADB on TCP fall back to no-root.

Shizuku after two tries with the 5555 option it connected.
![307151390-56c71bc0-8b5a-4ba7-a325-8e9253338e51](https://github.com/MuntashirAkon/AppManager/assets/13850028/7cb6f340-0c7c-47a2-a35c-de46bf401781)

Instead, with the Fire TV 4K Max 1 Gen (Android 9) AppManager worked properly.

### Logs

Logs using AppManager_v4.0.0-alpha02-DEBUG#2645:
[logs-2024-02-22-22-49-46.zip](https://github.com/MuntashirAkon/AppManager/files/14379725/logs-2024-02-22-22-49-46.zip)

### Device info

- Device: Fire TV 4K Max 2nd Gen
- OS Version: 11
- App Manager Version: 3.1.4 Stable
- Mode: ADB/NonRoot

**Comment by MuntashirAkon** [comment]
Did you enable logging debug info in Matlog? It appears that it didn't take any debug logs. I've only found the following error but not any debug info which should've been printed before this:

```
java.io.IOException: java.io.IOException: Could not create session
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.checkConnect(LocalServer.java:116)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.<init>(LocalServer.java:90)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.getInstance(LocalServer.java:48)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.restart(LocalServer.java:179)
	at io.github.muntashirakon.AppManager.settings.Ops.autoDetectRootSystemOrAdbAndPersist(Ops.java:357)
	at io.github.muntashirakon.AppManager.settings.Ops.init(Ops.java:221)
	at io.github.muntashirakon.AppManager.settings.MainPreferencesViewModel.lambda$setModeOfOps$4$io-github-muntashirakon-AppManager-settings-MainPreferencesViewModel(MainPreferencesViewModel.java:126)
	at io.github.muntashirakon.AppManager.settings.MainPreferencesViewModel$$ExternalSyntheticLambda12.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.IOException: Could not create session
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.getSession(LocalServerManager.java:88)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.start(LocalServerManager.java:124)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.checkConnect(LocalServer.java:111)
	... 12 more
Caused by: java.lang.Exception: Server wasn't started.
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.useAdbStartServer(LocalServerManager.java:225)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.startServer(LocalServerManager.java:254)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.getSession(LocalServerManager.java:86)
	... 14 more
```

**Comment by Werve** [comment]
I had left it with the default setting, which is verbose so they should be included:

![image](https://github.com/MuntashirAkon/AppManager/assets/13850028/f756fbd5-1d97-4e7f-b6f5-aca6af013490)

**Comment by MuntashirAkon** [comment]
> I had left it with the default setting, which is verbose so they should be included:
> 
> ![image](https://private-user-images.githubusercontent.com/13850028/307265486-f756fbd5-1d97-4e7f-b6f5-aca6af013490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzgzNjMsIm5iZiI6MTcwODY3ODA2MywicGF0aCI6Ii8xMzg1MDAyOC8zMDcyNjU0ODYtZjc1NmZiZDUtMWQ5Ny00ZTdmLWI2ZjUtYWNhNmFmMDEzNDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA4NDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Yjg3OTBkYjkzZTIxOTBmYzQ4ZDJjMmQ4OWYyZDhkMGU5YmVlODNlYjQwNjk3OTViZjkwN2Y2NTkzODNhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g28_B5zC7efnBEPNtK60Su0WZOs0TwXFMWKYGfsTKTk)
> 
> I will try to recapture

I tried filtering all the log entries with ` D/` and found nothing.

**Comment by Werve** [comment]
I set only Debug in Matlog and captured two more times.
[2024-02-23-09-47-47.zip](https://github.com/MuntashirAkon/AppManager/files/14383385/2024-02-23-09-47-47.zip)

**Comment by MuntashirAkon** [comment]
> I set only Debug in Matlog and captured two more times. [2024-02-23-09-47-47.zip](https://github.com/MuntashirAkon/AppManager/files/14383385/2024-02-23-09-47-47.zip)

Still no debug logs. No idea what's going on with it. Can you extract this file? `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`

**Comment by Werve** [comment]
> > I set only Debug in Matlog and captured two more times. [2024-02-23-09-47-47.zip](https://github.com/MuntashirAkon/AppManager/files/14383385/2024-02-23-09-47-47.zip)
> 
> Still no debug logs. No idea what's going on with it. Can you extract this file? `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`

Yes, but not via adb, apparently there are limitations in the new Fire TV 4K Max to adb permissions. 
I was able to extract it via Mixplorer launched from the device and granting the folder read permissions appeared.
[am.log](https://github.com/MuntashirAkon/AppManager/files/14384273/am.log)

**Comment by MuntashirAkon** [comment]
> Yes, but not via adb, apparently there are limitations in the new Fire TV 4K Max to adb permissions.

This might actually be the issue.

The response for the following command
```shell
sh /storage/emulated/0/Android/data/io.github.muntashirakon.AppManager.debug/cache/run_server.sh 60001 b5cc1db213132f4f67c728d4814eb9a9
```
was

```
sh: /storage/emulated/0/Android/data/io.github.muntashirakon.AppManager.debug/cache/run_server.sh: Permission denied
```

This means either it couldn't access `run_server.sh` via ADB or it does not have the execution permission.

**Comment by Werve** [comment]
Yes according to this article https://www.aftvnews.com/missing-storage-access-permission-in-fire-os-8-on-2nd-gen-fire-tv-stick-4k-4k-max-is-causing-issues-with-media-player-and-file-manager-apps/
that adb can no longer access "/sdcard/Android/data/" and "/sdcard/Android/obb/"

**Comment by MuntashirAkon** [comment]
> Yes according to this article https://www.aftvnews.com/missing-storage-access-permission-in-fire-os-8-on-2nd-gen-fire-tv-stick-4k-4k-max-is-causing-issues-with-media-player-and-file-manager-apps/ that adb can no longer access "/sdcard/Android/data/" and "/sdcard/Android/obb/"
> 
> This also explains the message in Shizuku's first screenshot

I guess, we need to do this for App Manager as well (an unrelated but interesting issue: #948).

**Comment by MuntashirAkon** [comment]
Latest update, I believe, has disabled access from localhost altogether.

**Comment by MuntashirAkon** [comment]
We need a starter script that can also be run from another device. This is the only solution that may work after the latest update.

**Comment by MuntashirAkon** [comment]
Should be fixed in 4f97928e97fd9da5a93c7ea1af40c682462b4e33

**Comment by Werve** [comment]
I've tried the latest debug build 4.0.0 beta01 (436) but it remains in no root mode. 
I've also tried to run the Custom commands described via adb shell with shizuku (aShell app) but both return Permission denied. 
The second command via normal shell returns file not found.

**Comment by MuntashirAkon** [comment]
Logs?

**Comment by Werve** [comment]
> Logs?

From Matlog DEBUG info:
[logs-2024-04-29-09-29-22.zip](https://github.com/MuntashirAkon/AppManager/files/15146236/logs-2024-04-29-09-29-22.zip)


From `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`
[am.zip](https://github.com/MuntashirAkon/AppManager/files/15146235/am.zip)


Note: 
After choosing the automatic mode of AppManager the RSA signature confirmation window for ADB (of Fire TV) appears and I set accept always.

I ran the two Custom Commands reported in AppManager in shell with aShell, then via Shizuku, and both returned Permission Denied.
![image](https://github.com/MuntashirAkon/AppManager/assets/13850028/746799f5-f997-49e9-ae20-8df54a445506)
