### ISSUE TITLE
Some samsung Unknown Net Policy

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1299]
### Describe the existing feature/documentation

> Policies unknown to App Manager will have a Unknown prefix along with the policy constant name and number in the hexadecimal format. Unknown policies should be reported to App Manager for inclusion.

### Describe your problem(s)

Unknown net policy

![Screenshot_20240302-010151_App Manager_1](https://github.com/MuntashirAkon/AppManager/assets/48226312/3a0c774c-642d-4789-b2a0-c6184f0fa1b6)

### Additional context

Device: Samsung J7 Prime (SM-G610F)
OS version: 8.1.0

[Here](https://github.com/shuvashish76/temp/blob/main/framework.jar) is the file for **framework.jar** from /system/framework.

Screenshot from  “App Info” page of any app > “Mobile data ~& Wi-Fi~” page

![Screenshot_20240302-012656_Settings_1](https://github.com/MuntashirAkon/AppManager/assets/48226312/beb276a1-7cf3-4711-851c-488f77d659c4)

**Comment by MuntashirAkon** [comment]
These are already documented here: https://muntashirakon.github.io/AppManager/en/#sec:net-policy

The usage is still unknown, however.
