### ISSUE TITLE
[Android 14 QPR2/March 2024] IPermissionManager internal/hidden API changes

### ISSUE THREAD

**Issue by craigacgomez** [MuntashirAkon/AppManager#1308]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Android 14 QPR2 / March 2024 update introduced method signature changes to several internal/hidden API changes in IPermissionManager. An additional method parameter "deviceId" was introduced. 

For example,
```int getPermissionFlags(String packageName, String permissionName, int userId);```
(see here https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-14.0.0_r23/core/java/android/permission/IPermissionManager.aidl)
is now
```int getPermissionFlags(String packageName, String permissionName, int deviceId, int userId);```
(see here https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-14.0.0_r29/core/java/android/permission/IPermissionManager.aidl)

This parameter requires compiling against SDK version 34 since the method used to retrieve the deviceId value ```int getDeviceId()``` method in android.android.Context was added in API level 34.

This method signature change is a breaking change and impacts multiple areas of AppManager, and causes AppManager to crash in several areas like when clicking on an app.

I've attached a basic diff of the areas where this change impacts AppManager. Please note this was a quick fix, and is not a clean implementation. This is also using the 3.1.x branch code as a base. It is not a fully functional solution since it will break AppManager on Android 14 releases before QPR2.
[AppManager_QPR2_PermissionManager.txt](https://github.com/MuntashirAkon/AppManager/files/14625975/AppManager_QPR2_PermissionManager.txt)

### To Reproduce

Open AppManager
Click on any app in the app list
AppManager crashes

### Expected behavior

Open AppManager
Click on any app in the app list
App info section of AppManager opens

### Logs

I did not keep a record the app crash log.

### Device info

- Device: Google Pixel 8 Pro
- OS Version: Android 14 (AP1A.240305.019.A1 / QPR2 / March 2024)
- App Manager Version: 3.1.4
- Mode: Root (Magisk)

**Comment by MuntashirAkon** [comment]
Thanks for sharing the insights. I'm already working on a fix which will be available in the next stable release.

**Comment by MuntashirAkon** [comment]
Do you have the release notes for this build? [The associated commit](https://android.googlesource.com/platform/frameworks/base/+/0f245abca17af3641fdd116ae079ca31c1569684%5E%21/#F5) seems accidental to me. It's highly unusual for Google to introduce a breaking change in a revision in the AOSP, or at least, I've come across such a breaking change only once.

**Comment by craigacgomez** [comment]
@MuntashirAkon , honestly, I was surprised by this change. It's not a Pixel specific change but a change included in the second quarterly feature update for Android 14. The Android security bulletin has no mention of this change. The issue tracker bug is private.

**Comment by MuntashirAkon** [comment]
> > Do you have the release notes for this build? [The associated commit](https://android.googlesource.com/platform/frameworks/base/+/0f245abca17af3641fdd116ae079ca31c1569684%5E%21/#F5) seems accidental to me. It's highly unusual for Google to introduce a breaking change in a revision in the AOSP, or at least, I've come across such a breaking change only once.
> 
> To be fair - that's not public API, no? I couldn't see Google intentionally breaking a public API but if it's an API only intended to be used by the system

It's not uncommon for vendors to make changes to the private APIs to suite their needs. But AOSP is usually very careful about making changes to the private APIs. I've seen only [one such incident](https://github.com/MuntashirAkon/AppManager/blob/b0d18fb05f23b491ce836db8b7800a20c5a186ac/hiddenapi/src/main/java/android/os/IUserManager.java#L21) before, and I track a lot of private APIs.

**Comment by MuntashirAkon** [comment]
Fixed via 985e3f77f6e5eca46742ce4eac8c2e703b8b5f31
