### ISSUE TITLE
Uses permissions are not saving after exit of the app

### ISSUE THREAD

**Issue by GirishKumarSharma** [MuntashirAkon/AppManager#1309]
### Describe your problem(s)

I am having realme c3 and when on incoming call there is no call notification, no ringtone i.e. issue of display over other apps.  So, if enables android.permission.SYSTEM_ALERT_WINDOW in Phone app by navigating to Uses permissions tab, it get enabled but again it get disabled after exiting the app i.e. it is not saving the permission.

In phone Settings when I tries to enable Display over other apps by Setting--App management--Display over other apps, it is not showing Phone app.

**Comment by MuntashirAkon** [comment]
Which version of Android?
