### ISSUE TITLE
Implement features like Storage Isolation

### ISSUE THREAD

**Issue by TheEvilSkeleton** [MuntashirAkon/AppManager#131]
**Is your feature request related to a problem? Please describe.**

There's an application called [Storage Isolation](https://play.google.com/store/apps/details?id=moe.shizuku.redirectstorage&hl=en_US&gl=US), and its goal is to isolate applications (similar to Flatpak on Linux).

**Describe the solution you'd like**
Implement features similar like Storage Isolation did.

**Additional context**
The app can also remap badly set directories in subdirectories in order to avoid apps from cluttering your storage.

Here's a video about the app: https://youtu.be/uViWKw55DYU?t=218

**Comment by MuntashirAkon** [comment]
Linking a closed source (and premium) app doesn't really help. Anyway, doesn't this depend on the Xposed framework? Because last time we discussed about this app, we found out that it didn't actually work very well without the Xposed framework.

**Comment by TuxKruger** [comment]
@MuntashirAkon, that app doesn't need Xposed Framework. It just needs Root access. There's also a magisk module for it, that improves its functioning, you can check it out here: https://github.com/Magisk-Modules-Repo/riru_storage_redirect

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon, that app doesn't need Xposed Framework. It just needs Root access. There's also a magisk module for it, that improves its functioning, you can check it out here: https://github.com/Magisk-Modules-Repo/riru_storage_redirect

Oh, sorry, I now remember it. It was this Magisk module. Like any other projects open sourced by @RikkaW, this also doesn't have a license and, therefore, it is non-free and unusable.

**Comment by RikkaW** [comment]
A living example of "I don't want to pay so I want open source" 🙃. This is why some of my projects are close sourced.

By the way, the complexity of Storage Isolation is much more than this "stitching" project. Better not to try :D

**Comment by MuntashirAkon** [comment]
> A living example of "I don't want to pay so I want open source" 🙃. This is why some of my projects are close sourced.

Tell that to the authors of Fairmail and Netguard, I'm sure they've earned more than you despite having a free (therefore, usable) license. Your source available projects have no value to the open source community because they neither have a "free" nor open source license. It doesn't matter whether you've published the source code or not. I rather think you've published them for your own benefit.

> By the way, the complexity of Storage Isolation is much more than this "stitching" project. Better not to try :D

Thanks for the compliments and the warning. Unlike many people, I like stitching because they can produce beautiful things if done carefully.

**Comment by TheEvilSkeleton** [comment]
> Linking a closed source (and premium) app doesn't really help.

The purpose of linking to the app is to show the concept of the app, not the source code

While I do admit (and should've added before) that since the app is proprietary, there will require a lot of time and effort to implement the features.

This is just a feature request. The app can already do a lot of stuff, but being able to isolate programs from user-desired storage would've been an awesome addition.

**Comment by TheEvilSkeleton** [comment]
> A living example of "I don't want to pay so I want open source" 🙃. This is why some of my projects are close sourced.

That's half the story, please don't change sentences to make us look like shit. The actual living example is "I want free, libre and accessible information therefore I want open source".

**Comment by MuntashirAkon** [comment]
> The purpose of linking to the app was to show the concept of the app, not the source code/implementation, which was why I added a YouTube video to show what the app does.

Yeah, I've understood that. This was just a remark.

> This is just a feature request. The app can already do a lot of stuff, but being able to isolate programs from user-desired storage would've been an awesome addition.

Thanks. It seems Android 11 will be forcing apps to use SAF. If they've decided not to provide any compatibility this time (although history says otherwise) like **W^X**, I think we will no longer need such a feature. But as you've said, this is just a feature request, so I will let it open until I came to some conclusion.

**Comment by MuntashirAkon** [comment]
Things have changed a lot since 2020. With SAF being mandatory for the most types of apps, there's no longer any need for such features.
