### ISSUE TITLE
Root mode is broken in 3.1.5

### ISSUE THREAD

**Issue by HanabishiRecca** [MuntashirAkon/AppManager#1311]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Root mode is broken for me in 3.1.5.

When trying to enable the Root mode of operation, I see "App Manager was granted Superuser rights" message from Magisk, but the app hangs for some time on `Loading...` screen, then falls back into the non-root mode.

Or if the app is just started, it hangs on the `Initializing...` screen for some time and then fails.

### To Reproduce

1. Try to enable the root mode.

### Expected behavior

Root mode should work.

### Logs

Seems like that's it:
```
D AndroidRuntime: Calling main entry io.github.muntashirakon.AppManager.server.RootServiceMain
E IPC     : Error in IPCMain
E IPC     : java.lang.IllegalArgumentException: Unknown action: efefc34a-d0a4-41e9-abe5-a8dd92df7bb6
E IPC     : 	at io.github.muntashirakon.AppManager.server.RootServiceMain.<init>(RootServiceMain.java:167)
E IPC     : 	at io.github.muntashirakon.AppManager.server.RootServiceMain.main(RootServiceMain.java:121)
E IPC     : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E IPC     : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
I binder  : 27280:27280 ioctl 40046210 7ffdad9f10 returned -22
I io.github.muntashirakon.AppManager:root: System.exit called, status: 1
I AndroidRuntime: VM exiting with result code 1.
```

### Device info

- Device: Sony Xperia XA2
- OS Version: LineageOS 21.0 / Android 14
- App Manager Version: 3.1.5
- Mode: Root, Magisk 27.0

**Comment by MuntashirAkon** [comment]
The IDE messed up the release it appears. It failed reproducibility test as well. Wait a few more minutes until I update the release. There's nothing wrong with the repository, only the binary (APK/APKS) files.

**Comment by MuntashirAkon** [comment]
> in 4.0 alphas I get a toast saying root mode isn't working even though it still works. Pixel 8 pro, March 2024 update

That's likely a different issue. Please open a new issue with debug logs.

**Comment by HanabishiRecca** [comment]
Reuploaded apk is fine. Thanks for fast response 👍

**Comment by jaywk** [comment]
Seeing the same issue with both the stable and beta versions using Apatch root method.

**Comment by MuntashirAkon** [comment]
> Seeing the same issue with both the stable and beta versions using Apatch root method.

This issue is about a broken release. Please create a new issue.
