### ISSUE TITLE
Get added on weblate

### ISSUE THREAD

**Issue by NobodyForNothing** [MuntashirAkon/AppManager#1313]
### Describe the existing feature/documentation

I noticed a few things of in the german translation and went to weblate to fix them.

### Describe your problem(s)

The info banner said I should request verification here.

**Comment by MuntashirAkon** [comment]
Your weblate username?

**Comment by NobodyForNothing** [comment]
`@derdilla06`

**Comment by MuntashirAkon** [comment]
Added. Thanks!
