### ISSUE TITLE
Activate ADB mode with USB debugging ONLY (no wifi or ethernet)

### ISSUE THREAD

**Issue by jcfyre** [MuntashirAkon/AppManager#1315]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

PLEASE add a "Mode of operation" for USB only ADB activation. I use ADB OTG using another android phone and can activate things like Shizuku using an "adb otg" app with a simple adb command "sh /shizuku's app data/start.sh" and I can even disconnect from the other phone and still use shizuku adb until reboot. This would be VERY useful on App Manager: use my other phone to enter adb otg, enter start command, put App Manager in adb mode until reboot even after disconnecting from adb otg from other phone. Would LOVE that.

### Describe the solution you'd like

ADB mode activated using wired connection terminal commands that can be used even with ADB OTG from another phone, just like Shizuku can while remaining active even after disconnection until reboot.

### Describe alternatives you've considered

None

### Additional context

With how much phones are locked down now, especially locked American bootloaders, having the most access is cruicial. By adding this function it allows one to use any small android device without data, hotspot, or wifi, using ADB OTG to activate the other phones elevated mode in App Manager thus releasing us a little more from the shackles of "big tech" both at home and On-The-Go.

**Comment by MuntashirAkon** [comment]
Implemented in 4aade1b72f3ecbb6a712a81c519da839fb8e148e
