### ISSUE TITLE
Main list selected items  bottom action menu area should be bigger on high resolution screen

### ISSUE THREAD

**Issue by czarnyckm** [MuntashirAkon/AppManager#1321]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

On high resolution screens (eg. 1440x3120) the selected items bottom area is too small.
It should show at least 3 rows instead of 2 and maybe 5 items in row instead of 4

![Screenshot_20240325-100233](https://github.com/MuntashirAkon/AppManager/assets/18211387/fa8fceeb-b91e-4e92-a06d-4fe4dbbe6e35)

**Comment by MuntashirAkon** [comment]
This panel has been replaced with a slightly different implementation in the pre-releases. So, this issue is no longer applicable.

**Comment by MuntashirAkon** [comment]
Related issue #1303
