### ISSUE TITLE
Usage widget should uses the bigger font size for the app names / usage time on higher screen resolutions

### ISSUE THREAD

**Issue by czarnyckm** [MuntashirAkon/AppManager#1322]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

The font size for the app names / usage time is too small on higher resolutions

![Screenshot_20240325-100252](https://github.com/MuntashirAkon/AppManager/assets/18211387/7233cbfc-6d1e-485c-a004-64d75e7f2603)

**Comment by MuntashirAkon** [comment]
Heights in the widget are set using `dp` values which should adjust the layout as needed. In this case, you've expanded the widget beyond the supported limit. I've added a hard-coded limit in 236f6142ca93c3db83f6064c92de25df4b13d832 to prevent such abuse.
