### ISSUE TITLE
Profile should not break the execution if contains unistalled app

### ISSUE THREAD

**Issue by czarnyckm** [MuntashirAkon/AppManager#1323]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

If a profile contains uninstalled app it break the execution with the exception.

### Expected behavior

Such uninstalled profile entries should be skipped or auto removed from the profile

### Device info

- Device: Pixel 7 Pro
- OS Version: GrapheneOS lastest version
- App Manager Version: 3.1.5
- Mode: ADB

**Comment by MuntashirAkon** [comment]
Doesn't seem to be reproducible in the latest beta.
