### ISSUE TITLE
Display the screen time in a permanent notification

### ISSUE THREAD

**Issue by czarnyckm** [MuntashirAkon/AppManager#1327]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Display the screen time in a permanent notification.
Just the time with a big font.

**Comment by MuntashirAkon** [comment]
This should be done by a dedicated app, such as **Average data usage widget**. App Manager is more or less a generic app where usage is a minor feature.
