### ISSUE TITLE
Delete Apk after install

### ISSUE THREAD

**Issue by nikhilbadyal** [MuntashirAkon/AppManager#1329]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

In the Installer section can we have an option which when Toggled on deletes the apk from device after the install is a success.

### Describe the solution you'd like

APK gets deleted after installing.

### Describe alternatives you've considered

I deleted apks manually after installing.

### Additional context

MIUI package Installer had this cool option.

**Comment by MuntashirAkon** [comment]
This isn't possible for most cases since the URIs supplied by other apps (stores, file managers) provide no option to delete them. This will result in inconsistency and confusion. In addition, the user should be responsible for anything they have provided outside App Manager. This is not just
