### ISSUE TITLE
App Ops denies clipboard permission by default

### ISSUE THREAD

**Issue by HarriBuh** [MuntashirAkon/AppManager#1330]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I set App Manager to automatically block trackers on any app installation, but I don't remember to have done the same to App Ops, too.

I recognised some apps not being able to both read or write to the clipboard, so I checked in App Manager and found out, that these permissions had been removed - most likely by App Manager.

### To Reproduce

1. Open affected app
2. Try to copy or paste text
3. Wonder why it won't work
4. Check specific app App Ops' via App Manager

### Expected behavior

See bug description

### Screenshots

![Screenshot_20240329-145902](https://github.com/MuntashirAkon/AppManager/assets/123186113/370e0f4e-bc01-431c-9d5f-88848df91b6d)

### Device info

- Device: Google Pixel 7
- OS Version: Android 14
- App Manager Version: 3.1.5
- Mode: Rooted with Magisk 27.0

### Additional context
Only after resetting App Ops of that affected App it would change back to "allowed". I am not able/ allowed no to manually allow these permissions back to normal.

**Comment by MuntashirAkon** [comment]
> I set App Manager to automatically block trackers on any app installation, but I don't remember to have done the same to App Ops, too.
> 
> I recognised some apps not being able to both read or write to the clipboard, so I checked in App Manager and found out, that these permissions had been removed - most likely by App Manager.

App Manager does NOT modify app ops during installation. No such feature was ever implemented in App Manager. It might be caused by something else. I suggest you do some investigations to figure it out.
