### ISSUE TITLE
auto backup APK on install

### ISSUE THREAD

**Issue by nutpantz** [MuntashirAkon/AppManager#1331]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Back up every install app apk to custom directory in compressed format. (Zip) and label it by version. Keep the last few versions.
. I used to love that feature on app monster

**Comment by MuntashirAkon** [comment]
Sorry, this feature cannot be implemented. Use the regular backup/restore feature instead. Routine operations are part of #61
