### ISSUE TITLE
Literally doesn't want to connect in wireless debug mode at all anymore since i launched it ONCE without being connected to a wifi.

### ISSUE THREAD

**Issue by vordx** [MuntashirAkon/AppManager#1340]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I can't connect in wireless debug no matter what.

I tried clearing cache, restarting, clearing data, unpair and repair, turn off wireless debug multiple times, nothing.

### To Reproduce

https://streamable.com/b06vtc

Video will expire in 2 days.

### Expected behavior

To connect normally?

### Screenshots

Video uploaded above

### Device info

- Device: Galaxy s23U
- OS Version: android 14
- App Manager Version: AM Debug v4.0.0-alpha02 Run#2678
- Mode: ADB

**Comment by MuntashirAkon** [comment]
Fixed via 935c5870dc1be6aa70e0df1391f7b5fe9884f3fd. There are still a few known issues left which will be gradually fixed.
