### ISSUE TITLE
Problem with launching non-exported activities 

### ISSUE THREAD

**Issue by GflowerG** [MuntashirAkon/AppManager#1341]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I think that AM launches the assistant before the system has registered the selected activity. Or cancels registration before the system calls the assistant. 

I think so, because the feature is triggered when the activity launch button is spammed. This means that the registration and launch of the activity are not synchronized even by a temporary pause. That is, these are parallel tasks.

### Device info

- Mode: **ADB**
- App Manager Version: Debug v4.0.0-alpha02; 2679 (**2620**)

### Additional context

I don't use the default assistant. But when I install it, AM just launches it instead of launching the selected activity.

**Comment by MuntashirAkon** [comment]
Tested on Lineage OS 18.1 and 21 (A11 and A14) with assistant turned on and off. They worked fine. I don't know if it's a ROM related issue or you're whether you're using any non-standard assistants (e.g. some launchers support custom assistants that are triggered by the launcher rather than the system).

**Comment by vordx** [comment]
I have the same issue but I thought i was doing something wrong because it works with Knox privilege activities launchers.

**Comment by MuntashirAkon** [comment]
> UPD. After experiments (MIUI ROM), I returned to the version that AM launches the restored assistant. AM does not give my system enough time to launch the selected activity...

It's up to you to determine the amount of waiting time (in milliseconds) required by your system in order for it to realize the change in the assistant by following #1243. You can write a shell script with variable delays to figure out a minimum amount of waiting time or delay.

```sh
# Store the configured assistant
last_val=`settings get secure assistant`
# Replace `package/activity` with the one you need to open
settings put secure assistant package/activity
# Empirically decided wait time (100 ms). Replace it with various values e.g., 0.3, 0.5 or 0.75 or 1.0 to find the best wait time
sleep 0.1
# Launch activity
input keyevent 219
# Restore assistant
settings put secure assistant "$last_val"```

**Comment by MuntashirAkon** [comment]
I've added an empirical value of 500ms in 120a95dc3319a54d0619b5e489f2ffd80437071a
