### ISSUE TITLE
What does "Swap" under Running apps actually display?

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#1344]
### Describe the existing feature/documentation

The "Running apps" is a pretty useful feature of AppManager and it displays the running processes and it displays various parameters for each process as well as compiled data(overall usage).

### Describe your problem(s)

The Running Apps page contains two Primary parameters "Memory" and "Swap".
The problem is that Android doesn't seem to implement the traditional Swap space and rather implements a Memory only(RAM only) equivalent called Z-RAM.
Now assuming that Swap refers Z-RAM,on a 6GB RMX2061 the Swap is shown to be 2.35GB whereas the Memory is shown to be 5.85GB.
Now the problem is that the Z-RAM+Memory cannot be 5.85GB+2.35GB as that would exceed the physical memory on the device.
Or is the "Swap" indicative of the equivalent decompressed anount of memory the compressed Z-RAM can store?
So what does the "Swap" parameter actually display?

**Comment by MuntashirAkon** [comment]
It uses whatever the kernel has returned. App Manager doesn't infer any swapping mechanism be it a swap image or partition or Z-RAM.
