### ISSUE TITLE
Plans for 4.0.0-alpha3 ?? Locked out of 4.0.0.alpha 2

### ISSUE THREAD

**Issue by sperglord8008s** [MuntashirAkon/AppManager#1348]
### Describe the existing feature/documentation

Required update locked out

### Describe your problem(s)

Any plans for 4.0.0-alpha3 any time soon ? given that the entire version is now locked out and I'm not sure if the settings backup will work on the 3.0 version

**Comment by MuntashirAkon** [comment]
Duplicate of #1324

**Comment by MuntashirAkon** [comment]
Please be patient. A release will be made very soon.
