### ISSUE TITLE
Crash exiting AppInfo while the purple progress bar is still visible

### ISSUE THREAD

**Issue by k9janer** [MuntashirAkon/AppManager#135]
**Describe the bug**
AppManager crashes when exiting AppInfo while the new progress bar above the app icon is visible.

**To Reproduce**

1. Click on an App in the list of packages.
2. Immediately press back while the purple progress bar is still displayed.
3. You will land back in the list of packages but then AppManager will crash

The crash also occurs if the progress bar is displayed during a different activity, such as disabling an app.

**Expected behavior**
AppManager should not crash.

**Screenshots**
-

**Crash logs**
https://pastebin.com/tW1iGPwR

**Device info**
 - Device: FireTV 4K Stick
 - OS Version: FireOS 6.2.7.3 (Android 7.1.2)
 - App Manager Version: v2.5.17
 - Mode: adb/stock

**Additional context**
Affected versions: 2.5.17 and 2.5.16
Not affected: 2.5.13

I encountered this bug on my FireTV 4K Stick. The bug could be exclusive to this device and its limited/broken(?) Android base in which case this bug would be irrelevant.

However it's also possible that this bug could happen on any slow device. I wasn't able to reproduce this bug on a Pixel 3a or a Fire HD 10 tablet since these devices are much faster and it looks like the progress bar disappears before it registers the back press.

Maybe someone could try this on an older, slower device?
On Fire TV 4K the progress bar is visible for up to 2 seconds and so the chances to run into this crash are pretty high.

**Comment by MuntashirAkon** [comment]
This is a known issue, and yes, your assumption about slow devices are correct.

**Comment by fusionneur** [comment]
I experienced same crash (see email), however I can confirm that this does not have anything to do with slow devices as mine is super fast :)

**Comment by MuntashirAkon** [comment]
> I experienced same crash (see email), however I can confirm that this does not have anything to do with slow devices as mine is super fast :)

If you closed the page while the page was still loading, you would experience a crash. It takes a long time to load the App Details page on slow devices and therefore they experience the crashes more frequently.

**Comment by MuntashirAkon** [comment]
I've added a fix via 539f5891 but it may still crash.

**Comment by MuntashirAkon** [comment]
I've also limited the number of threads that can be run at a time in cde749b1. This should also reduce the number of crashes. Please, confirm this by testing the latest debug builds.

**Comment by RickyM7** [comment]
@MuntashirAkon This crash occurred on my phone frequently, but after the [539f589139](https://github.com/MuntashirAkon/AppManager/commit/539f589139ca9efea43b9ba042fb1856690cd6f7) it stopped happening frequently and now I tested the debug builds 574 and 575 (the test consisted of getting into apps in AM and leaving before the information be loaded, this quickly and repeatedly) and the crash did not occur.

**Comment by MuntashirAkon** [comment]
@RickyM7: Thanks for testing.

**Comment by k9janer** [comment]
Yes, I just download the latest debug build and the app no longer crashes when exiting AppInfo!

However I have noticed that there is still a crash when exiting the "Deny app ops" menu while the app is compiling the list of affected apps (also with a purple progress bar).

To reproduce:

1) Have the app run in ADB mode
2) Menu - 1-Click Ops - Deny app ops...
3) Enter a value like 63 and click "search"
4) Now press back while the purple progress bar is visible.
5) Now you will return back to the app list.
6) Wait a little bit and AppManager will crash.

Crash Log from my Pixel 3a: https://pastebin.com/sN4tqnMh
LogCat: https://pastebin.com/RiVnrfEb

I guess this issue is a bit different since AppManager seems to crash when it wants to display the new window where you can select/deselect apps for the app ops process. Is it okay to add it to this issue?

Btw: Sorry for the late reply, I just couldn't figure out where to get the debug builds and I was waiting for it to show up on the releases page...

**Comment by MuntashirAkon** [comment]
> I guess this issue is a bit different since AppManager seems to crash when it wants to display the new window where you can select/deselect apps for the app ops process. Is it okay to add it to this issue?

The situation is very similar and may present in all the other tabs. Simply replacing AppInfo with App Details page is sufficient, I think.

**Comment by MuntashirAkon** [comment]
> I guess this issue is a bit different since AppManager seems to crash when it wants to display the new window where you can select/deselect apps for the app ops process. Is it okay to add it to this issue?

Please disregard the previous reply as I haven't noticed the 1-click ops page before. I think this deserves another issue. But no worries, I can migrate it myself.
