### ISSUE TITLE
Providers minor UI changes

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1358]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Since IFW does not support blocking providers
1. When Settings > Rules > Default blocking method is set to IFW + Disable or only IFW they should function as Disable for Providers i.e. no matter what blocking method you use it always setup as Disable for Providers. (not sure if it's already done this way)
2. Remove these options for Providers, when you long click the toggle button.
![2024-04-21_00-19](https://github.com/MuntashirAkon/AppManager/assets/48226312/c2138faa-dfe6-447c-abda-598755bf5732)

### Device info

App Manager v4.0.0-beta01

**Comment by MuntashirAkon** [comment]
Changed in 6e7f32d6d2060f68abbf9b86643bc56263d7f78f
