### ISSUE TITLE
A dedicated screen for installing apps

### ISSUE THREAD

**Issue by PoneyClairDeLune** [MuntashirAkon/AppManager#1362]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Some devices only have vendor ROMs available, and they will attempt at hijacking opening `.apk` files. By offering a dedicated installer screen in AppManager, this can be bypassed entirely for users with root.

### Describe the solution you'd like

Like "running apps" and "log viewer", offer a dedicated "installer" screen where only a file picker and an installer button are offered.

### Describe alternatives you've considered

* I've tried to find a way to launch the installer in AppManager directly, but that failed.
* I've tried to disable the system's default package installer, and while that works, the phone will enter a bootloop when rebooted.

**Comment by shuvashish76** [comment]
I think somehow you setup the action to launch your device Package Installer by default.
1. Open AM search "Package Installer" open the App Info page > Click on "View in Settings" from 3 dot menu > Open by defaults > click on "Clear Defaults"
2. To be sure check AM settings > Appearance > Enable/Disable features > Turn on Package Installer checkbox

Now when you click on `.apk` files from your file manager it should show you both the option.

> offer a dedicated "installer" screen where only a file picker and an installer button are offered.

We do have dedicated FileManager for AM (pre-releases) though.

> I've tried to find a way to launch the installer in AppManager directly, but that failed.

What do you mean by "launch the installer in AppManager directly"?
Alternatively you can sure the apk file to AM "Install" to install via AppManager.

**Comment by PoneyClairDeLune** [comment]
> I think somehow you setup the action to launch your device Package Installer by default.

No. I just confirmed that the settings page shows « Aucun paramètre par défaut défini » (No default parameters defined). As long as the package installer is enabled, it will always try to intercept `.apk` files.

> We do have dedicated FileManager for AM (pre-releases) though.

Hope it will be ready soon!

> What do you mean by "launch the installer in AppManager directly"?

Launching the Interceptor and trying to formulate a customized intent to the package installer activity in App Manager. Might have done it incorrectlt on my end however.

**Comment by MuntashirAkon** [comment]
You can use the “Share” button (if available) or a good file manager such as Material Files (you may need to use the “Open With” option) or MiXplorer. I don't plan on implementing a dedicated page for it since it should be the job of a properly developed file manager.

**Comment by PoneyClairDeLune** [comment]
> you may need to use the “Open With” option

The thing is that the ROM itself *intercepts* and redirects `.apk` files to be opened by its own package installer. If that have worked I wouldn't have made this issue *at all*.

However, the share button served as a pretty nice circumvention mechanism!

**Comment by MuntashirAkon** [comment]
> The thing is that the ROM itself _intercepts_ and redirects `.apk` files to be opened by its own package installer.

You didn't include your device info, so it's hard to tell. But I don't believe this to be true. A file manager can provide as many options it can by utilising the intent filters (as done by MiXplorer or App Manager beta). It's the file manager or the system “opener” that's causing issues. If you're, say, opening an APK from the browsers “Download” section or Android-default “Files” app, it may directly lead to the system installer in some ROMs because the system opener is configured to do that.
