### ISSUE TITLE
Failure when installing AppList Detector.

### ISSUE THREAD

**Issue by ChaliceChore** [MuntashirAkon/AppManager#1367]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When installing [**AppList Detector**](https://github.com/Dr-TSNG/ApplistDetector), the following error pops-up and the installation fails:

> Installation failed either because it was cancelled or the session was closed unexpectedly
>
> INSTALL_FAILED_VERIFICATION_FAILURE: Install not allowed for file:///data/app/vmdl1418703677.tmp

But if I install it using the standard Package Installer, it works fine.

### To Reproduce

1. Go to https://github.com/Dr-TSNG/ApplistDetector/releases
2. Download the latest apk.
3. Try installing it using App Manager installer.
4. Installation fails with the above error.

### Expected behavior

It should be installed without any issues.

### Screenshots

![Screenshot_2024-04-29-17-51-15-01_718a221d6c53e9d44e23988b91117061_1](https://github.com/MuntashirAkon/AppManager/assets/22472867/50ecf448-ab24-42a5-a72c-82653ac0f15a)

### Device info

- Device: realme GT 2 Pro
- OS Version: realme UI 5.0 (ColorOS 14)
- App Manager Version: 4.0.0 beta-01
- Mode: Root

**Comment by MuntashirAkon** [comment]
It's highly probable that the installation is being blocked by the package verifier, i.e., Google Play Protect or whatever you've got on your phone. Disable it temporarily and try again to verify.

**Comment by ChaliceChore** [comment]
I checked it. And you are right. Play Protect was the culprit. I guess it is triggered because the app has circumventing methods.
