### ISSUE TITLE
unable to ban the sensor

### ISSUE THREAD

**Issue by hishere** [MuntashirAkon/AppManager#1369]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

in appmanager this Application，i can't do it
but in appops Application，it's very useful。

### Screenshots

![Screenshot_2024-05-02-17-17-39-395_io github muntashirakon AppManager](https://github.com/MuntashirAkon/AppManager/assets/56129009/1af71215-35be-433a-b6d6-53bcf7bd1502)
![Screenshot_2024-05-02-17-18-04-590_rikka appops](https://github.com/MuntashirAkon/AppManager/assets/56129009/e90c7cd7-be75-4d09-8c2b-bd6ea90b7b1c)

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by hishere** [comment]
it's not use ,so i must be use appops to ban sensor
![Uploading Screenshot_2024-05-02-17-22-06-028_com.miui.home.png…]()

**Comment by hishere** [comment]
![Screenshot_2024-05-02-17-22-06-028_com miui home](https://github.com/MuntashirAkon/AppManager/assets/56129009/eff8cb4e-5518-48f8-b6f5-8924f4055449)

**Comment by MuntashirAkon** [comment]
ab73dfc90ce55a4185835bf9f6ba23b62f90c488
