### ISSUE TITLE
Apk share 

### ISSUE THREAD

**Issue by appt2** [MuntashirAkon/AppManager#1372]
### Describe the existing feature/documentation

hello @MuntashirAkon I wanted to know how can I share the apk file because no matter what I tried I couldn't find the Java code for it, can you help me?

**Comment by MuntashirAkon** [comment]
You can take a look at this: https://github.com/MuntashirAkon/AppManager/blob/1a8928c3717707fbcc938c53ae117827757bcf26/app/src/main/java/io/github/muntashirakon/AppManager/details/info/AppInfoFragment.java#L399-L415

**Comment by appt2** [comment]
> You can take a look at this:
> 
> https://github.com/MuntashirAkon/AppManager/blob/1a8928c3717707fbcc938c53ae117827757bcf26/app/src/main/java/io/github/muntashirakon/AppManager/details/info/AppInfoFragment.java#L399-L414

tnks
