### ISSUE TITLE
Shizuku

### ISSUE THREAD

**Issue by Jak2k** [MuntashirAkon/AppManager#1385]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Get elevated rights using shizuku.

**Comment by shuvashish76** [comment]
https://muntashirakon.github.io/AppManager/en/#subsec:faq:shizuku-support
https://github.com/amcommunity/TipsAndTricks/issues/14

Duplicate of #55

**Comment by shuvashish76** [comment]
@Jak2k Duplicate request of #892
https://github.com/MuntashirAkon/AppManager/commit/42c316fd501771699f55d2bcd0e9f2882d405c7a Already available for v4.0.0-beta01

**Comment by MuntashirAkon** [comment]
Duplicate of #55
