### ISSUE TITLE
App Inoperable

### ISSUE THREAD

**Issue by scruel** [MuntashirAkon/AppManager#1388]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Consider this issue caused by #1387, the large amount of log output may hang the app.

https://github.com/MuntashirAkon/AppManager/assets/16933298/d0a02255-ec41-44f8-b598-0538ab2cd46c

### Device info

- Device: Xiaomi cas
- OS Version: Android 13
- App Manager Version: 3.1.6
- Mode: NonRoot

**Comment by MuntashirAkon** [comment]
Thanks for the video.

**Comment by MuntashirAkon** [comment]
Related issue: #1317

**Comment by MuntashirAkon** [comment]
Related issue: #1173

**Comment by MuntashirAkon** [comment]
The issue does not seem to be reproducible after fixing #1173. Did you deny the notification permission earlier before making the video?

**Comment by scruel** [comment]
App should hasn't been granted with any permissions

**Comment by MuntashirAkon** [comment]
Duplicate of #1173
