### ISSUE TITLE
Allow Backup of "Keystore" Apps

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#139]
Hey there, I'd like to do some Backups, but I realized, that some apps won't backup, all of those have the "Keystore" Badge kinda thing, such as Firefox, Authenticator Pro, and some more - What prevents the backup? Is it possible to make it work? What are keystore apps?
Thanks!

**Comment by Atrate** [comment]
Duplicate of #82

**Comment by UltraBlackLinux** [comment]
@Atrate 
I searched for Keystore, and there were no results, thanks github.
Well thanks then ;)
