### ISSUE TITLE
Can we disable internet access to apps on certain android skins?

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#1392]
### Describe the existing feature/documentation

Currently the App Ops or even the Net policy do not have an option to completely revoke internet access to an app,as AOSP never had this built into its core.

### Describe your problem(s)

However android skins from brannds like xiaomi,oppo, realme(BBK Electronics) seem to have two extra options to disable Mobile data and wifi data access to apps under App info>Data usage details.
Are these options a part of extended App opps /Net policy configuration that these brands implement and is it possible for this functionality to be baked into App manger?,so that users of these skins can effectively disable network access to system apps.

### Additional context

![IMG_20240610_004720](https://github.com/MuntashirAkon/AppManager/assets/72438196/056cc14e-f9f2-425a-8f80-db6db5495bf9)

**Comment by MuntashirAkon** [comment]
If they're located in the data usage page, they should be part of the Net Policy. Certain custom ROMs (e.g., Lineage OS and derivatives) support complete blocking of network access via Net Policy. Graphene OS, on the other hand, has an option to disable the `android.permission.Internet` permission itself.
