### ISSUE TITLE
Backup Mutiple Auto Name Feature Not Work

### ISSUE THREAD

**Issue by L2750558108** [MuntashirAkon/AppManager#1393]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

It says "You can leave it blank to use the current date-time" after I check Backup/Restore > Backup Muitple checkbox in an application, but in fact it overwritten the base backup silently without any non-base backup named as date-time.

### To Reproduce

1.Open Backup/Restore dialog for any application
2.Check Backup Mutiple checkbox
3.Click backup button
4.Find a base backup created instead of a mutiple backup named date-time in restore list

### Expected behavior

It should create a mutiple backup named date-time

### Device info

- Device:Oneplus 10 Pro (NE2213)
- OS Version:Oxygen OS 14.0.0.700
- App Manager Version:3.1.6(249)
- Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed in 00990dd6bfed1e6dd4b94596b173845bf99ee950
