### ISSUE TITLE
Add support for MediaStore `ACTION_REVIEW` in interceptor

### ISSUE THREAD

**Issue by glemco** [MuntashirAkon/AppManager#1395]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

The interceptor is nice to understand why some apps are not listed for a specific action, this one action doesn't seem supported and it's hard to understand what is exactly triggered.
You can see the action when tapping on the thumbnail in the Lineage OS 21 camera app (Aperture).

### Describe the solution you'd like

Intercept that action.

### Additional context

Discovered while investigating https://github.com/deckerst/aves/issues/1052
More context can be found in that issue.

**Comment by MuntashirAkon** [comment]
Added via a2f7ce9c030b9b0cb94cc62a9a954e58b9ac7f56
