### ISSUE TITLE
Routine operations are blocked if Screen Lock options in enabled

### ISSUE THREAD

**Issue by OmarKSH** [MuntashirAkon/AppManager#1408]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When running a routine operation using the "am" command [as described by the docs](https://muntashirakon.github.io/AppManager/en/#sec:automating-tasks) while having the Screen Lock option enabled in AppManager the user is asked to unlock the app before executing the operation.

### To Reproduce

1. Go to profiles and create a profile adding a few applications to it and enabling routine ops for it in its configuration menu
2. Go to settings -> Privacy -> Toggle "Screen Lock" option as enabled
3. Try to run the profile using the "am" command as mentioned in the docs
4. Instead of the Routine Operation running automatically, it opens AppManager and requests you to unlock the application

### Expected behavior

The Expected behavior is for the routine operation to run automatically without user interaction

### Device info

- Device: Samsung Galaxy S10e
- OS Version: 13
- App Manager Version: 3.1.6
- Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed via ae2c23b71d0c8c20f2d482dde7950ead762da36b
