### ISSUE TITLE
family link bypass 

### ISSUE THREAD

**Issue by Sparkkkkie** [MuntashirAkon/AppManager#1410]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Hello! I am sadly using family link, and my mom is able to see when I have installed an app, I have root, but is there a way you could make a feature that bypasses announcing that an apk has been installed to gms, as family link runs off of gms.

### Describe the solution you'd like

Above

### Describe alternatives you've considered

Above above

### Additional context

Above above above

**Comment by MuntashirAkon** [comment]
App Manager is NOT a hacking software. It helps user improve privacy and usability of their device. That's it.
