### ISSUE TITLE
Is Pithus Report in Scanner page broken?

### ISSUE THREAD

**Issue by ExidusGIT** [MuntashirAkon/AppManager#1415]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

It seems that Pithus Report card inside Scanner page is not returning any info back but "Not Available". Since Pithus is still in Beta themselves, I am guessing they have changed the API access? 

### To Reproduce

Go to a random app in the app list
Click on Scanner
Scroll (if needed) to Pithus Report card
Error : Not Available

### Expected behavior

Getting results from Pithus Security platform.

### Device info

- Device: Samsung s22U
- OS Version:A 14 (OneUI 6.1)
- App Manager Version: 4.0.0 beta01
- Mode: Non Root

**Comment by shuvashish76** [comment]
Works as expected here for latest debug.
> Go to a random app in the app list

1. It works only if the "Use the internet" option is turned on. I'm guessing it's already turned on your device.
2. Display link to Pithus report **if available**. If not available, extract the app, upload on pithus & check scanner again.

**Comment by MuntashirAkon** [comment]
Pithus does not provide an API. So, App Manager can only check for reports by appending the APK hash to `https://beta.pithus.org/report/`. Technically, it might be possible to upload the APK, but I can't do this without prior permission from them.

**Comment by MuntashirAkon** [comment]
Pithus has been removed (0e187e8324958e5a88b6d2a0482f8eaa06f7fda4) since the project has been discontinued.
