### ISSUE TITLE
Not able to setup through wireless debugging in OOS

### ISSUE THREAD

**Issue by stillrinzler** [MuntashirAkon/AppManager#1417]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I've paired Appmanager using wireless debugging but when I open the app, it's automatically selected to no root mode and when I select wireless debugging mode, a dialog box shows up saying incomplete usb debugging, I've gone through the documentation but there wasn't anything specific for OOS
![Screenshot_2024-07-18-18-59-46-07_718a221d6c53e9d44e23988b91117061](https://github.com/user-attachments/assets/c627e92e-59c2-4536-8707-465251d62deb)

### To Reproduce

-1. Go to settings
-2. Click on mode of operation
-3. Select wireless debugging and pair it
-4. It should automatically revert to no root mode after pairing 
-5. Click on wireless debugging and you should get a dialog box saying 'Incomplete USB Debugging'

### Expected behavior

It should be paired without any issues since USB debugging is turned on as well as wireless debugging, I don't recall there's anything else that needs to be enabled for OOS
The below screenshot shows that Appmanager is connected under wireless debugging settings
![Screenshot_2024-07-18-18-59-33-76_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/6a6dcd4c-af72-48d8-849a-52bdb90552a1)

### Device info

- Device: OnePlus 12
- OS Version: OOS 14 14.0.0.810
- App Manager Version: 3.1.6
- Mode: Wireless Debugging

**Comment by ascendbeing** [comment]
Try 3.1.7. This was a major bug that ,7 was supposed to fix, and you said you're on 3.1.6.

**Comment by stillrinzler** [comment]
> Try 3.1.7. This was a major bug that ,7 was supposed to fix, and you said you're on 3.1.6.

I updated to 3.1.7 as soon as it got released and tried it out but I'm still getting the same error

**Comment by MuntashirAkon** [comment]
The prompt is usually displayed if `shell` lacks the permissions to modify permissions of other apps. While this almost always means that additional settings are needed to be enabled, I am not familiar with Oxygen OS to actually help you with it.

**Comment by stillrinzler** [comment]
> The prompt is usually displayed if `shell` lacks the permissions to modify permissions of other apps. While this almost always means that additional settings are needed to be enabled, I am not familiar with Oxygen OS to actually help you with it.

Ohh got it. So I tried disabling permission monitoring and it worked but when I disable permission monitoring and wireless debugging, it reverts back to no root even after being successfully paired

**Comment by MuntashirAkon** [comment]
> when I disable permission monitoring and wireless debugging, it reverts back to no root even after being successfully paired

You cannot disable permission monitoring.

**Comment by MuntashirAkon** [comment]
Updated docs via aedf23a3752babc65d2d01ebe92bae29d7e81fe1
