### ISSUE TITLE
Allow the user to choose when App Manager asks for user authentication

### ISSUE THREAD

**Issue by FixItKit** [MuntashirAkon/AppManager#1427]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

The user should be able to choose when App Manager asks for user authentication. For example when opening App Manager, when freezing apps, uninstalling apps or accessing sections of App Manager.

### Describe the solution you'd like

Allow the user to choose when App Manager asks for user authentication. You should be able to set the user authentication settings separately for user apps and system apps.

**Comment by MuntashirAkon** [comment]
You mean the “Screen lock” feature? If so, the purpose of the screen lock is to prevent misuse when the device is unlocked for unintended access e.g., because your younger sibling wants to play games in your device.

**Comment by MuntashirAkon** [comment]
> > You mean the “Screen lock” feature? If so, the purpose of the screen lock is to prevent misuse when the device is unlocked for unintended access e.g., because your younger sibling wants to play games in your device.
> 
> I think it would still be useful to expand it for when potentially dangerous stuff is being done.

Sorry, the implementation cost outweighs the benefit.
