### ISSUE TITLE
Some translate error in chinese

### ISSUE THREAD

**Issue by L2750558108** [MuntashirAkon/AppManager#1430]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

https://github.com/MuntashirAkon/AppManager/blob/874df1a2ccd716d90edb04d282f1ab712836e325/app/src/main/res/values-zh-rCN/strings.xml#L352
https://github.com/MuntashirAkon/AppManager/blob/874df1a2ccd716d90edb04d282f1ab712836e325/app/src/main/res/values-zh-rTW/strings.xml#L452

In these lines,
"cache" is translated into “不包括缓存”/"排除快取" (means "no cache" in chinese), the correct one is "包括缓存"/“包括快取”
Maybe there is also same problem in other languages but the only language I can read is chinese

### Device info

Not relative to device

**Comment by MuntashirAkon** [comment]
Fixed via 1c9ce7dea4177c5b782b5c160808ac0378cb89ac
