### ISSUE TITLE
Backup feature

### ISSUE THREAD

**Issue by Lucky390163** [MuntashirAkon/AppManager#1433]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Need a backup feature for apkm, apks and .apk files urgently.

### Describe the solution you'd like

A backup feature is needed

**Comment by MuntashirAkon** [comment]
You need to be more specific. There's already an option available through the batch options in the Main page that supports both APK and APKS format. APKM is a proprietary format introduced by APKMirror and cannot be implemented in App Manager.

> urgently.

Feature requests are prioritised based on the maintainers' state of mind. No urgency can have any effect on it.

**Comment by Lucky390163** [comment]
And what about backup in xapk or simple apk format?

**Comment by shuvashish76** [comment]
> - [x] I have read the docs

Again, please search the docs with specific keywords. e.g. xapk, apkm, apks, backup etc...
