### ISSUE TITLE
App stuck on initializing..

### ISSUE THREAD

**Issue by GalKar83** [MuntashirAkon/AppManager#1435]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Installed the app in my car. At first it used to work but now it is impossible to pass the initializing part while the app is loading. 
USB Debug is Allowed, tried clearing cache & data, rebooting , but nothing seems to make the app accessable. 

### To Reproduce

Just open the app.. 

### Expected behavior

App will load. 

### Device info

- Device: BYD Atto 3
- OS Version: Android 10
- App Manager Version: 3.1.7
- Mode: ADB/NonRoot

**Comment by oanhnet7** [comment]
I error like you. Y uninstall it -> off usb debug -> reboot. Reinstall 
Note: keep it on your memory. If y want to close -> change abd to no root before
Done 🥰🥰🥰

**Comment by BananotBI** [comment]
Thanks for replying, I did uninstall and reinstall the app.. The thing is I need USB Debugging and Wireless ADB for another app to work so I need these settings to be enabled. 
Is it possible that 2 apps with USB Debug allowed can cause problems while running simulationsly?

**Comment by GalKar83** [comment]
Thanks for replying, I did uninstall and reinstall the app.. The thing is I need USB Debugging and Wireless ADB for another app to work so I need these settings to be enabled. 
Is it possible that 2 apps with USB Debug allowed can cause problems while running simulationsly?

**Comment by oanhnet7** [comment]
I still run with shizuku. Run many app normal. Just this app error. Shizuku run very nice all time

**Comment by Xisrr1** [comment]
> I still run with shizuku. Run many app normal. Just this app error. Shizuku run very nice all time

Can you use app manager with Shizuku?

**Comment by Tharow** [comment]
> > I still run with shizuku. Run many app normal. Just this app error. Shizuku run very nice all time
> 
> Can you use app manager with Shizuku?

No and it never will link to AppManager Doc: https://muntashirakon.github.io/AppManager/en/#subsec:faq:shizuku-support

**Comment by ANaPhOrAX** [comment]
here to let you know it's not fixed... I'm currently experiencing the same. 4.0.5

**Comment by MuntashirAkon** [comment]
New issues are tracked via #1825
