### ISSUE TITLE
Reset AppInfo action

### ISSUE THREAD

**Issue by Mark-Joy** [MuntashirAkon/AppManager#1437]
### Describe your problem(s)

When open AppInfo of an app, android gives the option to choose between: [xxx-App](the app name that I forget) and [AppManager]  -- [Just Once] and [Always] . I choose [xxx-App] and [Always].
Now I want to change the option to [AppManager], but android does not give the option anymore.
How do I reset this AppInfo action and choose [AppManager] instead of [xxx-App]?

Edit:
- I figure out the way to reset it but still, I don't remember the [xxx-App] name
- The way to do is: Goto App Info of [xxx-App] -> Open by default -> CLEAR DEFAULTS

**Comment by MuntashirAkon** [comment]
It appears you've already solved your issue. Closing the issue...

**Comment by Mark-Joy** [comment]
@MuntashirAkon
Actually, no I haven't solved the issue yet.
I want to choose AppManager as the default "AppInfo", so I need to clear previous "default preferences"
The thing is I can't find the correct [AppName] to "Clear default preferences". It is suppose to be the system "Settings" app, but there is no  "Clear default preferences" in its "App Info".

I have a question:
1> I remember it is possible to open AppManager AppInfo activity by long-click on an installed app, and choose the [!] sign, and then choose AppManager (between AppManager and SystemAppInfo) . But now, even with AppManager newly installed on a new device, I can't see the dialog to choose AppManager when long-clicking on installed app.
It just goes straight to system [AppInfo] after clicking on [!] sign.

Is my understanding correct that it is possible to choose AppManager as default app when long-click on an installed app, and choose the  [!] sign?

**Comment by Mark-Joy** [comment]
@MuntashirAkon 
 - When long-click the installed app, and then choose PlayStore sign, a dialog is open to let me choose between: PlayStore, F-Droid and AppManager
 - When long-click the installed app, and then choose [!] sign, it goes straight into SystemAppInfo page  without letting me choose the AppManager.
 - Inside SystemAppInfo page of "Settings" app, there is no "Clear default preferences" in "Open by default". The thing is, I am not sure the "Settings" app is the one to "Clear default preferences"

https://github.com/user-attachments/assets/e840dfd6-b292-4308-b714-885a1d16234d

**Comment by MuntashirAkon** [comment]
These options depend on Launchers. We don't have any control over them.
