### ISSUE TITLE
Delete empty backup folders

### ISSUE THREAD

**Issue by FixItKit** [MuntashirAkon/AppManager#1438]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

App Manager should delete empty backup folders.

### Describe the solution you'd like

Delete an app's empty folder from the selected backup location after deleting an app's backup(s).

**Comment by MuntashirAkon** [comment]
Duplicate of #1189
