### ISSUE TITLE
Confused about "Safe to remove" label in debloater feature

### ISSUE THREAD

**Issue by 8itlew7r** [MuntashirAkon/AppManager#1439]
### Describe the existing feature/documentation

In the bloatware info for an application in the Debloater feature, there is a "Safe to remove" or "Exercise caution" label, etc.

### Describe your problem(s)

Based on my past experience, apps that have `coreApp` or `directBootAware` attributes in their Android manifest can cause a bootloop, so I'm wondering why it's marked as "Safe to remove"? Is it really safe?

Thanks.

### Additional context

Example:
KLMS Agent (com.samsung.klmsagent)
Version 1.1.25

**Comment by MuntashirAkon** [comment]
Please ask those questions here: https://github.com/MuntashirAkon/android-debloat-list

ADL is independent of App Manager.

**Comment by ElonSatoshi** [comment]
Thanks for transferring my issue to the android-debloat-list repo! I think it would be a good idea to transfer this one too
