### ISSUE TITLE
[Question] Approx. release date of 4.0 Update

### ISSUE THREAD

**Issue by HarriBuh** [MuntashirAkon/AppManager#1443]
Hey man,
Really like your app and use the 4.0 alpha 2 on a daily basis.
Thing is, it's still kinda unstable and buggy, BUT I cannot go back because 3.1.7 is worse regarding available features (especially for A14).

I recognise you are still busy developing, so I wanted to ask for an update on your progress.

Cheers.

**Comment by shuvashish76** [comment]
> ...use the 4.0 alpha 2 on a daily basis...BUT I cannot go back because 3.1.7 is worse regarding available features (especially for A14).

https://github.com/amcommunity/TipsAndTricks/issues/17

As mentioned there alpha/beta are mostly for testers. As recently [announced on TG post](https://t.me/sAppManagerChannel/381) next is **Beta** so I guess the new features available in v4 series are not coming to Stable version that soon.

**Comment by shuvashish76** [comment]
> I don't use Telegram

RSS/XML URLs (Add them to your RSS reader)
- https://rss-bridge.org/bridge01/?action=display&bridge=TelegramBridge&format=Atom&username=AppManagerChannel

- https://rss-bridge.org/bridge01/?action=display&bridge=TelegramBridge&format=Atom&username=AppManagerDebug

_Created using https://github.com/RSS-Bridge/rss-bridge ([public instances](https://rss-bridge.github.io/rss-bridge/General/Public_Hosts.html) if you preder)_

**Comment by MuntashirAkon** [comment]
Sorry, it's not possible for me to give any approximation. It is advisable to use the latest stable release for day-to-day use, or rolling debug releases for new features.
