### ISSUE TITLE
Option to use [AppManager-AppInfo] as default AppInfo action on installed apps instead of Android [Settings-AppInfo]

### ISSUE THREAD

**Issue by Mark-Joy** [MuntashirAkon/AppManager#1445]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Long-click an installed app, open AppInfo action using [AppManager-AppInfo] action instead of the android native one.
I may be mistaken in #1437 thinking that this feature already exists. If it's not, is it possible to implement it?

**Comment by MuntashirAkon** [comment]
As I said in the linked issue, these options are controlled by the Launcher itself. We have no control over these options. If this is a third-party Launcher, you may ask them to support opening the App Info page from App Manager.

**Comment by MuntashirAkon** [comment]
Technically speaking, the action `android.settings.APPLICATION_DETAILS_SETTINGS` (which open the App Info page in the Android Settings app) cannot be used by any non-system apps. So, it's not possible for App Manager to override the default action.

**Comment by Mark-Joy** [comment]
This may be late, but thank you for the explanation!
