### ISSUE TITLE
Added the installation lock function

### ISSUE THREAD

**Issue by Keeperorowner** [MuntashirAkon/AppManager#1447]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

It is recommended to lock AM as the system default installer, after all, AM installers are much more beautiful and practical than system installers

**Comment by Tharow** [comment]
Duplicate of https://github.com/MuntashirAkon/AppManager/issues/1404

This could be done separately  by disabling the associated activity of PackageInstaller  -- InstallStart iirc
