### ISSUE TITLE
The application list is messed up

### ISSUE THREAD

**Issue by Vladik01-11** [MuntashirAkon/AppManager#1450]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

If there is more than 1 user (in my case Knox folder) then the list of apps when using ADB takes VERY longer to load than usual, and also the list is not complete (1 app for the whole phone?).

### To Reproduce

1. Create a Knox folder
2. Go to ADB mod
3. Observe

### Expected behavior

App loading speeds are as fast as before, and valid

### Screenshots

![Screenshot_20240930_081632_Aves Libre](https://github.com/user-attachments/assets/494d24a3-9553-45f2-8646-e87eb17af84d)

### Logs

[29_09-23-16-03_712.zip](https://github.com/user-attachments/files/17184796/29_09-23-16-03_712.zip)

### Device info

- Device: Samsung S20 FE
- OS Version: 13
- App Manager Version: build 2763
- Mode: ADB

**Comment by MuntashirAkon** [comment]
Possibly related to #1432. Need logs to confirm.

**Comment by MuntashirAkon** [comment]
> this problem is a duplicate of #1409 than #1432

Nope, the authors are the same, and the reports point to the same issue.

> Now on the latest build 2786 the situation has not changed in any way, the list of applications still takes forever to load.

You need to share some logs.

**Comment by MuntashirAkon** [comment]
> Waited for half an hour, no application received at all :( [04_04-00-12-51_601.log](https://github.com/user-attachments/files/17787994/04_04-00-12-51_601.log)

```
ServerStatusChangeReceiver: Mismatch token. Expected: scrub-ferry-botch-slack-yard, Received: apron-bully-swim-wife-barge
```

It looks like ADB didn't connect at all due to authentication failure. You may either be running two instances of App Manager or cleared its data. App Manager remote server runs independently of App Manager, and it has no control over it if the authentication fails.
