### ISSUE TITLE
Add an option to web search the package

### ISSUE THREAD

**Issue by james28909** [MuntashirAkon/AppManager#1452]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

when i am looking through the list of apps, it would be handy to have an option that will automatically launch and search the selected package so i can get more info on it

**Comment by shuvashish76** [comment]
Some information are available through "Debloater" page of App Manager (_alpha/beta i.e v4.0.0 series_)
Duplicate request of #748

**Comment by MuntashirAkon** [comment]
Duplicate of #748
