### ISSUE TITLE
Notice from app

### ISSUE THREAD

**Issue by Lucky390163** [MuntashirAkon/AppManager#1457]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

1) App is laggy on scrolling it uses high memory.

2) Add a option to batch force stop apps and clean cache.

3) App beta version is 
![Screenshot_20241017_154730_App Manager](https://github.com/user-attachments/assets/086caabc-b92d-4dcf-b4e6-ef686de19102)
expiring

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by shuvashish76** [comment]
> App is laggy on scrolling it uses high memory.

 - [x] I know how to take logs

Provide the logs...

> Add a option to batch force stop apps and clean cache.

These features already available https://muntashirakon.github.io/AppManager/en/#subsec:batch-operations

 - App beta version is expiring

- [x] I know what my device, OS and App Manager versions are

Fill the **Device info** details and see #889

**Comment by MuntashirAkon** [comment]
You've listed too many unrelated issues in a single report and didn't report your device and app info. You need to open a new issue for each unrelated issue along with those information.
