### ISSUE TITLE
App Manager 4.0 beta 2 soon?

### ISSUE THREAD

**Issue by DB9-max** [MuntashirAkon/AppManager#1465]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Beta 2 needed 

### Describe the solution you'd like

While beta 1 is very good it's showing aging and is a hasbeen with bugs and missing functionality

### Describe alternatives you've considered

Beta 2!

### Additional context

Bet app is App Manager for app related managing

**Comment by jcfyre** [comment]
After reading what the developer is going through, I have the most empathy and respect for him. With that being said, especially after getting a new phone, I am EXTREMELY EXCITED for a finalized release of the new App Manager version with all of its fantastic new features I miss out on with 3.1.7. Of course, with patience and respect come great things.

**Comment by weskerty** [comment]
> After reading what the developer is going through, I have the most empathy and respect for him. 
What happened?

**Comment by jcfyre** [comment]
I decided to check out the App Manager Telegram page, and one of the posts from this year from September, he was talking about MAJOR events going on in his country as well as losing his beloved grandmother all while starting his PhD, and on top of that his dedication to App Manager. I mean, I am personally not a developer, just a person where I don't belong but long to be, but it doesn't take that much to see just how hard that man is working on both App Manager and his own life. So I have MUCH love and respect to everyone who is engaged in this project.
