### ISSUE TITLE
Want to contribute on Weblate

### ISSUE THREAD

**Issue by cairobraga** [MuntashirAkon/AppManager#1472]
### Describe the existing feature/documentation

I'd like to be added to the translating contributors on Weblate for Portuguese, please.

### Describe your problem(s)

Following the instructions and guidelines informed in AppManager's Weblate info page, I'm requesting permission to join so I can contribute to the Brazilian Portuguese and European Portuguese localizations of the app.

### Additional context

My username in Weblate is the same as here.

**Comment by MuntashirAkon** [comment]
Your request has been granted. Thanks.
