### ISSUE TITLE
Market/Installer Callback Link In System Settings

### ISSUE THREAD

**Issue by Tharow** [MuntashirAkon/AppManager#1474]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Make this button in the settings work, below is shown a enabled version of the button
Button should open App Details page for given app.
This feature only works for Applications that App Manager Installed.
![image](https://github.com/user-attachments/assets/95dff3c1-1816-43b6-b947-7fef09dc9da5)

### Describe the solution you'd like

calls ACTION_SHOW_APP_INFO intent  with Extra of PACKAGE_NAME, Example below
`intent:#Intent;action=android.intent.action.SHOW_APP_INFO;S.android.intent.extra.PACKAGE_NAME=eu.faircode.email;end`
Intent copied from interceptor uri field.
As this is a system intent is bypasses android:exported=false tag on activity meaning that only the settings page will be able to shortcut to the Details Page without Authorization  

### Additional context

PermissionController Source That Makes This Call [AOSP](https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/Permission/PermissionController/src/com/android/permissioncontroller/permission/utils/KotlinUtils.kt?q=symbol%3A%5Cbcom.android.permissioncontroller.permission.utils.KotlinUtils.getAppStoreIntent%5Cb%20case%3Ayes)

**Comment by MuntashirAkon** [comment]
Implemented in 257ac97ea4b1b5e1ddaec9d3733e6aff04b699eb
