### ISSUE TITLE
APatch support?

### ISSUE THREAD

**Issue by dhyanKaro** [MuntashirAkon/AppManager#1475]
APatch root method doesn't seem to be detected...

**Comment by MuntashirAkon** [comment]
I don't actually know how AParch works. Doesn't APatch turn the app process itself into root? If so, you can install the latest beta and run App Manager in no-root mode. Not all features were migrated though, so you may not use certain features like Intent Firewall. Let me know how it goes.

**Comment by MuntashirAkon** [comment]
This appears to be an issue with APatch itself: https://github.com/bmax121/APatch/issues/439
