### ISSUE TITLE
To publish a testing version on "F-Droid"

### ISSUE THREAD

**Issue by RejectVanity** [MuntashirAkon/AppManager#1477]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

The iteration cycles for the test versions (beta, alpha, RC) of the project (App Manager) seem quite long. In such cases, it would be suitable to publish testing versions on the "F-Droid" platform.

### Describe the solution you'd like

Publish testing versions on "F-Droid" with the stable version marked as "suggested."

### Additional context

Publishing testing versions on "F-Droid" has precedents, such as **[VLC](https://f-droid.org/packages/org.videolan.vlc/)**.

**Comment by shuvashish76** [comment]
> https://gitlab.com/fdroid/fdroiddata/-/issues/3245

[AutoUpdateMode](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.videolan.vlc.yml#L5690) disabled for VLC. Manual interventions necessary for new updates. AFAIK F-Droid has no automation for such cases.

**Comment by MuntashirAkon** [comment]
We had a discussion regarding this (when the discussion tab was enabled). F-Droid does not offer a good way to handle beta testing. So, it's not possible, at least, from my end to do anything about it.
