### ISSUE TITLE
Rewrite the features of AM

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#148]
AM is no longer a merge of Apps_packages Info, Watt or Activity Launcher, it has grown to be much more than what these apps are capable of doing, and the readme or fastlane metadata should reflect this.

**Comment by UltraBlackLinux** [comment]
Didn't want to make a new issue, because it's too similar: The instructions page is still about exodus, not scanner.

**Comment by MuntashirAkon** [comment]
> The instructions page is still about exodus, not scanner.

It was obsolete for a long time and finally has been removed.  See #208.
