### ISSUE TITLE
Not getting root permission

### ISSUE THREAD

**Issue by singh9596** [MuntashirAkon/AppManager#1485]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I'm using KSU for root access, but App manager doesn't seem to be working. It shows that the remote server is inactive. I have tried many versions of app manager, but none of them works.

### Screenshots

![Screenshot_20241214-162052_KernelSU](https://github.com/user-attachments/assets/b98853ed-1a0a-4854-af20-50cbdf983bb2)
![Screenshot_20241214-162101_App Manager](https://github.com/user-attachments/assets/30f778a9-bee3-4103-9d19-6508dfc884dc)

### Logs

[file_4514169169261927703.zip](https://github.com/user-attachments/files/18135518/file_4514169169261927703.zip)

### Device info

- Device: K20 Pro (Mi 9t pro)
- OS Version: Rom based on A14
- App Manager Version: 4.0.0. Beta 2
- Mode: Root (KSU)

**Comment by MuntashirAkon** [comment]
Looks like a SELinux issue. App Manager is unable to access it's external cache directory.

**Comment by MuntashirAkon** [comment]
Duplicate of #948

**Comment by singh9596** [comment]
> Looks like a SELinux issue. App Manager is unable to access it's external cache directory.

And how do i solve this?
