### ISSUE TITLE
info about disabled/uninstalled package

### ISSUE THREAD

**Issue by mariush444** [MuntashirAkon/AppManager#1486]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

if package is  disabled or uninstalled there is no way to get info about it.
When you tap on package the reinstallation is proposed only.
![adb](https://github.com/user-attachments/assets/58d14f5a-6ace-4c71-81bc-56ba930804f8)

### Describe the solution you'd like

I would like to have possibility to tap and see package full name and so on.
maybe the name can be wrapped but I have no idea about other info

### Describe alternatives you've considered

workaround is to use shell
adb shell pm list packages -d
adb shell pm list packages -u

**Comment by MuntashirAkon** [comment]
> I would like to have possibility to tap and see package full name and so on.

Under the installer dialog, there's an app info button which you can use to view the details of the app. Installer is prioritized over app info because that's how most people are using the feature.

**Comment by mariush444** [comment]
Can you show screenshot?
I can not see such info/possibility.

**Comment by MuntashirAkon** [comment]
> Can you show screenshot? I can not see such info/possibility.

It's currently available in the unstable releases only.
