### ISSUE TITLE
Unable to update AppManager using AppManager when AppManager is retired

### ISSUE THREAD

**Issue by perosb** [MuntashirAkon/AppManager#1487]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I use AppManager to install and update apps in my Car.
Today I got a "This version of App Manager has been retired" message.

Tapping update flickers and does nothing. I have my web browser in my car.
Tapping "Continue" and AppManager seems to hang and do nothing.

So this is a catch 22 as the only way to install apps is via AppManager.

Can this "retired" be disabled remotely?

### Device info

- Device: BYD Atto 3
- OS Version: Android Automotive OS
- App Manager Version: 3.1.0
- Mode: ADB

**Comment by MuntashirAkon** [comment]
You need to find another way to update because, unfortunately, the continue button does not work as expected in v3.1.x releases (a8442fe9a906ef2e58acfffdf1fa9ae3f565fae3)

**Comment by perosb** [comment]
So there is no way to disable the "retired" check? Is this a remote change or hardcoded?

Would be nice mot having the Car OS firmware downgraded of even possible.

**Comment by MuntashirAkon** [comment]
> So there is no way to disable the "retired" check? Is this a remote change or hardcoded?

It's hard coded. The only way that may work is going back in time, that is, setting the date to last month, update AM, and then reset the date again.
