### ISSUE TITLE
Trackers components

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#149]
Hi.I made Tracker(&ad&malicious) components list that doesn't blocked automatically.
Please add them when it possible." * " is wildcard.

--Activities--
com.appodealx.mraid.MraidActivity
com.explorestack.*
com.ogury.cm.ConsentActivity
com.pichillilorenzo.*
com.smaato.sdk.*
com.startapp.sdk.*
com.yalantis.ucrop.UCropActivity
io.flutter.plugins.*
jp.noahapps.sdk.*
com.facebook.*
jp.appAdForce.*
com.jirbo.adcolony.*
jp.maio.sdk.android.*
*.InterstitialAdActivity
*.InAppBannerWebActivity
com.gomfactory.adpie.*
com.kakao.adfit.*
com.mopub.common.*
.houseads.HouseAdActivity
com.vungle.warren.*
mozilla.components.lib.crash.*
mozilla.telemetry.*
com.sina.weibo.sdk.share.*
com.socdm.*.adgeneration.*
jp.supership.vamp.*
.ui.flutter.common.*
com.muf.sdk.tiktok.TikTokEntryActivity
com.vk.sdk.VKServiceActivity
org.gg.msdns.noroxi.*
com.deflocculent.fecklessness.*
com.shahenshah.mathematics.*
*.B2sActivity
*.BxcActivity

--Services--
com.startapp.sdk.*
io.flutter.plugins.*
jp.co.yahoo.android.yssens.YSSensDataShareService
jp.co.yahoo.yconnect.sdk.SharedDataService
com.mapbox.android.*
org.acra.sender.*
mozilla.components.lib.crash.*
.services.analytics.AnalyticsProviderService
com.deflocculent.fecklessness.*
*.MdService
.Service.Adjust*

--Receivers--
com.startapp.sdk.*
it.partytrack.sdk.*
com.facebook.*
com.xiaomi.market.sdk.*
com.deflocculent.fecklessness.*
*.LoReceiver
*.OxgReceiver
*.PdsReceiver

--Providers--
com.smaato.sdk.*
com.startapp.sdk.*
de.esys.esysfluttershare.*
io.flutter.plugins.*
com.facebook.*
com.vungle.warren.*
io.sentry.android.*

**Comment by MuntashirAkon** [comment]
Sorry, I don't take list of trackers directly as it's beyond my scope to verify or manage those signatures. You should open an issue in [exodus](https://github.com/Exodus-Privacy/exodus) instead.
