### ISSUE TITLE
App Usage Features

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#15]
Feature check list:
- [x] (v2.5.4) Add data usage (mobile+wifi) for each app (API 23 or later)
- [x] (v2.5.4) Add app open count (aka times opened) for each app
- [x] (v2.5.4) Sorting applications in terms of screen time, data usage, times opened, app label, last foreground time, notifications received
- [x] (v2.5.5) Display app usage details for each app on click (open in new dialog or activity)
- [x] (Abandoned) Investigate the probability of adding a bar/pie chart displaying usage frequency/higest used apps: It appears that other than a fancy display (which is beyond the scope of this project), these charts do not appear to provide any useful information whatsoever
- [x] (Abandoned) Add notification count for each app: It's inefficient for an user app to keep track of notifications as a service have to be constantly running in the background in order to count nofications which can take its toll on battery

Following features may not be best for this app, but was still considered:
- App timer
- App lock
- Invoke Do Not Disturb (DND) mode for a certain interval

**Comment by MuntashirAkon** [comment]
@deerp1976 Since your stupid email provider (aka Gmail) can't accept apk files (even as a zip), I'll include the zip file here. This should improve things a bit better but I can't gurantee.
[AppManager_v2.5.4 (190).apk.zip](https://github.com/MuntashirAkon/AppManager/files/4827936/AppManager_v2.5.4.190.apk.zip)

**Comment by MuntashirAkon** [comment]
@Deerp1976 Download the attached file. Usage log should be saved at `/sdcard/Android/data/io.github.muntashirakon.AppManager/cache/usage_log.txt`.

[AppManager_v2.5.4 (193).apk.zip](https://github.com/MuntashirAkon/AppManager/files/4831178/AppManager_v2.5.4.193.apk.zip)

**Comment by Deerp1976** [comment]
I've downloaded it and will share the results with yo soon as discussed on email. I don't really understand the log saved on my phone. Are these events such as opening up each app? Has this got anything to do with the GETEVENT command? I'm quite the amateur with these commands. I can get GETPROP working fine but GETEVENT requires more for example the package names like what you've given in log.

App usage in App is looking very very good now

**Comment by MuntashirAkon** [comment]
> Are these events such as opening up each app?

Yes. The numbers inside the brackets are the event constants (type of events such as app opening, closing, etc.) defined [here](https://developer.android.com/reference/android/app/usage/UsageEvents.Event). The long numbers are unix timestamp which denotes when these events are fired.

> Has this got anything to do with the GETEVENT command?

These events are logged at `/data/system/usagestats/` and can be accessible directly if you have root or can be accessed by normal apps when `GET_USAGE_STATS` permission is granted (which is this case I've done).

I'm trying to include as much data as possible within a single place (instead of what trivial apps have done). This will also give users insight on how much data can an app accessed when permissions like these are granted.
