### ISSUE TITLE
Display of Backup/Restore Compression method not updating when changed

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#166]
**Describe the bug**

Display of Backup/Restore Compression method not updating when changed.

**To Reproduce**

Go into Settings, and change Backup/Restore Compression method. After pressing "save", the option displayed in Settings does **not** change (the actual setting **has** changed, as verified by quitting and restarting the app, and then going back into settings).

**Expected behavior**
I expect to see a changed setting as soon as I change it (without having to restart the app).

**Device info**
Three completely different devices (with three different Android versions), so I assume this happens everywhere. :)

**Comment by MuntashirAkon** [comment]
Fixed via abae6904
