### ISSUE TITLE
Add support for IFW Enhance and Shizuku as package manager controller/operation mode

### ISSUE THREAD

**Issue by andrizmitnick** [MuntashirAkon/AppManager#171]
**Is your feature request related to a problem? Please describe.**
it's quite risky or i'd say not quite feasible to directly modify many services, receivers, broadcasts of many apps. reverting things might be troublesome.

**Describe the solution you'd like**
to add IFW Enhance and Shizuku as option modes, just like MyAndroidTools and Blocker app

**Describe alternatives you've considered**
-

**Additional context**
[IFW Enhance](https://github.com/Kr328/Riru-IFWEnhance)
[Shizuku](https://github.com/RikkaApps/Shizuku)
[Blocker](https://github.com/lihenggui/blocker)

![Screenshot_20201130122324](https://user-images.githubusercontent.com/21377475/100573124-b176b080-3309-11eb-9591-5f0212d5893b.jpg)
![Screenshot_20201130122348](https://user-images.githubusercontent.com/21377475/100573126-b3407400-3309-11eb-900d-69e0ad5ba3ca.jpg)

**Comment by MuntashirAkon** [comment]
ADB over TCP is integrated in AM (similar to Shizuku) so no need to use Shizuku. Component blocking is not supported from Android O, even with ADB. However, you can still control the components of a test APK as described [here](https://github.com/lihenggui/blocker#shizuku-mode-no-root-permission-required) but installing debug/test APK adds other vulnerabilities and therefore not recommended by AM.

PM method is useless and therefore will not be included. See [this FAQ](https://muntashirakon.github.io/AppManager/faq/app-components.html#why-are-the-components-blocked-by-am-not-detected-by-other-related-apps) or [this difference](https://github.com/lihenggui/blocker#differences-between-intent-firewall-and-package-manager) for more info.

**Comment by MuntashirAkon** [comment]
> it's quite risky or i'd say not quite feasible to directly modify many services, receivers, broadcasts of many apps. reverting things might be troublesome.

AM doesn't modify any app. It uses IFW rules to block app components.

**Comment by andrizmitnick** [comment]
thank you very much for the response and explanations!! glad that now i understood more about AM, thanks again!!

**Comment by MuntashirAkon** [comment]
You're welcome!
---
_Be sure to read the docs if you haven't already. You can learn not only about AM but also more about Android ecosystem for apps._

**Comment by sobaee** [comment]
> ADB over TCP is integrated into AM (similar to Shizuku), so there is no need to use Shizuku. Component blocking is not supported from Android O, even with ADB. However, you can still control the components of a test APK as described [here](https://github.com/lihenggui/blocker#shizuku-mode-no-root-permission-required) but installing debug/test APK adds other vulnerabilities and therefore not recommended by AM.
> 
> PM method is useless and therefore will not be included. See [this FAQ](https://muntashirakon.github.io/AppManager/faq/app-components.html#why-are-the-components-blocked-by-am-not-detected-by-other-related-apps) or [this difference](https://github.com/lihenggui/blocker#differences-between-intent-firewall-and-package-manager) for more info.

Hello dear

I didn't want to open a new issue to tell you these things about this topic.

I know that AM now could use ADB over TCP like Shizuku, but don't you think that activating Shizuku, especially after the restart, is much easier than AM; 
It is easier and for those who have other Shizuku needed tools like Darq, blocker, etc., to be able to activate all of them in one step by enabling the Shizuku app once, you don't have to activate ADB mode for every needed app separately!

For example, me, after every restart, I always have to activate ADB for AM, Brevent, Shizuku, etc., separately one by one!!

It's better to activate ADB only for Shizuku once, and he will do the rest!

**Comment by MuntashirAkon** [comment]
When the issue was raised, it was still possible to use Shizuku. But I cannot use Shizuku now because of its API limitations. Shizuku mostly allows a third-party app to run Framework/registered services, and I require more than that.
