### ISSUE TITLE
Crash when exiting the "Deny app ops" menu while the purple progress bar is still visible

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#189]
I have noticed that there is still a crash when exiting the "Deny app ops" menu while the app is compiling the list of affected apps (also with a purple progress bar).

To reproduce:

1) Have the app run in ADB mode
2) Menu - 1-Click Ops - Deny app ops...
3) Enter a value like 63 and click "search"
4) Now press back while the purple progress bar is visible.
5) Now you will return back to the app list.
6) Wait a little bit and AppManager will crash.

Debug Build: 2.5.20-DEBUG 578
Crash Log from my Pixel 3a: https://pastebin.com/sN4tqnMh
LogCat: https://pastebin.com/RiVnrfEb

_Originally posted by @k9janer in https://github.com/MuntashirAkon/AppManager/issues/135#issuecomment-744596473_

**Comment by MuntashirAkon** [comment]
Fixed via db2bf2f5. @k9janer: can you check?

**Comment by k9janer** [comment]
Thank you, I can confirm that this issue is now fixed on my Pixel 3a and Fire HD10 tablet.
