### ISSUE TITLE
Crash on permissions tabs on Android 11

### ISSUE THREAD

**Issue by bbigam** [MuntashirAkon/AppManager#194]
**Describe the bug**
On AM 2.5.20 on Android 11, AM crashes every time I try to access the App Ops, Uses Permissions, or Permissions tabs. It happened sporadically on AM 2.5.17 on Android 11, and did not happen on Android 10. I do not have root but have granted AM all relevant permissions, including All Files Access. Happens with or without adb.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any app details, including AM itself
2. Click on App Ops, Uses Permissions, or Permissions
3. AM immediately crashes every time

**Expected behavior**
Tab loads correctly, or shows error message or empty tab without crash.

**Crash logs**
**Running without adb mode:**
12-17 15:52:31.150 19592 20123 E AndroidRuntime: FATAL EXCEPTION: Thread-142
12-17 15:52:31.150 19592 20123 E AndroidRuntime: Process: io.github.muntashirakon.AppManager, PID: 19592
12-17 15:52:31.150 19592 20123 E AndroidRuntime: java.lang.ExceptionInInitializerError
12-17 15:52:31.150 19592 20123 E AndroidRuntime:        at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOpCode(AppOpsManager.java:1502)
12-17 15:52:31.150 19592 20123 E AndroidRuntime:        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(AppDetailsViewModel.java:1007)
12-17 15:52:31.150 19592 20123 E AndroidRuntime:        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$rcK05b73qPcOD8WauhT_GpajWOk(Unknown Source:0)
12-17 15:52:31.150 19592 20123 E AndroidRuntime:        at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$rcK05b73qPcOD8WauhT_GpajWOk.run(Unknown Source:2)
12-17 15:52:31.150 19592 20123 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
12-17 15:52:31.150 19592 20123 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
12-17 15:52:31.150 19592 20123 E AndroidRuntime:        at io.github.muntashirakon.AppManager.appops.AppOpsManager.<clinit>(AppOpsManager.java:1410)

**Running in adb mode:**
12-17 16:03:10.176 20105 21323 E AndroidRuntime: FATAL EXCEPTION: Thread-99
12-17 16:03:10.176 20105 21323 E AndroidRuntime: Process: io.github.muntashirakon.AppManager, PID: 20105
12-17 16:03:10.176 20105 21323 E AndroidRuntime: java.lang.ExceptionInInitializerError
12-17 16:03:10.176 20105 21323 E AndroidRuntime:        at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOpCode(AppOpsManager.java:1502)
12-17 16:03:10.176 20105 21323 E AndroidRuntime:        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(AppDetailsViewModel.java:1007)
12-17 16:03:10.176 20105 21323 E AndroidRuntime:        at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$rcK05b73qPcOD8WauhT_GpajWOk(Unknown Source:0)
12-17 16:03:10.176 20105 21323 E AndroidRuntime:        at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$rcK05b73qPcOD8WauhT_GpajWOk.run(Unknown Source:2)
12-17 16:03:10.176 20105 21323 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
12-17 16:03:10.176 20105 21323 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
12-17 16:03:10.176 20105 21323 E AndroidRuntime:        at io.github.muntashirakon.AppManager.appops.AppOpsManager.<clinit>(AppOpsManager.java:1410)

**Device info**
 - Device: Galaxy S10+ USA Unlocked
 - OS Version: Android 11 with One UI 3 (beta)
 - App Manager Version: 2.5.20
 - Mode: No root; adb and non-adb crash logs above

**Additional context**
I've tried clearing app cache and data, restarting phone, etc.

**Comment by MuntashirAkon** [comment]
Oops, it looks like your Android version is too up-to-date for AM!

**Comment by MuntashirAkon** [comment]
Fixed via 99aa4a6b

**Comment by bbigam** [comment]
You are quick! Thanks, I'll be looking forward to the next build. :-)

**Comment by MuntashirAkon** [comment]
> Thanks, I'll be looking forward to the next build. :-)

You can try the debug builds from the Actions tab to see if it's working: https://github.com/MuntashirAkon/AppManager/actions

Don't use it for regular use though since the credentials are public.

**Comment by bbigam** [comment]
Yes, it works. Thanks!
