### ISSUE TITLE
Reathorize adb on every view of apps list

### ISSUE THREAD

**Issue by bbigam** [MuntashirAkon/AppManager#195]
**Describe the bug**
Since updating to 2.5.20, every view of the apps list in AM requires a reathorization of allowing this computer (AM) to connect to debugging.

**To Reproduce**
Steps to reproduce the behaviour:
1. adb tcpip 5555
2. Open App Manager
3. Prompt appears to allow this computer to use debugging. Select "always allow."
4. toast message of adb mode, and everything works
5. Browse to any other page of AM - App details, settings, running apps, etc.
6. Go back to apps list
7. Get the prompt to allow this computer to use debugging. Select "always allow." Repeat steps 3-7 endlessly.

**Expected behavior**
As in 2.5.17 and previously:
1. adb tcpip 5555
2. Open App Manager
3. Prompt appears to allow this computer to use debugging. Select "always allow."
4. toast message of adb mode, and everything works
5. Everything keeps working for AM in adb mode without reathorization until the next reboot or until disabling adb in system settings.

**Device info**
 - Device: Samsung Galaxy S10+ USA Unlocked
 - OS Version: Android 11 with One UI 3 (beta)
 - App Manager Version: 2.5.20
 - Mode: adb-specific problem

**Additional context**
This worked in 2.5.17 as expected, including in Android 11 on the same device.
If logs could be helpful please tell me how to filter them for what you need.

**Comment by bbigam** [comment]
Additional info: This actually happens anytime leaving the apps list, not just when going to other AM screens. Even if I just go to Recents and immediately back to AM (and no other app in between) I get the prompt again.

**Comment by MuntashirAkon** [comment]
Open settings, select **ADB over TCP** in the **Mode of operations** and see if you can reproduce it again.

**Comment by bbigam** [comment]
Oh, it works as expected with ADB over TCP selected in settings. I guess the problem is in Auto mode?

**Comment by MuntashirAkon** [comment]
> I guess the problem is in Auto mode?

It depends on device, I guess, which is why I've added the entry in settings.

**Comment by NSTAdventure** [comment]
> > I guess the problem is in Auto mode?
> 
> It depends on device, I guess, which is why I've added the entry in settings.

Hello Developer Same With Me
Android 10 RMX 2030 Realme UI
Realme 5i Devices
And Also New Bug Again
SomeTime Why They Won't Load Any App Stuck In Loading :-(

**Comment by MuntashirAkon** [comment]
Fixed via ad4f5135
