### ISSUE TITLE
Deny Instead Of Ignore App Ops

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#196]
**Is your feature request related to a problem? Please describe.**
⬇️Yes it's Related To App Ops Problem ⬇️
Ignore Option Can still be reset again with the system :-( 

**Describe the solution you'd like**
Use Deny Option Instead Of Ignore Option
For App Ops Permission And Uses Permission

**Describe alternatives you've considered**
No Other Alternative Besides Deny Option 

**Additional context**
About App Ops
Ignore Option **Still Able To Reset By System Itself
Especially if you edit permissions in system applications** 
Based On My Experience With Some System Apps When I Set Deny It Won't Reset
**How Do I Know This?.
Some System App WILL CRASH Instantly (YES INSTANTLY)  If You Deny The Some App Ops Options**

Best Regards
NST_Adventure

**Comment by Atrate** [comment]
Could you please clarify what "ignore option" you are reffering to?

**Comment by NSTAdventure** [comment]
@Atrate 
App ops issues :)
Instead Of Ignore You Could Choose Deny 
Why?
Ignore Option For App Ops Still Able To Reset By System 
System Is Totally Hurt By Them

**Comment by MuntashirAkon** [comment]
In the next release, you can long click on any app operation item to set it to any mode that your device supports, including allow, ignore, deny, default, foreground, etc. Ignore is the standard way of blocking an app op (you can try out the debug builds to see how it works).

> Some System App WILL CRASH Instantly (YES INSTANTLY) If You Deny The Some App Ops Options

Yes, as stated in the [AM docs](https://muntashirakon.github.io/AppManager/tech/AppOps.html#mode-constants), denying an app op will throw a SecurityException which will cause the app to crash.

**Comment by NSTAdventure** [comment]
@MuntashirAkon 
Yeah But Ignore Always Reset By System To Default :-( 
Why?

**Comment by MuntashirAkon** [comment]
> Why Is That?There Is No Alternative Method?

No, there aren't any alternatives. Blocking app components is only possible via root.

> But Ignore Always Reset By System To Default :-( why?

It depends on the operating system you're using, really. On Android 11, for example, system will reset the mode of an app op to match its corresponding runtime permission. So, if you disable an app op, you have to disable its corresponding permission as well. In other versions, specifically in MIUI, certain app ops are reset arbitrarily. One way to deal with them is to monitor app ops constantly to detect changes and revert them accordingly. But it needs a foreground service/job service.

**Comment by NSTAdventure** [comment]
> No, there aren't any alternatives. Blocking app components is only possible via root

It is unfortunate :-( 

Best Regards
NST_Adventure

**Comment by NSTAdventure** [comment]
> (you can try out the debug builds to see how it works)

Where? @MuntashirAkon 

Best Regards
NST_Adventure

**Comment by MuntashirAkon** [comment]
> Where? @MuntashirAkon

https://github.com/MuntashirAkon/AppManager/actions

**Comment by NSTAdventure** [comment]
> > Where? @MuntashirAkon
> 
> https://github.com/MuntashirAkon/AppManager/actions

I mean apk file :-( 


Best Regards
NST_Adventure

**Comment by MuntashirAkon** [comment]
> I mean apk file :-(

Yes, click on any build there and download the zip file from the **Artifacts** section and extract it. Alternatively you can download from the Telegram channel: https://t.me/AMDebug

**Comment by NSTAdventure** [comment]
> > I mean apk file :-(
> 
> Yes, click on any build there and download the zip file from the **Artifacts** section and extract it. Alternatively you can download from the Telegram channel: https://t.me/AMDebug

Thanks i love to try debug build 😍😍😍😍😍
i guess something special Inside 😂

Did They Signed With Different Package Name? (So I Not Need To Replace My Previous Installed One) Thanks 💭

Best Regards
NST_Adventure

**Comment by MuntashirAkon** [comment]
> Have bug they always request ADB Access Again And Again :-(

Go to settings and change mode of operations to ADB over TCP.

**Comment by NSTAdventure** [comment]
> > Have bug they always request ADB Access Again And Again :-(
> 
> Go to settings and change mode of operations to ADB over TCP.

Done it's work 
Thanks

Anyway You can add deny option for batch operation to make them more easy

Beest Regards
NST_Adventure

**Comment by MuntashirAkon** [comment]
Fixed via 10dbfc7d, 39b6dbc0 and e5610959.

Batch operations doesn't yet support app ops, consider opening a separate issue for it or simply wait until it gets into the pipeline. Thanks.

**Comment by NSTAdventure** [comment]
@MuntashirAkon 
If we using ADB over TCP What block tracker button do?

**Comment by MuntashirAkon** [comment]
> If we using ADB over TCP What block tracker button do?

Nothing.

**Comment by NSTAdventure** [comment]
@MuntashirAkon 
So blocking tracker via batch operation required root?

**Comment by MuntashirAkon** [comment]
> So blocking tracker via batch operation required root?

Yes. Components cannot be blocked without root. ADB shell has no permission to access the `/data/system` folder.

**Comment by NSTAdventure** [comment]
> > So blocking tracker via batch operation required root?
> 
> Yes. Components cannot be blocked without root. ADB shell has no permission to access the `/data/system` folder.

Wait you say system?
What about user app?still same?
@MuntashirAkon

**Comment by NSTAdventure** [comment]
I have idea 
If apk can repacked i suggest you add feature to re-create apk and add option to remove Dangerous Permission 
Dangerous Hidden And App Ops Permission
Removing All Tracking Included Ads
So After Re Create Apk All Of These Things Is Removed ;)

@MuntashirAkon

**Comment by MuntashirAkon** [comment]
> If apk can repacked i suggest you add feature to re-create apk and add option to remove Dangerous Permission

See #138.

> Wait you say system?

No, this folder is used for blocking app components.

This issue has been closed now. Visit AM Docs, especially the FAQ page for info regarding component blocking. If you have any further queries, open a new issue as they are considered off-topic here.
