### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#199]
**Describe the bug**
Using Non Root Android
I Enable Root Mode
What is surprising is I Can Disable Broadcast
(Hey No Need To Tell Me I Know It Won't Work It Just Display Bug)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open App Manager > Setting > Enable Root Mode
2. Return To App View And Try To Disable Their Broadcast
3. They Disabled (Ofc Just Display Glitch)

**Expected behavior**
They Should Warn User 

**Screenshots**

![Screenshot_2020-12-23-06-59-44-23](https://user-images.githubusercontent.com/50813528/102944158-8ccabe80-44ec-11eb-8f1c-299d4ca7bb0e.jpg)

**Crash logs**
I

**Device info**
 - Device: Realme 5i
 - OS Version: Android 10 Realme UI
 - App Manager Version: 2.5.17 (Latest Version)
 - Mode: ADB/Non Root Mode

**Additional context**
Nothing Just Display Bug I Know It Won't Work Either 
@MuntashirAkon

**Comment by MuntashirAkon** [comment]
If you enable root mode in settings, AM will behave as if it's running as root. This isn't a bug, it's a feature. Even if they enable this option, no root-specific features will work. But thanks anyway.

**Comment by NSTAdventure** [comment]
Why? It should not Swichable if your phone non rooted 
Sorry i though it was bug

Best Regards
NST_Adventure

**Comment by MuntashirAkon** [comment]
> Why? It should not Swichable if your phone non rooted

Because root detection methods are not always perfect.

**Comment by NSTAdventure** [comment]
> > Why? It should not Swichable if your phone non rooted
> 
> Because root detection methods are not always perfect.

Well You Doing Great Job Here
Thanks For Clarifying This Problem

Next I Want To Open Some Disscussion 
But Later 👍 

Best Regards
NST_Adventure
