### ISSUE TITLE
[Feature] Root actions

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#2]
It would be nice if the application allowed performing actions requiring root, such as uninstalling system apps.

**Comment by MuntashirAkon** [comment]
It'll be my top priority after merging Watt.

**Comment by MuntashirAkon** [comment]
Relevant documentation: https://developer.android.com/studio/command-line/adb

Possible root actions (will be trying without root if possible):
- Enable/Disable applications (#12)
- Block providers (#5)
- Grant/revoke permissions
- Uninstall applications
- Clear data/cache
- Force stop/kill a running app

**Comment by MuntashirAkon** [comment]
Fixed via b58ed49, e1a0c3c, 61498ed, deb8ac5, 9fa7755 and 335c752.
