### ISSUE TITLE
Data Usage Not Showing Any Data

### ISSUE THREAD

**Issue by Deerp1976** [MuntashirAkon/AppManager#20]
Phone Huawei Honor 8S
Android OS EMUI 9.1.0
Rooted - no
Usage Information Access permission given to Application Manager
Application version used 2.5.1 from Izzys Fdroid repo.
Booted phone up and used data on Google Play Store, Fdroid and Star Trek Fleet Commander. 

If I check any app for data usage they all show 0mb data used since boot.

**Comment by MuntashirAkon** [comment]
Yes, it's broken since Android N, I believe. It'll be my top priority after implementing preferences.
