### ISSUE TITLE
Future of the instruction page

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#208]
<h2 align="center">Future of the instruction page</h2>

#### Implementation of docs on the instructions page

**This will be implemented in the following way:** Docs will be bundled with AM and will be located in the assets folder. In the APKS file, this will be available as a separate feature split which can be installed by the users if they choose to. If they don't install it, AM will open the URL in a web browser instead. In other cases, docs will always be bundled.

**INTERNET** permission will be removed from the main APK (hopefully in v2.5.22) as stated in #152 as many people are constantly emailing me about the permission despite my explanation that this permission doesn't have anything to do with the Internet in general. It is used to make socket connection and unfortunately, Android cannot distinguish between remote and local socket connections.

<h2 align="center">Related bug</h2>

#### Describe the bug
The crash occurs when you try to open the instructions from the changelog window. Obviously it's only possible to see this bug if you're opening the AM after updating it (and probably only works if you update it by F-Droid).

#### To Reproduce
Steps to reproduce the behaviour:
1. Open the AM after updating it by F-Droid
2. As soon as the changelog window appears, click in the "instructions" button
3. See error

#### Crash logs
java.lang.IllegalStateException: FragmentManager has been destroyed
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1861)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:324)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:289)
    at androidx.fragment.app.DialogFragment.show(DialogFragment.java:253)
    at io.github.muntashirakon.AppManager.types.FullscreenDialog.show(FullscreenDialog.java:72)
    at io.github.muntashirakon.AppManager.main.MainActivity.lambda$null$9$MainActivity(MainActivity.java:607)
    at io.github.muntashirakon.AppManager.main.-$$Lambda$MainActivity$F5tNHZc_Pry4k3yknH3MF3RMCVQ.onClick(lambda)
    at io.github.muntashirakon.AppManager.types.ScrollableDialogBuilder.lambda$setNeutralButton$4$ScrollableDialogBuilder(ScrollableDialogBuilder.java:129)
    at io.github.muntashirakon.AppManager.types.-$$Lambda$ScrollableDialogBuilder$LYcYcUFstkpVrHRkFjADUNGKKGY.onClick(lambda)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:165)
    at android.app.ActivityThread.main(ActivityThread.java:6375)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

Device Info:
App version: 2.5.21-PRE
App version code: 377
Android build version: V11.0.2.0.NCFMIXM
Android release version: 7.0
Android SDK version: 24
Android build ID: AL1512-mido-build-20191107001817
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: mido
Device model: Redmi Note 4
Device product name: mido
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pt-BR
In-App Language: auto

#### Device info
 - Device: Redmi Note 4
 - OS Version: MIUI 11 (Android 7.0)
 - App Manager Version: v2.5.21-PRE (F-Droid)
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Yeah, this has been reported before via e-mail, I think. The instruction page is pretty much obsolete now and will be replaced by a link to the docs page.

**Comment by RickyM7** [comment]
@MuntashirAkon A doubt, why don't you add the information available in the docs on the instructions page? I know it's really a lot of information and so doing this maybe isn't possible but i'm not sure.

**Comment by MuntashirAkon** [comment]
> I know it's really a lot of information and so doing this maybe isn't possible but i'm not sure.

Yes, it's impossible for me to do this. I've separate the docs because of the maintenance burden that I had to carry. If other contributors are interested, they might give it a try. But it will be very difficult to support both Markdown texts and localisation.

**Comment by MuntashirAkon** [comment]
On second thought, we might simply load the static website directly in a WebView. This could be done without any internet connection but I'm not sure how much work would it need though.

**Comment by MuntashirAkon** [comment]
The pages are around 668 KB in size when zipped and 2.6 MB when unzipped.

**Comment by Atrate** [comment]
If the zipped pages are 668KB, they could be bundled and displayed using a webview:

- If there's internet connectivity the webview would show the actual docs webpage

- If there's no connectivity, the webview would just load a local, bundled version

**Comment by MuntashirAkon** [comment]
> * If there's internet connectivity the webview would show the actual docs webpage

That would go against the no Internet connection policy.

**Comment by MuntashirAkon** [comment]
This will be implemented in the following way:

Docs will be bundled with AM and will be located in the assets folder. In the APKS file, this will be available as a separate feature split which can be installed by the users if they choose to. If they don't install it, AM will open the URL in a web browser instead. In other cases, docs will always be bundled.

INTERNET permission will be removed from the main APK (hopefully in v2.5.22) as stated in #152 as many people are constantly emailing me about the permission despite my explanation that this permission doesn't have anything to do with the Internet in general. It is used to make socket connection and unfortunately, Android cannot distinguish between remote and local socket connections.

**Comment by MuntashirAkon** [comment]
Closed via 1a510f92 and 6c6ead9c.

**Comment by RickyM7** [comment]
@MuntashirAkon I tested it and it worked perfectly here. Two questions, would it be possible to make the docs page automatically detect the language of the device and switch to it (if the docs are translated into that language)? Would it be possible to make the docs page follow the app theme?

**Comment by MuntashirAkon** [comment]
> would it be possible to make the docs page automatically detect the language of the device and switch to it (if the docs are translated into that language)?

I've thought about it but concluded that it's not necessary for now as docs in other languages are not very up-to-date. I don't want to take extra burden right now.

> Would it be possible to make the docs page follow the app theme?

I haven't yet found any good VuePress plugin that does that automatically.

**Comment by RickyM7** [comment]
> I've thought about it but concluded that it's not necessary for now as docs in other languages are not very up-to-date. I don't want to take extra burden right now.

Really. Btw, I hope to finish translating the docs to pt-BR this month or next month, my biggest problem is that I am not fluent in English so I end up taking a while to review everything carefully.

> I haven't yet found any good VuePress plugin that does that automatically.

Got it!

**Comment by MuntashirAkon** [comment]
> I hope to finish translating the docs to pt-BR this month or next month, my biggest problem is that I am not fluent in English so I end up taking a while to review everything carefully.

Take your time.

**Comment by RickyM7** [comment]
@MuntashirAkon I've finished translating the docs to pt-BR.
Note (about the changelog page): I translated this page in a very superficial way (with the exception of the changelogs of v2.5.13 and v2.5.12, as they are the latest versions of this page).
I will translate more carefully the changelogs of the new versions.

**Comment by MuntashirAkon** [comment]
> Note (about the changelog page): I translated this page in a very superficial way (with the exception of the changelogs of v2.5.13 and v2.5.12, as they are the latest versions of this page).

No problem. I also require some additional translations which I'll PM you via Crowdin.

**Comment by MuntashirAkon** [comment]
pt-BR is now live at: https://muntashirakon.github.io/AppManager/pt-BR/
