### ISSUE TITLE
Ability to use any file explorer to explore files

### ISSUE THREAD

**Issue by Deerp1976** [MuntashirAkon/AppManager#21]
Phone Huawei Honor 8S
Android OS EMUI 9.1.0
Rooted - no
Usage Information Access permission given to Application Manager
Application version used 2.5.1 from Izzys Fdroid repo.

I can only use MiXplorer and Solid Explorer to access folders and files from this app. I would like the opportunity to use the one I use the most - File Explorer.

![Screenshot_20200621_182709_com huawei android internal app](https://user-images.githubusercontent.com/61953306/85231192-1a6a0c00-b3ed-11ea-8c6d-a5b254cd4f9b.jpg)

Also what does the Large Heap mean when I check your app?

**Comment by MuntashirAkon** [comment]
> I can only use MiXplorer and Solid Explorer to access folders and files from this app. I would like the opportunity to use the one I use the most - File Explorer.

You mean the file explorer that comes with your device? Probably it is not shown because it cannot open it. I need more info about that (I used Android's default file opener/provider).

> Also what does the Large Heap mean when I check your app?

Large heap means the app has requested higher memory than what is typically required. But rest assured, AppManager in general do not use high memory. High memory usage is required (by 3xodus) in order to scan apps that are quite large in size such as Google Chrome or Bromite. Without requesting large heap, AppManager will crash if you try to scan apps for trackers which are large in size.

**Comment by Deerp1976** [comment]
This is the file explorer I use the most - https://play.google.com/store/apps/details?id=nextapp.fxhttps://play.google.com/store/apps/details?id=nextapp.fx

It is the only 1 I know with the ability to open dev, proc, data folders in system folders on Android even on non rooted phones although gaining access to most files is quite limited. 

I see you're trying to get access to /data/user folders. Is this the same folders as in data/data folder or is it different?

I'm not sure if FX can access /data/user folders I will investigate further for you.

I also use 3c Toolbox Pro which has a built in explorer too.

**Comment by Deerp1976** [comment]
Just tested both FX File Explorer and 3c Toolbox Pro.

FX File Explorer is able to gain access to data/app folder no issues at all. Only issue is I cannot access the oat folder but can open lib folder and explore the base.apk no problems whatsoever.

3c Toolbox Explorer cannot even open the data folder via normal means but if I copy the path directly into its explorer part, it is able to open up the data/app for any application. Again it cannot open the oat folder  without root.

![Screenshot_20200621_185638_nextapp fx](https://user-images.githubusercontent.com/61953306/85231791-07a60600-b3f2-11ea-8e66-59406edea6a0.jpg)
![Screenshot_20200621_185836_ccc71 at free](https://user-images.githubusercontent.com/61953306/85231793-08d73300-b3f2-11ea-8bb7-7e9315f30390.jpg)
![Screenshot_20200621_185631_nextapp fx](https://user-images.githubusercontent.com/61953306/85231794-096fc980-b3f2-11ea-8521-1f4b75c96da0.jpg)

These have been tested just opening up each application or if I attempted to open the APK file from another app and it gives me the option to choose what Application Iw want to use to open the file/folder.

**Comment by MuntashirAkon** [comment]
> I see you're trying to get access to /data/user folders. Is this the same folders as in data/data folder or is it different?

Not always. `/data/user/0/<package-name>` directories are often just symbolic link to `/data/data` but  device-protected data directories (ie. `/data/user_de/<user-id>/<package-name>` are not, and so is the data directories of other users.

> I'm not sure if FX can access /data/user folders I will investigate further for you.

AFAIK, only privileged apps can open `/data` folder. If an app is not privileged, it needs to use third-party API like the one provided by Shizuku.

**Comment by MuntashirAkon** [comment]
> Just tested both FX File Explorer and 3c Toolbox Pro.

Probably they don't support file opening from third-party apps? I'll check to see if that's the case.

**Comment by Deerp1976** [comment]
I don't know how FX File Explorer is able to get privileged access to data/data folder but I can actually access this folder albeit the only app folder I can open is its own application. It cannot access data/user folder via any means including the sym link. 

I can open any file with numerous choices of applications from within FX File Explorer. If I so wished I could attempt to open an apk file to view its contents with a music application although obviously it won't work! 

Only thing it cannot do is open an apk file with Google Play Store or other app store as Google took away access to content uri back in 2018 according to FX File Explorer.

See screenshots for details as I'm genuinely interested in how this particular file explorer as additional access to other file explorers even when non rooted.

![Screenshot_20200621_191505_nextapp fx](https://user-images.githubusercontent.com/61953306/85232076-679dac00-b3f4-11ea-8d1b-f38bc2aebbd3.jpg)
![Screenshot_20200621_191443_nextapp fx](https://user-images.githubusercontent.com/61953306/85232077-68ced900-b3f4-11ea-85c5-cf9a14fb0d89.jpg)
![Screenshot_20200621_191232_nextapp fx](https://user-images.githubusercontent.com/61953306/85232078-6a989c80-b3f4-11ea-85e0-649f37cdf302.jpg)

**Comment by MuntashirAkon** [comment]
This is interesting. I'll definitely look into it.

**Comment by Deerp1976** [comment]
No problems and thank you for all your hard work with this app. It's made my life a lot easier having just 1 app to use instead of 4 or 5!

The only reason I bought up using other file explorers is because the two Ive mentioned seem to have access to files/folders others do not so if its possible to update your app to include the option to choose other apps to open files, it opens up more possibilities.

Thanks again.

**Comment by Deerp1976** [comment]
> > I can only use MiXplorer and Solid Explorer to access folders and files from this app. I would like the opportunity to use the one I use the most - File Explorer.
> 
> You mean the file explorer that comes with your device? Probably it is not shown because it cannot open it. I need more info about that (I used Android's default file opener/provider).
> 
> > Also what does the Large Heap mean when I check your app?
> 
> Large heap means the app has requested higher memory than what is typically required. But rest assured, AppManager in general do not use high memory. High memory usage is required (by 3xodus) in order to scan apps that are quite large in size such as Google Chrome or Bromite. Without requesting large heap, AppManager will crash if you try to scan apps for trackers which are large in size.

Very interesting indeed. So your app has the capability to check if an app is using more memory than normal. Is it able to do with with any app? I have a game that often crashes to home screen which according to the game developers is fully compatible with my phone. Even after sorting out battery optimization, which apps I allow to keep in background etc, game still crashes. If your app is able to detect others which have memory leakage issues I would be very happy indeed. As you cannot check logcat without root apart from the application you're using as a logcat, it's difficult to gain access to why apps are crashing either with ANR crash reports or logcat. Certainly your app will be very useful indeed if it has the ability to check memory usage of other apps and if they use more memory than they usually use.

**Comment by MuntashirAkon** [comment]
> So your app has the capability to check if an app is using more memory than normal. Is it able to do with with any app?

Not really. It just checks if `FLAG_LARGE_HEAP` is enabled ie. whether there's `android:largeHeap=true` in **Manifest.xml**.

About **FX**, the app does have a public activity for file explorer (ie. `nextapp.fx.ui.ExplorerActivity`) but there's no documentation on whether it can be used to open any file or folder. A folder has the type `resources/folder` and there's no default handler such mime type in FX. That's why it couldn't open the folders, and there's nothing I can do about it: you should contact them to see if they provide any solution.

**Comment by 5c0tt-b0t** [comment]
**+1** I like the multiple file managers idea, but I use open source only: 'Material Files' or 'Ghost Commander'. They are the best open source file managers (both very good root browsers too!).

**Comment by Deerp1976** [comment]
> **+1** I like the multiple file managers idea, but I use open source only: 'Material Files' or 'Ghost Commander'. They are the best open source file managers (both very good root browsers too!).

It's a pity the ability to use other file explorers does not work yet as if I use Solid Explorer to view the /data/user folder via here it just gives me a pop up to say it cannot access and I have to force stop the app to do anything after that! It's not this apps fault, it's Solid Explorers for not giving the ability to back out and go back to main menu. 

Total Commander is another favourite of mine as its highly customizable, is very small file size and can even use it as a media player and transfer files to cloud services. 

I used to use ES File Explorer until they were pulled from Play Store for having adverts in their app that could be secretly clicked on by the app itself to generate ad revenue even when you wasn't using your phone and I do not tolerate behaviour like that from any app.

**Comment by 5c0tt-b0t** [comment]
> Total Commander is another favourite of mine as its highly customizable, is very small file size and can even use it as a media player and transfer files to cloud services.

Yes, another great file manager! whilst its not open source... it contains no ADs OR trackers! so a good choice, plus its fairly popular.

- Material Files
- Ghost Commander
- Total Commander

I think should be looked at, my two being the best open source apps, Total Commander being a privacy-respecting app widely available from Play Store.
Not all of these apps may be compatible, but I do think they are the best file managers to look into for sure.

**Comment by Deerp1976** [comment]
Is Material Files on FDroid? I will check it out as I like different apps for different purposes.

FX File Explorer is easily my favourite but it does have in-app purchase so don't believe you will like it for that reason. Only problem it has is extracting zip files as they take absolutely ages compared to say ZArchiver for example and it won't view or open RAR files at all. It's media scanner is surprisingly quick compared to other apps I've used and even the one built in your phone.

**Comment by MuntashirAkon** [comment]
BTW, Material Files uses native calls to fetch files and directories which means it won't be able to open `/data/apk` folder if you don't have root.

**Comment by MuntashirAkon** [comment]
> I like the multiple file managers idea

File managers are supposed to handle file URIs which **FX** doesn't. So, I can't help with that I'm afraid.

**Comment by 5c0tt-b0t** [comment]
Yeah as I said, some will not be compatible, I have root so I'm fine, and I do not use FX file manager either, I would just like to open the directories stated by the app in Material Files/Ghost Commander as I only use open source apps, I love MiXplorer but its does contain tracking, although this can be turned off in settings but I noticed from System Monitor it still connects to the internet :'( though, I am sure App Manager can sort this out now! :D **Thank you again**

**Comment by MuntashirAkon** [comment]
What I can do is let you browse the contents of the `/data/app/<package-name>` directory within the app. But since apk sharing is available already, I don't see why this should be implemented.
