### ISSUE TITLE
App Info does not load

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#211]
**Describe the bug**
The app information doesn't load, the "App Info" tab keeps loading endlessly.
Note 1: This only occurs in the "App Info" tab.
Note 2: The "App Info" tab loads without any problems in shared external apps.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Click on an app within AM
2. See error

**Screenshots**
![AppInfo](https://user-images.githubusercontent.com/24703825/103525199-9d205900-4e5d-11eb-9f4d-213b40a28993.jpg)

**Device info**
 - Device: Redmi Note 4
 - OS Version: MIUI 11 (Android 7.0)
 - App Manager Version: v2.5.22-DEBUG#681
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Unfortunately, I can't seem to reproduce it in no-root mode in A11.

**Comment by RickyM7** [comment]
@MuntashirAkon I tested and this bug started from the v2.5.22-DEBUG#679. The versions below this (like the v2.5.22-DEBUG#678) work normally.

**Comment by MuntashirAkon** [comment]
Still not sure what's causing this issue. I'll try one by one.

**Comment by MuntashirAkon** [comment]
Fixed via 518d1f0f

**Comment by a-pav** [comment]
I have this issue. It happens in ADB over TCP mode. Before enabling AoT it works as expected. But after, Tab Info just keeps loading 'endlessly' with no result. 

OS Version: 5.1.1
AM Version: 2.6.5 (396)

**Comment by MuntashirAkon** [comment]
@a-pav: What about v2.6.5.1?

**Comment by MuntashirAkon** [comment]
Closed due to lack of response from @a-pav. Feel free to open it again if you're still facing the issue.
