### ISSUE TITLE
Date & Time Formats

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#215]
### Is your feature request related to a problem? Please describe.
Date and time formats vary widely from place to place, so it would be cool to have an option to choose the format that will be shown in the app.
Note: I know there are few places in the app that show a date and time, but even so I think having this option would be helpful.

### Describe the solution you'd like
I think the example in "Additional Context" shows very well what I want.

### Additional context

| Example (App in Example: Simple Gallery Pro) |
| --- |
| ![IMG_20201101_195444](https://user-images.githubusercontent.com/24703825/97817708-c6194780-1c7c-11eb-85f3-ecdcf051a5ec.jpg) |

**Comment by Atrate** [comment]
I think AM should just use the system datetime format. An option would be to also allow the user to set it to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by RickyM7** [comment]
> I think AM should just use the system datetime format.

That would be perfect.

> An option would be to also allow the user to set it to ISO 8601.

That would be interesting too.

**Comment by MuntashirAkon** [comment]
> I think AM should just use the system datetime format. An option would be to also allow the user to set it to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

I think using the system datetime format is enough in our case. Unlike language or theme, people don't really customize the datetime format.

**Comment by MuntashirAkon** [comment]
Fixed in 48eb3185.
