### ISSUE TITLE
Backup presets

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#216]
Related issues: #61, #72, #136, #197

Now that profiles have been implemented, I think that several backup (and possibly restore) "presets" could be included for the user to choose and duplicate to customize.

Presets in order of perceived importance:
- Backup all user apps whose data has changed since last backup
- Backup all updated apps
- Redo all existing backups
- Verify (check integrity) of all backups and redo broken ones

Presets in order of perceived ease of implementation
- Redo all existing backups
- Verify (check integrity) of all backups and redo broken ones
- Backup all updated apps
- Backup all user apps whose data has changed since last backup

How it looks in Titanium Backup: ![TB Image](https://www.technorms.com/ezoimgfmt/mk0technormsdod2v8ll.kinstacdn.com/wp-content/uploads/2011/10/Titanium-Backup-Batch-Backup-and-Restore.jpg?ezimgfmt=rs:625x523/rscb3/ng:webp/ngcb3)

**Comment by MuntashirAkon** [comment]
#136 is also very similar to the issue.

**Comment by Atrate** [comment]
It seems that this is actually a dup of #136, I'll close
