### ISSUE TITLE
Inapp purchase remover

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#222]
Hey there,
I am unsure if this is in the scope of this project, but is there a chance of getting some kind of inapp purchase removal? I am using micog + Aurora, so inapp purchases don't work yet.
If you actually do implement this, it will propably come along with #138.
(I created another issue, because I wonder, if you even want to add this)
Thanks!

**Comment by Atrate** [comment]
See https://github.com/MuntashirAkon/AppManager/issues/138#issuecomment-729449885
