### ISSUE TITLE
APP launch consumes very very long time or crash.

### ISSUE THREAD

**Issue by lshilshi** [MuntashirAkon/AppManager#223]
**Device info**
 - Device: One Plus 7 Pro
 - OS Version: Android 9（H2OS）
 - App Manager Version: v2.5.21-pre
 - Mode: root
 -
**Additional context**
APP launch consumes very very long time.
Most of the time (>4/5) it will keep loading.
Few times（<1/10） it will go to the main activety after 3s
 or
crash.

Almost no crashes during normal operation after loading.

**Comment by MuntashirAkon** [comment]
No crashlogs or steps to reproduce.

**Comment by MuntashirAkon** [comment]
Closed due to inactivity. Feel free to open it again if you can still reproduce the error.

**Comment by lshilshi** [comment]
> No crashlogs or steps to reproduce.

until ver 2.5.24-PRE, APP launch consumes more time.
Crashes randomly during use, recurring operation unknown.
Attached below are 2 saved Logs.
