### ISSUE TITLE
Add app operation mode to crash log device info

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#225]
When pasting a crash log from AM, it has such device info attached:
```
Device Info:
App version: X
App version code: X
Android build version: X
Android release version: X
Android SDK version: X
Android build ID: X
Device brand: X
Device manufacturer: X
Device name: X
Device model: X
Device product name: X
Device hardware name: X
ABIs: X
ABIs (32bit): X
ABIs (64bit): X
System language: X
In-App Language: X
```

It might be worth also attaching app operation mode (root/adb/etc.) to it to ease debugging.

**Comment by MuntashirAkon** [comment]
Already added in a63e611.

**Comment by Atrate** [comment]
> Already added in [a63e611](https://github.com/MuntashirAkon/AppManager/commit/a63e611d9d2bc811731bf0b2a318c195bc71956d).

a77c311669c8d9ddb10e280eb0db8cf8f29f9729
