### ISSUE TITLE
AM doesn't sanitize profile names correctly

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#228]
**Describe the bug**
When creating profile names with characters such as spaces (or possibly "+"), AM fails to load the profile file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a profile with the name "Backup user apps+data"
2. Add apps to it, set backup options, save the profile
3. Exit AM
4. Try to open the profile
5. There are no apps added or options set.

You can then check the profile file. It gets created as `Backup_user apps+data.am.json`, so it seems that the first space gets sanitized but not subsequent ones.

**Expected behavior**
The filename should become `Backup_user_apps_data.am.json` or `Backup_user_apps+data.am.json` and AM should thus be able to load the profile (tested, changing spaces to underscores makes AM load it without a problem).

**Device info**
App version: 2.5.22-PRE
Android release version: 10
Android SDK version: 29
Device brand: lge
Device manufacturer: LGE
Device name: lucye
Device model: LG-H870
Device product name: lucye_global_com
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: root

**Comment by MuntashirAkon** [comment]
Fixed in f04411fb
