### ISSUE TITLE
More flexibility when selecting applications on lists

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#229]
**Is your feature request related to a problem? Please describe.**
Selecting large numbers of applications in profiles or 1-click ops can become very tiresome very quickly. Thus, the selection lists for apps could be revamped to include additional features.

**Describe the solution you'd like**
The lists where you select apps could have the following features:
1. Sorting (by package name, label, installation/update date, data size)
2. Filtering (system/user apps, or all the other filters from the main screen)
3. "Select all, deselect all"
4. "De/Select all system/user apps"
5. "Deselect/select all below/above". This option could appear when long-pressing on an item in the list, allowing the user to e.g. deselect all apps smaller/larger than an app in the list.

**Comment by MuntashirAkon** [comment]
Not possible considering the complexity of such scenario. However, the alternative is #162.

**Comment by MuntashirAkon** [comment]
About 1-click ops, the app list is visible there so that the user can select/deselect a few apps. If they need to select/deselect many apps, this isn't the right place to do so.
