### ISSUE TITLE
Backup folder name does not reflect current date

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#231]
**Describe the bug**
When making a backup and not providing a name, the folder's name gets set to "0" instead of the date. Setting a name (at least in Profiles) for the backup also doesn't result in a folder with the name `Name` but with `0_Name`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Backup an app without providing a backup name
2. Check the resulting backup folder's name. It will be "0"

**Expected behavior**
The backup folder should have the current date as the name.

**Device info**
App version: 2.5.22-PRE
Android release version: 10
Android SDK version: 29
Device brand: lge
Device manufacturer: LGE
Device name: lucye
Device model: LG-H870
Device product name: lucye_global_com
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: root

**Comment by MuntashirAkon** [comment]
Did you check the “Backup Multiple” flag?

**Comment by Atrate** [comment]
> Did you check the “Backup Multiple” flag?

No.

**Comment by Atrate** [comment]
Now I realise the "name" popup doesn't get shown when back-up multiple is deselected. Still, the second part of the issue stands.

**Comment by MuntashirAkon** [comment]
> Still, the second part of the issue stands.
> 
> > Setting a name (at least in Profiles) for the backup also doesn't result in a folder with the name Name but with 0_Name.
> 
> This may be intended, though.

Yes. The user ID is prefixed for a valid reason. Consider the situation when you back up an app for multiple users using the same name. However, it's not expected that users should be aware of it as they'll see `Name for user 0` during the restore.

**Comment by Atrate** [comment]
Alright, this makes sense, thanks for the explaination!
