### ISSUE TITLE
UX: Ongoing notification timeout

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#233]
This is a very low-priority issue.

**Describe the bug**
Ongoing notification about operation completion takes a few seconds to disappear after "done" notification is posted. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Use a 1-click op (e.g. blocking trackers)
2. Look at notifications
3. Notification about it being "done" gets posted, but the one about "operation running" remains for a couple of seconds.

The time it remains for on the screen seems to differ slightly between operations.

**Expected behavior**
The ongoing notification should disappear exactly as soon as the "done" notification gest posted.

**Device info**
App version: 2.5.22-PRE
Android release version: 10
Android SDK version: 29
Device brand: lge
Device manufacturer: LGE
Device name: lucye
Device model: LG-H870
Device product name: lucye_global_com
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: root

**Comment by MuntashirAkon** [comment]
This is an issue with the service itself. A foreground service needs a persistent notification and the notification runs as long as the service runs. The popup notification is generated by programmatically as soon as the tasks are finished. The service still takes some time to finish.

**Comment by Atrate** [comment]
Would it be a desirable outcome to generate the notification only after the service itself exits?

**Comment by MuntashirAkon** [comment]
> Would it be a desirable outcome to generate the notification only after the service itself exits?

OK, I'll investigate about it.

**Comment by MuntashirAkon** [comment]
Fixed in 31ae7af5
