### ISSUE TITLE
Improve search engine 

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#235]
Search apps by short name, i.e;
If I type 'ml', it'll contain "Mobile Legends Bang Bang" in the results.

For farther improvement;
If I type 'as', it'll contain "AppSales" ('Space absent in the middle') in the results.
Finally;
If I type 'coc', it'll contain "Clash of Clans" in the results.
If I type 'cc', it'll contain "Clash of Clans" in the results.

If still unclear you can ask me related questions;
This type of search is also used in a launcher app called "Nova launcher", you can try that too as an alternative.

P̷.̷S̷.̷ ̷A̷l̷t̷h̷o̷u̷g̷h̷,̷ ̷I̷ ̷d̷i̷d̷ ̷s̷a̷y̷ ̷I̷ ̷w̷o̷u̷l̷d̷ ̷s̷t̷o̷p̷ ̷f̷o̷l̷l̷o̷w̷i̷n̷g̷ ̷t̷h̷i̷s̷ ̷p̷r̷o̷j̷e̷c̷t̷,̷ ̷b̷u̷t̷ ̷I̷ ̷h̷a̷d̷ ̷t̷o̷ ̷r̷e̷t̷u̷r̷n̷ ̷b̷e̷c̷a̷u̷s̷e̷ ̷o̷f̷ ̷a̷ ̷l̷a̷c̷k̷ ̷o̷f̷ ̷a̷l̷t̷e̷r̷n̷a̷t̷i̷v̷e̷ ̷(̷y̷e̷t̷ ̷t̷o̷ ̷f̷i̷n̷d̷ ̷a̷ ̷p̷r̷o̷j̷e̷c̷t̷ ̷t̷h̷i̷s̷ ̷m̷u̷c̷h̷ ̷a̷c̷t̷i̷v̷e̷,̷ ̷t̷h̷i̷s̷ ̷t̷o̷o̷l̷ ̷s̷o̷l̷v̷e̷d̷ ̷m̷a̷n̷y̷ ̷b̷u̷g̷s̷ ̷e̷v̷e̷n̷ ̷i̷n̷ ̷r̷e̷c̷e̷n̷t̷ ̷d̷a̷y̷s̷ ̷t̷h̷a̷t̷ ̷s̷t̷i̷l̷l̷ ̷p̷e̷r̷s̷i̷s̷t̷s̷ ̷e̷v̷e̷n̷ ̷o̷n̷ ̷p̷a̷i̷d̷ ̷a̷p̷p̷s̷)̷ ̷a̷n̷d̷ ̷c̷o̷d̷i̷n̷g̷ ̷k̷n̷o̷w̷l̷e̷d̷g̷e̷ ̷(̷T̷h̷o̷,̷ ̷I̷'̷d̷ ̷s̷t̷i̷l̷l̷ ̷l̷i̷k̷e̷ ̷a̷ ̷f̷o̷r̷k̷ ̷t̷h̷a̷t̷ ̷w̷o̷u̷l̷d̷ ̷r̷e̷m̷o̷v̷e̷ ̷'̷s̷o̷m̷e̷'̷ ̷f̷o̷r̷c̷e̷d̷ ̷l̷i̷m̷i̷t̷a̷t̷i̷o̷n̷s̷ ̷b̷y̷ ̷t̷h̷e̷ ̷a̷u̷t̷h̷o̷r̷ ̷(̷a̷g̷a̷i̷n̷,̷ ̷t̷o̷ ̷w̷h̷o̷m̷ ̷I̷'̷m̷ ̷g̷r̷a̷t̷e̷f̷u̷l̷ ̷n̷e̷v̷e̷r̷t̷h̷e̷l̷e̷s̷s̷)̷,̷ ̷s̷i̷n̷c̷e̷ ̷i̷t̷'̷s̷ ̷o̷p̷e̷n̷-̷s̷o̷u̷r̷c̷e̷ ̷m̷a̷y̷b̷e̷ ̷o̷n̷e̷ ̷d̷a̷y̷,̷ ̷i̷f̷ ̷I̷ ̷l̷e̷a̷r̷n̷ ̷h̷o̷w̷ ̷t̷o̷ ̷c̷o̷d̷e̷,̷ ̷I̷'̷l̷l̷ ̷m̷a̷k̷e̷ ̷t̷h̷e̷ ̷f̷o̷r̷k̷ ̷m̷y̷s̷e̷l̷f̷)̷.̷ ̷A̷n̷d̷ ̷a̷b̷o̷u̷t̷ ̷t̷h̷e̷ ̷d̷i̷s̷a̷g̷r̷e̷e̷m̷e̷n̷t̷ ̷b̷e̷t̷w̷e̷e̷n̷ ̷m̷e̷ ̷a̷n̷d̷ ̷t̷h̷e̷ ̷a̷u̷t̷h̷o̷r̷,̷ ̷I̷'̷d̷ ̷t̷r̷y̷ ̷m̷y̷ ̷b̷e̷s̷t̷ ̷t̷o̷ ̷t̷a̷l̷k̷ ̷o̷n̷ ̷t̷h̷i̷n̷g̷s̷ ̷t̷h̷a̷t̷ ̷w̷e̷ ̷b̷o̷t̷h̷ ̷a̷g̷r̷e̷e̷ ̷o̷n̷ ̷a̷n̷d̷ ̷a̷v̷o̷i̷d̷ ̷s̷t̷u̷f̷f̷ ̷t̷h̷a̷t̷ ̷i̷s̷ ̷u̷n̷r̷e̷l̷a̷t̷e̷d̷ ̷t̷o̷ ̷t̷h̷i̷s̷ ̷p̷r̷o̷j̷e̷c̷t̷,̷ ̷i̷.̷e̷ ̷r̷e̷l̷i̷g̷i̷o̷n̷,̷ ̷p̷o̷l̷i̷t̷i̷c̷s̷.̷ ̷F̷i̷n̷a̷l̷l̷y̷,̷ ̷i̷f̷ ̷a̷n̷y̷ ̷o̷f̷ ̷m̷y̷ ̷s̷u̷g̷g̷e̷s̷t̷i̷o̷n̷ ̷s̷e̷e̷m̷s̷ ̷d̷u̷m̷b̷,̷ ̷j̷u̷s̷t̷ ̷c̷l̷o̷s̷e̷ ̷i̷t̷ ̷w̷i̷t̷h̷o̷u̷t̷ ̷e̷x̷p̷l̷a̷n̷a̷t̷i̷o̷n̷,̷ ̷i̷t̷'̷l̷l̷ ̷b̷e̷ ̷f̷o̷r̷ ̷t̷h̷e̷ ̷b̷e̷s̷t̷,̷ ̷I̷g̷.̷

**Comment by MuntashirAkon** [comment]
Thanks for this FR. I was actually looking forward to implementing this myself for some time now. But I wasn't so sure how much effort would it take.

**Comment by MuntashirAkon** [comment]
Fixed in d4bdff65

**Comment by Cyberavater** [comment]
This fast! 😲 thanks!
