### ISSUE TITLE
2.5.22 Dark/Night Mode broken

### ISSUE THREAD

**Issue by marcdw1289** [MuntashirAkon/AppManager#238]
**Describe the bug**
App starts with a blank screen. Can't back out. Have to forcefully close. Took awhile to figure out the reason. Any ROM using Substratum.
Clear cache and data. App starts up fine. Switch to Night mode and all is good until closed and try to open again.

No issues on non-rooted, non-Substratum device.

**To Reproduce**
Steps to reproduce the behaviour:
1a. Update against previously working app.
1b. App starts up with blank window.

2a. Clear data of app.
2b. App starts normally.
2c. Switch to Night mode. App functions normally until...
2d. Exit app and restart. Blank and frozen screen.
2e. Have to force close or clear from Recent/Overview.

**Expected behavior**
App to start normally and be ready for business.

**Screenshots**
None.

**Crash logs**
Using OctoDroid to post this. Linking not possible AFAIK. Will link log(s) later.

**Device info**
- Device: Motorola Moto G5 Plus potter
 - OS Version: Android 7.1.2, Tesla
 - App Manager Version: 2.5.22-PRE
 - Mode: root

- Device: Motorola Moto G5s Plus sanders
 - OS Version: Android 8.1.0, OmniROM
 - App Manager Version: 2.5.22-PRE
 - Mode: root

- Device: Essential PH-1 mata
 - OS Version: Android 9, /e/OS (LOS 16)
 - App Manager Version: 2.5.22-PRE
 - Mode: root

- Device: ZTE Axon 7
 - OS Version: Android 7.1.2, Candy7
 - App Manager Version: 2.5.22-PRE
 - Mode: root

Following device does not have the issue (no Substratum).
- Device: OnePlus 8T (no root, locked)
 - OS Version: Android 11, OxygenOS 11
 - App Manager Version: 2.5.22-PRE
 - Mode: no-root

**Additional context**

**Comment by marcdw1289** [comment]
Apologies for how the devices list showed up. Tried to fix but couldn't.
Here's a recorded log, not sure if useful.

[appmgr_2021-01-16-22-40-37.txt.zip](https://github.com/MuntashirAkon/AppManager/files/5825731/appmgr_2021-01-16-22-40-37.txt.zip)

**Comment by MuntashirAkon** [comment]
Which version did you try? APKS or APK?

**Comment by marcdw1289** [comment]
Oh, sorry. App Manager was (has been) installed via F-Droid.

**Comment by MuntashirAkon** [comment]
> Oh, sorry. App Manager was (has been) installed via F-Droid so whichever is used from there.

Then it should be the APK file. Could you try the APKS from the GitHub release section. You'd notice that it contains a new split called `feat_docs`. Try without it first.

**Comment by marcdw1289** [comment]
Okay. Installed the APKS without `feat_docs`. Same result with blank screen. Tried a few more times with just minimal (base, arch, one DPI) and full (with and without `feat_docs`) but no go.

**Comment by MuntashirAkon** [comment]
Hmmm, I don't remember changing anything regarding night mode in v2.5.22. What was the last version that worked? v2.5.21, I guess?

**Comment by marcdw1289** [comment]
Yes, 2.5.21 is good.
But... Just discovered a couple of things. Substratum is not the issue. On two ROMs I disabled and uninstalled overlays, still got blank frozen screen. So I thought what's the diff between the one working ROM vs the others.
System dark mode.

Though ROMs have included that for ages I never use it because default contacts, phone, and/or calendar would still be white. Hence themes.
On the LOS Pie and Candy 7 Nougat I turned in the dark modes. Lo and behold App Manager (in Night Mode) works fine. Switch the ROMs back to default/light mode and AM doesn't work.

Would seem that night mode is now dependent on a ROM's dark mode? Either way, I'll have to stick with .21 for the time being.

**Comment by MuntashirAkon** [comment]
I don't think I will be able to sort this thing out without some help (I'm not even sure which sort of help is required here). I've looked at the difference between v2.5.21 and v2.5.22, and I was correct. I haven't changed anything regarding light/dark mode between these versions.

**Comment by marcdw1289** [comment]
Yeah, it is an odd situation I have. When I get the chance I'll compare logs from all the devices and see what stands out.
Thanks.

**Comment by MuntashirAkon** [comment]
Any update?

**Comment by marcdw1289** [comment]
Oh my. Many many apologies. I had been so busy I forgot about this.

Whatever issue I had with night mode on 2.5.22 disappeared with 2.5.23 and later builds.
Been on various ROMs, with & without Substratum with no issues. Not sure why .22 behaved the way it did on my phones.

Once again, so sorry for letting this issue stay open.
