### ISSUE TITLE
App install window - updating problems

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#241]
Hey, there
I'd like to always use the AM app install/update UI. I have a problem though: I want to install an app, the way the system default does: No removing of data, because, obviously, the signature changed when updating an app. Even though I just want to update the app, without requiring sig-ver to be turned off, I tried that option and got greeted by an "Invalid APK files selected"
What am I doing wrong? I just wanted to update MM..
Thanks!

**Comment by MuntashirAkon** [comment]
If the app your updating has different signature than the one you've installed, there's no way you can update it without uninstalling the app first. The only other option would be to use corepatch or something similar.

**Comment by Atrate** [comment]
> If the app your updating has different signature than the one you've installed, there's no way you can update it without uninstalling the app first. The only other option would be to use corepatch or something similar.

AFAIK it was possible in the past by just replacing the apk in /data/app and rebooting, but I don't know if it works that way anymore.

**Comment by UltraBlackLinux** [comment]
@MuntashirAkon 
Huh? If I am uaing the Android install thing, it works...
I just meant, a checksum of an app - I guess that's its signature - changes for sure, if you update an app.
Please try it yourself - try updating your MM via the update button in Magisk.

**Comment by MuntashirAkon** [comment]
> Huh? If I am using the Android install thing, it works...
> I just meant, a checksum of an app - I guess that's its signature - changes for sure, if you update an app.
> Please try it yourself - try updating your MM via the update button in Magisk.

Checksum isn't [signature](https://muntashirakon.github.io/AppManager/guide/app-details-page.html#signatures-tab). Please, don't confuse yourself and us by using terminologies that you don't understand. I've always updated Magisk Manager through AM and it always worked. So, my guess is you are doing something wrong. Make sure [Sign APK](https://muntashirakon.github.io/AppManager/guide/settings-page.html#sign-apk) is disabled in settings.

**Comment by hyemi96** [comment]
![image](https://user-images.githubusercontent.com/74815320/104950556-39bd2c00-5a04-11eb-8b4c-515e19c57704.jpeg)

![image](https://user-images.githubusercontent.com/74815320/104950563-3e81e000-5a04-11eb-8014-315e92a5ec83.jpeg)

개발은 어렵다..나는 코딩을 배운지 2개월되었습니다. 오늘은 깃허그를 처음 배워보고 이것저것 올려보고 새벽 3시에 잠에 듭니다.

**Comment by UltraBlackLinux** [comment]
@MuntashirAkon oh lol I had the signature thing enabled - I remember testing something... Didn't know it would affect ao much, anyways, thanks ;)

**Comment by Atrate** [comment]
@MuntashirAkon Looks like spam from @hyemi96. Reported to GitHub, you may want to delete the spam as well.
