### ISSUE TITLE
Strange behavior when opening the app

### ISSUE THREAD

**Issue by RickyM7** [MuntashirAkon/AppManager#246]
**Describe the bug**
Basically the list of apps doesn't load, but if you minimize the AM and come back quickly or go back to the AM settings and go back to the list of apps it will load quickly.

Maybe the issue #223 similar to this, but this does not occur in `v2.5.21-PRE` or `v2.5.22-PRE` on my phone.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open AM
2. See error

**Screenshots**

| ![1](https://user-images.githubusercontent.com/24703825/105479484-456a5600-5c83-11eb-87b5-51a660ed213b.jpg) | ![2](https://user-images.githubusercontent.com/24703825/105479497-48fddd00-5c83-11eb-9493-3ec82bae6e23.jpg) |
| :---: | :---: |

**Device info**
 - Device: Redmi Note 4
 - OS Version: MIUI11 (Android 7.0)
 - App Manager Version: v2.5.23-DEBUG#786
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
It can't be reproduced in Android 10 or later, therefore, I can't test it myself.

**Comment by MuntashirAkon** [comment]
Ok, I've refactored some code in b1182e2f and the issue might be fixed. Please check.

**Comment by RickyM7** [comment]
The bug still continues.

**Comment by RickyM7** [comment]
@MuntashirAkon I just saw that this bug started from the v2.5.23-DEBUG#777.

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon I just saw that this bug started from the v2.5.23-DEBUG#777.

Yes, I know.

**Comment by MuntashirAkon** [comment]
Should be fixed in 7b967a0d.

**Comment by RickyM7** [comment]
Fixed in v2.5.23-DEBUG#789. Thank you!
