### ISSUE TITLE
Cannot launch the app

### ISSUE THREAD

**Issue by DrizztFR** [MuntashirAkon/AppManager#248]
**Describe the bug**
When launching AppManager, I just have a black screen with my buttons at the bottom. The only thing happenning is the toast telling me AM got root privileges. I cannot swipe up to get my android activities but I can tap on the middle button to go back to the launcher. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app drawer
2. Click on the AppManager icon
3. Wait endlessly

**Expected behavior**
I expect the app to launch.

**Crash logs**
ActivityManager(1307): Activity pause timeout for ActivityRecord{e42c1b u0 io.github.muntashirakon.AppManager/.main.MainActivity t104}

**Device info**
 - Device: Xiaomi Mi Mix 2S
 - OS Version: LineageOS 16.0 (Android 9)
 - App Manager Version: v2.5.22-PRE
 - Mode: root

**Additional context**
I tried emptying the cache but nothing changed. Trying to downgrade from f-droid gives me an error

**Comment by DrizztFR** [comment]
Not sure if related : 01-25 02:32:47.542 E/DatabaseUtils(1307): java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.

**Comment by MuntashirAkon** [comment]
I need full logcat output without filters.

**Comment by DrizztFR** [comment]
01-25 02:39:28.195 D/AndroidRuntime( 5560): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:28.344 D/AndroidRuntime( 5560): Calling main entry com.android.commands.content.Content
01-25 02:39:28.373 I/ActivityManager( 1307): Start proc 5582:com.pvw4un.n25osnGDL/u0a108 for content provider com.pvw4un.n25osnGDL/a.p
01-25 02:39:28.410 D/AndroidRuntime( 5570): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:28.439 E/vw4un.n25osnGD( 5582): Not starting debugger since process cannot load the jdwp agent.
01-25 02:39:28.462 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:28.499 D/AndroidRuntime( 5570): Calling main entry com.android.commands.content.Content
01-25 02:39:28.517 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:28.524 D/OpenGLRenderer( 5582): Skia GL Pipeline
01-25 02:39:28.536 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:28.537 D/AndroidRuntime( 5560): Shutting down VM
01-25 02:39:28.545 D/AndroidRuntime( 5593): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:28.545 I/ActivityManager( 1307): Killing 1534:org.mozilla.fennec_fdroid/u0a235 (adj 906): empty #17
01-25 02:39:28.547 D/AndroidRuntime( 5570): Shutting down VM
01-25 02:39:28.549 W/libprocessgroup( 1307): kill(-1534, 9) failed: No such process
01-25 02:39:28.575 D/AndroidRuntime( 5601): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:28.596 W/libprocessgroup( 1307): kill(-1534, 9) failed: No such process
01-25 02:39:28.602 I/Adreno  ( 5582): QUALCOMM build                   : 791494e, Id7006ec082
01-25 02:39:28.602 I/Adreno  ( 5582): Build Date                       : 12/09/18
01-25 02:39:28.602 I/Adreno  ( 5582): OpenGL ES Shader Compiler Version: EV031.24.02.00
01-25 02:39:28.602 I/Adreno  ( 5582): Local Branch                     : 
01-25 02:39:28.602 I/Adreno  ( 5582): Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.3.R1.09.00.00.423.045
01-25 02:39:28.602 I/Adreno  ( 5582): Remote Branch                    : NONE
01-25 02:39:28.602 I/Adreno  ( 5582): Reconstruct Branch               : NOTHING
01-25 02:39:28.603 I/Adreno  ( 5582): Build Config                     : S P 6.0.7 AArch64
01-25 02:39:28.606 I/Adreno  ( 5582): PFP: 0x016ee180, ME: 0x00000000
01-25 02:39:28.603 W/RenderThread( 5582): type=1400 audit(0.0:757): avc: denied { search } for name="proc" dev="debugfs" ino=14972 scontext=u:r:untrusted_app:s0:c108,c256,c512,c768 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
01-25 02:39:28.603 W/RenderThread( 5582): type=1400 audit(0.0:758): avc: denied { search } for name="ctx" dev="debugfs" ino=15001 scontext=u:r:untrusted_app:s0:c108,c256,c512,c768 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
01-25 02:39:28.617 W/RenderThread( 5582): type=1400 audit(0.0:759): avc: denied { search } for name="ctx" dev="debugfs" ino=15001 scontext=u:r:untrusted_app:s0:c108,c256,c512,c768 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
01-25 02:39:28.615 I/ConfigStore( 5582): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
01-25 02:39:28.616 I/ConfigStore( 5582): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
01-25 02:39:28.617 I/OpenGLRenderer( 5582): Initialized EGL, version 1.4
01-25 02:39:28.617 D/OpenGLRenderer( 5582): Swap behavior 2
01-25 02:39:28.641 I/Zygote  (  668): Process 1534 exited due to signal (9)
01-25 02:39:28.641 W/libprocessgroup( 1307): kill(-1534, 9) failed: No such process
01-25 02:39:28.641 I/libprocessgroup( 1307): Successfully killed process cgroup uid 10235 pid 1534 in 95ms
01-25 02:39:28.645 D/AndroidRuntime( 5593): Calling main entry com.android.commands.content.Content
01-25 02:39:28.647 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:28.660 D/AndroidRuntime( 5593): Shutting down VM
01-25 02:39:28.672 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=1591ce0 Toast)/@0x59a123f - animation-leash to Surface(name=1591ce0 Toast)/@0x59a123f - animation-leash#1
01-25 02:39:28.677 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@d420a37
01-25 02:39:28.686 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#1
01-25 02:39:28.697 D/AndroidRuntime( 5601): Calling main entry com.android.commands.content.Content
01-25 02:39:28.701 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:28.705 D/AndroidRuntime( 5601): Shutting down VM
01-25 02:39:28.713 I/ThermalEngine(  981): vs_get_temperature: read[0] xo_therm 36718 mC, weight[0] 2
01-25 02:39:28.713 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=2e55d0d Toast)/@0x2dd7e10 - animation-leash to Surface(name=2e55d0d Toast)/@0x2dd7e10 - animation-leash#1
01-25 02:39:28.714 I/ThermalEngine(  981): vs_get_temperature: read[1] quiet_therm 34264 mC, weight[1] 1
01-25 02:39:28.716 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@d046b3c
01-25 02:39:28.717 D/AndroidRuntime( 5632): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:28.733 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#2
01-25 02:39:28.809 D/AndroidRuntime( 5632): Calling main entry com.android.commands.content.Content
01-25 02:39:28.812 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:28.818 D/AndroidRuntime( 5632): Shutting down VM
01-25 02:39:28.821 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=7262a1a Toast)/@0x4aff28 - animation-leash to Surface(name=7262a1a Toast)/@0x4aff28 - animation-leash#1
01-25 02:39:28.826 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@c2656c3
01-25 02:39:28.844 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#3
01-25 02:39:28.847 D/AndroidRuntime( 5656): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:28.883 D/AndroidRuntime( 5672): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:28.929 D/AndroidRuntime( 5656): Calling main entry com.android.commands.content.Content
01-25 02:39:28.933 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:28.938 D/AndroidRuntime( 5656): Shutting down VM
01-25 02:39:28.940 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=d2cfa79 Toast)/@0xc8d9c1f - animation-leash to Surface(name=d2cfa79 Toast)/@0xc8d9c1f - animation-leash#1
01-25 02:39:28.944 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@f8e7fb1
01-25 02:39:28.954 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#4
01-25 02:39:28.965 D/AndroidRuntime( 5672): Calling main entry com.android.commands.content.Content
01-25 02:39:28.968 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:28.971 D/AndroidRuntime( 5672): Shutting down VM
01-25 02:39:28.981 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=e20f017 Toast)/@0xc5a65ed - animation-leash to Surface(name=e20f017 Toast)/@0xc5a65ed - animation-leash#1
01-25 02:39:28.984 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@d5bcb0f
01-25 02:39:28.993 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#5
01-25 02:39:29.020 D/AndroidRuntime( 5690): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:29.104 D/AndroidRuntime( 5690): Calling main entry com.android.commands.content.Content
01-25 02:39:29.109 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:29.121 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=42765a5 Toast)/@0x7153188 - animation-leash to Surface(name=42765a5 Toast)/@0x7153188 - animation-leash#1
01-25 02:39:29.122 D/AndroidRuntime( 5690): Shutting down VM
01-25 02:39:29.116 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:29.125 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@8114a93
01-25 02:39:29.131 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#6
01-25 02:39:29.142 D/AndroidRuntime( 5714): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:29.152 D/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener( 3330): Notification posted: com.pluscubed.matloglibre: null
01-25 02:39:29.155 I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener( 3330): Not forwarding notification, screen seems to be on and settings do not allow this
01-25 02:39:29.155 I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener( 3330): Ignore notification: com.pluscubed.matloglibre
01-25 02:39:29.170 W/SurfaceFlinger(  809): Attempting to set client state on removed layer: com.pluscubed.matloglibre/com.pluscubed.logcat.ui.RecordLogDialogActivity#2
01-25 02:39:29.170 W/SurfaceFlinger(  809): Attempting to destroy on removed layer: com.pluscubed.matloglibre/com.pluscubed.logcat.ui.RecordLogDialogActivity#2
01-25 02:39:29.229 D/AndroidRuntime( 5714): Calling main entry com.android.commands.content.Content
01-25 02:39:29.236 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:29.240 D/AndroidRuntime( 5714): Shutting down VM
01-25 02:39:29.242 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=d61ac9 Toast)/@0x515d0a6 - animation-leash to Surface(name=d61ac9 Toast)/@0x515d0a6 - animation-leash#1
01-25 02:39:29.245 W//system/bin/app_process( 5714): Thread attaching while runtime is shutting down: Binder:5714_2
01-25 02:39:29.245 I/AndroidRuntime( 5714): NOTE: attach of thread 'Binder:5714_2' failed
01-25 02:39:29.245 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@b0ad48a
01-25 02:39:29.258 D/AndroidRuntime( 5735): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:29.265 W/SurfaceFlinger(  809): Attempting to set client state on removed layer: Dim Layer for - Task=121#1
01-25 02:39:29.265 W/SurfaceFlinger(  809): Attempting to destroy on removed layer: Dim Layer for - Task=121#1
01-25 02:39:29.299 W/SurfaceFlinger(  809): Attempting to set client state on removed layer: com.pluscubed.matloglibre/com.pluscubed.logcat.ui.RecordLogDialogActivity#1
01-25 02:39:29.299 W/SurfaceFlinger(  809): Attempting to destroy on removed layer: com.pluscubed.matloglibre/com.pluscubed.logcat.ui.RecordLogDialogActivity#1
01-25 02:39:29.335 D/AndroidRuntime( 5740): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:29.345 D/AndroidRuntime( 5735): Calling main entry com.android.commands.content.Content
01-25 02:39:29.349 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:29.359 D/AndroidRuntime( 5735): Shutting down VM
01-25 02:39:29.361 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=27c4718 Toast)/@0x3d00bd7 - animation-leash to Surface(name=27c4718 Toast)/@0x3d00bd7 - animation-leash#1
01-25 02:39:29.357 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:29.364 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@40dbf65
01-25 02:39:29.367 D/AndroidRuntime( 5748): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-25 02:39:29.373 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#1
01-25 02:39:29.419 D/AndroidRuntime( 5740): Calling main entry com.android.commands.content.Content
01-25 02:39:29.422 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:29.426 D/AndroidRuntime( 5740): Shutting down VM
01-25 02:39:29.427 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=a8c58eb Toast)/@0x19ba648 - animation-leash to Surface(name=a8c58eb Toast)/@0x19ba648 - animation-leash#1
01-25 02:39:29.429 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@288fa63
01-25 02:39:29.443 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#2
01-25 02:39:29.451 D/AndroidRuntime( 5748): Calling main entry com.android.commands.content.Content
01-25 02:39:29.455 D/ActivityManager( 1307): Raise procstate to external provider: ProcessRecord{1b17cc8 5582:com.pvw4un.n25osnGDL/u0a108}
01-25 02:39:29.463 D/AndroidRuntime( 5748): Shutting down VM
01-25 02:39:29.475 D/SurfaceFlinger(  809): duplicate layer name: changing Surface(name=d505719 Toast)/@0xc864bd5 - animation-leash to Surface(name=d505719 Toast)/@0xc864bd5 - animation-leash#1
01-25 02:39:29.477 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@7ecd051
01-25 02:39:29.485 D/SurfaceFlinger(  809): duplicate layer name: changing Toast to Toast#3
01-25 02:39:29.722 I/ThermalEngine(  981): vs_get_temperature: read[0] xo_therm 37031 mC, weight[0] 2
01-25 02:39:29.724 I/ThermalEngine(  981): vs_get_temperature: read[1] quiet_therm 34264 mC, weight[1] 1
01-25 02:39:29.893 I/netd    (  667): gethostby*.getanswer: asked for "dealer.spotify.com IN AAAA", got type "HINFO"
01-25 02:39:30.080 I/ThermalEngine(  981): vs_get_temperature: read[0] xo_therm 37187 mC, weight[0] 2
01-25 02:39:30.081 I/ThermalEngine(  981): vs_get_temperature: read[1] quiet_therm 34264 mC, weight[1] 1
01-25 02:39:30.728 I/ThermalEngine(  981): vs_get_temperature: read[0] xo_therm 37343 mC, weight[0] 2
01-25 02:39:30.729 I/ThermalEngine(  981): vs_get_temperature: read[1] quiet_therm 34264 mC, weight[1] 1
01-25 02:39:30.796 I/SlideTouchEvent( 1775): vel=0.0, MinimumFlingVelocity=150
01-25 02:39:31.112 V/StatusBar( 1775): mStatusBarWindow: com.android.systemui.statusbar.phone.StatusBarWindowView{eb54e3f V.ED..... ........ 0,0-1080,72} canPanelBeCollapsed(): false
01-25 02:39:31.113 I/sysui_view_visibility( 1775): [207,0]
01-25 02:39:31.114 I/vol.Events( 1775): writeEvent dismiss_dialog volume_controller
01-25 02:39:31.114 I/sysui_multi_action( 1775): [757,207,758,2]
01-25 02:39:31.117 I/ActivityManager( 1307): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher (has extras)} from uid 1000
01-25 02:39:31.118 I/am_new_intent( 1307): [0,205091432,27,ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher,android.intent.action.MAIN,NULL,NULL,268435712]
01-25 02:39:31.119 I/wm_task_moved( 1307): [27,0,2147483647]
01-25 02:39:31.120 I/am_focused_stack( 1307): [0,0,95,bringingFoundTaskToFront]
01-25 02:39:31.120 I/wm_task_moved( 1307): [27,0,2147483647]
01-25 02:39:31.121 I/am_pause_activity( 1307): [0,232312291,com.pluscubed.matloglibre/com.pluscubed.logcat.ui.LogcatActivity,userLeaving=true]
01-25 02:39:31.124 I/am_set_resumed_activity( 1307): [0,ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher,resumeTopActivityInnerLocked]
01-25 02:39:31.129 I/am_resume_activity( 1307): [0,205091432,27,ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher]
01-25 02:39:31.130 I/am_task_to_front( 1307): [0,27]
01-25 02:39:31.137 D/Launcher.Utilities( 3294): onLauncherStart: 0
01-25 02:39:31.137 I/am_on_restart_called( 3294): [0,ch.deletescape.lawnchair.LawnchairLauncher,performRestartActivity]
01-25 02:39:31.139 W/ActivityManager( 1307): Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://ch.deletescape.lawnchair.plah:10500?v=7&cv=9 pkg=com.google.android.googlequicksearchbox } U=0: not found
01-25 02:39:31.139 I/am_on_start_called( 3294): [0,ch.deletescape.lawnchair.LawnchairLauncher,handleStartActivity]
01-25 02:39:31.139 I/am_on_resume_called( 3294): [0,ch.deletescape.lawnchair.LawnchairLauncher,RESUME_ACTIVITY]
01-25 02:39:31.144 I/am_on_paused_called( 4360): [0,com.pluscubed.logcat.ui.LogcatActivity,performPause]
01-25 02:39:31.147 I/am_stop_activity( 1307): [0,232312291,com.pluscubed.matloglibre/com.pluscubed.logcat.ui.LogcatActivity]
01-25 02:39:31.148 I/sysui_count( 1307): [window_time_0,2]
01-25 02:39:31.148 I/sysui_multi_action( 1307): [757,803,799,window_time_0,802,2]
01-25 02:39:31.173 I/am_on_stop_called( 4360): [0,com.pluscubed.logcat.ui.LogcatActivity,STOP_ACTIVITY_ITEM]
01-25 02:39:31.226 I/sysui_multi_action( 1307): [319,103,322,98,325,131446,757,761,758,9,759,2,806,ch.deletescape.lawnchair.plah,871,ch.deletescape.lawnchair.LawnchairLauncher,905,0,1320,8,1321,5]
01-25 02:39:31.475 W/NotificationService( 1307): Toast already killed. pkg=com.pvw4un.n25osnGDL callback=android.app.ITransientNotification$Stub$Proxy@be0e797
01-25 02:39:31.731 I/ThermalEngine(  981): vs_get_temperature: read[0] xo_therm 37500 mC, weight[0] 2
01-25 02:39:31.732 I/ThermalEngine(  981): vs_get_temperature: read[1] quiet_therm 34264 mC, weight[1] 1
01-25 02:39:32.007 W/SurfaceFlinger(  809): Attempting to destroy on removed layer: e9041b7 Toast#0
01-25 02:39:32.084 I/ThermalEngine(  981): vs_get_temperature: read[0] xo_therm 37552 mC, weight[0] 2
01-25 02:39:32.085 W/WindowManager( 1307): Unable to start animation, surface is null or no children.
01-25 02:39:32.085 I/ThermalEngine(  981): vs_get_temperature: read[1] quiet_therm 34264 mC, weight[1] 1
01-25 02:39:32.089 E/Launcher.Utilities( 3294): mapToRange: range has 0 length
01-25 02:39:32.281 I/sysui_action( 3294): [629,0]
01-25 02:39:32.281 I/sysui_multi_action( 3294): [757,629,758,4,759,0]
01-25 02:39:32.530 D/RILJ    ( 2001): [8618]> RIL_REQUEST_GET_CELL_INFO_LIST [SUB1]
01-25 02:39:32.532 D/RILJ    ( 2001): [8618]< RIL_REQUEST_GET_CELL_INFO_LIST [] [SUB1]
01-25 02:39:32.532 D/LocaleTracker( 2001): getCellInfo: cell info=[]
01-25 02:39:32.532 D/LocaleTracker( 2001): Can't get cell info. Try again in 2 secs.
01-25 02:39:32.532 D/LocaleTracker( 2001): updateLocale: mcc = null, country = 
01-25 02:39:32.487 I/chatty  ( 3294): uid=10500(ch.deletescape.lawnchair.plah) identical 24 lines
01-25 02:39:32.504 E/Launcher.Utilities( 3294): mapToRange: range has 0 length
01-25 02:39:32.734 I/ThermalEngine(  981): vs_get_temperature: read[0] xo_therm 37604 mC, weight[0] 2
01-25 02:39:32.735 I/ThermalEngine(  981): vs_get_temperature: read[1] quiet_therm 34313 mC, weight[1] 1
01-25 02:39:32.867 I/chatty  ( 1307): uid=1000(system) android.display identical 8 lines
01-25 02:39:32.937 W/WindowManager( 1307): Unable to start animation, surface is null or no children.
01-25 02:39:32.950 I/ActivityManager( 1307): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.github.muntashirakon.AppManager/.main.MainActivity bnds=[230,264][436,616]} from uid 10500
01-25 02:39:32.953 I/wm_stack_created( 1307): 98
01-25 02:39:32.954 I/wm_task_created( 1307): [124,98]
01-25 02:39:32.955 I/wm_task_moved( 1307): [124,0,2147483647]
01-25 02:39:32.955 I/am_focused_stack( 1307): [0,98,0,reuseOrNewTask]
01-25 02:39:32.955 I/am_create_task( 1307): [0,124]
01-25 02:39:32.955 I/am_create_activity( 1307): [0,59809716,124,io.github.muntashirakon.AppManager/.main.MainActivity,android.intent.action.MAIN,NULL,NULL,270532608]
01-25 02:39:32.956 I/wm_task_moved( 1307): [124,0,2147483647]
01-25 02:39:32.957 I/am_pause_activity( 1307): [0,205091432,ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher,userLeaving=true]
01-25 02:39:32.979 W/WindowManager( 1307): Unable to start animation, surface is null or no children.
01-25 02:39:33.044 I/am_on_paused_called( 3294): [0,ch.deletescape.lawnchair.LawnchairLauncher,performPause]
01-25 02:39:33.044 I/am_uid_running( 1307): 10102
01-25 02:39:33.047 I/sysui_count( 1307): [window_time_0,2]
01-25 02:39:33.047 I/sysui_multi_action( 1307): [757,803,799,window_time_0,802,2]
01-25 02:39:33.058 I/am_proc_start( 1307): [0,5834,10102,io.github.muntashirakon.AppManager,activity,io.github.muntashirakon.AppManager/.main.MainActivity]
01-25 02:39:33.058 I/ActivityManager( 1307): Start proc 5834:io.github.muntashirakon.AppManager/u0a102 for activity io.github.muntashirakon.AppManager/.main.MainActivity
01-25 02:39:33.066 E/akon.AppManage( 5834): Not starting debugger since process cannot load the jdwp agent.
01-25 02:39:33.071 I/am_proc_bound( 1307): [0,5834,io.github.muntashirakon.AppManager]
01-25 02:39:33.076 I/am_uid_active( 1307): 10102
01-25 02:39:33.076 I/am_restart_activity( 1307): [0,59809716,124,io.github.muntashirakon.AppManager/.main.MainActivity]
01-25 02:39:33.077 I/am_set_resumed_activity( 1307): [0,io.github.muntashirakon.AppManager/.main.MainActivity,minimalResumeActivityLocked]
01-25 02:39:33.092 I/LoadedApk( 5834): No resource references to update in package io.github.muntashirakon.AppManager.feat_docs
01-25 02:39:33.228 I/am_on_create_called( 5834): [0,io.github.muntashirakon.AppManager.main.MainActivity,performCreate]
01-25 02:39:33.231 I/am_on_start_called( 5834): [0,io.github.muntashirakon.AppManager.main.MainActivity,handleStartActivity]
01-25 02:39:33.232 I/am_on_resume_called( 5834): [0,io.github.muntashirakon.AppManager.main.MainActivity,RESUME_ACTIVITY]
01-25 02:39:33.232 D/OpenGLRenderer( 5834): Skia GL Pipeline
01-25 02:39:33.245 I/am_on_paused_called( 5834): [0,io.github.muntashirakon.AppManager.main.MainActivity,performPause]
01-25 02:39:33.247 I/am_on_stop_called( 5834): [0,io.github.muntashirakon.AppManager.main.MainActivity,handleRelaunchActivity]
01-25 02:39:33.249 I/am_on_destroy_called( 5834): [0,io.github.muntashirakon.AppManager.main.MainActivity,performDestroy]

**Comment by MuntashirAkon** [comment]
Seems to be a duplicated of #238

**Comment by DrizztFR** [comment]
I tweaked my dark mode in android settings and I actually got AM to work. Totally related.

Settings working for me :
Dark mode on
Dark Mode Color set to Black (dark doesn't work anymore)

Thanks for your help

**Comment by MuntashirAkon** [comment]
Thanks. Closed in favour of #238.
