### ISSUE TITLE
Toggle MicroG GCM(FCM) registration status through AM

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#252]
With MicroG,it's able to choose which apps will receive Firebase's notification.
It can configure in MicroG settings.and this setting is stored in "/data/data/com.google.android.gms/databases/gcmstatus" as sqlite database.
It is better to make this settings configurable through AM.

**Comment by MuntashirAkon** [comment]
Can you explain this more elaborately, if possible, using additional context such as screenshots and links? I've never really used MicroG. I went from full-Google to full-FOSS, so never had to stuck in the middle.

**Comment by gnuhead-chieb** [comment]
Here is  a screenshot of MicroG GCM section
![Screenshot_20210128-222441](https://user-images.githubusercontent.com/41156994/106145132-11a09c00-616d-11eb-8f3f-c5edb98e70c0.png)


and here is a database sample(sqlite)
https://upload.disroot.org/r/AsV1ABfa#Oxn50CTvPbTjysOTvVgxEc9KSpFnVxJnY1PwHNySanI=

**Comment by MuntashirAkon** [comment]
The DB schema is as follows:
```sql
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE apps (
    package_name TEXT,
    last_error TEXT DEFAULT '',
    last_message_timestamp INTEGER,
    total_message_count INTEGER,
    total_message_bytes INTEGER,
    allow_register INTEGER DEFAULT 1,
    wake_for_delivery INTEGER DEFAULT 1,
    PRIMARY KEY (package_name)
);
CREATE TABLE registrations (
    package_name TEXT,
    signature TEXT,
    timestamp INTEGER,
    register_id TEXT,
    PRIMARY KEY (package_name, signature)
);
```

There's not much I can do without looking at the source. The issue is somewhat related to #14.

**Comment by HanabishiRecca** [comment]
> There's not much I can do without looking at the source.
MicroG is open source btw
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/gcm/GcmDatabase.java

**Comment by MuntashirAkon** [comment]
> MicroG is open source btw

I know that. I meant I have to inspect the source code in order to understand what to do with it. Simply changing the database shouldn't be enough unless there is some sort of database change listener (which is hardly expected).

**Comment by HanabishiRecca** [comment]
Ok. I just pointed to it.  
I personally don't think AM even really needs this feature. This thing too complicated. Even MicroG itself sometimes has issues with it.

**Comment by MuntashirAkon** [comment]
> Ok, just pointed to it.

The linked portion just stores the values in the database. I have to understand how this information is processed i.e. whether I have to run some service to ensure that the values are applied correctly.

**Comment by HanabishiRecca** [comment]
I don't think you want to mess with it. This actions is not local-only. MicroG also sends some registration requests to Google servers.

**Comment by MuntashirAkon** [comment]
> I don't think you want to mess with it. This actions is not local-only. MicroG also sends some registration requests to Google servers.

Could you point me where it is done provided you're familiar with the source code? Maybe I can understand it better for this purpose.

**Comment by HanabishiRecca** [comment]
> you're familiar with the source code?

No, I'm not familiar with the codebase. Just found this piece of code via search.

**Comment by MuntashirAkon** [comment]
> No, I'm not familiar with the codebase. Just found this piece of code via search.

Alright, no problem. I'll look into it in my free time.

**Comment by MuntashirAkon** [comment]
@gnuhead-chieb: It would be better if you ask the MicroG devs about it.

**Comment by MuntashirAkon** [comment]
MicroG doesn't provide any API to change this.
