### ISSUE TITLE
AM could not backup APKs to SD card location

### ISSUE THREAD

**Issue by kgursu** [MuntashirAkon/AppManager#257]
**Describe the bug**
On two of my devices, I tried to backup only APKs to their SD card location, but the process resulted as a failure. No APKs were created there while AM showing an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings/Backup-Restore/Backup Volume
2. Select SD card location (tried both /mnt/media_rw and /storage/ on debug version, also)
3. Go back to main screen
4. Select APKs you want
5. Click Backup APK on the 3-point lower-right side menu.

**Expected behavior**
I expected selected APKs to be backed up.

**Screenshots**
![IMG_20210131_094204_100.jpg](https://user-images.githubusercontent.com/35314872/106376686-a9d69500-63a8-11eb-94c2-c517e55f1165.jpg)
![IMG_20210131_094214_148.jpg](https://user-images.githubusercontent.com/35314872/106376690-b35ffd00-63a8-11eb-9a59-1f8e586bfb72.jpg)
![IMG_20210131_094221_005.jpg](https://user-images.githubusercontent.com/35314872/106376691-bbb83800-63a8-11eb-95f1-ab44c07595c6.jpg)

**Crash logs**
Got 2 logcats not from this simulation for getting screenshots, but from an instance with multiple selections of apps.
This one with /mnt/media_rw/ setting:
[https://del.dog/reegerucyp]()
This one with /storage/ setting:
[https://del.dog/fackimifay]()

**Device info**
 - Device: Sony Xperia Z2 (sirius)
 - OS Version: Android 10
 - App Manager Version: 2.5.23 Run#835
Similar results with 2.5.22 Pre-release

**Additional context**

**Comment by Atrate** [comment]
Can reproduce for normal backups

**Comment by MuntashirAkon** [comment]
It doesn't work because it isn't implemented yet.

**Comment by MuntashirAkon** [comment]
Implemented in 1901f893. Should work on both `/storage` and `mnt/media_rw` locations.

**Comment by kgursu** [comment]
Ok, thanks. Will try soon...

**Comment by kgursu** [comment]
6 apps' APKs could not be backed up. When I try to look which ones they are, AM crashes. Here is the crash log:

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.misc.HelpActivity}: android.view.InflateException: Binary XML file line #24 in io.github.muntashirakon.AppManager.debug:layout/activity_help: Binary XML file line #24 in io.github.muntashirakon.AppManager.debug:layout/activity_help: Error inflating class android.webkit.WebView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
 Caused by: android.view.InflateException: Binary XML file line #24 in io.github.muntashirakon.AppManager.debug:layout/activity_help: Binary XML file line #24 in io.github.muntashirakon.AppManager.debug:layout/activity_help: Error inflating class android.webkit.WebView

Device Info:
App version: 2.5.23-DEBUG
App version code: 380
Android build version: eng.tunaha.20200516.044047
Android release version: 10
Android SDK version: 29
Android build ID: lineage_sirius-userdebug 10 QQ2A.200405.005 eng.tunaha.20200516.044047 test-keys
Device brand: Sony
Device manufacturer: Sony
Device name: sirius
Device model: Xperia Z2
Device product name: lineage_sirius
Device hardware name: qcom
ABIs: [armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): []
System language: tr-TR
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment]
Did you reinstall the debug build? Debug builds always have to be reinstalled otherwise they might behave in an undefined manner.

**Comment by kgursu** [comment]
Oh ok. Didn't know that...

**Comment by kgursu** [comment]
Different results with different devices, shall I both post them here?

**Comment by MuntashirAkon** [comment]
Yeah.

**Comment by kgursu** [comment]
sirius device while /storage/ option selected:
6 apps' APKs still can't be backed up. Those are:
![Screenshot_20210131-215229_1.jpg](https://user-images.githubusercontent.com/35314872/106394776-682d0500-640f-11eb-801b-2a52c58ac319.jpg)

Logcat:
[https://del.dog/grunoderar]()

**Comment by Atrate** [comment]
Seems like an issue of filename sanitization — `:`s and `&`s

**Comment by kgursu** [comment]
Other device:

**Device info**
 - Device: Asus Zenfone 2 Laser 5 (ZE500KL)
 - OS Version: Android 10
 - App Manager Version: 2.5.23 Run#837

Didn't backup any APK.
Only option that can be selected is: /storage/

Logcat:
[https://del.dog/uloxegoobu]()

**Comment by MuntashirAkon** [comment]
> Didn't backup any APK.

It says:

```
java.io.IOException: Root/ADB not enabled.
```

**Comment by MuntashirAkon** [comment]
> Seems like an issue of filename sanitization — `:`s and `&`s

Yeah. FAT32/NTFS limitation, I guess. I'll do the necessary sanitisation.

**Comment by MuntashirAkon** [comment]
> 6 apps' APKs still can't be backed up. Those are:

This was a partition format-specific issue and is fixed in ee2b289c by replacing the invalid characters.

**Comment by kgursu** [comment]
> > Didn't backup any APK.
> 
> It says:
> 
> ```
> java.io.IOException: Root/ADB not enabled.
> ```

This one indeed has root and given permission, I suppose.

**Comment by MuntashirAkon** [comment]
> This one indeed has root and given permission, I suppose.

In that case, open a new issue with additional contexts.

**Comment by kgursu** [comment]
> > This one indeed has root and given permission, I suppose.
> 
> In that case, open a new issue with additional contexts.

Sorry, that was a mistake by me. Everything seems to be fine with the latest debug version.
One last question:
Is it normal to get different apk and apks sizes for the same app, even the device's architectures are similar like they are both 64-bit?
I've got different sizes even within the same device with different version of AM.

**Comment by MuntashirAkon** [comment]
> Is it normal to get different apk and apks sizes for the same app, even the device's architectures are similar like they are both 64-bit?

Sorry. No idea what you're talking about. APKS exported by AM are simple zip files with the system default compression ratio.
