### ISSUE TITLE
Why is the internet permission required in this app?

### ISSUE THREAD

**Issue by seth100** [MuntashirAkon/AppManager#258]
Hi,

My report is just a question to know why the `android.permission.INTERNET` is required in this app.
Thanks

**Comment by GithbUser** [comment]
@seth100 
Read the app manager documentation from [Here](https://muntashirakon.github.io/AppManager/) or app itself 
Why am requires internet promising is mentioned in FAQs miscellaneous section

**Comment by MuntashirAkon** [comment]
See https://github.com/MuntashirAkon/AppManager/blob/master/docs/faq/misc.md#why-does-am-have-the-internet-permission-when-it-doesnt-connect-to-the-internet

**Comment by seth100** [comment]
thank you for the help! Just a futher question: if I block AM with AFWall+ does it prevent AM from working well (I have a rooted device and gave AM root permissions)?

**Comment by MuntashirAkon** [comment]
> if I block AM with AFWall+ does it prevent AM from working well (I have a rooted device and gave AM root permissions)?

No. AM only uses localhost. It doesn't communicate outside your device. So, it should work just fine.

**Comment by seth100** [comment]
thank you very much!
