### ISSUE TITLE
[FEATURE REQUEST] Keep the search active

### ISSUE THREAD

**Issue by fabianski7** [MuntashirAkon/AppManager#26]
Some trackers are well known and are in almost all applications such as Google (Analytics, Firebase). So this is a basic search that I think almost everyone who uses this application does.

My suggestion to make it easier is to keep the search as you navigate between Activities, Services, Receivers and Providers. Currently, it is reset when we change tabs.

There is already a button to clear the search bar (the "X"), so my suggestion won't be something that will hinder the application's usability or something similar.

![Screenshot_20200622-111810__01](https://user-images.githubusercontent.com/47755037/85299287-9d926d00-b494-11ea-8246-4bc3bddd74f7.jpg)

**Comment by MuntashirAkon** [comment]
I'll look into it.
