### ISSUE TITLE
NOT ABLE to export blocking rules 

### ISSUE THREAD

**Issue by ale82to** [MuntashirAkon/AppManager#260]
in am settings i m not able to export any of my rules please see screen record
https://drive.google.com/file/d/14VMEcWjNNW4EZ2LOy-7sY_gD5wmoTb9q/view
any help I need this asap im moving to a new phone.

**Comment by MuntashirAkon** [comment]
You're clicking on the wrong option. If you're using debug builds, use a stable build or pre-release.

**Comment by ale82to** [comment]
nope I m not so stupid it my phone showing false overlay I ve reported to telegram too, stable version worked.
debug version even after uninstalling, rebooting and reinstalling Will NOT work,so pleasellook into the issue I ve had this problem since lots of debug build

**Comment by ale82to** [comment]
that's where I click
https://drive.google.com/file/d/19UhHY2vwTwqkyUrVv9iVy_wAzoVvbih5/view

**Comment by MuntashirAkon** [comment]
I cannot work on something I cannot reproduce. Use only stable versions.
