### ISSUE TITLE
An error occurred when opening the apk or apks

### ISSUE THREAD

**Issue by fucksafetynet** [MuntashirAkon/AppManager#261]
**To Reproduce**
Steps to reproduce the behaviour
 Open the apk with AM pre-release AppDetailsActivity

**Crash logs**
```
2021-02-04 12:46:12.305 E/IPC: Init: Local server
2021-02-04 12:46:12.318 E/IPCUtils: Launching service...
2021-02-04 12:46:12.330 E/IPC: Running service starter script...
2021-02-04 12:46:12.809 E/IPCUtils: service onServiceConnected
2021-02-04 12:46:12.940 E/ApkFile: Invalid mime: application/zip
2021-02-04 12:46:12.962 E/ADA: Could not fetch package info.
io.github.muntashirakon.AppManager.apk.ApkFile$ApkFileException: java.io.FileNotFoundException: /proc/self/fd/68 (Permission denied)
	at io.github.muntashirakon.AppManager.apk.ApkFile.<init>(ApkFile.java:262)
	at io.github.muntashirakon.AppManager.apk.ApkFile.createInstance(ApkFile.java:88)
	at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackage(AppDetailsViewModel.java:128)
	at io.github.muntashirakon.AppManager.details.AppDetailsActivity.lambda$onAuthenticated$5$AppDetailsActivity(AppDetailsActivity.java:102)
	at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsActivity$N44Vyz4IkC88KWOwbq04gs3biVs.run(Unknown Source:14)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.FileNotFoundException: /proc/self/fd/68 (Permission denied)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:265)
	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
	at java.util.zip.ZipFile.<init>(ZipFile.java:201)
	at io.github.muntashirakon.AppManager.apk.ApkFile.<init>(ApkFile.java:260)
	... 5 more
```
**Interceptor**
```
intent://com.mixplorer.fileProvider/CEWvRkIDpqtERwAodrdmLajAO9X7ctrxf0eCl8xfdSSgxD3HMU5TGPch-lM5EO5f/MiXplorer%20Silver_6.51.2_21020112_arm64.apk#Intent;scheme=content;category=android.intent.category.BROWSABLE;type=application/vnd.android.package-archive;launchFlags=0xc3;S.package_name=com.mixplorer;S.real_path=%2Fstorage%2Femulated%2F0%2FDownload%2FMiXplorer%20Silver_6.51.2_21020112_arm64.apk;l.orig_size=9676681;S.real_id=0;i.current_folder_count=20;B.tab_index=true;end
------------
<b><u>Action</u></b> android.intent.action.VIEW
<b><u>Data</u></b> content://com.mixplorer.fileProvider/CEWvRkIDpqtERwAodrdmLajAO9X7ctrxf0eCl8xfdSSgxD3HMU5TGPch-lM5EO5f/MiXplorer%20Silver_6.51.2_21020112_arm64.apk
<b><u>MIME Type</u></b> application/vnd.android.package-archive
<b><u>URI</u></b> intent://com.mixplorer.fileProvider/CEWvRkIDpqtERwAodrdmLajAO9X7ctrxf0eCl8xfdSSgxD3HMU5TGPch-lM5EO5f/MiXplorer%20Silver_6.51.2_21020112_arm64.apk#Intent;scheme=content;category=android.intent.category.BROWSABLE;type=application/vnd.android.package-archive;launchFlags=0xc3;S.package_name=com.mixplorer;S.real_path=%2Fstorage%2Femulated%2F0%2FDownload%2FMiXplorer%20Silver_6.51.2_21020112_arm64.apk;l.orig_size=9676681;S.real_id=0;i.current_folder_count=20;B.tab_index=true;end
<b><u>Categories</u></b>
android.intent.category.BROWSABLE
<b><u>Flags</u></b>
FLAG_GRANT_READ_URI_PERMISSION
FLAG_GRANT_WRITE_URI_PERMISSION
FLAG_GRANT_PERSISTABLE_URI_PERMISSION
FLAG_GRANT_PREFIX_URI_PERMISSION
<b><u>Extras</u></b>
1 Class Name java.lang.String
Key Name package_name
Value com.mixplorer
2 Class Name java.lang.String
Key Name real_path
Value /storage/emulated/0/Download/MiXplorer Silver_6.51.2_21020112_arm64.apk
3 Class Name java.lang.Long
Key Name orig_size
Value 9676681
4 Class Name java.lang.String
Key Name real_id
Value 0
5 Class Name java.lang.Integer
Key Name current_folder_count
Value 20
6 Class Name android.net.Uri$HierarchicalUri
Key Name mix_data_uri
Value content://com.mixplorer.fileProvider/CEWvRkIDpqtERwAodrdmLajAO9X7ctrxf0eCl8xfdSSgxD3HMU5TGPch-lM5EO5f/MiXplorer%20Silver_6.51.2_21020112_arm64.apk
7 Class Name java.lang.Boolean
Key Name tab_index
Value true

------------
<b><u>Matching activities</u></b>
* 扫描器 (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.scanner.ScannerActivity)
* 应用信息 (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.details.AppDetailsActivity)
* Manifest Viewer (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.details.ManifestViewerActivity)
* Install (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity)
* 拦截器 (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.intercept.ActivityInterceptor)
* 浏览 (com.mixplorer - com.mixplorer.activities.ExploreActivity)
```

**Device info**
 - Device: MI 6X(wayne)
 - OS Version: pex 11
 - App Manager Version: 2.5.23
 - Mode: root

**Comment by MuntashirAkon** [comment]
The logs do not look alright to me.
1. If MIME type was indeed set to `application/vnd.android.package-archive`, AM would detect the APK file correctly. The logs suggests that the MIME was invalid (which was `application/zip` rather than `application/vnd.android.package-archive`). 
2. Even if the MIME type was set to `application/zip`, AM would detect the APK type using the file extension, which suggests that the file you were opening was not an APK, rather it was APKS, XAPK or APKM.

**Comment by fucksafetynet** [comment]
> The logs do not look alright to me.
> 1. If MIME type was indeed set to `application/vnd.android.package-archive`, AM would detect the APK file correctly. The logs suggests that the MIME was invalid (which was `application/zip` rather than `application/vnd.android.package-archive`). 
> 2. Even if the MIME type was set to `application/zip`, AM would detect the APK type using the file extension, which suggests that the file you were opening was not an APK, rather it was APKS, XAPK or APKM.

It is indeed an apk
![Screenshot_20210204-151640_Pixel_启动器.png](https://user-images.githubusercontent.com/58792941/106858044-082eab00-66fc-11eb-8bb4-ae313f00204c.png)![Screenshot_20210204-151708_Pixel_启动器.png](https://user-images.githubusercontent.com/58792941/106858062-1086e600-66fc-11eb-96cc-155742198fcd.png)

**Comment by fucksafetynet** [comment]
The apks file whose MIME is application/zip cannot be opened either

intent://com.mixplorer.fileProvider/CEWvRkIDpqtERwAob-_o-rxleKxRAbjkoIeaX6_fuIh3KH8=/AM%20Pre-release_2.5.23-PRE.apks#Intent;scheme=content;category=android.intent.category.BROWSABLE;type=application/zip;launchFlags=0xc3;S.package_name=com.mixplorer;S.real_path=%2Fstorage%2Femulated%2F0%2FAM%20Pre-release_2.5.23-PRE.apks;l.orig_size=5273035;S.real_id=0;i.current_folder_count=14;B.tab_index=true;end
------------
<b><u>Action</u></b> android.intent.action.VIEW
<b><u>Data</u></b> content://com.mixplorer.fileProvider/CEWvRkIDpqtERwAob-_o-rxleKxRAbjkoIeaX6_fuIh3KH8=/AM%20Pre-release_2.5.23-PRE.apks
<b><u>MIME Type</u></b> application/zip
<b><u>URI</u></b> intent://com.mixplorer.fileProvider/CEWvRkIDpqtERwAob-_o-rxleKxRAbjkoIeaX6_fuIh3KH8=/AM%20Pre-release_2.5.23-PRE.apks#Intent;scheme=content;category=android.intent.category.BROWSABLE;type=application/zip;launchFlags=0xc3;S.package_name=com.mixplorer;S.real_path=%2Fstorage%2Femulated%2F0%2FAM%20Pre-release_2.5.23-PRE.apks;l.orig_size=5273035;S.real_id=0;i.current_folder_count=14;B.tab_index=true;end
<b><u>Categories</u></b>
android.intent.category.BROWSABLE
<b><u>Flags</u></b>
FLAG_GRANT_READ_URI_PERMISSION
FLAG_GRANT_WRITE_URI_PERMISSION
FLAG_GRANT_PERSISTABLE_URI_PERMISSION
FLAG_GRANT_PREFIX_URI_PERMISSION
<b><u>Extras</u></b>
1 Class Name java.lang.String
Key Name package_name
Value com.mixplorer
2 Class Name java.lang.String
Key Name real_path
Value /storage/emulated/0/AM Pre-release_2.5.23-PRE.apks
3 Class Name java.lang.Long
Key Name orig_size
Value 5273035
4 Class Name java.lang.String
Key Name real_id
Value 0
5 Class Name java.lang.Integer
Key Name current_folder_count
Value 14
6 Class Name android.net.Uri$HierarchicalUri
Key Name mix_data_uri
Value content://com.mixplorer.fileProvider/CEWvRkIDpqtERwAob-_o-rxleKxRAbjkoIeaX6_fuIh3KH8=/AM%20Pre-release_2.5.23-PRE.apks
7 Class Name java.lang.Boolean
Key Name tab_index
Value true

------------
<b><u>Matching activities</u></b>
* 复制至 … (com.mixplorer - com.mixplorer.activities.CopyActivity)
* 解压到 … (com.mixplorer - com.mixplorer.activities.ExtractActivity)
* 浏览 (com.mixplorer - com.mixplorer.activities.ExploreActivity)
* 应用信息 (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.details.AppDetailsActivity)
* 安装 (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity)
* 拦截器 (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.intercept.ActivityInterceptor)
* 应用信息 (io.github.muntashirakon.AppManager.debug - io.github.muntashirakon.AppManager.details.AppDetailsActivity)
* 安装 (io.github.muntashirakon.AppManager.debug - io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity)
* 拦截器 (io.github.muntashirakon.AppManager.debug - io.github.muntashirakon.AppManager.intercept.ActivityInterceptor)
* ZArchiver Pro (ru.zdevs.zarchiver.pro - ru.zdevs.zarchiver.pro.ZArchiver)



However, this strange phenomenon seems to only appear in mixplorer, and the app manager can open apk/apks normally in other file managers.

**Comment by MuntashirAkon** [comment]
> However, this strange phenomenon seems to only appear in mixplorer

A MiXplorer issue, maybe? There are various reports that I've seen suggested that MiXplorer is having issues with API 30. They've published beta versions targeting API 30. Maybe try them too?

**Comment by MuntashirAkon** [comment]
I've put an explicit check just to see if AM can read the file but it successfully got passed that. So, later on, it was assumed that file would be readable to AM but apparently, it wasn't. It also threw a `FileNotFoundException` instead of `SecurityException` which is weird.

**Comment by fucksafetynet** [comment]
> > However, this strange phenomenon seems to only appear in mixplorer
> 
> A MiXplorer issue, maybe? There are various reports that I've seen suggested that MiXplorer is having issues with API 30. They've published beta versions targeting API 30. Maybe try them too?

This happens in both API29 and API30 mixplorer

**Comment by fucksafetynet** [comment]
> > However, this strange phenomenon seems to only appear in mixplorer
> 
> A MiXplorer issue, maybe? There are various reports that I've seen suggested that MiXplorer is having issues with API 30. They've published beta versions targeting API 30. Maybe try them too?

Other applications (such as libchecker) can open apk files normally（I posted a video in the TG group）

**Comment by MuntashirAkon** [comment]
> Other applications (such as libchecker) can open apk files normally

That's a different story. AM handles files a bit differently due to the amount of analysis it has to do on them.

**Comment by MuntashirAkon** [comment]
It seems more than one person is able to reproduce this issue. But it might be restricted to Android 11 only or MiXplorer only.

**Comment by fucksafetynet** [comment]
mixplorer 6.51.5 seems to solve this problem

**Comment by MuntashirAkon** [comment]
@fucksafetynet  MiXplorer 6.53.2 probably has this issue again. Can you check?
