### ISSUE TITLE
Unable to backup APK files

### ISSUE THREAD

**Issue by PookaMustard** [MuntashirAkon/AppManager#262]
**Describe the bug**
On the main menu screen, when selecting any app (via holding) then clicking the menu button on the bottom-right, and selecting the Backup APK button, an error is thrown with the following details:

AM Debug - Batch Operations
**Backup APK**
Could not back up 1 app. Tap to see details.

This error happens regardless of whether the app in question is a regular APK or an APKS.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select any app from main menu by long holding
2. Click the menu button (three vertical dots) on the left of the bottom bar
3. Click Backup APK

**Expected behavior**
The APK successfully saved to AppManager/apks on the phone's storage.

**Screenshots**
![photo_2021-02-04_15-52-51](https://user-images.githubusercontent.com/19552979/106902140-277c0700-6701-11eb-8c5b-98a347c81932.jpg)

**Crash logs**
[am.log](https://github.com/MuntashirAkon/AppManager/files/5926143/am.log)
(Unfortunately the AM log file does not include anything about this particular error, with the latest lines being written _before_ the error was reproduced)

**Device info**
 - Device: Huawei Mate 10 lite
 - OS Version: Android 8.0 Oreo
 - App Manager Version: v2.5.24-DEBUG#855, bug found in earlier versions as well
 - Mode: root

**Additional context**
In addition to the problem being present on older versions of the debug app, the problem was still present even after an uninstall and reinstall of App Manager.

**Comment by MuntashirAkon** [comment]
Add logcat output, please.

**Comment by PookaMustard** [comment]
There you go
[logcat_02-04-2021_17-17-26.txt](https://github.com/MuntashirAkon/AppManager/files/5926660/logcat_02-04-2021_17-17-26.txt)

**Comment by MuntashirAkon** [comment]
This should be fixed after 4dc6ebe6. Please check.

**Comment by PookaMustard** [comment]
I tried debug #859 and I got the same result. This time, I uninstalled and reinstalled.

**Comment by MuntashirAkon** [comment]
> This time, I uninstalled and reinstalled.

Reinstall is optional, but restart is a must. System likes to cache code for future use, which usually cause the problems.

> I tried debug #859 and I got the same result

Logs are the same?

**Comment by PookaMustard** [comment]
Oh, alright, I restarted the whole system and backing up APK files works again. I'll remember to restart whenever I run into another issue like this.

**Comment by MuntashirAkon** [comment]
Thanks for testing.
