### ISSUE TITLE
Publish on PlayStore

### ISSUE THREAD

**Issue by LiteApplication** [MuntashirAkon/AppManager#266]
Hello, 
I have a Play Store Developer account and i wanted to know if you were interested in publishing this app to the Google Play Store
As the purchase of a Developer account is a one-time purchase, this would be completely free.

I already published an application for [@imknown](https://github.com/imknown) : [LowLevelDetector](https://play.google.com/store/apps/details?id=net.imknown.android.forefrontinfo) sources [here](https://github.com/imknown/AndroidLowLevelDetector)

All I need is a mail (or more) so I can send the invite

Feel free to contact me by [email ](mailto:rossfelderalexis@gmail.com)

**Comment by MuntashirAkon** [comment]
I've looked at the Google Developer Program policies few months ago. They indicated that the app won't be accepted. Examples include:

> Android devices running R (Android 11, API Level 30) or later, will require the MANAGE_EXTERNAL_STORAGE permission in order to manage access in shared storage. All apps that target R and request broad access to shared storage (“All files access”) must successfully pass an appropriate access review prior to publishing. Apps allowed to use this permission must clearly prompt users to enable “All files access” for their app under “Special app access” settings. For more information on the R requirements, please see this help article.

and

> Apps that block or interfere with another app displaying ads.

The statement below is also applicable for future builds (violates ToS of Accessibility permission):
> Apps that access or use a service or API in a manner that violates its terms of service.

This is just my initial review of their policies. There might be others too.

**Comment by MuntashirAkon** [comment]
Also, since AM uses some _sensitive_ permissions, it also needs a privacy policy.

**Comment by LiteApplication** [comment]
Ok, thank you, don't hesitate to contact me if you want to publish an app that complies with Google Play Store policies

**Comment by MuntashirAkon** [comment]
It's probably possible to find a way around the first statement and Google seems to be not caring about the third statement. But the second statement is a problem.

**Comment by LiteApplication** [comment]
You could bypass the second statement by making a lite PlayStore-friendly version of the app but this is a lot of work...

**Comment by MuntashirAkon** [comment]
> You could bypass the second statement by making a lite PlayStore-friendly version of the app

I'm not going to do that. AM isn't bounded by the principles of the evil corps nor by any corporate greed. Reconciliation is what made them more powerful than most governments on the planet. I think it's better to stick to F-Droid until Play Store policies become more acceptable to developers (which I highly doubt).

**Comment by LiteApplication** [comment]
You are right, keep up the good work 😄
