### ISSUE TITLE
Hightlight trackers

### ISSUE THREAD

**Issue by fabianski7** [MuntashirAkon/AppManager#27]
AppManager [highlights some permissions](https://upload.vaa.red/2qUHjw#MeXdwymRnL332T8v4spHFBfVZQ0M4WUI) according to your flag (dangerous, normal, signature, etc.) this is useful and serves as an alert. Due to its usefulness, I think this highlight could also be added in other tabs.

Since trackers are identified by their names (com.facebook.share, com.google.firebase.analytics, ...) then it would be possible to do this. Those that are on the exodus list would be highlighted so that the user can turn it off more easily without having to search for each tracker individually.

what do you think?

**Comment by MuntashirAkon** [comment]
Can you name an app with such trackers (for testing purpose)? I hardly use any closed source app these days.

**Comment by MuntashirAkon** [comment]
Notice: Permissions are coloured red based on the protection level flags. It means that only permissions that the system considers *dangerous* are coloured red which skips a lot of permissions that are actually dangerous (`PACKAGE_USAGE_STATS` for example). I might change this to make a customized list of dangerous permissions. Also, only dangerous permissions can be disabled using `pm` command, the rests cannot be disabled but their corresponding operations (op) can be disabled which are listed in the App Ops tab.

**Comment by fabianski7** [comment]
> Can you name an app with such trackers (for testing purpose)? I hardly use any closed source app these days.

here you go 
https://reports.exodus-privacy.eu.org/en/reports/com.miniclip.eightballpool/latest/
https://play.google.com/store/apps/details?id=com.miniclip.eightballpool

**Comment by fabianski7** [comment]
thank you!
