### ISSUE TITLE
can NOT backup whatsapp or swiftkey 

### ISSUE THREAD

**Issue by ale82to** [MuntashirAkon/AppManager#270]
why backup for many apps like whatsapp or swiftkey is failing, looking at log
BackupOp: Failed to backup data directory at /data/user/0/com.touchtype.swiftkey.beta

**Comment by MuntashirAkon** [comment]
Please provide additional information such as full logs (without filters), steps to reproduce, etc. from the latest debug builds.

**Comment by MuntashirAkon** [comment]
Closed as there are no response for three weeks. Feel free to open it if the bugs are still present.
