### ISSUE TITLE
Multi-threaded optimization

### ISSUE THREAD

**Issue by fucksafetynet** [MuntashirAkon/AppManager#271]
![Screenshot_20210208-032240.png](https://user-images.githubusercontent.com/58792941/107157067-00e9f480-69bd-11eb-8bb4-4b5366da24f4.png)
When backing up the app, only one core seems to be working
Can the load be spread across multiple cores?

**Comment by MuntashirAkon** [comment]
Backup/restore is not currently thread-safe.

**Comment by MuntashirAkon** [comment]
Possible challenges in developing a multi-threaded backup/restore system:
1. Encryption: It is necessary to ask users to insert password
2. Need multiple proxy services running at the same time
3. Determine the no. of threads to be used (without user intervention unlike others did)
4. Determine thread usage
    - Single backup/restore operation in multiple threads
    - Multiple backup/restore operations in multiple threads

**Comment by MuntashirAkon** [comment]
This issue depends on #115.

**Comment by MuntashirAkon** [comment]
Implemented in c077c510. This may introduce new bugs related to concurrency. Single backup/restore operation is not considered for simplicity.
