### ISSUE TITLE
Unable to restore backup. 

### ISSUE THREAD

**Issue by tommynok** [MuntashirAkon/AppManager#272]
Unable to restore backups.
Backups of two applications, split and non-split.
The storage location for backups is an external SD card, and an internal memory of the device.
Algorithm -
- I made a backup, first indicating the storage location for the backup copies of the external SD card, then the internal memory of the phone. Default backup settings.
- I uninstalled apps using AM
- I tried to restore first from an external memory card, then from an internal memory. Both attempts failed. During recovery, a notification appears, almost immediately - "could not restore 1 app. Tap to see details."
- 

Device - Lenovo p1, OS MM.
AppManager_v2.5.24-DEBUG#871.

Log - 
https://del.dog/wicrollibi

**Comment by MuntashirAkon** [comment]
Fixed in 8f018168
