### ISSUE TITLE
Screen lock is bypassable

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#274]
**Describe the bug**
The screen lock can simply be bypassed by tapping through it/pressing the back button

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable screen lock in AM
2. Close AM
3. Open AM
4. Tap on empty space/press the back button
5. Congrats, the screen lock just goes away and AM opens

**Expected behavior**
The screen lock should *not* be bypassable and even if it's somehow dismissed, AM should just close.

**Device info**
 - Device: LG G6 H870
 - OS Version: A11
 - App Manager Version: v2.5.23
 - Mode: root

**Comment by MuntashirAkon** [comment]
Fixed in f58ca27c

**Comment by MuntashirAkon** [comment]
In 9e892544, I've also made sure that blocking AuthenticationActivity doesn't crash the app.
