### ISSUE TITLE
Restore fails if previous restore was abruptly cancelled

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#275]
**Describe the bug**
If the restoration of an app is abruptly cancelled (e.g. via power loss or force-stopping AM), subsequent restores of the app will fail.

This is, as far as I can see due to the following:
1. AM decrypts `source/data.tar.gz..aa.gpg`, creating a file named `source/data.tar.gz.aa`
2. While doing that, AM is stopped.
3. The decrypted/partially decrypted (often corrupted) `.tar.gz.aa` files are left.
4. AM fails to decrypt them again as the files already exist.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start restoring a large app using AM
2. Kill AM in the middle of the process
3. Try to restore the app again
4. AM fails

**Expected behavior**
AM should probably use `.tmp` for unpacking app files for restore

**Crash logs**
Curiously, no logs were produced at all in the logcat.

**Device info**
 - Device: LG G6
 - OS Version: A11
 - App Manager Version: v2.5.23
 - Mode: root

**Comment by MuntashirAkon** [comment]
This is also a security issue. I'm currently trying to figure out a way to support in-memory encryption/decryption instead of the strategy followed by OAB. Since AM only checks the checksum of the backed up APK files, it's possible to inject the decrypted files by a malicious actor by watching the directory changes.

**Comment by MuntashirAkon** [comment]
5eef371e will override existing/broken residues if exist. The possibility of an in-memory encryption/decryption system will be discussed in a separate issue in future.
