### ISSUE TITLE
APKiD and Interesting strings extraction

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#277]
These feature is implemented in MobSF.
https://github.com/MobSF/Mobile-Security-Framework-MobSF

APKiD is the tool for to identify obfuscators and packers in Android apps.
Sourcecode is here
https://github.com/rednaga/APKiD

Interesting strings extraction is also feature implemented in MobSF.
More specifically, extract strings that seems interesting that likes URLs,E-mail address or secrets from decompiled source.

**Comment by MuntashirAkon** [comment]
Duplicate of #133

**Comment by MuntashirAkon** [comment]
VT's Yara is already in my todo list
