### ISSUE TITLE
Wireless debugging on Android 11+

### ISSUE THREAD

**Issue by notgood** [MuntashirAkon/AppManager#281]
Android 11 now supports enabling Wireless debugging straight from Developer options, without USB cable and PC, details in https://developer.android.com/studio/command-line/adb

AppManager could support this mode of operation, much more flexible for unrooted phones, no need to reenable TCP debugging using USB cable after every reboot.

**Comment by MuntashirAkon** [comment]
https://github.com/tananaev/adblib/issues/14

**Comment by MuntashirAkon** [comment]
Partial support for Wireless debugging added via #433. See the PR description for details.

**Comment by MuntashirAkon** [comment]
Implemented in 91d180b9.
