### ISSUE TITLE
Impossible uninstallation

### ISSUE THREAD

**Issue by fabastrid** [MuntashirAkon/AppManager#282]
Hello.
I am on Xiaomi Redmi Note 7  with Lineageos 17.1 Android 10, I'm trying to uninstall in every possible way, nothing to do. Any suggestions?

**Comment by Atrate** [comment]
Uninstall what? What "every possible way"? Please be more specific.

**Comment by MuntashirAkon** [comment]
Duplicate of #159

**Comment by MuntashirAkon** [comment]
It's a ROM bug. Follow the issue above or contact your ROM developer.

**Comment by MuntashirAkon** [comment]
**Update:** The issue has been addressed and fixed by Lineage OS. Here's the issue: https://gitlab.com/LineageOS/issues/android/-/issues/3030
