### ISSUE TITLE
[Feature] Spoof Play Store installation

### ISSUE THREAD

**Issue by unresolvedsymbol** [MuntashirAkon/AppManager#283]
A way to spoof the package that installed the application would be very useful for the few (stupid) apps that use the pm API as a half assed integrity check, ensuring it was installed from `com.android.vending`

**Comment by Atrate** [comment]
May only be possible during installation (TB does it like that) but could be a useful feature

**Comment by MuntashirAkon** [comment]
You can already change the default installer. See docs: https://muntashirakon.github.io/AppManager/guide/settings-page.html#installer-app

**Comment by unresolvedsymbol** [comment]
Is it possible to allow setting this to a package that isn't installed?

**Comment by MuntashirAkon** [comment]
> Is it possible to allow setting this to a package that isn't installed?

I guess so.

**Comment by MuntashirAkon** [comment]
> Is it possible to allow setting this to a package that isn't installed?

Implemented in 6368f87d
