### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by GithbUser** [MuntashirAkon/AppManager#286]
Am pre release crash log
[Am pre release 2.5.23 crash.txt](https://github.com/MuntashirAkon/AppManager/files/5990235/Am.pre.release.2.5.23.crash.txt)

**Comment by MuntashirAkon** [comment]
Use the bug report template if you don't know how to report bugs.

**Comment by GithbUser** [comment]
Sorry but currently i dont know how to reproduce the bug 
I will give info when i find out
Thanks

**Comment by MuntashirAkon** [comment]
Take your time.

**Comment by GithbUser** [comment]
Currently i am not using Am pre release 
I am using Am debug
And i know i can install them both at same time 
But i dont know what caused the bug mentioned above so i am closing this issue

**Comment by MuntashirAkon** [comment]
Alright. Feel free to open it again in case you find a way to reproduce this.
