### ISSUE TITLE
Providers/Apps ops/ Uses permissions crash

### ISSUE THREAD

**Issue by HoboVidens** [MuntashirAkon/AppManager#287]
I have recently clean installed latest arrowos 11.0 on my curtana device. The app manager app runs ok, but crashes when I go to the Providers/ App ops or Uses permissions tablets. I tried clean installation twice, I have no password and I turned on any permission I could find about the app. Any fixes?

**Comment by MuntashirAkon** [comment]
You've failed to mention AM version. Is it v2.5.20?

**Comment by HoboVidens** [comment]
Sorry. It is v2.5.17. Latest on f-droid.

**Comment by MuntashirAkon** [comment]
Duplicate of #194
