### ISSUE TITLE
Temporary Tracker was merged into ETIP.Now safe to remove.

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#289]
Temporary tracker signatures([d218d6d](https://github.com/MuntashirAkon/AppManager/blob/d218d6d53176e12d57713d3efb22aa3ebfc538c6/scripts/tmp_trackers.json)) was merged into ETIP with my account.

**Comment by MuntashirAkon** [comment]
Would they all be approved though? For instance, people consider ACRA to be safe because it is open source (whatever it means I don't understand).

**Comment by gnuhead-chieb** [comment]
Maybe yes.
exodus official website says " 'open source' trackers exist" and treated crashreporter as tracker.
https://reports.exodus-privacy.eu.org/en/info/trackers/

**Comment by MuntashirAkon** [comment]
ACRA isn't just a regular crash reporter (I also wonder why not people create their own crash reporter, it's very easy and [could be done in less than a 100 lines](https://github.com/MuntashirAkon/AppManager/blob/master/app/src/main/java/io/github/muntashirakon/AppManager/misc/AMExceptionHandler.java), it can be utilised for the purposes of logging and analytics, and it send them without user intervention which is the prime reason for it to be included here.

**Comment by gnuhead-chieb** [comment]
true

**Comment by MuntashirAkon** [comment]
Anyway, did you include all the trackers listed there? Trackers such as `com.google.unity.ads.` is missing from the list. It's a hugely popular library used by many game apps.

**Comment by gnuhead-chieb** [comment]
`com.google.unity.ads.` is my mistake.I thought it was added before to skipped it.
I added now.

**Comment by MuntashirAkon** [comment]
Found the following signatures missing:
```
{
  "trackers": {
    "2": {
      "id": 2,
      "name": "µ?ACRA",
      "description": "",
      "creation_date": "",
      "code_signature": "ch.acra.",
      "network_signature": "",
      "website": "https://github.com/ACRA/acra"
    },
    "34": {
      "id": 34,
      "name": "Pangle SDK",
      "description": "",
      "creation_date": "",
      "code_signature": "com.bytedance.sdk.openadsdk",
      "network_signature": "",
      "website": "https://www.pangleglobal.com"
    }
  }
}
```

There would be one more signature `com.google.android.gms.ad` which you don't need to add in the ETIP. It's added for AM's own use.

**Comment by MuntashirAkon** [comment]
Only **Pangle SDK** is missing now.

**Comment by o700** [comment]
added

**Comment by MuntashirAkon** [comment]
If you have time to do some investigation, try the following:
**Extracted from LuckyPatcher**
```
com.adknowledge.
com.oneriot.
.qwapi.adclient.android.view.
MediaPlayerWrapper
.nbpcorp.
.superawesome.
```
**Extracted from some other app**
```
Adam
net.daum.adam.publisher

Dawin
com.incross.dawin

AppLift
com.hf.appliftsdk

AppFlood
com.appflood

Mojise
kr.com.mojise.sdk
```

**Note:** Both apps contain many outdated signatures, so the signatures above could be outdated too.

**Comment by gnuhead-chieb** [comment]
Updated ETIP trackers.
・Facebook Analytics （Updated)
・VK SDK （Updated）
・Microsoft App Center /Updated
・Tencent /Updated
・Inmobi(Updated)
・Malverting/Adfrauds /Updated
・IGAWorks
・Baidu Crash Reporter
・Vivo Push SDK
・appPlant
・Pincrux
・CaramelAds
・ONEstore(mNewsK SDK)
・Incross Dawin
・Papaya /Updated
・SuperAwesome
・Unknown Trackers


In addition,These signatures wasn't added:

AD@M(`net.daum.adam.publisher`)
Service ended and changed their name to Kakao Adfit(com.kakao.adfit.).
https://reddreams.tistory.com/1283

Applift(`com.hf.appliftsdk`)
Already exits in ETIP.

OneRiot(`com.oneriot.`)
Service Ended

Adknowledge(`.com.adknowledge.`)
Service Ended

**Comment by gnuhead-chieb** [comment]
Many trackers added

**Comment by MuntashirAkon** [comment]
The following trackers were removed from ETIP that (I think) you've added there:

```
.InterstitialAdActivity
.InAppBannerWebActivity
com.microsoft.appcenter.distribute.
com.yoc.sdk
```

**Comment by gnuhead-chieb** [comment]
Trackers updated

**Comment by MuntashirAkon** [comment]
[B4A](https://github.com/AnywhereSoftware/B4A) has been removed from ETIP. Can you check why it was added in first place (if you've got time)?

**Comment by MuntashirAkon** [comment]
@gnuhead-chieb Can you investigate on this: `com.google.cloud.audit`

**Comment by gnuhead-chieb** [comment]
> @gnuhead-chieb Can you investigate on this: `com.google.cloud.audit`

added

**Comment by MuntashirAkon** [comment]
@gnuhead-chieb: I've found the following `path`s not included in the ETIP repo (taken from @IzzySoft's repo):
```
{"id":"/com/google/android/gms/admob","path":"/com/google/android/gms/admob","name":"Google AdMob","type":"Advertisement","perms":"","url":"https://www.google.com/admob/"}
{"id":"/com/google/firebase/firebase_ads","path":"/com/google/firebase/firebase_ads","name":"Firebase Ads","type":"Advertisement","perms":"","url":"https://firebase.google.com/"}
{"id":"/com/rjfun/cordova/ad","path":"/com/rjfun/cordova/admob","name":"AdMob Plugin Pro","type":"Advertisement","perms":"","url":"https://github.com/floatinghotpot/cordova-admob-pro"}
{"id":"/com/zenjoy/ads","path":"/com/zenjoy/ads","name":"Zenjoy","type":"Advertisement","perms":"","url":"http://www.zenjoy.net/"}
{"id":"/com/google/firebase/analytics","path":"/com/google/firebase/firebase_analytics","name":"Firebase Analytics","type":"Mobile Analytics","perms":"","url":"https://firebase.google.com/docs/analytics/"}
```

@IzzySoft: Could you please inform me or @gnuhead-chieb in case you add any **Mobile Analytics** or **Advertisement** in the `libsmali.txt` file (I know that you don't get enough time to contribute to ETIP)? We're working very hard to make sure that ETIP is up to date. We've added more than a hundred signatures in the past few months (and your help would be much appreciated).

**Comment by gnuhead-chieb** [comment]
Added
https://etip.exodus-privacy.eu.org/trackers/e9c80f4c-cf20-4a7b-8aa0-4db002597a21/
https://etip.exodus-privacy.eu.org/trackers/f7df535a-7954-48fd-87db-5db6e29f0f09/
https://etip.exodus-privacy.eu.org/trackers/862b2b1f-47d3-4dc0-9527-d50e73ce2536/
https://etip.exodus-privacy.eu.org/trackers/901597f7-ea1c-467b-bb9f-a1a7e9fc6741/

**Comment by IzzySoft** [comment]
@MuntashirAkon could you maybe subscribe to the repo? Updates are pushed about once a month. I wouldn't remember whom I had to inform (there are some more interested parties). I didn't dig into that, but if subscriptions can be limited to commits, that shouldn't result in many notifications. And even if not, not much traffic otherwise either (rarely issues, no MRs until now); so it shouldn't be much more than one notification per week on average.

@gnuhead-chieb I just wanted to rejoice that Firebase was picked up by ETIP – I was too early with that (not complaining, as it's not "tracking" in the primary sense – but it's always Google getting a ping which is why I consider it a "secondary tracker": Google can easily combine that with their other collectors for profiling)…

**Comment by MuntashirAkon** [comment]
@gnuhead-chieb: `com.google.firebase.firebase_analytics` seems to be missing.

> @MuntashirAkon could you maybe subscribe to the repo?

Alright. _I've to update libraries from there anyway._

**Comment by gnuhead-chieb** [comment]
```
{"id":"/io/intercom/android/sdk","path":"/io/intercom/android/sdk","name":"Intercom","type":"Utility","perms":"","url":"https://github.com/intercom/intercom-android"}
{"id":"/gun0912/ted/tedbottompicker","path":"/gun0912/ted/tedbottompicker","name":"TedBottomPicker","type":"UI Component","perms":"","url":"https://github.com/ParkSangGwon/TedBottomPicker"}
{"id":"/gun0912/ted/tedbottompicker","path":"/com/gun0912/ted/tedbottompicker","name":"TedBottomPicker","type":"UI Component","perms":"","url":"https://github.com/ParkSangGwon/TedBottomPicker"}
{"id":"/gun0912/ted/tedkeyboardobserver","path":"/gun0912/ted/tedkeyboardobserver","name":"TedKeyboardObserver","type":"Utility","perms":"","url":"https://github.com/ParkSangGwon/TedKeyboardObserver"}
{"id":"/gun0912/ted/tedclustering-naver","path":"/gun0912/ted/tedclustering-naver","name":"TedNaverMapClustering","type":"Map","perms":"","url":"https://github.com/ParkSangGwon/TedNaverMapClustering"}
{"id":"/gun0912/ted/tedonactivityresult-rx1","path":"/gun0912/ted/tedonactivityresult-rx1","name":"TedRxOnActivityResult","type":"Utility","perms":"","url":"https://github.com/ParkSangGwon/TedRxOnActivityResult"}
{"id":"/gun0912/ted/tedbottompicker","path":"/com/gun0912/ted/tedbottompicker","name":"TedPicker","type":"UI Component","perms":"","url":"https://github.com/ParkSangGwon/TedBottomPicker"}
{"id":"/gun0912/ted/tedimagepicker","path":"/gun0912/ted/tedimagepicker","name":"TedImagePicker","type":"UI Component","perms":"","url":"https://github.com/ParkSangGwon/TedImagePicker"}
{"id":"/com/braintreepayments/api","path":"/com/braintreepayments/api","name":"Braintree","type":"Payment","perms":"","url":"https://developers.braintreepayments.com/"}
{"id":"/com/comm100/livechat","path":"/com/comm100/livechat","name":"Comm100","type":"Utility","perms":"","url":"https://www.comm100.com/platform/livechat/"}
{"id":"/com/sailthru/mobile/sdk","path":"/com/sailthru/mobile/sdk","name":"Sailthru","type":"Utility","perms":"","url":"https://docs.mobile.sailthru.com/docs/sdk-integration"}
{"id":"/com/huawei/appmarket/component","path":"/com/huawei/appmarket/component","name":"Huawei Appmarket","type":"App Market","perms":"","url":"https://developer.huawei.com/consumer/en/"}
{"id":"/com/huawei/hms/hwid/internal","path":"/com/huawei/hms/hwid/internal","name":"HMS Signin","type":"Utility","perms":"","url":"https://developer.huawei.com/consumer/en/"}
{"id":"/com/huawei/updatesdk","path":"/com/huawei/updatesdk","name":"Huawei Update SDK","type":"Utility","perms":"","url":"https://developer.huawei.com/consumer/en/"}
{"id":"/com/unity/purchasing","path":"/com/unity/purchasing","name":"Unity IAP","type":"Payment","perms":"","url":"https://docs.unity3d.com/ja/2019.4/Manual/com.unity.purchasing.html"}
{"id":"/jp/line/android/sdk","path":"/jp/line/android/sdk.","name":"LINE SDK","type":"Utility","perms":"","url":"https://developers.line.biz/ja/docs/android-sdk/"}
{"id":"/jp/line/android/sdk","path":"/com/linecorp/linesdk","name":"LINE SDK","type":"Utility","perms":"","url":"https://developers.line.biz/ja/docs/android-sdk/"}
{"id":"/com/adyen/checkout","path":"/com/adyen/checkout","name":"Adyen","type":"Payment","perms":"","url":"https://docs.adyen.com/online-payments/classic-integrations/checkout-sdks/android-sdk"}
{"id":"/com/facebook/unity","path":"/com/facebook/unity","name":"Facebook Unity SDK","type":"Utility","perms":"","url":"https://developers.facebook.com/docs/unity/"}
{"id":"/com/google/games","path":"/com/google/games","name":"Play Games Services","type":"Utility","perms":"","url":"https://developers.google.com/games/services/android/quickstart"}
{"id":"/com/google/games","path":"/com/google/android/gms/games","name":"Play Games Services","type":"Utility","perms":"","url":"https://developers.google.com/games/services/android/quickstart"}
{"id":"/kr/co/smartstudy","path":"/kr/co/smartstudy","name":"SmartStudy","type":"Utility","perms":"","url":"https://www.smartstudy.co.kr/en/"}
{"id":"/com/inca/security","path":"/com/inca/security","name":"ICNA nProtect GameGuard","type":"Development Aid","perms":"","url":"https://inca.co.kr/en/index.html"}
{"id":"/com/onevcat/uniwebview","path":"/com/onevcat/uniwebview","name":"UniWebView","type":"Utility","perms":"","url":"https://docs.uniwebview.com/"}
{"id":"/io/invertase/firebase","path":"/io/invertase/firebase","name":"Invertase RNFirebase","type":"Utility","perms":"","url":"https://github.com/invertase/react-native-firebase"}
{"id":"/com/imagepicker","path":"/com/imagepicker","name":"ImagePicker","type":"UI Component","perms":"","url":"https://github.com/jeasonlzy/ImagePicker"}
{"id":"/net/sanukin","path":"/net/sanukin","name":"sanukin","type":"Utility","perms":"","url":"https://github.com/sanukin39"}
{"id":"/org/jitsi/meet/sdk","path":"/org/jitsi/meet/sdk","name":"Jitsi Meet SDK","type":"Utility","perms":"","url":"https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk"}
{"id":"/org/matrix/android/sdk","path":"/org/matrix/android/sdk","name":"Matrix SDK","type":"Utility","perms":"","url":"https://matrix.org/docs/projects/sdk/matrix-org-android-sdk/"}
{"id":"/splitties","path":"/splitties","name":"Splitties","type":"Development Framework","perms":"","url":"https://github.com/LouisCAD/Splitties"}
{"id":"/com/oneclickaway/opensource/placeautocomplete","path":"/com/oneclickaway/opensource/placeautocomplete","name":"PlaceAutocomplete","type":"Utility","perms":"","url":"https://github.com/Drabu/PlaceAutocomplete"}
{"id":"/com/oneclickaway/opensource/formvalidationsexample","path":"/com/oneclickaway/opensource/formvalidationsexample","name":"FormValidator","type":"Utility","perms":"","url":"https://github.com/Drabu/FormValidator"}
{"id":"/com/github/Drabu/SSNInputView","path":"/com/github/Drabu/SSNInputView","name":"SSNInputView","type":"Utility","perms":"","url":"https://github.com/Drabu/SSNInputView"}
{"id":"/com/just/agentweb","path":"/com/just/agentweb","name":"AgentWeb","type":"Utility","perms":"","url":"https://github.com/Justson/AgentWeb"}
{"id":"/com/flyingpigeon","path":"/com/flyingpigeon","name":"Flying-Pigeon","type":"Utility","perms":"","url":"https://github.com/Justson/flying-pigeon"}
{"id":"/com/flyingpigeon","path":"/com/github/Justson/flying-pigeon","name":"Flying-Pigeon","type":"Utility","perms":"","url":"https://github.com/Justson/flying-pigeon"}
{"id":"/com/queue/library","path":"/com/queue/library","name":"Dispatch queue","type":"Utility","perms":"","url":"https://github.com/Justson/dispatch-queue"}
{"id":"/com/queue/library","path":"/com/github/Justson/dispatch-queue","name":"Dispatch queue","type":"Utility","perms":"","url":"https://github.com/Justson/dispatch-queue"}
{"id":"/com/download/library","path":"/com/download/library","name":"Downloader","type":"Utility","perms":"","url":"https://github.com/Justson/Downloader"}
{"id":"/com/github/tamsiree/RxTool","path":"/com/github/tamsiree/RxTool","name":"RxTool","type":"Development Aid","perms":"","url":"https://github.com/Tamsiree/RxTool"}
{"id":"/com/github/tamsiree/RxTool","path":"/com/github/vondear/RxTools","name":"RxTool","type":"Development Aid","perms":"","url":"https://github.com/Tamsiree/RxTool"}
{"id":"/me/yokeyword/fragmentation","path":"/me/yokeyword/fragmentation","name":"Fragmentation","type":"Utility","perms":"","url":"https://github.com/YoKeyword/Fragmentation/"}
{"id":"/me/yokeyword/fragmentation","path":"/me/yokeyword/fragmentation-swipeback","name":"Fragmentation","type":"Utility","perms":"","url":"https://github.com/YoKeyword/Fragmentation/"}
{"id":"/me/yokeyword/fragmentation","path":"/me/yokeyword/eventbus-activity-scope","name":"Fragmentation","type":"Utility","perms":"","url":"https://github.com/YoKeyword/Fragmentation/"}
{"id":"/com/liulishuo/okdownload","path":"/com/liulishuo/okdownload","name":"OkDownload","type":"Utility","perms":"","url":"https://github.com/lingochamp/okdownload"}
{"id":"/org/cocos2dx","path":"/org/cocos2dx","name":"Cocos2d-x","type":"Game Engine","perms":"","url":"https://www.cocos2d-x.org/"}
{"id":"/com/google/cardboard/sdk","path":"/com/google/cardboard/sdk.","name":"Cardboard SDK","type":"UI Component","perms":"","url":"https://developers.google.com/cardboard"}
{"id":"/co/sensara/sensy","path":"/co/sensara/sensy","name":"Sensara","type":"Utility","perms":"","url":"https://www.sensara.tv/"}
{"id":"/com/dmm/asdk/api","path":"/com/dmm/asdk/api","name":"DMM GAMES","type":"Utility","perms":"","url":"https://dmmgames.co.jp/"}
{"id":"/net/agasper/unitynotification","path":"/net/agasper/unitynotification","name":"Unity3D Android notification plugin","type":"Utility","perms":"","url":"https://github.com/Agasper/unity-android-notifications"}
{"id":"/com/unity/androidnotifications","path":"/com/unity/androidnotifications","name":"Unity Mobile Notifications","type":"Utility","perms":"","url":"https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.0"}
{"id":"/com/microsoft/appcenter/push","path":"/com/microsoft/appcenter/push","name":"App Center Push","type":"Utility","perms":"","url":"https://docs.microsoft.com/en-us/appcenter/push/"}
{"id":"/anywheresoftware/b4a","path":"/anywheresoftware/b4a","name":"B4A","type":"Development Framework","perms":"","url":"https://www.b4x.com/b4a.html"}
{"id":"/com/sendbird/android","path":"/com/sendbird/android","name":"Sendbird","type":"Utility","perms":"","url":"https://sendbird.com/"}
{"id":"/es/voghdev/pdfviewpager","path":"/es/voghdev/pdfviewpager","name":"PdfViewPager","type":"Utility","perms":"","url":"https://github.com/voghDev/PdfViewPager"}
{"id":"/io/intercom/android/sdk","path":"/us/shandian/giga","name":"GigaGet","type":"Utility","perms":"","url":"https://github.com/PaperAirplane-Dev-Team/GigaGet"}
{"id":"/klb/android/GameEngine","path":"/klb/android/GameEngine","name":"Playground OSS","type":"Game Engine","perms":"","url":"https://github.com/KLab/PlaygroundOSS"}
{"id":"/com/wireguard/android/backend","path":"/com/wireguard/android/backend","name":"Wireguard Embedding","type":"Utility","perms":"","url":"https://github.com/WireGuard/wireguard-android"}
{"id":"/com/markodevcic/peko","path":"/com/markodevcic/peko","name":"PEKO","type":"Utility","perms":"","url":"https://github.com/deva666/Peko"}
{"id":"/com/markodevcic/kvalidation","path":"/com/markodevcic/kvalidation","name":"KValidation","type":"Utility","perms":"","url":"https://github.com/deva666/KValidation"}
{"id":"/com/allenliu/versionchecklib","path":"/com/allenliu/versionchecklib","name":"CheckVersionLib","type":"Utility","perms":"","url":"https://github.com/AlexLiuSheng/CheckVersionLib"}
{"id":"/com/allenliu/floatview","path":"/com/allenliu/floatview","name":"FloatView","type":"UI Component","perms":"","url":"https://github.com/AlexLiuSheng/FloatView"}
{"id":"/com/allenliu/badgeview","path":"/com/allenliu/badgeview","name":"BadgeView","type":"UI Component","perms":"","url":"https://github.com/AlexLiuSheng/BadgeView"}
{"id":"/com/github/AlexLiuSheng/AnimSideBar","path":"/com/github/AlexLiuSheng/AnimSideBar","name":"AnimSideBar","type":"UI Component","perms":"","url":"https://github.com/AlexLiuSheng/AnimSideBar"}
{"id":"/com/allenliu/CircleMenuView","path":"/com/allenliu/CircleMenuView","name":"CircleMenuView","type":"UI Component","perms":"","url":"https://github.com/AlexLiuSheng/CircleMenuView"}
{"id":"/com/github/AlexLiuSheng/EasyBluetoothFrame","path":"/com/github/AlexLiuSheng/EasyBluetoothFrame","name":"EasyBluetoothFrame","type":"Utility","perms":"","url":"https://github.com/AlexLiuSheng/EasyBluetoothFrame"}
{"id":"/com/github/whataa/pandora","path":"/com/github/whataa/pandora","name":"Pandora","type":"Utility","perms":"","url":"https://github.com/whataa/pandora"}
{"id":"/com/github/whataa/noDrawable","path":"/com/github/whataa/noDrawable","name":"NoDrawable","type":"Utility","perms":"","url":"https://github.com/whataa/noDrawable"}
**{"id":"/com/lxj/xpermission","path":"/com/lxj/xpermission","name":"XPermission","type":"Utility","perms":"","url":"https://github.com/li-xiaojun/XPermission"}
{"id":"/com/lxj/xpopup","path":"/com/lxj/xpopup","name":"XPopup","type":"UI Component","perms":"","url":"https://github.com/li-xiaojun/XPopup"}
{"id":"/com/lxj/xpopup","path":"/com/lxj/xpopup-ext","name":"XPopup","type":"UI Component","perms":"","url":"https://github.com/li-xiaojun/XPopup"}
{"id":"/com/lxj/androidktx","path":"/com/lxj/androidktx","name":"AndroidKTX","type":"Utility","perms":"","url":"https://github.com/li-xiaojun/AndroidKTX"}
{"id":"/com/lxj/statelayout","path":"/com/lxj/statelayout","name":"StateLayout","type":"UI Component","perms":"","url":"https://github.com/li-xiaojun/StateLayout"}
{"id":"/com/github/li-xiaojun/OkhttpDownloader","path":"/com/github/li-xiaojun/OkhttpDownloader","name":"OkhttpDownloader","type":"Utility","perms":"","url":"https://github.com/li-xiaojun/OkhttpDownloader"}
{"id":"/com/criware","path":"/com/criware","name":"Criware","type":"Game Engine","perms":"","url":"https://www.criware.com/en/"}
```

@IzzySoft

**Comment by IzzySoft** [comment]
That looks line it could be from my `libsmali.txt` but obviously isn't – so I assume you suggest I should add those lines. What's in there is a library – not necessarily a tracker or having any AntiFeature. Those details are in `libinfo.txt` – and each line here should have a corresponding line there. Would you have those corresponding lines as well – or could at least specify the category? Are those all trackers? I see e.g. "Google Cardboard SDK". Is that NonFreeDep **and** Tracking – or just one of the two – or neither?

Oh, and before we hijack this issue here, shouldn't this rather go to [my repo](https://gitlab.com/IzzyOnDroid/repo)?

**Comment by MuntashirAkon** [comment]
Yeah, it should be off-topic here.

**Comment by MuntashirAkon** [comment]
@gnuhead-chieb: Can you check on Agora SDK (`io.agora`), there might be some analytics part in it.

**Comment by gnuhead-chieb** [comment]
> Can you check on Agora SDK (`io.agora`), there might be some analytics part in it.

Agora is already exits in trackers database
https://github.com/MuntashirAkon/AppManager/blob/master/app/src/main/res/values/trackers.xml#L573

**Comment by MuntashirAkon** [comment]
> Agora is already exits in trackers database

I see. It's only in the ETIP. Somebody reported the signature via email.

**Comment by gnuhead-chieb** [comment]
3 more trackers added in ETIP (extracted from com.root.clean.boost.explorer.filemanager and com.firstscreen.weather)

**Comment by MuntashirAkon** [comment]
> 3 more trackers added in ETIP (extracted from com.root.clean.boost.explorer.filemanager and com.firstscreen.weather)

Done.

**Comment by IzzySoft** [comment]
@gnuhead-chieb Guess you consider the "add to my library definitions" part obsolete now, as I did not receive any request at my repo (with the `libinfo.txt` part added)? Might be useful as meanwhile my library scanner is also used by [F-Droid's IssueBot](https://gitlab.com/fdroid/issuebot) to run on the APKs if build succeeds (and we cannot have Exodus check that APK for obvious reasons).

**Comment by gnuhead-chieb** [comment]
@IzzySoft 
I created issue on your repo.

https://gitlab.com/IzzyOnDroid/repo/-/issues/164

**Comment by IzzySoft** [comment]
Thanks a lot, just found it! Will see to include it ASAP with its own commit to properly give credits :smiley:

**Comment by gnuhead-chieb** [comment]
Some trackers added in ETIP

**Comment by gnuhead-chieb** [comment]
I investigated dov-e SDK and I found it is used in [BBVA Wallet](https://play.google.com/store/apps/details?id=com.bbva.bbvawalletpe).
Then i looked classes of this app to I noticed it should change signature to "`com.dv.DVSDK`"

However, this tracker is approved tracker,so if I fix signature in ETIP,It need re-approved for apply changes.(I only have permission to edit ETIP and I can't edit Exodus main list)
So the fastest way is create issue in Exodus github repo and ask who has permission of edit main list of exodus

**Comment by MuntashirAkon** [comment]
Okay. I will create an issue in the GitHub repo.

**Comment by MuntashirAkon** [comment]
https://github.com/Exodus-Privacy/exodus/issues/463

**Comment by IzzySoft** [comment]
@MuntashirAkon any details on that signature? What is it etc? I didn't yet encounter it, hence it's not there. As you obviously encountered it, mind to name the remaining pieces? :smiley:

**Comment by MuntashirAkon** [comment]
@gnuhead-chieb: Can you check `com.unity3d.services` on Exodus? As I was going through emails regarding missing signatures, I bumped into this signature and it seemed to me that the signature is overly generalised. It should be something like `com.unity3d.services.ads.`.

**Comment by MuntashirAkon** [comment]
> It was removed Kakao AD SDK I added before by someone on ETIP. I reverted it because it seems mistakes https://etip.exodus-privacy.eu.org/trackers/3717f449-6d14-4620-8d4d-cf896e6c65a4/

Will be updated in the next iteration.

**Comment by IzzySoft** [comment]
Just to update: the [culprit with E-Rezept was MLKit](https://www.kuketz-blog.de/reaktion-der-gematik-auf-e-rezept-app-pruefung/). The devs have no idea why it does that, they didn't initiate the tracking. So MLKit should clearly be considered a tracker – as it reports to FA not only without informing the user, but also without making the dev aware. Though it of course still could be something the devs missed. But still, they didn't intentionally enable it – so it's at least not "privacy by default".

Quoting the relevant part:

> Diese Kommunikation findet durch das Google ML Kit statt. Diese Kommunikation ist ohne Anlass; wir nutzen das ML Kit für das Lesen des Data Matrix Codes. Warum das ML Kit überhaupt mit Firebase Analytics kommuniziert, ist uns unbekannt. Auf jeden Fall ist es nicht durch uns initiiert.

Translation:

> This communication takes place through the Google ML Kit. This communication is without cause; we use the ML Kit to read the Data Matrix code. Why the ML Kit is communicating with Firebase Analytics at all is unknown to us. In any case, it is not initiated by us.

**Comment by MuntashirAkon** [comment]
> About the specific issue with `com.google.android.gms.ads.`, I don't see any issue replacing the following list (current signatures for tracker Google AdLob) by this, although I don't know whether we'll catch more apps with it:

That's not the issue, I think. There are many overly generalised signature on ETIP, so why an exception for this? Technically speaking, for App Manager as it scans user apps for potential trackers, matching one signature instead of five signatures means a notable performance gain. And I think I've already discussed this issue before on GitHub without a satisfactory answer.



> Happy to discuss any changes on εxodus trackers (and the ETIP tracker database) but to be fair I'm getting a bit lost in this thread 😅

You should only read the last few bits because, for some reason, we decided to continue our discussions in a closed thread.

> Unfortunately ETIP's comments system is still too limited for that purpose 😞

Yeah. Comments section should be improved (it should, at least, go outside the tracker info table).

**Comment by IzzySoft** [comment]
> send everything without user interaction unless the developer decides to do something about it

Ouch! So whoever told me the exact opposite was misguided, and as a result so was I… That's what's called progress: now we have guided missiles and misguided men. We're proud of machines which think while being suspicious of people who attempt to…

**Comment by MuntashirAkon** [comment]
[This](https://developers.google.com/ml-kit/terms) is the one of the most absurd things I've read on the Internet:

> When you use ML Kit APIs, processing of the input data (e.g. images, video, text) fully happens on-device, and **ML Kit does not send that data to Google servers.** As a result, you can use our APIs for processing data that should not leave the device.

Then, in the next line:

> The ML Kit APIs may contact Google servers from time to time in order to receive things like bug fixes, updated models and hardware accelerator compatibility information. The ML Kit APIs also send metrics about the performance and utilization of the APIs in your app to Google. Google uses this metrics data to measure performance, debug, maintain and improve the APIs, and detect misuse or abuse, as further described in our Privacy Policy.

You find a full list of _things_ collected by Google (basically everything that is possible) in the link above.

It is also stated that:

> **You are responsible for informing users of your app about Google’s processing of ML Kit metrics data as required by applicable law.**

So, if E-Rezept devs didn't specify data collections by ML Kit, it's their fault, not Google's, and it also easily makes it a candidate for Exodus list (@gnuhead-chieb: please add it in the ETIP if possible).

**Comment by gnuhead-chieb** [comment]
Hey @pnu-s,your [Oct. 9, 2021 revision](https://etip.exodus-privacy.eu.org/admin/trackers/tracker/3717f449-6d14-4620-8d4d-cf896e6c65a4/history/) is mistake.
This duplicates `com.kakao.adfit`. I reverted it on ETIP but it doesn't applied on main list of exodus because you changed signature and approved it.
Revoke approving or Reapprove correct signature to apply it!

**Comment by pnu-s** [comment]
> Hey @pnu-s,your Oct. 9, 2021 revision is mistake.
> This duplicates com.kakao.adfit. I reverted it on ETIP but it doesn't applied on main list of exodus because you changed signature and approved it.
> Revoke approving or Reapprove correct signature to apply it!

Thanks for raising this @gnuhead-chieb 
The issue is that we cannot ship it as is because indeed it collides with the signature of Adfit (see https://etip.exodus-privacy.eu.org/trackers/3717f449-6d14-4620-8d4d-cf896e6c65a4/)

Do you have a more precise signature so that it can be differentiated from Adfit?

**Comment by gnuhead-chieb** [comment]
This doesn't collides with Adfit.
There is `.(dot)` after `com.kakao.ad`

Cause of "Collision detected" showing is you changed its signature to "com.kakao.adfit".
So There is 2 "com.kakao.adfit" signatures on Exodus.(You can see this by just open exodus json file and do Ctrl+F to search this signature)
Collision will be fixed when you reaprrove or revoke this approving.

**Comment by pnu-s** [comment]
Please trust me to know how the code of ETIP works, I wrote a big part of it :wink: 

This is a regular expression, so `com.kakao.ad.` **DOES** collide with `com.kakao.adfit`.
Note that the collision displayed on ETIP doesn't have anything to do with the signatures in exodus (which was removed by the way).
