### ISSUE TITLE
Possible failure, does not load app ops in some apps

### ISSUE THREAD

**Issue by gallegonovato** [MuntashirAkon/AppManager#295]
Good afternoon:

First of all, thank you for your great application.

To say that in my terminal I have LineageOS 17.1 with Mahisk in its latest version. 

I also have your application in the latest version on fdroid.

I gave you all the permissions you asked for. Super user, storage 

But they do not load the app ops in applications such as:

Media Storage 
Android System Webview
Files
Autostarts
Bluetooth 
Bookmark Provider
Calendar 
Contacts
Fdroid 
Fennec f-droid
Sd maid

Among others

Since I try to remove the boot options with the system for example from sd maid, fdroid and fennec or Iceraven. And I do not find the way

Best regards and thank you for your help and time.

**Comment by MuntashirAkon** [comment]
AppManager v2.5.17 is no longer supported. Use v2.5.20 or later.

**Comment by gallegonovato** [comment]
Good afternoon @MuntashirAkon 

Thank you very much for your help and time 

But in fdroid is the latest version there https://f-droid.org/es/packages/io.github.muntashirakon.AppManager/ . And when I download it from fdroid I think it will give error if I update from github. If I am not wrong.

I don't know if you are going to upload the new version to fdroid?

A hug

**Comment by MuntashirAkon** [comment]
> when I download it from fdroid I think it will give error if I update from github. If I am not wrong.

Yes, you're correct. You have to uninstall the F-Droid version as it has a different signature than the GitHub version.

> I don't know if you are going to upload the new version to fdroid?

See #202.
