### ISSUE TITLE
Possible failure, does not load app ops in some apps

### ISSUE THREAD

**Issue by gallegonovato** [MuntashirAkon/AppManager#296]
Good afternoon:

First of all, thank you for your great application.

To say that in my terminal I have LineageOS 17.1 with Mahisk in its latest version.

I also have your application in the latest version on github

I gave you all the permissions you asked for. Super user, storage

But they do not load the app ops in applications such as:

Media Storage
Android System Webview
Files
Autostarts
Bluetooth
Bookmark Provider
Contacts
Fdroid
Sd maid

Among others

Since I try to remove the boot options with the system for example from sd maid, fdroid and fennec or Iceraven. And I do not find the way

Best regards and thank you for your help and time.

Pd: Similar or the same happened in the fdroid version. But this time with the version updated to the latest stable version from github. For example in the fdroid application it is impossible or at least I do not get to mark not to start with the system. 

Sorry for nagging you so much or being repetitive

**Comment by MuntashirAkon** [comment]
App Manager version is not mentioned. No logs provided.

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for your help and time.

The version is the latest stable version from github. That is 2.5.20

Make a log. I don't know how to do it. Since I use lineageos with nothing from gaps or google. And all open source.

But it gives me, observing the behavior of the version. It is that, as if there is no understanding between magisk and it. Or the other way around. Since I use magisk in its latest version as well as magisk manager. And sometimes when I open app manager in lineageos 17.1 and I get the message of superuser permission or magisk manager. App manager seems to work fine, but other times I don't get that message and things don't load properly in appmanager. I tried appmanager version 2.5.23 but for example if I hit remove tracker, the app closes by itself. I get the message that there has been an error.

I have granted all the permissions that I asked appmanager. And in magisk comes out active with superuser permissions.

Thanks for your time and help.

**Comment by MuntashirAkon** [comment]
There are many apps such as logcat reader which can be used to take logs without ADB.

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for your help and time.

If you could tell me how to upload the report I would have no problem uploading it. But I do not know how to do it, since I have never done it. 

I also looked in the apk mirror settings. More specifically in the "mode of operation" section. I put auto, I do not know if you should put another option.  

Best regards

**Comment by MuntashirAkon** [comment]
Search the Internet on how to take logcat output. I wish I could help you more on this but I have limited free time.

**Comment by MuntashirAkon** [comment]
Closed due to inactivity. Feel free to open it again if you can reproduce the issue in the latest version.
