### ISSUE TITLE
[Enhancement] Allow opening F-Droid links in Aurora Droid

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#3]
Aurora Droid is an alternative, FOSS client for F-Droid that has gained traction due to its' superior performance and stability.

It would be nice if the app could send open app info intents to this if F-Droid is missing.

https://f-droid.org/app/com.aurora.adroid

**Comment by MuntashirAkon** [comment]
Thanks. I'll do that in the next release. Actually, the app info window doesn't contain much info other than Exodus and Manifest. Now that I'm working with app usage statistics, I'll add more contents there.

**Comment by MuntashirAkon** [comment]
Fixed via 26f5fa6
