### ISSUE TITLE
Flipping orientation back and forth skews disclaimer

### ISSUE THREAD

**Issue by comradekingu** [MuntashirAkon/AppManager#300]
Open the app first time in vertical)

- Flip to horisontal
- Flip back to vertical

Dialog is out of bounds
![bilde](https://user-images.githubusercontent.com/13802408/109410891-82bab580-799e-11eb-8649-eaf6c8b155ca.png)

Motorola G7 Power
LineageOS 17.1
App Manager 2.5.17 from F-Droid
root

Flipping it back worked after a few tries. Dialog could have more text in horisontal mode.

**Comment by MuntashirAkon** [comment]
v2.5.17 is no longer supported. Upgrade to v2.5.20 or later.
