### ISSUE TITLE
Consider using Latex instead of VuePress.

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#303]
Latex has the ability to generate PDF, HTML or ePub with small size and to create differences between two versions which can be useful in understanding the difference between to versions. The HTML page won't be as fancy as the static site generated by VuePress, but this will reduce a lot of burden on me as I've to spend hours on them only to fix broken links and formatting.

**Comment by gnuhead-chieb** [comment]
Please make docs translatable to Japanese on weblate.
