### ISSUE TITLE
Shared Prefs Editor as XML/Value editor

### ISSUE THREAD

**Issue by Sekkei** [MuntashirAkon/AppManager#304]
The built-in Manifest Editor is not a normal xml line-by-line editor, It would be very helpfull if this editor could be used as a activity (? I think it's the right name) to edit any xml file from e.g a file manager.

Maybe json could also be supported ? But this would only be a nice bonus I think , as probably only third party apps uses json (?) XML is still the android default

**Comment by MuntashirAkon** [comment]
App Manager doesn't have a manifest editor yet. See #138.

**Comment by Sekkei** [comment]
Oh my bad I mean the shared prefs editor

**Comment by MuntashirAkon** [comment]
Not possible as it's not really an XML editor. It's a specialised editor for shared prefs which do not support any nesting. A generic XML file can be very ugly and any visual editor would make things more complicated than just raw XML.

**Comment by Sekkei** [comment]
I understand and accept your deccision , but still wanted to propose a concept (even if it actually has little to do with appmanager now). 

The last two states would be the normal AM pref editor view , while the first two handle normal and nested tags
![nested](https://user-images.githubusercontent.com/28356741/109983822-7b2f3f80-7d03-11eb-87bd-8314def5bd1e.png)

**Comment by MuntashirAkon** [comment]
XML files can have hundreds of attributes, values and nestings. Shared prefs consist of only key-value pairs where tag names are hidden in the list since they're not necessary.
