### ISSUE TITLE
Can not work normally with 咪咕音乐 on Android 5.0.2.

### ISSUE THREAD

**Issue by gaojicainiao** [MuntashirAkon/AppManager#305]
AppManager version:2.5.20
Mode:Any
Device and OS:Unofficial rooted Android 5.0.2 ROM on Letv x600.
Installed 咪咕音乐（A Chinese online music software）, then it shows only 咪咕音乐 and nothing else.
When I tap it, it displays “Could not fetch package info”.
After uninstalling 咪咕音乐, it returns normal.
My rooted Unofficial Android 10 ROM on Xiaomi Redmi note 4X doesn't have such problem.

I don't mind such problem. Fix it if you like. :)
Thank all contributers and developers of AppManager.

**Comment by MuntashirAkon** [comment]
Huh, weird. Can you take logcat output?

**Comment by ZhongYouDianNao** [comment]
> Huh, weird. Can you take logcat output?

This one?
cleared AppManager's data→started AppManager→installed 咪咕音乐→started AppManager again→tapped 咪咕音乐→uninstalled 咪咕音乐→started AppManager again and refreshed→got the am.log.
[am.log](https://github.com/MuntashirAkon/AppManager/files/6082996/am.log)

**Comment by gaojicainiao** [comment]
> Huh, weird. Can you take logcat output?
This one?
[am.log](https://github.com/MuntashirAkon/AppManager/files/6083035/am.log)

cleared AppManager's data→started AppManager→installed 咪咕音乐→started AppManager again→tapped 咪咕音乐→uninstalled 咪咕音乐→started AppManager again and refreshed→got the am.log.

**Comment by MuntashirAkon** [comment]
> This one?

Search “how to take logcat output” online to know how to capture logcat output. If you have root, you can do that using Android apps such as Logcat Reader.

For taking logs, use debug builds instead of the release builds. They have different signature so you can install them alongside the regular App Manager. You can get debug builds from GitHub actions: https://github.com/MuntashirAkon/AppManager/actions

**Comment by MuntashirAkon** [comment]
Closed due to inactivity. Feel free to open the issue if you can still reproduce the issue.

**PS:** One of the testers tried to reproduce the issue on a device running Android Lollipop but was unable to reproduce it.
