### ISSUE TITLE
Uninstall apps for a particular user

### ISSUE THREAD

**Issue by the-anonymous-raven** [MuntashirAkon/AppManager#307]
Is it possible to add uninstalling apps for a particular user?
By default when I uninstall an app in any user, it removes it for user 0.

I meant implementation of 
pm uninstall -k --user xx name-of-application

**Comment by MuntashirAkon** [comment]
It uninstalls an app for the user that you have selected before loading the app details page. Batch operations are done for all users.

**Comment by the-anonymous-raven** [comment]
I can confirm that choosing the user and then clicking on uninstall uninstalls it for user 0 only and  not other work profiles.

**Comment by MuntashirAkon** [comment]
> Perhaps it is a bug then?

I think so. This only seems to happen when the app is installed on both profiles.

**Comment by MuntashirAkon** [comment]
Fixed in 799df310
