### ISSUE TITLE
Can't enable global component blocking on debug version #942

### ISSUE THREAD

**Issue by kgursu** [MuntashirAkon/AppManager#308]
**Describe the bug**
When I tried to use that setting the app freezes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings
2. Click on Global component blocking
3. App freezes

**Expected behavior**
I expected to enable that setting.

**Screenshots**
![IMG_20210305_113137_024.jpg](https://user-images.githubusercontent.com/35314872/110088815-63f55e00-7da6-11eb-8632-0b1196b6084d.jpg)

**Crash logs**
[Logcat](https://del.dog/otanavywit)

**Device info**
 - Device: Sony Xperia Z2 (sirius)
 - OS Version: Android 10
 - App Manager Version: Debug version 2.5.24 #942
 - Mode: root

**Additional context**
I tried disabling the same setting of AM Pre-release before trying again. The same outcome occur.

**Comment by MuntashirAkon** [comment]
Fixed in 9bc198ec
