### ISSUE TITLE
Add option to disable kill feature for system apps

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#31]
Hi,
Im scared to enter the app kill window cause I dont wanna accidently kill system apps, I need the root features though... Please add a setting for this!
Thanks
(Also Thanks for the great app! <3)

**Comment by Atrate** [comment]
What?

**Comment by MuntashirAkon** [comment]
> Im scared to enter the app kill window cause I dont wanna accidently kill system apps, I need the root features though... Please add a setting for this!

I'll add an option to disable kill options for system apps and processes owned by root.

**Comment by UltraBlackLinux** [comment]
thanks!

**Comment by MuntashirAkon** [comment]
Closed via 50e32a4
