### ISSUE TITLE
Element inspector

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#310]
Need opensource alternative of this app
https://play.google.com/store/apps/details?id=com.appsisle.developerassistant
![Screenshot_20210307-041731](https://user-images.githubusercontent.com/41156994/110218500-051d0b00-7eb2-11eb-8119-d4d6e8277aac.png)  ![Screenshot_20210307-041933](https://user-images.githubusercontent.com/41156994/110218586-67760b80-7eb2-11eb-9b68-297c0d2f680d.png)
![Screenshot_20210307-042002](https://user-images.githubusercontent.com/41156994/110218508-0ea67300-7eb2-11eb-93c5-66ce97164bdd.png) ![Screenshot_20210307-042035](https://user-images.githubusercontent.com/41156994/110218510-1108cd00-7eb2-11eb-8cee-8422eb8426ad.png)

**Comment by MuntashirAkon** [comment]
Publish it on open source forums or some other place. This is outside of this project's scope.

**Comment by gnuhead-chieb** [comment]
For now, I think this is not outscope of AppManager if Logcat Viewer can get implemented in AM.
I think this feature is useful for knowing app's layout and current activity.

**Comment by MuntashirAkon** [comment]
Log viewer is created to help the users, not developers.
