### ISSUE TITLE
Xposed/App hooking(riru) features

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#311]
・Restrict app behavior(e.g. read clipboard,use sensors,etc...)
・Hide app from other apps
・Apply settings per app(e.g. use different locale,font size,dpi,etc... per app)
・Mock device information per app(e.g. SN,Android ID,IMEI,etc...)

alternatives:
https://github.com/Mikanoshi/SudoHide
https://github.com/M66B/XPrivacyLua
https://github.com/BlueCat300/XposedAppSettings

**Comment by MuntashirAkon** [comment]
As I said in various issues, I don't use Xposed.

If any other developer is interested in contributing (which is highly unlikely in my experience), then the issue may be reopened.

**Comment by gnuhead-chieb** [comment]
how about zygisk?

**Comment by MuntashirAkon** [comment]
> how about zygisk?

It's still in beta.

**Comment by gnuhead-chieb** [comment]
stable version released for now

**Comment by MuntashirAkon** [comment]
> stable version released for now

Yes, I was talking about v24 (and v24.1). If you looked carefully, you'd see that Zygisk is still in beta in those versions and disabled by default. It would be troublesome if the APIs change in the between versions. So, I will wait for a production version first.
