### ISSUE TITLE
Backup/Restore with 'Only APK' option unmarked creates corrupted app

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#313]
Continuation from here; https://github.com/MuntashirAkon/AppManager/issues/30#issuecomment-792279264
As the title says it creates a corrupted installation of apps that doesn't launch. (Badly crashes while trying to launch).

Note:
No Odex patch applied, just regular Backup/Restore.

Crash log: https://del.dog/ypexaperru
![image](https://user-images.githubusercontent.com/32187927/110244471-066d3700-7f89-11eb-89ec-9a14eee862db.png)
Shows this weird msg while uninstalling.

**Comment by MuntashirAkon** [comment]
On the same device?

**Comment by Cyberavater** [comment]
Of course! Why don't you try it, it's easy to reproduce.

**Comment by MuntashirAkon** [comment]
It's working fine here.

**Comment by Cyberavater** [comment]
So, what might be wrong on my side? Also, can you try on different devices? (Or someone you might know can check this?) My device is Android 10 LOS-based.

**Comment by Cyberavater** [comment]
> It's working fine here.

If you don't uninstall the app before restoring it, there are 2 copies of the same app (Only happens when the 'Only APK' option is un-marked), one that is working fine (from before), the other one is a corrupted installation. Maybe you missed checking the other copy? (As this issue is present in my other device too).

**Comment by MuntashirAkon** [comment]
> If you don't uninstall the app before restoring it, there are 2 copies of the same app (Only happens when the 'Only APK' option is un-marked), one that is working fine (from before), the other one is a corrupted installation. Maybe you missed checking the other copy?

Huh? Two copies of the same app? Weird.

**Comment by MuntashirAkon** [comment]
Can you share the full workflow, i.e. which flags were used during the back up and during restore? Try with the latest debug build as usual.

**Comment by Cyberavater** [comment]
To further test this issue, I need #345 fixed.

**Comment by Cyberavater** [comment]
> which flags were used during the backup and during restore?

All except "APK only", "Rules", "Backup multiples"

Now I see only one un-lauchable copy.


![image](https://user-images.githubusercontent.com/32187927/113121894-ed2c7300-9234-11eb-9312-03681c4cea2f.png)

**Comment by MuntashirAkon** [comment]
Open the source directory to see if the `oat` folder's empty.

**Comment by Cyberavater** [comment]
Source directory sent to you via TG

**Comment by MuntashirAkon** [comment]
I think this need a lot of studies, how its implemented in Android framework and how it is utilised by third-party tools like Xposed or Lucky Patcher. So, I'm disabling the flag for now. It will only backup/restore APK files until the issue is fixed.
