### ISSUE TITLE
I seem to be unable to open as "working on ADB mode"

### ISSUE THREAD

**Issue by wandererby** [MuntashirAkon/AppManager#318]
**Describe the existing feature/documentation**

**Describe your problem(s)**
Per the section - "<https://muntashirakon.github.io/AppManager/guide/adb-over-tcp.html#_4-2-enable-adb-over-tcp-via-pc-or-mac>", I was opening the AM but without any "working on ADB mode" prompt but one prompt popup "Allow USB debugging?" and the list of all apps are showing well.  Also I clicked and went into one app's details and chose tab "APP OPS" where there showed nothing...finally then I went back to the main page and I found out the popup "Allow USB debugging" always popped up, so that I needed clicking ALLOW all the time...

I am not sure if I did something incorrect? Please helps...

**Additional contexts**
Android 10, Nokia 8.1, plugging in the USB cable with "file transfer mode".

**Comment by wandererby** [comment]
x

**Comment by wandererby** [comment]
Strangely it is!  It suddenly recovered to be normal when I unplugged the USB cable and restarted the app...😅

**Comment by MuntashirAkon** [comment]
As noted in the [docs](https://muntashirakon.github.io/AppManager/guide/adb-over-tcp.html#_4-3-enable-adb-mode-on-app-manager), you may need to disconnect the cable in order for it to work. This seems to be the case in many phones including Samsung, Nokia and One Plus, and in Lineage OS or its derivatives.

**Comment by wandererby** [comment]
@MuntashirAkon Got it, thanks a lot! And I have another one question - every time both open the app or go back to the homepage of the app from detail page, it all will pop up one box "Allow USB Debugging?". Even though I checked the box to always agree but it will remain. 

So I just wanted to know if this is a known issue or just specific? Thanks again for your update! 🙂

**Comment by MuntashirAkon** [comment]
It depends on App Manager version. The issue has been fixed in v2.5.23. If you're using only stable releases, wait for v2.5.25.

**Comment by wandererby** [comment]
@MuntashirAkon Thanks a lot, I am now using the v2.5.20 and waiting for v2.5.25. :-)
