### ISSUE TITLE
Difference App Tabs

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#319]
**Is your feature request related to a problem? Please describe.**
i can't check which one is system framework app and which one is not

**Describe the solution you'd like**
maybe add tab to tell you:
-Os App
-System App 
-And Many More

**Describe alternatives you've considered**

**Additional context**
Ok I Understand My Explanation Is Too Difficult To Understand 
To Understand What I Mean:
Check Brevent App On Playstore

**Comment by MuntashirAkon** [comment]
I don't have the time to check any third-party app. You should include the necessary information/screenshots in the report itself. Check out #138 or #164 to get a better idea on how to request for a new feature.

---
_It's better to use a translator if you're not familiar with English._

**Comment by NSTAdventure** [comment]
> I don't have the time to check any third-party app. You should include the necessary information/screenshots in the report itself. Check out #138 or #164 to get a better idea on how to request for a new feature.
> 
> _It's better to use a translator if you're not familiar with English._

![Screenshot_2021-03-20-13-14-50-19](https://user-images.githubusercontent.com/50813528/111861108-5fbc6980-897e-11eb-97f9-5bb25dafb2f8.jpg)

Os app:
-app that you cannot do anything on it include
Change app ops and more
-core apps
Are apps that have same signature as system framework apps
-system apps
-user apps 


....

**Comment by MuntashirAkon** [comment]
It's not possible to add tabs like that because our design is more generalised and very different. Adding tabs will prevent users from utilising batch operations, for example. Instead, you can use filters (or can request for new filters).

**Comment by NSTAdventure** [comment]
> It's not possible to add tabs like that because our design is more generalised and very different. Adding tabs will prevent users from utilising batch operations, for example. Instead, you can use filters (or can request for new filters).

Haish 

Bro if you cannot add tab then take it as filter feature request

**Comment by MuntashirAkon** [comment]
> Bro if you cannot add tab then take it as filter feature request

Okay.

**Comment by MuntashirAkon** [comment]
So, what are the filters that you want? The only usable filter, it seems, it the apps matching system signatures.

**Comment by NSTAdventure** [comment]
like i mentioned above


also i will make other issues (feature request) 
stay tuned :D

> > I don't have the time to check any third-party app. You should include the necessary information/screenshots in the report itself. Check out #138 or #164 to get a better idea on how to request for a new feature.
> > _It's better to use a translator if you're not familiar with English._
> 
> ![Screenshot_2021-03-20-13-14-50-19](https://user-images.githubusercontent.com/50813528/111861108-5fbc6980-897e-11eb-97f9-5bb25dafb2f8.jpg)
> 
> Os app:
> -app that you cannot do anything on it include
> Change app ops and more
> -core apps
> Are apps that have same signature as system framework apps
> -system apps
> -user apps
> 
> ....
