### ISSUE TITLE
Blocking trackers in desktop enivronnements apps.

### ISSUE THREAD

**Issue by molitona** [MuntashirAkon/AppManager#323]
Hi MuntashirAkon and all AppManager community,

I wonder, Is it possible to find any solution to block trackers on GNU/Linux or Windows applications ?
If there is ones, which are they ?
If not, Is it impossible to have such ones, and why  ?

Sorry, if I'm talking about a non-related AppManager topic, because I think you're the only person you could answer that question giving your expertise in that field.
Thanks.

**Comment by MuntashirAkon** [comment]
In most desktop operating systems, software are not as well structured as in Android and doesn't provide much option to modify an app's component without modifying the app itself. You can still use app specific Internet firewall provided you have proper sandboxing enabled i.e. making use of SELinux or AppArmor in Linux, or installing apps only from the Microsoft Store in Windows (sandboxing is enabled by default in macOS' XNU kernel). You can also use DNS or hosts-file based blocking.

For Linux, you can take a look at [Madaidan's guide on Linux hardening](https://madaidans-insecurities.github.io/guides/linux-hardening.html) (caution: it's a very very long article).

If you want better privacy and security, macOS is probably the best option right now as sandboxing is enabled by default and inter-process communication is very strict provided you have system integrity protection enabled (it's enabled by default). It also offers file vault which can be used to encrypt your hard-drive (like BitLocker in Windows). You can use app specific firewall like LittleSnitch (proprietary) or [LuLu](https://github.com/objective-see/LuLu) (FOSS) as well as hosts/DNS blocking. Unlike Windows, system apps can't be bypassed from blocking (up to 10.15 and after 11.2.3) and you can prevent macOS from calling home with simple blocking.

**Comment by gnuhead-chieb** [comment]
Try this tools
https://github.com/henrypp/simplewall
https://pi-hole.net/
https://github.com/evilsocket/opensnitch

**Comment by molitona** [comment]
> Try these tools
> https://github.com/henrypp/simplewall
> https://pi-hole.net/
> https://github.com/evilsocket/opensnitch
> https://safing.io/portmaster/

Thanks for sharing!

**Comment by molitona** [comment]
> In most desktop operating systems, software are not as well structured as in Android and doesn't provide much option to modify an app's component without modifying the app itself. You can still use app specific Internet firewall provided you have proper sandboxing enabled i.e. making use of SELinux or AppArmor in Linux, or installing apps only from the Microsoft Store in Windows (sandboxing is enabled by default in macOS' XNU kernel). You can also use DNS or hosts-file based blocking.
> 
> For Linux, you can take a look at [Madaidan's guide on Linux hardening](https://madaidans-insecurities.github.io/guides/linux-hardening.html) (caution: it's a very very long article).
> 
> If you want better privacy and security, macOS is probably the best option right now as sandboxing is enabled by default and inter-process communication is very strict provided you have system integrity protection enabled (it's enabled by default). It also offers file vault which can be used to encrypt your hard-drive (like BitLocker in Windows). You can use app specific firewall like LittleSnitch (proprietary) or [LuLu](https://github.com/objective-see/LuLu) (FOSS) as well as hosts/DNS blocking. Unlike Windows, system apps can't be bypassed from blocking (up to 10.15 and after 11.2.3) and you can prevent macOS from calling home with simple blocking.

As expected, you're top 😃. Thanks for sharing that, and please if you have another great resources related to GNU/Linux feel free to share them!

**Comment by MuntashirAkon** [comment]
> if you have another great resources related to GNU/Linux feel free to share them!

Read the guide. It has links to many other resources. It's more or less a complete guide to securing Linux. Additionally, you can setup DNSCrypt (you can tor as the DNS resolver if you want), or if you have a spared device, you can run Pi-hole server there for a network-wide ad blocking experience.

**Comment by molitona** [comment]
Ok, thanks!
