### ISSUE TITLE
Update trackers/libs dynamically

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#328]
Currently users have to update AM for new tracker/libs signatures.
It is better to allow users to choose signature source retrive/update signatures from exodus,etip,izzyondroid and custom signatures sources with internet.

**Comment by MuntashirAkon** [comment]
AM doesn't connect to the Internet and we like to keep it that way.

**Comment by gnuhead-chieb** [comment]
> AM doesn't connect to the Internet and we like to keep it that way.

After https://github.com/MuntashirAkon/AppManager/commit/8a8a38bb55d0eba3ceeed9093ccd27f39c36cc5b, there is internet-depending feature.

**Comment by MuntashirAkon** [comment]
> After [8a8a38b](https://github.com/MuntashirAkon/AppManager/commit/8a8a38bb55d0eba3ceeed9093ccd27f39c36cc5b), there is internet-depending feature.

Yes, and for that I had to add a disclaimer at two places even though that feature will not be used by most people due to the complexity it involves (most people may never even notice the feature). Updating trackers and libraries means connecting to GitHub, GitLab (thrice each) and Exodus (twice) which still costs a lot.

**Comment by MuntashirAkon** [comment]
I think we can, at least, attempt to keep the trackers up-to-date (others are not that important). But first, I have to know how long Exodus retains personal information (IP info, etc.) and if they are okay with downloading ETIP signatures via App Manager by its users. ETIP is also not a part of the Exodus API, so chances are that they may have not reserved enough bandwidth for this subdomain.

@pnu-s: I apologize for pinging you here. Do you have any input regarding this?

**Comment by pnu-s** [comment]
I would advise to use the Exodus API for multiple reasons:
* on ETIP you will find a lot of unvalidated trackers, so you have a real risk of false positives
* Exodus API is made for that purpose: the trackers endpoint is available without API key and there is some caching in place

> I have to know how long Exodus retains personal information (IP info, etc.)

As far as I know we do not retain much, but @codeurimpulsif can confirm this

**Comment by MuntashirAkon** [comment]
> on ETIP you will find a lot of unvalidated trackers, so you have a real risk of false positives

We are aware of that as we've been contributing to the ETIP since last year (and actually, as far as I remember, the last reported false-positive was one of the accepted trackers). This is a risk worth taking because it aligns with our interests.

**Comment by codeurimpulsif** [comment]
> I have to know how long Exodus retains personal information (IP info, etc.)

For now, on the Exodus API we keep information (IP address, date, time, requested URL and user-agent) for 16 days (for abuse prevention).
