### ISSUE TITLE
Make scrollbar draggable

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#329]
Same as title

Example:
https://user-images.githubusercontent.com/41156994/111993768-e86a0f80-8b0e-11eb-840a-29af69e11f27.mp4

**Comment by MuntashirAkon** [comment]
I don't get it. Fast scrolling has already been enabled on most pages, tabs and dialogs. Can you elaborate that?

**Comment by gnuhead-chieb** [comment]
Thanks.Fastscroll works in new debug build.
