### ISSUE TITLE
Am crash on viewing yesterday usage(special case)

### ISSUE THREAD

**Issue by GithbUser** [MuntashirAkon/AppManager#338]
Am debug 1056 crashes when you try to view yesterday app usage when you flashed custom rom today(when yesterday data is not found/missing).

Steps to reproduce the behaviour:
1. Go to Am
2. Click on three dots and then app usage 
3. Click on today and select yesterday

Expected behavior
Add no data found or something instead of crash

Crash log
[New file.txt](https://github.com/MuntashirAkon/AppManager/files/6204430/New.file.txt)

Screenrecord: 

https://user-images.githubusercontent.com/75420364/112470068-39d50180-8d90-11eb-9c97-4b1729f1e1d2.mp4

Device info
 - Device: Poco m2 pro
 - OS Version: Arrow OS android 11
 - App Manager Version: am debug 2.6.0 #1056
 - Mode: root

**Comment by MuntashirAkon** [comment]
Fixed in 1fc5ba69
