### ISSUE TITLE
Changing the app name

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#339]
We're now hitting a major release (v2.6.0). This is going to be the first long term supported release, i.e. this will be the first version of app manager to receive patches until the next stable release is made.

App Manager is something I made for myself and never really thought that it would reach so much audiences. Now, I can feel that there are many people like me who were waiting for an app that would help them replace privacy invading, non-free apps as well as help those who're suffering from the guilt of using cracked software. The development of App Manager was so fast because I've spent a lot of time analysing other not-so-usable and, often abandoned projects which has given me insights on how to implement such features. I'm also working very hard to ensure security of the data because a rooting app itself is never fully secured (and you're welcome to find any security issues!).

Therefore, it's time to change the name of the app to something special so that it can be uniquely identified (the package name will still be the same though and the old repository will be redirected to the new one).

The best name will be chosen based on the apps functions and/or creativity, and the person will be credited in the about section!

Here are a few names that was proposed by one of the contributors:
- Great Manager
- Good Manager
- Deep Manager
- Endless
- Endless Manager
- Extreme Manager
- Ex Manager
- Xtreme Manager
- X Manager
- Manager X

**Comment by PookaMustard** [comment]
AM Toolbox, or AM Tools

Benefits of these names:
- retains the App Manager branding
- gets people interested about what the AM means, they get "App Manager"
- abbreviated to AMT

**Comment by itsakkayy** [comment]
Appex Manager

**Comment by RezurrectBodg** [comment]
Allmight toolbox

**Comment by uri13** [comment]
- Manager Ops
- ManOps

**Comment by asood971** [comment]
Akon's Incessant Solitude ( privacy)
Incessant Privacy Manager

**Comment by MPeti1** [comment]
I don't have a unique idea, but I think most of the proposals don't make it apparent what does the app manage, or what does it do.
AM Toolbox is one of those that I like more, because it's not too long, and I think it makes the app's goal clear (and the abbreviation clears up questions).
I don't want to be pedantic, but I hope that this will help people in coming up with names.

**Comment by Younes-L** [comment]
* **Privacy Toolbox**

I like Pooka's AM Toolbox/Tools , as it does a good job of suggesting that AM is a multi purpose app. But it doesn't emphasise the privacy guarding features of AM which I think are the most important/distinctive.

My other suggestions if you want to focus even more on privacy : any combination of these words

| first word | | | second word |
| :---: | :---: | :---: | :---: |
| App | | | Sentinel |
| Package | | | Patrol |
| Privacy | | | Guard |
| Permission |  | | Toolbox |

One potential reason to have a name that starts with `A` is to keep AM listed at the top of the app drawer and other app lists such as system settings

**Comment by Atrate** [comment]
"AM Tools/Toolbox" sounds best IMO, although something like "AM Privacy/Device Tools/Toolbox" could be considered as well.

**Comment by tommynok** [comment]
App Multitool

**Comment by mario0318** [comment]
AAME, or AEM (pronounced aim), AEK, or simply AE
Android Auxiliary Management Extensions
Android Extensions Management Kit
(Android/Auxiliary) Extensions

Or some combination of any of that. I was trying to come up with a self-referential name like how GNU stands for "GNU's Not Unix", like AMS could be AM Master Suite where AM can really mean just about anything Android related.

**Comment by RezurrectBodg** [comment]
I like @mario0318's AMS Master Suite, but I think we could take it a step further.

**Comment by PookaMustard** [comment]
> I like Pooka's AM Toolbox/Tools , as it does a good job of suggesting that AM is a multi purpose app. But it doesn't emphasise the privacy guarding features of AM which I think are the most important/distinctive.

As much as I'd like the privacy aspects to be emphasized, I think focusing on the privacy bit would make the new name a touch more cumbersome. AM Toolbox/Tools just rolls off the tongue and is a fairly simple yet non-intrusive rebranding. A title centered on the privacy, or indeed any aspect of AM other than its diverse toolset, would miss the point of my minimal take. A quick and dirty example: AM Privacy Tools just implies AM is like a combo of VPNs and Tor more than an app manager.

**Comment by Younes-L** [comment]
> A quick and dirty example: AM Privacy Tools just implies AM is like a combo of VPNs and Tor more than an app manager.

If that's what I means to you, fair.
To me it doesn't imply VPNs , it implies the blocking of permissions/receivers/etc and other tangible features of AM.
Especially if keeping AM (App Manager) in the name, VPNs have little to do with managing apps.

In my opinion, there needs to be emphasis on the privacy blocking and permission control features. Otherwise potential users will miss out on these important features if they already have a backup/restore app or if they don't need such convenience features.

Sure AM can also uninstall and backup but these are convenience features, uninstalling can be done from system settings and any file manager can also backup .apk files without root. With root you can also backup /data/pakagename of any app.

AM enables users to do more than just backup or uninstall apps, and this is why the name should reflect the unique features of AM

I guess for this argument to go further, everyone who suggested names should also explain why they installed AM and what features they use.

> Also longer abbreviation and full name.

PT is a same length abbreviation , 2 words just like AM.

**Comment by hemantmeena1990** [comment]
What about it?
Android Confiner & Comptroller(ACC)

**Comment by LeSnake04** [comment]
I  would suggest a mix between App Manager and Privacy:

App Privacy Manager APM
Or App Privacy Toolbox APT

The short version of my second suggestion would be a funny, but kind of fitting coincident

**Comment by tiborkulcsar** [comment]
App Master
But all aside I think the current name is best, can't imagine another one

**Comment by AzimsTech** [comment]
**AppMan**

I remember a lot of Symbian app uses CamelCase naming convention. I thought it would be fun to bring it back for nostalgia's sake. :laughing:
![](https://i.imgur.com/EQUPfa6.png)

**Comment by RezurrectBodg** [comment]
@LeSnake04 yup, APT. Maybe "App Privacy Tool"?

**Comment by LeSnake04** [comment]
@RezurrectBodg I think toolbox sounds better

**Comment by RezurrectBodg** [comment]
@LeSnake04 I think we won't say the app name out loud anyway, since it's written

**Comment by LeSnake04** [comment]
@RezurrectBodg I see what you did there...

But it also looks better ?

**Comment by krouter** [comment]
Applorian or Appalorian - fiercely guarding, caring and delivering. This is the way.

**Comment by Deerp1976** [comment]
AM Toolbox seems the best name I've seen. Or if you wanted to be different
how about MA Toolbox and then it will be same as your initials Muntashir
Akon

**Comment by RezurrectBodg** [comment]
@LeSnake04 the shorter the better🙂
@Deerp1976 MA like in... Manager App?

**Comment by Deerp1976** [comment]
@Rezurrectbodg yes of course Manager App. It was just a play on AM Toolbox
and reversing the letters makes it Muntashirs initials too. To be honest it
doesn't really matter what the initials stand for just as long as it's
memorable. I used to work at a bank called Egg which Im sure you agree, it
has nothing to do with a financial institution but the word is memorable.
That's the key to marketing!

**Comment by MuntashirAkon** [comment]
> AM Toolbox seems the best name I've seen. Or if you wanted to be different how about MA Toolbox and then it will be same as your initials Muntashir Akon

I don't want to include my name, of course 😃 . **MA Toolbox** would have a short name **MAT** which already exists: MyAndroidTools. Also, **AM Toolbox** sounds a lot cooler than **MA Toolbox**.

> Or some combination of any of that. I was trying to come up with a self-referential name like how GNU stands for "GNU's Not Unix", like AMS could be AM Master Suite where AM can really mean just about anything Android related.

This (the GNU or WINE part) was actually the first thing that came to my mind due to my motivation of creating such tools. However, I have yet to find a name that would sound better. AMS is a good name and is, in some sense, analogous to what @PookaMustard has proposed but I'll still wait for a better name!

**Comment by Deerp1976** [comment]
I take it that Muntashir's Intelligent Toolbox or MIT is out the question
then 😂

**Comment by RezurrectBodg** [comment]
@Deerp1976, it can be "M Intelligent Toolbox" then.

**Comment by Cyberavater** [comment]
Also, consider changing the icon too, the current icon is very common and can be seen in most other places.

**Comment by MuntashirAkon** [comment]
> Also, consider changing the icon too, the current icon is very common and can be seen in most other places.

Submit your ideas in #53.

**Comment by MrCarb0n** [comment]
- **AppBox**
- **AMBox**

**Comment by MrCarb0n** [comment]
**AkonBox** - _A Android App Management Toolbox by **Muntasir Akon**_

I'd prefer different naming instead of `App`, `Management`, `Toolbox`. What you think ppl?

**Comment by Alifaisal404** [comment]
**_AM Toolbox_** seems beeter than AM Tools, go ahead!!

**Comment by Alifaisal404** [comment]
**_AM Toolbox_** seems better than AM Tools, go ahead!!

**Comment by MuntashirAkon** [comment]
I think **AM Toolbox** is the winner here. As the only additional to the original name is the _toolbox_, I will still use the **AM** abbreviation to refer the app as it's more convenient than _AMT_. However, the issue will remain open till 24 April to see if anybody comes up with a better suggestion.

**Comment by NSTAdventure** [comment]
> I think **AM Toolbox** is the winner here. As the only additional to the original name is the _toolbox_, I will still use the **AM** abbreviation to refer the app as it's more convenient than _AMT_. However, the issue will remain open till 24 April to see if anybody comes up with a better suggestion.

agree your app has AIO solution

**Comment by solomonrajan** [comment]
App Engine

**Comment by EnlightenedIllusions** [comment]
AM Toolbox is my favorite given all the reasons already mentioned. The word toolbox for me makes me think you never know what your going to get as far as one persons toolbox might be an unorganized mess and another the opposite, so to that, I prefer Toolkit, because a kit is well thought out and organized (or at least in theory) based on its purpose. So I submit AM Toolkit as an alternative to consider. Fantastic all around btw! Thankyou @MuntashirAkon and all contributors for your hard work.

**Comment by LeSnake04** [comment]
I would prefer AM Toolkit over AM Toolkit

**Comment by MuntashirAkon** [comment]
I've thought this through with a few of my _professional_ friends (I'm not one of them!) and we agreed that neither **AM Toolbox** nor **AM Toolkit** has any advantage over the current name. They've also suggested me to avoid any tri- or poly-syllabic names. Hence, I think I'll stick to App Manager or AM for now until I find a better alternative that's, preferably, outside the norm.

So, it's not yet the end! You can still suggest some good names if you have them in your bucket!

**Comment by Cyberavater** [comment]
What's your opinion on naming from significant historic events, naming from influential wars, or character/artifact from mythology?

**Comment by MuntashirAkon** [comment]
> What's your opinion on naming from significant historic events, influential wars, or character/artifact from mythology, which might make the user learn something new/forgotten in the way?

Perfectly allowed, as long as there's no copyright/trademark or something equivalent.

**Comment by Alifaisal404** [comment]
> > What's your opinion on naming from significant historic events, influential wars, or character/artifact from mythology, which might make the user learn something new/forgotten in the way?
> 
> Perfectly allowed, as long as there's no copyright/trademark or something equivalent.

How is "Hitler App Manager". No offence, it's Hitler for trackers. 😎

**Comment by LeSnake04** [comment]
> > > What's your opinion on naming from significant historic events, influential wars, or character/artifact from mythology, which might make the user learn something new/forgotten in the way?
> > 
> > 
> > Perfectly allowed, as long as there's no copyright/trademark or something equivalent.
> 
> How is "Hitler App Manager". No offence, it's Hitler for trackers. 😎

*Perfectly allowed, as long as there's no copyright/trademark, controversy or something equivalent.
