### ISSUE TITLE
Logcat viewer

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#34]
A properly formatted logcat viewer is very helpful in debugging applications and a must have feature of an app manager.

**Comment by Atrate** [comment]
To integrate it more tightly with the idea of AppManager, it could maybe be possible to press "logcat" in an app's detaiped view and have the logcat filtered by packagename of the app

**Comment by MuntashirAkon** [comment]
> To integrate it more tightly with the idea of AppManager, it could maybe be possible to press "logcat" in an app's detaiped view and have the logcat filtered by packagename of the app

Great thinking. I will keep that in mind when I'll implement this.

**Comment by MuntashirAkon** [comment]
Features:
1. Dedicated entrance to the log viewer page via the three-dots menu
2. Package-specific (actually PID specific) viewer via the app details page (for running packages only)
3. PID specific viewer from the running apps page

Capabilities:
We'll be reusing code from [Matlog Libre](https://github.com/pluscubed/matlog) (which is based on CatLog), therefore it will have all the features that this software offers, except the colour schemes. AM will allow users to edit/import all the colours used by the app (except the primary, secondary and accent colours) in the future.
