### ISSUE TITLE
Cannot install apps using AM Installer

### ISSUE THREAD

**Issue by hbarsaiyan** [MuntashirAkon/AppManager#340]
**Describe the bug**
Every time I try to use the installer for installing an apk, the loading popup appears for a few seconds and then nothing happens. The install prompt never comes.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to apk file location
2. Open apk with App Manager to install
3. See error

**Expected behavior**
Prompt to install apk and eventually install it. 

**Screenshots**
![Screenshot_20210327-235308_AM_Pre-release](https://user-images.githubusercontent.com/37732050/112730465-bbc35700-8f57-11eb-8f59-77ae892fb6aa.png)
![Screenshot_20210327-235325_MiXplorer](https://user-images.githubusercontent.com/37732050/112730468-bfef7480-8f57-11eb-8fbe-dd2b0d26ed1c.png)

**Crash logs**
If applicable, add crash logs to help us figure out the problem. 
[Log_2021-03-27_23-55-54.txt](https://github.com/MuntashirAkon/AppManager/files/6216162/Log_2021-03-27_23-55-54.txt)

**Device info**
 - Device: Lenovo Tab 4 X304L
 - OS Version: Lineage OS 16
 - App Manager Version: 2.5.24 pre-release
 - Mode: root

**Additional context**
I opened the apk file from Mixplorer.

**Comment by MuntashirAkon** [comment]
Have you tried any other file managers or the Android-default **Files** app?

**Comment by hbarsaiyan** [comment]
@MuntashirAkon Yes it is a hit or a miss. Sometimes it works perfectly, other times the installer popup just disappears after the loading screen.

**Comment by Cyberavater** [comment]
I confirm this, I've reported this issue long ago (multiple times via TG).

Note: It doesn't happen if installed from AM's app info activity (or if using install activity of older build, forgot specific version).

**Comment by MuntashirAkon** [comment]
Parsing package often fails due to a cache bug present in the Android's PackageManager. I've been writing an alternative to Android PackageManager since December but it's not yet usable.

**Comment by MuntashirAkon** [comment]
The issue contains the phrase **every time**, so I initially thought it could be related to the MiXplorer issues.

**Comment by hbarsaiyan** [comment]
It wasn't working on the 2.5.24 pre-release. It works for most of the part on 2.6.0 debug builds, except for big apk files. But as you said you are working on an alternative, i will wait for it.

**Comment by Cyberavater** [comment]
This issue is fixed in the latest version.

**Comment by MPeti1** [comment]
Which latest version? Latest debug? Debug Build #1105

**Comment by Cyberavater** [comment]
Yes.

**Comment by MPeti1** [comment]
Should I open a new issue if it's still not working for me?
Asking because for me it's not just the app installation that does not work, but also the manifest viweing, scanning, etc, both from MiXplorer and Total Commander

**Comment by Cyberavater** [comment]
> Should I open a new issue if it's still not working for me?

No need, it's not closed yet. You reporting it here was enough. Thanks for reporting. Altho, you should add your logs here too, the dev might check if it's a different issue.

**Comment by MPeti1** [comment]
Ok, nevermind, it seems it was only a (storage) permission problem in the debug version.  
Though the latest pre-release errors out even with the permission granted, so we probably had the same problem which is fixed in this build.

**Comment by MuntashirAkon** [comment]
Should be fixed with the introduction of the new installation interface in v2.6.4
