### ISSUE TITLE
Crashes on Selecting System Config in 3 dot right upper menu.

### ISSUE THREAD

**Issue by Genxster1998** [MuntashirAkon/AppManager#341]
```
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.ParcelFileDescriptor io.github.muntashirakon.AppManager.IRemoteFile.getPipedInputStream()' on a null object reference
    at io.github.muntashirakon.io.ProxyInputStream.<init>(ProxyInputStream.java:43)
    at io.github.muntashirakon.AppManager.utils.IOUtils.getFileContent(IOUtils.java:337)
    at io.github.muntashirakon.AppManager.utils.IOUtils.getFileContent(IOUtils.java:323)
    at io.github.muntashirakon.AppManager.sysconfig.SystemConfig.readPermissionsFromXml(SystemConfig.java:657)
    at io.github.muntashirakon.AppManager.sysconfig.SystemConfig.readPermissions(SystemConfig.java:642)
    at io.github.muntashirakon.AppManager.sysconfig.SystemConfig.readAllPermissions(SystemConfig.java:542)
    at io.github.muntashirakon.AppManager.sysconfig.SystemConfig.<init>(SystemConfig.java:537)
    at io.github.muntashirakon.AppManager.sysconfig.SystemConfig.getInstance(SystemConfig.java:331)
    at io.github.muntashirakon.AppManager.sysconfig.SysConfigWrapper.getSysConfigs(SysConfigWrapper.java:40)
    at io.github.muntashirakon.AppManager.sysconfig.SysConfigActivity.lambda$onStart$1$SysConfigActivity(SysConfigActivity.java:103)
    at io.github.muntashirakon.AppManager.sysconfig.-$$Lambda$SysConfigActivity$Z0_yuKTYWENRNY2UDv8WHBgf8cs.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:919)

Device Info:
App version: 2.5.24-PRE
App version code: 383
Android build version: eng.vishwa.20210122.113105
Android release version: 10
Android SDK version: 29
Android build ID: rr_violet-userdebug 10 QQ3A.200905.001 eng.vishwa.20210122.113105 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: violet
Device model: Redmi Note 7 Pro
Device product name: violet
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
```

**Comment by MuntashirAkon** [comment]
Set mode to `auto` and try again.

**Comment by Genxster1998** [comment]
@MuntashirAkon it was auto already at first attempt .

**Comment by MuntashirAkon** [comment]
Was it a clean install or did you restart your device after updating the app?

**Comment by Genxster1998** [comment]
@MuntashirAkon it was update ,but I again reinstalled fresh yet same result

**Comment by MuntashirAkon** [comment]
Restart is a must after an update.

**Comment by Genxster1998** [comment]
@MuntashirAkon problem is , it won't work if it is not running in background if I select an app from explorer to view on app manager

**Comment by Genxster1998** [comment]
And gives could not get package info toast message

**Comment by Genxster1998** [comment]
I am out of clue , on first launch after reinstalling,everything works but on second launch after force stopping it and relaunching , I can't able to view apk from file manager .

**Comment by Genxster1998** [comment]
And it happens onwards all launches.

**Comment by Genxster1998** [comment]
First it give message about initialisation but at last could not get package info toast

**Comment by MuntashirAkon** [comment]
Parsing package often fails due to a cache bug present in the Android's PackageManager. I'm working on a fix but this will take some time as I'd have to rewrite the entire package manager. But your issue is either related to MiXplorer or MIUI. Try using another file manager or disable MIUI optimization to see what happens.

**Comment by Genxster1998** [comment]
@MuntashirAkon I have other file managers too but  it results same .It works fine on 2.5.21 and 2.5.22 version .

**Comment by MuntashirAkon** [comment]
OK. Uninstall App Manager, restart your device, install it again. After that, try to open an APK from the file manager to see what happen and be sure to take logs using logcat at the same time.

**Comment by Genxster1998** [comment]
@MuntashirAkon https://del.dog/ugrimimofu.go

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon https://del.dog/ugrimimofu.go

Without any filters. It missed all the important logs. Install a debug build if possible as they are more helpful.

**Comment by Genxster1998** [comment]
@MuntashirAkon okay

**Comment by Genxster1998** [comment]
This is from latest debug version , I still can't upload full logcat due to some privacy issues 
https://del.dog/wymapifylo

**Comment by MuntashirAkon** [comment]
> I still can't upload full logcat due to some privacy issues

Send via email. The logs still don't contain any useful logs. Most logs are printed in a context different than App Manager's own. So, they are filtered out if you only grab logs for the app.

**Comment by gnuhead-chieb** [comment]
@Genxster1998
> It works fine on 2.5.21 and 2.5.22 version .

Not working on 2.5.23?
Try these debug builds and check if these build work or not


#780 and #769
https://github.com/MuntashirAkon/AppManager/suites/1854311875/artifacts/35990737

https://github.com/MuntashirAkon/AppManager/suites/1845531361/artifacts/35740263

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
