### ISSUE TITLE
Backup process keeps on going forever for some specific apps (if the app was launched at least once)

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#345]
All settings default, except volume changed to ExtSDcard.

Log sent via TG.

**Comment by Cyberavater** [comment]
It seems it's really app-specific. AM is backing up other apps perfectly instead of just that app. App sent via TG (If you wanna investigate)

**Comment by MuntashirAkon** [comment]
Will do. Thanks.

**Comment by MuntashirAkon** [comment]
The APK backed up perfectly on my device. Perhaps sharing steps to reproduce the error using the latest debug build would help.

**Comment by Cyberavater** [comment]
> The APK backed up perfectly on my device. Perhaps sharing steps to reproduce the error using the latest debug build would help.

To reproduce this issue, you need to launch the app at least once, I confirmed it right now.
Reopening issue with correct OP.

**Comment by MuntashirAkon** [comment]
This should be the case for all apps with KeyStore, I believe.

**Comment by Cyberavater** [comment]
But the app is not showing any KeyStore flag. Also, even if it was KeyStore why should it keep going? I've got the KeyStore option enabled.

> which flags were used during the backup and during restore?

All except "APK only", "Rules", "Backup multiples"

**Comment by MuntashirAkon** [comment]
> Also, even if it was KeyStore why should it keep going?

No idea. It shouldn't just stuck there. I've to check.

**Comment by MuntashirAkon** [comment]
Yeah, I've checked other apps with KeyStore, they've also hanged forever.

**Comment by MuntashirAkon** [comment]
Signal, Threema were exceptions, however.

**Comment by MuntashirAkon** [comment]
Found the underlying issue. It was something to do with the file types.

**Comment by MuntashirAkon** [comment]
Fixed in 06f729d3
