### ISSUE TITLE
not working on LineageOS 18.1

### ISSUE THREAD

**Issue by fwrg3r44r4** [MuntashirAkon/AppManager#352]
**Describe the bug**
Not working on LineageOS 18.1

**To Reproduce**
1. Install LineageOS 18.1
2. Install AppManager
3. Open Appmanager
4. Nothing happens.

**Expected behavior**
Nothing happens. Black screen.

**Screenshots**
Imagine a black screen.

**Crash logs**
No crashes.

**Device info**
 - Device: Pixel
 - OS Version: LineageOS 18.1
 - App Manager Version: 2.5.20
 - Mode: root/adb/no-root

**Additional context**
You're breathtaking! Thanks for this beautiful app.

**Comment by MuntashirAkon** [comment]
Was it fixed?
