### ISSUE TITLE
Explore and decompress APK files

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#36]
### Strongly related to #6 

A feature that might be useful would be the ability to explore and decompress APK files to a selected directory

**Comment by MuntashirAkon** [comment]
> ### Strongly related to #6
> A feature that might be useful would be the ability to explore and decompress APK files to a selected directory

Yes, once I clear all the queue, I'll give a hand on Smali.

**Comment by MuntashirAkon** [comment]
@Atrate when you mean explore and extract apk files, do you mean just unzipping the zip file or decompile the Manifest, classes.dex and all?

**Comment by Atrate** [comment]
Decompile, like [ApkTool](https://github.com/iBotPeaches/Apktool)

**Comment by MuntashirAkon** [comment]
> Decompile, like [ApkTool](https://github.com/iBotPeaches/Apktool)

What is the exact benefit of such decompilation if you can't compile them on Android? Apktool, the desktop app (jadx, I believe can convert from smali to java code as well), can both decompile and recompile an apk file.

**Comment by Atrate** [comment]
> What is the exact benefit of such decompilation if you can't compile them on Android?
To be completely honest, I do not actually know

**Comment by MuntashirAkon** [comment]
Will be implemented as part of #138.
