### ISSUE TITLE
Backup command seems not to be available

### ISSUE THREAD

**Issue by jmozmoz** [MuntashirAkon/AppManager#362]
**Backup**
According to the [documentation](https://muntashirakon.github.io/AppManager/guide/backup-restore.html#location) the backup command should be available from the page of each single app. Backup Manager is started with super user rights (by Magisk).

**Describe your problem(s)**
No backup command seems to be available. Also not on the page with the list of all apps.

**Additional contexts**
Using version v2.5.20.

**Comment by MuntashirAkon** [comment]
Backup/restore is yet not available in the stable releases. Wait for the next stable release which will be available after 26 April.
