### ISSUE TITLE
Quick Setting

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#364]
**Is your feature request related to a problem? Please describe.**
Yes Example You Using App Like Material Notifications Shade Some Tile Is Unable to toggle with some reason 

**Describe the solution you'd like**
Add Quick Setting Feature

**Describe alternatives you've considered**

**Additional context**
Quick Feature:
1. Toggle Wifi And Data
2. Toggle Airplane Mode
3. Toggle Night Mode
4. Toggle Eye Comfort
And Much More (Welp To Make Those Feature Work You Need To Grant WRITE_SECURE_SETTING First)

**Comment by MuntashirAkon** [comment]
Not possible. App Manager only manages **apps**.

**Comment by NSTAdventure** [comment]
> Not possible. App Manager only manages **apps**.

wait do not close this yet what i mean is you add this feature to your app 

so we need open the app to use quick setting 


no need to add quick tiles feature 🙏

**Comment by MuntashirAkon** [comment]
Again, AM manages Android apps, not its settings.
