### ISSUE TITLE
1 Click Deny App Ops

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#365]
**Is your feature request related to a problem? Please describe.**
I got annoyed when you click block dangerous permission because they ignore instead of deny

**Describe the solution you'd like**
deny it instead of ignore

**Describe alternatives you've considered**
Add new function like ignore dangerous app ops to ignore all dangerous permission

and add deny dangerous App Ops To Deny Them

**Additional context**

**Comment by MuntashirAkon** [comment]
In 1-click ops, you have all the available options.

![1-ClickOps - AppOps](https://user-images.githubusercontent.com/8176128/114288588-3087ac80-9a93-11eb-8e30-f5a4f213e160.png)

**Comment by NSTAdventure** [comment]
> In 1-click ops, you have all the available options.
> 
> ![1-ClickOps - AppOps](https://user-images.githubusercontent.com/8176128/114288588-3087ac80-9a93-11eb-8e30-f5a4f213e160.png)

what i mean if you open app ops tab and you click  block dangerous permission they will deny them instead of ignore :)

**Comment by MuntashirAkon** [comment]
> what i mean if you open app ops tab and you click block dangerous permission they will deny them instead of ignore :)

No, they are ignored, not denied. Check the app ops mode after denying them. You are possibly implying the reverse, in this case, yes, they are ignored because that's the standard way to denying a permission. If you need to use `MODE_ERRORED` AKA deny, do that manually by long clicking on each app op associated with the dangerous permission.

**Comment by NSTAdventure** [comment]
> > what i mean if you open app ops tab and you click block dangerous permission they will deny them instead of ignore :)
> 
> No, they are ignored, not denied. Check the app ops mode after denying them. You are possibly implying the reverse, in this case, yes, they are ignored because that's the standard way to denying a permission. If you need to use `MODE_ERRORED` AKA deny, do that manually by long clicking on each app op associated with the dangerous permission.

Aw man but i t take long time :(
