### ISSUE TITLE
UI: "Disable" icon stands out due to it being red

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#37]
The "disable" icon has a different style and stands out — all icons are coloured orange-ish (accent colour) while "disable" is red.

App version: 2.5.7

![Screenshot](https://i.imgur.com/YPETcC9.jpg)

**Comment by MuntashirAkon** [comment]
> The "disable" icon has a different style and stands out — all icons are coloured orange-ish (accent colour) while "disable" is red.

Should I change it to accent colour as well? I thought it looks good in this way?

**Comment by Atrate** [comment]
I guess we should wait and see what other people think

**Comment by UltraBlackLinux** [comment]
I like the red disable button, but it isnt very dangerous do disable an app so propably change the colors. Id make the uninstall button red.
