### ISSUE TITLE
Allow restoring backups made by third-party apps

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#371]
**OAndBackup** was the best open source backup manager for Android and used by many people (including myself). Since I have older backups (and many others might as well), I find it necessary to support restoring backups made by OAndBackup backups. (Unfortunately, we can't support **OAndBackupX** since it is not yet stable.)

Although I don't like closed source apps, **Titanium Backup** is a widely used app, even by those who dislike closed source apps. So, to promote open source software in lieu of the closed source ones, I've decided to support restoring backups from Titanium Backup too. But this requires further investigation as I've never used it in my life.

Checklist:
- [x] OAndBackup
- [x] Titanium Backup
- [x] Swift Backup
- [ ] 3C Toolbox / 3C App Manager

**Comment by MuntashirAkon** [comment]
**OAndBackup**

Like App Manager, OAB uses individual folders for storing backups named after the package name. Inside this folder, there is a `<package-name>.log` file which stores a json file consisting of the following items:
- `label`: App label
- `packageName`
- `versionName`
- `sourceDir`: Location to the **base.apk** file
- `dataDir`: Internal data directory
- `lastBackupMillis`: Backup time
- `versionCode`
- `isEncrypted`: Whether the backup is encrypted using OpenPGP. It doesn't store key id so it's up to the user to select the correct key in order to decrypt the backups.
- `isSystem`: Whether the app is a system app (doesn't matter much for us)
- `backupMode`
    * `0`: Unset
    * `1`: Backup only the base.apk file
    * `2`: Backup only the internal data folder
    * `3`: Backup both the base.apk file and the internal data folder

The base.apk file is stored as is within the folder. So, we'll just have to decrypt it (if encryption is used) and install it.

Restoring data is slightly complicated:
1. Internal data: Internal data folder is stored in `lastPathComponent(dataDir).zip` file. The folder have to extracted to `/data/user/<id>/` instead of `/data/user/<id>/<package-name>` since it also contains the package name.
2. External folder: External data folder is stored in `external_files/lastPathComponent(dataDir).zip` file. Extraction is similar to above.

**NOTE:**
* Naturally, we won't allow restoring special backups.
* Backup location must be in the same storage where App Manager folder is located.
* Backup location must be the root directory (e.g. /sdcard/oandbackups). If the user has configured custom location, they must move the folder in the root of the storage.

**Comment by MuntashirAkon** [comment]
**Titanium Backup**

TB stores metadata in a file with `properties` extension and formatting. The keys are given below:
- `sys_ro.product.model`
- `app_is_forward_locked`
- `has_prefsdata`
- `app_version_name`
- `sys_ro.build.date.utc`
- `has_prefsdata_jpu`
- `app_apk_codec` (GZIP and BZIP2)
- `app_version_code`
- `app_label`
- `app_gui_icon`
- `sys_ro.build.version.release`
- `has_external_data`
- `sys_ro.serialno`
- `has_dbdata`
- `app_apk_md5`
- `app_is_system`
- `generation`
- `sys_ro.build.decription`
- `app_apk_location`
- `app_gui_label`

The metadata file and the data folder backup uses the same file name (i.e. `<package-name>-<YYYYMMDD-HHMMSS`) but with different extensions (data backups have `tar` extension with either `gz` or`bz2` based on configuration). The APK file has `<package-name>-<app_apk_md5>.apk` (with either `gz` or `bz2` based on configuration).

The APK is only compressed, so all we have to do is uncompress it and install it.

Restoring data is a bit complicated (more complicated than OAB) since both internal and external data are stored in the same file.
1. Data are archived using tar (this is also what we do, so it doesn't matter much)
2. The folders inside has `/data/data` prefix. Then,
    * Internal folder has `<package-name>/./` prefix (presumably because it was generated using busybox tar)
    * External folder has `.external.<package-name/./` prefix.

**NOTE:**
* No support LZO compression (you shouldn't use it anyway)
* No support for encrypted backups since they don't allow exporting the RSA and/or the AES keys.
* The requirements about backup location described in the previous comment applies here too. In this case, the folder name is `TitaniumBackup`.

**Comment by Cyberavater** [comment]
While you're at it, what about adding support for SB too? I myself am a banned user there (for piracy and to use that app you need to be not banned) and there should be countless other fools like me, so it should be more helpful?

**Comment by MuntashirAkon** [comment]
> what about adding support for SB too?

I don't know anything about SB at all. Someone told me that it uses a proprietary format for backups. I can't use the app because it doesn't work without a Google account. Without knowing what features it offers I can't do anything.

**Comment by Cyberavater** [comment]
I can send you an unencrypted backed-up app and you check if it's feasible for you. I think that you can easily add support for it for the most part(as one can manually do it with ZArchiver), except for the component that resembles "Extras" of AM since it's encrypted.

**Comment by MuntashirAkon** [comment]
**Swift Backup**

All relevant files starts with package names.
- Metadata files are stored in an `xml` file which seems to be a binary XML file (not sure how to read it yet)
- `base.apk` is renamed as `<package-name>.app`
- Splits are zipped together in a file with `splits` extension
- OBB folder is zipped and stored in the `exp` file (root directory is the package name)
- Internal and external data folders are zipped separately in `dat` and `extdat` files respectively (root directory is the package name)

**NOTE**
- The information are gather from the files provided by @Cyberavater, I haven't checked them myself
- I don't know the exact location of the files relative to the storage
- Since I haven't found a way to read the XML file, support for SB backups will be limited.

**Comment by Cyberavater** [comment]
> I don't know the exact location of the files relative to the storage

/storage/emulated/0/SwiftBackup [Further depth is given in the file that I shared]

> Since I haven't found a way to read the XML file, support for SB backups will be limited.

AFAIK, you can even read it. The required key is stored in his firebase, upon logging in, it gives that key, at least that's what I heard (from the dev?), of course, I could be all wrong and probably mixed up with something else. https://swiftapps.org/faq#whygoogle

**Comment by MuntashirAkon** [comment]
Targeted v2.7.0 instead of v2.6.0 due to lack of time.

**Comment by bege10** [comment]
I was disappointed by TB and never got an answer to sent issues, other users reported similar experience. That's why I changed to 3C All-In-One Toolbox ccc71.at.free which includes 3C App Manager ccc71.at.am (both in Play Store). Backups are not encrypted.

**Comment by MuntashirAkon** [comment]
@bege10: I cannot add support for 3C Toolbox unless you provide me some background on how backup works there since I've never used the app. In any case, so far as I know 3C Toolbox allows backing up custom folders which means this feature can't be implemented in AM until #360 is fixed.

**Comment by bege10** [comment]
Restoring the backups of 3C Toolbox/3C App Manager would be helpful especially when setting up a new ROM on a phone that is ungoogled. Aurora Store is often unreliable and so it is not easy to install 3C Toolbox in the beginning.

Attached you find a sample backup. (not all mentioned files/folders are in it)

The backups' folder tree looks like this:
{base folder set in app}
_{packet name}
__{version}
___data
____{phone name set in app}
_____{backup date in seconds}

The {version} folder contains the APKs (single or split). (Even it there are split APKs from different platforms in the same folder 3C Toolbox selects the correct ones for the respective phone.)
info.txt contains among others the /data/apps folder. But one can save backups of several phones in the same folder (I do this by syncing the backups) . So one can restore the backup from one phone to another phone as long as they are compatible and the 3C apps restore to the correct folder even if they are different on the different phones.

The {backup date in seconds} folder contains the app data:
{packet name}.zip goes to /data/data/{packet name}
extra_data.zip goes to storage/emulated/0/Android/data/{packet name}
extra_secondary_data.zip goes to ext._SD/Android/data/{packet name}

$.zip contains one optional additional user defined folder from storage/emulated/0/
This may be the custom folder you mentioned. E.g. 3C Toolbox and Tasker have an additional folder each on storage/emulated/0/. But these folders are not necessary to restore the apps, they will be created by the apps on first start.
E.g. Tasker data backups in that folder I backup separately.
So I think that AM could provide the ability to restore these backups even without the ability to restore the additional folder.

[com.bdroid.audiomediaconverter.zip](https://github.com/MuntashirAkon/AppManager/files/6543605/com.bdroid.audiomediaconverter.zip)

The developer can be contacted via https://forum.xda-developers.com/t/app-4-0-3c-all-in-one-toolbox.2942186/ or the apps which are free with in-app purchase.

**Comment by MuntashirAkon** [comment]
> Restoring the backups of 3C Toolbox/3C App Manager would be helpful especially when setting up a new ROM on a phone that is ungoogled. Aurora Store is often unreliable and so it is not easy to install 3C Toolbox in the beginning.

We won't be restoring backups directly from any non-free apps such as TB, SB or 3C Toolbox. App Manager will only provide an option to import them (which you can restore on App Manager). This is essentially a one-way process, specifically provided to the users who're migrating from the said apps (along with OAndBackup which, unfortunately, has since been discontinued).

> The backups' folder tree looks like this:

Thanks for your descriptive comment. However, you forgot to mention where the backup files are located. For instance, the backup location of TB is `/storage/emulated/<user-id>/TitaniumBackup`.

> The {backup date in seconds} folder contains the app data:
> {packet name}.zip goes to /data/data/{packet name}
> extra_data.zip goes to storage/emulated/0/Android/data/{packet name}
> extra_secondary_data.zip goes to ext._SD/Android/data/{packet name}
> 
> $.zip contains one optional additional user defined folder from storage/emulated/0/
> This may be the custom folder you mentioned. E.g. 3C Toolbox and Tasker have an additional folder each on storage/emulated/0/. But these folders are not necessary to restore the apps, they will be created by the apps on first start.
> E.g. Tasker data backups in that folder I backup separately.

After I implement the feature, I would need to test if they're working as expected. So, I would suggest you to take a backup that includes all of these things (like what @Cyberavater did). Current sample only includes the internal data and APK files.

> The developer can be contacted via https://forum.xda-developers.com/t/app-4-0-3c-all-in-one-toolbox.2942186/ or the apps which are free with in-app purchase.

Thanks for the info. However, if you know me, I don't use XDA nor have any plans on polluting my phone with a non-free app. But it doesn't matter if you're going to supply all the resources I need on 3C Toolbox.

**Comment by bege10** [comment]
> We won't be restoring backups directly from any non-free apps such as TB, SB or 3C Toolbox. App Manager will only provide an option to import them (which you can restore on App Manager). This is essentially a one-way process, specifically provided to the users who're migrating from the said apps (along with OAndBackup which, unfortunately, has since been discontinued).

I am fine with that. I have the 3C Toolbox, so I don't need this feature on a regular basis, but installing apps on a new system this way will be helpful.
 
> Thanks for your descriptive comment. However, you forgot to mention where the backup files are located. 

As posted the base folder for all backups is user defined (on internal or external SD) in the app.

> After I implement the feature, I would need to test if they're working as expected. So, I would suggest you to take a backup that includes all of these things 

I have few apps with all these data and they contain private data. But I will provide a backup with test data.

**Comment by bege10** [comment]
[com.bdroid.audiomediaconverter.zip](https://github.com/MuntashirAkon/AppManager/files/6556896/com.bdroid.audiomediaconverter.zip)

**Comment by MuntashirAkon** [comment]
**3C Toolbox** or **3C App Manager**

The backup system isn't very well-designed similar to most other systems. However, unlike others, its backup system is hybrid and supports multiple backups based on app version and number of devices (if they are synchronised).

Similar to App Manager, the main folder for an app is the package name. Oddly enough, child folders have the `versionCode_versionName` format (the **versionName** section being unreliable due to file system limitations). Each child folder contains the following items:

- The APK file in `<package-name>.apk` format
- Icon for the APK file: `icon.png`
- `info.txt` contains 3 lines: App label, app location and version info in `versionCode_versionName` format. It's useless for us as we have to parse the APK file.
- Splits are stored as is (simply copied from the source directory)
- `tags.txt`: Whatever it is, it's useless for us
- A `data` folder containing the app data

The child folders of the `data` folder have arbitrary names "the device name" set by the user. The child folders of each device folder have the backup time in milliseconds, and they may contain the following zip files (therefore, it doesn't preserve any file permissions):

- `<package-name>.zip`: Contains the contents of `/data/user/0/<package-name>` (root directory is the package name)
- `extra_data.zip`: Contains the contents of the internal storage i.e. `/storage/emulated/0/Android/data/<package-name>` (root directory is the package name)
- `extra_secondary_data.zip`: Contains the contents of the external storage. Due to our design, we can only backup this folder if the external storage is present (root directory is the package name)
- `$.zip`: Contains the contents of a folder from `/storage/emulated/0/`. Root directory is not guaranteed, therefore, it can only be used when #360 has been fixed.

**NOTE**
- Information are gathered from the files provided by @bege10
- Location of the backups are user defined
- Three layers of multiple backups: Version, device and backup time.

**Comment by bege10** [comment]
>     * `$.zip`: Contains the contents of a folder from `/storage/emulated/0/`. Root directory is not guaranteed, therefore, it can only be used when #360 has been fixed.

I attached a zip file that contains a user defined subfolder from internal SD. I didn't know that the name of the archive changes with the subfolders.
$.zip = base folder is storage/emulated/0
$audiomediaconverter.zip = base folder is storage/emulated/0/audiomediaconverter
$audiomediaconverter$files1.zip = base folder is storage/emulated/0/audiomediaconverter/files1 (as in attached archive) .
[$audiomediaconverter$files1.zip](https://github.com/MuntashirAkon/AppManager/files/6565274/audiomediaconverter.files1.zip)

**Comment by bege10** [comment]
> The child folders of each device folder have the backup time in milliseconds, and they may contain the following zip files (therefore, it doesn't preserve any file permissions):

The <package-name>.zip file contains an at.cfg file which contains the file permissions.

**Comment by MuntashirAkon** [comment]
@bege10: While I was testing OAndBackup, I've realised that I would need a number of test data in order to ensure that all aspects of a backup are tested properly. So, a single test backup won't be enough. I'll inform you my requirements along with the APK files that needs to be tested if I start working on it.

**Comment by MuntashirAkon** [comment]
> The `<package-name>.zip `file contains an at.cfg file which contains the file permissions.

Wow. That's a crazy workaround. They could've just moved to `tar` and forgotten the idea of permissions.

**Comment by MuntashirAkon** [comment]
@Cyberavater: To test Swift Backup, I need the following backups (you have to open the app before taking a backup):

1. APK only: https://f-droid.org/packages/ademar.textlauncher/
2. Apk + Data: https://f-droid.org/en/packages/org.billthefarmer.editor/
3. Apk + Data + External Data: https://f-droid.org/en/packages/dnsfilter.android/ 
4. Data only: https://f-droid.org/en/packages/ca.cmetcalfe.locationshare/
5. APK + Splits: [sample.apks.zip](https://github.com/MuntashirAkon/AppManager/files/6565933/sample.apks.zip) (remove `.zip` and install with AM)
6. APK + OBB:  [sample.apk.zip](https://github.com/MuntashirAkon/AppManager/files/6565948/sample.apk.zip) & [test-assets.obb.zip](https://github.com/MuntashirAkon/AppManager/files/6565949/test-assets.obb.zip) (remove `.zip` extension from both files and put the OBB at `/sdcard/Android/obb/com.test.app`)

**Comment by MuntashirAkon** [comment]
Things have become a little too complicated with Swift Backup. It seems the backups provided by @Cyberavater do not match with the one provided by the other user.

**Differences**

Subject | @Cyberavater's | Other's
--------------| ------- | ----
`.exp` (OBB files) | ZIP | TAR
`.dat` and `extdat` (data files) | ZIP | TAR.ZIP

However, in the header section of the new data files, there's a comment: `{"_backupFormat":2}` which is likely used to distinguish between the two.

**Comment by Cyberavater** [comment]
It is because the files provided by me are from version 3.2.x (and its structure should be the same till 3.3.x). Currently, the dev might've found that the best way to backup with permission is .tar so he migrated to tar (the current version is 3.5.x this might've been introduced in 3.4.x).

**Comment by MuntashirAkon** [comment]
> It is because the files provided by me are from version 3.2.x (and its structure should be the same till 3.3.x). Currently, the dev might've found that the best way to backup with permission is .tar so he migrated to tar (the current version is 3.5.x this might've been introduced in 3.4.x).

Yeah. Looks like a compatibility nightmare. I've already added support for your versions but the newer versions seem different, and I'm not sure whether I'll continue to support SB (similar to OABX). I don't like to pay for the poor design choices of others. (The current one also has several problems, so I guess they'll make some more changes in the coming future.)

**Comment by MuntashirAkon** [comment]
For now, I added OAndBackup and Titanium Backup since these services have been discontinued for quite some time. Since other backup services are still active, we need to carry out some study to ensure that the analysis that we've done above are actually correct. If, for instance, there are compatibility issues with certain backups (such as what we've seen earlier for SB), we have either to address them properly or ignore them altogether. But even if we decided to support them, there wouldn't be any guarantee that the future version of the software would also be supported. This is also considered a burden because we could've spent our precious time on doing some good features such as the routine operations which is currently the most essential feature to implement. Therefore, we will only consider the other software iff we see popular demands for them.

The issue will be kept open for future references.

**Comment by Cyberavater** [comment]
> Yeah. Looks like a compatibility nightmare. I've already added support for your versions.

Can you add this one? I mean, since you already spent time writing the code, can you implement this, please? It should help me much and the most banned users are from version 3.2.x (if they are holding to their backup data that is), you can add a note that it'll work up to 3.2.x.

**Comment by MuntashirAkon** [comment]
> Can you add this one? I mean, since you already spent time writing the code, can you implement this, please? It should help me much and the most banned users are from version 3.2.x (if they are holding to their backup data that is), you can add a note that it'll work up to 3.2.x.

Sure! But I need tests from 3.2.x as [outlined above](https://github.com/MuntashirAkon/AppManager/issues/371#issuecomment-850966189) to ensure if the import actually works. Somehow manage this and I'll add support for 3.2.x in no time (since I have the implementation ready already). I've got tests from 3.5.x which is completely different from yours, and I'm not going support them for the reasons mentioned above.

**Comment by Cyberavater** [comment]
> Sure! But I need tests from 3.2.x as outlined above to ensure if the import actually works. Somehow manage this and I'll add support for 3.2.x in no time (since I have the implementation ready already). 

The thing is that to do more tests using SB would mean I would need to open another account there, (which I'm not interested in, that's why I came back to request you again).
If it's possible can you implement it as is in debug (or a different branch for me?), and let me inform if it works?

> I've got tests from 3.5.x which is completely different from yours, and I'm not going support them for the reasons mentioned above.

Fully understandable, no need to write more code for others' continuously changing apps, I just asked for the part that already been written.

**Comment by MuntashirAkon** [comment]
> The thing is that to do more tests using SB would mean I would need to open another account there, (which I'm not interested in, that's why I came back to request you again).
>
> If it's possible can you implement it as is in debug (or a different branch for me?), and let me inform if it works?

You can create a burner account for extracting those data. As you're aware, I'm not going to spend much time with this as this feature will be used by a handful of people. If I have the required data, I can implement this in a very short time. Implementing through a trial and error process that you're proposing takes a lot of time, and in the end, the feature may still remain incomplete. It's much easier to just extract the said data with a burner account and start working on it.

Apart from that I could made the tests automated which would ensure that the feature isn't broken in a future release (which you frequently see in other places where there's no way to write automated tests).

**Comment by Cyberavater** [comment]
I've sent your requested files via TG.

P.S. if possible please let the user select the path to SwiftBackup, as I've moved the large folder to ExtSdCard (and currently don't have the required space in local storage).

**Comment by Cyberavater** [comment]
> I can implement this in a very short time.

Just a friendly reminder, if possible please check here.

**Comment by MuntashirAkon** [comment]
> Just a friendly reminder, if possible please check here.

I've already had SB support on another local git branch but the storage framework in the main repo has changed a lot since then which made it a bit complicated to handle, especially with custom directory.

**Comment by MuntashirAkon** [comment]
@Cyberavater Can you specifically tell me the version range of SB which can be imported in AM? It could be useful for documentation.

**Comment by Cyberavater** [comment]
> @Cyberavater Can you specifically tell me the version range of SB which can be imported in AM? It could be useful for documentation.

The settings only show OAB and TB. 
The upper range is 3.2.x and the lower range may be 3.0.0 (you can't test beyond that because of their TOS (i.e. when trying to logging in using <3 will be banned).

**Comment by MuntashirAkon** [comment]
> The settings only show OAB and TB.

UI isn't implemented yet. Only the logic has been implemented and the tests are passing.

**Comment by MuntashirAkon** [comment]
Implemented in 30aea570.
