### ISSUE TITLE
Not showing any apps after initializing

### ISSUE THREAD

**Issue by usamaiqbal1177** [MuntashirAkon/AppManager#373]
**Describe the bug**
After initializing, it doesn't show any app on pre release app manager. However, debug version of app Manger doesn't have this issue. 

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: [e.g. POCO X3 NFC]
 - OS Version: [e.g. Android 11 (Octavi OS]
 - App Manager Version: [PRE. v2.5.24]
 - Mode: root/adb/no-root

![Screenshot_20210413-155526_AM_Pre-release](https://user-images.githubusercontent.com/58624914/114573646-fb957880-9c91-11eb-9c9f-b2b3bb1986ba.png)
[appmgr.txt](https://github.com/MuntashirAkon/AppManager/files/6304626/appmgr.txt)

**Comment by MuntashirAkon** [comment]
Are the logs taken from the pre-release? They are suggesting that the app is in debug mode and everything's working correctly.

**Comment by usamaiqbal1177** [comment]
> Are the logs taken from the pre-release? They are suggesting that the app is in debug mode and everything's working correctly.

Yes. Taken from pre-release. Line number 141 seems useful. Pointed out by Masa Peter in the tg group.

**Comment by MuntashirAkon** [comment]
Related issue: https://github.com/tiann/FreeReflection/issues/33

**Comment by MuntashirAkon** [comment]
Fixed in e4e16ded.

**Comment by MuntashirAkon** [comment]
I've replaced the previous solution with another in f34f35ee. Could you please verify that it's also working on A11?
