### ISSUE TITLE
Action to re-install an uninstalled system app

### ISSUE THREAD

**Issue by MPeti1** [MuntashirAkon/AppManager#374]
**Is your feature request related to a problem? Please describe.**
When I go to delete some unused apps, it's always possible that when cleaning system apps, I break the system, or an important part of it.  
An example is MIUI's `com.miui.home.launcher.assistant`. Removing it causes the MIUI launcher to crash at start, making my phone hard to use. Found out that App Manager uses the `pm uninstall --user [userid] [packagename]` command for uninstallation, and then that this can be reversed with `pm install -r --user [userid] $(pm dump [packagename] | awk '/path/{ print $2 }')`.

**Describe the solution you'd like**
A 1 click op to run the above mentioned command for a given packagename.

**Describe alternatives you've considered**
An action similar to launch, disable, uninstall, etc on the AppDetailsActivity, but this would first need a modification to be able to open apps that are not installed, so a different solution might be better.

**Additional context**
AM can already list uninstalled apps if I set the filter appropriately (I think not all though, but this might be because of my other problem), so this might be incorporated into the feature.

**Comment by MuntashirAkon** [comment]
> Found out that App Manager uses the `pm uninstall --user [userid] [packagename]` command for uninstallation

AM no longer uses command line to install/uninstall/enable/disable/force stop apps. It uses Android's system APIs instead.

> AM can already list uninstalled apps if I set the filter appropriately

Yes, and if you click on any of them, the installer dialog will be displayed. The uninstalled apps are displayed by default provided you haven't modified the filters. So, I'm not sure what you're looking for here.

> I think not all though, but this might be because of my other problem

Yeah, this could be one of your device-specific issues. If you're running MIUI, I suggest you disable MIUI optimisation for AM.

**Comment by MPeti1** [comment]
> Yes, and if you click on any of them, the installer dialog will be displayed.

If I click on them, AM says "App not installed"

> If you're running MIUI, I suggest you disable MIUI optimisation for AM

Well, I can only disable it globally, and previously it have caused problems :/ an example is that it breaks the dialog for changing MIUI specific permissions of an app, and if I turn it back on and reboot the most of the things will still be broken

**Comment by MuntashirAkon** [comment]
> If I click on them, AM says "App not installed"

There are currently issues with updating the database. You have have to refresh 2-3 times before AM can detect that the app has been uninstalled.

> Well, I can only disable it globally, and previously it has caused problems :/ an example is that it breaks the dialog for changing MIUI specific permissions of an app, and if I turn it back on and reboot most of the things will still be broken

This greatly limits capabilities for MIUI users, I'm afraid. Probably switching to a better and usable ROM is a good idea.

**Comment by lshilshi** [comment]
> > If I click on them, AM says "App not installed"
> 
> There are currently issues with updating the database. You have have to refresh 2-3 times before AM can detect that the app has been uninstalled.

When operating on the component （block/apply rule etc）, 
AM often crash or returns to the main page with a toast message "App not installed".

**Comment by MPeti1** [comment]
> There are currently issues with updating the database. You have have to refresh 2-3 times before AM can detect that the app has been uninstalled.

Thank you, this made it work!

> This greatly limits capabilities for MIUI users, I'm afraid. Probably switching to a better and usable ROM is a good idea.

I was thinking of that, but there are a few limiting factors :/
- no whole-disk backup solutions that I trust (there was FlashFire, but with Magisk it does not work, and the backup mechanism of 
my custom recovery is also not really flawless)
- there's LOS for my device, but it's maintained by a 3rd party who is unknown to me (trustabiliy, other works in the field, etc). I think I would have the ability to build it on my computer, and I would love to deal with it, but I'm afraid it would take weeks at least to check the source diff to the main LOS version.
- also currently I have a few features on my system (due to using xMIUI) that I can't give up, and I'm afraid they're not available on an other ROM, and xMIUI can only make the required changes on the ROM that I currently use. I can only resolve this "I'm afraid this and that" if I can try out an other ROM without data loss, but without FlashFire that's either dualboot (a very painful thing on my phone, and I have already lost _a lot_ of data due to auto-full disk encryption), or a new phone, which I have been also planning for around 2-3 years now

**Comment by MuntashirAkon** [comment]
Closed via #430
