### ISSUE TITLE
Latest debug build stucks forever on app details section

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#375]
Video reproduce:

https://user-images.githubusercontent.com/41156994/115007352-68c72a80-9e99-11eb-9f8d-593b7aa02f05.mp4

This bug can be temporary fixed by clear AM data but recurrence soon.

Logcat:

[logcat_04-16-2021_18-44-20.txt](https://github.com/MuntashirAkon/AppManager/files/6324133/logcat_04-16-2021_18-44-20.txt)

P.S. I added trackers to ETIP.Plz update tracker signatures.

**Comment by MuntashirAkon** [comment]
Did you restart your phone after the updating AM?

**Comment by gnuhead-chieb** [comment]
It seems working after reboot my phone.Thank you for your advice :)
