### ISSUE TITLE
Not displayed "Storage & Cache" in debug builds.

### ISSUE THREAD

**Issue by tommynok** [MuntashirAkon/AppManager#376]
In debug versions of the AM not displayed "Storage & Cache", in the "App Info tab".
Unfortunately, I cannot specify a more specific version of the debug build in which this bug appeared.
All pre-releases do not have this problem (from 2.5.15 to 2.5.24 inclusive).
At the moment I can not provide more specific information, such as logs, etc.

Device Info:
App version: 2.6.0-1108-DEBUG
App version code: 384
Android build version: P1a42_S288_160721_ROW
Android release version: 6.0.1
Android SDK version: 23
Android build ID: P1a42_S288_160721_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: P1a42
Device model: Lenovo P1c58
Device product name: passion_row
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: ru-RU
In-App Language: auto
Mode: root

**Comment by tommynok** [comment]
Upd.
I've checked about 30 old debug builds.
It seems that the bug appeared in version 2.6.0-1055.

**Comment by MuntashirAkon** [comment]
Should be fixed in efa6ddc9. Can you check?

**Comment by tommynok** [comment]
> Should be fixed in [efa6ddc](https://github.com/MuntashirAkon/AppManager/commit/efa6ddc952eac3ab5ee52673104d675f347ba65c). Can you check?

Yes, now everything is ok. Thank you !
