### ISSUE TITLE
AM crash when importing rules from Blocker.

### ISSUE THREAD

**Issue by tommynok** [MuntashirAkon/AppManager#379]
AM crash when selecting a rules file that previously exported from Blocker.
[AM_log.txt](https://github.com/MuntashirAkon/AppManager/files/6338743/AM_log.txt)
[logcat.txt](https://github.com/MuntashirAkon/AppManager/files/6338744/logcat.txt)

**Comment by MuntashirAkon** [comment]
Fixed in f5800986. The import was successful in any case.
