### ISSUE TITLE
Trackers not detected

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#38]
I jusz downloaded this app (https://play.google.com/store/apps/details?id=com.cg.moneybuster) to play around with tracker patching a bit, and it seems like no trackers are getting detected at all... Even an exodus scan did nothing.
What is that?

**Comment by MuntashirAkon** [comment]
When you report such bugs, include device specifications, App Manager version, etc. It's working nicely on my side.

**Comment by MuntashirAkon** [comment]
Here's a screenshot from the latest stable build (v2.5.8):

![Screenshot_20200717-001031_App_Manager](https://user-images.githubusercontent.com/8176128/87707178-3d8b9f80-c790-11ea-9bf4-f0e1c3d7d9cd.png)

**Comment by MuntashirAkon** [comment]
Here's a sneak peek of the tracker activities from the latest unstable build (v2.5.9 build 304):

![Screenshot_20200717-001822_App_Manager](https://user-images.githubusercontent.com/8176128/87707810-40d35b00-c791-11ea-9c7c-367fa055a68d.png)

**Comment by UltraBlackLinux** [comment]
OOF. Im litterally stupid. I thought the trackers were highlighted red and I wondered why there were no, I used a different patcher before lol
