### ISSUE TITLE
Usage monitor and history

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#382]
Show an alerting notification when an app is using location, camera, microphone.
History would contain this usage record.

This feature is part of an app called App Ops: https://play.google.com/store/apps/details?id=rikka.appops&hl=en&gl=US
[Only added for reference, the app is closed soured, afaik.]

Also, if it's possible I'd request the dev to check this app's "Permissions View" listing if something similar can be implemented on AM too.

**Comment by MuntashirAkon** [comment]
Duplicate of #143
