### ISSUE TITLE
Right-to-left layout support

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#383]
AM has been translated into languages (such as Arabic and Farsi) which are written from right to left (RTL). The books written in these languages also start from end (when compared with English). Android also has support for RTL layout, and for these languages, RTL layout should be more suitable as the default LTR layout may not display everything properly (such as the App Info page). But I don't know if the users of these languages are familiar with RTL layout themselves (because not many apps actually support RTL layout).

**Comment by GooseTheDuck** [comment]
Based on the screenshots sent in the telegram channel, Yes I think its a better idea to make the app RTL for languages using Abjad writing systems (arabic, hebrew, ..)

**Comment by LeSnake04** [comment]
I am not Arabic, but I think its a good idea

I think the best solution is making it RTL for these languages by default, but make a option to make it LTR

**Comment by GooseTheDuck** [comment]
Making an option would be great but the problem is there is currently some ui problems in farsi ( arabic writing system)

**Comment by MuntashirAkon** [comment]
> Making an option would be great but the problem is there is currently some ui problems in the farsi ui

Such as? It would be very helpful if you can specify the issues so that I can look into it.

**Comment by LeSnake04** [comment]
The options I would give to the user:

- Language based (LTR unless Arabic and Farsi)
- Left to right
- Right to left

So everyone can use the layout he wants :)

**Comment by GooseTheDuck** [comment]
> > Making an option would be great but the problem is there is currently some ui problems in the farsi ui
> 
> Such as? It would be very helpful if you can specify the issues so that I can look into it.

Sorry but the issues were in the LTR not the RTL

The text that is supposed to be spread out on the sides is now centered,
English test is written on the right and the other on the left making it hard to read,
The 3 (٣)، and 5 (٥) look weird (idk know this language so it may be because of that)

![20210421_204520](https://user-images.githubusercontent.com/73031433/115598543-35462f00-a2e3-11eb-9e0f-8fc3e3cf7e82.jpg)

**Comment by MuntashirAkon** [comment]
> So everyone can use the layout he wants :)

If you try to use RTL layout for LTR languages, the layout will be distorted.

**Comment by MuntashirAkon** [comment]
@rex07: Any opinion?

**Comment by MuntashirAkon** [comment]
Implemented in e5a2c750.

By default the layout orientation is set to left to right, instead of language-default as most users are not familiar with right to left orientation.
