### ISSUE TITLE
Data Usage not show in android 7 and below

### ISSUE THREAD

**Issue by Nenirey** [MuntashirAkon/AppManager#389]
the app never display the Data Usage in android 7 and below, event with al permissions.

**Comment by MuntashirAkon** [comment]
@tommynok and @PookaMustard: can you confirm?

**Comment by Cyberavater** [comment]
I can confirm this.
SS from my A 7.1 virtual machine (root and usage access granted)
![unnamed (1)](https://user-images.githubusercontent.com/32187927/115723788-24102780-a3a2-11eb-9fdc-b4d20e82099b.jpg)

You can see that, it doesn't show how much data the Playstore used.

**Comment by MuntashirAkon** [comment]
> I can confirm this.

Virtual machines usually do not store data usage. This feature can also be disabled by the OEM. To verify this, try other third-party apps that can display data usage.

**Comment by Nenirey** [comment]
other apps can get the data usage from that 7.1 android virtual (tested), you can try with Datally from Google, the problem is the NetworkStats api that not work well in this android version, i see that you use the /data/ usage files in part of your code, you use it for some low versions?

**Comment by Cyberavater** [comment]
> other apps can get the data usage from that 7.1 android virtual (tested)

Can you link the app? Whatever app I tried is not showing me data usage (except for one, that asked to use their firewall).

**Comment by Cyberavater** [comment]
Luckily, I have checked from an A-7.12 LOS-based android phone from my friend's and I can see the data usage there as expected.

**Comment by Cyberavater** [comment]
I've requested him a ss;
![unnamed (2)](https://user-images.githubusercontent.com/32187927/115734105-422e5580-a3ab-11eb-81c5-728c7f947c2f.jpg)

**Comment by Nenirey** [comment]
> > other apps can get the data usage from that 7.1 android virtual (tested)
> 
> Can you link the app? Whatever app I tried is not showing me data usage (except for one, that asked to use their firewall).

Datally is not in Google Play any more, google abandoned it, but i test with other app from Cuban local app store

**Comment by tommynok** [comment]
> @tommynok and @PookaMustard: can you confirm?

MM - statistics displayed correctly
LP - check tomorrow

**Comment by Nenirey** [comment]
> Luckily, I have checked from an A-7.1.2 LOS-based android phone from my friend's and I can see the data usage there as expected, in AM's usage page.

maybe the problem is below 7.1 version

**Comment by MuntashirAkon** [comment]
> Datally is not in Google Play any more, google abandoned it, but i test with other app from Cuban local app store

Isn't Datally a VPN app? It is supposed to save data by running a VPN so that it can monitor the traffic. Naturally, since it can monitor data traffic AKA packets, it can obviously calculate the data usage from there.

**Comment by MuntashirAkon** [comment]
> LP - check tomorrow

It won't work on Lollipop because the API is introduced in Android M. But in Lollipop, the **data usage** section in the App Info page should work as it is fetched using a different "hacky" method.

**Comment by Nenirey** [comment]
> > Datally is not in Google Play any more, google abandoned it, but i test with other app from Cuban local app store
> 
> Isn't Datally a VPN app? It is supposed to save data by running a VPN so that it can monitor the traffic. Naturally, since it can monitor data traffic AKA packets, it can obviously calculate the data usage from there.

yes but i not test with Datally, i use other app called 'Mis datos' a cuban app in a local app store that not use vpn, it only use the usage stats

**Comment by Nenirey** [comment]
> > LP - check tomorrow
> 
> It won't work on Lollipop because the API is introduced in Android M. But in Lollipop, the **data usage** section in the App Info page should work as it is fetched using a different "hacky" method.

red the data from /proc/uid_stat/ ?

**Comment by tommynok** [comment]
> > LP - check tomorrow
> 
> It won't work on Lollipop because the API is introduced in Android M. But in Lollipop, the **data usage** section in the App Info page should work as it is fetched using a different "hacky" method.
I urgently did research)
The LP shows statistics, but in a peculiar way.
**Today** - statistics are shown
**Yesterday** is empty
**Weekly** - the same data as **today**

**Comment by Nenirey** [comment]
> > > LP - check tomorrow
> > 
> > 
> > It won't work on Lollipop because the API is introduced in Android M. But in Lollipop, the **data usage** section in the App Info page should work as it is fetched using a different "hacky" method.
> > I urgently did research)
> > LP shows statistics, but in a peculiar way.
> > **Today** - statistics are shown
> > **Yesterday** - empty
> > **Weekly** - the same data as **today**

in LP is not use bucket that have the data storage by dates

**Comment by MuntashirAkon** [comment]
> red the data from /proc/uid_stat/ ?

Yes.

**Comment by PookaMustard** [comment]
I know I'm late, but

This is what I see on my Android 8.0.0 phone
![Screenshot_20210422-173521](https://user-images.githubusercontent.com/19552979/115742803-55342c00-a391-11eb-879b-0ca9c93beffe.jpg)

This is what I see on my Android 7.0 tablet.
![Screenshot_2021-04-22-17-35-38-200](https://user-images.githubusercontent.com/19552979/115742890-6846fc00-a391-11eb-95b1-e57b9e45936d.jpeg)

**Comment by Nenirey** [comment]
> I know I'm late, but
> 
> This is what I see on my Android 8.0.0 phone
> ![Screenshot_20210422-173521](https://user-images.githubusercontent.com/19552979/115742803-55342c00-a391-11eb-879b-0ca9c93beffe.jpg)
> 
> This is what I see on my Android 7.0 tablet.
> ![Screenshot_2021-04-22-17-35-38-200](https://user-images.githubusercontent.com/19552979/115742890-6846fc00-a391-11eb-95b1-e57b9e45936d.jpeg)
> 
> I tried transferring files through MiXplorer between both devices at over 100MBs but no immediate changes were noticed. Probably I need to wait a bit for Android app usage to update. Both were tasted on debug run 1150.

that is for wifi, i am talking about data mobile usage

**Comment by Nenirey** [comment]
> I've requested him a ss:
> ![unnamed (2)](https://user-images.githubusercontent.com/32187927/115734105-422e5580-a3ab-11eb-81c5-728c7f947c2f.jpg)

can you test on data mobile usage?

**Comment by Nenirey** [comment]
please make the tests for data mobile usage

**Comment by MuntashirAkon** [comment]
> that is for wifi, i am talking about data mobile usage

I don't think you were talking about mobile data usage before. Anyway, there's a chance that mobile data usage requires the `READ_PHONE_STATE` permission on old operating systems (similar to `ACCESS_NETWORK_STATE`).

**Comment by Nenirey** [comment]
> > that is for wifi, i am talking about data mobile usage
> 
> I don't think you were talking about mobile data usage before. Anyway, there's a chance that mobile data usage requires the `READ_PHONE_STATE` permission on old operating systems (similar to `ACCESS_NETWORK_STATE`).

sorry i forget mentioned it, the app not ask for grant this permissions?

**Comment by Nenirey** [comment]
but maybe that's the problem, the app never ask from the state phone permissions in android 7 and is not include in the androidmanifest

**Comment by MuntashirAkon** [comment]
> but maybe that's the problem, the app never ask from the state phone permissions in android 7 and is not include in the androidmanifest

Does the working app “Mis Datos” have this permission?

**Comment by Nenirey** [comment]
> > but maybe that's the problem, the app never ask from the state phone permissions in android 7 and is not include in the androidmanifest
> 
> Does the working app “Mis Datos” have this permission?

yes, in the androidmanifest and ask for it programmatically, but is an close source app, it's very hard find good open source app that manage the data use, this is the best option, good job.

**Comment by MuntashirAkon** [comment]
> yes, in the androidmanifest and ask for it programmatically

OK then, I'll add and ask this permission in Android <= 7 and > 5. Let's see if it works.

**Comment by MuntashirAkon** [comment]
> i am working in an app that use your function to get the data use and with android 8 and below not work event with the READ_PHONE_STATE permission granted, so i think that other thing is missing too

No, it should work. Wait for my implementation.

**Comment by MuntashirAkon** [comment]
Should be fixed in 1cba5120

**Comment by MuntashirAkon** [comment]
One thing I forgot to mention: My only device is an Android 10 smartphone. So, I would expect somebody to actually verify if this is working.

**Comment by Nenirey** [comment]
i confim that now it's work for android 5-7 and 9> but its not working in android 8 and 8.1

**Comment by MuntashirAkon** [comment]
No idea why it should not work on Android Oreo. Maybe the subscriber IDs are not returning correctly?

**Comment by Nenirey** [comment]
it's in only some devices, in oreo subscriber ids it's always null

**Comment by MuntashirAkon** [comment]
> it's in only some devices, in oreo subscriber ids it's always null

It would be better if you could share some logs as well as device info such as Android version, patch level, etc.

**Comment by JustAnUserLol** [comment]
> i confim that now it's work for android 5-7 and 9> but its not working in android 8 and 8.1

It's working in Android 8.1 for me.
