### ISSUE TITLE
[Locale]Distinguish word "signature" for each meaning

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#390]
I want use different translation of word "**signature**" for each meaning.
Tracker **signatures** -->トラッカーの**シグネチャ** or トラッカーの**定義リスト**

App's signature key --> アプリの**署名**鍵

**Comment by MuntashirAkon** [comment]
Fixed in 551a1fb8. If the name of the string containing the word "signature" has `app_signing` prefix/infix, it denotes that it's related to app signing rather than signatures/class names.

**Comment by gnuhead-chieb** [comment]
Thanks.!
By the way,I have a question about translation.
Where is used these strings Base backup(base_backup),Log report(subject_log_report),%1$s compressed(gz_bz2_compressed),and %1$s encrypted(pgp_aes_rsa_encrypted)?
