### ISSUE TITLE
"Share apk" failed

### ISSUE THREAD

**Issue by fucksafetynet** [MuntashirAkon/AppManager#393]
![Screenshot_20210423-071635184](https://user-images.githubusercontent.com/58792941/115796455-6b2f0480-a404-11eb-9674-ae0b2f1ca00d.jpg)
![Screenshot_20210423-071620_ShapeShift_Launcher](https://user-images.githubusercontent.com/58792941/115796465-6e29f500-a404-11eb-862d-03c53a0747b2.png)
Clicking on the share APK has no response, and found that there is a 10KB apk in Android/data/io.github.muntashirakon.AppManager.debug/cache

2.6.0-1153-DEBUG (384)

OS version: 11
Bootloader: unknown, VM: ART
Kernel: 4.4.267-Illium-EAS
Brand: Xiaomi, Model: MI 6X
Board: sdm660, Manufacturer: Xiaomi

This problem seems to exist in AM Debug v2.6.0 Run#1080+

**Comment by MuntashirAkon** [comment]
This is only applicable for bundled apps, I believe?

**Comment by tommynok** [comment]
I have the same AM behavior.
But it seems to me that this is not a bug.
The time that the phone spends for creating a backup of a split-application, and for sharing, is the same.

**Comment by MuntashirAkon** [comment]
Should be fixed in 81a04c89
