### ISSUE TITLE
Stop using Weblate for docs translation

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#398]
Docs string key setting is wrong that made string position goes wrong every resource update.

**Comment by MuntashirAkon** [comment]
Is there an active issue about it in the Weblate repo? If not, open an issue there too.

----

We've moved from Crowdin because it doesn't offer much control. Probably Transifex will work.

**Comment by comradekingu** [comment]
@gnuhead-chieb Where?

**Comment by gnuhead-chieb** [comment]
> Is there an active issue about it in the Weblate repo? If not, open an issue there too.
No,This is not weblate's problem.


After a investigation, I found what a problem is.
This is caused due to translating from HTML output.
so,strings position will goes wrong when every resource update due to lost string key for determine string's position like this.
![screenshot](https://user-images.githubusercontent.com/41156994/115985918-85e8b100-a59d-11eb-8fd8-aff73ad39693.png)



To fix this, You have to convert to gettext .po format from latex, then after update .po translation file, reconvert .po to latex again.then, export as html or something else.

You can convert latex to .po using po4a

References:
https://po4a.org/
https://www.systutorials.com/docs/linux/man/1-po4a/
https://www.systutorials.com/docs/linux/man/7-po4a/

**Comment by MuntashirAkon** [comment]
> To fix this, You have to convert to gettext .po format from latex, then after update .po translation file, reconvert .po to latex again.then, export as html or something else.

I initially went for it during the testing phase (you can still see it in the commit history, and the po4a annotations are still present in the latex files). But Latex has troubles handling texts that are not Roman alphabet. So our conclusion was that it's better to use HTML output than the Latex files themselves.

In short:
1. **Markdown.** Not supported by Weblate. Crowdin supports this but it creates more problems than solving them as I have to spend hours fixing the strings
2. **Latex.** Latex itself is the issue in this case as it doesn't have any localisation support (doesn't have any proper support for non-Roman alphabets and therefore, unusable), and the po4a extension for Latex is not up to date.
3. **HTML.** Weblate interally uses po4a to handle the HTML files which is currently in beta stage (according to their docs), and as you've reported it's not working correctly either.

**Conclusion:** There's no viable way to handle translations of documentations in Weblate in the technologies that I'm familiar with. If you know of any technology that can handle translation as well as generate _static_ pages, let me know.

**Comment by gnuhead-chieb** [comment]
I found this site may it will useful
https://tex.stackexchange.com/questions/60781/managing-multiple-translation-of-a-single-document

**Comment by MuntashirAkon** [comment]
> I found this site may it will useful
> https://tex.stackexchange.com/questions/60781/managing-multiple-translation-of-a-single-document

Trust me, I've gone through all that. Doesn't work for non-Roman languages. Latex was originally created to support only English texts. Later alternatives such as Xelatex were introduced which can better handle things. Although with a few tweaks they work for a few languages, tex4ht can't produce texts for them. Instead you'll only see blank lines. Only pdflatex (the original latex) works but it doesn't support many languages (not even my native language).

**Comment by gnuhead-chieb** [comment]
Finally I found out the way to convert multilangages latex to html.
No code changes required.

Just install **pandoc** by apt and run this command in latex directory.
`pandoc main.tex -c custom.css -o main.html -t html5 -f latex -s --toc`

I tested with many langauges and this is worked fine.

**Comment by MuntashirAkon** [comment]
> Finally I found out the way to convert multilangages latex to html.

If you've seen the history, I've tried pandoc too (I've even created an issue in their repo). It has formatting issues and doesn't support `\hyperref` which is a big no in this case.

**Comment by gnuhead-chieb** [comment]
> It has formatting issues and doesn't support `\hyperref` which is a big no in this case.

Latest version 2.13 is working that

**Comment by MuntashirAkon** [comment]
> Latest version 2.13 is working that
> https://github.com/jgm/pandoc/releases

The hyperref issue hasn't been fixed yet. An example is given below:

![Screenshot 2021-04-27 at 14 32 45](https://user-images.githubusercontent.com/8176128/116211475-a8c5c180-a765-11eb-8a79-e6a4b3ef981e.png)

There are other issues such as
1. No support for custom colours
    ![Screenshot 2021-04-27 at 14 32 09](https://user-images.githubusercontent.com/8176128/116211625-d3177f00-a765-11eb-8431-8b5fff854140.png)
2. Custom layouts do not work as expected
    ![Screenshot 2021-04-27 at 14 31 42](https://user-images.githubusercontent.com/8176128/116211715-eaef0300-a765-11eb-8c69-5587416d80d9.png)
    ![Screenshot 2021-04-27 at 14 25 37](https://user-images.githubusercontent.com/8176128/116211750-f6dac500-a765-11eb-8365-caf45fa497d2.png)


These are the ones I've found by skimming through the texts. There might be others that I haven't noticed.

**Comment by gnuhead-chieb** [comment]
It seems you have to write custom template and change CSS to deal with these problems.
See here:
https://pandoc.org/MANUAL.html#templates
https://github.com/jgm/pandoc-templates/blob/master/default.html5

Also I have the other idea for fixing this problem.
_Separate html files per tex files_
It is simple way.For instance, **create faq/aot.html for faq/aot.tex , create pages/app-details-page.html for pages/app-details-page.tex instead of summarize single html file.**
The issue that we are facing is caused due to classify strings just by html positon,That why, it is inevitable to string position goes wrong every resource update.
It will allows us to reduce many hours to fix broken strings.If updated change logs,Every strings will broke for now.But to do like this,We only have to fix change logs, other files will not affected anymore.

**Comment by MuntashirAkon** [comment]
Maybe you can work on this issue if you're interested. I've already wasted too much time on this.

> The issue that we are facing is caused due to classify strings just by html positon,That why, it is inevitable to string position goes wrong every resource update.

This will introduce the link fixing nightmare that I was trying to get rid of in first place.

**Comment by gnuhead-chieb** [comment]
Update.

I wrote simple script for fixing custom color.I'm now trying to fix up other pandoc issue.


```
#!/bin/bash

pandoc main.tex -c main.css -o main.pandoc.html -t html5 -f latex -s --toc -N --section-divs

while read line
do
colorset=$(echo $line | sed -e "s/\\definecolor{//" -e "s/}{HTML}{/ /" -e "s/}//")
colorname=$(echo $colorset | awk '{print $1}')
colorcode=$(echo $colorset | awk '{print $2}' | sed -e "s/^/#/")
#echo N $colorname C $colorcode
sed -i -e "s/style\=\"background-color\: ${colorname}\"/style\=\"background-color\: ${colorcode}\"/g" \
       -e "s/style\=\"color\: ${colorname}\"/style\=\"color\: ${colorcode}\"/g" main.pandoc.html

done < <(grep "\definecolor" main.tex)
```

**Comment by gnuhead-chieb** [comment]
>     2\. Custom layouts do not work as expected

Probably tcolorbox will work.I will try porting mdframed to tcolorbox.

**Comment by gnuhead-chieb** [comment]
Update.

Added App icon Fixup

```
#!/bin/bash

OUTPUT=main.pandoc.html
pandoc main.tex -c main.css -c custom.css -o $OUTPUT -t html5 -f latex -s --toc -N --section-divs --default-image-extension=png

##Custom Color Fixup
while read line
do
colorset=$(echo $line | sed -e "s/\\definecolor{//" -e "s/}{HTML}{/ /" -e "s/}//")
colorname=$(echo $colorset | awk '{print $1}')
colorcode=$(echo $colorset | awk '{print $2}' | sed -e "s/^/#/")
#echo N $colorname C $colorcode
sed -i -e "s/style\=\"background-color\: ${colorname}\"/style\=\"background-color\: ${colorcode}\"/g" \
       -e "s/style\=\"color\: ${colorname}\"/style\=\"color\: ${colorcode}\"/g" $OUTPUT
done < <(grep "\definecolor" main.tex)

##Icon Fixup(Need --default-image-extension=png option)
sed -i -e "s/\<img src\=\"images\/icon.png\" style\=\"width:2cm\"/\<img src\=\"images\/icon-.png\" style\=\"width\:16.69\%\"/g" $OUTPUT
```

**Comment by gnuhead-chieb** [comment]
Moved to https://github.com/MuntashirAkon/AppManager/pull/418
