### ISSUE TITLE
Avoid using untranslatable abbreviation

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#399]
For instance,the word "AoT" abbreviation of "ADB over TCP" cannot translate to other langauge in most cases.
I translate "ADB over TCP" to "TCP経由のADB" into Japanese.
So this abbreviation cannot integrated into Japanese(and maybe most other langauges)
I'm currently preventing confusion in explanation section  of this abbreviation to use following trick like this .

```
AoT — ADB over TCP（TCP経由のADB）の略称ですが、日本語翻訳においては混乱を招くため今後使用しません。この項目は意味がないので無視してください。

AoT — It is abbreviation of ADB over TCP(TCP経由のADB) ,but I will not use this abbreviation in this docs because it will may cause confusion to use this abbreviation.This section is NO MEANING.Please IGNORE it.
```

**Comment by gnuhead-chieb** [comment]
It should be unify format of itemized form.

e.g,

```
Quote from 2.1.5.2 List Options

・User app first. User apps are listed on top
・App label. Sort in ascending order based on the app labels (also known as app names). This is the default sorting preference
・Package name. Sort in ascending order based on package names
```

should be change like this:

・User app first – User apps are listed on top.
・App label – Sort in ascending order based on the app labels (also known as app names). This is the default sorting preference.
・Package name – Sort in ascending order based on package names.

**Comment by gnuhead-chieb** [comment]
2.2.1 Colour Codes
"very dark orange"  Color name maybe wrong

**Comment by gnuhead-chieb** [comment]
Should be distinguish "source" to "sourcecode " and "distribution source" in 1.3 and 1.4.1

**Comment by MuntashirAkon** [comment]
> For instance,the word "AoT" abbreviation of "ADB over TCP" cannot translate to other langauge in most cases.

Simply remove that section and replace the abbreviation with the full meaning.

> "very dark orange" Color name maybe wrong

Yeah, it should be vivid orange.

> It should be unify format of itemized form.

I've initially used dashes. But full stop is widely used in books in order to assist the screen readers.

> Should be distinguish "source" to "sourcecode " and "distribution source" in 1.3 and 1.4.1

It's written like a book (a manual is indeed a book). This isn't like the VuePress documentation that was introduced earlier (and is being removed). So, when you're in §1.4, it's expected that you already know where the source can be downloaded.
