### ISSUE TITLE
AM crash during import of blocking rules

### ISSUE THREAD

**Issue by tommynok** [MuntashirAkon/AppManager#400]
AM crash when trying to import blocking rules (previously exported from AM).
[AMlog_import.txt](https://github.com/MuntashirAkon/AppManager/files/6370989/AMlog_import.txt)
[logcat.txt](https://github.com/MuntashirAkon/AppManager/files/6370990/logcat.txt)

**Comment by MuntashirAkon** [comment]
Fixed in 14d24951
