### ISSUE TITLE
User Interface Changes

### ISSUE THREAD

**Issue by tommynok** [MuntashirAkon/AppManager#406]
It seems to me that the _divider_ in the list of components / app ops / permissions can help in improving the perception of information, readability, let's say (especially in a light theme).
Primarily it would help in displaying the list of _components_ (imho)

**Comment by MuntashirAkon** [comment]
Two colours are used for dividing even and odd items i.e. the list is a zebra-stripped list. So, why would you need a divider?

**Comment by tommynok** [comment]
> Two colours are used for dividing even and odd items i.e. the list is a zebra-stripped list. So, why would you need a divider?

The option with a divider seems _more readable_ to me (In a light or dark theme)
Like Blocker MAT or FreezeYou, for example.
This suggestion is also the result of a small poll/vote among AM users. (not very representative, of course)
(also two colours used for dividing can be used together with a divider)

**Comment by MuntashirAkon** [comment]
Implemented in f03d4eeb5db12ba8e08b3d8bc058b44e35ad3e62
