### ISSUE TITLE
Does not load on Android TV 10. The opening screen stays on "Initializing" forever. 

### ISSUE THREAD

**Issue by Tbo29** [MuntashirAkon/AppManager#407]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: [e.g. One Plus 8 Pro]
 - OS Version: [e.g. Android 10]
 - App Manager Version: [e.g. v2.5.13]
 - Mode: root/adb/no-root

**Additional context**

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
