### ISSUE TITLE
Can you add explanation about what all symbols and icons in AM means?

### ISSUE THREAD

**Issue by GalaxyS9plus** [MuntashirAkon/AppManager#408]
HI Muntashir!
Tnx again for your apps and help!!!
I have a question.
 
Can you please add in FAQ what this and each icons inside AM means? I can not find any explanation about it. 

For. ex. here:
Which one of this 2 means Blocked tracker? Second?
If yes, why?
It would be logical to mark the blocked element with a crossed-out sign, and not in the form of a watch with a back arrow.

<a href='https://postimg.cc/mtYyCzHM' target='_blank'><img src='https://i.postimg.cc/mtYyCzHM/icons.jpg' border='0' alt='icons'/></a>

Thank you.
Have a good life!

**Workers of the world, Unite in the workers parties!**
[Imperialism, the Highest Stage of Capitalism](https://www.marxists.org/archive/lenin/works/1916/imp-hsc/)

**Comment by tommynok** [comment]
> For. ex. here:
> Which one of this 2 means Blocked tracker? Second?
https://muntashirakon.github.io/AppManager/guide/app-details-page.html#colour-codes

**Comment by GalaxyS9plus** [comment]
HI Muntashir!
I seen this page before. But [there](https://muntashirakon.github.io/AppManager/guide/app-details-page.html#colour-codes) you talk about colors and not about signs/icons.

**Comment by GalaxyS9plus** [comment]
A question again.
Is it possible to add in 1click operation: an option to change all SSAID in all apps, with a choice of apps (in the window), and an option for to do this change automaticlly after restart of device? Thank you.

**Comment by GalaxyS9plus** [comment]
**I wholeheartedly congratulate everyone on the International Day of Workers ' Solidarity! The 1-st May!**
