### ISSUE TITLE
App Info doesn't load for hidden apps

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#410]
**Describe the bug**
am cannot view app that DISABLED BY ISLAND

**To Reproduce**
Steps to reproduce the behaviour:
1. open AM
2. Click on App That Disabled By Island
3. Couldn't Fetch Package Info

**Expected behavior**
It Should Work But Due To Glitch Or Something From Island, Other App Cannot View Disabled App By Island

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: Realme 5i
 - OS Version: Android 10
 - App Manager Version: 2.6.0 Stable Release
 - Mode: ADB 

**Additional context**
I Guess This Are Glitch Or Restriction From Island

The Only Solution Is Add Mark On App That Disabled By Island So User Understand If That App Are Disabled by Island

**Comment by NSTAdventure** [comment]
i don't know from where bug coming 

but on previous version of AM (2.5.20) it able to see app that disabled by island

**Comment by MuntashirAkon** [comment]
> The Only Solution Is Add Mark On App That Disabled By Island So User Understand If That App Are Disabled by Island

Island doesn't disable an app, it suspends them (a sort of misleading word “freeze”, I wonder why they use it). A suspended app while visible can't be parsed by the package manager. The only way to parse it is by un-suspending it.

**Comment by MuntashirAkon** [comment]
Fixed in 0f54f179.

**Comment by NSTAdventure** [comment]
> > The Only Solution Is Add Mark On App That Disabled By Island So User Understand If That App Are Disabled by Island
> 
> Island doesn't disable an app, it hides them (a sort of misleading word “freeze”, I wonder why they use it). A hidden app while visible can't be parsed by the package manager. The only way to parse it is by unhiding it.

Wait a second 
But the app is totally disabled :(
You cannot find or even worst you cannot launch those apps so it completely disabled not only hidden @MuntashirAkon

**Comment by MuntashirAkon** [comment]
> But the app is totally disabled :(

It's not disabled but hidden. There are several ways to control an app: force-stop, suspend, disable, hide and uninstall.

**Comment by NSTAdventure** [comment]
> > But the app is totally disabled :(
> 
> It's not disabled but hidden. There are several ways to control an app: force-stop, suspend, disable, hide and uninstall.

but how island able to freeze all bg behavior while app is hidden (freezed)
