### ISSUE TITLE
operation take forever

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#416]
**Describe the bug**
Doing Operation from profile is impossible they will take forever to finish

**To Reproduce**
Steps to reproduce the behaviour:
1. Open AM > Profile
2. You Can Create Or Import or use preset (I use preset Qualcomm Profile)
3. after that try to apply it and operation will take forever to finish

**Expected behavior**
It should work

**Screenshots**

**Crash logs**

**Device info**
 - Device: Realme 5i
 - OS Version: Android Q Realme UI 
 - App Manager Version: 2.6.0
 - Mode: ADB

**Additional context**
1. I Used Qualcomm Preset
2. Profile Auto Detect All User So They Applied To All User Automatically
3. I Use This Additional Setting
-Clear Cache And Data
-Force Stop

**Comment by MuntashirAkon** [comment]
Why did you create a Q&A (#415) and an issue for the same thing?

**Comment by NSTAdventure** [comment]
> Why did you create a Q&A (#415) and an issue for the same thing?

i forgot 🤦🤦🤦🤦🤦🤦

**Comment by MuntashirAkon** [comment]
This isn't reproducible on my device. Share logs from logcat.

**Comment by NSTAdventure** [comment]
> This isn't reproducible on my device. Share logs from logcat.

OTW

**Comment by NSTAdventure** [comment]
hi @MuntashirAkon  how it's going?

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.

**Comment by NSTAdventure** [comment]
> Closed due to lack of response. Feel free to open it again if you're still facing the issue.

okay

**Comment by NSTAdventure** [comment]
@MuntashirAkon hi so now on 2.6.3 this glitch still exist

Again i am using same android and devices model also using ADB i already restart devices and nothing work here

**Comment by MuntashirAkon** [comment]
Still found nothing relevant regarding profile. Can you share the profile itself by exporting it?

**Comment by NSTAdventure** [comment]
> Still found nothing relevant regarding profile. Can you share the profile itself by exporting it?

Here you go sir 🙏

**Comment by NSTAdventure** [comment]
> Still found nothing relevant regarding profile. Can you share the profile itself by exporting it?

Here you go sir 🙏

https://ufile.io/uadywtgg
I use anonymously free cloud server to upload and because i am not logged in file will survive only for 1 month so please download this file asap thank you! 🙏😊
