### ISSUE TITLE
Reconsider ETIP usage

### ISSUE THREAD

**Issue by HanabishiRecca** [MuntashirAkon/AppManager#417]
Hello again. I've reported earlier about app breakage with some ETIP rules. You've said report it to ETIP, but here is the answer:
> The ETIP database is an investigation platform (this is actually the IP in ETIP) therefore some of the trackers in it are not yet validated or reviewed.
If you want a more "mature" database, you can check directly https://github.com/Exodus-Privacy/exodus instead.

https://github.com/Exodus-Privacy/etip/issues/115#issuecomment-828707750

**Comment by MuntashirAkon** [comment]
If you go through the history of `app/src/main/values/trackers.xml`, you'd see that there's hardly any tracking signature that do not made it into the main list.

**Comment by gnuhead-chieb** [comment]
Firefox issue is already fixed before.
If you know other app breaking trackers,please let me know and I will investigate and fixing it with my ETIP account(or consider opening yourself account.You can get your own account easily by sending username that you want use by email with simple message)
