### ISSUE TITLE
Language Switching

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#42]
So the German translation is quite broken since 2/3 of the words arent translated - please add a language switcher that I can use the English one.
;)

**Comment by MuntashirAkon** [comment]
I think it would be better to disable translation altogether since these translations are actually from the original fork and no translation are added ever since and a lot has changed of late and a lot will be changing at the end of v2.5.

**Comment by UltraBlackLinux** [comment]
Ok, thanks :)
