### ISSUE TITLE
Can't restore WhatsApp Data

### ISSUE THREAD

**Issue by ghost** [MuntashirAkon/AppManager#426]
**Describe the bug**
Not able to restore my WhatsApp backup. I made it when I was on EvolutionX ROM (Android 11) so I can restore it later after switching to ArrowOS (Android 11). I made it with a debug build(just a day old) and I installed the same debug build on arrowOS and tried to restore my WhatsApp backup and it failed. I tried to restore that backup with stable version of AM but it failed there too with the same error as I saw in logs. 

This is the first time I backed up something with AM to restore it after switching ROM and this happened. I usually use swift backup to backup WhatsApp always and it never disappointed. 

**Expected behavior**
Data should be restored.

**Screenshots**
-

**Crash logs**
Here is the restore log - https://del.dog/mofuthelec.txt

**Device info**
 - Device: [Poco M2 Pro]
 - OS Version: [e.g. Android 11]
 - App Manager Version: [v2.6.0]
 - Mode: root

**Comment by MuntashirAkon** [comment]
Release version doesn't log anything other than errors. Use debug builds for taking logs, and don't use any filters.

**Comment by shivvvvvv** [comment]
> Release version doesn't log anything other than errors. Use debug builds for taking logs, and don't use any filters.


I did a fresh backup with latest debug, backed up Base apk and internal data only. Same error while restoring. 

https://del.dog/uxypamewea.txt

**Comment by MuntashirAkon** [comment]
> I did a fresh whatsapp backup with latest debug (fresh installation/No filters), backed up Base apk and internal data only. Same error while restoring.

The logs you shared are not what I wanted. Use logcat to take logs without any filters.

**Comment by shivvvvvv** [comment]
> > I did a fresh whatsapp backup with latest debug (fresh installation/No filters), backed up Base apk and internal data only. Same error while restoring.
> 
> The logs you shared are not what I wanted. Use logcat to take logs without any filters.

 Oops... Sorry, misunderstood earlier. Here you go - https://del.dog/phocrugygr.log

**Comment by MuntashirAkon** [comment]
> Oops... Sorry, misunderstood earlier. Here you go - https://del.dog/phocrugygr.log

Thanks. The error is a bit confusing. Are you trying to restore with “cache” option checked? If so, uncheck it and try again. If no, then locate `AppManager/com.whatsapp/0/data0.tar.gz` and then check the files inside it as follows:

```
tar -tzf /path/to/AppManager/com.whatsapp/0/data0.tar.gz
```

File list doesn't usually contain anything sensitive.

**Comment by shivvvvvv** [comment]
> > Oops... Sorry, misunderstood earlier. Here you go - https://del.dog/phocrugygr.log
> 
> Thanks. The error is a bit confusing. Are you trying to restore with “cache” option checked? If so, uncheck it and try again. If no, then locate `AppManager/com.whatsapp/0/data0.tar.gz` and then check the files inside it as follows:
> 
> ```
> tar -tzf /path/to/AppManager/com.whatsapp/0/data0.tar.gz
> ```
> 
> File list doesn't usually contain anything sensitive.

It listed all the files inside compressed data file. I removed some lines because it contained phone numbers.

https://del.dog/lokinufuci.txt

**Comment by MuntashirAkon** [comment]
A/C deleted.
