### ISSUE TITLE
Add an app-launch button

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#43]
Its a bit annoying that I have to switch between app_manager and my launcher all time after patching, could you add a launch button next to the disable button or sth?

**Comment by MuntashirAkon** [comment]
There's already a launch button. Scroll near the end of App Info window until you get “Main Activity.” The button next to it could be used to launch the app.

**Comment by UltraBlackLinux** [comment]
@MuntashirAkon Hm I actually mean a bit more obvios one, as easy accessible as the uninstall and disable button
