### ISSUE TITLE
 no user selection screen (2.6.0)

### ISSUE THREAD

**Issue by ghost** [MuntashirAkon/AppManager#431]
- [ ✓] I know what my device, OS and App Manager versions are
- [ ✓] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
i upgraded island to v 5.3 
am detect the user but when instal apk they not prompt you to choose user 🤦

**To Reproduce**
Steps to reproduce the behaviour:
1. open any file manager choose any apk
2. Click the apk and tap install (am icon),
3. click instal and you not able to choose user

**Expected behavior**
you can choose user before installing

**Screenshots**

**Crash logs**

**Device info**
 - Device: Realme 5i
 - OS Version: Android Q (Realme UI 1.0)
 - App Manager Version: v2.5.20
 - Mode: ADB

**Additional context**
no island didn't do anything weird on this updates 

ok setting checked still not working though :(
Edit:
Log Provided
[USERRRRRRRRRRRR.log](https://github.com/MuntashirAkon/AppManager/files/6456419/USERRRRRRRRRRRR.log)

**Comment by NSTAdventure** [comment]
MOMMY! 😭

**Comment by MuntashirAkon** [comment]
After updating Insular, did you clear cache and restart your device? This could be an Insular/Island issue. I'm also using the latest version of Insular, and everything's working fine. Also, check if **Show users in installer** is checked (it's unchecked by default).

**Comment by NSTAdventure** [comment]
> After updating Insular, did you clear cache and restart your device? This could be an Insular/Island issue. I'm also using the latest version of Insular, and everything's working fine. Also, check if **Show users in installer** is checked (it's unchecked by default).

sometime even i already check option they cannot work as well temporary fix is tried to re enable switch in setting
