### ISSUE TITLE
is the tracker really removed? 🥴

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#434]
- [ ✓] I know what my device, OS and App Manager versions are
- [✓ ] I know how to take logs
- [ ✓] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
i check app info using AM but there is no tracker on app but when i tap scan they found 2 tracker

**To Reproduce**
Steps to reproduce the behaviour:
1. (INSTAL TARGET APK FIRST!!!) then Open AM Check App Info 
2. There Is Tracker Detected
3. tap scanner and scanner result detect 2 tracker

**Expected behavior**
I want to get accurate result

**Screenshots**
OTW 

**Crash logs**

**Device info**
 - Device: Realme 5i
 - OS Version: Android Q
 - App Manager Version: 2.6.0
 - Mode: ADB

**Additional context**
1. App That Are Scanned By AM Is Modded By Kirlif They Disabled The Tracker And Make The App AOSP Compatible

**Comment by MuntashirAkon** [comment]
Already covered in FAQ: https://muntashirakon.github.io/AppManager/en/#x1-1690004.1.7. Also see the disclaimer section in the scanner page: https://muntashirakon.github.io/AppManager/en/#x1-1200002.7.
