### ISSUE TITLE
Uninstalled apps config remover

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#44]
Could you add a button that cleans the remaining configs of uninstalled apps in the root/data/data/this.app.trash directory?
This is great for storage saving, e.g after uninstalling firefox with 50 extentions.

**Comment by MuntashirAkon** [comment]
I'll implement as part of one click operation scheme that I'm currently designing.

**Comment by MuntashirAkon** [comment]
Related to #56

**Comment by MuntashirAkon** [comment]
Actually, I think it is succeeded by #56 as it offers similar functions.
