### ISSUE TITLE
Add options to select users that App Manager should work with

### ISSUE THREAD

**Issue by rustforfuture** [MuntashirAkon/AppManager#443]
Hello

Thank you for your great app.

May you please bring back the filter option (showing system apps, disabled, etc separately)

And also please if may move the other profile sections in another format.

What i mean is please for example add an option so we can select the app manager to show each profile (owner, work, ...) Separately because in version 2.6 it is somewhat confusing because for example i disabled/removed many apps from my main (owner) profile but app manager shows them because they are exist in my work profile (which i freezed using island)

If may please bring back / add these options because as of version 2.6 the ux is somewhat confusing because of these.

Thank you very much.

Screenshots from how i mean to do user selection like appsopsX:

![Screenshot_20210517_034038_com zzzmode appopsx~01](https://user-images.githubusercontent.com/49192003/118415864-0d6ba080-b6c2-11eb-95c3-ad8a855077b0.jpg)

![Screenshot_20210517_034045_com zzzmode appopsx~01](https://user-images.githubusercontent.com/49192003/118415868-13fa1800-b6c2-11eb-8f1c-3caa27412341.jpg)

Sorry, i couldn't search for similar issue and read template carefully because i have eye problems and typed nost of this with voice typing.

Thank you very much

**Comment by MuntashirAkon** [comment]
> May you please bring back the filter option (showing system apps, disabled, etc separately)

Filters and sorting options are now under the **List Options**. We occasionally require changing or moving some UI components in order to improve UX. This is why we publish very detailed changelogs, and the users are expected to go through them. The issue with the old filter menu was that each time you select a filter the menu would be closed. The new implementation fixes that issue and now you can select multiple filters at the same time. Additionally, you can also filter items based on profiles, a new feature introduced a few months ago.

> What i mean is please for example add an option so we can select the app manager to show each profile (owner, work, ...)

Ability to select (one or more) users will be added in a later version.

**Comment by rustforfuture** [comment]
> Filters and sorting options are now under the **List Options**. We occasionally require changing or moving some UI components in order to improve UX. This is why we publish very detailed changelogs, and the users are expected to go through them. The issue with the old filter menu was that each time you select a filter the menu would be closed. The new implementation fixes that issue and now you can select multiple filters at the same time. Additionally, you can also filter items based on profiles, a new feature introduced a few months ago.

Oh, really sorry and thank you for your kind response.
I haven't seen the filter ticks in list menu and didn't know it is scrollable.

I checked it now after your response and it us great.

Thank you very much.

> Ability to select (one or more) users will be added in a later version.

Thank you very much ♥️
