### ISSUE TITLE
Question: Why disable ADB over TCP and why it is insecure when device ask for permission?

### ISSUE THREAD

**Issue by rustforfuture** [MuntashirAkon/AppManager#444]
Also i have a question, why you wrote we should disable adb over tcp as soon as we didn't needed it?

Because phone always will prompt when some app wants to connect through it, so why it is insecure to be enabled?

(Excuse me, i read that some malware use this but i don't know how so i wanted to ask you as a veteran android dev that so that prompt can bypassed by malicious apps?)

Sorry, i couldn't search for similar issue or the FAQ of app and read template carefully because i have eye problems and typed nost of this with voice typing.

Thank you very much

**Comment by MuntashirAkon** [comment]
> why you wrote we should disable adb over tcp as soon as we didn't needed it?

- ADB over TCP broadcasts phone identifier over network which is not good privacy-wise.
- Prompts, despite all the efforts to block overlays, can be bypassed. On older and some newer devices, displaying prompts aren't even enabled by default.
- It runs a server in your phone which might drain your phone's battery faster than usual.

This is all I can remember right now.

>  i wanted to ask you as a veteran android dev that so that prompt can bypassed by malicious apps?

I'm not actually a veteran Android developer. App Manager is my second Android app (first one was part of a university project). So, my (real) experience as an Android developer is around a year or so. But yes, I've been using Android OS for a long time and I'm quite familiar with root, ADB and Xposed framework from the start.

**Comment by rustforfuture** [comment]
Thank you very much for your detailed and kind response.

Stay safe.
Good luck.
