### ISSUE TITLE
Fate of Aurora Store

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#445]
Last week, it came to my attention that Aurora Store is going for an opt-in promotional apps section on top of the **For You** page. But Their first client is [1xBet](https://en.wikipedia.org/wiki/1xBet), a notorious gambling company which is banned in the USA, Russia and many other European countries. This movement made our users concerned about the future of Aurora Store and whether we should include or promote this app any longer in the app details page of App Manager.

We have a policy, from the beginning, of not promoting any non-free apps which included Google Play Store, MyAndroidTools and Tasker. Even though we planned to support some apps such as TitaniumBackup and Swift Backup, App Manager would work as a sink, not source, and strictly for migration purposes. Aurora Store was an exception in the sense that we trusted that the server it uses has not been modified to log personally identifiable information (PII). After hearing the announcement, I personally felt betrayed. If they required crowd sourcing to continue to maintain the servers, they could've announced it or they could've integrated a donation-based plan, alongside a free plan.

However, I've decided to wait for a few weeks to see how the users of Aurora Store, and F-Droid react to this new (in their own terms) “autocratic” decision. Some of our contributors and well wishers have suggested forking Aurora Store which I cannot do because of my no-string-attached policies (however, we may work on a [F-Droid integration](249) which doesn't need any strings).

The purpose of the issue is to know what others think of this revelation.

**Comment by assembleDebug** [comment]
It will be better to remove it the dev doesn't come up with any other solution or change within few days. Personally I feel that he should have turned off the promotional app listing by default. The intention is just not to keep the servers running with that money, there is something more. Picking a betting app for promotion, really?

**Comment by MuntashirAkon** [comment]
> Picking a betting app for promotion, really?

Yeah, precisely.

**Comment by Deerp1976** [comment]
I have already deleted Aurora from my phone because I feel this decision
that has been made is extremely uncomfortable. To try and keep level headed
about this, I decided to investigate this illicit gambling company for
myself just to see why my country (United Kingdom), has decided to ban the
company outright and the more I read, the more disgusted I got. Although I
won't repeat the more severe allegations made about 1xbet, what I did read
that can be proven has made me seriously question why the developer of
Aurora is thinking of allowing this company to be advertised on Aurora.

Even if this was just a normal gambling company, I could not support it
because it cuts off users who are not old enough to gamble to use any app
that has been sponsored. Gambling is strictly regulated for a very good
reason and allowing sponsorship of it should not be a decision to be taken
lightly. In my country, any form of gambling advertisements must strictly
only be shown on TV after 9pm. As this is an app that can be used at any
time, I cannot support or endorse Aurora any longer.

As for App Manager having a direct link to Aurora, unless things
drastically change for the better, I have to say the link and any mention
of Aurora must be taken off for the greater good. I will of course fully
support any decision made but my feelings I think I've made crystal clear
on the matter.

Thanks

**Comment by MuntashirAkon** [comment]
The developers of Aurora Store have just announced that **promoted apps** section will be removed in the next version, and in their words, they “will ensure Aurora always is free and ad-free”. So, Aurora Store will not be removed from App Manager.

Notice that Aurora Store (listed as **Store** in the app info tab) is only displayed if the app itself is installed.

**Comment by nitanmarcel** [comment]
The promotional tab won't affect by any means user's experience as they will show as simple installable apps and not those big banner ads.

Also the promoted apps section would be disableable from the app's settings.

The promotional content is only there because the developer needs some help mentaining the server and the app running.

**Comment by MuntashirAkon** [comment]
> The promotional tab won't affect by any means user's experience as they will show as simple installable apps and not those big banner ads.
> 
> Also the promoted apps section would be disableable from the app's settings.
> 
> The promotional content is only there because the developer needs some help mentaining the server and the app running.

An app with advertisements automatically makes it unsuitable for App Manager to promote due to our philosophy. However, my question is this: If they are unable to bear the maintenance cost, why won't they run a donation campaign or make it a freemium app? A lot of apps including F-Droid, Fairmail, Netguard, Signal, AFWall+ adopted these alternatives, and last time I checked, they are all still being actively developed.

Moreover, we have issues with their current sponsor, the **1xBet** company itself: Apart from the fact that some users of AM are under 18, 1xBet is considered an illegal gambling company by many European countries, Russia, and the USA, and was thrown out from Google Play Store. The owners of the app are wanted felons in Russia. This may even cause legal issues for the creators of Aurora Store, F-Droid as a distributor and even App Manager as a promoter as the governments of the world take issues like these quite seriously. (I don't have a lawyer and I don't know if they have any.) This also questions the app's legitimacy since advertise like this are usually present in illegal torrent sites and pirated movies.

Anyway, as explained in b004329e, we've only removed support for Aurora Store 4.0.5 and later (until the creators publishes an ad-free version). You can still use the older versions without issues.

**Comment by nitanmarcel** [comment]
> > The promotional tab won't affect by any means user's experience as they will show as simple installable apps and not those big banner ads.
> > Also the promoted apps section would be disableable from the app's settings.
> > The promotional content is only there because the developer needs some help mentaining the server and the app running.
> 
> An app with advertisements automatically makes it unsuitable for App Manager to promote due to our philosophy. However, my question is this: If they are unable to bear the maintenance cost, why won't they run a donation campaign or make it a freemium app? A lot of apps including F-Droid, Fairmail, Netguard, Signal, AFWall+ adopted these alternatives, and last time I checked, they are all still being actively developed.
> 
> Moreover, we have issues with their current sponsor, the **1xBet** company itself: Apart from the fact that some users of AM are under 18, 1xBet is considered an illegal gambling company by many European countries, Russia, and the USA, and was thrown out from Google Play Store. The owners of the app are wanted felons in Russia. This may even cause legal issues for the creators of Aurora Store, F-Droid as a distributor and even App Manager as a promoter as the governments of the world take issues like these quite seriously. (I don't have a lawyer and I don't know if they have any.) This also questions the app's legitimacy since advertise like this are usually present in illegal torrent sites and pirated movies.
> 
> Anyway, as explained in [b004329](https://github.com/MuntashirAkon/AppManager/commit/b004329e044654ca8b8e3e92b32d75a473cede98), we've only removed support for Aurora Store 4.0.5 and later (until the creators publishes an ad-free version). You can still use the older versions without issues.

I had no idea of the new promoted apps tab until today as I was on a long hiatus nor I know why Rahul made the decision to include promoted apps (especially 1xBet). About the donation campaign, there we're always options to donate to the developer but I suppose it wasn't used to much, and if by "donation campaign" you're referring to one of those found raising campaigns, from my point of view it won't be effective since like the user's of your apps we also have underage people using the app.

Anyway just like other features that we implemented in our app, the way we deliver the promoted apps might be improved in the future but Rahul doesn't plan to get rid of it completely.

**Comment by nitanmarcel** [comment]
An idea I still have to bring the developer is to ask the user when he first installs the app if he wants to opt-in having promoted apps displayed in the "For You" section, and if he chose not to the app would have disabled the respective section of promoted apps from showing up. Acting like it would have been disabled by default as @assembleDebug mentioned above

**Comment by MuntashirAkon** [comment]
> I had no idea of the new promoted apps tab until today as I was on a long hiatus nor I know why Rahul made the decision to include promoted apps (especially 1xBet). About the donation campaign, there we're always options to donate to the developer but I suppose it wasn't used to much, and if by "donation campaign" you're referring to one of those found raising campaigns, from my point of view it won't be effective since like the user's of your apps we also have underage people using the app.

You should try it first. But I'd say it depends on your policy. If you're only going to use the donation money to run the server, donations should be enough. I'm certain that you'd find one or two interested users who are going to support you. But if you're looking for supporting the developers and the creators too, this will be difficult (but you should start anyway). But in any case, the donation campaign should be very transparent and thoroughly carried out otherwise most people won't even notice them (simply putting a donation link won't be enough). If you need further help, you can ask those who have past experiences such as @izzysoft of F-Droid. I'm sure they would gladly help you on this matter as Aurora Store being the only viable alternative to the Google Play Store to people who're gradually trying to get rid of Google from their life.

> Anyway just like other features that we implemented in our app, the way we deliver the promoted apps might be improved in the future but Rahul doesn't plan to get rid of it completely.

I've seen an announcement that he's going to remove the **promotional apps** section in the next version.

> An idea I still have to bring the developer is to ask the user when he first installs the app if he wants to opt-in having promoted apps displayed in the "For You" section, and if he chose not to the app would have disabled the respective section of promoted apps from showing up.

This could be an option for you, but not for us, I'm afraid. The users and contributors of App Manager (including myself) are very critic on matters like this.

**Comment by IzzySoft** [comment]
What seems to work for funding are "campaigns" with transparently defined "goals" – like "if we reach USD xx in donations, we'll do ZZZ" (e.g. work on a specific feature). A donation-based plan with extra-features is another good possibility. A third one is a "nag screen" on first install (and each update) stating something like "we have USD xx costs but only USD yy cost coverage; if you like our app please consider donating" (with pointers on how to donate). Platforms like OpenCollective and Liberapay feature recurring payments, so one could eg donate a buck all 3 months or something like that (Liberapay only works with Paypal or Stripe; with OC you could also have SEPA).

I fully agree with @MuntashirAkon on the point that promoting "shady apps" definitely is the wrong way; like Muntashir, I'd 100% reject that idea (well, not sure what would happen if I'd be offered an 8 digit sum or more – but that's of course purely fictional :rofl:).

**Comment by assembleDebug** [comment]
![Screenshot_20210527-161145_1](https://user-images.githubusercontent.com/83750299/119813260-adb59680-bf06-11eb-9817-11cec12f508c.png)

*I go away*

**Comment by MuntashirAkon** [comment]
> ![Screenshot_20210527-161145_1](https://user-images.githubusercontent.com/83750299/119813260-adb59680-bf06-11eb-9817-11cec12f508c.png)
> 
> _I go away_

Wow, that's a harsh reply. Still, I hope that he reconsiders his decision.

**Comment by MuntashirAkon** [comment]
Re-added Aurora Store 4.0.6 and onwards as the promotional section has been removed (9c20ea56).
