### ISSUE TITLE
Make key name more readable in pref editor

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#449]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
In preference editor, when the length of key name is more than 5 or 6 words (depending on the screen space), the key name is not completely readable. It is not scrollable in list as well as in the input box. As a result, we can't read the whole key. 

![Screenshot_20210521-195950_AM_Debug](https://user-images.githubusercontent.com/83750299/119155157-2920cf00-ba53-11eb-8692-acb8bbdd1469.png)
Screenshot 1 - See the Keyboard_redesign...... line. 

![Screenshot_20210521-200428_AM_Debug](https://user-images.githubusercontent.com/83750299/119155413-743ae200-ba53-11eb-96e8-2d3b82b57991.png)
Screenshot 2 - The key name isn't scrollable, so user have no idea what the rest of the line contains.

**Describe the solution you'd like**
Make is scrollable (Horizontally ofcourse) or if possible just show it in two lines.

**Comment by MuntashirAkon** [comment]
I think only the key name in the edit/input dialog should be scrollable.

**Comment by assembleDebug** [comment]
> I think only the key name in the edit/input dialog should be scrollable.

Yup, I meant that only. Its okay if it's not scrollable in the list.

**Comment by MuntashirAkon** [comment]
Fixed in 5fb67209
