### ISSUE TITLE
Please make available version with fix for Android 6 missing apps in the list

### ISSUE THREAD

**Issue by solnyshok** [MuntashirAkon/AppManager#450]
hi, I see in the closed issues, that about 2 weeks ago, you made a fix for Android 6 problems with app list. Where can I download one. i am on Android 6 too and see only 3 apps in version 2.6. Last version that shows all (or almost all) apps, is 2.5.22

**Comment by MuntashirAkon** [comment]
We have a fixed schedule for each stable release. See [milestones](https://github.com/MuntashirAkon/AppManager/milestones?direction=asc&sort=title&state=open) for details.
