### ISSUE TITLE
Some Permissions & App Ops Revert Back in Android 11

### ISSUE THREAD

**Issue by anedroid** [MuntashirAkon/AppManager#456]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
App Manager doesn't change some kind of permissions, like *android.permission.ACCESS_COARSE_LOCATION*, *android.permission.CALL_PHONE* or *android.permission.CAMERA*.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open any app in App Manager
2. Slide to "uses permissions"
3. Try to grant or revoke permission
4. Refresh

**Expected behavior**
If you revoke permission, after it should be revoked, or if you grant, should be granted.

**Screenshots**
https://user-images.githubusercontent.com/72965850/119520566-b0838080-bd7a-11eb-9eff-e248d5868cf3.mp4

**Device info**
 - Device: Moto g7 Power (ocean)
 - OS Version: Android 11 (LineageOS with microG)
 - App Manager Version: 2.6.0
 - Mode: root

**Additional context**
I can change state of permission using `sudo pm grant|revoke [package] [permission]`.

**Comment by MuntashirAkon** [comment]
Yes, this is an Android 11 specific issue happens because it expects the same changes to both permission and the associated app operation unlike Android 10 or earlier where this _liaison_ didn't exist.

**Comment by NSTAdventure** [comment]
> Yes, this is an Android 11 specific issue happens because it expects the same changes to both permission and the associated app operation unlike Android 10 or earlier where this _liaison_ didn't exist.

nah android 10 also keep revert everything as you know by my issues

**Comment by MuntashirAkon** [comment]
> nah android 10 also keep revert everything as you know by my issues

That's a different issue. Don't mix the two.

**Comment by MuntashirAkon** [comment]
Wait, was your issue got fixed? It shouldn't be (at least not on my device).

**Comment by anedroid** [comment]
Oh, maybe it because now I use Android 11. I'll open it again.

**Comment by NSTAdventure** [comment]
> Everything works now for me, I don't know, why. I'll open it again.

Also sorry for my latest discussion earlier sir 🙏  i didn't have any intention to OOT 🙏

Don't ban me pls I won't oot again nextime 🙏

**Comment by MuntashirAkon** [comment]
Should be fixed after 0b571a38 and d96e9cd0.
