### ISSUE TITLE
Tracker Disabl does not apply to some trackers

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#46]
Pressing on Disable trackers does not apply to all paets of google firebase - is only app measurement a tracker?

**Comment by UltraBlackLinux** [comment]
Wait, Im.stupid.

**Comment by MuntashirAkon** [comment]
> Pressing on Disable trackers does not apply to all paets of google firebase - is only app measurement a tracker?

Google Firebase itself is not considered as tracker by Exodus. It's essential for many apps to work as they use it to store database for example.

**Comment by MuntashirAkon** [comment]
@UltraBlackLinux I'll be adding an option to block the given signature(s) system-wide which you use to block your desired components like firebase or facebook.
