### ISSUE TITLE
[Bug] failed to restore an app 

### ISSUE THREAD

**Issue by Mtkmanjaro** [MuntashirAkon/AppManager#462]
make a backup successfully then tried to restore, and even if the apk is installed crash when tried to open.

Device: xiaomi redmi note 5 plus
Codename: Vince
Android: 11 permissive build 
Mode: Root
App manager: lastest release

Log from the apk it self:
android.database.sqlite.SQLiteCantOpenDat abaseException: Cannot open database '/data/ user/O/com.animeworld.app pro2/databases/ androidx.work.workdb': Directory /data/user/o / com.animeworld.app_pro2/databases doesn't exist at android.database.sqlite.SQLiteConnection.open(SQLiteC onnection.java:252)

Log from App manager:

05-30 21:34:53.500 I/ActivityTaskManager(1496): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.animeworld.app_pro2/com.animeworld.Root bnds=[439,92][641,337]} from uid 10211
05-30 21:34:53.548 I/ActivityManager(1496): Start proc 27959:com.animeworld.app_pro2/u0a248 for pre-top-activity {com.animeworld.app_pro2/com.animeworld.Root}
05-30 21:34:53.633 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/cache: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.649 I/DefaultProvider(27959): onCreate; originalPackageName: com.animeworld.app_pro2
05-30 21:34:53.650 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.651 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.674 W/CloneSettings(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/cloneSettings.json: open failed: ENOENT (No such file or directory)
05-30 21:34:53.676 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/cache: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.691 I/Signatures(27959): init; packageName: com.animeworld.app_pro2, uid: 10248, originalPackageName: com.animeworld.app_pro2, originalUid: 10248, originalSignatures:
05-30 21:34:53.836 E/AndroidRuntime(27959): Process: com.animeworld.app_pro2, PID: 27959
05-30 21:34:53.836 E/AndroidRuntime(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:53.699 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/cache: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.882 W/FileUtils(27959): Failed to chmod(/data/user/0/com.animeworld.app_pro2/files): android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
05-30 21:34:53.722 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.723 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.724 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/no_backup: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.729 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.731 V/chatty  (27959): uid=10248(com.animeworld.app_pro2) identical 1 line
05-30 21:34:53.745 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.753 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.animeworld.app_pro2_preferences.xml
05-30 21:34:53.754 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.animeworld.app_pro2_preferences.xml
05-30 21:34:53.758 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.763 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.776 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/databases: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.778 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.778 E/SQLiteLog(27959): (14) os_unix.c:38589: (2) open(/data/user/0/com.animeworld.app_pro2/databases/com.google.android.datatransport.events) - 
05-30 21:34:53.779 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.782 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.787 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.790 E/SQLiteDatabase(27959): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/com.google.android.datatransport.events'.
05-30 21:34:53.790 E/SQLiteDatabase(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/com.google.android.datatransport.events': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:53.791 E/TransportRuntime.Executor(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/com.google.android.datatransport.events': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:53.792 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.794 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:53.794 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/no_backup: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.797 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.800 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.801 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.804 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.805 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:53.813 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.818 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.819 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.820 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.824 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.824 I/TetheringManager(27959): registerTetheringEventCallback:com.animeworld.app_pro2
05-30 21:34:53.825 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.832 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/databases: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.833 E/SQLiteLog(27959): (14) os_unix.c:38589: (2) open(/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb) - 
05-30 21:34:53.835 E/SQLiteDatabase(27959): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb'.
05-30 21:34:53.835 E/SQLiteDatabase(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:53.837 E/UncaughtException(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:53.873 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.881 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.883 E/FirebaseCrash(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/firebase_inter_process_mutex-lock_write_report_to_sqlite.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:53.883 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/databases: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.883 E/SQLiteLog(27959): (14) os_unix.c:38589: (2) open(/data/user/0/com.animeworld.app_pro2/databases/crash_reports) - 
05-30 21:34:53.885 E/SQLiteDatabase(27959): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports'.
05-30 21:34:53.885 E/SQLiteDatabase(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:54.150 W/FileUtils(27959): Failed to chmod(/data/user/0/com.animeworld.app_pro2/files): android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
05-30 21:34:53.890 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.appid.xml
05-30 21:34:53.891 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.891 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:53.892 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.907 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.firebase.crashlytics.xml
05-30 21:34:53.907 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/FirebaseAppHeartBeat.xml
05-30 21:34:53.908 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/FirebaseAppHeartBeat.xml
05-30 21:34:53.908 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-30 21:34:54.172 W/FileUtils(27959): Failed to chmod(/data/user/0/com.animeworld.app_pro2/files): android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
05-30 21:34:53.917 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.946 I/FA      (27959):   adb shell setprop debug.firebase.analytics.app com.animeworld.app_pro2
05-30 21:34:53.980 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.981 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:53.982 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.988 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/databases: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.989 E/SQLiteLog(27959): (14) os_unix.c:38589: (2) open(/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db) - 
05-30 21:34:53.990 E/SQLiteDatabase(27959): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db'.
05-30 21:34:53.990 E/SQLiteDatabase(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:53.991 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/databases: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.992 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/databases: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.992 E/SQLiteLog(27959): (14) os_unix.c:38589: (2) open(/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db) - 
05-30 21:34:53.993 E/SQLiteDatabase(27959): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db'.
05-30 21:34:53.993 E/SQLiteDatabase(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:53.993 E/FA      (27959): Failed to open local database. Events will bypass local storage: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:54.018 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.187 W/FileUtils(27959): Failed to chmod(/data/user/0/com.animeworld.app_pro2/files): android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
05-30 21:34:54.019 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.251 I/WindowManager(1496): WIN DEATH: Window{4ff2e6d u0 com.animeworld.app_pro2/com.animeworld.Root}
05-30 21:34:54.252 I/ActivityManager(1496): Process com.animeworld.app_pro2 (pid 27959) has died: fg  TOP 
05-30 21:34:54.263 W/ActivityTaskManager(1496): Force removing ActivityRecord{cbaf564 u0 com.animeworld.app_pro2/com.animeworld.Root t70}: app died, no saved state
05-30 21:34:54.019 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.042 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.043 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.043 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.051 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-30 21:34:54.052 V/chatty  (27959): uid=10248(com.animeworld.app_pro2) queued-work-loo identical 8 lines
05-30 21:34:54.053 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-30 21:34:54.056 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.056 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.057 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.065 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.066 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.066 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.070 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.085 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.086 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.086 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.121 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.122 E/CrossProcessLock(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.122 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.132 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.146 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.150 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.151 E/FirebaseCrash(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/firebase_inter_process_mutex-lock_write_report_to_sqlite.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.151 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/databases: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.151 E/SQLiteLog(27959): (14) os_unix.c:38589: (2) open(/data/user/0/com.animeworld.app_pro2/databases/crash_reports) - 
05-30 21:34:54.152 E/SQLiteDatabase(27959): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports'.
05-30 21:34:54.152 E/SQLiteDatabase(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:54.384 D/NotificationService(1496): 0|com.animeworld.app_pro2|1621363246|null|10248: granting content://settings/system/notification_sound
05-30 21:34:54.385 D/NotificationService(1496): 0|com.animeworld.app_pro2|1621363246|null|10248: granting content://settings/system/notification_sound
05-30 21:34:54.153 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.160 V/chatty  (27959): uid=10248(com.animeworld.app_pro2) identical 1 line
05-30 21:34:54.168 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.169 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-30 21:34:54.170 V/chatty  (27959): uid=10248(com.animeworld.app_pro2) queued-work-loo identical 4 lines
05-30 21:34:54.170 E/SharedPreferencesImpl(27959): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-30 21:34:54.172 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.172 W/CrashHandler(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:54.173 E/FirebaseCrash(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/firebase_inter_process_mutex-lock_write_report_to_sqlite.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.173 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/databases: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.173 E/SQLiteLog(27959): (14) os_unix.c:38589: (2) open(/data/user/0/com.animeworld.app_pro2/databases/crash_reports) - 
05-30 21:34:54.174 E/SQLiteDatabase(27959): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports'.
05-30 21:34:54.174 E/SQLiteDatabase(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-30 21:34:54.178 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.186 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.187 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:54.187 E/FirebaseCrash(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/firebase_inter_process_mutex-lock_send_report_to_server.lock: open failed: ENOENT (No such file or directory)
05-30 21:34:54.250 W/InputDispatcher(1496): channel '4ff2e6d com.animeworld.app_pro2/com.animeworld.Root (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-30 21:34:54.250 E/InputDispatcher(1496): channel '4ff2e6d com.animeworld.app_pro2/com.animeworld.Root (server)' ~ Channel is unrecoverably broken and will be disposed!
05-30 21:34:54.251 W/InputDispatcher(1496): Attempted to unregister already unregistered input channel '4ff2e6d com.animeworld.app_pro2/com.animeworld.Root (server)'
05-30 21:34:54.404 W/NotifBindPipeline(1871): Row is not set so pipeline will not run. notif = 0|com.animeworld.app_pro2|1621363246|null|10248
05-30 21:34:54.892 D/IconPackManager(2033): Received intent action android.intent.action.PACKAGE_CHANGED for com.animeworld.app_pro2
05-30 21:34:55.006 D/ImsResolver(2200): maybeAddedImsService, packageName: com.animeworld.app_pro2
05-30 21:34:55.038 I/Fitness (2512): OnPackageChangedOperation got intent: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.animeworld.app_pro2 flg=0x45000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) } [CONTEXT service_id=17 ]

**Comment by MuntashirAkon** [comment]
Use the issue template to create issues.
