### ISSUE TITLE
AM fails to restored a backup

### ISSUE THREAD

**Issue by Mtkmanjaro** [MuntashirAkon/AppManager#463]
make a backup successfully of an app "anime world", then tried to restore, Am said falied to restore, go to the launcher the app is installed but unusable.

step to reproduce the bug:
make a backup of any app try to restore, restore falied 

the expected behavior:
restore the app successfully, and the app works normally

Log from AM:
```
05-30 21:34:53.633 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/cache: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.649 I/DefaultProvider(27959): onCreate; originalPackageName: com.animeworld.app_pro2
05-30 21:34:53.650 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/files: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.651 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/shared_prefs: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.674 W/CloneSettings(27959): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/cloneSettings.json: open failed: ENOENT (No such file or directory)
05-30 21:34:53.676 W/ContextImpl(27959): Failed to ensure /data/user/0/com.animeworld.app_pro2/cache: mkdir failed: EACCES (Permission denied)
05-30 21:34:53.691 I/Signatures(27959): init; packageName: com.animeworld.app_pro2, uid: 10248, originalPackageName: com.animeworld.app_pro2, originalUid: 10248, originalSignatures:
05-30 21:34:53.836 E/AndroidRuntime(27959): Process: com.animeworld.app_pro2, PID: 27959
05-30 21:34:53.836 E/AndroidRuntime(27959): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
```

**Comment by MuntashirAkon** [comment]
Looks like a permission issue.

Follow the instructions to verify the issue:
1. Uninstall the app
2. Open App Manager
3. Open log viewer to start taking logs
4. Restore the app
5. Stop taking logs
6. Send me the logs

**Comment by MuntashirAkon** [comment]
If you've updated AM from a previous version and haven't restarted, please restart before doing so.

**Comment by Mtkmanjaro** [comment]
Same behavior
reboot the device twice
full log if you needed
https://pastebin.com/48LiKD7L

 log:

05-31 12:16:27.491 W/FileUtils(1784): Failed to chmod(/data/user/0/com.animeworld.app_pro2/files): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
05-31 12:16:27.455 E/AndroidRuntime(1784): Process: com.animeworld.app_pro2, PID: 1784
05-31 12:16:27.455 E/AndroidRuntime(1784): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 12:10:36.373 E/PackageManager(1502): failed to find package com.animeworld.app_pro2
05-31 12:10:36.373 E/OverlayManager(1502): Failed to change enabled overlays for com.animeworld.app_pro2 user 0
05-31 12:22:19.323 E/PackageManager(1502): failed to find package com.animeworld.app_pro2
05-31 12:22:19.323 E/OverlayManager(1502): Failed to change enabled overlays for com.animeworld.app_pro2 user 0
05-31 12:23:33.473 E/JavaBinder(8838): java.lang.RuntimeException: android.os.RemoteException: /data/user/0/com.animeworld.app_pro2/com.animeworld.app_pro2/cache/WebView/Crashpad/settings.dat: open failed: ENOENT (No such file or directory)
05-31 12:23:33.473 E/JavaBinder(8838): Caused by: android.os.RemoteException: /data/user/0/com.animeworld.app_pro2/com.animeworld.app_pro2/cache/WebView/Crashpad/settings.dat: open failed: ENOENT (No such file or directory)

**Comment by Mtkmanjaro** [comment]
@MuntashirAkon  from what i can see from logs AM is unable to set the files and permissions for the restored app

**Comment by MuntashirAkon** [comment]
Install the APK file from here: https://github.com/MuntashirAkon/AppManager/actions/runs/891249853

and follow the same instruction given above.

**Comment by Mtkmanjaro** [comment]
just to be clear, uninstalled lastest release reboot the device, installed 2.6.1 1315 debug reboot the devive again. follow the steps sadly the same result, permissions denied.

Log:

05-31 21:42:12.522 E/WorkSourceUtil(2707): Could not find package: com.animeworld.app_pro2
05-31 21:42:12.118 E/PackageManager(1517): failed to find package com.animeworld.app_pro2
05-31 21:42:12.118 E/OverlayManager(1517): Failed to change enabled overlays for com.animeworld.app_pro2 user 0
05-31 21:43:17.695 E/JavaBinder(5491): java.lang.RuntimeException: android.os.RemoteException: /data/user/0/com.animeworld.app_pro2/com.animeworld.app_pro2/cache/WebView/Crashpad/settings.dat: open failed: ENOENT (No such file or directory)
05-31 21:43:17.695 E/JavaBinder(5491): Caused by: android.os.RemoteException: /data/user/0/com.animeworld.app_pro2/com.animeworld.app_pro2/cache/WebView/Crashpad/settings.dat: open failed: ENOENT (No such file or directory)
05-31 21:43:17.702 E/RestoreOp(1797): Caused by: java.io.IOException: android.os.RemoteException: /data/user/0/com.animeworld.app_pro2/com.animeworld.app_pro2/cache/WebView/Crashpad/settings.dat: Couldn't get remote file writer.
05-31 21:43:17.702 E/RestoreOp(1797): Caused by: android.os.RemoteException: /data/user/0/com.animeworld.app_pro2/com.animeworld.app_pro2/cache/WebView/Crashpad/settings.dat: Couldn't get remote file writer.
05-31 21:46:57.696 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.animeworld.app_pro2_preferences.xml
05-31 21:46:57.697 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.animeworld.app_pro2_preferences.xml
05-31 21:46:57.738 E/SQLiteLog(1801): (14) os_unix.c:38843: (13) lstat(/data/user/0/com.animeworld.app_pro2/databases/com.google.android.datatransport.events) - 
05-31 21:46:57.756 E/SQLiteDatabase(1801): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/com.google.android.datatransport.events'.
05-31 21:46:57.756 E/SQLiteDatabase(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/com.google.android.datatransport.events': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:57.757 E/TransportRuntime.Executor(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/com.google.android.datatransport.events': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:57.759 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:57.764 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:57.834 E/SQLiteLog(1801): (14) os_unix.c:38843: (13) lstat(/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb) - 
05-31 21:46:57.835 E/SQLiteDatabase(1801): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb'.
05-31 21:46:57.835 E/SQLiteDatabase(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:57.836 E/AndroidRuntime(1801): Process: com.animeworld.app_pro2, PID: 1801
05-31 21:46:57.836 E/AndroidRuntime(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:57.837 E/UncaughtException(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/androidx.work.workdb': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:57.870 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.firebase.crashlytics.xml
05-31 21:46:57.870 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/FirebaseAppHeartBeat.xml
05-31 21:46:57.871 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/FirebaseAppHeartBeat.xml
05-31 21:46:57.899 E/FirebaseCrash(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/firebase_inter_process_mutex-lock_write_report_to_sqlite.lock: open failed: EACCES (Permission denied)
05-31 21:46:57.900 E/SQLiteLog(1801): (14) os_unix.c:38843: (13) lstat(/data/user/0/com.animeworld.app_pro2/databases/crash_reports) - 
05-31 21:46:57.902 E/SQLiteDatabase(1801): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports'.
05-31 21:46:57.902 E/SQLiteDatabase(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:57.908 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.appid.xml
05-31 21:46:57.910 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:57.972 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-31 21:46:57.973 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-31 21:46:57.975 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:57.979 E/SQLiteLog(1801): (14) os_unix.c:38843: (13) lstat(/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db) - 
05-31 21:46:57.982 E/SQLiteDatabase(1801): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db'.
05-31 21:46:57.982 E/SQLiteDatabase(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:57.984 E/SQLiteLog(1801): (14) os_unix.c:38843: (13) lstat(/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db) - 
05-31 21:46:57.985 E/SQLiteDatabase(1801): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db'.
05-31 21:46:57.985 E/SQLiteDatabase(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:57.986 E/FA      (1801): Failed to open local database. Events will bypass local storage: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/google_app_measurement_local.db': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:58.008 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.031 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.044 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.052 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.071 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.087 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-31 21:46:58.089 E/SharedPreferencesImpl(1801): Couldn't create directory for SharedPreferences file /data/user/0/com.animeworld.app_pro2/shared_prefs/com.google.android.gms.measurement.prefs.xml
05-31 21:46:58.105 E/CrossProcessLock(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/generatefid.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.162 E/FirebaseCrash(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/firebase_inter_process_mutex-lock_write_report_to_sqlite.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.162 E/SQLiteLog(1801): (14) os_unix.c:38843: (13) lstat(/data/user/0/com.animeworld.app_pro2/databases/crash_reports) - 
05-31 21:46:58.163 E/SQLiteDatabase(1801): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports'.
05-31 21:46:58.163 E/SQLiteDatabase(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:58.182 E/FirebaseCrash(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/firebase_inter_process_mutex-lock_write_report_to_sqlite.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.183 E/SQLiteLog(1801): (14) os_unix.c:38843: (13) lstat(/data/user/0/com.animeworld.app_pro2/databases/crash_reports) - 
05-31 21:46:58.184 E/SQLiteDatabase(1801): Failed to open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports'.
05-31 21:46:58.184 E/SQLiteDatabase(1801): android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.animeworld.app_pro2/databases/crash_reports': Directory /data/user/0/com.animeworld.app_pro2/databases doesn't exist
05-31 21:46:58.192 E/FirebaseCrash(1801): java.io.FileNotFoundException: /data/user/0/com.animeworld.app_pro2/files/firebase_inter_process_mutex-lock_send_report_to_server.lock: open failed: EACCES (Permission denied)
05-31 21:46:58.266 E/InputDispatcher(1517): channel '9634b7c com.animeworld.app_pro2/com.animeworld.Root (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by MuntashirAkon** [comment]
> just to be clear, uninstalled lastest release reboot the device, installed 2.6.1 1315 debug reboot the devive again. follow the steps sadly the same result, permissions denied.

Yeah, the results are expected to be the same. I asked you to install the debug builds so that the logs would be more verbose. However, you haven't followed the instructions and haven't posted the required logs.

**Comment by Mtkmanjaro** [comment]
i did the steps as you required anyway here another attempt

https://pastebin.com/0GxZsVjf

**Comment by MuntashirAkon** [comment]
> i did the steps as you required anyway here another attempt

You haven't followed the instructions specified in the [above comment](https://github.com/MuntashirAkon/AppManager/issues/463#issuecomment-851619018). In order to sort out the issues, I need to see how AM restored the backup which I can only do if you follow the instructions in exact order.

**Comment by Mtkmanjaro** [comment]
idk what is supposed I'm doing wrong but i tried to follow the steps and find this, sorry for the inconveniences English is not my native language so most of the time i understand the things at half and sometimes with help of google translator

full log here: AM log
https://pastebin.com/qJxM1qer

06-01 18:16:03.130 D/SHELL_IN(20300): cp /data/user_de/0/io.github.muntashirakon.AppManager.debug/main.jar /data/local/tmp && chmod 755 /data/local/tmp/main.jar && chown shell:shell /data/local/tmp/main.jar && (CLASSPATH=/data/local/tmp/main.jar /system/bin/app_process  /system/bin io.github.muntashirakon.AppManager.server.IPCMain io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.ipc.AMService io.github.muntashirakon.AppManager.ipc.IPCServer)&

log for the app that falied to restore
full log:
https://pastebin.com/kqeVnCSN

05-31 21:46:57.885 W/FileUtils(1801): Failed to chmod(/data/user/0/com.animeworld.app_pro2/files): android.system.ErrnoException: chmod failed: EACCES (Permission denied)

**Comment by MuntashirAkon** [comment]
Thanks. These were the correct logs.

As you can see, AM is unable to set permission for the files and directories, usually occurs when there's any trouble with the rooting method. Which version of Android were you running, and which Magisk version were you using (both `su` and client)?

**Comment by Mtkmanjaro** [comment]
@MuntashirAkon thanks to God that these were the correct logs.

I'm running Android 11 "fluid" Rom permisive build 
running Magisk  binary 23.0 (23000) 
               Magisk manager 23.0 (23000)

**Comment by MuntashirAkon** [comment]
> I'm running Android 11 "fluid" Rom permisive build
> running Magisk binary 23.0 (23000)
> Magisk manager 23.0 (23000)

It's difficult to say whether Magisk is creating problem or not, mostly because you've filtered out the logs. There could be some SELinux errors which were skipped as a result. So, I would suggest providing a log without any filters first (if you have privacy issues, you can send via Email) before trying anything else. (It also makes me wonder why were you using a permissive build? Any app can spy on the entire Android system without any obstacle.)

**Comment by Mtkmanjaro** [comment]
there's no AVC issue relate to AM i checked today in morning, I'm using permisive because this is my favorite Rom and the Dev is still working on DT fixing never allow and avc denied, but today i will move to another Rom with enforce selinux and i will try to restore some app.

**Comment by Mtkmanjaro** [comment]
@MuntashirAkon  i moved  to another Rom that have enforce selinux  and found this, in ultimate intance i will send you the full log to your mail

06-02 16:53:58.777 W/pool-30-thread-(18223): type=1400 audit(0.0:2726): avc: denied { write } for name="com.animeworld.app_pro2.app" dev="mmcblk0p50" ino=2056215 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0 app=io.github.muntashirakon.AppManager.debug

**Comment by MuntashirAkon** [comment]
> 06-02 16:53:58.777 W/pool-30-thread-(18223): type=1400 audit(0.0:2726): avc: denied { write } for name="com.animeworld.app_pro2.app" dev="mmcblk0p50" ino=2056215 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0 app=io.github.muntashirakon.AppManager.debug

It does look like a SELinux issue, the context here should be `magisk` instead of `untrusted_app`. Did you enable "Global namespace" in Magisk setting? If not, do that first.

**Comment by Mtkmanjaro** [comment]
@MuntashirAkon  
set  mounting name space to global reboot the device get the same avc denied

06-02 23:04:09.625 W/pool-6-thread-1(4871): type=1400 audit(0.0:24): avc: denied { write } for name="com.animeworld.app_pro2.app" dev="mmcblk0p50" ino=2056215 scontext=u:r:untrusted_app:s0:c203,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0 app=io.github.muntashirakon.AppManager.debug

**Comment by MuntashirAkon** [comment]
> set mounting name space to global reboot the device get the same avc denied

Alright. Send the logs then. Although I think it's a Magisk issue, I'll see if there is anything I can do.

Also, check if AM displays/modifies SSAID for an app (such as Poweramp or MiXplorer).

**Comment by Mtkmanjaro** [comment]
check your mail i send you the full log, i don't see nothing wrong with SSAID of mixplorer or Amp, btw all my apps are restore by migrate every time i chamge the rom so idk if have something to do, anyway i don't think so because i download Quick edit from play store tried to do a restore and fail in the same way

**Comment by MuntashirAkon** [comment]
This time it failed in an early stage. See the bold-faced log item below. The app couldn't be installed because Google SafetyNet (read SlaveryNet) has blocked it.

<pre>
06-02 16:53:58.787 D/PackageInstallerCompat(18223): Installing for user 0
06-02 16:53:58.788 D/PackageInstallerCompat(18223): Installer app: io.github.muntashirakon.AppManager.debug
06-02 16:53:58.792 D/IPC     (18288): transact: uid=10203, descriptor=android.content.pm.IPackageManager, code=135
06-02 16:53:58.794 D/IPC     (18288): transact: uid=10203, descriptor=android.content.pm.IPackageInstaller, code=1
06-02 16:53:58.798 D/PackageInstallerCompat(18223): OpenSession: session id 2065200081
06-02 16:53:58.799 D/IPC     (18288): transact: uid=10203, descriptor=android.content.pm.IPackageInstaller, code=5
06-02 16:53:58.897 D/PackageInstallerCompat(18223): OpenSession: session opened.
06-02 16:53:58.900 D/IPC     (18288): transact: uid=10203, descriptor=android.content.pm.IPackageInstallerSession, code=4
06-02 16:53:58.900 D/PackageInstallerCompat(18223): Action: io.github.muntashirakon.AppManager.debug.action.INSTALL_STARTED
06-02 16:53:58.901 D/PackageInstallerCompat(18223): Session ID: 2065200081
06-02 16:53:59.653 E/ppManager.debu(18223): failed to connect to jdwp control socket: Connection refused
06-02 16:53:59.715 D/PackageInstallerCompat(18223): Commit: calling activity to request permission...
06-02 16:53:59.716 D/IPC     (18288): transact: uid=10203, descriptor=android.content.pm.IPackageInstallerSession, code=9
06-02 16:54:00.602 I/Finsky  (17437): [2] adhy.b(5): Verification requested, id = 56
06-02 16:54:00.621 I/Finsky  (17437): [223] adjg.a(7): Single user settings service is not running, bind it now
06-02 16:54:00.628 I/Finsky  (17437): [2] adjf.onServiceConnected(1): Single user settings service is connected
06-02 16:54:00.638 W/Settings(17437): Setting install_non_market_apps has moved from android.provider.Settings.Global to android.provider.Settings.Secure, returning read-only value.
06-02 16:54:00.767 I/system_server(1503): Background concurrent copying GC freed 222128(12MB) AllocSpace objects, 70(3968KB) LOS objects, 49% free, 24MB/48MB, paused 543us total 427.341ms
06-02 16:54:01.654 E/ppManager.debu(18223): failed to connect to jdwp control socket: Connection refused
06-02 16:54:02.150 I/Finsky  (17437): [223] lcf.b(3): Task 7 requested foreground
06-02 16:54:02.152 I/Finsky  (17437): [223] lcf.b(8): Not entering foreground
06-02 16:54:03.655 E/ppManager.debu(18223): failed to connect to jdwp control socket: Connection refused
06-02 16:54:04.251 I/Finsky  (17437): [224] adnt.c(3): Verify: Verification package=com.animeworld.app_pro2, id=56 response=3
06-02 16:54:04.262 I/Finsky  (17437): [223] VerifyInstallTask.j(3): Verifying id=56, result=-1
<b>06-02 16:54:04.266 I/Finsky  (17437): [223] adnh.a(7): Verify: Installation silently blocked. package=com.animeworld.app_pro2</b>
06-02 16:54:04.266 I/Finsky  (17437): [2] VerifyInstallTask.mH(6): Verification complete: id=56, package_name=com.animeworld.app_pro2
06-02 16:54:04.269 I/Finsky  (17437): [2] VerifyInstallTask.h(1): Verification stage already finished, ignoring sub-task callback
06-02 16:54:04.276 D/BoundBrokerSvc(19628): onBind: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
06-02 16:54:04.277 D/BoundBrokerSvc(19628): Loading bound service for intent: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
06-02 16:54:04.299 E/RestoreOp(18223): A (re)install was necessary but couldn't perform it.
06-02 16:54:04.299 E/RestoreOp(18223): io.github.muntashirakon.AppManager.backup.BackupException: A (re)install was necessary but couldn't perform it.
06-02 16:54:04.299 E/RestoreOp(18223): 	at io.github.muntashirakon.AppManager.backup.RestoreOp.restoreApkFiles(RestoreOp.java:288)
06-02 16:54:04.299 E/RestoreOp(18223): 	at io.github.muntashirakon.AppManager.backup.RestoreOp.runRestore(RestoreOp.java:173)
06-02 16:54:04.299 E/RestoreOp(18223): 	at io.github.muntashirakon.AppManager.backup.BackupManager.restore(BackupManager.java:162)
06-02 16:54:04.299 E/RestoreOp(18223): 	at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:261)
06-02 16:54:04.299 E/RestoreOp(18223): 	at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
06-02 16:54:04.299 E/RestoreOp(18223): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
06-02 16:54:04.299 E/RestoreOp(18223): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-02 16:54:04.299 E/RestoreOp(18223): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-02 16:54:04.299 E/RestoreOp(18223): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-02 16:54:04.299 E/RestoreOp(18223): 	at java.lang.Thread.run(Thread.java:923)
06-02 16:54:04.301 D/RestoreOp(18223): Close called
</pre>

**Comment by MuntashirAkon** [comment]
After a [quick lookup](https://developers.google.com/android/reference/com/google/android/gms/safetynet/VerifyAppsConstants#HARMFUL_CATEGORY_TROJAN), it seems that Google thinks the app contains a trojan. So, I suggest you scan the APK before using it.

**Comment by Mtkmanjaro** [comment]
i tried with "Quick editor" downloaded from play store same results restore falied, because i was aware of the safety net bullshit, there's tons of worse apps in play store and safety net ignore it. choose an app i will try to do a restore and  when falied let see what logs has to say

**Comment by EsEnZeT** [comment]
Same issues, restore for apk/data never worked for me...

**Comment by Mtkmanjaro** [comment]
@EsEnZeT  to be honest never worked on Q for me, neither on A11 no matter on what apk you tried is just broken, and since there's better tools for restore and backup is no a big deal

**Comment by MuntashirAkon** [comment]
Unfortunately, we haven't got enough testers for back up/restore to actually test the feature on these devices. As a result, I just push it as long as it works on my device. It would be very nice if you supplied some logs so that I could figure out what went wrong.

**Comment by MuntashirAkon** [comment]
I've added a fix in baf0bfb1 that was reported earlier. However, I don't know if it's related to this issue since no logs are provided thus far.

**Comment by Mtkmanjaro** [comment]
@MuntashirAkon   there's something in the logs about this but also there's a ton of error so idk there's AVC selinux denied etc, restore function is just broke Af

06-09 17:28:21.298 E/RestoreOp(5189): 	at io.github.muntashirakon.AppManager.utils.TarUtils.extract(TarUtils.java:194)

06-09 17:28:21.298 E/RestoreOp(5189): 	at io.github.muntashirakon.AppManager.utils.TarUtils.extract(TarUtils.java:177)

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon there's something in the logs about this but also there's a ton of error so idk there's AVC selinux denied etc, restore function is just broke Af

The SELinux issues in the last logs were irrelevant i.e. they were unrelated to App Manager.

And kindly share the full logs instead of just _what you think is relevant_. There might be issues that is beyond your understanding such as the previous one.

**Comment by Mtkmanjaro** [comment]
@MuntashirAkon  i sent you the full logs many times, in "paste bin" even one time i sent you a full log by mail for security reasons ,just look a few comments top, so to give you the reason,  this time no log, despite i have store the full logs, have nice day

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon i sent you the full logs many times, in "paste bin" even one time i sent you a full log by mail for security reasons ,just look a few comments top, so to give you the reason, this time no log, despite i have store the full logs, have nice day

The only useful logs you sent me were the one via email.
