### ISSUE TITLE
could not fetch package info for Swype keyboard

### ISSUE THREAD

**Issue by Raj52537** [MuntashirAkon/AppManager#472]
**Describe the bug**
Not actually a bug it might be due to app not in the app manager database
App name is com.nuance.swype.dtc.india downloaded from apkpure.
Since app is not open source I just want to extract its activities and disable unnecessary ones
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to main screen
2. Click on app called Swype keyboard by nuance (discontinued in 2018) 

**Expected behavior**
Using app property screen
**Screenshots**
![Screenshot_20210607-165412380](https://user-images.githubusercontent.com/81609264/121029634-62cd3600-c7c6-11eb-8d8a-c106aa3815eb.jpg)

**Crash logs**
Not actually since app does not crashed
https://telegra.ph/gs-06-07-2.

**Device info**
 - Device: Xiaomi Redmi 6 pro
 - OS Version: 11 using custom Rom (Derpfest os)
 - App Manager Version: [v2.6.1 34187] downloaded from telegram release channel
 - Mode: root

**Additional context**

**Comment by MuntashirAkon** [comment]
Fixed in 4aae1070
