### ISSUE TITLE
App initialising for ever on Android 7.0

### ISSUE THREAD

**Issue by Sami32** [MuntashirAkon/AppManager#474]
Hello,

It seem that a regression bug affect your App (v2.6.1 from F-Droid), with Android 7.0 at least, that make the start initializing for ever.

**Comment by MuntashirAkon** [comment]
Possible duplicate of #466

**Comment by MuntashirAkon** [comment]
Closed because no template was used.

**Comment by Sami32** [comment]
That could be because i'm using a Xiomi Redmi Note 4. Also i only get an endless initializing message at start.
I can confirm that v2.6.0 work fine.

**Comment by MuntashirAkon** [comment]
> That could be because i'm using a Xiaomi Redmi Note 4.

I'm currently downloading Android 7 ISO file to test it myself. (I'm currently living in a village, so the Internet speed is way too slow here.)

**Comment by MuntashirAkon** [comment]
Duplicate of #466

**Comment by MuntashirAkon** [comment]
The issue has been fixed as mentioned in the linked issue.
