### ISSUE TITLE
Font scaling and formatting issue

### ISSUE THREAD

**Issue by Sami32** [MuntashirAkon/AppManager#475]
View the App manifest file in your App doesn't fit nicely, at least using v2.6.0 with a 5" smartphone running Android 7.0.
See the comparison with an other manifest viewer:
![IMG_20210611_143058](https://user-images.githubusercontent.com/18471069/121687339-c2bb2980-cab1-11eb-934e-879d3c42e4cb.jpg)
App Manager:
![IMG_20210611_142955](https://user-images.githubusercontent.com/18471069/121687351-c64eb080-cab1-11eb-844c-55ad75bdf6cd.jpg)

**Comment by MuntashirAkon** [comment]
Just for the record: The launchMode="singleTask" is correct ([there's no such launch mode as "multiple"](https://developer.android.com/guide/topics/manifest/activity-element#lmode)).

**Comment by MuntashirAkon** [comment]
For now, you can just disable soft wrapping using the **wrap** symbol on top-right side of the page.

**Comment by Sami32** [comment]
Yeah, that why i said nothing about the launchmode because these snapshots has also been sent to the other App owner for this purpose ;)
