### ISSUE TITLE
Prevent app at start up

### ISSUE THREAD

**Issue by fusionneur** [MuntashirAkon/AppManager#478]
Is it possible to prevent an app from starting at phone startup via AM? For example to prevent spotify running in background (also a notification appears)

**Comment by MuntashirAkon** [comment]
Currently, AM doesn't provide an option to see which app _broadcast_ components run at startup (#309). However, you can look at the broadcasts tab and block any component there. It's usually called startup receiver or something similar.

**Comment by MuntashirAkon** [comment]
Duplicate of #316

**Comment by fusionneur** [comment]
For broadcast tab, you mean the receivers tab ? thanks

**Comment by MuntashirAkon** [comment]
> For broadcast tab, you mean the receivers tab ?

Yes.
