### ISSUE TITLE
App crashes in details page of any app.

### ISSUE THREAD

**Issue by shavez2315** [MuntashirAkon/AppManager#48]
App crahses when opening other tabs like Activities, services, recievers in details page of any app.

Device : Mi A3 (Android one)
Android version: 10

Same behaviour on Nokia 6.1 plus (Android one)

Expected behaviour:
Details about activities, services, recievers when tab is switched in app details page.

Actual behaviour:
App crashes as soon as tab is switched.

Awesome app!

**Comment by MuntashirAkon** [comment]
Please include the following info:
- App Manager version
- Crashlog
- Mode of operation: ADB/no-root/root

Install the latest debug builds from [here](https://github.com/MuntashirAkon/AppManager/actions?query=workflow%3A%22Debug+Build%22) to see if you can reproduce the issue.

**Comment by shavez2315** [comment]
> Please include the following info:
> - App Manager version

2.5.9

> - Crashlog

I will provide in a few hours.

> - Mode of operation: ADB/no-root/root

No-root

> 


> Install the latest debug builds from [here](https://github.com/MuntashirAkon/AppManager/actions?query=workflow%3A%22Debug+Build%22) to see if you can reproduce the issue.

Okay I will try these.

**Comment by MuntashirAkon** [comment]
The issue should be fixed in the latest release.

**Comment by shavez2315** [comment]
Yes it is fixed. Thanks. Great app!
