### ISSUE TITLE
Differentiate releases from prereleases

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#480]
F-Droid official client fails to display the current stable version of App Manager if IzzyOnDroid repository is added to the list of repositories. As a result, it's confusing to everybody about the current status of App Manager. For instance, we've made two releases: v2.6.0 (the major release) and v2.6.1 (a minor release), yet the F-Droid client displays that the last update is about 2 months ago. To mitigate this issue, I'm giving a separate package name for the prereleases.

So, we would now have three separate package names:

**Stable Release:** `io.github.muntashirakon.AppManager` (App Manager)
**Pre-release:** `io.github.muntashirakon.AppManager.pre` (AM Pre-release)
**Debug release:** `io.github.muntashirakon.AppManager.debug` (AM Debug)

**Comment by MuntashirAkon** [comment]
@IzzySoft: I request you to remove **App Manager** from the IzzyOnDroid repository immediately, and add **AM Pre-release** when a new pre-release has been made. The metadata should be the same except the package name and the app label i.e. the pre-releases will continue to have the `pre-` prefixes in them. Thanks.

**Comment by MuntashirAkon** [comment]
Fixed in 87ff26ff

**Comment by IzzySoft** [comment]
Apologies for the late reply, too many things to take care of… So basically, once the next pre-release is made it comes with a different package name then – while the same "pattern" for grabbing the APK file applies? That would be ideal as then my updater will yell at the packageName mismatch when you're ready and thus give me the signal to change :wink:

**Comment by MuntashirAkon** [comment]
Correct. It's too bad that the world is not a perfect place. But then again, we might never exist if it was.

**Comment by MuntashirAkon** [comment]
@IzzySoft: It looks like we now have almost 400 subscribers in the [Debug channel](https://t.me/AppManagerDebug) on Telegram (and I don't know how many follows the actions at GitHub). So, I am giving up making any pre-releases in order to release my burden (instead the debug releases will be signed using a non-public key in order to make them more secure). So, here at last, App Manager has to go away from your F-Droid repository (since most of the F-Droid clients are still having issues detecting new updates).

_As always, I am working on reviving a few more exciting apps. Hopefully people might find them in your repo during the testing phase. Thanks!_

**Comment by IzzySoft** [comment]
Done (effective with the next sync today). And yes, be welcome with the other revivals :smiley:

**Comment by IzzySoft** [comment]
> So, here at last, App Manager has to go away from your F-Droid repository (since most of the F-Droid clients are still having issues detecting new updates).

You still link to it from your Readme. So shall I restore it – or do you want to remove the link?

**Comment by MuntashirAkon** [comment]
> You still link to it from your Readme. So shall I restore it – or do you want to remove the link?

Thanks for noticing. I forgot to remove it.

**Comment by IzzySoft** [comment]
OK, thanks! I just was a little bit confused when recommending your app and, while checking for the repo link, found the badge still there :see_no_evil:
