### ISSUE TITLE
initializing forever (2.6.0)

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#485]
- [ ✓] I know what my device, OS and App Manager versions are
- [ ✓] I know how to take logs
- [ ✓] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
AM are initializing forever (not even req for ADB)

**To Reproduce**
Steps to reproduce the behaviour:
1. Find Apk file then open it via AM
2. (sometime am can instal apk and sometime not by stuck on initializing)
3. if am can't instal apk then bug are triggered now everytime you launch AM it won't work anymore in ADB over TCP

**Expected behavior**
AM can connect to ADB over TCP

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: Realne 5i
 - OS Version: Android Q
 - App Manager Version: 2.6.0
 - Mode: ADB

**Additional context**
installing APK via AM only to trigger the glitch after you success trigger the glitch AM will stuck in initializing screen forever

temp fix:
Re enable usb debugging (after disable pls revoke all req then enable the usb debugging back)

also i used latest sdk platform tools.zip binary to run ADB over TCP

**Comment by NSTAdventure** [comment]
why? @MuntashirAkon 

fixed on milestones release?

**Comment by MuntashirAkon** [comment]
Only latest or supported releases are supported like any other projects.

**Comment by NSTAdventure** [comment]
> Only latest or supported releases are supported like any other projects.

wait but in f droid there is no new version yet :( or still otw?

**Comment by MuntashirAkon** [comment]
> wait but in f droid there is no new version yet :( or still otw?

v2.6.1 was published in 5 June, 2021, more than 15 days ago.

https://f-droid.org/packages/io.github.muntashirakon.AppManager/

**Comment by NSTAdventure** [comment]
> > wait but in f droid there is no new version yet :( or still otw?
> 
> v2.6.1 was published in 5 June, 2021, more than 15 days ago.
> 
> https://f-droid.org/packages/io.github.muntashirakon.AppManager/

dang it nvm sorry sir

i forgot if i ignore those update on f droid setting :(

**Comment by MuntashirAkon** [comment]
Duplicate of #454
