### ISSUE TITLE
RescheduleReceiver remains displayed as deactivated although it has been reactivated by the app

### ISSUE THREAD

**Issue by bege10** [MuntashirAkon/AppManager#491]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
AFAIK apps can re-activate the RescheduleReceiver. If I have deactivated it and use the app, afterwards the receiver is activated again. This is confirmed in the permission settings of 3C All-In-One Toolbox and by the fact that the app starts after BOOT_COMPLETED again. But in App Manager the receiver is still displayed as deactivated. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Deactivate ResceduleReceiver of an app that starts after BOOT_COMPLETED
2. Run the app e.g. Firefox and close it.
3. Check other App that handles permissions: The receiver is active again.
4. Check App Manager: The receiver is still displayed as deactivated.

**Expected behavior**
Show the correct state of receiver

**Device info**
 - Device:Fairphone 3
 - OS Version: /e/OS (based on FairphoneOS, LineageOS for microG, Android 10)
 - App Manager Version: 2.6.1
 - Mode: root/Magisk

**Additional context**

**Comment by MuntashirAkon** [comment]
> by the fact that the app starts after BOOT_COMPLETED again.

Can you actually confirm this? _Not really looking to installing Firefox._ The component should have stayed blocked even if it is displayed as unblocked in other apps.

**Comment by MuntashirAkon** [comment]
Also, read this: https://muntashirakon.github.io/AppManager/en/#x1-1640004.1.2

I haven't really carried out any tests on Intent actions, but this could also be the reason.

**Comment by bege10** [comment]
> 
> 
> Also, read this: https://muntashirakon.github.io/AppManager/en/#x1-1640004.1.2
> 
> I haven't really carried out any tests on Intent actions, but this could also be the reason.

I looked for the mentioned apps to see what they say, but the Blocker website says:

> In version 2.0, Watt has completely abandoned disabling components through the Intent Firewall, because ifw will cause android10+ devices to keep restarting. In view of this poor performance, Watt 2.0 uses pm commands to refactor the entire application.

For Blocker I don't find an APK.

**Comment by MuntashirAkon** [comment]
> I looked for the mentioned apps to see what they say, but the Blocker website says:
> 
> > In version 2.0, Watt has completely abandoned disabling components through the Intent Firewall, because ifw will cause android10+ devices to keep restarting. In view of this poor performance, Watt 2.0 uses pm commands to refactor the entire application.

Blocking components through Package Manager is very unstable/unusable as explained in the docs. As a result, we use both Package Manager and IFW. Even then, there are limitations as explained in the docs. I haven't found any evidence of performance issues on Android 10+ devices (I use Android 11). The Intent Firewall implementation remained the same since Android 5. If such cases do exist, it is most probably device specific and/or done intentionally.

**Comment by MuntashirAkon** [comment]
Any updates on this issue?

**Comment by MuntashirAkon** [comment]
Fixed in b8f5ea53395e0ed94009e0eaa1bd8295a7401531
