### ISSUE TITLE
How can I prevent apps from start after BOOT_COMPLETED?

### ISSUE THREAD

**Issue by bege10** [MuntashirAkon/AppManager#492]
**Describe your problem(s)**
AFAIK apps can and do reactivate the RescheduleReceiver so that I cannot prevent them from start after BOOT_COMPLETED.
Is there a way App Manager can help to accomplish this?

**Additional contexts**
Add any other context or screenshots about the feature/documentation here.
#491

**Comment by MuntashirAkon** [comment]
> Is there a way App Manager can help to accomplish this?

**No.** App Manager can only block app components, not actions. However, it has been planned. See #447 and #309.
