### ISSUE TITLE
Clear app cache in the main menu.

### ISSUE THREAD

**Issue by kuruptos** [MuntashirAkon/AppManager#494]
I'd think it would be of great utility if it was possible to clear app cache through the app selection screen:
![1](https://user-images.githubusercontent.com/83143475/123597433-dd480f00-d7e2-11eb-9a80-b487b22ca4dc.png)
I imagine the option would be located near the "clear app data" button.

Adding a feature like this would make cache cleaning a very simple task for LineageOS 15 or above users (No way to clear all app cache in one go). This feature would also make this a great open-source alternative to SD Maid, as giving root permissions to proprietary apps can be pretty scary.

Thanks for reading.

**Comment by MuntashirAkon** [comment]
Implemented in 13ce4a84
