### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by trunggiaothuy** [MuntashirAkon/AppManager#496]
I clone source code in https://github.com/MuntashirAkon/AppManager and
run by android studio 4.1.3, then an error occurs " Execution failed for task ':server:build'.
> A problem occurred starting process 'command 'E:\MyProject\Test\AppManager-2.6.1/scripts/check_am_server.sh''.
What should I do, please tell me how to fix it. Thanks you.

**Comment by MuntashirAkon** [comment]
Which operating system?

**Comment by trunggiaothuy** [comment]
> Which operating system?

I run on WINDOWS operating system

**Comment by MuntashirAkon** [comment]
> I run on WINDOWS operating system

It looks like you haven't read the README. Windows is not supported.

**Comment by trunggiaothuy** [comment]
> > I run on WINDOWS operating system
> 
> It looks like you haven't read the README. Windows is not supported.

ok thanks you, maybe i was missing that part, if i run the app now on MAC OS then i follow this guide https://github.com/MuntashirAkon/AppManager/blob/master/BUILDING.rst before build apk using android studio

**Comment by MuntashirAkon** [comment]
> ok thanks you, maybe i was missing that part, if i run the app now on MAC OS then i follow this guide https://github.com/MuntashirAkon/AppManager/blob/master/BUILDING.rst before build apk using android studio?

Yes.

**Comment by trunggiaothuy** [comment]
The following steps are required only if you want to build APKS:

Sorry i followed the instructions and moved the os to mac, the configuration is as follows but the build of the app with android studio still fails, can you help me, thanks you

Install Homebrew:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
Install bundletool:

brew install bundletool

+ Here is the link image configuration bundletool on mac:
   => https://drive.google.com/file/d/1sN90DPjacJaeP0XacZBFieR__YFwypvQ/view?usp=sharing
+ Here is the link image build app on android studio error
https://drive.google.com/file/d/1F6E3HG-3zCsGrH2aimUDXuoI_rb_0BM_/view?usp=sharing

**Comment by MuntashirAkon** [comment]
This is weird. Try running `./scripts/make_docs.sh` in the Terminal (PWD must be the project root).

_We don't like Google's proprietary products, so upload the images/logs here directly instead of sharing the links to Google drive._

**Comment by trunggiaothuy** [comment]
``

**Comment by trunggiaothuy** [comment]
ok, i running /scripts/make_docs.sh in terminal in root project but it looks like the picture below, I don't know where to type the command
<img width="1440" alt="Screen Shot 2021-07-01 at 10 30 45" src="https://user-images.githubusercontent.com/12692743/124060628-aa5a8100-da57-11eb-981f-925c5a8c9c4e.png">

**Comment by MuntashirAkon** [comment]
> ok, i running /scripts/make_docs.sh in terminal in root project but it looks like the picture below, I don't know where to type the command

CD to the root directory of App Manager repository (which is also the project root) and run the command: `./scripts/make_docs.sh`. If it says `no such file or directory`, it probably means you haven't cloned the repository properly.

All scripts has to be run from the root directory. Otherwise they won't work.

**Comment by trunggiaothuy** [comment]
ok, thanks you, I built the app, may I ask further, I see screenshots in github has something like the image below but when I run the application and test it, I can't find this place, can you tell me where it is in app?
![github_qs](https://user-images.githubusercontent.com/12692743/124064879-e1cd2b80-da5f-11eb-894f-ec7cfeaa39fc.png)

**Comment by MuntashirAkon** [comment]
It's under the three dots menu. See docs: https://muntashirakon.github.io/AppManager/en/#x1-260002.1.5.4
