### ISSUE TITLE
[Feature] Enable/disable application components

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#5]
### This is dependent on issue #2

A useful and sensible feature to be added would be to allow the user to disable specific app components (services, broadcast receivers, activities and content providers).

This could be used to e.g. disable Google Analytics or Measurement services.

This would be similar to what MyAndroidTools has:
https://www.myandroidtools.com/

MAT has a very nice UI/UX for that: it allows the user to see a list of the receivers of all installed apps, filter them by name and batch disable.

**Comment by MuntashirAkon** [comment]
I have plans to merge Watt which let you disable activities, receivers and services. But it may take some time as it is written in Kotlin.

**Comment by MuntashirAkon** [comment]
Partially fixed in the 0882b02. Blocking content providers via IFW should be supported but I don't yet know how. Currently you can only block activities, broadcast receivers and services.

**Comment by MuntashirAkon** [comment]
I don't find any documentation on how content providers can be blocked via IFW. So, I might only add blocking via `pm`.

**Comment by MuntashirAkon** [comment]
It's final: for providers, I'll only add blocking via `pm`. Other components will still be blocked via Intent Firewall due to its superiority.

**Comment by MuntashirAkon** [comment]
Fixed via 9fa7755
