### ISSUE TITLE
When using the configuration function’s BUG

### ISSUE THREAD

**Issue by MAT-OUT** [MuntashirAkon/AppManager#500]
when using the configuration function, there is a question of selecting all applications. I can’t just select the application I searched for. In addition, it is recommended to strengthen the filtering function here, which is really bad

**Comment by MuntashirAkon** [comment]
Closed because the issue doesn't follow any template.

**Comment by MuntashirAkon** [comment]
By the way, what is “configuration function”?

**Comment by MAT-OUT** [comment]
> 
> 
> By the way, what is “configuration function”?

emm,Configuration features in the menu...

**Comment by MuntashirAkon** [comment]
> emm,Configuration features in the menu...

I still don't get it. Create another issue with the issue template containing screenshots of the feature you're talking about.

**Comment by MAT-OUT** [comment]
> 
> 
> By the way, what is “configuration function”?



> 
> 
> > emm,Configuration features in the menu...
> 
> I still don't get it. Create another issue with the issue template containing screenshots of the feature you're talking about.

sorry,Translation problems have caused you confusion, I will take screenshots and reorganize the grammar
