### ISSUE TITLE
Profiles bug

### ISSUE THREAD

**Issue by MAT-OUT** [MuntashirAkon/AppManager#501]
**Describe the bug**
When I use the profiles feature and select an application, its own search feature is wrong: search for the keywords of the application I need, and then select all, but at this time all the applications (including those that have not been searched) are selected
![Screenshot_20210702-141622_App_Manager](https://user-images.githubusercontent.com/62179039/124231612-12d25c80-db43-11eb-8f94-1b5c659154a3.png)
![Screenshot_20210702-141633_App_Manager](https://user-images.githubusercontent.com/62179039/124231616-149c2000-db43-11eb-9e78-e12c4c3486d9.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. open profiles feature
2. select apps
3. search keywords
4. select all

**Expected behavior**
Only select the apps I search

**Screenshots**

![Screenshot_20210702-141622_App_Manager](https://user-images.githubusercontent.com/62179039/124231641-1fef4b80-db43-11eb-928f-087a447dd855.png)
![Screenshot_20210702-141633_App_Manager](https://user-images.githubusercontent.com/62179039/124231646-21207880-db43-11eb-8941-0bb0f7217b14.png)

**Crash logs**
none

**Device info**
 - Device: [redmi note5]
 - OS Version: [Android 11]
 - App Manager Version: [2.6.2]
 - Mode: root

**Additional context**
I hope to enhance the filtering features to select specific applications in profiles

**Comment by MuntashirAkon** [comment]
Fixed in 55241014
