### ISSUE TITLE
Notifications aren't being displayed in Android TV

### ISSUE THREAD

**Issue by rex07** [MuntashirAkon/AppManager#507]
- [✓] I know what my device, OS and App Manager versions are
- [✓] I know how to take logs
- [✓] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the app then 'The app stuck on initializing screen'
2. It loop on the initializing

**Expected behavior**
A adk.

**Screenshots**

![](https://i.imgur.com/8EsyLUm.jpg)
**Crash logs**

[log(1).txt](https://github.com/MuntashirAkon/AppManager/files/6777523/log.1.txt)
[log.txt](https://github.com/MuntashirAkon/AppManager/files/6777524/log.txt)

**Device info**
 - Device: [android tv]
 - OS Version: [Android 9]
 - App Manager Version: [v2.7.0-DEBUG#1387 and V2.6.2]
 - Mode: adb/no-root

**Additional context**

**Comment by MuntashirAkon** [comment]
Your logs are filtered using package name which excludes most of the important logs. Share logs without any filter. By the way, since you've tried using ADB, see #466 first.

**Comment by rex07** [comment]
Full System log dump
[log(2).txt](https://github.com/MuntashirAkon/AppManager/files/6778073/log.2.txt)

**Comment by MuntashirAkon** [comment]
Logs are saying that App Manager asked for a KeyStore password and you haven't provided any. You have to create a new KeyStore password, otherwise it wouldn't work. See #467.

**Comment by rex07** [comment]
How can I provide any on frozen app on tv

**Comment by MuntashirAkon** [comment]
> How can I provide any on frozen app on tv

There should be a popup notification asking for a password.

**Comment by rex07** [comment]
There is noting 
not any notification

**Comment by MuntashirAkon** [comment]
> not any notification

No idea, then. I don't have any Android TV to test. Try v2.6.0 first.

**Comment by rex07** [comment]
V2.6.0 works fine
![screenshot_1625679511385](https://user-images.githubusercontent.com/13156001/124804941-81f4ea00-df63-11eb-8f96-da1589d87cdd.png)

**Comment by MuntashirAkon** [comment]
> V2.6.0 works fine

Yeah, as expected. Now, navigate to **Settings** > **APK Signing**. You should see a notification immediately there. Let me know if you can see one.

**Comment by rex07** [comment]
Yes an Adb debugging notification

**Comment by MuntashirAkon** [comment]
> Yes an Adb debugging notification

Nothing on KeyStore? That's really odd.

**Comment by rex07** [comment]
Unfortunately nothing on keystore

**Comment by MuntashirAkon** [comment]
> Unfortunately nothing on keystore

Okay. I think this requires some broad investigation. It's already late night here. So, I'll try to figure it out in the next day. Thanks for reporting the issue.

**Comment by MuntashirAkon** [comment]
Android TV supports notifications only for system apps. So, notifications for App Manager were simply skipped (since it's not a system app). So, I guess I need to find workarounds.

**Comment by MuntashirAkon** [comment]
We've eliminated the need for entering KeyStore password in #513. However, there are still many problems regarding notifications that need addressing such as installation confirmation (in app installer) and service notifications.

**Comment by MuntashirAkon** [comment]
In 0eaa6f21, notifications during app installation are disabled for Android TV (Oreo or later). So, you should now be able install APK without issues.
