### ISSUE TITLE
Enhanced support for installing apps with a different signature

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#509]
Since Android 10, Google quietly added an option to disable package verification, the one and only way to verify if a package is from the right place i.e. there isn't any external modification in place. I'm aware of this from the start, but Google Play's recent announcement on taking signatures on their own hands from the developers and recent updates to Google apps are drawing attention to developers and security researchers.

With the introduction of v4 signature (#178), package verification became optional to the Android package manager when the APK's being installed by Google Play Store (since v4 signature has an external `idsig` file to verify contents of an APK). However, this also means that both the developers and the end users have to trust Google (nobody with their sane mind would trust Google, or any corporations for that matter). However, Amazon's been doing that for years yet nobody seem to have complained, so my guess would be people do trust these companies (even when they're own employees do not).

Consequently, in the next few months, the fans and supporters of Google monopoly would see a lot of apps having different signatures, and without disabling verification, no third-party app will be able to install them on top of the installed app (Google Play Services can do it because it's whitelisted in most ROMs). For user apps, you can simply uninstall and install an app, but for system apps, this cannot be done easily.

To solve this issue, App Manager may provide an option to disable APK verification from Android 11 (may or may not include 10) which would be strictly applicable to the Google Play apps (Yes, Google will provide a way to detect if the app has been _infected_ with Google MitM).

**Comment by MuntashirAkon** [comment]
Related issue #346.

**Comment by wenchiching** [comment]
according to AOSP source
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/util/apk/ApkSignatureVerifier.java;l=91
if there is a V4 signature exist, framework will keep checking V2(or V3) to make sure V4, V2(or V3) are signed with same key
package verification will never become optional

**Comment by MuntashirAkon** [comment]
> according to AOSP source
> https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/util/apk/ApkSignatureVerifier.java;l=91
> if there is a V4 signature exist, framework will keep checking V2(or V3) to make sure V4, V2(or V3) are signed with same key
> package verification will never become optional

Not sure how's that relevant. But in any case, this has already been described in the link in #178 (v4 itself makes use of v2/v3 signatures). The issue is that since Android 10, Android provides an option to disable signature verification during APK installation (UID `1000` specific though). When `INSTALL_DISABLE_VERIFICATION` is set during installation, system can install an app without any verification.

**Comment by MuntashirAkon** [comment]
Instead, I've added support for the following:
1. Support for apps with proof of rotation (70c6b5ea)
2. Detect possible MitM by Google (66ac9262)
