### ISSUE TITLE
Initializing 2.6.2

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#512]
- [ ✓] I know what my device, OS and App Manager versions are
- [ ✓] I know how to take logs
- [✓ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Sometimes am stuck on initializing and no key notifications

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and instal AM 
2. Launch AM
3. Stuck forever

**Expected behavior**
Adb over TCP should working?

**Screenshots**

**Crash logs**
[log.txt](https://github.com/MuntashirAkon/AppManager/files/6796041/log.txt)

**Device info**
 - Device: Realme 5i
 - OS Version: Android Q
 - App Manager Version: 2.6.2
 - Mode: ADB

**Additional context**
Ok so after trying again today it's looks like Am working but sometime they stuck like that tho :( i hate to always restarting to fix this issues :(((((((((

**Comment by MuntashirAkon** [comment]
Logs suggested that a notification was displayed and the password prompt has been displayed and closed, so I don't find anything wrong with it. The only case where the initialization screen stuck forever is when you do not insert a mandatory KeyStore password. It has a timeout for two minutes in all the other cases.

**Comment by NSTAdventure** [comment]
> Logs suggested that a notification was displayed and the password prompt has been displayed and closed, so I don't find anything wrong with it. The only case where the initialization screen stuck forever is when you do not insert a mandatory KeyStore password. It has a timeout for two minutes in all the other cases.

sorry for mistundestanding
what i mean is sometime these notifications not appear that's why i open issues and provide that log

**Comment by MuntashirAkon** [comment]
It would only appear once.
