### ISSUE TITLE
Running apps endless loading

### ISSUE THREAD

**Issue by BloodReleasesPain** [MuntashirAkon/AppManager#514]
- [X ] I know what my device, OS and App Manager versions are
- [X ] I know how to take logs
- [X ] I know how to reproduce the issue which may not be specific to my device

When entering "running apps", it loads infinitely.

![Screenshot_20210712-051054_AM Debug.jpg](https://user-images.githubusercontent.com/43686736/125285935-0f23a000-e2d0-11eb-81dc-260ee9a4a62a.jpg)

I will send a full unfiltered log through email since logs from /storage/emulated/0/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log  doesn't show anything. 

**Device info**
 - Galaxy S7 Edge 8.0.0
 - Debug #1402
 - ADB over TCP

**Comment by MuntashirAkon** [comment]
Seems to be present only in v2.7.0 variants.

**Comment by BloodReleasesPain** [comment]
> Seems to be present only in v2.7.0 variants.

I can attest to that.

**Comment by MuntashirAkon** [comment]
@BloodReleasesPain: Can you confirm if #521 fixes this issue?

**Comment by BloodReleasesPain** [comment]
> @BloodReleasesPain: Can you confirm if #521 fixes this issue?

I can confirm the issue is fixed 👍🏻

**Comment by MuntashirAkon** [comment]
Thanks @d4rkk3y for the fix.
