### ISSUE TITLE
Themes related issue (some buttons & text unseen)

### ISSUE THREAD

**Issue by zputnyq** [MuntashirAkon/AppManager#523]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

Hi @MuntashirAkon 
It's my first time using app manager, it's really great. Thanks, I really appreciate it.
There are issues related to theme on my device. On day theme including "follow system" back button, home & recent buttons are unseen. While on night theme base backup's text is unseen (the text is black similar to the box background).

**To Reproduce**
Steps to reproduce the behaviour:

Issue on Day & follow system theme on my device

1. Use day/follow system theme
2. Back button, home & recent buttons are unseen

Issue on night theme

1. Go to settings & change the App Theme to night
2. Click on an app then backup button under the app's icon
3. See unseen text (black text)

**Expected behavior**
those buttons & text should be seen

**Screen shot**
![_20210721_231901](https://user-images.githubusercontent.com/31039796/126531287-07aaec9d-6552-4d83-a164-36b68c608cc6.JPG)
![_20210721_231930](https://user-images.githubusercontent.com/31039796/126531339-09cc9e5e-d81c-42bb-9039-558733b935b0.JPG)

**Device info**
 - Device: [Sony Xperia M4 Aqua]
 - OS Version: [stock android 6 ]
 - App Manager Version: [v2.6.2]
 - Mode: root/adb/no-root

**Logs**
Only saw some javabinder error when using day / follow system theme
[logcat.txt](https://github.com/MuntashirAkon/AppManager/files/6860216/logcat.txt)

**Comment by MuntashirAkon** [comment]
Fixed in 3b158e25 and 93e0e8c9.
