### ISSUE TITLE
(Auto) blocking of only trackers

### ISSUE THREAD

**Issue by UltraBlackLinux** [MuntashirAkon/AppManager#524]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
I am using AdAway, and just recently discovered, that it apparently supports exactly, what I need: It can block ads and send the app a "nerfed" ad simultaneously, so I won't get ad-locked.
For this to work though, I need to be able to choose, what to block, in this case only the trackers, and not also the ad activities.

**Describe the solution you'd like**
Allow blocking ads and trackers separately

(Also I'd love AM to block trackers for newly installed apps automagically ;) )

**Comment by MuntashirAkon** [comment]
> Allow blocking ads and trackers separately

Unfortunately, Exodus doesn't distinguish between ads and trackers, so we too can't. Consider asking the Exodus authors to distinguish between ads and trackers.

> (Also I'd love AM to block trackers for newly installed apps automagically ;) )

Duplicate of #40.

**Comment by UltraBlackLinux** [comment]
isn't AM using a custom blocker of yours?

**Comment by MuntashirAkon** [comment]
> isn't AM using a custom blocker of yours?

I no longer maintain a custom list. They're all merged with Exodus.
