### ISSUE TITLE
Bug displaying app details

### ISSUE THREAD

**Issue by tommynok** [MuntashirAkon/AppManager#526]
1-AM randomly freezes after viewing app details.
This happens when I try to exit the details tab and go to the main AM window.

2-When I try to view the details of an application, I see an "app not installed" notification.
This happens with two applications, system and user .

Device - Lenovo p1
OS- 6.0.1
Mode - root
AM version - 2.7.0-1428 (391)
[2-2021-07-23_154721_logcat_noinst.txt](https://github.com/MuntashirAkon/AppManager/files/6869415/2-2021-07-23_154721_logcat_noinst.txt)
[1-2021-07-23_154244_logcat_alru.txt](https://github.com/MuntashirAkon/AppManager/files/6869416/1-2021-07-23_154244_logcat_alru.txt)

**Comment by MuntashirAkon** [comment]
> 2-When I try to view the details of an application, I see an "app not installed" notification.
> This happens with two applications, system and user .

Try d6058524. AM should now crash for these apps. If this happens, share the crashlogs here.

---

I suggest you add `StatusBarManager` in the **Filter out tags section** next time you take any logs. They're very annoying.

**Comment by MuntashirAkon** [comment]
> 1-AM randomly freezes after viewing app details.
> This happens when I try to exit the details tab and go to the main AM window.

Retake logs with the latest debug build. Also, tell me the filter/sort options you've used in the main page.

**Comment by tommynok** [comment]
> Try [d605852](https://github.com/MuntashirAkon/AppManager/commit/d6058524268c4c8a0bf13d77201cca20435b9b5f). AM should now crash for these apps. If this happens, share the crashlogs here.

Version 2.7.0-1435 - no crashes for these applications.


> Retake logs with the latest debug build. Also, tell me the filter/sort options you've used in the main page.

I was unable to reproduce this bug using version 2.7.0-1435
  Anyway, for filtering and sorting, I used the default settings.

--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------
However, the bug (numbered 2) that I described in the initial post is repeated in the debug version **2.7.0-1455**.
[logcat_08-05-2021_03-03-45.zip](https://github.com/MuntashirAkon/AppManager/files/6935052/logcat_08-05-2021_03-03-45.zip)

**Comment by MuntashirAkon** [comment]
Sorry, I forgot to log some important failures. Could you take logs again using the latest debug build?

**Comment by tommynok** [comment]
> take logs again using the latest debug build

[logcat_08-07-2021_13-15-03.zip](https://github.com/MuntashirAkon/AppManager/files/6948920/logcat_08-07-2021_13-15-03.zip)

**Comment by MuntashirAkon** [comment]
First issue could be fixed by 42b04c4b

**Comment by tommynok** [comment]
> First issue could be fixed by [42b04c4](https://github.com/MuntashirAkon/AppManager/commit/42b04c4be759421816dc8eaa2f5bcbb8d339ed75)

Yes, this bug seems to be fixed.
But I faced a new one
AM crash after clicking "App Usage"

[logcat_09-08-2021_20-24-33.txt](https://github.com/MuntashirAkon/AppManager/files/7130887/logcat_09-08-2021_20-24-33.txt)
[AM_log.txt](https://github.com/MuntashirAkon/AppManager/files/7130888/AM_log.txt)

**Comment by MuntashirAkon** [comment]
> AM crash after clicking "App Usage"

Fixed in c0f42b57

**Comment by MuntashirAkon** [comment]
Second issue might be fixed in 8ac3de4b

**Comment by tommynok** [comment]
> Second issue might be fixed in [8ac3de4](https://github.com/MuntashirAkon/AppManager/commit/8ac3de4b2120ba22a210d4133e24422e4bbf0f41)

Yes, now everything is ok!
Thanks for the fix.
