### ISSUE TITLE
Option to backup to external storage

### ISSUE THREAD

**Issue by Thewisem** [MuntashirAkon/AppManager#533]
- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

**Is your feature request related to a problem? Please describe.**
It is storage consuming to make backups on internal storage as it can fill the storage before finishing it.
**Describe the solution you'd like**
An option to create backup on sd card path.
**Describe alternatives you've considered**
A popup of the location for the user to choose to make backup.
**Additional context**

**Comment by MuntashirAkon** [comment]
Already available.  See docs: https://muntashirakon.github.io/AppManager/en/#x1-1080002.6.8.5

**Comment by Thewisem** [comment]
It is shown in the document that this is always internal storage

**Comment by Thewisem** [comment]
Problem is it won't back up

**Comment by Thewisem** [comment]
It will say fail to backup when changed to to sd card

**Comment by MuntashirAkon** [comment]
Open another issue with logs.
