### ISSUE TITLE
Sort by size

### ISSUE THREAD

**Issue by BloodReleasesPain** [MuntashirAkon/AppManager#535]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

I'd like to have an option to sort packages by size from largest to smallest and vice versa to help decide what apps to uninstall, as well as to clear data and/or cache. I'd like to also see storage usage by packages in the app list itself to prevent having to press every package individually to see storage usage.

**Comment by MuntashirAkon** [comment]
> I'd like to have an option to sort packages by size from largest to smallest and vice versa to help decide what apps to uninstall, as well as to clear data and/or cache.

What did you mean by package size? Is it APK size, data size, cache size or a total?

**Comment by BloodReleasesPain** [comment]
> > I'd like to have an option to sort packages by size from largest to smallest and vice versa to help decide what apps to uninstall, as well as to clear data and/or cache.
> 
> What did you mean by package size? Is it APK size, data size, cache size or a total?
> 
> 

Packages as in an apk including cache and data. I worded it wrong. My apologies. Would be interesting to be able to sort apps by cache only too, but wouldn't want to be too much of an undertaking.
