### ISSUE TITLE
App manager loading non stop while scanning "battery log" app by hwangti

### ISSUE THREAD

**Issue by Ananas-Kuchen** [MuntashirAkon/AppManager#536]
- [x] I know what my device, OS and App Manager versions are
- [x] I don't know how to take logs. because the log viewer doesn't show anything at redmi 6
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
When I try to scan an app with package name "kr.hwangti.batterylog (google play)". the application keeps loading without reaching the end. It's been hours but nothing has changed

**To Reproduce**
dunno

**Expected behavior**
This happened when I tried it on appmanager version above v2.6.0

**Screenshots**
![ss2](https://user-images.githubusercontent.com/65159908/127602514-7f37e495-5370-4493-866a-f14f57c614df.png)
Like this

**Crash logs**
Unfortunately the app doesn't crash. just weird things like keeps loading while scanning certain apps (since new version v2.6.1)

**Device info**
 - Device: 1.redmi 6 (only), 2.redmi note 8
 - OS Version: 1.(8.1), 2.(9)
 - App Manager Version: v2.6.1, v2.6.2
 - Mode: no-root

**Additional context**
Things like endless app scanning also happen to some other apps, unfortunately I can't remember all of them. and what I remember the most is when I scanned that "battery log" apps.

**Comment by Ananas-Kuchen** [comment]
The last time I scanned that app, the result was that there was no tracker at all

**Comment by MuntashirAkon** [comment]
Fixed in 2ccf6dce
