### ISSUE TITLE
Add Finer Profiles Options

### ISSUE THREAD

**Issue by FrozenVertx** [MuntashirAkon/AppManager#541]
Hi,
I want to suggest a small improvement in profiles area. As by default in areas like appops have only option to choose to add OFF(Ignore) particular appops. So please add more options like specifically allow,deny,foreground to apply all over profiles. In permission area please add option to choose from pre-exist permissions like set custom app op its hard to go and search then copy permission to profile in order to use it.

**Comment by MuntashirAkon** [comment]
Superseded by #561
