### ISSUE TITLE
Doubt about eliminating trackers

### ISSUE THREAD

**Issue by gallegonovato** [MuntashirAkon/AppManager#543]
Good afternoon:

First of all thank you for your great application. Every day I learn more things about it.

But I have a doubt. Recently I am using Mull from fdroid: https://f-droid.org/es/packages/us.spotco.fennec_dos

And when I check it with your application I get these trackers:

https://ibb.co/dDzxsts

I don't know if for a possible version of your application or with the current stable version, it would be possible to remove these trackers.

Thank you very much for your time and help

**Comment by MuntashirAkon** [comment]
> I don't know if for a possible version of your application or with the current stable version, it would be possible to remove these trackers.

Not possible. If it were, the developers of Mull would do it in first place. Analytics/tracking in Firefox is so deeply integrated that it's very difficult to remove them completely without breaking some other features. If possible, migrate to Bromite.

> Every day I learn more things about it.

There's an instructions page within the app (which is fully offline). You can use it to learn a lot about the apps and its features.
