### ISSUE TITLE
Convert system apps<---->user apps by move apk to /system/app,/system/priv-app<---->/data/app

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#545]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

As I said in title,Link2SD and LP (and more) has this feature.

**Comment by MuntashirAkon** [comment]
AM is never going to modify the system partition in any circumstances. An alternative is #150 (postponed due to the uncertain future of Magisk).
