### ISSUE TITLE
Improve Interceptor to get Camera requests

### ISSUE THREAD

**Issue by mubashir-rehman** [MuntashirAkon/AppManager#549]
<
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant

**Is your feature request related to a problem? Please describe.**
I am trying to submit some documents in an app which requires them to be taken with camera. I have taken all the document pictures already and don't want to take new ones. Moreover, I don't have one document here cause I have sent it for verification. Now, as Muntashir once told intent interceptor is a very handy tool. So, I gave it a try. With hit and trial I was able to manage pick photos using files app as shown below.
![image](https://user-images.githubusercontent.com/51048830/128643133-473c7e3e-55c5-4e86-8c4b-888a42fc8fd4.png)
However, there is one button that doesn't allow to send intent to intent interceptor and straight goes to camera. I can't take new pic cause document is not here for now and will return possibly after a month or so. The issue is shown in below video:

https://user-images.githubusercontent.com/51048830/128643211-a8614928-78e9-44ac-8424-0b72c244f6b7.mp4

**Describe the solution you'd like**
Clicking the area to submit the document should give option to forward intent to intent interceptor.

**Describe alternatives you've considered**
I have tried Intent Intercept but same results as AppManager https://github.com/k3b/intent-intercept

**Comment by mubashir-rehman** [comment]
For later use maybe:
![image](https://user-images.githubusercontent.com/51048830/128643991-ef7caf1d-144c-4827-ab15-ea641e43452e.png)

**Comment by MuntashirAkon** [comment]
Implemented in fa74389b
