### ISSUE TITLE
Version 2.6.2 (F-Droid) have problem and won't work in adb over tcp mode 

### ISSUE THREAD

**Issue by rustforfuture** [MuntashirAkon/AppManager#554]
- [ ✓] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [✓ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

After 2.5.17, every version i install from F-Droid won't work in adb mode and even though i force it in setting to use adb over tcp, it always prompt that there is a problem with current working method and would you like to go to non root mode?

I tested this is two devices, in both devices the latest F-Droid version (2.6.2) have exact this problem but when i remove it and install 2.5.17 again, it prompt for adb permission and will work.

I tested this in two devices without root access.

Honor 10 lite woth android pie

Huawei y5 lite 2018 with android oreo go edition.

In both 1.5.17 worked perfectly but 2.6.2 didn't worked and prompt me that text i writed before to go to non root method.

Although it is not related to this issue, for more info i tested this in a android box that have root access and it works very good with root thanks god :)

By the way thank you very much for this great app.

I also checked 1.5.17 settings but there wasn't any settings to export logs, that is the reason i didn't checked it in first of this issue.

Otherwise i probably can find out if you help a little to provide you logs.

Also how much are private this logs?

Does them have any personal identifiable information in them?

Thank you very much.

**Expected behavior**

App should show toast message that are working in adb mode and can disable/enable system apps and other things that it could done qith adb mode in the past versions.

**Screenshots**

App manager in version (1.5.17) :

![Screenshot_20210813_204854_io github muntashirakon AppManager](https://user-images.githubusercontent.com/49192003/129389622-d30de72a-32e1-4849-92f2-65ddc8c09942.jpg)

App manager in version (2.6.2) : (screen record)(available untill 30 days from now)

https://upload.disroot.org/r/rb1Z0xqd#XlO0I6ZneaLPNwfagTKek6LqsMlXySKgJsECcuHH/cw=

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: (Huawei) Honor 10 lite + Huawei Y5 Lite 2018
 - OS Version: Android 9 + Android 8 (Go Edition)
 - App Manager Version: 2.5.17 (works in adb mode and has no problem) vs 2.6.2 (don't work with adb over tcp and have problem) (F-Droid versions)
 - Mode: adb

**Additional context**
Thank you very much.

**Comment by MuntashirAkon** [comment]
This issue has been fixed (see #513). Wait for the next release.

**Comment by rustforfuture** [comment]
> This issue has been fixed (see #513). Wait for the next release.

Thank you very much
