### ISSUE TITLE
Sort by name in Installer App section

### ISSUE THREAD

**Issue by DreadedLama** [MuntashirAkon/AppManager#560]
**Is your feature request related to a problem? Please describe.**
Selecting the Choose option in “Installer App” section in the Installer settings displays the installed apps randomly. It's difficult to find the required app from the list. 

**Describe the solution you'd like**
Sort the installed apps on the basis of name

App Manager Version: v2.6.3
Mode: root

**Comment by MuntashirAkon** [comment]
Implemented in 00b73b03
