### ISSUE TITLE
ADB over TCP and Wireless debugging mode on failure

### ISSUE THREAD

**Issue by DoveBoy** [MuntashirAkon/AppManager#562]
**Describe the existing feature/documentation**
ADB over TCP and Wireless debugging mode on failure

**Describe your problem(s)**
ColorOS Android 11. Activate AM via PC using ADB over TCP mode works fine.But if I enter adb devices and adb tcpip 5555 in this phone using Termux emulator, it does not turn on, can I activate ADB over TCP only through PC terminal?
The USB debugging mode and wireless debugging function are both turned on in the developer options, but using the wireless debugging function cannot be opened
The above two opening methods are tested on both AM and AM debug apps with the same result

**Additional contexts**
Add any other context or screenshots about the feature/documentation here.

**Comment by MuntashirAkon** [comment]
> But if I enter adb devices and adb tcpip 5555 in this phone using Termux emulator, it does not turn on, can I activate ADB over TCP only through PC terminal?

Of course, not. If you can connect your phone via Termux's `adb` package, you can also run ADB over TCP from there. But as usual, you have to make sure that _you disconnect your existing ADB connection_ before opening App Manager as this will cause collision.

> The USB debugging mode and wireless debugging function are both turned on in the developer options, but using the wireless debugging function cannot be opened

As you might be aware, wireless debugging facility is quite limited in the release builds. You have to connect at least once via ADB over TCP in order to use wireless debugging, which is effectively the same as pairing (which, again wasn't supported due to licensing issues). Debug builds support pairing but you might have to try multiple pairing codes due to [a bug](https://github.com/MuntashirAkon/spake2-java/issues/1) in the underlying library.

**Comment by DoveBoy** [comment]
@MuntashirAkon 
> Of course, not. If you can connect your phone via Termux's adb package, you can also run ADB over TCP from there. But as usual, you have to make sure that you disconnect your existing ADB connection before opening App Manager as this will cause collision.
Using the adb command in Termux eventually prompts a failure.How to determine disconnect the existing ADB connection before opening App Manager
![Screenshot_2021-08-19-18-55-45-53_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/19201447/130057296-1a5bfdf4-c50d-4aa8-bc2d-298951e5d0c2.jpg)

**Comment by MuntashirAkon** [comment]
> Using the adb command in Termux eventually prompts a failure.How to determine disconnect the existing ADB connection before opening App Manager

Since the list of devices section is empty, the device isn't connected to ADB. So, this method won't work. Try using wireless debugging using the trick mentioned above.

**Comment by DoveBoy** [comment]
@MuntashirAkon 

> Since the list of devices section is empty, the device isn't connected to ADB. So, this method won't work. Try using wireless debugging using the trick mentioned above.

I use the AM debug version, during the wireless debugging process, I select the pair option and enter the Wi-Fi pairing code and port several times, but it always prompts me that the wireless debugging function is failed, and I have confirmed that the wireless debugging function is enabled. In addition, which port in the screenshot is used, 1 or 2? I have tried both of them many times, but still can't
![Screenshot_2021-08-19-18-55-45-53_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/19201447/130063042-51361c81-5485-447f-ae85-ab29b349dbf9.jpg)

**Comment by MuntashirAkon** [comment]
> In addition, which port in the screenshot is used, 1 or 2? I have tried both of them many times, but still can't

**List of devices** section is empty which means it didn't find any devices. The only way to connect to ADB via Termux would be via wireless debugging:
1. First, split the screen into two parts: One for Termux and another for Wireless Debugging setting.
2. Then select **pair a new device** in the setting page and note down pairing code, IP address and port number.
3. In Termux run: `adb pair ip:port pairing_code` (replace `ip` with the IP address, `port` with the port number and `pairing_code` with the pairing code you've noted in step 2).
4. Now run: `adb devices`. You should now see your device there.

> I use the AM debug version, during the wireless debugging process, I select the pair option and enter the Wi-Fi pairing code and port several times, but it always prompts me that the wireless debugging function is failed, and I have confirmed that the wireless debugging function is enabled.

Can you seen **AppManager** entry in the wireless debugging setting page? If you've already connected App Manager using ADB over TCP (and haven't cleared data), there should be an entry there.

**Comment by DoveBoy** [comment]
@MuntashirAkon 

1. First, split the screen into two parts: One for Termux and another for Wireless Debugging setting.
2. Then select pair a new device in the setting page and note down pairing code, IP address and port number.
3. In Termux run: `adb pair ip:port pairing_code` (replace `ip` with the IP address, `port` with the port number and `pairing_code` with the pairing code you've noted in step 2).
4. Now run: `adb devices`. You should now see your device there.

Following the above steps, Termux still shows an empty result
![Screenshot_2021-08-19-20-18-02-86_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/19201447/130067756-bbd75f34-e658-4611-91ae-2c46b778d5b7.jpg)

**Comment by MuntashirAkon** [comment]
> Following the above steps, Termux still shows an empty result

It seems you also have to connect manually. Run: `adb connect 192.168.50.53:39165` (IP:Port taken from the screenshot). After that run `adb devices` to see if it's been connected.

Since there's no “AppManager” entry, it means App Manager was never connected using ADB over TCP.

**Comment by DoveBoy** [comment]
@MuntashirAkon 

> Run: adb connect 192.168.50.53:39165

This step does work, adb devices can see the connected devices, adb tcpip 5555 shows normal, in the AM Manager prompt has been connected by ADB way, thanks!

**Comment by elswerky** [comment]
When I use adb pair command 
It pair successfully 
But adb devices shows no connected devices 

After this if I used adb connect it says  failed to connect 

What should I do ?
A11 ,miui  ROM 12.5

**Comment by elswerky** [comment]
![Uploading Screenshot_2022-01-17-11-55-41-393_com.termux.jpg…]()

**Comment by elswerky** [comment]
Ok I can connect now 
On termux 

On my Xiaomi device wireless debugging
There is option named pair device with pairing code 

Now I pair device by 
adb pair ip_address:port  wifi_pairing_code


Now I can connect 
There is ip_address:port in wireless debugging 
But here port is different than the port of pairing code 
So I can connect now 
$ adb connect ip_address:port 
Here port is different than the pairing code port and this what was causing it to refuse to connect with me at first 

Here screenshots explain it 
![IMG_20220117_140147](https://user-images.githubusercontent.com/26687459/149768686-9fc2ff94-5ba2-4dd6-b6d1-ba9752636b0b.jpg)
![IMG_20220117_140124](https://user-images.githubusercontent.com/26687459/149768696-83083f8d-5dc0-4be8-bd23-0c0c105eb73c.jpg)

**Comment by MuntashirAkon** [comment]
Yes. All ports are randomly generated. I will add a detailed guide later in the docs section.
