### ISSUE TITLE
Virtual environments for apps

### ISSUE THREAD

**Issue by anedroid** [MuntashirAkon/AppManager#564]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

It would be great if AM could install and launch apps in sandboxes, like Parallel Space, and had some features to control these apps, here's my ideas about this:

- Spoofing details about device, e.g. vendor, model, location, installed apps, network status etc.
- SAF provider to let non-root users access private storage
- Virtual internal storage - user would choose its location through SAF
- Multiple VPN apps running at the same time - traffic would be routed by AM, and user could decide, which VPN use for which app. This could be done by creating proxy port, or local VPN.
- Shortcuts and widgets on homescreen provided by AM
- Fake permissions

**Comment by anedroid** [comment]
I would add optional fake root, but I think most of root apps wouldn't work then, because usually they're changing something in system. Maybe it should be separate app for this, not the part of AM.

**Comment by Atrate** [comment]
Related projects:
https://github.com/asLody/VirtualApp
https://github.com/android-hacker/VirtualXposed

I feel like while the idea is nice, it would be a lot of effort to implement and maintain, especially across different Android versions.

**Comment by MuntashirAkon** [comment]
> I feel like while the idea is nice, it would be a lot of effort to implement and maintain, especially across different Android versions.

I agree. Maintenance would be much difficult on my part. In the future, if contributors are interested in maintaining such feature, I might rethink my positions regarding this. But in any case, this feature shouldn't be part of the main app as most users won't be interested in such feature.

Besides, we've already got users who use App Manager in their favourite virtual environments.

**Comment by NSTAdventure** [comment]
Don't forget about notifications bro how app that inside am ve can send notifications?

**Comment by MuntashirAkon** [comment]
> Don't forget about notifications bro how app that inside am ve can send notifications?

Notifications are being made optional. See #507.

**Comment by gnuhead-chieb** [comment]
So far VirtualApp has proprietary blob and VMOS is malware,there's completely opensource way to do it for now.
https://github.com/twoyi/twoyi
https://install.appcenter.ms/users/weishu/apps/twoyi/distribution_groups/internal

**Comment by NSTAdventure** [comment]
> So far VirtualApp includes proprietary blob and VMOS is malware,there's completely opensource way to do it for now. https://github.com/twoyi/twoyi https://install.appcenter.ms/users/weishu/apps/twoyi/distribution_groups/internal

btw that app is full of bug if developer want implement any feature based on it i recommend to think twice first

1. wifi not available
2. sometime twoyi will freeze probably caused by i open a app

**Comment by MuntashirAkon** [comment]
> btw that app is full of bug if developer want implement any feature based on it i recommend to think twice first

This is a new app. Bugs are kind of expected.

**Comment by MuntashirAkon** [comment]
As I've said earlier. I do not have any intention to to work on this feature.

If somebody wants to ensure privacy and security, avoiding the rogue apps altogether is the best solution. Relying on these apps by any means (e.g. through the use of MicroG or SafetyNet bypassing methods, et al.) only hampers the motivation of the developers to build new alternatives and, on the whole, disrupts our efforts and movements on creating sustainable solutions. This could be related to the E-Mail protocol: No matter how much you try, you cannot fix what's already broken. As a result, we now have good alternatives such as the Signal protocol which is even adopted by many closed source and/or privacy disrespecting services.

This is also why we are replacing trackers with a more _sane and realistic_ alternatives such as AntiFeatures used by F-Droid. I understand that most people do not have (nor have any interests in building) a threat model. As a result, as a developer, it's my task to ensure that App Manager comes with a threat model applicable to the people who have limited to no understanding of privacy (without the use of the _privacy_ buzzword anywhere). This is by no means an easy thing to do (as these are highly opinionated), but I am trying any way, and so far, it gives me hope seeing how App Manager was able to change the lives of, at least, a handful of people.

**Comment by NSTAdventure** [comment]
> > btw that app is full of bug if developer want implement any feature based on it i recommend to think twice first
> 
> This is a new app. Bugs are kind of expected.

ofc sir i just remind just in case you or other dev want to implement something that are based on twoyi or any new app hehe 🙏😄

**Comment by gnuhead-chieb** [comment]
> * wifi not available
> 
> * sometime twoyi will freeze probably caused by i open a app

works on my side.

**Comment by gnuhead-chieb** [comment]
this issue should be closed.
