### ISSUE TITLE
Can't block tracker or anything else after update to 2.6.3

### ISSUE THREAD

**Issue by citizenserious** [MuntashirAkon/AppManager#567]
**Describe the bug**

After the update to v2.6.3 the app took for ages (about 3 min) to load, and if it finally does I can no longer change the settings of an app, and the options on the top right just shows "Refresh"
I restarted the device after the update.
The problem appeared  exactly after the update, nothing else was changed and has worked very fine before.

**To Reproduce**
Upgrade to v.2.6.3

**Expected behavior**
Be able to disable trackers and other parts of any application.

**Screenshots**
![AppManager 1](https://user-images.githubusercontent.com/62773866/131569499-618d3257-977c-42ef-b8ba-51d7d895bd44.png)

![AppManager](https://user-images.githubusercontent.com/62773866/131568601-cef22364-0b60-4ca1-b9f4-bfb00a6e0813.png)

**Crash logs**
nothing crashes

**Device info**
- Galaxy S9 (starlte)
- Android 11 with LOS
- AppManager v2.6.3 from F-Droid
- root with Magisk 23.0, su permission granted

**Additional context**
Things blocked before the update are still blocked, but can't be unblocked. I just don't understand it.

**Comment by citizenserious** [comment]
I changed the "Mode of operation" from "Auto" to "Root" now it works again.
It is even possible to change it back to "Auto"
It still takes a long time to load (Initializing) the app though, but I am happy that I can use it again.

**Comment by MuntashirAkon** [comment]
Yes, a few people have reported similar issues including #563 but I'm unable to reproduce the issues on my device. Therefore, it would be helpful if you provided some logs.

**Comment by citizenserious** [comment]
I am sorry but I have to ask how to create a log file for the AppManager startup.
