### ISSUE TITLE
Add option to revert "Block trackers" for "1-Click Ops" feature.

### ISSUE THREAD

**Issue by pjmp** [MuntashirAkon/AppManager#57]
After i applied  `1-Click Ops > Block trackers`, some 3rd party apps refuses to open i.e it crashes immediately.
I want to revert applying of  `1-Click Ops > Block trackers` but i see none.

**Comment by MuntashirAkon** [comment]
**Block trackers** is renamed as **Block/unblock trackers** with an extra option to unblock tracker components from the selected apps.
