### ISSUE TITLE
Widget not working

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#573]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
![Screenshot_2021-09-06-08-28-26](https://user-images.githubusercontent.com/48226312/132154468-3ac25e26-59a2-4d0f-9cbe-b8a3b8d0b79d.jpeg)
Currently AM widget not working for some reason.

v 2.6.3 (F-Droid version)

**Comment by MuntashirAkon** [comment]
Fixed in 14310708
