### ISSUE TITLE
[Feature request] Search feature to Instruction page

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#576]
- [x] I am using the latest version of App Manager
- [ ] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
Current Instruction page like a Wikipedia, lots of info there. I hope with time more instructions will be added with more features coming in future Though it is organized nicely, it's hard for a new user to check instructions.

**Describe the solution you'd like**

Let's say I want to check adb related instructions/info only & not by going through all the instructions pages.
In Telegram, there is a search button where you type a word/line & it searches the whole group/conversation matching such particular word. Similarly, there is `Ctrl+F` in browsers to find the user-defined words in a particular website/webpage...

Not only this is useful to new users. It is useful if you are a regular/advanced user & you know about the features/instructions but want to recheck the instruction page. Now you don't need to remember where that exact instruction is. Just type related words & go through them quickly until you find the instruction that you want.

![Screenshot_2021-09-10-17-57-47](https://user-images.githubusercontent.com/48226312/132853388-b6023f84-1988-4fcf-8225-4b3b2c5fb92e.jpeg)

- Add a search icon in top-left-corner. By clicking it, it should expand to a search bar, where users can type words.
- Type words & it should show results immediately without hitting enter button. (Just like we have search option in our AM start screen (Onboard packages))

**Comment by MuntashirAkon** [comment]
Already implemented in 263902a5e0c73478afb9dba04636342238d52671. This wasn't backported to v2.6.x, so you'd have to wait for v3.0.0.
