### ISSUE TITLE
When using interceptor how can i set the correct type?

### ISSUE THREAD

**Issue by temp-github-acc** [MuntashirAkon/AppManager#578]
**Describe the existing feature/documentation**
Interceptor

**Describe your problem(s)**
I want to edit the EXTRA data field of the intent, but I don't know the type of the original data, it seems to be a list of string, (it's in the form of [1,2]) but when i removed and added a new field of list of string and sent edited intent, the screen went black and it went back to the previous screen.
Maybe the type is wrong, but how can I determine? there's no hint of type, and we can't edit the data directly (have to remove it and add it).
Btw, I set the value type as list of string, and in value field i typed "A,B". is that wrong?
Thanks

**Additional contexts**
Add any other context or screenshots about the feature/documentation here.

**Comment by temp-github-acc** [comment]
The field is actually STREAM, which i suspect to be a speical type, list of uri maybe?

**Comment by MuntashirAkon** [comment]
> The field is actually STREAM, which i suspect to be a speical type, list of uri maybe?

If the action is `android.intent.action.SEND_MULTIPLE`, the value of `android.intent.extra.STREAM` should be a **list of Uris** (not supported right now) otherwise the value should be **Uri** (supported).

**Comment by temp-github-acc** [comment]
Thanks for your reply!!
Will it be supported in the future?
Although it's not appropriate to say but i really need this feature.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MuntashirAkon** [comment]
> Will it be supported in the future?

Implemented in 0a1fb17d.

**Comment by temp-github-acc** [comment]
Thank you so much.
I'm sorry but since this is a Help Needed issue, i believe i can ask more.
I downloaded the debug version and tried it. For a SEND_MULTIPLE action intent, there are MIME type, URI, FLAGS and so on, i left those unchanged, and only copied the content in EXTRA - android.intent.extra.STREAM which is in the form of [content://xxxxx, content://xxxxx].
Then i deleted the existing android.intent.extra.STREAM and added a new one, type set as "List of URIs", then in the value field i pasted: content://xxxxx,content://xxxxx
I pressed "Send Edited Intent", and selected the targeted app, although the app can receive the files but abandoned some apparently, which is different from sharing directly (without editing).
May i ask why?
Thanks
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MuntashirAkon** [comment]
> May i ask why?

AM doesn't remove anything you've inserted in the supported extras field. However, it might be removed during parsing because you've used the wrong format e.g. when separating strings using comma, if a string contains a comma, it must be escaped. If everything is correct, then it can still happen if the destination app cannot access all the URIs i.e. the source app didn't grant read/write permission for some URIs.
