### ISSUE TITLE
Endless app loading...

### ISSUE THREAD

**Issue by entaytion** [MuntashirAkon/AppManager#580]
Since v2.6.3 Run#1529, I have had endless app loading. Before v2.6.3 Run#1528, I have applications open instantly, but after the update and its subsequent versions, the loading doesn't stop and applications are not displayed.

**Comment by entaytion** [comment]
![Screenshot_2021-09-17-09-58-01-250_io github muntashirakon AppManager debug](https://user-images.githubusercontent.com/57830743/133739176-73b66a3c-db12-451f-aa53-020b54f906f9.png)
It looks like this.

**Comment by MuntashirAkon** [comment]
> Since v2.6.3 Run#1529, I have had endless app loading. Before v2.6.3 Run#1528, I have applications open instantly, but after the update and its subsequent versions, the loading doesn't stop and applications are not displayed.

There was never a **v2.6.3**#1528 but **v2.7.0**#1528. Two versions are different and will not work at the same time without clearing app data. To fix this issue, revert back to 1528 until a new build is available for v2.7.0.
