### ISSUE TITLE
App usage of work profile not shown

### ISSUE THREAD

**Issue by dennis90a** [MuntashirAkon/AppManager#584]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Usage of work profile apps not shown in app usage

**To Reproduce**
Steps to reproduce the behaviour:
1. Use work profile app
2. Open App Manager
3. Click on 3 dots > App Usage
4. See bug - no usage of work profile app shown

**Expected behavior**
Expected app usage of work profile app to be shown as well

**Device info**
 - Device: Mi 11x
 - OS Version: Android 11
 - App Manager Version: 2.6.3
 - Mode: root

**Comment by MuntashirAkon** [comment]
You mean displaying the usage from work profile when App Manager is installed in the default profile?

**Comment by dennis90a** [comment]
Yes

**Comment by MuntashirAkon** [comment]
Implemented in 3ea94103
