### ISSUE TITLE
Feature Request: Add support in intent intercept for ACTION_OPEN_DOCUMENT_TREE 

### ISSUE THREAD

**Issue by mubashir-rehman** [MuntashirAkon/AppManager#585]
- [ ] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
I replaced the stock DocumentsUI (file provider) with Google's Files app. Which doesn't have intent for ACTION_OPEN_DOCUMENT_TREE . Hence, I am left with no app that supports intent ACTION_OPEN_DOCUMENT_TREE. Therefore, many apps either crash on selecting files or don't even respond.

**Describe the solution you'd like**
Add support for ACTION_OPEN_DOCUMENT_TREE  in intent interceptor with related permissions so i can browse all the files and directories.

**Describe alternatives you've considered**
I have tried Amzae File Explorer, Mixplorer, Google Files app. they all can show and modify files in their own app. but when other apps requests ACTION_OPEN_DOCUMENT_TREE  no one responds.

**Comment by MuntashirAkon** [comment]
`ACTION_OPEN_DOCUMENT_TREE` cannot be used by a user app.
