### ISSUE TITLE
cannot export rules (from settings) 

### ISSUE THREAD

**Issue by ale82to** [MuntashirAkon/AppManager#591]
on my device xiomi mi 10 with plain lineage OS 18.1
i cannot export rules (from setting) if I choose lineage OS inbuilt file apk to export rules all I get is a an empty 0 bite file xxxAM.am.tsv.
if I choose mixplorer when trying to export rules it fails with this error java.io.FileNotFoundException.
so can please someone tell me how to proper export rules (from setting?)

**Comment by MuntashirAkon** [comment]
Fixed in 908c2f94. Since the rules weren't stored in the app-private directory, you have to reapply the rules.
