### ISSUE TITLE
adb wifi connection stopped working after phone formatting 

### ISSUE THREAD

**Issue by edersonmax21** [MuntashirAkon/AppManager#595]
Good morning, After several times I have disconnected the adb app manager, After a format it no longer connects to my s10+, the adb confirmation message no longer appears, I don't know what to do.

**Comment by MuntashirAkon** [comment]
Sorry, I didn't understand your situation properly. If you have formatted the whole device, **enabled USB debugging**, installed App Manager again, and used the `adb tcpip 5555` command to connect to ADB _after disconnecting your device from the PC_, the confirmation message should appear as it was the first time.

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
