### ISSUE TITLE
Rebuild APKs

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#6]
### While I believe that #2, #3 and #4 are in line with this project's direction, this issue might not be.

An interesting (and hard and time consuming to implement) feature I couldn't find in any FOSS app so far is APK rebuilding.

By that I mean disassembling the application, modifying the manifest file and some classes, then recompiling and signing with a new key, similar to what apps like Lucky Patcher or Jasi Patcher do.

This would allow for a very deeply-rooted removal of advertising receivers and services or unneeded permissions, instead of simply disabling them.

This would also allow for the removal of permissions that can't be disabled, e.g. android.permission.INTERNET.

Curiously, this does not require root access at all.

**Comment by MuntashirAkon** [comment]
I would love that myself. But I'll probably have decompile Lucky Patcher to figure it out. I know how to find classes inside classes.dex and modify them but that's all I know as of today. I've no idea how odex works and I have yet to figure out how to convert odex to dex without root.

**Comment by MuntashirAkon** [comment]
> This would also allow for the removal of permissions that can't be disabled, e.g. android.permission.INTERNET.

Are you sure permissions like `android.permission.INTERNET` can't be disabled? **AppOpsX** can disable such permissions but the source code has no documentation whatsoever. I'll probably merge this app if I can figure out what it's been doing to disable these permissions. Currently I can't even make it work due to API issues: it uses API 28 as the target API but I only have API 29 (can't download API 28 due to bandwidth issues) and while it does compile on API 29, the app doesn't work at all.

**Comment by Atrate** [comment]
> AppOpsX can disable such permissions but the source code has no documentation whatsoever. I

Always thought it was impossible, but if AppOpsX does it and it works then that's great

**Comment by MuntashirAkon** [comment]
It seems most methods that are used to modify permissions are restricted in the latest APIs. There are some methods to bypass this restriction but I'm not sure if it worth it. My three days of effort ends here, I think. Regarding #2, I will only add a switch next to permissions that can be revoked using the `pm` command (only `dangerous` permissions can be revoked by `pm` by the way).

Modifying/rebuilding apk on the fly seem to be the only viable solution for newer versions of Android. But I've no idea how to get started yet.

**Comment by MuntashirAkon** [comment]
Related wiki article: [How to control application components without root](https://translate.googleusercontent.com/translate_c?depth=1&pto=aue&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://github.com/lihenggui/blocker/wiki/%255B%25E5%25AE%259E%25E9%25AA%258C%25E6%2580%25A7%25E5%258A%259F%25E8%2583%25BD%255D-%255B%25E5%25BC%2580%25E5%258F%2591%25E8%2580%2585%25E5%2590%2591%255D%25E5%25A6%2582%25E4%25BD%2595%25E5%2585%258DRoot%25E6%258E%25A7%25E5%2588%25B6%25E5%25BA%2594%25E7%2594%25A8%25E7%25A8%258B%25E5%25BA%258F%25E7%25BB%2584%25E4%25BB%25B6&usg=ALkJrhiTrqEMCwbWFB2TqQy8YcubRjhiLw#%E5%AE%89%E8%A3%85%E4%BF%AE%E6%94%B9%E7%89%88%E7%9A%84apk)

**Comment by MuntashirAkon** [comment]
AppOps-related discussion is moved to #17.

**Comment by MuntashirAkon** [comment]
I've finally decided to add support for app manifest editing, hopefully in v2.6. But I'm not sure how the F-Droid repo owner react to that.

**Comment by Atrate** [comment]
> So, unless my app is a system app, there's no way to achieve this. So, it's a lost cause now.

Might be outdated now, but a Magisk module could be used to make AppManager a privileged system app. I could quickly spin such a module up and AM would just DL and install the zip if the user needed such functionality.

**Comment by MuntashirAkon** [comment]
> Might be outdated now, but a Magisk module could be used to make AppManager a privileged system app. I could quickly spin such a module up and AM would just DL and install the zip if the user needed such functionality.

Current method of setting app ops is a bit slow but works. So, I won't be working on this any time soon.

**Comment by Atrate** [comment]
Might come in handy:
https://github.com/kefir500/apk-editor-studio

**Comment by MuntashirAkon** [comment]
Closing in favour of #138 (this thread contains too many off-topic comments).
