### ISSUE TITLE
Allow splitting data backups into 4GB volumes

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#60]
### Rationale:

Some apps (such as Spotify, Deezer) allow the user to download a large amount of data onto their phones, often surpassing a couple of gigabytes. This can be a problem when trying to back this data up into one archive if a user has a FAT32 formatted SD card or USB device

### Solution:

Add an option in the setting or automatically split data backups into 4GB volumes.

**Comment by MuntashirAkon** [comment]
Related to #30 and documentations on how this is going to be solved will be described in there.
