### ISSUE TITLE
Extend the scanner functionality

### ISSUE THREAD

**Issue by GameHunter** [MuntashirAkon/AppManager#607]
It would be nice to have a pissibility to scan entire Android system for trackers, like Warden does

It would be nice to scan all APKs in a specified folder and its subfolders for trackers (Warfen does not)

Sincerely yours,
GH.

- [ + ] I am using the latest version of App Manager
- [ + ] I have searched the issues and haven't found anything relevant
- [ + ] I have read the docs

**Comment by MuntashirAkon** [comment]
> It would be nice to have a pissibility to scan entire Android system for trackers

This is already available via **1-Click Ops** > **Block trackers...**.

> It would be nice to scan all APKs in a specified folder and its subfolders for trackers

What is the benefit of such a feature? If you are installing the APKs via App Manager's installer, you can already visualise the trackers.

**Comment by MuntashirAkon** [comment]
We have found the terminology _trackers_ highly misleading if not wrong and will be replaced with alternatives (#827).
