### ISSUE TITLE
"Running apps" doesn't show running apps, but only AppManager itself

### ISSUE THREAD

**Issue by MR-Diamond** [MuntashirAkon/AppManager#612]
Redmi Note 10 Pro, MIUI 12.5.4.0, Android 11.

Issue:
When i click on List options > Running apps, only AppManager itself is showed as running application, nothing else appears there, why?

If I open the "Security app", and then I click "boost speed",  there I can see all running apps (user and system services).

So: how can I achieve the same with AppManager?

Thanks.

**Comment by MuntashirAkon** [comment]
> When i click on List options > Running apps, only AppManager itself is showed as running application, nothing else appears there, why?

Root or ADB?

**Comment by MR-Diamond** [comment]
The phone is not rooted; I can use ADB on the phone with Termux.

**Comment by MuntashirAkon** [comment]
> The phone is not rooted; I can use ADB on the phone with Termux.

You can grant `android.permission.DUMP` using ADB, or use ADB over TCP in App Manager.

**Comment by MR-Diamond** [comment]
> You can grant `android.permission.DUMP` using ADB

Can you explain me how can I do this?
Thank you.

**Comment by MuntashirAkon** [comment]
Open ADB shell and run:

```
pm grant io.github.muntashirakon.AppManager android.permission.DUMP
```

**Comment by MR-Diamond** [comment]
Somethint is wrong, I got:

```
Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
	at android.app.ContextImpl.enforce(ContextImpl.java:2028)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2056)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1445)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1426)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2300)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:251)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22200)
	at android.os.Binder.shellCommand(Binder.java:932)
	at android.os.Binder.onTransact(Binder.java:816)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4687)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4417)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
	at android.os.Binder.execTransact(Binder.java:1126)
```

**Comment by MuntashirAkon** [comment]
> java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.

No idea. Could be issues with Termux's implementation of ADB client. Ask on Android forums for possible troubleshooting, or use ADB over TCP with App Manager.

**Comment by MR-Diamond** [comment]
Doesn't happen only in Termux; it also happen using ADB over USB.

> or use ADB over TCP with App Manager

How I do this?

**Comment by MuntashirAkon** [comment]
> How I do this?

See user manual: https://muntashirakon.github.io/AppManager/en/#x1-1360003.1. Be sure to read your platform-specific instruction there as you seem to be running MIUI or something similar.

**Comment by MR-Diamond** [comment]
Solved: all I had to do, was to enable "USB debugging (Security settings)" in developer options.

**Comment by MR-Diamond** [comment]
> Solved

Nope... Now, AppManager, in "Running apps" shows nothing.

**Comment by MuntashirAkon** [comment]
@d4rkk3y: Could you look into it?

**Comment by gnuhead-chieb** [comment]
> Nope... Now, AppManager, in "Running apps" shows nothing.

Try also **DISABLE** MIUI Optimization

**Comment by MR-Diamond** [comment]
> **DISABLE** MIUI Optimization

Done, doesn't helped.

**Comment by gnuhead-chieb** [comment]
Did you regrant permission after you changed settings?

**Comment by MR-Diamond** [comment]
Sure, but the situation remains the same: nothing is displayed in running apps.

**Comment by MuntashirAkon** [comment]
That won't do. This clearly looks like a bug.

**Comment by MR-Diamond** [comment]
Keep in mind that the simple "Security app" (com.miui.securitycenter) included by default in the phone, is able to list applications and background services and processes

**Comment by MuntashirAkon** [comment]
> Keep in mind that the simple "Security app" (com.miui.securitycenter) included by default in the phone, is able to list applications and background services and processes

App Manager's “running apps” page actually lists all processes instead of just normal Android apps (with filtering capabilities). For those who're using App Manager with root or ADB, the list is generated by analysing the `/proc` directory (the virtual file system where all the processes are listed in Linux). For non-root users, it is fetched using the `dumpsys` command which requires the `android.permission.DUMP` permission (it only lists Android apps though). You can also filter out the running apps (should be broken too, in your case) in the main page and view running services (along with other details if you're running the latest debug build) when you click on the `running` tag under an apps App Info tab (in the App Details page). For privileged users, it is also possible to kill, force-stop, view filtered logs or disable background operation individually (or in batch in the debug builds).

**Comment by MR-Diamond** [comment]
> For privileged users, it is also possible to kill, force-stop

Although the phone is not rooted, I am able to achieve this using adb, eg. `adb shell am force-stop eu.thedarken.sdm` in Termux (using Wireless debugging and LADB — Local ADB Shell); I noticed that I am not able to do this in AppManager.

**Comment by MR-Diamond** [comment]
Was my fault!

I followed these instructions: https://muntashirakon.github.io/AppManager/guide/adb-over-tcp.html#_4-3-enable-adb-mode-on-app-manager

And now AppManager works as expected.
I am sorry.

You can remove the bug label.

**Comment by MuntashirAkon** [comment]
> You can remove the bug label.

No. It's indeed a bug. The `dumpsys` command isn't working as expected. When you enable ADB over TCP mode, it no longer uses that permission which is why you don't get any issues.

**Comment by MuntashirAkon** [comment]
It looks like I was wrong. **Running apps** page hasn't been enabled for no-root users yet due to issues regarding how the process info will be generated.
