### ISSUE TITLE
Shared Prefs

### ISSUE THREAD

**Issue by solomonrajan** [MuntashirAkon/AppManager#614]
- [ ✓] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [ ✓] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Inorder to edit the XML in Shared Prefs, XML are showing up, but not contents in the Shared Prefs XML are shown. It's just only showing the file not the content in it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'any app'
2. Click on 'shared prep'
3. Scroll down to 'XML's shown'

**Expected behavior**
App expected to show the XML and can be edited or can be added new XML file.

**Screenshots**
![Screenshot_20211101-070030_AM_Debug](https://user-images.githubusercontent.com/24839246/139609547-458a69d9-a0c1-4b76-bbb3-333f9e0e169d.png)

**Device info**
 - Device: Redmi Note 10 Pro Max
 - OS Version: Android 11
 - App Manager Version: Version 2.7.0-1586-DEBUG
 - Mode: root

**Additional context**
In release version of App Manager everything showing up.

**Comment by MuntashirAkon** [comment]
Fixed in 09cf7d8e.
