### ISSUE TITLE
App Manager in TWRP recovery

### ISSUE THREAD

**Issue by yephny** [MuntashirAkon/AppManager#619]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
I've disabled some system apps with google in their name with App Manager and now my device is in a bootloop.

**Describe the solution you'd like**
I figured since App Manager can enable/disable apps, if it had binaries that could be used through a CLI in recovery, I could re-enable the disabled apps that are causing the bootloop with a few commands.

**Describe alternatives you've considered**
Now, I need to dig through files and edit them manually line by line instead.

**Comment by MuntashirAkon** [comment]
> I figured, since App Manager already has capabilities beyond those of package manager, if it had binaries that could be used through a CLI in recovery, I could re-enable the disabled apps that are causing the bootloop with a few commands.

App Manager still relies on Android framework and Java, both of which aren't available in TWRP mode. So, creating CLI would be out of scope of this project as it requires a lot of time and effort that I, as an individual, cannot give.

**Comment by yephny** [comment]
Thanks, I understand. After digging a bit deeper, I realized App Manager is like pm, which doesn't work in recovery as it is made to work on Android, not a recovery environment. Can you, by any chance, help me out though? I'm trying to manually edit `package-restrictions.xml ` to revert back the latest changes I made with App Manager but I'm not sure what to change. Does App Manager log disabled apps/components or take a backup of this file before disabling apps?

**Comment by MuntashirAkon** [comment]
> Can you, by any chance, help me out though?

I think a simple web search would do better than me (after all, I would do the same). Regarding enabling blocked components, you can take a look at this: https://github.com/MuntashirAkon/AppManager/issues/363#issuecomment-817224737

> Does App Manager log disabled apps/components or take a backup of this file before disabling apps?

App Manager doesn't take a backup of the `package-restrictions.xml` file, but it does keep a list of components disabled by users (which can be exported as well). You can find these files at `/data/user/0/io.github.muntashirakon.AppManager/files/conf/` directory.

**Comment by yephny** [comment]
That was useful, thanks. I individually identified which packages I wanted to enable, then modified the file accordingly.

Do you think it makes sense App Manager to back up ~package-restrictions.xml`? It could help with such issues like this one. I can make a proper feature request if needed.

**Comment by MuntashirAkon** [comment]
> Do you think it makes sense for App Manager to back up `package-restrictions.xml`? 

I agree. This could be a good idea to backup `package-restrictions.xml` in each session (i.e. every time a user opens App Manager and runs disable/block operations at least once) which will be cleared in the next boot.
