### ISSUE TITLE
Some apps crash with blocked trackers, how to revert?

### ISSUE THREAD

**Issue by dhammel** [MuntashirAkon/AppManager#62]
Hi,

as ive blocked trackers, some apps just force closed when launched. Ive tried uninstall, reboot and reinstall of the apps having issues and not even that fixed it.

How are the trackers even blocked, that would cause a reinstall not to fix it?

I realize one issue was already closed as you've implement a way to revert this, but is there a way in latest version from Fdroid to manually undo it?

I would also suggest adding this to maybe the introduction section as a tip or something if it is possible (such as how trackers are blocked, how to undo...)

Thank you :)

**Comment by MuntashirAkon** [comment]
I've added workarounds for the previous versions in the [FAQ](https://github.com/MuntashirAkon/AppManager/wiki/Frequently-Asked-Questions-(FAQ)#How_to_unblock_the_tracker_components_blocked_using_1Click_Ops_or_Batch_Ops).
