### ISSUE TITLE
Work profile apps not shows in 1-Click Ops

### ISSUE THREAD

**Issue by DreadedLama** [MuntashirAkon/AppManager#634]
Work Profile apps are not shown in 1-Click ops.

I have verified in
 - Block/Unblock trackers
 - Block components
 - Set mode for app ops

Also can you please sort the apps in 1-Click ops on the basis of the name. Currently, they seem to be sorted in random order.

**Comment by MuntashirAkon** [comment]
Fixed in 055ac15d
