### ISSUE TITLE
[Installer] When a package cannot be installed due to conflict give detailed reasoning

### ISSUE THREAD

**Issue by BurhanDanger** [MuntashirAkon/AppManager#639]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [ ] I have read the docs

**Is your feature request related to a problem? Please describe.**
Currently the reasoning given as to why an app cannot be installed it bit vague. A clear indication of what is actually conflicting would be helpful. 

To give an example currently it looks like this when trying to install a conflicting app through **APP MANAGER**.

![Screenshot_20211129-195946272_1](https://user-images.githubusercontent.com/25033866/143883316-c57465c9-702d-42b3-ab85-bd077c7dd62e.jpg)
 

**Describe alternatives you've considered**

While using [**Apktool M**](https://maximoff.su/apktool/?lang=en) for installation of an app conflict reasoning is given like this.

![Screenshot_20211129-200050112_1](https://user-images.githubusercontent.com/25033866/143884144-b162eb4a-cc03-4f8f-9e2e-8cd9f6314b95.jpg)

**Comment by gnuhead-chieb** [comment]
Google limits instalation of some app(eg,Google camera) if you are using stock ROM since Android11.

flash xposed(or lsposed) and install module `Integrity Verification Disabler`

**Comment by BurhanDanger** [comment]
> Google limits instalation of some app(eg,Google camera) if you are using stock ROM since Android11.
> 
> flash xposed(or lsposed) and install module `Integrity Verification Disabler`

How is this related to the discussion ?

**Comment by gnuhead-chieb** [comment]
https://repo.xposed.info/module/com.alex193a.ivdisabler

https://modules.lsposed.org/module/com.alex193a.ivdisabler

**Comment by gnuhead-chieb** [comment]
> How is this related to the discussion ?

You are trying installing gcam related app on the image

**Comment by BurhanDanger** [comment]
I am not trying to install gcam here. I only used gcam as an example. Also I'm not on stock ROM. This issue is about a feature request.

Here I was trying to install `Gcam-Services-Provider` . This enables gcam to run without GAPPS installed, this also helps to open the last photo without having Google Photos installed. And because I had microg installed, this conflicted with microg. 

#Offtopic

**Comment by MuntashirAkon** [comment]
Implemented in 68cd7758
