### ISSUE TITLE
Request ALL button for sending UKNOWN's during an "Intercenpt"

### ISSUE THREAD

**Issue by Moonshinebeam** [MuntashirAkon/AppManager#648]
- [X ] I am using the latest version of App Manager
- [X ] I have searched the issues and haven't found anything relevant
- [X ] I have read the docs

**Is your feature request related to a problem? Please describe.**
You request updated trackers and or unknown package certifications, not yet in your data base? I would like to do so, however one particular package made by adobe had over 75 UNKNOWNS. To tick every single one off, would be wasteful of the end users time, when they themselves are busy with their own project.  Would you be so kind as to add a ALL button, in order to send you to tracker and or certifications on packages not in your data inventory?  I like the work you done! Thank you so much. Saves a great deal on the pull and drain on my phone. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MuntashirAkon** [comment]
This is done _intentionally_. From [docs](https://muntashirakon.github.io/AppManager/en/#x1-1210002.7.1):

> At the bottom of the page, there is a special item denoting the number of missing signatures (i.e. missing classes). The missing signatures are the ones that AM has failed to match against any known libraries. The number itself has no particular meaning as many libraries contain hundreds of classes, but clicking on the item will bring up a dialog containing the signatures which is helpful in inspecting the missing signatures. **This feature is only intended for people who know what a missing signature is and what to do with it, average users should just ignore it.**
