### ISSUE TITLE
App list is empty on `AM Debug v2.7.0 Run#1637`

### ISSUE THREAD

**Issue by mpeter50** [MuntashirAkon/AppManager#650]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
When starting the app, the app list is not populated with apps.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start AM Debug.
2. Wait for the loading animation to stop.
3. See that the app list is empty.

**Expected behavior**
App list should be populated with the installed apps.

**Screenshots**
|App list while loading|App list after loading stopped|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/83356418/147596692-216769a0-4cbd-4750-8771-33f8ad07475c.png)|![image](https://user-images.githubusercontent.com/83356418/147596699-e5a618c8-b726-4623-9e2c-55ddb2b1168e.png)|

**Crash logs**
The app itself didn't crash so I don't have crash stack traces, and `/data/local/tmp` does not contain log files that were recently updated.

**Device info**
 - Device: Xiaomi Redmi 3S
 - OS Version: Android 6
 - App Manager Version: v2.7.0 (Debug, Run#1637)
 - Mode: root

**Additional context**

**Comment by mpeter50** [comment]
Oh, forgot to include the logs...
Full and filtered log can be found here: https://gist.github.com/mpeter50/5c6332988e8e31c38b52121d467ff88d

Also, you can filter additionally for the process ids.
App PID: 25469
Subprocess PID 1: 25506
Subprocess PID 2: 25514

**Comment by MuntashirAkon** [comment]
Can you do the same but with run#1665?

**Comment by mpeter50** [comment]
It works now! Thank you!
