### ISSUE TITLE
Broken Filter Combination 

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#654]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
In filter dialogue when I select User Apps + System Apps, the app list becomes empty. Basically I was trying to use the "User+System+With Activites" filter, I noticed this behaviour that time. Well, basically I can just only select "with activites" filter to achieve the same thing. But still....

**Expected behavior**
The app list should show user and system apps. 

**Screenshots**
![Screenshot_20220112-134400_AM Debug](https://user-images.githubusercontent.com/83750299/149089057-48b53105-fe84-42dd-88dd-d95caab2e0d6.png)

**Device info**
 - Device: Resmi note 10 pro
 - OS Version: Android 12
 - App Manager Version: Latest debug
 - Mode: root

**Comment by MuntashirAkon** [comment]
This is working as expected. Filters follow **and** (intersection) relations. An app cannot be both user and system (or vice versa) simultaneously.
