### ISSUE TITLE
appops doesn't show up

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#657]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Crash logs**
[logcat_01-22-2022_22-07-28.txt](https://github.com/MuntashirAkon/AppManager/files/7918384/logcat_01-22-2022_22-07-28.txt)

**Comment by MuntashirAkon** [comment]
Logs does not contain anything unusual. Open open log viewer (filter by App Manager's PID) and app ops tab for an app. Then, start recording the logs in the log viewer page. Then in the app ops tab, swipe down to refresh the tab. After a few seconds, stop recording the logs and send them to me.

**Comment by gnuhead-chieb** [comment]
i did that




https://user-images.githubusercontent.com/41156994/150713014-b6d267a9-1183-423f-80f7-0adb4726405d.mp4

**Comment by MuntashirAkon** [comment]
> i did that

No, you didn't. You've filtered the results using AppManager, not its PID. The two are _completely_ different things, **only** PID filtering would be able to capture all the logs belonging to App Manager.

**Comment by MuntashirAkon** [comment]
By the way, you can use AM's own log viewer. It opens in a separate window.

**Comment by gnuhead-chieb** [comment]
[2022-01-24-11-59-45.log](https://github.com/MuntashirAkon/AppManager/files/7922309/2022-01-24-11-59-45.log)

**Comment by MuntashirAkon** [comment]
Can you send me logs from the last debug i.e. 1671?

**Comment by gnuhead-chieb** [comment]
[2022-01-24-11-59-45.log](https://github.com/MuntashirAkon/AppManager/files/7965820/2022-01-24-11-59-45.log)

**Comment by gnuhead-chieb** [comment]
[logcat_01-30-2022_20-50-20.txt](https://github.com/MuntashirAkon/AppManager/files/7965823/logcat_01-30-2022_20-50-20.txt)

**Comment by MuntashirAkon** [comment]
You haven't supplied any device info.

**Comment by gnuhead-chieb** [comment]
crDroid A12 begonia

**Comment by MuntashirAkon** [comment]
Fixed in 1228c0e1
