### ISSUE TITLE
Crashing on fresh install 

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#667]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Crash while fresh installating AM debug build on A12.

**To Reproduce**
Steps to reproduce the behaviour:
Just fresh install latest AM debug build and try to open it.
AM debug #1676 works fine.

**Expected behavior**
Should open the app.

**Crash logs**
https://bin.kv2.dev/~61fbea5b410e7c32e6698bef

**Device info**
 - Device: Xiaomi Note 10 Pro
 - OS Version: 12
 - App Manager Version: Debug #1678
 - Mode: root

**Comment by MuntashirAkon** [comment]
Fixed in da807a6d
