### ISSUE TITLE
Prevent Android11+ from intercepting sync components through IFW

### ISSUE THREAD

**Issue by arm64-v9a** [MuntashirAkon/AppManager#672]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Android11+ using IFW to intercept sync component may cause system_server to crash

**To Reproduce**

Intercept the sync component of any application

**Expected behavior**

Intercepting sync components should only use disable

**Crash logs**
This seems to be a problem with AOSP

**Device info**
 - Device: [MI10,MI6X,WSA,AVD]
 - OS Version: [Android12,Android11,Android11,Android12L]
 - App Manager Version: [#1689]
 - Mode: root

**Comment by MuntashirAkon** [comment]
There is an option to change the behaviour (IFW, PM, IFW+PM) with IFW + PM being the default. Use of PM doesn't ensure that the components will stay blocked as the target app can detect and revert it, or cause crashes if the disabling of a components isn't handled correctly. With IFW, none of the issues are present.

> This seems to be a problem with AOSP

IFW works fine in LOS 18.1. If this is indeed an AOSP-issue, you might want to open it in the [Google Issue tracker](https://issuetracker.google.com/) instead with necessary crash logs.
