### ISSUE TITLE
Running apps doesn't show up

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#674]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Screenshots**
![Screenshot_20220208-094942_AM Debug](https://user-images.githubusercontent.com/41156994/152897312-5f708b01-f201-48a1-b2af-671c97f35ce6.png)

**Crash logs**
[logcat_02-08-2022_09-51-37.txt](https://github.com/MuntashirAkon/AppManager/files/8019770/logcat_02-08-2022_09-51-37.txt)

**Comment by MuntashirAkon** [comment]
> [logcat_02-08-2022_09-51-37.txt](https://github.com/MuntashirAkon/AppManager/files/8019770/logcat_02-08-2022_09-51-37.txt)

```
android.os.RemoteException: Root/ADB enabled but privileged service isn't alive.
```

**Comment by gnuhead-chieb** [comment]
It seems working after reboot
