### ISSUE TITLE
Scanner gives false positive for libfb.so

### ISSUE THREAD

**Issue by klib-so** [MuntashirAkon/AppManager#680]
- [x ] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [ x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
It seems the scanner function is falsely associating **libfb.so** with **Facebook SDK** and thus deeming it a tracker. As far as we can tell this library actually comes from [react native](https://github.com/facebook/react-native/tree/main/ReactAndroid/src/main/jni/first-party/fb) and is a harmless part of the UI toolkit. This caused a bit of a stir because it is included in element, a privacy based messaging client for matrix.  I tried to find a library with this name in the SDK but could not, although the generality of the name fb makes it difficult.

**To Reproduce**
Steps to reproduce the behaviour:
* Run scan on element matrix client for android
**Expected behavior**

**Screenshots**
![Screenshot_20220212-122816_App_Manager](https://user-images.githubusercontent.com/21196529/154017431-9072acb9-fd63-4e7c-828c-4bb697a30976.png)

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Samsung J5
 - OS Version: LineageOS 16 -> Android 9
 - App Manager Version: v2.6.5.1

**Additional context**
I ran a PCap on the offending application for four to five hours and the network activity was completely clean

**Comment by MuntashirAkon** [comment]
@gnuhead-chieb

**Comment by gnuhead-chieb** [comment]
> * App Manager Version: v2.6.5.1

Already fixed in latest version

**Comment by gnuhead-chieb** [comment]
use 3.0 alpha or latest debug

**Comment by klib-so** [comment]
Ok thank you
