### ISSUE TITLE
Pure black theme

### ISSUE THREAD

**Issue by zkollz** [MuntashirAkon/AppManager#681]
- [ ] I am using the latest version of App Manager
- [ ] I have searched the issues and haven't found anything relevant
- [ ] I have read the docs

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Is there any chance to include a pure black dark mode?

**Comment by MuntashirAkon** [comment]
> Is there any chance to include a pure black dark mode?

Yes, but not right now. Material library imposes dark mode based on elevation meaning certain components such as dialogs, context menus won't be black unless explicitly set so.
