### ISSUE TITLE
Make a design change in app info page 

### ISSUE THREAD

**Issue by Unmesh98** [MuntashirAkon/AppManager#682]
- [yes(stable version) ] I am using the latest version of App Manager
- [yes ] I have searched the issues and haven't found anything relevant
- [ yes] I have read the docs

**Is your feature request related to a problem? Please describe.**
NO.

**Describe the solution you'd like**
I want that bump like a12 app info(refer to images) in app manager app info page. 
I think that will look good 👍 please implement :)

**Describe alternatives you've considered**
No alternatives:)

**Additional context**
Yes. I have attached screenshots ;)
![IMG_20220217_154507](https://user-images.githubusercontent.com/93302440/154454971-1016d94f-8fcb-4544-93d8-81fac6dfc17a.jpg)
![IMG_20220217_154051](https://user-images.githubusercontent.com/93302440/154454978-a7fcd787-3b5c-431d-9153-a1c7e9fe9f43.jpg)

**Comment by MuntashirAkon** [comment]
The view that we're using is scrollable. Not sure how this design would fit into our system.

**Comment by Unmesh98** [comment]
Hmm you can do one thing. 
Divide options into groups of 3 with mentioned design and then make them scrollable. I think this is better.

**Comment by MuntashirAkon** [comment]
That would make the UI more confusing, leading to people believe that there are only three options.

**Comment by MuntashirAkon** [comment]
394630ea8ebaefd0484a6cb83ca67dfe2a192d1f
