### ISSUE TITLE
Disabling a package temporarily by uninstalling/reinstalling it?

### ISSUE THREAD

**Issue by xandro0777** [MuntashirAkon/AppManager#683]
I have a nasty app for a "health device" which I want to completely disable most of the day or even a few days because apparently nothing else stops it from being woken up by various broadcasts and consume energy. This is Android 11, don't want to root it yet and the device reboots often enough that enable/disable which apparently require adb method is not usable.

So the question is .. is it likely that uninstall keeping all data and reinstall when I want to use the app again would work as expected for that? Setting up the app was major hassle so avoiding the need to do it repeatedly is important.

Next, if that would work can that be automated using a profile to make it easy (and avoid user errors) or should I open a feature request for this?

Forgot to write, the app is nasty enough that it prevents backup of its data by adb.

Many thanks in advance.

**Comment by MuntashirAkon** [comment]
> is it likely that uninstall keeping all data and reinstall when I want to use the app again would work as expected for that?

Yes, it should. But if it's a system app, you can disable/enable the app using App Info page in the Android settings app which is much easier.

> Next, if that would work can that be automated using a profile to make it easy (and avoid user errors) or should I open a feature request for this?

Not possible using profile. Uninstall is a destructive operation and profile is not meant to be used for such operation. Even if it did, it would not work in no-root mode.
