### ISSUE TITLE
Ability to search the contents in the manifest viewer

### ISSUE THREAD

**Issue by Jackie7610** [MuntashirAkon/AppManager#684]
A search option/button that can help search the contents inside the manifest viewer.

Are there any chances of such a feature to be implemented in the near future?

Thank you :)

**Comment by MuntashirAkon** [comment]
Depends on #138.

**Comment by MuntashirAkon** [comment]
Added in 29e43fbc82a3ba045e573e2471cf5a8fa83b134b
