### ISSUE TITLE
no apps are found

### ISSUE THREAD

**Issue by ANN-MB** [MuntashirAkon/AppManager#686]
**Bug description**
Since last update (3.3.0-alpha01), no apps are found at all. Looping search progress bar.

**To Reproduce**
Main screen of the app. 
Try different filters.
Try keywords.

**Expected behavior**
The apps are detected ans displayed on the main screen

**Device info**
Samsung Galaxy A3 2017
Lineage OS 17 (a3y17lte)
App Manager v. 3.3.0-alpha01
Mode: root

**Comment by gnuhead-chieb** [comment]
seems duplicate:https://github.com/MuntashirAkon/AppManager/issues/685

Force-stop and Clear AM data from Settings->Apps->AppManager

then try again.

**Comment by MuntashirAkon** [comment]
Duplicate of #865
