### ISSUE TITLE
Some Incompatible API Usages in APP

### ISSUE THREAD

**Issue by Valentin-ys** [MuntashirAkon/AppManager#687]
Dear developers,

We have recently developed a state-of-the-art static analysis tool for uncovering API compatibility issues in Android apps. Applying this tool to open source apps on F-droid, we have exposed a few instances of compatibility issues and submitting them to development teams for a fix.

For your app, we have found that this project has accessed the following APIs which are available only on an API level higher than the declared minSdkVersion and which are accessed without proper protection. In other words, if those APIs get called at runtime, it will trigger a NoSuchMethodError and thus result in a crash of the running application.

1. <javax.net.ssl.X509ExtendedTrustManager: void <init>()>:[24,30]
``` java
Error invoking path: <io.github.muntashirakon.AppManager.adb.AdbUtils$2: void <init>()>[[]]--><javax.net.ssl.X509ExtendedTrustManager: void <init>()>
```
2.<android.app.usage.NetworkStats: boolean getNextBucket(android.app.usage.NetworkStats.Bucket)>:[23,30]
``` java
Error invoking path: <io.github.muntashirakon.AppManager.usage.AppUsageActivity$AppUsageAdapter: void lambda$onBindViewHolder$1$AppUsageActivity$AppUsageAdapter(io.github.muntashirakon.AppManager.usage.PackageUsageInfo,android.view.View)>[[]]--><io.github.muntashirakon.AppManager.usage.AppUsageStatsManager: io.github.muntashirakon.AppManager.usage.AppUsageStatsManager getInstance(android.content.Context)>[[]]--><io.github.muntashirakon.AppManager.usage.AppUsageStatsManager: void <init>(android.content.Context)>[]--><io.github.muntashirakon.AppManager.usage.AppUsageStatsManager: androidx.collection.SparseArrayCompat getDataUsageForNetwork(android.app.usage.NetworkStatsManager,int,int)>[[]]--><android.app.usage.NetworkStats: boolean getNextBucket(android.app.usage.NetworkStats.Bucket)>
```

3.<android.telephony.SubscriptionInfo: int getSubscriptionId()>:[22,30]
```java
Error invoking path: <io.github.muntashirakon.AppManager.usage.AppUsageActivity$AppUsageAdapter: void lambda$onBindViewHolder$1$AppUsageActivity$AppUsageAdapter(io.github.muntashirakon.AppManager.usage.PackageUsageInfo,android.view.View)>[[]]--><io.github.muntashirakon.AppManager.usage.AppUsageStatsManager: io.github.muntashirakon.AppManager.usage.AppUsageStatsManager getInstance(android.content.Context)>[[]]--><io.github.muntashirakon.AppManager.usage.AppUsageStatsManager: void <init>(android.content.Context)>[]--><io.github.muntashirakon.AppManager.usage.AppUsageStatsManager: androidx.collection.SparseArrayCompat getDataUsageForNetwork(android.app.usage.NetworkStatsManager,int,int)>[[]]--><io.github.muntashirakon.AppManager.usage.AppUsageStatsManager: java.util.List getSubscriberIds(android.content.Context,int)>[[]]--><android.telephony.SubscriptionInfo: int getSubscriptionId()>
```
Note that, because of the nature of the static analysis, we cannot confirm whether the flagged APIs would actually be called at runtime (e.g., unreachable code). However, we still believe that those APIs, which may cause compatibility issues, should not be accessed or at least be accessed with proper protections.

In addition to the aforementioned APIs (i.e., backward-compatibility), which could cause app crashes if accessed, we have also identified that this project has also accessed some APIs that have been removed from the latest public SDK, making the app possibly suffer from forward-compatibility issues.

NONE

We would be very much appreciated if you can acknowledge to us that those reported APIs are indeed problematic for the project’s long-term stability. please let us know if you need any more information relating to this issue report

**Comment by Valentin-ys** [comment]
No, it's just an issues report ofour academic researchs testing on AppManager 2.6.4.  Those APIs might be accessible on incompatibile SDK level devices. So we suggest you to add an if-then check, like "if(Build.Verion.SDK>=24)" for No.1 issue when you invoking it. If you find it helpful, you can debug relative incompatibile API usages in your App.

**Comment by MuntashirAkon** [comment]
They've already had proper annotations in the source code.
