### ISSUE TITLE
second space xiaomi tracker

### ISSUE THREAD

**Issue by codebreaker332** [MuntashirAkon/AppManager#691]
hello, the 1-click tracker blocker cannot identify the app's trackers in the second space of the xiaomi, having to be blocked one at a time,Could you improve this option so that it appears please.

**Comment by gnuhead-chieb** [comment]
works on my side with shelter.
it seems due to modifications of work profile feature of android by xiaomi.
try switching [shelter](https://f-droid.org/en/packages/net.typeblog.shelter/) or [insular](https://f-droid.org/en/packages/com.oasisfeng.island.fdroid/)

**Comment by codebreaker332** [comment]
these two are not a good option for me to use on a daily basis, that's why I requested an improvement in the blocking of trackers

**Comment by MuntashirAkon** [comment]
Should be fixed in 2d3e4765912d8ca6300ceefbbf81bcf38edcf4e2. I cannot guarantee though because I can't test it.
