### ISSUE TITLE
Options for signing and blocking trackers on installer page

### ISSUE THREAD

**Issue by Bugaddr** [MuntashirAkon/AppManager#692]
- [√] I am using the latest version of App Manager
- [√] I have searched the issues and haven't found anything relevant
- [√] I have read the docs

**Is your feature request related to a problem? Please describe.**
Whenever i want to sign a app or block trackers while installing it, i had to go back to setting of app manager. That seems like a hassel currently.

**Describe the solution you'd like**
Options to sign apk and blocking trackers can be added to installer page

**Describe alternatives you've considered**
Currently no alternative decided.

**Additional context**
None

**Comment by MuntashirAkon** [comment]
I've found at least six options that can be added here:
1. User selection
2. Installation location
3. Installer name
4. Sign APK files
5. Force dexopt after installation
6. Block trackers

**Comment by MuntashirAkon** [comment]
Implemented in b6a263a34047bf1da562c2cd929e901a4211bb5a
