### ISSUE TITLE
Tracker Blocked Indicator

### ISSUE THREAD

**Issue by Raif1** [MuntashirAkon/AppManager#695]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe
NO

**Describe the solution you'd like**
something like an indicator which indicates which and what or all tarckers are blocked from an app.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by MuntashirAkon** [comment]
Too vague. You've to be more precise. For example, we already list blocked components in the components tabs using the colour codes described in the [docs](https://muntashirakon.github.io/AppManager/en/#subsec:app-details-colour-codes).

**Comment by Raif1** [comment]
Like the brave has a tracker and i blocked it


.![gggy.png](https://user-images.githubusercontent.com/93464125/157213963-55b8a5cf-ced6-4d9f-9afc-1df7eb3285ac.png)

So as my feature suggests there will be an indicator which indicates this tracker is blocked. Like having a green color coding to mean the tracker is blocked and the default orange one is for the tracker isnt blocked.

**Comment by MuntashirAkon** [comment]
Fixed in 200afd6e0e2e4924e909668bd1ba50cadf4e7425

**Comment by Raif1** [comment]
Thanks
