### ISSUE TITLE
[UI/UX Issue] Long loading times of large app manifests

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#7]
Loading and rendering large manifests (e.g. the manifest of Android System, UID 1000) takes a very long time (10-20 seconds) during which the application is completely unresponsive.

**Comment by MuntashirAkon** [comment]
Fixed in v2.3.0. It generates dynamic manifest which may take a long time depending on app size. I now added a ProgressBar instead of the deprecated ProgressDialog. You can now go back to App Info page if you want using the back button.
