### ISSUE TITLE
Question regarding prevent background operation

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#708]
Question/Help needed regarding prevent background operation

Prevent background operation option is not available for some apps via 3 dot menu(running apps section).
However it is available via the long press menu
but doesn't work on toggling on
Also...why isn't it available for some apps/processes only??
Also dev you are great...this is an awesome app
I really appreciate your effort and would have donated in the campaign if i weren't a child(teen)🙃

https://user-images.githubusercontent.com/72438196/159173198-7a75d6e2-79cc-4430-aacb-7f3bfc95b134.mp4

**Comment by MuntashirAkon** [comment]
> Prevent background operation option is not available for some apps via 3 dot menu(running apps section).
> However it is available via the long press menu

In 3-dots menu, it specifically checks to see if `RUN_IN_BACKGROUND` app op is disabled (this has been enhanced further in 5632881405ee4492d0a3b53dac6a8e9c1a5030db) before rendering the options which is not checked when the options in the batch operations are rendered to avoid performance issues.

> Also...why isn't it available for some apps/processes only??

The feature depends on `RUN_IN_BACKGROUND` and `RUN_ANY_IN_BACKGROUND` app ops which are only applicable for the Android apps (and not any other processes).

**Comment by MuntashirAkon** [comment]
Locked due to https://github.com/MuntashirAkon/AppManager/issues/730#issuecomment-1114186327
