### ISSUE TITLE
Cannot disable any Sky Go services

### ISSUE THREAD

**Issue by danboid** [MuntashirAkon/AppManager#709]
- [x ] I know what my device, OS and App Manager versions are
- [x ] I know how to take logs
- [x ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

I have read on XDA that some have been successful in getting the Sky Go app to work on their Android TV boxes by blocking the VGDRM Helper service using App Manager. I have tried to do this without any luck because I don't see any crossed out circle icons displayed on any of the services for Sky Go under App Manager's Services screen.

**To Reproduce**

Install latest App Manager from F-Droid repos and Sky Go from Google Play Store. Open App Manager, select Sky Go then open the Services page. 

**Expected behavior**

I was expecting to see crossed out circle icons that would let me disable Sky Go services.

**Device info**
 - Device:  H10 Play 6K TV box
 - OS Version: Android 9
 - App Manager Version: 3.0.0-alpha01
 - Mode: rooted

**Comment by MuntashirAkon** [comment]
The block/unblock button is supposed to be displayed if root is present and the app is not an external APK(s). So, I am not sure how the block/unblock buttons could have been disappeared. Could you check at **settings** > **mode of ops** to see if the inferred mode is set to **root**?

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
