### ISSUE TITLE
An export option

### ISSUE THREAD

**Issue by Raif1** [MuntashirAkon/AppManager#710]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
Nah

**Describe the solution you'd like**
An export option which will let me export the .apk file of an app.And for this feature add an extra option to select where to save the .apk file.As my feature suggests  i want the option to be here
![Screenshot_20220323-iieie.png](https://user-images.githubusercontent.com/93464125/159763464-4ae63509-efae-41a4-9cdb-2e3ad2a4fc98.png)

**Describe alternatives you've considered**none

**Additional context**

**Comment by MuntashirAkon** [comment]
Use the share button located in the action bar of this tab.

**Comment by MuntashirAkon** [comment]
Shared button on top is enough in this case.
