### ISSUE TITLE
Bug related to app opps

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#712]
✓I am using the latest version of App Manager
 ✓I have searched the issues and haven't found anything relevant
 ✓I have read the docs

The app ops doesn't allow to disable/deny monitor location permission for google play services ...by the normal touch switch...but it allows to deny it via long press menu but it actually doesn't get disabled

https://user-images.githubusercontent.com/72438196/160640414-439bc54f-0748-4941-b972-f69a97603542.mp4

**Comment by kryptobolt200528** [comment]
![Uploading Screenshot_2022-04-05-10-53-38-96_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by kryptobolt200528** [comment]
![Screenshot_2022-04-05-10-53-38-96_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/72438196/161684621-89f5cedf-fd14-4d1a-98e4-a660f2f23002.jpg)

**Comment by kryptobolt200528** [comment]
https://user-images.githubusercontent.com/72438196/161684894-9c1f1b97-4aff-4578-9f9d-ef76d5f57a29.mp4

**Comment by MuntashirAkon** [comment]
Locked due to https://github.com/MuntashirAkon/AppManager/issues/730#issuecomment-1114186327

**Comment by MuntashirAkon** [comment]
As can be seen in the terminal. For this particular case, the app op reverts immediately after it was **successfully** set. So, although App Manager reported the change correctly when it was changed, it was unable to see that it was reverted just after that. Additional investigation is required to devise a way of detecting the change.

**Comment by MuntashirAkon** [comment]
Should be fixed in 4c9e83d9e5ef70f7d7bd0a408105467b1ea9058f
