### ISSUE TITLE
Add ability to manually edit ssaid and set new default andoid id

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#713]
Add ability to manually edit ssaid and set new default android id(i.e id that would be use incase of a reinstall)
Something like this ⬇️
![IMG_20220329_222839](https://user-images.githubusercontent.com/72438196/160665778-49c1a058-1f25-4428-9012-8c1e00de1311.jpg)

**Comment by MuntashirAkon** [comment]
Fixed in 0b43115f031d3200561b3aa0f9bf44574dd64734

**Comment by MuntashirAkon** [comment]
Locked due to https://github.com/MuntashirAkon/AppManager/issues/730#issuecomment-1114186327
