### ISSUE TITLE
Add ability to filter/search apps by permission/app ops

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#714]
Please add the ability to filter/search apps by permission/app ops...eg filtering apps with ACCESS_ACCESSBILITY app ops/permission

**Comment by MuntashirAkon** [comment]
Duplicate of #321

**Comment by MuntashirAkon** [comment]
Locked due to https://github.com/MuntashirAkon/AppManager/issues/730#issuecomment-1114186327
