### ISSUE TITLE
Change the app icon

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#715]
I think this icon would look better
![Picsart_22-03-30_08-33-06-960](https://user-images.githubusercontent.com/72438196/160745176-d8ef7b71-dea3-448a-833a-e511d57474a7.png)

**Comment by MuntashirAkon** [comment]
The icon has already been updated from @atrate's original work to improve its colours and geometry.

**Comment by MuntashirAkon** [comment]
Locked due to https://github.com/MuntashirAkon/AppManager/issues/730#issuecomment-1114186327
