### ISSUE TITLE
Monet/Material You & Updater Request Suggestions

### ISSUE THREAD

**Issue by zkollz** [MuntashirAkon/AppManager#717]
please read these suggestions:

1. Add Compatibility with Monet/Material You, so it can be themed by repainter.
2. Add a way to check for updates and alert the user when entering the app so as not to be out of date.

**Comment by Raif1** [comment]
Where ?

**Comment by MuntashirAkon** [comment]
> Where ?

For some reason, the author has chosen to use the title to describe what they want.

**Comment by zkollz** [comment]
> > Where ?
> 
> For some reason, the author has chosen to use the title to describe what they want.

I don't know if the app manager already has it integrated but I think it would be great if it included an autorun manager to deactivate the autostart of some apps 🤔

**Comment by zkollz** [comment]
> > Where ?
> 
> For some reason, the author has chosen to use the title to describe what they want.

I don't know if the app manager already has it integrated but I think it would be great if it included an autorun manager to deactivate the autostart of some apps 🤔

**Comment by MuntashirAkon** [comment]
> I don't know if the app manager already has it integrated but I think it would be great if it included an autorun manager to deactivate the autostart of some apps 🤔

See #309

**Comment by MuntashirAkon** [comment]
> Add Compatibility with Monet/Material You, so it can be themed by repainter.

Already added in v3.0.0 (will be available at the end of the next month).

**Comment by MuntashirAkon** [comment]
> 2\. Add a way to check for updates and alert the user when entering the app so as not to be out of date.

Closing in favour of #931
