### ISSUE TITLE
Select a higher DPI if no supported DPI is available during split APK installation

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#718]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Title describes everything.AM installer doesn't checks xxhdpi split.
without this split,installed app will be crash.

**Comment by MuntashirAkon** [comment]
One of mdpi, ldpi, hdpi, xhdpi, xxhdpi, xxxhdpi and mdpi is chosed based on your device configuration. However, none of them are selected if you are updating an app and the app previously didn't have one of them installed.

**Comment by MuntashirAkon** [comment]
Fixed in cfe682196afa2fa9b4ab0662d99bd50ab91139d5
