### ISSUE TITLE
Won't Load Apps on Samsung Tab A7

### ISSUE THREAD

**Issue by rjm831** [MuntashirAkon/AppManager#724]
When I start App Mgr it doesn't load any apps at all - it just stays in an infinite loop attempting to load them.  All other functions seem to work properly.  This issue began several updates ago - I'm currently using the latest beta (3.0.0 alpha 2).  Will provide any logs or other data you may wish.
I'm using a Samsung Tab A7 (Android 11), non-root,  and App Mgr has all permissions granted.

**Comment by MuntashirAkon** [comment]
Please install a debug builds from GitHub actions (or Telegram channel) and capture some logs using logcat.

**Comment by rjm831** [comment]
Uninstalled beta, rebooted, installed debug build, and ... the debug build worked properly.  So I uninstalled it, rebooted, installed the latest beta again, and now everything is functioning properly.  I have no explanation for why AppMgr wasn't loading the tablet's apps before (perhaps Samsung's latest security update?) but it's working properly now.  I apologize for bothering you with this issue.  And thank you sincerely for your work in developing this app - it is appreciated.
