### ISSUE TITLE
Interceptor taking over viewing photos in the camera app

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#726]
I only see this on one device (I don't know why - I don't think I did anything particularly different on it). In the camera app, when I press the button to view photos already taken, AppManager Interceptor pops up:

Action: com.android.camera.action.REVIEW

Data: content://media/external/images/media/17515

URI: intent://media/external/images/media/17515#Intent;scheme=content;action=com.android.camera.action.REVIEW;end

Macthing activities: Interceptor:
io.github.muntashiakon.AppManager
io.github.muntashiakon.AppManager.intercept.ActivityInterceptor

I can't figure out how to get into any kind of view mode. I probably do have some setting screwed up, but how do I get AppManager to let the camera app show me past photos?

**Comment by MuntashirAkon** [comment]
AM is opened first most probably because you do not have any other app to open this intent. If not, try disabling Interceptor feature from settings inside AM.
