### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#729]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Keyboard auto pop up every time you open
1. The app 1st time
2. when go to any other app options & come back to AM home screen
App version: v3.0.0-ALPHA01

**Expected behavior**
Do not focus on AM search bar like AM's earlier versions (ex: v2.6.5.1)

**Screen recording**

https://user-images.githubusercontent.com/48226312/162117776-d6bdc839-8b03-48a9-a5d1-2043f0d7fa5e.mp4

**Device info**
Checked in my both Tab & Phone both running android 8.1.0, tested with both AnySoftKeyboard & FlorisBoard, same issue.

**Additional info**
![Screenshot_2022-04-07-09-46-01](https://user-images.githubusercontent.com/48226312/162119110-4105cc4b-4a1f-4683-a7f0-8b651e2baf78.jpeg)

Not sure if "auto-focus-on-search" added to AM v3+ with this search filter feature. But it's annoying to force close keyboard repetitively.

_(probably this happens on Android versions less than 8. Similar [issue](https://github.com/VishnuSanal/Quotes/issues/56) from another app)_

**Comment by MuntashirAkon** [comment]
Fixed in 52de0f43b0830bc2b2a5fda686c11ab89550739e
