### ISSUE TITLE
Add a prompt to upload large apps to virustotal if not found in database

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#730]
I have been facing a problem wherein app (of size >50mb)manager is unable to produce virus total scan result for an app,due to it not being on the virustotal database(checked using website)

App manager doesn't automatically upload the app on the database(maybe since its too large )and therefore one cannot get results...
Please add a prompt for uploading such big apps (apk)to the database

![Screenshot_2022-04-07-10-46-46-66_7036e97d057c640af5e19886b605c25a](https://user-images.githubusercontent.com/72438196/162125356-65855b77-0a08-4d09-b2a9-79f2ef038db4.jpg)
Note:The app is <650mb and therefore can be uploaded to VT so the size limit is not a problem here..also the 4 request per minute limit is also not a problem

**Comment by MuntashirAkon** [comment]
VT has 32 MB limitations via public API. See API docs: https://developers.virustotal.com/v2.0/reference/file-scan

**Comment by MuntashirAkon** [comment]
Editing a feature request in a way as to change the original request is a serious violation, against the project and its contributors. This will be first and final warning against such act.

In addition, all the issues created by you in the past shall be locked to prevent further modification.
