### ISSUE TITLE
App manager not working on S10+ One UI 4.1 Android 12

### ISSUE THREAD

**Issue by edersonmax21** [MuntashirAkon/AppManager#734]
Good morning, after an update on my cell phone, my app manager doesn't work anymore, I can't make the wireless debugging connection anymore, I would like you to fix it if possible because I really like the app manager.

![Screenshot_20220418-151505_App Manager.jpg](https://user-images.githubusercontent.com/52547471/163854424-6ca75b7b-bdf9-4a36-8e95-97bd2b171f91.jpg)

![Screenshot_20220418-151459_App Manager.jpg](https://user-images.githubusercontent.com/52547471/163854434-f2ce46b8-8101-4c69-8c71-a864e7e7c2b3.jpg)

![Screenshot_20220418-151448_App Manager.jpg](https://user-images.githubusercontent.com/52547471/163854444-7a4393d9-32d7-4377-bb38-28620b0fb61d.jpg)

![Screenshot_20220418-151406_App Manager.jpg](https://user-images.githubusercontent.com/52547471/163854461-511ddda7-8f3c-49da-af81-d90500ad03f3.jpg)

**Comment by ZenerDeveloper** [comment]
Can confirm, works intermittently on S21 Ultra with android 12 oneui 4.1 with wireless debugging or adb over tcp.

**Comment by edersonmax21** [comment]
On mine it's not working, I don't know what's wrong, maybe it's my cell phone patch.

**Comment by MuntashirAkon** [comment]
Sharing some logs would definitely help.

**Comment by MuntashirAkon** [comment]
Looks like it might already be fixed. You might try one of the latest debug builds to check this.

**Comment by UltraBlackLinux** [comment]
I can confirm, that the debug builds fix this
