### ISSUE TITLE
Seeking info -- Can AppManager disable apps from auto starting? 

### ISSUE THREAD

**Issue by sperglord8008s** [MuntashirAkon/AppManager#737]
Hello,
Firstly your App is outstanding thank you for the amazing work!

Just a quick question, I've had a search thru your documentation and i cant seam to find any information on if AppManager can disable apps from automatically starting in the background, I check the running apps every so often and find so many apps i haven't used are for some reason running in the background . Its very frustrating!  

I am using a Nexus 6P on Android 8 Rooted. 

Thanking you in advance amigo.

**Comment by MuntashirAkon** [comment]
No. See #309
