### ISSUE TITLE
Android App Bundle(AAB) installation support

### ISSUE THREAD

**Issue by DaniAndTheWeb** [MuntashirAkon/AppManager#741]
It would be great if it were possible to add support for installing Android App Bundles.

**Comment by MuntashirAkon** [comment]
AAB files are meant to be utilised by the developer, not the end-users. Using **bundle-tools** (also provided by Google), the developer can easily convert it to APKS and supply it to the end-users.

**Comment by ildar** [comment]
@MuntashirAkon does this mean that `APKS` format is supported?

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon does this mean that `APKS` format is supported?

Yes.
