### ISSUE TITLE
Uninstalling App from main list doesn't work

### ISSUE THREAD

**Issue by shifoc** [MuntashirAkon/AppManager#745]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
I can't uninstall an app by selecting it from the main list

**Device info**
 - Device: Samsung S22 Ultra
 - OS Version:  Android 12
 - App Manager Version: v3.0.0-alpha3
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Added in 6f01603d78e28a43ec38941410bd40f025d1df8b
