### ISSUE TITLE
Replace “Force-stop” with freeze and more

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#749]
“Freeze” and “disable” option can be user-configured in the following way:

1. Freeze: Either force-stop (default) or suspend (Android 7+)
2. Disable: Either disable (default) or hide

**Comment by bolbolfolfol** [comment]
where can i find the setting ?
i tried the latest beta but i still can see freezed apps

**Comment by MuntashirAkon** [comment]
> where can i find the setting ? i tried the latest beta but i still can see freezed apps

The issue is still _pending_, that is, this issue still hasn't been decided for implementation.

**Comment by bolbolfolfol** [comment]
> > where can i find the setting ? i tried the latest beta but i still can see freezed apps
> 
> The issue is still _pending_, that is, this issue still hasn't been decided for implementation.

i see, good luck (i really need it, i don't want lucky patcher anymore ^.....^)
if you have some time please add "pitch black" theme (pure black) to the app and thank you
