### ISSUE TITLE
Cannot uninstall a system app

### ISSUE THREAD

**Issue by yephny** [MuntashirAkon/AppManager#753]
**Describe the existing feature/documentation**
I cannot uninstall Google Play Services installed as part of open Gapps for some reason. I intend to replace it with microg's GmsCore, but it has a different signature, so I have to uninstall the one currently installed (even though signature spoofing is enabled). Whenever I uninstall it, it still says there's an app with the same package name if I try to install gmscore. Searching for Play Services in app manager brings up a result, tapping which prompts a reinstall menu. My device's rooted with Magisk.

**Comment by MuntashirAkon** [comment]
> even though signature spoofing is enabled

**Signature spoofing ≠ Disabling signature verification.** To disable signature verification, you can apply [CorePatch](https://github.com/LSPosed/CorePatch), but it's not advised as it has detrimental effect on the overall security of your operating system.

> Whenever I uninstall it, it still says there's an app with the same package name if I try to install gmscore.

App Manager only uninstall the app for the user, it does not delete the app completely as it is located in the system partition (App Manager never modifies a system partition). A workaround for this is to install the app systemless-ly over the APK via Magisk.
