### ISSUE TITLE
is app manager deleting APK files after installing?

### ISSUE THREAD

**Issue by nutpantz** [MuntashirAkon/AppManager#756]
I download a lot of apk files but after i started using app manager when i go back to the download directory days after install  the files are gone. 

It is either app manager or maybe Android 12 on my new pixel auto cleaning space, if that is possible

**Comment by MuntashirAkon** [comment]
App Manager never deletes APK files. So, I guess it is some sort of auto-cleaning feature either by the system itself (enabled somewhere) or any third-party apps such as LTE Cleaner which you may not be aware of.
