### ISSUE TITLE
Fail to block trackers in the Providers tab

### ISSUE THREAD

**Issue by Ryakna** [MuntashirAkon/AppManager#757]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Cannot block trackers in the Providers tab

**Device info**
 - Device: Poco F3
 - OS Version: LineageOS 18.1
 - App Manager Version: 3.0.0-alpha02
 - Mode: root

**Additional context**
Whenever I try to block trackers, either from 1-click ops or directly within an app listing, all of them are successfully blocked with the exception of those in the Providers tab. Am I doing something wrong?

**Comment by MuntashirAkon** [comment]
How did you block trackers there? Blocked a components one by one or using the “block/unblock trackers” option in the menu?

**Comment by Ryakna** [comment]
> How did you block trackers there? Blocked a components one by one or using the “block/unblock trackers” option in the menu?

Tried first to block through 1-Click Ops in the 3-dot menu and it blocks all trackers except those in the providers tab.

Then tried to tap and hold the app on the main list and select "Block/unblock trakers", same result.

Also tried to open each app on the main list, go to providers tab and tap on "IFW + disable" on the relevant entries (trackers) and it appears to work but after pulling down to refresh, they're not blocked.

As I said, this only happens with entries on the providers tab, all other trackers are successfully blocked.

**Comment by MuntashirAkon** [comment]
App Manager version that you are using is not supported. Update to v3.0.0-rc01 and try again.
