### ISSUE TITLE
Advanced search to find contents from all apps at once

### ISSUE THREAD

**Issue by metronightly** [MuntashirAkon/AppManager#762]
- [ √ ] I am using the latest version of App Manager (v3.0.0-rc01)
- [ √ ] I have searched the issues and haven't found anything relevant
- [ x ] I have read the docs

Hey, Muntashir. For context, I recently found a tracker called applovin on my DNS Logs and after going through 'Services' and 'Activity' of each app one by one, I found the culprit.

This incident got me thinking.. App Manager already has a search function that can be used to search for keywords inside an App(Services, Activities, Permissions etc) but it feels limited in the sense that we need to open app one by one and search inside.

What I'm proposing is a global search feature that would search for keywords through all the apps at once. Currently, the search on the main menu only finds app name. So it would be great if there was an option for a powerful search that would kind of scan and find keyword from all the apps at once like how it does inside single apps.

I don't know if this is even possible but just wanted to share.

Edit: looks like #321 matches my request.

**Comment by MuntashirAkon** [comment]
Duplicate of #321
