### ISSUE TITLE
App ops missing for Google and other google related apps

### ISSUE THREAD

**Issue by Hikandy** [MuntashirAkon/AppManager#763]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
I want to disable few app ops like run in bg etc for Google but there are literally no app ops available for Google when i try to open that app here

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Google app ops tab
2. It shows no app operations 

**Expected behavior**
There should be app operations

**Screenshots**
https://forum.xda-developers.com/attachments/screenshot_20220509-175835-png.5610193/

**Device info**
 - Device: HTC U11
 - Android 9
 - App Manager Version: 3.0.0-alpha3
 - Mode: root

**Comment by MuntashirAkon** [comment]
Unfortunately, I do not use any Google apps, so you have to provide some logs from the [debug releases](https://muntashirakon.github.io/AppManager/en/#subsec:binary-distribution-sources).

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
