### ISSUE TITLE
RTL layout issues in FlowLayout

### ISSUE THREAD

**Issue by rex07** [MuntashirAkon/AppManager#764]
- [✓] I know what my device, OS and App Manager versions are
- [✓] I know how to take logs
- [✓] I know how to reproduce the issue which may not be specific to my device

**Describe the  #bug*

**To Reproduce**
1. Go to 'app settings'
2. Click on 'Layout orientation'
3. Set  layout orientation 'to rtl'

**Expected behavior**
 Center buttons

**Screenshots**

**Crash logs**
No need for it .

**Device info**
 - Device: [Nokia 9]
 - OS Version: [e.g. Android 12]
 - App Manager Version: v3.0.0
 - Mode: root

**Additional context**
None.

**Comment by rex07** [comment]
RTL
![Screenshot_20220527-142316_AM_Debug](https://user-images.githubusercontent.com/13156001/170692607-f0c45070-fac2-4f19-a14c-adecf3b0bdbc.png)
LTR
![Screenshot_20220527-142253_AM_Debug](https://user-images.githubusercontent.com/13156001/170692700-7791c352-6993-4444-bfc9-f24f28dc3354.png)

**Comment by MuntashirAkon** [comment]
Fixed in 0c8f3724b0ddb3815d5b370f87e5fcf33cbfa160. If you encounter more/other issues, please do inform me.

**Comment by rex07** [comment]
all fine now 
Thank You
