### ISSUE TITLE
crash when clicking setting

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#766]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**To Reproduce**
just opening settings from 3-dot-menu.

**Crash logs**
https://paste.crdroid.net/qg46XS

**Device info**
 - Device: crDroid A12 Begonia
 - App Manager Version: [Debug 1815](https://github.com/MuntashirAkon/AppManager/actions/runs/2396217383)
 - Mode: root

**Comment by MuntashirAkon** [comment]
It would be better if you provided the crashlog prepared by App Manager. It would clear things up.

**Comment by gnuhead-chieb** [comment]
After clearing data of AM,settings opens correctly and cannot reproduce again.

**Comment by MuntashirAkon** [comment]
Could be fixed in 635dcd6255f0c78e59df5c9d2119eab2623a666e
