### ISSUE TITLE
disclaimer when changing the system theme

### ISSUE THREAD

**Issue by andsofine** [MuntashirAkon/AppManager#768]
- [✓] I know what my device, OS and App Manager versions are
- [✓] I know how to take logs
- [✓] I know how to reproduce the issue which may not be specific to my device

The disclaimer (App manager offers root functions...) is shown when turning the dark theme on/off

does not happen if you tick "Never show this again"

**Screenshots**
![Screenshot_20220602-230949](https://user-images.githubusercontent.com/99369164/171729377-077e43b1-5ee2-41d5-9c65-9ac15055388b.png)

**Device info**
 - Device: Pixel 4 xl
 - OS Version: Android 12L grapheneos
 - App Manager Version: 3.0.0-rc02
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Fix in 4229df6bf1552fc6b4953233b442f64e62618be2
