### ISSUE TITLE
Add translation in pt_BR

### ISSUE THREAD

**Issue by aevw** [MuntashirAkon/AppManager#77]
Hi AppManager devs,

I translated your app into pt_BR, it has lots of IT phrases which I left out eg boolean, iteger. I think that those are well understood by ppl that use this app.

Anyway, here is the file:
[pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/appmanager_strings-pt_BR.xml) 

Thanks

**Comment by MuntashirAkon** [comment]
Are you the same person who translated pt_BR in the Crowdin site (here: https://crowdin.com/project/android-app-manager/pt-br)?

**Comment by aevw** [comment]
You got me by surprise, nope it's not me. Even though I did some translations on there for other projects as well. Let's hope at least some part of this translation will serve you.

**Comment by MuntashirAkon** [comment]
> You got me by surprise, nope it's not me. Even though I did some translations on there for other projects as well. Let's hope at least some part of this translation will serve you.

If you have an account there, join in and upload the strings there. In this way, it would be easier to select the best translations.

BTW, I was about to add pt_BR translations in the next version tomorrow. You've contacted me in the right time, I've to say :)

**Comment by aevw** [comment]
To be honest I don't like working online on translations it takes way to much time. That's why I translate strings offline upload them and offer them to be merged. So please use what you think might be useful. I think overall quality is pretty good.

**Comment by MuntashirAkon** [comment]
> To be honest I don't like working online on translations it takes way to much time. That's why I translate strings offline upload them and offer them to be merged. So please use what you think might be useful. I think overall quality is pretty good.

You can upload the string file in Crowdin as well, I think. If you don't have an account, I can upload it for you. I cannot make any decision about the strings in your language since I don't know Portuguese (and certainly not the Brazilian Portuguese). If your versions are uploaded there as well, it would be easier to choose which translation to keep by the proof readers in future.
