### ISSUE TITLE
auto language change

### ISSUE THREAD

**Issue by andsofine** [MuntashirAkon/AppManager#770]
- [✓] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [✓] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
the language in the app is set to auto, but when I change the system language, the language in the app doesn't change
even after restarting the app

the language I am switching to is in the list of languages ​​of the application. so this is not due to its absence

**Device info**
 - Device: Pixel 4 xl
 - OS Version: Android 12L grapheneos
 - App Manager Version: 3.0.0-rc02
 - Mode: no-root

**Comment by MuntashirAkon** [comment]
Fixed in 635dcd6255f0c78e59df5c9d2119eab2623a666e
