### ISSUE TITLE
[UI] Action bar background color blinking while scrolling 

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#775]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Action bar color in the app detail page keeps changing/blinking while we scroll the page. I have attached a video of it below. 

**Expected behavior**
Shouldn't blink or stay consistent

**Screenshots**

https://user-images.githubusercontent.com/83750299/172086432-a50698c1-447f-480a-ac7c-06255f1021f6.mp4

**Device info**
 - Device: Note 10 pro
 - OS Version: 12.1
 - App Manager Version: latest debug
 - Mode: root

**Comment by MuntashirAkon** [comment]
https://github.com/material-components/material-components-android/issues/2591

**Comment by MuntashirAkon** [comment]
Fixed in 7ee3eb9b462e71cbf0c654f1d2ed802fa8d5df6c
