### ISSUE TITLE
Little bug on clean cache after adb app disable

### ISSUE THREAD

**Issue by samuraikid0** [MuntashirAkon/AppManager#776]
- [ x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
So if you remove an app via adb, when you select all apps the clean button becomes gray you need to unselect the removed app to be able to click it and clean

**Expected behavior**
Clean even the disabled apps

**Screenshots**
![Uploading Screenshot_20220606-030413_App_Manager.png…]()

**Device info**
 - Device: [Samsung S7]
 - OS Version: [Android 10]
 - App Manager Version: [e.g. v3.0.0-rc02 (404) ]
 - Mode: root/

**Comment by MuntashirAkon** [comment]
You've submitted the form before the image was completely uploaded.

**Comment by samuraikid0** [comment]
> You've submitted the form before the image was completely uploaded.

![Screenshot_20220606-030413_App_Manager](https://user-images.githubusercontent.com/46766062/172211976-ede23803-3fe9-4246-9c9b-9f1dd19d09c8.png)
![Screenshot_20220606-030401_App_Manager](https://user-images.githubusercontent.com/46766062/172212002-976d71b9-d6b1-41ac-ae95-621f7b519c10.png)

**Comment by MuntashirAkon** [comment]
Did you disable it or uninstall it?

**Comment by samuraikid0** [comment]
> Did you disable it or uninstall it?

Sorry its uninstalled has root the script uses the command

pm uninstall --user <user> <package>
