### ISSUE TITLE
Fails to read PKCS12 keystore format; JKS is able to be read

### ISSUE THREAD

**Issue by jonathan2384** [MuntashirAkon/AppManager#787]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Reading a PKCS12 format keystore within Settings>APK Signing fails with `Could not read the KeyStore`, despite the password being correct. Other keystore formats appear to work, including a JKS format keystore.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the provided `demo.keystore` (password is `password`) or generate a new PKCS12 format keystore with Java Keytool.
2. Verify that the keystore is of PKCS12 format and that it is able to be read by keytool with `keytool -list -keystore demo.keystore`
3. Go to the APK signing option within App Manager, and click Signing key. Import by selecting `PKCS # 12` as the keystore format and use the password (that has been shown to be correct with keytool -list)
4. The error should occur.

**Expected behavior**
As other tools, such as the Java Keytool, is able to read the PKCS12 format keystore, I would have expected App Manager to be able to read and import the keystore as well.

I've also verified that the example keystore provided is able to be used to sign an APK with [uber-apk-signer](https://github.com/patrickfav/uber-apk-signer) .

**Screenshots**
![Screenshot_20220624-135029_Termux](https://user-images.githubusercontent.com/93066841/175464584-66572cb7-87c7-4617-9dee-a4dbe074cea7.jpg)
*Screenshot shows the command used to generate the example keystore provided in this issue. It's also verified that it is able to be read and that it is PKCS12 format by `keytool -list -keystore demo.keystore -alias client`*

![Screenshot_20220624-133411_App Manager](https://user-images.githubusercontent.com/93066841/175464725-aa8f1761-6bb9-47fd-97d2-241046e8acaa.jpg)
*The same keystore fails to be imported in App Manager, despite the correct password and keystore format "PKCS # 12" being selected.*

![Screenshot_20220624-135703_Termux](https://user-images.githubusercontent.com/93066841/175465201-1c54fbdd-e85b-405e-a92a-ae02976f0932.jpg)
*Able to use uber-apk-signer to sign the APK with provided example PKCS12 keystore.*

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: Samsung Note 20 Ultra
 - OS Version: Android 12, One UI 4.1 on May 2022
 - App Manager Version: 2.6.5.1
 - Mode: no-root

**Additional context**
[Demo keystore](https://drive.google.com/file/d/1ksGOArNaZOlT6Oi8Oyvf-VFrrfou3ijy/view?usp=sharing)

**Comment by MuntashirAkon** [comment]
Fixed in 115011d894c8fb85df30c05a78b0d08d1c3434b5
