### ISSUE TITLE
Not able to "Add to profile" from main app screen

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#788]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
I have created an empty profile. Adding apps in the profile works fine from Profile Screen but not from the home screen's long press selection menu after selecting apps.

**To Reproduce**
Steps to reproduce the behaviour:
1. Long press and select apps from main screen.
2. Tap on "add to profile" and select a profile and done.
3. Check the profile again and the selected apps aren't there.

**Expected behavior**
Should add the selected app to profile.

**Device info**
 - OS Version: Android 12.1
 - App Manager Version: Debug latest
 - Mode: root

**Comment by MuntashirAkon** [comment]
Fixed in c0fc9a6ff1ff58a0b70f55f12ac33364efd8aef6
