### ISSUE TITLE
Not possible anymore to install apps with different signature

### ISSUE THREAD

**Issue by 1RandomDev** [MuntashirAkon/AppManager#793]
**Describe the existing feature/documentation**
In a previous version of app manager it was possible to install an app with a different signature without deleting the data which worked extremely well, but apperantly this option got removed in a newer update :C

**Describe your problem(s)**
I want to be able again to install apps with different signatures while keeping the data.

**Comment by MuntashirAkon** [comment]
Such options were never added. See https://github.com/MuntashirAkon/AppManager/issues/753#issuecomment-1129476671
