### ISSUE TITLE
[UI Enhancement] Adaptive icon/Distinct icon from AppsPackagesInfo

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#8]
I've noticed that the app doesn't possess an adaptive icon, making it stand out (in a bad way) from other such apps. 

I think it would also be reasonable to make it so that the app's icon would be distinct from its predecessor, AppsPackagesInfo.

**Comment by MuntashirAkon** [comment]
I agree. But I'm not creative in that particular field :( So, I'll stick to it until I get some idea or somebody provides me some.

**Comment by Atrate** [comment]
One thing I've seen a couple of projects do is simply saturate the icon with a colour, like this:

![ic_launcher_app_manager](https://user-images.githubusercontent.com/26827848/83903903-4041b080-a75f-11ea-8405-5b11b9fdef89.png)

This could serve as a placeholder until a better icon is made.

**Comment by MuntashirAkon** [comment]
> If you agree, I can quickly make a PR and replace https://github.com/MuntashirAkon/AppManager/blob/master/app/src/main/res/drawable-xxhdpi/ic_launcher_app_manager.png with the above.

No problem.

**Comment by Atrate** [comment]
@MuntashirAkon 

So far I've managed to come up with a few possible icons, which ones do you like best?

![image](https://user-images.githubusercontent.com/26827848/84383720-1d931a00-abed-11ea-9899-e47ad2b93f4a.png)

![image](https://user-images.githubusercontent.com/26827848/84383754-2c79cc80-abed-11ea-944a-eca7f1c7d06e.png)

![image](https://user-images.githubusercontent.com/26827848/84383806-3d2a4280-abed-11ea-8de3-3ce03a511f0b.png)

![image](https://user-images.githubusercontent.com/26827848/84383833-516e3f80-abed-11ea-95d7-5107efbbe7c0.png)

![image](https://user-images.githubusercontent.com/26827848/84383852-5af7a780-abed-11ea-815c-fb1a4ae9f8db.png)

![image](https://user-images.githubusercontent.com/26827848/84383879-634fe280-abed-11ea-8de4-ee5e7a89fcd4.png)

![image](https://user-images.githubusercontent.com/26827848/84383898-6c40b400-abed-11ea-9e79-00b80619cb08.png)

**Comment by MuntashirAkon** [comment]
I like the second one I think. It is based on the accent color (of night mode) I believe.
