### ISSUE TITLE
Add App Firewall

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#80]
Being an _app manager_, AM should support app firewall, preferably, for both root and non-root users.

### Related implementations
- [AFWall+](https://github.com/ukanth/afwall)
- [NetGuard](https://github.com/M66B/NetGuard)
- [Tracker Control](https://github.com/OxfordHCC/tracker-control-android)

Actually, there is already an iptables-based firewall implementation available within AM (thanks to AppOpsX). But it doesn't yet have a front-end.

**Comment by Atrate** [comment]
It is also possible to implement a firewall through Xposed (EdXposed) (to augument an iptables-based one, not replace it).

An example implementation is [https://forum.xda-developers.com/xposed/modules/app-lightningwall-t2746254](LightningWall) by Defim, but it is not open-source.

**Comment by MuntashirAkon** [comment]
> It is also possible to implement a firewall through Xposed (EdXposed) (to augument an iptables-based one, not replace it, since an Xposed-based fw will always be active, even on startup).
> 
> An example implementation is [https://forum.xda-developers.com/xposed/modules/app-lightningwall-t2746254](LightningWall) by Defim, but it is not open-source.

Xposed is not supported by my device. So, no support for Xposed will be provided in AM.

**Comment by 0pLuS0** [comment]
Am should support firewalls in what way?

**Comment by MuntashirAkon** [comment]
> Am should support firewalls in what way?

This discussion here is purely technical. Once the implementation is completed, I'll add a user-friendly documentation in the docs site.

**Comment by 0pLuS0** [comment]
Ok, I was just hoping that a firewall was not going to be implemented into AM is all...

THANKS

**Comment by MuntashirAkon** [comment]
> Ok, I was just hoping that a firewall was not going to be implemented into AM is all...

An app manager should manage every aspects of an app, not just install/uninstall/backup/restore.

> P.S. I am Technical I am a Linux Geek of 20 years... 👍

Then you should know that AM already uses Intent Firewall to block app components. Internet firewall is different but very similar concept.

**Comment by 0pLuS0** [comment]
Well I'm not an Android Geek, that's the problem, in Linux Application Managers only manage, installing, removing, updating, helping to manage them, no Firewalls.

To me an app manager and a firewall are two different things in the computer world, I guess not so in Android? 

I assumed AM is simply going to disable an application and it's components, therefore crippling it, without the need for any firewall? Hmm

**Comment by MuntashirAkon** [comment]
> I planned to run AFWall+ on a next release, how is this firewall going to work, with what is being done in AM, in regards to the Intent Firewall, might this cause any conflicts?

AFWall+ isn't an Intent Firewall, it's an Internet Firewall.

This isn't the place to describe everything about Android firewall system. For intent firewall, you can visit the external links provided in the FAQ section.

**Comment by 0pLuS0** [comment]
Yes I understand this isn't the place of these discussions.

I only have one question, so AFWall+ and the Intent Firewall can't create conflicts with each other?

THANKS

**Comment by MuntashirAkon** [comment]
> I only have one question, so AFWall+ and the Intent Firewall can't create conflicts with each other?

No, these are completely different things.

**Comment by 0pLuS0** [comment]
Ok sorry my bad...

**Comment by UltraBlackLinux** [comment]
I would not want an afwall implementation - keep it apart please. App manager is not an app replacer - it's a toolkit-thing for managing apps - the most I would add is a link to afwall's github or an install button.
I mean, if AM had weird random crashes, afwall would also die. AFwall is very important for me btw.

**Comment by MuntashirAkon** [comment]
> I would not want an afwall implementation - keep it apart please.

You're again talking out of context here. I link the related implementations to study how they work or how they are related.

That being said, AM isn't going to implement AFWall+ because AM will not include methods which do not work. IPC on Android is very different from what you see in most operating systems and typical firewall doesn't really work for apps which badly want to connect to the Internet and you'll never know until you capture packets because the data usage will never display anything in the app settings.

**Comment by MuntashirAkon** [comment]
As I mentioned earlier, Android is built in such a way that it is impossible to stop an app from connecting to the Internet using the IP Tables on its own. The alternative way would be to use VPN style blocking like NetGuard (pDNSf or hosts based blocking are beyond the scope of this project). But I think NetGuard already offers the best service and implementing such feature in AM will further complicate things. In future, I may consider adding this functionality as a separate add-on. But the original issue can't be implemented. But the related [branch](https://github.com/MuntashirAkon/AppManager/tree/firewall) will still be kept.
