### ISSUE TITLE
root mode failed to work and splash screen takes too much time

### ISSUE THREAD

**Issue by molitona** [MuntashirAkon/AppManager#803]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
I upgraded to latest available apk and noticed that:
The root mode always failed to work (see screenshot)
Splash screen takes 46s saying "initializing"

I rebooted and cleared cash after apk install.

I use Magisk for root and worked fine with AM in my last version 2.6.x

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Click on 'mode of operation'
3. Click on 'root'

**Expected behavior**
Root mode works and lower time for splash screen

**Screenshots**
This is the Toast after selecting Root mode. It tooks 1m to check and shows that.
![2](https://user-images.githubusercontent.com/35532337/178491799-8eb6f3dc-f88e-463f-b262-dad40327e60a.png)

**Device info**
 - Device: [Samsung J3 2016]
 - OS Version: [7.1.2]
 - App Manager Version: [3.0.0-rc04]
 - Mode: root

**Comment by MuntashirAkon** [comment]
Which rooting app? If it is Magisk, which version?

**Comment by molitona** [comment]
Magisk Manager 8.0.4

**Comment by MuntashirAkon** [comment]
> Magisk Manager 8.0.4

Not Magisk Manager, Magisk version. (Magisk Manager is discontinued, by the way. You should migrate to Magisk.)

**Comment by MuntashirAkon** [comment]
Try the last debug build from GitHub Actions to see if it can detect root. (It uses a different package name and can be installed side-by-side with the one you've already installed.)

**Comment by molitona** [comment]
> Try the last debug build from GitHub Actions to see if it can detect root. (It uses a different package name and can be installed side-by-side with the one you've already installed.)

It doesn't work too..

**Comment by molitona** [comment]
> > Magisk Manager 8.0.4
> 
> Not Magisk Manager, Magisk version. (Magisk Manager is discontinued, by the way. You should migrate to Magisk.)

Magisk 21.1

**Comment by molitona** [comment]
Works fine.

Jul 13, 2022, 16:44 by ***@***.***:

**Comment by MuntashirAkon** [comment]
What's the output of `which su`?

**Comment by molitona** [comment]
> What's the output of `which su`?

/sbin/su

**Comment by molitona** [comment]
@MuntashirAkon 

any update ?

**Comment by MuntashirAkon** [comment]
> any update ?

None. If `/sbin/` in the the `PATH` variable, App Manager should be able to detect root automatically unless something is preventing App Manager from accessing it. App Manager uses the [same library](https://github.com/topjohnwu/libsu) that Magisk (Manager) itself use. So, I don't see why App Manager should be affected by this.

In any case, try with the latest debug build (Run#1912) and filter the logs by `RunnerUtils` and send them here.

**Comment by molitona** [comment]
I installed that build, filtered with that keyword and the filter doesn't show any entry ! 


Jul 21, 2022, 06:48 by ***@***.***:

**Comment by MuntashirAkon** [comment]
In that case, you've to send full system logs using Build#1917. Make sure to uninstall the previous build before installing the new one.

**Comment by molitona** [comment]
> In that case, you've to send full system logs using Build#1917. Make sure to uninstall the previous build before installing the new one.

This build worked perfectly. I got root access.
