### ISSUE TITLE
Reverting changes for Block components

### ISSUE THREAD

**Issue by kgursu** [MuntashirAkon/AppManager#805]
**Describe the existing feature/documentation**
Reverting changes for Block components option of 1-Click Ops menu

**Describe your problem(s)**
I have blocked com.facebook with this option. Some apps crashed with this. So, I need to revert this for some apps or if not possible for all.

**Additional contexts**

**Comment by MuntashirAkon** [comment]
Currently, the only way that I can think of is via profiles.

**Comment by MuntashirAkon** [comment]
#853
