### ISSUE TITLE
F-Droid II

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#81]
[Here you go](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7260) – I hope that's the final move now :wink: Otherwise we'll need a new issue, as this one already loads ages when I try to open the page…

_Originally posted by @IzzySoft in https://github.com/MuntashirAkon/AppManager/issues/1#issuecomment-675077675_

**Comment by MuntashirAkon** [comment]
@IzzySoft The latest versions won't build since I've moved 
`app/src/main/java/io/github/muntashirakon/AppManager/activities/ClassListingActivity.java` to `
`app/src/main/java/io/github/muntashirakon/AppManager/details/ClassListingActivity.java`. The **scanignore** part needs an update.

**Comment by IzzySoft** [comment]
Can you submit a corresponding MR to [fdroiddata](https://gitlab.com/fdroid/fdroiddata/) then? I'm neither dev nor packager, so I usually do not touch build stuff. If you cannot make an MR, open an issue there to request that a packager does the MR for you. If you can provide the diff (i.e. how the required changes should look like), that would speed up things. Thanks!

**Comment by MuntashirAkon** [comment]
> open an issue there to request that a packager does the MR for you.

Submitted an issue there: https://gitlab.com/fdroid/fdroiddata/-/issues/2144

**Comment by IzzySoft** [comment]
@MuntashirAkon with your app now in "F-Droid proper", shall it still be kept in my repo? We usually avoid "double listings" unless explicitly requested (eg for test builds).

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon with your app now in "F-Droid proper", shall it still be kept in my repo? We usually avoid "double listings" unless explicitly requested (eg for test builds).

It's not proper yet. I've added NDK dependencies and submodules of late which means I need to create an issue in the fdroiddata repo again (and only God knows how long its going to take to fix it). The toybox binary has to be compiled using a custom script (as a prebuild task on Gradle) which could be a problem as well. Also, many people still rely on your repo for updates (instead of F-Droid due to signature issues). That being said, how can I release test builds so that only you can grab it (and not F-Droid)?

**Comment by IzzySoft** [comment]
Good enough a reason for me. As for test builds only I should grab: simply use different tag names. For F-Droid, you currently use `v<versionName>` (keep it that way, please) – so F-Droid will stick to those as it's defined thus in the metadata. You could introduce a new prefix, eg `iod-<versionName>` ("iod" = "IzzyOnDroid") or `test-<versionName>` and let me know to adjust my metadata to stick to those.

**Comment by MuntashirAkon** [comment]
Thanks. I'll inform you when I'm ready.

**Comment by MuntashirAkon** [comment]
Ok, I'll go for `pre-<version_name>`. I think the next release will take some time (as I still have many things to do). Therefore, I'm going to publish pre-releases for now. I will probably publish a prerelease later today.

**Comment by IzzySoft** [comment]
Cool! I've already adjusted metadata right now to only go for `pre-<versionName>` tags. Previous releases will automatically be purged as soon as the pre-releases trickle in. If you wish a note added to the description (to make the users aware), let me know when the first pre is available.

**Comment by MuntashirAkon** [comment]
@IzzySoft I've pushed a pre-release about 3 days ago. Sorry for the delay as I was very busy of late.

**Comment by IzzySoft** [comment]
Thanks for the note! My updater ignored it as I had set it to `pre-<versionName>`. Adjusted that on my end to `pre-v<versionName>` and will trigger the updater manually now to verify.

Ah, good thing to have done. Also needed to adjust for `pre-Release`, which I previously ignored :rofl: Thanks, works now!
