### ISSUE TITLE
Not following Material You accent in pitch black mode

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#810]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
I don't know if this is intentional behaviour. App Manager doesn't seem to follow material you accent colors (for toggles and other things) when using the pitch black mode. Even in "Day" mode, if you turn on pitch black mode, the accent/background changes to some pre-default colors or something. see screenshot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to settings
2. Click on turn on pitch black mode
3. See the colors changed automatically

**Expected behavior**
Should follow the material you colors on supported devices.

**Screenshots**
![Screenshot_20220720-081408.png](https://user-images.githubusercontent.com/83750299/179884849-c2160094-c589-4483-8860-f9c99fc535e2.png)
![Screenshot_20220720-081404.png](https://user-images.githubusercontent.com/83750299/179884874-79145600-e3dd-4ead-b57d-3ef5d20b7355.png)

The first image is with Pitch black option turned on. The second with pitch black mode turned off.

**Device info**
 - Device: Note 10 Pro
 - OS Version: 12.1/L
 - App Manager Version: Debug #1906
 - Mode: root

**Comment by MuntashirAkon** [comment]
Hmm, I've probably skipped some docs regarding M3. Let me review the docs to see what I did wrong.

**Comment by MuntashirAkon** [comment]
Google is yet to release an Google API-less version of Sv2 (Android 12L) iso file for the emulator (Android 12 emulator version does not support Material You). So, I cannot test it for now.

**Comment by MuntashirAkon** [comment]
Check 47931efa1a865fb7174193df45d3181ca0c3a169. (Highly unlikely that the issue will be resolved but just in case.)

**Comment by MuntashirAkon** [comment]
Please check 0c19ed30d1c51426e65c4a2810a5202c0ab1a985. (I still can't check as I don't have access to an OS that support dynamic colours.)

**Comment by MuntashirAkon** [comment]
Hmm, there seems to be some sort of elevation present there.

> But because of material you elements it's not completely possible to have pitch black everywhere, that's completely understandable.

An option could be added to disable dynamic colouring, too.

**Comment by MuntashirAkon** [comment]
Fixed in 87f4a00d575313a3f62f4cbce60bf0b15e9eb113
