### ISSUE TITLE
User cannot select the desired split apks

### ISSUE THREAD

**Issue by arm64-v9a** [MuntashirAkon/AppManager#813]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specifi

**Describe the bug**
User cannot select the desired split apks

**To Reproduce**
Steps to reproduce the behaviour:
1. 

https://user-images.githubusercontent.com/58792941/180603266-85bbb8ec-26ec-4c6c-bc7d-2c8e254313d3.mp4

**Expected behavior**
Only the required split apks are automatically selected the first time, after that it is up to the user

**Screenshots**
no

**Crash logs**
no

**Device info**
 - Device: [Pixel4 XL]
 - OS Version: [Android Sv2]
 - App Manager Version: [v3.0.0-rc4]
 - Mode: root

**Comment by MuntashirAkon** [comment]
Since you've disabled displaying the taps, I don't think I've understood anything in the video. So, I'm not sure what you're trying to say. But, split selection cannot always be up to the user. For example, when the user selects a feature but forgets to select the associated splits (display, language, etc.), the app may simply crash. But, of course, there are rooms for improvement here.

**Comment by MuntashirAkon** [comment]
> I tried to uncheck split app for arm64-v8a, but AppManager also automatically unchecked base.apk

Hmm, this appears to be a bug.

**Comment by MuntashirAkon** [comment]
There are a few cases to be considered here:
1. Most users do not know which splits to select. If they mess it up, the app may never launch. This, I believe, is enough to justify the arguments that the auto-selection feature should exists.
2. Advance users, those who knows what they're doing, should also have a limited freedom to choose whatever splits they want to install but App Manager still have to guarantee that the app should launch as expected.

Hence, I think the solution to the issue should be as follows:
1. Choosing the base.apk or any feature split should still select all its dependencies, without which the app may never run.
2. After the user has selected a split for a class (e.g. armeabi-v7a), unselecting another split of the same class should not run any dependency check.
3. Any unsupported split (eg. x86 in an ARM device) should not be selectible.

**Comment by MuntashirAkon** [comment]
Fixed in 62fd558d786f2f2c19797920ae9e5027458e95b7
