### ISSUE TITLE
App manager doesn't show full list of apps

### ISSUE THREAD

**Issue by PstalDude** [MuntashirAkon/AppManager#814]
I'm using a third party build of CianogenMod 12.1 (android 5.1).
I've run into the problem that the App Manager doesn't show the full list of apps even if I'm using root permissions (works for displayed apps). At the same time, all these applications are present in the app manager profile settings. Also I noticed some thing. When I installed the application (firefox) with the app manager running, after installation, the application appeared in the list, and I was able to interact with it, but when the list was forced to refresh, the application disappeared.

**Comment by MuntashirAkon** [comment]
You've forgotten to include App Manager version.

**Comment by PstalDude** [comment]
> You've forgotten to include App Manager version.
Sorry, 2.6.5.1

**Comment by MuntashirAkon** [comment]
Try the last pre-release. The issue should be fixed there.

**Comment by PstalDude** [comment]
The problem was not solved in version 3.

**Comment by MuntashirAkon** [comment]
1. Download and install (or re-install if you already have a debug release installed) the debug release from here <https://github.com/MuntashirAkon/AppManager/actions/runs/2846093197>
2. Use `logcat` to take **full system logs** (with no filtering) during and after opening and loading the list of apps
3. Upload the logs here (or send to me by E-Mail).

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
