### ISSUE TITLE
Issues with imported profiles

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#815]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Issue 1 : Imported profiles are not listing apps i.e the apps which were in the list while exporting the profile are not showing after importing.

Issue 2 : Imported profiles can't be deleted. When we tap delete, they just switch to "disable" state.

**To Reproduce**
Export any profile first with some apps and then try to import it.

**Expected behavior**
Should show the app list after importing profile and should be able to be deleted by user. I was able to import the profile with stable version and it worked as expected.

**Device info**
 - Device: Redmi note 10 pro
 - OS Version: Android 12 , miui
 - App Manager Version: Latest debug
 - Mode: root

**Comment by MuntashirAkon** [comment]
Fixed in d3ff29b156f6d64d7e2bfddc6426902468b2ac3f
