### ISSUE TITLE
AM fails to restore multiple Extras+Rules backups

### ISSUE THREAD

**Issue by skrimix** [MuntashirAkon/AppManager#817]
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
When trying to restore multiple backups that contain only Extras and Rules, AM fails to restore them if "APK files" is checked in Backup Options in AM settings. "APK files" option is hidden in restore menu is this case so I can't uncheck it.

**To Reproduce**
1. Go to Settings - Backups/Restore - Backup Options and check "APK files"
2. Backup 2 or more apps with only "Rules" and "Extras" checked
3. Select multiple backed up apps and try to restore them
4. "Could not restore X apps" notification appears and details contain this error message for every restore: 

> io.github.muntashirakon.AppManager.backup.BackupException: APK restore is requested but backup doesn't contain any source files.

**Expected behavior**
AM restores the backups

**Device info**
 - Device: Poco X3 Pro
 - OS Version: Android 12L
 - App Manager Version: v3.0.0-rc04-DEBUG (407)
 - Mode: root

**Comment by MuntashirAkon** [comment]
fixed in f30f0bd05d187125beba33b24e375cdd0e5cdc78
