### ISSUE TITLE
Add "App Info" button to installation popup

### ISSUE THREAD

**Issue by Bluscream** [MuntashirAkon/AppManager#818]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A small button to the installation dialog so i can still have the convinience of not opening the big dialog everytime i open an apk but still have an easy way to reach it in case i need to check something

**Describe alternatives you've considered**
Not telling android to always use the installer, which is inconvinient

**Additional context**

**Comment by MuntashirAkon** [comment]
Can you elaborate a bit, perhaps with a picture? I don't think I have properly understood what you're trying to say.

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/182691171-eb979618-d39e-47de-97c8-e42d5e007627.png)

**Comment by MuntashirAkon** [comment]
Depends on #692

**Comment by MuntashirAkon** [comment]
Added via 0b3c698407b56c2fdd7ea5c0650557ef4d20c1a8
