### ISSUE TITLE
Restore fails for apps that use Android KeyStore

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#82]
Android [KeyStore](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/keystore/java/android/security/KeyStore.java;bpv=0;bpt=0) can be used by an app to store valuable keys and is actively used by apps like Signal (and it's derivatives) and andOTP.  Restoring the app data of these apps fails and may result in crash because of this. I'm still not sure if there is a way out of this other than notifying users that the app cannot be backed up as it uses Android KeyStore.

If there is any way to iterate over the keys stored for an app (we can always **run-as** the app using the `su - <uid>` command), the problem could be solved by backing up the unencrypted keys and restoring them again as needed.

**Comment by MuntashirAkon** [comment]
Related article: https://developer.android.com/training/articles/keystore.html

**Comment by MuntashirAkon** [comment]
Related issue #30

**Comment by Atrate** [comment]
Related OABX issue: https://github.com/machiav3lli/oandbackupx/issues/96

**Comment by MuntashirAkon** [comment]
@Atrate There is actually an easy solution, but that requires the owner to delete any screen lock mechanism which will remove encryption from the KeyStore files and they can be safely backed up. Same rules apply when restoring them. This process is stated in the Signal documentation: https://community.signalusers.org/t/wiki-howto-manual-backup-restore-if-full-backup-does-not-work/2462

**Comment by MuntashirAkon** [comment]
Until I implement a solution to this problem, backup  of apps having files at Android KeyStore will fail without warning.

**Comment by MuntashirAkon** [comment]
`su <uid>` method doesn't seem to be working at all, at least with Android's own `keystore_cli_v2` tool (however, it does work when a key is generated using this tool). So, there must be something that I'm missing.

- [x] We have access to the **masterkey** (when it exists)
- [x] We know the patterns used by Android KeyStore `<uid>_<KEY_TYPE>_<alias>`
- [x] We can also list keys using `su <uid> -c keystore_cli_v2 list`
- [ ] `su <uid> -c keystore_cli_v2 export --name=<KEY_TYPE>_<alias>` does not work for existing keys
- [x] KeyStore backup/restore works if the masterkey doesn't exist (ie. when no screen/device lock is set)
- [ ] There are some hidden files in `/data/misc/keystore/<user_id>/` identical to the key names but we don't know what they are and what they do
- [ ] There is no Java way to access the service responsible for generating and managing KeyStore, there's only native (c/c++) way

**Comment by MuntashirAkon** [comment]
Priority changed as it requires some study (I haven't even found any helpful Chinese blog articles on this topic).

**Comment by MuntashirAkon** [comment]
Should be fixed in b808ce50.

Notes:
1. This is not a well-tested feature. If most users are successfully able to restore KeyStore items, we can conclude this to be a solution and remove the KeyStore setting from the Back up/restore settings page.
2. While a user might be able to upgrade from Android 6+ devices to Android 9+ devices (or even from Android 5+ devices), downgrading is not possible.
