### ISSUE TITLE
Clearing logs is not working 

### ISSUE THREAD

**Issue by shifoc** [MuntashirAkon/AppManager#821]
- [x ] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
If I clear the logs, click on the back button and open the logs again the same logs are still there

**Device info**
 - Device: S22 ultra
 - OS Version: Android 12
 - App Manager Version: v3.0.0
 - Mode: no-root

**Additional context**

**Comment by MuntashirAkon** [comment]
Where?

**Comment by shifoc** [comment]
> Where?

![Screenshot_20220804-110237_App Manager.jpg](https://user-images.githubusercontent.com/32818143/182795978-69e70e89-dfd8-4c4a-b1ca-9320f6a3c7a1.jpg)

**Comment by MuntashirAkon** [comment]
Logs are captured from the system. When you clear logs using the “clear”, it only clears the display, not the actual logs from the system. So, when re-open the Log Viewer, it displays the same logs again as the system has reported them.
