### ISSUE TITLE
Not every Google tracker should be blocked (MLKit)

### ISSUE THREAD

**Issue by xslvrxslwt** [MuntashirAkon/AppManager#822]
https://gitlab.com/Nekogram/Nekogram/-/issues/77

![Screenshot_20220804-170708_App Manager~2](https://user-images.githubusercontent.com/105242066/182881843-6c47790b-57b9-4919-8f94-b8bc58ac3ac0.png)

This breaks the auto translation in Nekogram, i don't really think it's should be labeled as a  "tracker"

![Screenshot_20220804-170901_Nekogram~2](https://user-images.githubusercontent.com/105242066/182882347-509c5766-d765-4999-90a0-817e9c0390ed.png)
xd

**Comment by xslvrxslwt** [comment]
In case you think this is a tracker — maybe categorize the trackers with (may be) Critical/Safe to disable 👍

**Comment by MuntashirAkon** [comment]
Unfortunately, App Manager (and I) might be _dumb_ but honest. We both try our best to keep our work separate from our personal preferences. This is why we do not rank nor classify trackers as bad or less bad.

In this particular case, it took a real security expert to discover MLKit to be a tracker. See https://github.com/MuntashirAkon/AppManager/issues/289#issuecomment-943758190 learn more about MLKit and why it could've been a candidate of a rather bad kind of tracker if we had had used such a classification.

**Comment by vdbhb59** [comment]
Just do not trust Nekogram Developer please. Does not matter what he (or if she them) says. They are stealing numbers, so even if they sound right, I will not trust them at all.

**Comment by MuntashirAkon** [comment]
Nekogram is one of the most controversial Telegram clients from the beginning (apart from the state-linked clients from Iran and Russia). I wonder why people are still using it.

**Comment by vdbhb59** [comment]
Agreed. Just that today I found around 5 people have already lost money somehow after continued usage of the app. They still use it. Lols.
Anyways, too much #ot from my end.
