### ISSUE TITLE
Auto-update and search by package name in Running Apps

### ISSUE THREAD

**Issue by nisehime** [MuntashirAkon/AppManager#824]
- [x] I am using the latest version of App Manager
- [x] I have read the docs
- [x] I have searched the issues and haven't found anything relevant

Hello.

I'd like to ask 2 things for Running Apps tab.
1. Auto-update feature, preferably with the ability to select time interval.
2. Perform search for package name as well. Currently it only does it with normal names.

**Comment by MuntashirAkon** [comment]
> 2\. Perform search for package name as well. Currently it only does it with normal names.

Implemented in b5ac6914b62ea09f3759009aaa3208cfce83fefc

**Comment by MuntashirAkon** [comment]
> * Auto-update feature, preferably with the ability to select time interval.

Implemented via 4595100db97e64bd7d5888e06da7de0f1886dee5 (with 10 sec fixed interval)
