### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by gallegonovato** [MuntashirAkon/AppManager#825]
Good afternoon:

I wanted to ask a question if I may.

I happen to use your application (latest stable version), uploaded to Fdroid. And my question is if you will upload the new version App Manager v3.0.0 Stable to fdroid.

Thanks for your time and help.

**Comment by MuntashirAkon** [comment]
I have no control over the build systems of F-Droid repository. You've to ask the maintainers of F-Droid. But usually it takes them more than three days to publish a new release.

**Comment by MuntashirAkon** [comment]
It looks like F-Droid has already build v3.0.0. It should be available within 7 August.

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for all your work and effort. And for your help.

I would like to take this opportunity to thank you for updating the autostarts application.

Thank you very much

Best regards
