### ISSUE TITLE
Freez app like lucky patcher

### ISSUE THREAD

**Issue by bolbolfolfol** [MuntashirAkon/AppManager#828]
Hi
i want to request freezing app like lucky patcher (after the freez, the app is not visible in setting/apps)
(xposed edge can also do the same)

- I am using the latest (3.0) version of App Manager
- I have read the docs

and thank you for this wonderful app

**Comment by MuntashirAkon** [comment]
Duplicate of #749

**Comment by bolbolfolfol** [comment]
Hi or assalamo alaykom ^....^
i didn't find the option to freez and hide the app, when i freez an app i
still see it in settings/all app
and i also tested with the beta build, same problem
any idea ?
