### ISSUE TITLE
Type io.github.muntashirakon.AppManager.server.common.Actions is defined multiple times:

### ISSUE THREAD

**Issue by SArsalanK** [MuntashirAkon/AppManager#83]
Type io.github.muntashirakon.AppManager.server.common.Actions is defined multiple times: /Users/apple/Downloads/MyApplication/AppManagerServer/build/.transforms/f151c752b1dbdd450d9f261d013bf39d/classes/classes.dex, /Users/apple/Downloads/MyApplication/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes.dex

**Comment by MuntashirAkon** [comment]
Clean and rebuild the project again.

**Comment by MuntashirAkon** [comment]
Closed due to inactivity.
