### ISSUE TITLE
work profile apps restore issue

### ISSUE THREAD

**Issue by kohanla** [MuntashirAkon/AppManager#836]
- [X] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

App Manager 3.0.0 on Android 12:

It is possible to backup apps with App Manager (started by user 0) which belong to "user 10" (for example a work profile user). However it is not possible to restore them (actually the UI allows to restore, but "nothing happens" on restore).

If it is not possible to backup/restore work profile apps with user 0, then maybe App Manager shouldn't offer to backup those?

**Comment by MuntashirAkon** [comment]
> If it is not possible to backup/restore work profile apps with user 0, then maybe App Manager shouldn't offer to backup those?

There are certain use-cases which prompted me to keep the backup feature even though restoring has been disabled (#671). For example, one might want to clone an application from the work profile to the main profile or even to another device.
