### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kohanla** [MuntashirAkon/AppManager#838]
This is an amazing app with an unbelievable number of features. I am also impressed by the documentation. Hard to believe this is a "one developer project". 

Thanks again for developing this.

**Comment by MuntashirAkon** [comment]
Thanks. Yes, it is indeed surprising to not to see any developer turning up, which I too was expecting. But in any case, I love working on the project and hope to continue develop it as long as Android remains a developer friendly platform.
