### ISSUE TITLE
Work profile: Grant usage access

### ISSUE THREAD

**Issue by kohanla** [MuntashirAkon/AppManager#839]
- [X] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

When clicking on an app on the app overview page, App Manager 3.0.0 (installed in a work profile, user 10) requests "Grant Usage Access", but usage access was granted already. 

(There is no problem when starting App Manager from the main profile, user 0).

**Comment by kohanla** [comment]
![image](https://user-images.githubusercontent.com/787406/184096159-98d5b6ce-9927-49ad-b860-d07f3767d251.png)

![image](https://user-images.githubusercontent.com/787406/184096199-1f804da8-a738-4b45-b4af-056f0f705213.png)

App has usage access, but an error message is always appearing ...

![image](https://user-images.githubusercontent.com/787406/184096283-6153290d-ba5c-4ca4-b8cd-5cc2a99d0f16.png)

**Comment by MuntashirAkon** [comment]
This could most likely be an issue with the Island installation. Try another simple app that require usage access, for example, this one: https://f-droid.org/en/packages/godau.fynn.usagedirect/

**Comment by kohanla** [comment]
Yes, same happen with usagedirect as well.

I don't think it is an Island issue. Island just triggers the work profile creation. So it seems to be a "work profile" issue. 

But here is the workaround I found. When the popup shows up, I switch to the "personal" tab, revoke the usage access there, then go back to the work tab, and turn on "usage access". After that the problem disappears.
