### ISSUE TITLE
Backup fails in work profile

### ISSUE THREAD

**Issue by kohanla** [MuntashirAkon/AppManager#840]
- [X] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

Backup fails in work profile. First line of the log indicates a permission issue?

java.lang.SecurityException: getPackagesForUid: UID requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS or android.permission.INTERACT_ACROSS_PROFILES to access user

**Comment by MuntashirAkon** [comment]
Did it detect root correctly? Find _inferred mode_ at Settings > Mode of operations

**Comment by kohanla** [comment]
Inferred mode is "no root". But App Manager requested and was granted root by Magisk. Root works correctly in other apps.

**Comment by MuntashirAkon** [comment]
> Inferred mode is "no root". But App Manager requested and was granted root by Magisk. Root works correctly in other apps.

App Manager works quite differently from the other apps that uses root. It's environment is similar to what Shizuku (and a handful of other apps) does. Generally, it is not expected from anybody to use root in the work profile, so not much testing has been done to ensure that the privileged features are working as expected in the work profile. But since you've raised the issue, I will take a look at it.

**Comment by kohanla** [comment]
If it were possible to restore work profile apps from the main profile (user 0), then it probably wouldn't be necessary (see also other issue). But to be able to backup and restore apps in the work profile you have to install App manager also in the work profile. So it is appreciated that you look at it :-)

**Comment by MuntashirAkon** [comment]
> If it were possible to restore work profile apps from the main profile (user 0), then it probably wouldn't be necessary (see also other issue).

Restoring work profile backups from the main profile was supported in the previous versions but is disabled in the latest stable due to #671. It might be supported in a future release if I can manage to fix the issue.

**Comment by kohanla** [comment]
Restoring a profile "cross profile" is probably difficult. Solving this issue is hopefully much easier.

**Comment by MuntashirAkon** [comment]
In that case, I'm closing this in favour of the earlier issue #834 since both are the results of the same problem.
