### ISSUE TITLE
CPU usage background

### ISSUE THREAD

**Issue by kohanla** [MuntashirAkon/AppManager#844]
I installed AppManaget 3.0.0 and it works well.

When I check the list of running processes, I can see that AppManager is running in the background and using 0.6% CPU. I could force stop the app of course, but my question is:

Is AppManager doing actually anything useful in the background?

**Comment by MuntashirAkon** [comment]
> Is AppManager doing actually anything useful in the background?

If App Manager is kept in _Recents_ (and App Manager's main window is running), it looks for changes to the applications via broadcast receivers. So, if you use a lot of applications, all the state changes will be broadcasted to App Manager and it will try to update its database to reflect those changes. You can avoid this by simply removing it from _Recents_.
