### ISSUE TITLE
After uninstallation, it cannot be installed again

### ISSUE THREAD

**Issue by netforfreedom** [MuntashirAkon/AppManager#845]
- [ ] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: moto g pro
 - OS Version: Android 12
 - App Manager Version: AppManager_v3.0.0-alpha02
 - Mode: root

**Additional context**
Hello, thank you for your app. It's very useful,
My phone runs Android 12,If the data is retained during uninstallation, Appmanager cannot be reinstalled.
`C:\Users\Downloads>adb install AppManager_v3.0.0.apk
Performing Streamed Install
adb: failed to install AppManager_v3.0.0.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.github.muntashirakon.AppManager signatures do not match previously installed version; ignoring!]`

**Comment by MuntashirAkon** [comment]
See answer here: https://github.com/MuntashirAkon/AppManager/discussions/819#discussioncomment-3321363
