### ISSUE TITLE
App Manager shows improper behavior on Android SDK 33

### ISSUE THREAD

**Issue by NO111ONE** [MuntashirAkon/AppManager#847]
- [YES] I know what my device, OS and App Manager versions are
- [YES] I know how to take logs
- [LIKELY NOT] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
The app list is: blank (v2.6)/shows only App Manager(v3). No permissions for app list are requested. 
Doing OTA from Android 12 SDK 31 to SDK 33 will make the app crash shortly after launch. The crash is detected by ThirdKit (testing-logging system app) and a crash log is given.

**To Reproduce**
Steps to reproduce the behaviour:
Do OTA from ColorOS C.66 to F.02. 

**Expected behavior**
App list shows up, no errors about backup volumes.

**Screenshots**
![Screenshot_2022-08-15-17-44-13-09_718a221d6c53e9d44e23988b91117061](https://user-images.githubusercontent.com/63470411/184659558-9dca8672-5da4-4c3d-9105-a267ed78bc9d.jpg)
![Screenshot_2022-08-15-17-53-45-24_e6871cd13ad370b30dca80a8c4050ac0](https://user-images.githubusercontent.com/63470411/184659586-f0654613-98f3-492c-8c87-ca5109788ad5.jpg)

**Crash logs**
None available

**Device info**
 - Device: OnePlus 9 LE2110
 - OS Version: Android 13 alpha ColorOS F.02_log
 - App Manager Version: v2.6.5.1 and v3 stable
 - Mode: no-root

**Additional context**
Clearing app list DB does not fix this issue. Storage Framework says that /storage/emulated/0 is not usable as it is not private enough.

**Comment by MuntashirAkon** [comment]
App Manager is tightly coupled with Android framework. As a result, unsupported SDKs will cause random behaviour. v2.6.5.1 and earlier have no support for Android 13 and will crash at startup due to the recent API changes in the Android framework (#738). v3.0.0 has limited support for Android 13 (so far only tested on the public beta by the users).

**Comment by kohanla** [comment]
Regarding the first screenshot. See also #837

**Comment by NO111ONE** [comment]
This issue will be closed as the device is no longer using Android 13, and further tests will not be done.
