### ISSUE TITLE
Add an Option to Convert User App To System App

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [MuntashirAkon/AppManager#85]
Loved your project. Carry on !
Add root installer or turning any user app to system app. It will be a great addition !

**Comment by MuntashirAkon** [comment]
> Add root installer

As of v2.5.13, if you have enabled root, apps are installed using root.

**Comment by BL4CKH47H4CK3R** [comment]
I was using 2.5.12

**Comment by BL4CKH47H4CK3R** [comment]
> > Add root installer
> 
> As of v2.5.13, if you have enabled root, apps will be installed using root.

Not working I tried !

**Comment by MuntashirAkon** [comment]
I think I need to think this through. The typical way of converting an app to system app compromises boot verification and therefore SafetyNet. I think a better option is to convert it via Magisk in which case the system app will be installed systemless-ly.

@Atrate what is your opinion on this?

**Comment by Atrate** [comment]
I am 100% for a systemless approach, these days there's virtually no reason to write to `/system` directly.

Reference implementation: https://github.com/Magisk-Modules-Repo/terminal_systemizer

If Magisk is unavalable (e.g. someone uses SuperSU (why tho)) an option to write directly to `/system` could be presented, but with a hefty disclaimer about the possible consequences.

**Comment by MuntashirAkon** [comment]
> I am 100% for a systemless approach, these days there's virtually no reason to write to `/system` directly.

I agree. For now, I'll only stick to the systemless approach. The second option will only be considered if enough people show their interests in it.

**Comment by MuntashirAkon** [comment]
> Reference implementation: https://github.com/Magisk-Modules-Repo/terminal_systemizer

Well, that requires some major works, I think. I have to think about the future as well because it could be useful for restoring backups of the system apps (which are not installed anymore).

**Comment by BL4CKH47H4CK3R** [comment]
I know Terminal Systemizer very well. I can also do that on my own. But terminal systemizer is not that I need. Besides, it has so many problems like reverting. Your app your wish. I am just a well wisher who loves your work

Greetings !
BL4CKH47H4CK3R

**Comment by MuntashirAkon** [comment]
> I know Terminal Systemizer very well. I can also do that on my own. But terminal systemizer is not what I need. Besides, it has so many problems like reverting & there are always something called app permissions.

Well, I need some examples to start my work. I can always fix bugs later. If I were to start from scratch, it would take about a year to do the work that I've done in the last three months.

**Comment by MuntashirAkon** [comment]
It seems the systemless approach is useful in many respects (for apps only), just not only to escalate the privileges of an app.
1. **Uninstall/debloat.** Replacing the directory of the responsible app (with removing updates first) would completely remove the app
2. **Replace** The system app can be replaced with an apk of different signature (e.g. webview) in two ways:
  a. Install the app as a system app by replacing the directory at `/system/app` or wherever the file is located at the system partition and then install the app again after a reboot (this is probably due to the oat file)
  b. Replace the directory of the system app so that the app can be installed as a user app

**Comment by BL4CKH47H4CK3R** [comment]
>     1. **Uninstall/debloat.** Replacing the directory of the responsible app (with removing updates first) would completely remove the app
I see actually it doesn't delete the complete path but the items of it

**Comment by MuntashirAkon** [comment]
> I see actually it doesn't delete the complete path but the items of it

It just mounts an empty directory on top of the existing directory as a result the directory appears to be empty while it's not. Therefore, the app will be removed systemless-ly without touching the system partition. However, Magisk does have problems with OverlayFS (see https://github.com/topjohnwu/Magisk/issues/2359).

**Comment by MuntashirAkon** [comment]
Closed in favour of #150.
