### ISSUE TITLE
Invalid application name.

### ISSUE THREAD

**Issue by sanek184** [MuntashirAkon/AppManager#850]
If you click on any application. And click cancel, not install. Then clicking on any other apk will have an incorrect display of the application name.
If you go to the AppManager application to update the list of applications, the bug will disappear until the next same action
The bug manifests itself with any APK
Device:Redmi 7 EU11.0.11A9

> ![photo_2022-08-20_19-01-55](https://user-images.githubusercontent.com/10418650/185756109-10ba0faa-b3aa-43cd-a443-e09151773811.jpg)

**Comment by MuntashirAkon** [comment]
You didn't mention Android version and App Manager version.

In some cases, however, App Manager can display wrong information because of the caching issues with the Android package manager (I've seen this kind of errors before).

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
