### ISSUE TITLE
Expand documentation regarding uninstallation of system apps?

### ISSUE THREAD

**Issue by genpfault** [MuntashirAkon/AppManager#851]
- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

**Is your feature request related to a problem? Please describe.**
I'm trying to wrap my head around these two statements and how they relate to what App Manager is doing when it uninstalls system apps:

> ... [For the uninstalled system apps, it displays a dialog prompt which can be used to reinstall the app.](https://muntashirakon.github.io/AppManager/en/#toc:sec:main-page) ...

This seems to indicate that App Manager might be keeping the APK for system apps around somewhere when it deletes them?  Otherwise how would it be able to reinstall the app?

> [...these methods cannot remove the system apps completely as they are located in the system partition which is a read-only partition. If you have root, you can remount this partition to manually purge these apps but this will break Over the Air (OTA) updates since data in the system partition has been modified.](https://muntashirakon.github.io/AppManager/en/#toc:subsec:faq:what-are-bloatware) ...

...and this seems to indicate that App Manager is re-mounting the system partition as read/write to uninstall system apps?  Which as the text points out would break OTA updates, which doesn't sound good and would drive me away from trying to use App Manager to remove system apps.

However, [a comment](https://github.com/MuntashirAkon/AppManager/issues/753#issuecomment-1129476671) on the issue tracker indicates that App manager is *not* remounting the system partition as read/write, so it's not clear to me how it's uninstalling system apps.

**Describe the solution you'd like**
Please add a section to the documentation that explains how App Manager is uninstalling/reinstalling system apps without remounting the system partition as read/write.

**Comment by MuntashirAkon** [comment]
> this seems to indicate that App Manager is re-mounting the system partition as read/write to uninstall system apps?

Here's the complete sentence that you've quoted there:

> AM can uninstall system apps with root or ADB (the latter with certain limitations, of course), but these methods cannot remove the system apps completely as they are located in the system partition which is a read-only partition.

I think it's quite clear from the above line that App Manager cannot not _delete_ the system APK files, it can only _uninstall_ them. In newer Android operating systems, mounting system partition as R/W is not even possible.

> it's not clear to me how it's uninstalling system apps.

It uninstalls the system apps using the Android-provided uninstaller just as it uninstalls any other apps. But uninstalling a system app does not delete the APK file itself as it's still available in the system or the vendor partition. This is why App Manager can offer the reinstallation of such an app (or you can use command option such as `pm install-existing package-name`). But a potential side-effect is that the apps may be installed again after an OTA update (usually when it is a big update). (To mitigate this, however, it is possible to delete the APK systemless-ly using Magisk as proposed in #150.)

**Comment by genpfault** [comment]
That clears it up, thank you!
