### ISSUE TITLE
Trackers not shown anymore (v3.0.1)

### ISSUE THREAD

**Issue by kohanla** [MuntashirAkon/AppManager#860]
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

I (uninstalled and) updated to 3.0.1 (from fdroid to github release).

Then I activated "sort by trackers", but surprisingly could not find some apps which are known to have trackers.

For example, Google News does not have a green/orange "tracker badge" anymore. But when checking via 1-click ops, I can see that Google News has 8 trackers.

This seems to be a regression bug.

**Comment by MuntashirAkon** [comment]
Working perfectly on my side, make sure you're <ins>not</ins> visiting the App Info tab for an app in the work profile from your main profile (which is a known issue and will not be fixed anytime soon). Note that nothing related to trackers have been altered between v3.0.0 and v3.0.1 (the latter only contains a few unrelated fixes). So if it is present in v3.0.1, it should also be present in v3.0.0.
