### ISSUE TITLE
Many of you have been written to me in the past regarding the freezing of an app in Android, and it also appears that the opinions regarding this keyword differ widely. So, let me explain to you what freezing means and why the opinions differ and what steps App Manager might take to clear this up.

### ISSUE THREAD

**Issue by yluap** [MuntashirAkon/AppManager#863]
Many of you have been written to me in the past regarding the freezing of an app in Android, and it also appears that the opinions regarding this keyword differ widely. So, let me explain to you what freezing means and why the opinions differ and what steps App Manager might take to clear this up.

**Overview**

Android framework DOES NOT use any terminology that goes by the name freezing. This particular terminology, I believe, is popularised by Titanium Backup as well as Link2SD in the early days. Later many other developers, as the term is well known among the users, had also adopted the terminology. However, since Android is a sufficiently dynamic operating system, new features are always introduced, and freezing, it seems, has also evolved.

**Understanding the operations on an Android app**

Android supports several operations related to freezing. If we are to sort them in the order of their strength, they could be listed as follows: force-stop, suspend (Android N and onwards), disable, hide (previously called block), uninstall.

1. **Force-stop.** This simply stops an app from running either in the foreground or in the background for a time being. The app can still be activated anytime by the user, another app, alarm manager (which manages execution of a service at a certain point in time) or a system broadcast receiver. (For developers, it issues PACKAGE_CHANGED intent.)
2. **Suspend.** This is similar to disable (see below) but it’s intended for the device admin apps. In this case, the app might still be visible in your launcher, but it might be grayed out, and when you would try to launch it, it would issue an warning that the app may not be available at the moment as it is suspended by an app. But it entirely depends on how your launcher handles it. This is lesser than disable because it does not actually disable the app or its components. (For developers, it issues PACKAGES_SUSPENDED or PACKAGES_UNSUSPENDED intent.)
3. **Disable.** This disables an app along with all its components. Since the app will not have any activity that can be launched, it will not be present in the list of apps in the launcher. (For developers, it issues PACKAGE_CHANGED intent.)
4. **Hide.** This used to be known as block until the AOSP team renamed it to hide. This is similar to suspend except that the app behaves as if it has been uninstalled from the system and remains hidden from the launcher. (For developers, it issues PACKAGE_REMOVED or PACKAGE_ADDED intent.)
5. **Uninstall.** This operation completely or partially uninstalls the app from the system depending on whether you choose to retain its data. Note that data also include the signature of the app. So, if you chose to retain its data during the uninstallation but later wanted to install the same app with a different signature, the installation would fail. (For developers, it issues PACKAGE_REMOVED or PACKAGE_ADDED intent.)

**App Manager's take on freezing**

The term freeze denotes one of 2–4 operations/actions described above (i.e. suspend, disable or hide), depending on the app that the user is familiar with. In App Manager, instead of displaying all three actions separately in the app info tab (just think how much space would it take for, more or less, the same feature) or elsewhere, a single action, namely freeze, would be added, replacing the current disable action. In settings, an option would be added to configure how this action would behave. For compatibility reasons, the default behaviour would be disable.

_Originally posted by @MuntashirAkon in https://github.com/MuntashirAkon/AppManager/discussions/835_

**Comment by MuntashirAkon** [comment]
Spam??
