### ISSUE TITLE
Additional options for filtering

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#866]
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**

I would like to see the option to filter apps on additional criteria (particularly the presence of KeyStore or SSAID, but no doubt other possibilities exist).

**Describe the solution you'd like**

Just those fields added to the possible filters (doesn't seem too difficult :) ).

**Describe alternatives you've considered**

At the moment, I actually keep track of those manually (in a file, which I keep updated).

**Comment by MuntashirAkon** [comment]
> doesn't seem too difficult :)

Not difficult in terms of implementation, but implementation is just a tip of an iceberg. You need extensive planning so that in the future no compatibility issue may arise, and this isn't an easy thing to do because nobody can foresee the future.
