### ISSUE TITLE
Backup does not finish correctly for apps in work profile

### ISSUE THREAD

**Issue by fekir** [MuntashirAkon/AppManager#877]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

With Appmanager it is possible to manage also application installed in the work profile.

A work profile can be setup easily with insular (https://secure-system.gitlab.io/Insular/)

It is possible, without errors, to disable, uninstall, force-stop, clear data, access to thedatabase, etc.etc.

This "proves" that Appmanager has access to the data of the application.

When doing a backup, AppManager notifies that the backup has been created correctly, but there is no backup in the configured folder, and AppManager offers no possibility to restore it

### To Reproduce

- 1. Install and configure insular (also avaiable on f-droid: https://f-droid.org/en/packages/com.oasisfeng.island.fdroid/)
- 2. Install one application in insular
- 3. Open AppManager, and search for the application installed in the work profile
- 4. Do a backup
- 5. Try to restore a backup (not possible as not backup has been ceated)

### Expected behavior

That AppManager creates a backup that can be restored.

### Logs

In the log dialog I could not find anything related to "backup"

### Device info

- Device: (observed at least on two different devices)
- OS Version: Android 12
- App Manager Version: 3.0.1
- Mode: Root

**Comment by MuntashirAkon** [comment]
Should be fixed in 4b23278761f73689d618b5856b4cb25b03285ad0
