### ISSUE TITLE
System config not showing full names

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#878]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

System config is not showing full text of some list elements. Text is kinda forced to be single line there with no ability to scroll to see full line. Please see screenshot.

### To Reproduce

1. Go to system config.
2. Open "feature" from down menu.
3. Scroll the list to see if there is any element which isn't showing full text in single line.

### Expected behavior

It should show full text.

### Screenshots

![Screenshot_20220925-181712](https://user-images.githubusercontent.com/83750299/192144628-a7f5c43d-c36d-49a0-9747-3d6bcc20713f.png)

### Device info

- Device:
- OS Version: 13
- App Manager Version: AM Debug v3.1.0-alpha01 Run#2021
- Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed in 6cadfe499f8315a2a4a8dc9f57eb1d9dfbf4e28f
