### ISSUE TITLE
Allow installing packages for other users using `pm install-existing`

### ISSUE THREAD

**Issue by binarynoise** [MuntashirAkon/AppManager#882]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Additionally to the dialogue upon install, I'd like to have some option to install an existing app to a different user, so I can skip finding and downloading the app there again.
Examples would be AppManager itself, Magisk, file managers and commonly used apps.

Optionally add an option to install apps from other users.

### Describe the solution you'd like

I'd like to easily install apps across user boundaries.

### Describe alternatives you've considered

- using `pm install-existing` manually

**Comment by gnuhead-chieb** [comment]
AM alreadw have such feature.
AM settings-->Installer-->Show users in installer

**Comment by gnuhead-chieb** [comment]
1.Enable Show users in installer at AM settings
2.Go to app you want to clone in other user
3.Tap share button at righter-up
4.Open AM installer

**Comment by binarynoise** [comment]
Selecting all user doesn't install it for secondary user, only selecting the secondary user itself actually installs it for him. Is that a bug?

Apart from that, it works but I wouldn't have come up with that myself.

**Comment by gnuhead-chieb** [comment]
> Selecting all user doesn't install it for secondary user, only selecting the secondary user itself actually installs it for him. Is that a bug?

yeah,it seems

**Comment by binarynoise** [comment]
I filed a separate bug for that: https://github.com/MuntashirAkon/AppManager/issues/883

Still, a direct option to cross-install apps would be great. It would enhance the already existing multiuser management

**Comment by MuntashirAkon** [comment]
I think the only suitable place for this feature is in the App Info tab. In the three dots menu, an additional option could be added which would let the user install the app for other user profiles.

**Comment by MuntashirAkon** [comment]
There is another use-case for this. It appears that in Samsung's One UI, some uninstalled system apps can only be installed using this method.

**Comment by MuntashirAkon** [comment]
Added via e65d65a4059912c60b179fb0986d101e0d5237dd and 546f608871e2a3413fdba32b4882d578f9a4bc88
