### ISSUE TITLE
Selecting all user doesn't install and app for secondary user

### ISSUE THREAD

**Issue by binarynoise** [MuntashirAkon/AppManager#883]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When reinstalling an app for all users and a secondary user didn't have the app installed, the secondary user won't have the app installed afterwards.

### To Reproduce

1. Have a device with multiple profiles
2. Enable show users in the installer settings (AM settings --> Installer-->Show users in installer)
3. Have an app that is installed only on the main profile
4. Open the app's details in AM, share the app and select install with AM
5. Select all users
6. Let it install
7. Switch users ⇾ App still isn't there or relaunch AM and don't be presented the chose user dialogue on opening app details

### Expected behavior

When installing for all users, the app is subsequently available to all users, regardless of whether it was previously installed for them or not.

### Device info

- Device: Samsung Galaxy S4
- OS Version: LineageOS 18.1 (Android 11)
- App Manager Version: 3.0.2
- Mode: Root

**Comment by MuntashirAkon** [comment]
App Manager currently uses the OS-default options for installing an app. When you select "All users" in the installer page, it sets a flag requesting the Android server to install the app, which appears to be ignored if the app is already installed in the system. This could, of course, be fixed by adding support for #882.

**Comment by binarynoise** [comment]
Which flags exactly? I could try to reproduce and raise an issue at my rom's maintainers

**Comment by MuntashirAkon** [comment]
`PackageManager#INSTALL_ALL_USERS` flag. Note that this behaviour might be deliberately set by the AOSP. After all, this is a private flag and third-party apps are not _supposed_ to use these flags.

**Comment by MuntashirAkon** [comment]
Fixed in c096c87c9c9fd09d24e576fdf8c541cd89e2475d
