### ISSUE TITLE
Unable to disable services for System apps despite having root

### ISSUE THREAD

**Issue by chaoscreater** [MuntashirAkon/AppManager#887]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I'm using App Manager v3.0.2 running on Android 11, rooted.

When I try to disable services for a System app, such as Google Play Services, it'll show Rules not applied. This works fine for User apps. I can also set AppOps on System Apps, but just not disable services, receivers, etc. I'm 100% rooted and App Manager has root permissions. I even set the mode to root explicitly in the settings. Still unable to disable services. At the moment, I'm using another app called Service Disabler (also requires root) to do this.

### Expected behavior

Be able to disable services for System apps.

### Device info

- Device: Redmi Note 9T
- OS Version: Android 11
- App Manager Version: 3.0.2
- Mode: Root

**Comment by MuntashirAkon** [comment]
Even after applying rules from 3-dots-menu > apply rules as per [docs](https://muntashirakon.github.io/AppManager/en/#additional-features-for-rooted-phones)?

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
