### ISSUE TITLE
[REGRESSION] links to stores

### ISSUE THREAD

**Issue by ildar** [MuntashirAkon/AppManager#89]
1st versions allowed to open the app page in F-Droid and Play store.
Now it's replaced with Aurora only. This is disappointing. Please bring both back.
FTR: I use mainly off. FDroid client and Yalp for browsing G00gle.

**Comment by MuntashirAkon** [comment]
> 1st versions allowed to open the app page in F-Droid and Play store.

Google Play Store was never supported by me (nor any non-free software). F-Droid will be displayed only if Aurora Droid is not installed. See the documentation: https://muntashirakon.github.io/AppManager/guide/app-details-page.html#horizontal-action-panel
