### ISSUE TITLE
Applying rules does not work

### ISSUE THREAD

**Issue by Bladius2022** [MuntashirAkon/AppManager#893]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Applying rules does not work, although root privileges have been granted

### To Reproduce

1.Go to any app from list
2. Click any tab where you can use the crossed circle icon.
3. Get error The rules have not been implemented

### Device info

- Device: Redmi Note 10 
- OS Version: Android 12, MIUI 13 v13.0.10.0
- App Manager Version: 3.1.0 Alpha 01
- Mode: Root Magisk

**Comment by MuntashirAkon** [comment]
Rules are only applied when you explicitly apply them from the 3-dots menu. See docs: https://muntashirakon.github.io/AppManager/en/#additional-features-for-rooted-phones
