### ISSUE TITLE
AppManager crash 

### ISSUE THREAD

**Issue by Bladius2022** [MuntashirAkon/AppManager#894]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AppManager crashes unexpectedly during startup.

### Device info

- Device: Redmi Note 10 
- OS Version: Android 12 MIUI13 13.0.10.0
- App Manager Version: 3.1.0 Alpha 01
- Mode: Root Magisk

**Comment by MuntashirAkon** [comment]
No crashlogs
