### ISSUE TITLE
Typo in German localisation

### ISSUE THREAD

**Issue by ksaerdna** [MuntashirAkon/AppManager#895]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

„Von Links nach Rechts” must be „Von links nach rechts”.

(Usage of wrong upper case characters is kind of an endemic disease in Germany)

### To Reproduce

Open vertical three dot menu.
Select "Einstellungen".
See near: "Ausrichtung des Layouts"

### Expected behavior

„Von links nach rechts”

### Device info

N/A (device independent)

**Comment by MuntashirAkon** [comment]
You can also easily fix them yourself in Weblate: https://hosted.weblate.org/projects/app-manager/

**Comment by arjundevasi** [comment]
If it is not fixed yet, can i help?
also if I'm not wrong the fix is required on line 938 in strings.xml in /values-de

**Comment by ksaerdna** [comment]
I made an attempt to correct the text via Weblate, as suggested. However, I am not sure, if this will work.
 

Gesendet: Mittwoch, 19. Oktober 2022 um 10:32 Uhr
Von: "Arjun Devasi" ***@***.***>
An: "MuntashirAkon/AppManager" ***@***.***>
Cc: "ksaerdna" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [MuntashirAkon/AppManager] Typo in German localisation (Issue #895)


 

If it is not fixed yet, can i help?
also if I'm not wrong the fix is required on line 938 in strings.xml in /values-de

**Comment by arjundevasi** [comment]
okay

**Comment by MuntashirAkon** [comment]
> I made an attempt to correct the text via Weblate, as suggested. However, I am not sure, if this will work.

It appears that the mentioned string has already been changed in Weblate.
