### ISSUE TITLE
Don't disable mlkit service

### ISSUE THREAD

**Issue by WhiCCX0** [MuntashirAkon/AppManager#899]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App manager will disable these when block trackers
Service:
com.google.mlkit.common.internal.MlKitComponentDiscoveryService 
and provider:
com.google.mlkit.common.internal.MlKitInitProvider 

which will cause some app to force close or some function not to work 

### To Reproduce

1.1-click ops 
2.Block/unblock trackers
3.Block

### Expected behavior

Whitelist these two components
com.google.mlkit.common.internal.MlKitInitProvider 
com.google.mlkit.common.internal.MlKitComponentDiscoveryService 

### Device info

- Device: mi11x
- OS Version:12.1
- App Manager Version: latest 
- Mode: Root/ADB/NonRoot
Root

### Additional context

https://t.me/NekoUpdates/319

**Comment by shuvashish76** [comment]
Duplicate #822
