### ISSUE TITLE
Show Actions in the Receivers tab

### ISSUE THREAD

**Issue by Nill53** [MuntashirAkon/AppManager#901]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Show a list of Actions for each Receiver in the receivers tab. Such as
android.intent.action.BOOT_COMPLETED
android.net.conn.CONNECTIVITY_CHANGE
etc.

**Comment by MuntashirAkon** [comment]
Duplicate of #309
