### ISSUE TITLE
app startup time is huge

### ISSUE THREAD

**Issue by ildar** [MuntashirAkon/AppManager#906]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

i.e. launching the App Manager takes up to ~10 seconds. This is VERY long.
Comparing to other apps showing the all-apps-list.
I suggest to push some work to background showing the list ASAP.

### Device info

- Device: 8-core Mediatek, 4 GB RAM
- OS Version: 12
- App Manager Version: latest
- Mode: Root

**Comment by MuntashirAkon** [comment]
Include App Manager version name. App Manager always have two latest versions at any given time. It's also useful for archiving purpose.

**Comment by Kimphunh** [comment]
The release ver is loading very slow,up to 20-30s
and the apps-list takes a long time to display, and sometimes it doesn't show up even though it's loaded for a long time
But the debug ver is much faster just take to 3-5s,the apps-list is faster and much more stable,

**Comment by Kimphunh** [comment]
and adb connection is also very unstable, it doesn't show adb connection screen
Even though I have enabled adb mode
This problem has appeared since the first days I used it. Specifically 1 year ago
Once again the debug ver did it very well

**Comment by Kimphunh** [comment]
> Include App Manager version name. App Manager always have two latest versions at any given time. It's also useful for archiving purpose.

The release ver is loading very slow,up to 20-30s
and the apps-list takes a long time to display, and sometimes it doesn't show up even though it's loaded for a long time
But the debug ver is much faster just take to 3-5s,the apps-list is faster and much more stable

**Comment by Kimphunh** [comment]
> Include App Manager version name. App Manager always have two latest versions at any given time. It's also useful for archiving purpose.

and adb connection is also very unstable, it doesn't show adb connection screen
Even though I have enabled adb mode
This problem has appeared since the first days I used it. Specifically 1 year ago
Once again the debug ver did it very well

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.

**Comment by Mertica** [comment]
> Closed due to lack of response. Feel free to open it again if you're still facing the issue.

Hello, I have this same issue!

Earlier today it was working just fine, but all of a sudden, at some point, when I tried to open the app, the loading time was 30 to 60 seconds long...

When I try to change mode (root, wireless debug, etc.) it also takes 30 to 60 seconds to give me the pair and connect window for wireless debugging...

The only thing I remember could've done anything was creating a shortcut to freeze a particular app, but nothing was out of the ordinary then...

I only noticed this once I tried clicking it, and got a long or infinite "Initializing..." loading pop-up

I tried force-stopping and clearing cache multiple times, but nothing changed...

I have not tried uninstalling the app yet as I don't want to lose my configurations and customizations...

**Comment by rickdtc** [comment]
Alright, I am encountering this problems. So here we go.

I restart my phone, no process running.
First 3-2 times I open, it's fine, on the 4th time, holy shiit, 3-4 minutes then i see a prompt to connect to wireless adb, so here are the logs on the initializing page, and some seconds after it started up if it's not a problem.

[07-10_23-57-46.txt](https://github.com/MuntashirAkon/AppManager/files/12838801/07-10_23-57-46.txt)
