### ISSUE TITLE
can't unfreeze app

### ISSUE THREAD

**Issue by Kimphunh** [MuntashirAkon/AppManager#907]
although it can freeze the app,It can't unfreeze the app again.and i use "hail" to unfreeze this app
So I changed to suspend method,it still can freeze the app,but never unfreeze that app again
can you give me adb command to unsuspend pls
## **More info**
Android 11
Mode:Wireless Adb
AM Debug v3.1.0-alpha01 Run#2070

**Comment by MuntashirAkon** [comment]
> Lastest version

Which latest version?

**Comment by Kimphunh** [comment]
> > Phiên bản mới nhất
> 
> Phiên bản mới nhất?

AM Debug v3.1.0-alpha01 Run#2070

**Comment by MuntashirAkon** [comment]
Fixed in 8f29b2e0969dce567ea5b10c134bfedb5f3c4824
