### ISSUE TITLE
redundant entry

### ISSUE THREAD

**Issue by zhaoshuai23** [MuntashirAkon/AppManager#909]
![Screenshot_20221029-215757_App Manager](https://user-images.githubusercontent.com/31366586/198835642-ec994262-6064-481d-b005-ed3f78d02e1f.jpg)
After I updated this system application, there was an entry that could not be opened and could not be removed. Clicking it showed that it was not installed.

**Comment by MuntashirAkon** [comment]
We have a future plan for this. Hopefully, this will be released in v3.2.0.

**Comment by MuntashirAkon** [comment]
After 4c30b30410d3107c44523ca07dad5f951f38a5b6, there shouldn't  be any redundant entries after the second pass. (Initially, there might still be some redundant entries due to caching.)
