### ISSUE TITLE
Add sign apk option on install confirm dialog

### ISSUE THREAD

**Issue by fairyex** [MuntashirAkon/AppManager#912]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Add sign apk option on install confirm dialog, Instead of a fixed option in app settings,  the users could decide what apk should sign before installation.

**Comment by MuntashirAkon** [comment]
Duplicate of #692
