### ISSUE TITLE
less apps visible than in classyshark3xodus

### ISSUE THREAD

**Issue by pabloski80** [MuntashirAkon/AppManager#913]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

On samsung galaxy s4, android version 5.0.1, the list of apps is roughly only 30% of one in classyshark3xodus

### To Reproduce

Just enter app, with maximum list selected in view options.

### Expected behavior

All apps at least available in classyshark3xodus should be viewable/available in app manager

### Device info

- Device: samsung galaxy s4
- OS Version: androud 5.0.1
- App Manager Version: 3.0.3
- Mode: Root/ADB/NonRoot NonRoot

**Comment by MuntashirAkon** [comment]
This appears to be related to #298. But I need logs figure out the actual issue.

**Comment by pabloski80** [comment]
Which logs exactly would you need? I will try to get them and attach them.

**Comment by MuntashirAkon** [comment]
1. Install a debug build from GitHub actions and launch it in no-root mode (set no-root in settings after the first launch). 
2. Remove the app from the Recents to close it completely
3. Launch it again and wait for a few minutes
4. Send me the logs located at `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`

**Comment by pabloski80** [comment]
[am.log](https://github.com/MuntashirAkon/AppManager/files/9946556/am.log)

Here we go.

**Comment by MuntashirAkon** [comment]
> [am.log](https://github.com/MuntashirAkon/AppManager/files/9946556/am.log)
> 
> Here we go.

Logs look fine. This might mean that issues are only logged by system as warning or info. You have to take full system logs while you follow procedure#3 in the instructions above. You might also want to find out the output of `pm list packages -a`.

**Comment by MuntashirAkon** [comment]
Please also take a look at the linked issue (#298) too. It was applicable for Android 6, but could be applicable for Android 5 too.

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
