### ISSUE TITLE
Stuck at start up and install page with wireless ADB on

### ISSUE THREAD

**Issue by fairyex** [MuntashirAkon/AppManager#914]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

enable and connect wireless ADB with appmanager,  everything seems fine at the beginning, but when it running background after a long time(more then several hours), it would stuck at start up or apk install page.

Meanwhile other APPs that use wireless ADB are working fine.Reboot the phone could temporary solve the problem but it could reproduce everytime.

### To Reproduce

1. enable wireless ADB and connect with APP Manager
2. let it running at background.

### Device info

- Device: F936 Galaxy Z Fold4
- OS Version: OneUI 4.1.1 Android12.1
- App Manager Version: 3.0.3 latest version
- Mode: ADB

**Comment by MuntashirAkon** [comment]
> it running background after a long time(more then several hours), it would stuck at start up or apk install page.

What exactly did you mean by running it in the background for a long time? Could you elaborate on that, such as what did you do to keep it running for that long period of time?

**Comment by sobaee** [comment]
> > it running background after a long time(more then several hours), it would stuck at start up or apk install page.
> 
> What exactly did you mean by running it in the background for a long time? Could you elaborate on that, such as what did you do to keep it running for that long period of time?

I think he simply means that if the app is on Wifi-ADB mode, then you close it then open it again → it will refuse to startup "stuck on initializing..." 


This is what is happening with me.

**Comment by MuntashirAkon** [comment]
> I think he simply means that if the app is on Wifi-ADB mode, then you close it and then after a while you open it again→ it will refuse to startup "stuck on initializing..."

What do you mean by closing? Removing the app from the Recents? It would be better if you shared the steps to reproduce it so that I might have a better understanding of what went wrong.

**Comment by MicroBeast** [comment]
On me. This "stuck" on AppManager Initialization screen also happen if the Mode of operation is ADB over TCP.

I think, that also what happen when I try to use the AppManager Install feature, AppManager stuck on starting.

The issue start if I chose to remember USB Authorization when asked. And yeah, it produceable at least on me.

It seem, AppManager trying to figure out to use ADB or not, then eventully fall back to None mode after minutes pass.

Workaround(?):
I "probably" solve it by, Revoke USB debugging authorization in Developer options. No long Initialization so far. When opening AppManager again, just do not make AppManager remember the authorization when asked. I don't know what to think about why that authorization related at all.

AppManager:
- v3.1.0
- v3.2.0-alpha01

Devices:
- Vivo Y15s, Android 12go, arm-v7a
- Samsung M20g, Android 10, arm64
- Redmi 4A, Android 7.1.2, arm64
- Samsung T-555, Android 7.1.1, arm-v7a
