### ISSUE TITLE
Illiterate Forum

### ISSUE THREAD

**Issue by brewmaster396** [MuntashirAkon/AppManager#916]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Setting for VirusTotal is just there to troll

### Device info

- Device: P6P, P4XL, N6, CCwGTV
- OS Version: 13 TP1A.221005.002 on P6P
- App Manager Version: 3.0.3 and all other versions
- Mode: Root/ADB/NonRoot Currently Nonroot, same in adb mode

### Additional context

Dev is AI bot

**Comment by MuntashirAkon** [comment]
We shall keep this and your previous discussion just to prove your point. Thanks.
