### ISSUE TITLE
Remove "Doesn't connect to the internet" entry from fastlane description

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#918]
### Please check before submitting an issue

- [X] This issue is not related to the translated version of the documentation
- [X] I know technical terms used in the documentation

### Describe the problem area

[/fastlane/metadata/android/en-US/full_description.txt](https://github.com/MuntashirAkon/AppManager/blob/master/fastlane/metadata/android/en-US/full_description.txt) says doesn't connect to the internet but there's some internet depending features for now.Therefore, this statement may be misleading to users.

### Current documentation if it present

```diff
<li>Doesn't connect to the internet (internet permission is required for ADB mode)</li>
```

### Describe your suggestion

```diff
- <li>Doesn't connect to the internet (internet permission is required for ADB mode)</li>
```
Just remove or,

```diff
- <li>Doesn't connect to the internet (internet permission is required for ADB mode)</li>
+ <li>Doesn't connect to the internet without the user's explicit permission.</li>
```

### Additional context

Related:#856

**Comment by gnuhead-chieb** [comment]
If you think need this change,I'll sent PR including Japanese translation

**Comment by MuntashirAkon** [comment]
I think the second one looks nice.

**Comment by MuntashirAkon** [comment]
Changed in e3547c0658d318ef4f0bd8f4feb15affe5383288
