### ISSUE TITLE
Show warning alert if found app that using Fake Play App Signing

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#919]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

As my research of Android malwares,they often use fake Play App Signing.
This is fake-chrome malware that has worm and botnet functionality prevalent these days made by cybercriminal from china.

This fake signature has identifier same with PAS, but public key and checksum are different.
As far as I know, all apps with such signatures were malware.
Therefore, I thought it would be a good idea to warn users and encourage them to uninstall such applications when AMs discover them.
<img src="https://user-images.githubusercontent.com/41156994/200158355-805f7bbd-b5f7-45be-acbc-5f486593a599.png" height="40%" width="40%"/><img src="https://user-images.githubusercontent.com/41156994/200158357-3a5da4d7-9c9d-4d6e-b614-18df1cdccd7c.png" height="40%" width="40%"/>

**Comment by MuntashirAkon** [comment]
How to detect them?

**Comment by gnuhead-chieb** [comment]
App has signature identifier `CN=Android,OU=Android,O=Google Inc.,L=Mountain View,ST=California,C=US` but does not include Google's signature

**Comment by MuntashirAkon** [comment]
> CN=Android,OU=Android,O=Google Inc.,L=Mountain View,ST=California,C=US

This is the default identifier used by Android tools.

**Comment by gnuhead-chieb** [comment]
ah ok i understand
