### ISSUE TITLE
AppManager do not work in root mode on rooted device

### ISSUE THREAD

**Issue by beljaeff** [MuntashirAkon/AppManager#920]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AppManager do not work in root mode on rooted device (SuperSu is used): I can't block trackers.

### To Reproduce

- 1. Install AppManager
- 2. Make sure SuperSu up and running
- 3. Open AppManager and grant root priv
- 4. Text "Initializing…" shows for 40-60 sec 
- 5. AppManager shows message 'Unable to use the current mode of operation. Falling back to no-root mode for this session.'
- 6. When I try to block tracers AppManager show message "Only works in root or ADB mode"

### Expected behavior

- 1. AppManager successfully recognizes that device is rooted.
- 2. AppManager supports root mode on device.
- 3. AppManager successfully block trackers.

### Screenshots

http://ims.cr.zyns.com/app-manager-bugreport/1.png

http://ims.cr.zyns.com/app-manager-bugreport/2.png

http://ims.cr.zyns.com/app-manager-bugreport/3.png

http://ims.cr.zyns.com/app-manager-bugreport/4.png

http://ims.cr.zyns.com/app-manager-bugreport/5.png

### Logs

.......
D/RootServiceManager( 4908): ( [ -d  /data/local/tmp ] || ( rm /data/local/tmp; mkdir /data/local/tmp && chmod 771 /data/local/tmp && chown 2000:2000 /data/local/tmp ) ) && cp /storage/emulated/0/Android/data/io.github.muntashirakon.AppManager/cache/main.jar /data/local/tmp && chmod 755 /data/local/tmp/main.jar && chown shell:shell /data/local/tmp/main.jar && (CLASSPATH=/data/local/tmp/main.jar  /proc/4908/exe  /system/bin --nice-name=io.github.muntashirakon.AppManager:root io.github.muntashirakon.AppManager.server.RootServiceMain io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.ipc.AMService 10155 59aa9f96-048f-47f8-a237-8a8781626558 start)&
.......
W/art     ( 4942): Could not create mount namespace.
.......
E/memtrack( 4942): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 4942): failed to load memtrack module: -2
D/AndroidRuntime( 4942): Calling main entry com.android.commands.am.Am
D/AndroidRuntime( 4942): Shutting down VM
.......
I/Choreographer( 4908): Skipped 40 frames!  The application may be doing too much work on its main thread.
.......
E/SQLiteLog( 4908): (283) recovered 14 frames from WAL file /data/data/io.github.muntashirakon.AppManager/databases/apps.db-wal
.......
E/JavaBinder( 4908): !!! FAILED BINDER TRANSACTION !!!
W/ParceledListSlice( 4908): Failure retrieving array; only received 114 of 157
W/ParceledListSlice( 4908): android.os.TransactionTooLargeException
W/ParceledListSlice( 4908):     at android.os.BinderProxy.transactNative(Native Method)
W/ParceledListSlice( 4908):     at android.os.BinderProxy.transact(Binder.java:496)
W/ParceledListSlice( 4908):     at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:97)
W/ParceledListSlice( 4908):     at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:41)
W/ParceledListSlice( 4908):     at android.content.pm.ParceledListSlice$2.createFromParcel(ParceledListSlice.java:200)
W/ParceledListSlice( 4908):     at android.content.pm.ParceledListSlice$2.createFromParcel(ParceledListSlice.java:198)
W/ParceledListSlice( 4908):     at android.content.pm.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:2692)
W/ParceledListSlice( 4908):     at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:105)
W/ParceledListSlice( 4908):     at io.github.muntashirakon.AppManager.db.utils.AppDb.updateApplications(AppDb.java:147)
W/ParceledListSlice( 4908):     at io.github.muntashirakon.AppManager.utils.PackageUtils.lambda$getInstalledOrBackedUpApplicationsFromDb$0(PackageUtils.java:172)
W/ParceledListSlice( 4908):     at io.github.muntashirakon.AppManager.utils.PackageUtils$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
W/ParceledListSlice( 4908):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/ParceledListSlice( 4908):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/ParceledListSlice( 4908):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/ParceledListSlice( 4908):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/ParceledListSlice( 4908):     at java.lang.Thread.run(Thread.java:818)
.......

### Device info

- Device: Asus Memo Pad 7 ME572C
- OS Version: Android 5.0
- App Manager Version: 3.0.3 (414)
- Mode: Root

### Additional context

Log is large, so I analyzed it and provide only part of it (interesting lines for my opinion) in this message. I can paste a full log if needed.

Device is x86 - Intel Atom Z-serie.

Thank you for cool app!

**Comment by MuntashirAkon** [comment]
Install a debug build from GitHub actions and open it. After it displays the fallback to no-root message, close the app and send me the file located at `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`

**Comment by MuntashirAkon** [comment]
Install a debug build from GitHub actions and open it. After it displays the fallback to no-root message, close the app and send me the file located at `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`

**Comment by beljaeff** [comment]
Thank you for lightning fast response!

I install 3.1.0-alpha011-DEBUG (411).

Here is the log: http://ims.cr.zyns.com/app-manager-bugreport/am.log

For this log entry:
2022-11-07 22:35:26.736 W/Path: Could not get privileged access to path /data/secure/system/ifw

There is no such path on the device. But following path exists: /data/system/ifw. It is empty directory:
drwx------ system   system            2021-06-14 09:46 ifw

**Comment by MuntashirAkon** [comment]
> Here is the log: http://ims.cr.zyns.com/app-manager-bugreport/am.log

```
2022-11-07 22:34:38.173 D/Runner: RootShell
2022-11-07 22:34:38.178 D/ServiceConnectionWrapper: Launching service...
2022-11-07 22:35:23.181 E/ROOT
android.os.RemoteException: Binder not running.
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.getService(ServiceConnectionWrapper.java:86)
	at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.bindService(ServiceConnectionWrapper.java:98)
	at io.github.muntashirakon.AppManager.ipc.LocalServices.bindAmService(LocalServices.java:56)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.launchAmService(LocalServer.java:66)
	at io.github.muntashirakon.AppManager.settings.Ops.autoDetectRootOrAdb(Ops.java:227)
	at io.github.muntashirakon.AppManager.settings.Ops.init(Ops.java:167)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel.lambda$setModeOfOps$0$io-github-muntashirakon-AppManager-settings-SecurityAndOpsViewModel(SecurityAndOpsViewModel.java:75)
	at io.github.muntashirakon.AppManager.settings.SecurityAndOpsViewModel$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

Seems to be related to #606. Need full system logs during that moment and not just the logs from am.log to confirm.

**Comment by beljaeff** [comment]
Here is it: http://ims.cr.zyns.com/app-manager-bugreport/all.log

**Comment by MuntashirAkon** [comment]
> Here is it: http://ims.cr.zyns.com/app-manager-bugreport/all.log

Run this command as root and while running this, take logs as well:

```sh
(AM_VERBOSE_LOGGING=1 CLASSPATH=/data/local/tmp/main.jar  /proc/8096/exe  /system/bin --nice-name=io.github.muntashirakon.AppManager.debug:root io.github.muntashirakon.AppManager.server.RootServiceMain io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.ipc.AMService 10156 80831ad6-e0fd-442a-a4e5-e318f9b8ac45 start)&
```

If the above command succeeds, then run the following to see what happened:

```sh
ps | grep io.github.muntashirakon.AppManager.debug:root
```

**Comment by beljaeff** [comment]
I tried to run that command, the result is:

/system/bin/sh: /proc/8096/exe: not found

There is no folder 8096 inside /proc. Command failed to start so there is no logs.

**Comment by MuntashirAkon** [comment]
> /system/bin/sh: /proc/8096/exe: not found

`8096` is the process ID of App Manager. Instead of this, you can also use `/system/bin/app_process`.

**Comment by beljaeff** [comment]
What I've done.

1. Open one terminal (1) and run `adb shell` there and execute `su` inside adb
2. Open another terminal (2)  and execute `adb logcat` there
3. Run AM Debug on device
4. Execute `ps | grep ebug` in (1) and got AM Debug pid (13452)
5. Run `(AM_VERBOSE_LOGGING=1 CLASSPATH=/data/local/tmp/main.jar  /proc/13452/exe  /system/bin --nice-name=io.github.muntashirakon.AppManager.debug:root io.github.muntashirakon.AppManager.server.RootServiceMain io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.ipc.AMService 10156 80831ad6-e0fd-442a-a4e5-e318f9b8ac45 start)&` in (1), output:
`[1] 13513`
7. Wait until AM Debug loads
8. Run `ps | grep io.github.muntashirakon.AppManager.debug:root`, output is:
`[1] + Aborted              ( AM_VERBOSE_LOGGING=1 CLASSPATH=/data/local/tmp/main.jar /proc/13452/exe /system/bin --nice-name=io.github.muntashirakon.AppManager.debug:root io.github.muntashirakon.AppManager.server.RootServiceMain io.github.muntashirakon.AppManage`
9. Take logs from (2) and am.log

I saw logs, there are a lot of exceptions and backtraces there...

Have I do it right?

The logs:
[adb.2022-11-27.1.log](https://github.com/MuntashirAkon/AppManager/files/10098081/adb.2022-11-27.1.log)
[am.2022-11-27.1.log](https://github.com/MuntashirAkon/AppManager/files/10098082/am.2022-11-27.1.log)

**Comment by MuntashirAkon** [comment]
> 7\. [1] + Aborted              ( AM_VERBOSE_LOGGING=1 CLASSPATH=/data/local/tmp/main.jar /proc/13452/exe /system/bin --nice-name=io.github.muntashirakon.AppManager.debug:root io.github.muntashirakon.AppManager.server.RootServiceMain io.github.muntashirakon.AppManage

This is not the output of `ps | ...` command but the continuation of the previous command, the next command returned nothing because the previous command failed. If it was successful, you would've seen something like the following in Android 5.0:

```
root      2719  2710  691608 38116 ffffffff 9f79da8a S io.github.muntashirakon.AppManager.debug:root
```

Therefore, the next step is to determine what is causing the command to abort. But at first, I have to do something on my end. I will send you the instructions after I push a new build.

**Comment by MuntashirAkon** [comment]
1. Install the latest build
2. Restart your device
3. Start taking logs using **logcat** (NOT am.log)
4. Open App Manager and wait for it to load all the apps
5. Send me the logs.

**Comment by beljaeff** [comment]
I've installed build #2110 from github actions and completed all the steps.
The logs:
[log.1.log](https://github.com/MuntashirAkon/AppManager/files/10098949/log.1.log)

**Comment by MuntashirAkon** [comment]
> I've installed build #2110 from github actions and completed all the steps. The logs: [log.1.log](https://github.com/MuntashirAkon/AppManager/files/10098949/log.1.log)

It's failing much earlier it seems. I will add some more logs to figure out the issue and ping you again.

**Comment by beljaeff** [comment]
Ok! Thank you!

**Comment by MuntashirAkon** [comment]
Hi again, could you try the latest build?

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.

**Comment by hexman1999** [comment]
Hello 

It seems that I have same problem here @MuntashirAkon 


What to do to trace the problem?
