### ISSUE TITLE
App list not showing any application

### ISSUE THREAD

**Issue by Tacobelled** [MuntashirAkon/AppManager#921]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When connected to wireless debugging, then tried press on any app in the app list it crashed, after restarting the app manager, the list doesn't pop up any application including in the running apps menu

### To Reproduce

- 1. Connect wireless debugging
- 2. Open any application menu in the app list
- 3. Restart the app manager as it just crashed
- 4. Doesn't pop up any app in the application list

### Expected behavior

_app manager crashed_

### Screenshots

![Screenshot_2022-11-07-23-25-04-89_718a221d6c53e9d44e23988b91117061](https://user-images.githubusercontent.com/117423323/200348130-c9b82066-3854-4e63-9042-11ca7cd7f123.jpg)
![Screenshot_2022-11-07-23-25-02-06_718a221d6c53e9d44e23988b91117061](https://user-images.githubusercontent.com/117423323/200348139-e6eb339f-c565-41ff-b7cf-1c9e2f403510.jpg)

### Device info

- Device: Realme GT Master Edition
- OS Version: RMX3363_11_C.11
- App Manager Version: 3.0.3
- Mode: ADB

**Comment by MuntashirAkon** [comment]
You said that App Manager crashed but attached no crash logs.

**Comment by MuntashirAkon** [comment]
Closed due to lack of response. Feel free to open it again if you're still facing the issue.
