### ISSUE TITLE
Add ability to filter by Installer App

### ISSUE THREAD

**Issue by mr-ransel** [MuntashirAkon/AppManager#923]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

### Describe a description of the new feature

In the list view it would be a very helpful filter to introduce the ability to filter the Installer App. 

The app already collects this information, but it would be hugely beneficial to be able to filter out apps managed by Google Play/FDroid/IzzyOnDroid/GDroid/App Manager/Manually. 

### Describe the solution you'd like

Some examples of experiences that achieve this goal
* Filter by a particular Installer App (from an enumerated drop-down) in the list view
* Inverse filter by specifically "Not installed by Google Play", or a specific app store thats configurable in settings. 
* A generated "preset" profile that can be generated by using one of the above filters without having to clutter the filter view with more options, just a new preset profile creation option.

### Describe alternatives you've considered

I've searched for other apps to accomplish this, but currently the only option I've found is combining something like the List My Apps app on FDroid and generating a text file list, grepping out the Play/Aurora apps, and then going down the list manually one by one in App Manager to see which ones were installed by what installer.

**Comment by knakamura8** [comment]
Considering Google Play's recent update to match all apps by name instead of install location or signature, this would be especially useful at present.

**Comment by thibaultmol** [comment]
This would be so convenient to filter out all the play store apps so i can easily only transfer the fdroid, manual apk, etc apps

**Comment by MuntashirAkon** [comment]
Superseded by #1488
