### ISSUE TITLE
Redesign App Icon & Add Themed Icon Support 

### ISSUE THREAD

**Issue by Amorphous404** [MuntashirAkon/AppManager#924]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Suggestion:

![Screenshot_2022-11-09-09-16-32-55_3822ac0e29cfec8970059bb21d01f05e](https://user-images.githubusercontent.com/96917972/200734082-df9f06b3-ab83-4898-a343-ca0bad766096.jpg)

1) Your app already support Adaptive Shape but, Please redesign/remove the squircle background from the icon, you can use the same color for the cog/settings icon instead so it looks good with adaptive shapes or you can use fully colored background so it looks well when changing the shape.

2) And also if possible add support for Dynamic 
Icons/Themed Icons (Material You)

Developer Guide:

https://developer.android.com/about/versions/13/features#themed-app-icons

**Comment by MuntashirAkon** [comment]
4aeebbe97de618cb16d856ff54ce23bacaae60f8

**Comment by MuntashirAkon** [comment]
> * Your app already support Adaptive Shape but, Please redesign/remove the squircle background from the icon, you can use the same color for the cog/settings icon instead so it looks good with adaptive shapes or you can use fully colored background so it looks well when changing the shape.

I can't change the icon without a good alternative (#53) (and ripping off an icon from another app is clearly not a solution.)
