### ISSUE TITLE
Hidden button (backup section)

### ISSUE THREAD

**Issue by J4CKED** [MuntashirAkon/AppManager#925]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

In the backup section, the bottom button is hidden. Fortunately, I manage to press it.
The font and screen settings are the default on my Android.

### Screenshots

![Screenshot_20221109-173511_App Manager](https://user-images.githubusercontent.com/60573158/200889979-3eadce0d-9ab5-4350-a8c6-e16f6f57c6ac.jpg)

Here you can't see what the buttons are.
![Screenshot_20221110-153705_App Manager](https://user-images.githubusercontent.com/60573158/201120813-2e5f3a33-2e27-4a9e-83c0-1b40e6b4d6e2.jpg)

### Device info

- Device: Realme 7 Pro
- OS Version: Android 12 (DerpFest)
- App Manager Version: 3.0.2 and 3.0.3
- Mode: Root

**Comment by J4CKED** [comment]
Update. I noticed that this bug only occurs in applications that already have a backup.

**Comment by MuntashirAkon** [comment]
> Update. I noticed that this bug only occurs in applications that already have a backup.

This is a bug in the AndroidX viewpager library (viewpager2 is even worse). Until I figure out a way to fix this, you can display the buttons by swiping up in the upper section of the bottomsheet page (above the tab names).

**Comment by MuntashirAkon** [comment]
Fixed in abac815f4521ea3b755892d73f026bfdf4f0fd6c
