### ISSUE TITLE
Wrong translation (Polish)

### ISSUE THREAD

**Issue by J4CKED** [MuntashirAkon/AppManager#926]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

1. Go to: Settings > Backup/Restore. Instead of "Ilość kopii zapasowych" it should be "Miejsce zapisu".

2. Click to some app > 3 dot menu > Backup/Restore. Instead of "Utwórz kopię zapasową wielu" it should be "Utwórz kolejną kopię"

- App Manager Version: 3.0.3

**Comment by MuntashirAkon** [comment]
Fixed in cfedd135af190c0be4841db73c5f9ea90fb94417
