### ISSUE TITLE
Change ssaid not working 

### ISSUE THREAD

**Issue by QPLAYid** [MuntashirAkon/AppManager#932]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I change ssaid not working not happenin

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by QPLAYid** [comment]
I try mode root

**Comment by QPLAYid** [comment]
Android 12

**Comment by MuntashirAkon** [comment]
Duplicate of #457
