### ISSUE TITLE
Tips constantly reappear

### ISSUE THREAD

**Issue by cohesive-flight** [MuntashirAkon/AppManager#934]
### Please check before submitting an issue

- [x] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device
- 
### Describe the bug

The tips that appear when viewing the `App Ops`, `Uses permissions`, or `Permissions` tabs constantly reappear no matter how many times they're closed. They do disappear initially, but if the user views any of these three tabs again after backing out of the app's details, it causes them to reappear.

### To Reproduce

1. View an app's details
2. Visit the `App Ops`, `Uses permissions`, or `Permissions` tabs
3. Close the tip
4. Back out of the app's details
5. Repeat steps 1-2
7. Tip should reappear

### Expected behavior

For the tip to not reappear once closed.

### Device info

- Device: Pixel 7
- OS Version: Android 13 (Graphene OS)
- App Manager Version: 3.0.3 (414)
- Mode: No Root

### Additional context

I'd recommend implementing an option within the settings to reset these tips, in case a user ever forgets a tip or regrets closing one.

**Comment by cohesive-flight** [comment]
In retrospect, I should've labeled this issue as a bug, because I don't believe it's intended for the tips to keep appearing once you close them.

**Comment by MuntashirAkon** [comment]
Fixed in 2ec19fab30dfd3587b583d8180c91f7dfd273fa6
