### ISSUE TITLE
it is possible to switch: Services, Reсievers, Providers

### ISSUE THREAD

**Issue by OmlineEditor** [MuntashirAkon/AppManager#936]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

it is not possible to switch the following values individually in a convenient form:  Services, Reсievers, Providers

### Describe the solution you'd like

please add a convenient switch to select. see the picture:
![sw](https://user-images.githubusercontent.com/13348933/204031285-cf4fdde9-f0d6-4c75-a65e-71e0e68801c1.jpg)

### Describe alternatives you've considered

the alternative is to use another program:
![oth](https://user-images.githubusercontent.com/13348933/204031584-cd719b74-d174-497f-bd2c-3316119b0a1b.jpg)

**Comment by MuntashirAkon** [comment]
Implemented in b6b2c0709d31bb18c8f00dfa655628cb14f38d79
