### ISSUE TITLE
the interface goes beyond the edge of the screen

### ISSUE THREAD

**Issue by OmlineEditor** [MuntashirAkon/AppManager#937]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I open the applications and see that part of the interface goes off the screen and I can't switch and change the values.

### To Reproduce

1. I open any the app.
2. I look at the characteristics of the tabs.
3. I'll scroll to the bottom
4. I see part of the interface hidden under the triangle circle and square buttons, because behind the screen where you can press your finger

### Expected behavior

all interface elements are on the screen and are not hidden abroad. sometimes if you close the application and repeat the same actions again, the problem disappears. i.e. the problem spontaneously appears

### Screenshots

![bug](https://user-images.githubusercontent.com/13348933/204037091-29b8b224-9d8c-43b3-bd5d-79bff0d8575e.jpg)

### Device info

- Device: Redmi Note 7
- OS Version: Android 10
- App Manager Version: 3.0.3
- Mode: Root

**Comment by MuntashirAkon** [comment]
Not sure why this should ever happen. I've tried A10 in the emulator, it works perfectly well.

**Comment by OmlineEditor** [comment]
the problem spontaneously appears. I don't understand how it works

**Comment by MuntashirAkon** [comment]
Unfortunately, it's not possible to address intermittent bugs since they can't be reproducible on my side. Feel free to reopen the issue when you're confident that there's a definite way to reproduce the issue.
