### ISSUE TITLE
view important receivers in one place for all applications

### ISSUE THREAD

**Issue by OmlineEditor** [MuntashirAkon/AppManager#938]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

you need to make a separate menu item where you can view all the important receivers for all applications. These important receivers are listed in the picture (power on, network connection, time change, application installation/removal).

![all](https://user-images.githubusercontent.com/13348933/204040454-b8d0a32e-977c-450c-ab98-a6d5da4963ad.jpg)

### Describe the solution you'd like

I can see all the important receivers and can selectively turn them off for applications.

![exampl](https://user-images.githubusercontent.com/13348933/204040269-d96f760e-803d-4eb0-9ac7-020897430447.jpg)

### Describe alternatives you've considered

I am using another application MyAndroidTools but it is no longer supported and new versions are no longer being released.
https://www.myandroidtools.com/

### Additional context

if possible, study an alternative program [MyAndroidTools ](https://www.myandroidtools.com/) that I use and take ideas from it for your program.

**Comment by MuntashirAkon** [comment]
I have different plans for App Manager. See #321 and #309.
