### ISSUE TITLE
improved display of long text

### ISSUE THREAD

**Issue by OmlineEditor** [MuntashirAkon/AppManager#939]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

when viewing actions, the line is incomplete. it's hard to understand. the text does not fit completely on the screen.
![runstr](https://user-images.githubusercontent.com/13348933/204101035-ffe2b19f-8936-4c82-8261-6645c7ba2614.jpg)

### Describe the solution you'd like

please make a long text moving. The text moves and is shown completely. If it is difficult to make the text move, then make a transfer of a long text to 2 lines.

example of long text movement (animated picture):
![d](https://user-images.githubusercontent.com/13348933/204101129-e411bf69-3e7b-4a31-9770-a79d67e06fa8.gif)

### Describe alternatives you've considered

there are no alternatives, I don't see the text because it is long and there is not enough space to display it

**Comment by MuntashirAkon** [comment]
These are the standard menu items. Therefore, you can just tap and hold on an item to see a tooltip containing the entire text.
