### ISSUE TITLE
1 Click Blocking Trackers - "No Tracker Found"

### ISSUE THREAD

**Issue by Sn0whax** [MuntashirAkon/AppManager#942]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

1-Click Blocking Trackers is showing "No Tracker Found"
This contradicts the app as when I go into a few specific apps and see their receivers marked as trackers.

A few notes:
- I've tried both ADB over TCP and WiFi. 
- Default blocking method defaults back to "Disable" when I change it to anything else.

### Device info

- Device: Pixel 7 Pro
- OS Version: Grapheneos Latest on Android 13
- App Manager Version: 3.0.3
- Mode: ADB

**Comment by MuntashirAkon** [comment]
> * I've tried both ADB over TCP and WiFi.

In ADB mode, 1-Click Ops for blocking tracker only checks for apps having the **test-only** flag as specified in the [release logs](https://muntashirakon.github.io/AppManager/en/#component-blocking). If there's no test-only app with trackers, it will report that there are no trackers to be blocked.

> * Default blocking method defaults back to "Disable" when I change it to anything else.

In ADB mode, only **Disable** option is supported. Therefore, setting this option to anything else will not work.

**Comment by molitona** [comment]
Hello @MuntashirAkon 
i've 2 questions if you don't mind to see if my understanding is correct :)

1. for non-rooted phones, we can only block tracker of test-only apps with either ADB over TCP or WiFi ?
2. if yes for the 1st question, how to have a list of all test-only apps using the app ?

**Comment by MuntashirAkon** [comment]
> * for non-rooted phones, we can only block tracker of test-only apps with either ADB over TCP or WiFi ?

Via 1-click ops as usual.

> 2\. if yes for the 1st question, how to have a list of all test-only apps ?

There's no such option right now. You need to wait for #321, which may be available in the next quarter.

**Comment by MuntashirAkon** [comment]
> * I use this android app FW https://rethinkdns.com/app and I block WIFI+mobile data for non-FOSS/non-clean of trackers apps found by exodus. do you know about it, i tried it, it blocks TCP connections, ICMP it didn't work, for UDP didn't test. do you think it's a good strong FW that can't be bypassed? (I have android 13)

No, I never tried this app.

> 2\. For android 13, some 3rd party apps (aurora/fdroid) shows an option to block WIFI+data in their settings and others not, why this? can app devs deny it from being prevented to use wifi/data ?

Depends on the availability of the Internet permission.

**Comment by molitona** [comment]
`Depends on the availability of the Internet permission.`
you know what is exactly this permission that is added to manifest file ?
some apps shows an option to block wifi and data, others only data and others nothing


otherwise, i have 1 question, to my understanding on android phones we can't have both privacy and security in the same time.

if i root my phone anyone can go to twrp, delete the file that stores pin/password and have access to my phone data so NO SECURITY! (i remember searched for a way to have TWRP secured by password but found it's not possible years ago..)

in the other end, if we stay with no-root then OEMs can still spy on us and steal our data no matter how many bloatware apps we remove with adb.

you agree with my point PRIVACY && SECURITY is something unachievable in android phones ?

**Comment by MuntashirAkon** [comment]
> you know what is exactly this permission that is added to manifest file ?

I'm not exactly sure _how many_ permissions. But I'm sure it includes `android.permission.INTERNET`.

> otherwise, i have 1 question, to my understanding on android phones we can't have both privacy and security in the same time.

That's not true. It entirely depends on your threat model. For example, you could buy a Pixel phone, unlock bootloader, install GrapheneOS, re-lock bootloader, and only install privacy respecting apps in the primary profile and others in the secondary/work profile.

**Comment by molitona** [comment]
> > you know what is exactly this permission that is added to manifest file ?
> 
> I'm not exactly sure _how many_ permissions. But I'm sure it includes `android.permission.INTERNET`.
> 
> > otherwise, i have 1 question, to my understanding on android phones we can't have both privacy and security in the same time.
> 
> That's not true. It entirely depends on your threat model. For example, you could buy a Pixel phone, unlock bootloader, install GrapheneOS, re-lock bootloader, and only install privacy respecting apps in the primary profile and others in the secondary/work profile.

ok what can happen if i let bootloader unlocked after rooting ?

**Comment by MuntashirAkon** [comment]
> ok what can happen if i let bootloader unlocked after rooting ?

Off-topic questions should be asked in groups/forums, not in an issue tracker. Thanks.
