### ISSUE TITLE
ZSTD and XZ support

### ISSUE THREAD

**Issue by abvgdeyoj** [MuntashirAkon/AppManager#944]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

It would be helpful to have both/either of XZ and ZSTD as compression methods for backups.

**Comment by MuntashirAkon** [comment]
Yes, ZSTD support will be added soon which will also be the new default. However, XZ support will not be added as it consumes a lot of memory during compression.

**Comment by MuntashirAkon** [comment]
Added in 2e9a08d64c3243f15f02acea3e583f0edaa64b9c
