### ISSUE TITLE
Fails to convert to java

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#946]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Using App Manager Debug (latest builds) fails to convert the smali code to java whenever we tap on "Java" option given in smali viewer.

This is happening in newer debug version because stable App Manager works perfectly. I am attaching a screenshot to show what the error looks like. 

### To Reproduce

1. Open any app using "Explore", I tried it on Google photos and Spotiflyer apk files.
2. Choose classes.dex and try to open any smali file.
3. See the error.

### Expected behavior

Should show java code without throwing error

### Screenshots

![Screenshot_20221202-164351_AM Debug](https://user-images.githubusercontent.com/83750299/205281954-c20b74ce-1457-468e-ac4b-0de2c039ab46.png)

### Device info

- Device: Emmm 
- OS Version: Android 13
- App Manager Version: latest debug
- Mode: Root

**Comment by MuntashirAkon** [comment]
Fixed in fcecd9738204eb3ded3c10fdc30cd0890a89cd0c
