### ISSUE TITLE
How to re-enable backround running

### ISSUE THREAD

**Issue by friendlytherapist** [MuntashirAkon/AppManager#95]
Hello I have "diabled backround run" on one of my apps in the running apps tab. How do I re-enable backround running for the app?

**Comment by MuntashirAkon** [comment]
> Hello I have "diabled backround run" on one of my apps in the running apps tab. How do I re-enable backround running for the app?

Go to the **App Ops** tab, search for `RUN_IN_BACKGROUND` and use the toggle button on the right hand side to enable it.

**Comment by friendlytherapist** [comment]
thanks working
