### ISSUE TITLE
App update (likely) caused disabled feature (Interceptor) to be re-enabled (checkbox still disabled)

### ISSUE THREAD

**Issue by opusforlife2** [MuntashirAkon/AppManager#952]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I disabled the App Interceptor feature while setting up the app. However, recently, I noticed that it started being offered again to intercept links.

I simply toggled the checkbox on and then off again. Now the Interceptor isn't showing up.

The most likely possibility that occurs to me is that a recent update caused the feature disablement to be reset, without affecting the checkbox state.

### To Reproduce

Likely steps:
1. Disable Interceptor.
2. Update app. (not sure which version to update from, but probably 3.0.2.)
3. Try an action it can intercept.

### Expected behavior

The disabled feature should stay disabled after updates.

### Device info

- Device: Mi 5
- OS Version: LOS 19.1
- App Manager Version: ? to 3.0.3
- Mode: Root

**Comment by MuntashirAkon** [comment]
This wasn't reproducible on my side. Since this does not bear any significance in the overall UX of the app, I will not waste my time on investigating it any further. If you can reproduce this again, feel free to re-open it along with steps to reproduce it.
