### ISSUE TITLE
May you please add an option to AppManager that it can save (backup/export) the APK files of other users also (specially work profile)

### ISSUE THREAD

**Issue by Rustlang4Future** [MuntashirAkon/AppManager#955]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

One of my use of AppManager is to backup my apk files and it is so far great.

But it won't let me export APK files of work profile or the ones that are freezer in work profile with Island. (Although it recognise and show them to me)

### Describe the solution you'd like

May you please add an option to AppManager that it can save (backup/export) the APK files of other users also (specially work profile)

### Additional context

Thank you very much.
Best wishes.

**Comment by MuntashirAkon** [comment]
This should be a bug report rather than an FR. While the issue has already been fixed. Assuming you're currently using the latest stable (v3.0.3), you will have to wait for the next minor release (i.e. v3.1.0).
