### ISSUE TITLE
Hardware keyboard

### ISSUE THREAD

**Issue by 5A52** [MuntashirAkon/AppManager#956]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Started from version 3.x.x. when using hardware keyboard (not shure how to explain) search field loses focus after each letter. So if I whant to type "appmanager" I have to 

### To Reproduce

click (tap) on a search field, press "A",   click (tap) on a search field, press "P", click (tap) on a search field, press "P"......

### Expected behavior

click on a search field, type "appmanager"

### Device info

- Device: galaxy s10e
- OS Version: 10-11-12
- App Manager Version: 2.x.x, 3.x.x, 3.1.0-alpha0.2
- Mode: Root

### Additional context

in versions 2.x.x. all ok.

**Comment by MuntashirAkon** [comment]
Fixed in 43c0f9ad7b6eb1eeec4c7e0ed2ee4a6680dc38cc
