### ISSUE TITLE
Sort by Permission? (boot_complete for example)

### ISSUE THREAD

**Issue by Mitezuss** [MuntashirAkon/AppManager#957]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Sort by BOOT_COMPLETE or another permission

### Describe the solution you'd like

Wanna sort by BOOT_COMPLETE

**Comment by MuntashirAkon** [comment]
You might be looking for a feature like this #321 instead.
