### ISSUE TITLE
magisk denylist fails

### ISSUE THREAD

**Issue by fusionneur** [MuntashirAkon/AppManager#961]
trying magisk denylist on revolut v8.82.3 by selecting all processes
i get error message: 
could not enable magisk denylist

also it is not clear for me whether it is actually added in denylist or not, because there is no indicator to show this

**Comment by MuntashirAkon** [comment]
Already fixed via 567ff695b7c98dd907b0b1a0a87e63c96dcda830. Wait for the next release, and please use a single comment to post everything, use the edit option when necessary (but the use of a template would've made it much easier). I've got three E-Mails for this issue which is quite annoying considering how many E-Mails I receive everyday.
