### ISSUE TITLE
Freez /unfreez shortcut removed in stable version 

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#971]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

In earlier stable version there is option to create shortcut of freez and unfreez app from app details screen and its removed from latest stable version.

**Comment by MuntashirAkon** [comment]
Nope. Stable version never had this feature. You've mistakenly installed a pre-release (v3.1.0-alpha02).
