### ISSUE TITLE
List of apps with known issues and workarounds for them

### ISSUE THREAD

**Issue by wojnilowicz** [MuntashirAkon/AppManager#974]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Recently I blocked all the trackers for [AccuBattery](https://play.google.com/store/apps/details?id=com.digibites.accubattery&gl=US&pli=1) and found out that it doesn't even start after this. It started only after I unlocked org.acra.attachment.AcraContentProvider marked as a tracker. It took me some time to find out that it was org.acra.attachment.AcraContentProvider and not an other tracker. It could be more effortless. 

Otherwise the app gives me great power, so thank you for developing it.

### Describe the solution you'd like

Several possible choices for it being more effortless:
1. A warning in the App Manager that blocking given tracker will make the app useless
2. A new chapter in the documentation that lists popular apps and issues with them after e.g. blocking a tracker

**Comment by MuntashirAkon** [comment]
App Manager Community has a documentation regarding this. See https://t.me/s/AppManagerCommunity/9:

> [#tracker](https://t.me/s/AppManagerCommunity/9?q=%23tracker) [#blocking](https://t.me/s/AppManagerCommunity/9?q=%23blocking) [#crash](https://t.me/s/AppManagerCommunity/9?q=%23crash)
> **Why blocking some trackers lead to crashes and how to fix them?**
>
> In many cases, certain functions of the tracker are initialised when the application is being launched. Many tracker libraries offer one or more [content providers](https://muntashirakon.github.io/AppManager/en/#subsubsec:providers), some of which need to be initialised this way. So, if these providers are blocked or disabled, and the library or the application wasn’t made to handle errors due to this, the application may crash.
>
> If the cause of the crashes are indeed the content providers, they might be fixed by one of the following ways:
> 1. Block the providers using Intent Firewall (IFW) only.
> 2. Unblock the providers one by one to find the real culprits and then block the rests again keeping the culprits unlocked.
> 3. A more advanced approach is to edit the APK to delete such initialisations by looking at the backtrace in the crash log.
>
> If procedure 1 and 2 do not work, the cause of the crashes may not be the providers. In such cases, you should unblock all components for the application, perform investigation by checking all the blocked components one by one, or find an alternative application. Of late, many quality open source software have been developed for Android which could be used as replacements for many proprietary applications.
>
> 🏷 Q&A
