### ISSUE TITLE
Editing an "intent"?

### ISSUE THREAD

**Issue by ixalcor** [MuntashirAkon/AppManager#977]
### Describe the existing feature/documentation

It seems AppManager allows editing of activities/intents through the interceptor.

### Describe your problem(s)

So here's the thing. I rooted my phone and eventually deleted the Galaxy Store app to test and see if I could install it as a user app. Evidently that's not the case since I can't even launch the app without it crashing immediately. I don't really mind that I can't use that app and I have no intention of reflashing and re-rooting this thing yet again, thing is tho that whenever I go to "download fonts" now under font size and style settings it takes me to the interceptor thing, which is a pretty minor thing but it's sort of awkward. I remember experiencing something like this in a previous device, so I'm wondering if instead of having the interceptor open whenever I select download fonts I can do something like search "fonts" in Aurora Store

### Additional context

![Screenshot_20230114-225952_Settings](https://user-images.githubusercontent.com/122711014/212522278-452ff954-bb4d-4e3f-a3b5-b4b5d2ebefaf.jpg)
![Screenshot_20230114-230001_App Manager](https://user-images.githubusercontent.com/122711014/212522284-50a9435c-553d-46f0-9cea-f7bba30e9c8a.jpg)

**Comment by MuntashirAkon** [comment]
If an intent is directly opened by the Interceptor (unless you allowed it in first place), it means that there are no other apps to handle it. You can easily find that by disabling interceptor in App Manager > Settings [> Appearance] > Enable/disable features. Now, if you want to search for `fonts` in Aurora Store using this Intent, you can ask the developer of Aurora Store to implement the feature. `market` scheme is a very commonly used scheme. I don't know why it's not handled by Aurora Store in first place.

Interceptor is intended to work as a man-in-the-middle between two applications. More features will be added in the future to automate the process using, possibly, third-party integrations too. But for now, you have to do everything manually.

**Comment by ixalcor** [comment]
Oh I see..
well, disabling interceptor gets rid of the button altogether so I guess that's another way of solving the issue
thanks for the explanation
