### ISSUE TITLE
Block app subprocess in ram.

### ISSUE THREAD

**Issue by Hell0Earth** [MuntashirAkon/AppManager#978]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

In low end devices 4gb of ram an lower is the normal and in some cases is necessary to block apps in ram due to personal necessary, already exits apps to block app in ram but this alternatives block all app in ram and this can generate issues depending on the app.

### Describe the solution you'd like

The solution will be give to the users the ability of block or unblock apps subprocess in ram, with this is not necessary to block all app in ram, avoiding excessive ram consumption and bringing to the  users better control of what app subprocess is that they needs blocked.

### Describe alternatives you've considered

I don't have an alternative idea.

### Additional context

Context: In my case this feature will be useful to block SystemUI Imagewallpaper subprocess in ram. Due to low ram, my device restarts Imagewallpaper service in every home return and this shows a black screen every time, the solution, block SystemUI in ram but this generate instability, so the better alternative will be only block Imagewallpaper service in ram, like other subprocess that are blocked of native form but in this case will blocked with a root root tool provided by AppManager.

**Comment by MuntashirAkon** [comment]
How to do that?

[BTW, could this be an issue with the OS itself? Because my device is pretty low end with 3 GB memory, and it runs Android 11 quite well.]

**Comment by UniverseCodex01** [comment]
> How to do that?
> 
> [BTW, could this be an issue with the OS itself? Because my device is pretty low end with 3 GB memory, and it runs Android 11 quite well.]

Wtf with your fastest response XD, seriously that was really fast, I did the post few minutes ago. Well related to your ask, idk if it's a bug but it's normal in miui A10 with the change of launcher, when system it's out of memory, in home return kill Imagewallpaper service because isn't locked by default, like Recents SystemUI subprocess.

**Comment by MuntashirAkon** [comment]
I don't think it's possible to do this in Android in a convenient way. App Manager would need to run a background service to check the process creation and kill (or force-stop if its an Android package) it immediately after its creation. But system processes can just restart again immediately or after some time (if triggered by another app). So, it'll be just a cat-and-mouse game in the end and will simply be a waste of CPU cycles and battery.
