### ISSUE TITLE
add a section with a focus on managing all app autostarts

### ISSUE THREAD

**Issue by zkollz** [MuntashirAkon/AppManager#979]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

I mean, a section like one-click operations to allow you to select and enable or disable autostart receivers for apps to speed up startup, but in one place and not one by one.

**Comment by MuntashirAkon** [comment]
Duplicate of #309
