### ISSUE TITLE
Remove all rules causes buggy settings to be applied (Google Maps)

### ISSUE THREAD

**Issue by friendlytherapist** [MuntashirAkon/AppManager#98]
**Describe the bug**
Remove all rules causes buggy settings to be applied. Namely, the ability to get a GPS signal in Google Maps app becomes broken.

**To Reproduce**
Steps to reproduce the behaviour:
1. Modify Google map settings (block trackers)
2. Open Maps, it doesnt work because trackers disabled (this works as expected)
3. Close Maps
4. Open AppManager and go to settings and select remove all rules.
5. Go to Maps in AppManager and now see that everything has been enabled (uses permissions) including things that weren't before and corse location disabled for some reason.
6. Maps Gps is now broken no matter what I do. I re-enable corse location, uninstalled maps, delete maps data, cashe, wipe dalvik, delete AppManager, nothing fixes it.

**Expected behavior**
My system to be restored to how it was previous to install of AppManager

**Device info**
 - Device: Galaxy s7
 - OS Version: Android 8
 - App Manager Version: Newest version
 - Mode: root

**Additional context**
Important to note that only Maps GPS seems to be affected as far as I know. Also I have fixed it with a TWRP restore but that was not something most can do.

**Comment by MuntashirAkon** [comment]
That's really weird. It could be that the rules weren't removed properly. Unfortunately, I don't use any Google apps so I can't reproduce this issue. If you're interested in helping me figure out the issue, you can do as follows:
1. Follow step 1-3 of the reproduce section of your issue (Google Maps only. If you're blocking trackers in Google Play services, enable them all)
2. Open AM
3. Find Google Maps (hereafter will be known as GM) and click to see details
3. In the activities, services, receivers and providers tab, enable all the components that were disabled earlier
4. Open GM to see if it's working. If it isn't working, proceed to step 8
5. Follow step 1-2 (above)
6. Navigate to settings and select remove all rules
7. Follow step 4
8. Open `/data/system/ifw` using your favourite file manager
9. See if there are any xml files there
10. If you find any, open `/data/data/io.github.muntashirakon.AppManager/files/conf`
11. See if there are any tsv files there
12. If you find anything in step 9 and 11, report them here along with screenshots/files. These files do not contain any personally identifiable information.

**Comment by MuntashirAkon** [comment]
@friendlytherapist please download the artifact (AppManager) from https://github.com/MuntashirAkon/AppManager/actions/runs/248769671 and see if it also has this issue. If it still has, then follow the instruction in https://github.com/MuntashirAkon/AppManager/issues/98#issuecomment-690049060.

**Comment by friendlytherapist** [comment]
With the debug app it is still buggy with GM permissions. It enables all app ops ect.. but disables coarse location, but it does now fix the app if you enable coarse location so thats a step in the right direction. Here are the logs:
gib.xml
`
<rules>
  <broadcast log="true">
    <component-filter name="com.keramidas.TitaniumBackup/.MyWidget" />
    <component-filter name="com.keramidas.TitaniumBackup/.schedules.BootReceiver" />
    <component-filter name="com.keramidas.TitaniumBackup/.MyDataProfileWidget" />
    <component-filter name="com.keramidas.TitaniumBackup/.PackageEventsReceiver" />
    <intent-filter />
    <or>
      <sender type="system" />
      <not>
        <sender type="userId" />
      </not>
    </or>
  </broadcast>
  <broadcast block="true">
    <intent-filter>
      <action name="com.oasisfeng.greenify.action.SELF_CHECK" />
    </intent-filter>
  </broadcast>
</rules>`

csv file:
`69	APP_OP	0
0	APP_OP	0
59	APP_OP	0
65	APP_OP	0
60	APP_OP	0
23	APP_OP	0
com.google.android.gms.permission.CAR_SPEED	PERMISSION	true
android.permission.WRITE_EXTERNAL_STORAGE	PERMISSION	true
android.permission.RECORD_AUDIO	PERMISSION	true
android.permission.READ_EXTERNAL_STORAGE	PERMISSION	true
android.permission.READ_CONTACTS	PERMISSION	true
android.permission.CAMERA	PERMISSION	true
`

**Comment by MuntashirAkon** [comment]
> gib.xml

Where's this file came from? It isn't generated by App Manager.

> With the debug app it is still buggy with GM permissions. It enables all app ops ect.. but disables coarse location, but it does now fix the app if you enable coarse location so thats a step in the right direction. Here are the logs:

It means that problems related to app components are solved. But app ops and permissions are still not working.

**Comment by MuntashirAkon** [comment]
Found the problem. It seems disabling `OP_GPS` (2) actually disables `OP_COARSE_LOCATION` (0) which is causing the issue. There are other issues as well. I think it is necessary to ensure that the parent of an app op is enabled/disabled along with the op itself. My tests suggest that the app ops are enabled correctly but their parents are not.

**Comment by MuntashirAkon** [comment]
@friendlytherapist Try this: https://github.com/MuntashirAkon/AppManager/runs/1105261983

**Comment by friendlytherapist** [comment]
Thanks for the help, unfortunately I dont have the time to keep creating and restoring TWRP backups on my daily use phone every time I test the app so I wont be able to continue testing for you.

**Comment by Rikj000** [comment]
I might be experiencing the same issue here. But for me location in general is broken, on all apps.
I can see that the apps that I try are using my location under the app's info section in the system settings.   
But it fails to position me on the map/retrieve my location.      
   
### My setup:   
- LineageOS 17.1   
- MicroG 0.2.17.204714 (All checks are ok)   
- MozillaUnifiedNlp Backend 1.4.0   
- Nominatim Geocoder Backend 1.2.2   
- App Manager 2.5.17   
- FakeGapps 2.0 (Xposed Module)   
- App Systemizer 17.3.1 (Magisk Module, all MicroG/Location apps moved to `/system/priv-app`)   
   
### The screwup:   
I initially used the 1-Click Ops to block all trackers, including system apps.
Then I proceeded to block parts of MicroG/MozillaUnifiedNlp/Nominatim.
This ended up breaking my location I believe.   
   
### I tried:
- Unblocking everything I blocked in App Manager for these apps (Activities, services, receivers, providers)   
- Resetting the `app ops` to default for these apps   
- Making sure the `uses permissions` sections had all location permissions enabled   
- Updating LineageOS to the latest version   
- Deleted the caches and data from MicroG/MozillaUnifiedNlp/Nominatim, uninstalled them, wiped dalvik & cache, reinstalled the whole MicroG/Location setup   
   
### My findings in App Manager:   
- Under microG Services Core's `uses permissions` section I could only see the `ACCESS_COARSE_LOCATION` option (enabled). The `ACCESS_BACKGROUND_LOCATION` and `ACCESS_FINE_LOCATION` options where gone (before I reinstalled everything), I added them back using `su` and  `pm grant com.google.android.gms android.permission.ACCESS_BACKGROUND_LOCATION` (and the equivalent for fine location) but this did not solve my issue. After the reinstall all 3 of these were automatically there and enabled.   
- Under microG Services Core's `app ops` section I can only see `(0) COARSE_LOCATION` (enabled) for operations that are related to locations. I assume that `(1) FINE_LOCATION` and `(2) GPS` have gone missing for this app? (However I'm unsure if they really are supposed to be there)   
- Under MozillaUnifiedNlp Backend's `uses permissions` section I can see all 3 above mentioned location permissions enabled.   
- Under MozillaUnifiedNlp Backend's `app ops` section I can only see `(0) COARSE_LOCATION` and `(1) FINE_LOCATION`  (both enabled) for operations that are related to locations. I assume that `(2) GPS` has gone missing for this app? (However again I'm unsure if it's really supposed to be there)   
   
### Question:   
How could I restore and enable these `app ops` that I assume to be missing? Or any suggestions for a fix? This is my main driver and I need my GPS back soon. Hopefully without having to reinstall everything.   
   
Ps: Love the app, finally I have the power to block trackers that come embedded in apps, thank you so much for this.

**Comment by MuntashirAkon** [comment]
> How could I restore and enable these `app ops` that I assume to be missing? Or any suggestions for a fix? This is my main driver and I need my GPS back soon. Hopefully without having to reinstall everything.

v2.5.17 is too old to know what went wrong. Try v2.5.20 (latest stable) or v2.5.22 (latest pre-release).

**Comment by Rikj000** [comment]
I uninstalled v2.5.17 and updated App Manager to v2.5.22-pre with SAI.   
   
With the new version I was able to restore some more location app ops and permissions.   
Mostly with the awesome new `+1 Set custom app op` feature.   
I also grabbed my older phone (LineageOS 16.0 + MicroG 0.2.11.202414) where the GPS/Location functionalities still work correctly and also installed the latest App Manager onto it so I could compare better with my newer phone.   
   
### My findings in App Manager:   
From this I learned that under MicroG Core Service's `app ops` section that the `(1) FINE_LOCATION` and `(2) GPS` toggles indeed have gone missing while they should be enabled there.   
However I was only able to re-add `(1) FINE_LOCATION` with the new `+1 Set custom app op` feature.   
I also noticed that it's missing `(42) MONITOR_HIGH_POWER_LOCATION` and `(41) MONITOR_LOCATION`, both of those I also can't re-add.   
   
Currently I remain unable to re-add the `(2) GPS`, `(42) MONITOR_HIGH_POWER_LOCATION` and `(41) MONITOR_LOCATION` app ops for MicroG Core Service which I assume will be needed to restore normal working functionality.   
   
### Worth to mention:   
- MozillaUnifiedNlp Backend's app ops and permissions seemed correct compared to my old phone.   
- I added the `(2) GPS` app op to LineageOS's `Fused Location`(com.android.location.fused), which doesn't appear to be there on my old phone so I think I added this one while it's not needed there and remain unsure on how to remove/restore it, however the app appears to be using it. I doubt that this would be the cause of the issue though? Since my GPS apps (Waze, PocketMaps, GPSTest) all also make use of this app op.

**Comment by Rikj000** [comment]
Copied the logcat exception when I try to add those app ops:   
01-24 09:48:49.891 E/InputDispatcher(3233): Window handle Window{1bd763c u0 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity} has no registered input channel.

**Comment by MuntashirAkon** [comment]
@Rikj000 When you set an app op to its default mode, it won't be displayed in the App Ops tab. It only displays the app ops that are, in some way, modified or the app has defined the corresponding permissions unless you choose to display the default app ops (ie. app ops with no associated permissions). The behaviour of app ops and permissions vary widely between operating system versions, and so is the total number of app ops (Android 10 has total 91 app ops ranging from 0 to 90).

**Comment by Rikj000** [comment]
Happy to say I resolved my issue and that it wasn't a bug in the app.   
   
I still was blocking some of the LineageOS/System App Ops relating location/settings saving.   
Once I unblocked those everything started working again!   
Sorry for my doubt!
