### ISSUE TITLE
Permissions changes Not sticking (reverting)

### ISSUE THREAD

**Issue by Dukyduk** [MuntashirAkon/AppManager#981]
### Describe the existing feature/documentation

Hi,

### Describe your problem(s)

I'm **trying to grant permissions** like ACCESS_RESTRICTED_SETTINGS (to a system app that keeps crashing) **but** when i press "refresh" it directly reverts back to the original.

I guess it works but something else reverts it back directly.

I'm wondering if there is some Conflicting samsung-system software that i could disable for AM to work..?

### Additional context

_Coming from :
Samsung S22 Ultra
Stock 
Rooted, Magisk 25.2_

**Comment by MuntashirAkon** [comment]
> I'm **trying to grant permissions** like ACCESS_RESTRICTED_SETTINGS (to a system app that keeps crashing) **but** when i press "refresh" it directly reverts back to the original.

Try using `pm grant ...` command to see what happens. However, there might be some peculiarities with this particular permission according to a user who was unable to grant this permission to an app. Later the problem was solved by reinstalling the app and granting the permission immediately. (There might also be a restart involved but I cannot remember the particulars.)

**Comment by kryptobolt200528** [comment]
> ### Describe the existing feature/documentation
> Hi,
> 
> ### Describe your problem(s)
> I'm **trying to grant permissions** like ACCESS_RESTRICTED_SETTINGS (to a system app that keeps crashing) **but** when i press "refresh" it directly reverts back to the original.
> 
> I guess it works but something else reverts it back directly.
> 
> I'm wondering if there is some Conflicting samsung-system software that i could disable for AM to work..?
> 
> ### Additional context
> _Coming from : Samsung S22 Ultra Stock Rooted, Magisk 25.2_

if you wouldn't mind what app were you trying to use?

**Comment by MuntashirAkon** [comment]
I'm closing this as OP seems to be unresponsive.
