### ISSUE TITLE
Edit system config

### ISSUE THREAD

**Issue by Mahantor** [MuntashirAkon/AppManager#982]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Please add a feature to edit system config
For example remove or add an app from allow in power save
![Screenshot_2023-01-24-23-14-49-234_io github muntashirakon AppManager-edit](https://user-images.githubusercontent.com/91434001/214395238-ad0bbfd0-e687-47de-ad1d-48f257181681.jpg)

**Comment by MuntashirAkon** [comment]
System configurations have been generated from hundreds of files located in partitions such as vendor and system, and they cannot be modified without a massive undertake which I am not in the position of doing.
