### ISSUE TITLE
Support for Shizuku for Unistalling apps and more

### ISSUE THREAD

**Issue by TISupe** [MuntashirAkon/AppManager#983]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

While uninstalling an app with AppManager, It opens the system's package manager prompt and if im uninstalling a "system app" it just with a notification for failed to uninstall "system app.

### Describe the solution you'd like

It would be better to use shizuku for installing and uninstalling apps, and maybe shizuku support as mode of operation.

### Additional context

Shizuku: https://github.com/RikkaApps/Shizuku

**Comment by MuntashirAkon** [comment]
Use ADB over TCP or Wireless debugging just as you would've used with Shizuku. See more on this issue in the docs: https://muntashirakon.github.io/AppManager/en/#subsec:faq:shizuku-support

**Comment by Werve** [comment]
I tried v3.1.4 Stable version with Fire TV 4K Max 2 Gen (Android 11) but both auto mode and ADB on TCP fall back to no-root.

Shizuku after two attempts with the 5555 option connected. 
![image](https://github.com/MuntashirAkon/AppManager/assets/13850028/56c71bc0-8b5a-4ba7-a325-8e9253338e51)


With the Fire TV 4K Max 1 Gen (Android 9) AppManager worked properly instead.
