### ISSUE TITLE
unable to open activity shortcut 

### ISSUE THREAD

**Issue by borderlinefancy** [MuntashirAkon/AppManager#985]
### Describe the existing feature/documentation

Using the shortcut feature, I'm able to create shortcuts for Activities for the Settings app. But only some shortcuts actually open. Some say "app isn't installed" when trying to open.

### Describe your problem(s)

I'm trying to create a activity shortcut for changing the refresh rate from the homescreen. I can launch the activity from the App Manager. But when I create a shortcut, I can't open it. I get the error "app isn't installed". 

I tried using Shortcut Maker (Rushikesh Kamewar) to create an activity shortcut for refresh rate and it works. When I open it, it opens. But when using the shortcut made with App Manager it says "app isn't installed". 

I looked deeper and found that the "action" in Interceptor has "android.intent.action.VIEW", when it should be "android.intent.action.MAIN". And that's why the shortcut maker one works and the app manager one doesn't work. When I change that the shortcut works but it also open the Interceptor every time I use the shortcut. How can I go about this? 

I already use App Manager for so many things. I would much prefer using it for shortcuts too. I don't want to download an extra app for that when the functionality already exists :(

### Additional context

This is one a asus zenfone 9

**Comment by MuntashirAkon** [comment]
This appears to be an issue rather than something that I can help you with. So, create a new issue using the bug report template as it does not include the required fields to understand the issue. Thanks.
