### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by instrumentum33** [MuntashirAkon/AppManager#989]
### Describe the existing feature/documentation

For now I want to uninstall the app m, but I am not able to.

**Comment by MuntashirAkon** [comment]
From the [community page](https://t.me/AppManagerCommunity/14):

> **Attempting to uninstall App Manager causes crash. How to fix?**
>
> In some variants of One UI and Lineage OS 17.1, attempting to uninstall App Manager might cause the Android installer to crash. This is a third-party issue and can’t be fixed from our side. However, it may still possible to uninstall App Manager in one of several ways:
> 
> 1. Ensure that Lineage OS 17.1 and OpenGapps are up-to-date.
> 2. Remove the SD Card before attempting to uninstall App Manager.
> 3. Clear all data or reset all permissions of App Manager, especially the usage stats permission.
> 4. Disabling App Manager also helped some One UI users to successfully uninstall App Manager. If you cannot disable, you can also try force-stopping the app.
> 5. Uninstall without clearing data. Use this as a last resort. If you are running App Manager in root or ADB mode, you can do this inside App Manager by navigating to the App Details page of the app. In other cases, you can either use root or ADB to run the following command:
>     ```
>     pm uninstall -k io.github.muntashirakon.AppManager
>     ```
> Samsung has a long history of paying no attention to issues and vulnerabilities. So, if you care about privacy, you should install a privacy-friendly ROM instead of One UI, and if you care about security, you should avoid buying Samsung devices altogether.
>
