### ISSUE TITLE
HELP: 4.3. Enable ADB mode on App Manager - No Toast Message?

### ISSUE THREAD

**Issue by 0pLuS0** [MuntashirAkon/AppManager#99]
**Describe the existing feature/documentation**

In the DOCS for 4.3;
https://muntashirakon.github.io/AppManager/guide/adb-over-tcp.html#_4-3-enable-adb-mode-on-app-manager

**Describe your problem(s)**
It mentions this about a Toast message;

After enabling ADB over TCP (in the previous subsections), open App Manager (AM). ```You should see working on ADB mode toast message at the bottom.```

I am not seeing any Toast message. I tried restarting AM, it still won't appear, I'm not sure what to do...

**Additional contexts**
Device: OnePlus 5T
Android: OxygenOS 9.0.11 Pie
Rooted: Magisk 20.4
Kernel: Franco Kernel r49

When I run ```./adb devices``` it shows it running on tcp.

./adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully

Then I run the tcpip command and it now shows this;

./adb tcpip 5555           
restarting in TCP mode port: 5555

**Comment by MuntashirAkon** [comment]
> I am not seeing any Toast message. I tried restarting AM, it still won't appear, I'm not sure what to do...

If you've given root permission to AM, ADB won't work as root as the highest priority. You can only get it working after denying root permission in the Magisk Manager.

**Comment by 0pLuS0** [comment]
Ok, I now see ```working on ADB mode```.

When I see ```working on ADB mode``` do I then enable AM in Magisk, or leave it disabled, because after I see the message ```working on ADB mode``` I see from Magisk saying app manager denied Superuser rights.

Also, so I understand correctly, to get Root access, we enable adb, then when done using AM, for security Stop adb server?

THANKS

**Comment by MuntashirAkon** [comment]
> Also, so I understand correctly, to get Root access, we enable adb, then when done using AM, for security Stop adb server?

If you have root, you don't need to worry about ADB at all. It's intended for non-root users only. If you're a root user and allow AM root access, AM will behave like any system app and have the same permissions.

> Root mode in the settings can't be used with ADB?

As I've said already, ADB over TCP is only for non-root users.

> It's confusing trying to understand what is giving better Root access, using Root access in the app and Magisk, or ADB?

ADB doesn't provide root access, Magisk does.

This is an interesting perspective, and I think I should clarify this in the documentation to prevent further confusion.

**Comment by 0pLuS0** [comment]
My device is rooted with Magisk, so that was the confusion on my part.

If my phone is rooted with Magisk do I still need to see the Toast Message at the bottom?

THANKS

**Comment by MuntashirAkon** [comment]
> If my phone is rooted with Magisk do I still need to see the Toast Message at the bottom?

No, ADB over TCP is only intended for non-root users.

**Comment by 0pLuS0** [comment]
I already understand the Root part, I just didn't know if the Toast message was releated to only adb, or if I was rooted, I'd still see it...

Thanks

**Comment by MuntashirAkon** [comment]
> I already understand the Root part, I just didn't know if the Toast message was releated to only adb, or if I was rooted, I'd still see it...

Ok, I'll add a tip for root users in that section to give it more clarity.

**Comment by 0pLuS0** [comment]
Sounds good, cause I was certainly confused... LOL
