### ISSUE TITLE
Add pm force-dex-opt for package(s)

### ISSUE THREAD

**Issue by tk2p** [MuntashirAkon/AppManager#992]
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Add an option to run a dexopt job on selected app(s)

Usage: `pm force-dex-opt PACKAGE`

### Describe the solution you'd like

Maybe add it to one click ops as well, the command for that is `pm bg-dexopt-job`

### Describe alternatives you've considered

I'm using termux atm for this but I believe it should be in a GUI because

a) people don't know about it
b) gui is more accessible 

### Additional context

Allows users to manually run dex2oat per on-app basis, useful for freshly installed/updated apps

p.s. android automatically runs this only when:

a) device is idle for 2 hours
b) device is fully charged (100%)

this basically forces you to charge overnight as that's the only period when your device can be 100% and idle for 2 hours (which is unhealthy for the battery)

also, taking into consideration that many people stopped overnight charging / charging their battery to 100% — this could really help

**Comment by MuntashirAkon** [comment]
I think, in addition to this, there should also be an option to set compiler filter such as `everything-profile`.

**Comment by MuntashirAkon** [comment]
Implemented via 491bbbfd40fdfc3cc0c2ac6ec46f735a300b3bf9
