### ISSUE TITLE
App Manager opens up every time when profile shortcut is used (ADB mode)

### ISSUE THREAD

**Issue by resiehnnes** [MuntashirAkon/AppManager#993]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Good day.

App Manager opens up every time when profile shortcut is used **if** it is available in recent apps list. I feel like this is intended behavior because it has to show up when doing certain tasks, and I can see it pops up for a split of a second when I run profile shortcuts and App Manager is closed (not in recent apps list), if so, I could tag this as 'Feature request' and see if there's any workaround  you could do to this issue.

Best regards,
resiehnnes

### Device info

- Device: Huawei P30 Pro
- OS Version: Android 10
- App Manager Version: 3.0.4 (416)
- Mode: ADB

**Comment by MuntashirAkon** [comment]
> App Manager opens up every time when profile shortcut is used **if** it is available in recent apps list.

You're right to assume that this shouldn't happen.

> I feel like this is intended behavior because it has to show up when doing certain tasks, and I can see it pops up for a split of a second when I run profile shortcuts and App Manager is closed (not in recent apps list), if so, I could tag this as 'Feature request' and see if there's any workaround you could do to this issue.

Every action in App Manager must happen via an activity, because:

1. The current mode of operation may require some user interaction
2. Screen lock might be enabled which means a prompt is needed to be displayed to unlock App Manager.

**Comment by MuntashirAkon** [comment]
This was fixed (but only for new shortcuts because of how shortcuts work).
