### ISSUE TITLE
Going to any app's "permissions" / "uses permissions" tab causes it to crash.

### ISSUE THREAD

**Issue by bagarwa** [MuntashirAkon/AppManager#994]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

In AppManager, when I go to any app's "permissions" or "uses permissions" tab, AppManager crashes and I get a notification to send the crash report to the developer. (which I did.)

### To Reproduce

1. Launch AppManager
2. Tap any app on the main screen. That app's details page opens.
3. Tap the "Permissions" or "Uses Permissions" tab at the top. 
4. AppManager crashes. 

### Expected behavior

Not crash. That app's permissions list should be shown.

### Logs

java.lang.NoClassDefFoundError: io.github.muntashirakon.AppManager.appops.AppOpsManager at io.github.muntashirakon.AppManager.details.AppDetailsFragment.permAppOp(appdetailsfragment.java:526) at io.github.muntashirakon.AppManager.details.AppDetailsFragment.access$1000(appdetailsfragment.java:99) at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getPermissionsView(appdetailsfragment.java:1047) at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(appdetailsfragment.java:696) at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(appdetailsfragment.java:530) at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(recyclerview.java:7254) at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(recyclerview.java:7337) at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(recyclerview.java:6194) at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(recyclerview.java:6460) at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(recyclerview.java:6300) at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(recyclerview.java:6296) at androidx.recyclerview.widget.LinearLayoutManager$[LayoutState.next](https://layoutstate.next/)(linearlayoutmanager.java:2330) at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(linearlayoutmanager.java:1631) at androidx.recyclerview.widget.LinearLayoutManager.fill(linearlayoutmanager.java:1591) at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(linearlayoutmanager.java:668) at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(recyclerview.java:4309) at androidx.recyclerview.widget.RecyclerView.dispatchLayout(recyclerview.java:4012) at androidx.recyclerview.widget.RecyclerView.onLayout(recyclerview.java:4578) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at android.widget.FrameLayout.layoutChildren(framelayout.java:332) at android.widget.FrameLayout.onLayout(framelayout.java:270) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at android.widget.RelativeLayout.onLayout(relativelayout.java:1103) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(swiperefreshlayout.java:688) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at androidx.viewpager.widget.ViewPager.onLayout(viewpager.java:1775) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(headerscrollingviewbehavior.java:149) at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(viewoffsetbehavior.java:43) at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(appbarlayout.java:2253) at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(coordinatorlayout.java:918) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at android.widget.FrameLayout.layoutChildren(framelayout.java:332) at android.widget.FrameLayout.onLayout(framelayout.java:270) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at android.widget.LinearLayout.setChildFrame(linearlayout.java:1891) at android.widget.LinearLayout.layoutVertical(linearlayout.java:1729) at android.widget.LinearLayout.onLayout(linearlayout.java:1638) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at android.widget.FrameLayout.layoutChildren(framelayout.java:332) at android.widget.FrameLayout.onLayout(framelayout.java:270) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at android.widget.LinearLayout.setChildFrame(linearlayout.java:1891) at android.widget.LinearLayout.layoutVertical(linearlayout.java:1729) at android.widget.LinearLayout.onLayout(linearlayout.java:1638) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at android.widget.FrameLayout.layoutChildren(framelayout.java:332) at android.widget.FrameLayout.onLayout(framelayout.java:270) at com.android.internal.policy.DecorView.onLayout(decorview.java:788) at android.view.View.layout(view.java:24071) at android.view.ViewGroup.layout(viewgroup.java:6421) at android.view.ViewRootImpl.performLayout(viewrootimpl.java:4144) at android.view.ViewRootImpl.performTraversals(viewrootimpl.java:3476) at android.view.ViewRootImpl.doTraversal(viewrootimpl.java:2358) at android.view.ViewRootImpl$[TraversalRunnable.run](https://traversalrunnable.run/)(viewrootimpl.java:9275) at android.view.Choreographer$[CallbackRecord.run](https://callbackrecord.run/)(choreographer.java:1236) at android.view.Choreographer$[CallbackRecord.run](https://callbackrecord.run/)(choreographer.java:1244) at android.view.Choreographer.doCallbacks(choreographer.java:899) at android.view.Choreographer.doFrame(choreographer.java:832) at android.view.Choreographer$[FrameDisplayEventReceiver.run](https://framedisplayeventreceiver.run/)(choreographer.java:1219) at android.os.Handler.handleCallback(handler.java:958) at android.os.Handler.dispatchMessage(handler.java:99) at android.os.Looper.loopOnce(looper.java:205) at android.os.Looper.loop(looper.java:294) at android.app.ActivityThread.main(activitythread.java:8052) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$[MethodAndArgsCaller.run](https://methodandargscaller.run/)(runtimeinit.java:578) at com.android.internal.os.ZygoteInit.main(zygoteinit.java:946) Caused by: java.lang.ExceptionInInitializerError at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.getPermissionItem(appdetailsviewmodel.java:1471) at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(appdetailsviewmodel.java:1438) at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$22$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(appdetailsviewmodel.java:917) at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$[ExternalSyntheticLambda35.run](https://externalsyntheticlambda35.run/)(Unknown Source:4) at java.util.concurrent.Executors$[RunnableAdapter.call](https://runnableadapter.call/)(executors.java:487) at [java.util.concurrent.FutureTask.run](https://java.util.concurrent.futuretask.run/)(futuretask.java:264) at java.util.concurrent.ThreadPoolExecutor.runWorker(threadpoolexecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$[Worker.run](https://worker.run/)(threadpoolexecutor.java:644) at [java.lang.Thread.run](https://java.lang.thread.run/)(thread.java:1012) Caused by: java.lang.IllegalStateException: sOpToSwitch length 121 should be 131 at io.github.muntashirakon.AppManager.appops.AppOpsManager.(appopsmanager.java:1748) at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.getPermissionItem(appdetailsviewmodel.java:1471) at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(appdetailsviewmodel.java:1438) at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$22$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:917) at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda35.run(Unknown Source:4) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487) at java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012) Device Info: App version: 3.1.0-beta01 App version code: 418 Android build version: 9542930 Android release version: 13 Android SDK version: 33 Android build ID: UPP1.230113.009 Device brand: google Device manufacturer: Google Device name: cheetah Device model: Pixel 7 Pro Device product name: cheetah_beta Device hardware name: cheetah ABIs: [arm64-v8a] ABIs (32bit): [] ABIs (64bit): [arm64-v8a] System language: en-US In-App Language: auto Mode: auto Inferred Mode: root

### Device info

- Device: Pixel 7 Pro
- OS Version: Android 14 DP1
- App Manager Version: 3.0.4
- Mode: Root

### Additional context

This crash happens only when the app actually has some permissions. If the app doesn't have / use any permission at all, then AppManager shows "No permission", instead of crashing.

**Comment by MuntashirAkon** [comment]
Fixed in 4c9e83d9e5ef70f7d7bd0a408105467b1ea9058f
