### ISSUE TITLE
AppManager not work properly on Android 13

### ISSUE THREAD

**Issue by Bladius2022** [MuntashirAkon/AppManager#996]
### Describe the existing feature/documentation

Does AppManager support Android 13?  Each version of this app randomly launches correctly.  However, it often hangs at the "Initialization in progress" stage and very often an error pops up that the program was unable to work in root mode despite the permissions granted.

**Comment by MuntashirAkon** [comment]
Submit an issue using the issue template.

**Comment by Bladius2022** [comment]
I have no idea what you are talking about.  I don't know how to do it or even how to log.  The program does not have the appropriate option or instructions for this, and I do not see it.  Tell me how to do it

**Comment by MuntashirAkon** [comment]
> I have no idea what you are talking about. I don't know how to do it or even how to log. The program does not have the appropriate option or instructions for this, and I do not see it. Tell me how to do it

Create an issue using [this template](https://github.com/MuntashirAkon/AppManager/issues/new?assignees=&labels=Bug&template=bug_report.yml), and make sure include include all the required information (marked with star).

**Comment by Bladius2022** [comment]
you did not understand.  I mean I don't know how to create a log in the program
