### ISSUE TITLE
App info page

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#999]
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

In beta update app info page take long time to load...

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by MuntashirAkon** [comment]
Fixed in 0c19ed30d1c51426e65c4a2810a5202c0ab1a985
